### ISSUE TITLE
err

### ISSUE THREAD

**Issue by PlexPt** [lss233/chatgpt-mirai-qq-bot#1]
File "bot.py", line 17
    async def to_thread(func, /, *args, **kwargs):
                              ^
SyntaxError: invalid syntax

**Comment by lss233** [comment]
请检查一下你的 Python 版本是不是 >= 3.9

**Comment by PlexPt** [comment]
3.7




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dark ***@***.***&gt;; 
发送时间: 2022年12月6日(星期二) 下午5:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lss233/chatgpt-mirai-qq-bot] err (Issue #1)





 
请检查一下你的 Python 版本是不是 &gt;= 3.9

**Comment by PlexPt** [comment]
可以做个docker镜像

**Comment by lss233** [comment]
好主意。您来个 PR？

**Comment by PlexPt** [comment]
你的python版本是

**Comment by lss233** [comment]
```bash
➜  ~ python3.9 -V
Python 3.9.5
```

**Comment by PlexPt** [comment]
让它教你
![image](https://user-images.githubusercontent.com/15922823/205878344-a52dc6ee-12ac-4581-86c6-0b09f5ec6947.png)

**Comment by PlexPt** [comment]
#2 #3

**Comment by lss233** [comment]
非常感谢！
