### ISSUE TITLE
mirai登录后仍然出现Websocket reconnecting.

### ISSUE THREAD

**Issue by woltium** [lss233/chatgpt-mirai-qq-bot#102]
chatgpt-qq-mirai-1    | 2023-02-12 08:38:08 I/main: 3 plugin(s) enabled.
chatgpt-qq-mirai-1    | 2023-02-12 08:38:08 I/main: Auto-login 2546518385, protocol: ANDROID_WATCH, heartbeatStrategy: STAT_HB
chatgpt-qq-mirai-1    | 2023-02-12 08:38:08 I/Bot.2546518385: Loaded account secrets from local cache.
chatgpt-qq-mirai-1    | 2023-02-12 08:38:08 I/Bot.2546518385: Saved account secrets to local cache for fast login.
chatgpt-qq-mirai-1    | 2023-02-12 08:38:08 I/Bot.2546518385: Login successful.
chatgpt-qq-mirai-1    | 2023-02-12 08:38:08 V/Bot.2546518385: Event: BotOnlineEvent(bot=Bot(2546518385))
chatgpt-qq-mirai-1    | 2023-02-12 08:38:08 I/Bot.2546518385: Bot login successful.
chatgpt-qq-mirai-1    | 2023-02-12 08:38:08 I/main: mirai-console started successfully.
chatgpt-qq-mirai-1    | > 2023-02-12 08:38:08 W/console: Closing input service...
chatgpt-qq-chatgpt-1  | 2023-02-12 08:38:11.352 | WARNING  | graia.ariadne.connection.ws:_:77 - Websocket reconnecting...
chatgpt-qq-chatgpt-1  | 2023-02-12 08:38:11.457 | INFO     | graia.ariadne.connection.ws:_:89 - Websocket connection closed
chatgpt-qq-chatgpt-1  | 2023-02-12 08:38:11.458 | WARNING  | graia.ariadne.connection.ws:_:75 - Websocket reconnecting in 5s...
chatgpt-qq-chatgpt-1  | 2023-02-12 08:38:16.458 | WARNING  | graia.ariadne.connection.ws:_:77 - Websocket reconnecting...
chatgpt-qq-chatgpt-1  | 2023-02-12 08:38:16.472 | INFO     | graia.ariadne.connection.ws:_:89 - Websocket connection closed
chatgpt-qq-chatgpt-1  | 2023-02-12 08:38:16.473 | WARNING  | graia.ariadne.connection.ws:_:75 - Websocket reconnecting in 5s...

在本机上跑的 配置没问题 使用代理、不使用代理都试过了还是不行

**Comment by lss233** [comment]
也许你忽略了这个步骤：https://github.com/lss233/chatgpt-mirai-qq-bot/wiki/%E4%BD%BF%E7%94%A8-Docker-Compose-%E9%83%A8%E7%BD%B2%EF%BC%88%E5%90%8C%E6%97%B6%E4%BD%BF%E7%94%A8-Mirai-%E5%92%8C-%E6%9C%AC%E9%A1%B9%E7%9B%AE%EF%BC%89#6-%E9%85%8D%E7%BD%AE%E6%9C%AC%E9%A1%B9%E7%9B%AE

**Comment by woltium** [comment]
[mirai]
qq = "myqq"

# 以下设置如果不了解，可以不用理会
api_key = "1234567890"
http_url = "http://mirai:8080"
ws_url = "http://mirai:8080"

我用的是api版本的自动部署脚本（2月12号更新的那个）
上面这些配置是自动生成了
（qq号去掉了

**Comment by lss233** [comment]
那上一步的配置呢？

**Comment by woltium** [comment]
```
adapters:
  - http
  - ws
debug: true
enableVerify: true
verifyKey: 123456789
singleMode: false
cacheSize: 4096
persistenceFactory: 'built-in'
adapterSettings:
  http:
    host: mirai
    port: 8080
    cors: ["*"]
  ws:
    host: mirai
    port: 8080
    reservedSyncId: -1
```

同样是脚本生成的 我没有改过

**Comment by lss233** [comment]
配置是没有问题的，除非你这里的 `myqq` 不是你实际上登录的那个QQ

> ```
> [mirai]
> qq = "myqq"
> 
> # 以下设置如果不了解，可以不用理会
> api_key = "1234567890"
> http_url = "http://mirai:8080"
> ws_url = "http://mirai:8080"
> ```
> 
> 我用的是api版本的自动部署脚本（2月12号更新的那个） 上面这些配置是自动生成了 （qq号去掉了

**Comment by woltium** [comment]
麻烦作者了
但是我重启之后仍然如此，重装之后仍然有问题
此外在用部署脚本部署好后第一次运行会提示配置文件错误，因为在之前让输入apikey的时候没带双引号，config文件里的也就没带双引号。
加上双引号后就开始报Websocket 的错
`[mirai]
qq = 2546518385

# 以下设置如果不了解，可以不用理会
api_key = "1234567890"
http_url = "http://mirai:8080"
ws_url = "http://mirai:8080"

[openai]
# 机器人情感值
temperature = 0.5
# API Key
api_key = "sk-....."
`

**Comment by lss233** [comment]
那就看一下  Mirai 启动阶段的日志吧，按说它会输出 mirai api http 的信息。

**Comment by deadnessking** [comment]
> ```
> adapters:
>   - http
>   - ws
> debug: true
> enableVerify: true
> verifyKey: 123456789
> singleMode: false
> cacheSize: 4096
> persistenceFactory: 'built-in'
> adapterSettings:
>   http:
>     host: mirai
>     port: 8080
>     cors: ["*"]
>   ws:
>     host: mirai
>     port: 8080
>     reservedSyncId: -1
> ```
> 
> 同样是脚本生成的 我没有改过

注意看api_key是1234567890，mirai设置的是123456789，少了一个0

**Comment by lss233** [comment]
> 注意看api_key是1234567890，mirai设置的是123456789，少了一个0

还是你细节

**Comment by woltium** [comment]
感谢 的确如此 此外自动部署脚本的默认使用的模型已经不能用了 得把docker-compose.yaml里的付费模型注释解掉才能成功运行
