### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by moiu93** [lss233/chatgpt-mirai-qq-bot#1023]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
根本聊不了，除了重置会话给个已重置，其它发什么都是出现故障

出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
原因：429 Too Many Requests {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/72690881/7d6e87ef-41ed-4b3b-93b3-05fbf301d14b)

**运行环境:**  
- 操作系统：Windows10
- 项目版本：Windows-quickstart-go-cqhttp-refs.tags.v2.5.2

**复现步骤**  
描述你是如何触发这个 BUG 的
配置完开始聊天就这样

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by JJTools** [comment]
你的API没钱了，说个啥。花钱买API。学我。3块钱一个，收了10个

**Comment by moiu93** [comment]
3.5不是一直免费吗，在官网也能正常用
以前配的mirai，用的就是api-key是正常的

**Comment by JJTools** [comment]
> 3.5不是一直免费吗，在官网也能正常用 以前配的mirai，用的就是api-key是正常的

API是有配额和时间限制的，默认5美刀，有效期在3个月。
如果使用量打，建议多买几个

**Comment by clark-2468** [comment]
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/39589318/89320ab0-d10d-4f60-a209-486c618db878)
有时候他们服务器出问题了也会429报错这样
我是账户上有他们24年1月送的余额
我还挂着银行卡的我不可能没钱
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/39589318/447ae842-339e-4fe7-8ad4-4932bebe8e54)
