### ISSUE TITLE
[BUG] 接入点项目已更新，更新后账号密码登录路径改变

### ISSUE THREAD

**Issue by Nothingness-Void** [lss233/chatgpt-mirai-qq-bot#1027]
https://github.com/linweiyuan/go-chatgpt-api
这个项目最近更新了，把接入点的结构改了
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/55913486/dc3eff08-27bd-4abe-bfb9-2e6fa028cfbb)
之前是xxx/chatgpt/
现在在后边多加了一个/backend-api/
之前账号密码登录是直接访问/login/，现在账号密码登录不能直接访问/login/了
这样就没办法用账号密码登录了

**Comment by Haibersut** [comment]
需要账号密码登录的话可以在此处修改
https://github.com/lss233/chatgpt-mirai-qq-bot/blob/11081c4d6089b4b3ead624a3fc74c8c4c24daa89/manager/bot.py#L500

**Comment by Nothingness-Void** [comment]
> 需要账号密码登录的话可以在此处修改
> 
> https://github.com/lss233/chatgpt-mirai-qq-bot/blob/11081c4d6089b4b3ead624a3fc74c8c4c24daa89/manager/bot.py#L500

感谢回复，已联系接入点作者进行修改了
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/55913486/c14dd4e4-e44d-44ca-a476-2919283d3a19)
