### ISSUE TITLE
[BUG] 程序无法退出

### ISSUE THREAD

**Issue by jiaigo** [lss233/chatgpt-mirai-qq-bot#1039]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
1. 无法 Ctrl+C 退出，请问是什么原因，是否与creart创建的loop有关
2. 图2的loop.run_forever() 注释后也是一样无法 Ctrl+C 退出

**截图**  
![微信截图_20230710112055](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/42903140/1d38607d-7d4f-4010-ab34-c7092d045919)
![微信截图_20230710112215](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/42903140/4b1208a1-feb6-4d8b-92c2-f23609df344c)

**Comment by Haibersut** [comment]
http模式下的已知问题

**Comment by Haibersut** [comment]
目前缓解措施如下：
将bot.py中的hook()调整到`loop.run_until_complete(asyncio.gather(*bots))`前
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/117586514/2eae83bc-85bb-4e5f-9999-7bc72b4c58bd)

然后在utils文件夹的exithooks.py中，开头导入
`import os`
`from constants import config`
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/117586514/e3a62b32-15b4-4527-bc76-6912b4b0eeaa)

然后修改exit_gracefully函数
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/117586514/4372b271-6830-4390-8d02-719fb66efa38)

在出现
**2023-07-10 21:11:21.875 | INFO     | __main__:<module>:54 - [Edge TTS] 读取成功！**
后即可随时关闭。

**Comment by Haibersut** [comment]
看错了，hook加在try前面好一些
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/117586514/add7a5c6-5a89-4c53-95f6-7abadfca8d17)

**Comment by jiaigo** [comment]
有两点疑问：
1. 从调整的顺序来看，如何理解hook与loop.create_task，loop.run_until_complete之间的关系，个人测试creat_task -> run_until_complete -> hook -> run_until_complete是可以进入exit_grace函数的，但期待一个合理的解释
2. 关于sys.exit和os._exit，后者无释放资源 (如线程锁)，强制退出，前者会陷入lock释放的死循环，不知可否考虑优化前者，而不是暴力退出😀

**Comment by Haibersut** [comment]
理论上来说，hook函数在 bot.py 中的位置决定了何时开始捕获sigint信号，但是尝试下来放在全部启动完成后可以正常关闭http服务，所以也就是个经验，所以很迷惑的就是不知道为什么放在最开始不行

由于http服务不是我写的，我要看一下才能知道，可能是监听或者开了别的线程的问题

暴力退出剩下的交给操作系统（bushi

**Comment by Haibersut** [comment]
看起来是因为多开了几个别的线程导致信号无法给到全部线程

开启HTTP后
![0 KX}DUE{)07`I%30C@G{ U](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/117586514/450b3a94-0ff1-496e-a6fa-a1c777f77861)

未开启HTTP
![)8 3_NE3H`_FSZ06N6{9~B6](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/117586514/21a4f8a3-2f6d-42af-a864-ad4130d546c8)

**Comment by jiaigo** [comment]
> 理论上来说，hook函数在 bot.py 中的位置决定了何时开始捕获sigint信号，但是尝试下来放在全部启动完成后可以正常关闭http服务，所以也就是个经验，所以很迷惑的就是不知道为什么放在最开始不行
> 
> 由于http服务不是我写的，我要看一下才能知道，可能是监听或者开了别的线程的问题
> 
> 暴力退出剩下的交给操作系统（bushi

你可以试试将edeg_tts那段注释，一样无法exit，就算是放在启动http服务前面那行
