### ISSUE TITLE
[HELP]甲骨文arm执行第七步 启动 docker-compose up时报错

### ISSUE THREAD

**Issue by cx99325** [lss233/chatgpt-mirai-qq-bot#105]
root@jp2:~/chatgpt-mirai-qq-bot# docker-compose up

Pulling chatgpt (lss233/chatgpt-mirai-qq-bot:v1.5.3)...
v1.5.3: Pulling from lss233/chatgpt-mirai-qq-bot
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

请问是没有适配arm机器吗

**Comment by lss233** [comment]
要养成先看 issue 再提 issue 的习惯。
甲骨文的 IP 已经被封干净了，不值得试了。  
#81

**Comment by cx99325** [comment]
抱歉耽误大佬时间，我看了issue，但是因为不是一个步骤的报错哈，我就又提了一个。IP倒是可以套vpn解决

**Comment by lss233** [comment]
#81 现在已经提供了解决方法
