### ISSUE TITLE
[BUG] 重置会话后报错：cannot access local variable 'completion_text' where it is not associated with a value

### ISSUE THREAD

**Issue by zhuddd** [lss233/chatgpt-mirai-qq-bot#1053]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [o] 我已看过其他 issue，他们不能解决我的问题 
- [o] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
重置会话后报错：cannot access local variable 'completion_text' where it is not associated with a value

**运行环境:**  
- 操作系统：![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/40013519/62b2f609-c92f-45af-a925-1bcdd8ad0087)
- Docker： Docker version 24.0.2, build cb74dfc
- 项目版本：![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/40013519/78ef7718-8b7a-452c-9772-40e767092f48)

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 正常发送消息，机器人正常回答
2. 发送重置会话，
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/40013519/10613e86-0697-4b6b-b171-9b46a609511b)

3. 正常发送消息，出现报错
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/40013519/5917a454-5a8b-43b0-b350-aa6bac7619d0)

**预期行为**  
正常正常回复

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
该bug针对单个用户发送“重置会话”后出现，即用户a触发bug后，用户b或群聊不受影响

**Comment by nonotouchtouch** [comment]
我也出现了这个问题，但是并没有重置会话，周四用的好的，今天用不了了。报错相同。

**Comment by Haibersut** [comment]
你看你api请求用的None模型，选一个正常的

**Comment by zhuddd** [comment]
> 你看你api请求用的None模型，选一个正常的

none模型是在重置会话后自动切过去的，手动切回3.5模型后依然会报这个错误

**Comment by Haibersut** [comment]
> > 你看你api请求用的None模型，选一个正常的
> 
> none模型是在重置会话后自动切过去的，手动切回3.5模型后依然会报这个错误

你拉一下最新的docker看看，我这里是复现不出来
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/117586514/fc885ee4-46ea-4f33-8397-7da5f7207be3)

**Comment by zhuddd** [comment]
> > > 你看你api请求用的None模型，选一个正常的
> > 
> > 
> > none模型是在重置会话后自动切过去的，手动切回3.5模型后依然会报这个错误
> 
> 你拉一下最新的docker看看，我这里是复现不出来 ![image](https://user-images.githubusercontent.com/117586514/253805907-fc885ee4-46ea-4f33-8397-7da5f7207be3.png)
重新部署机器人后依然有问题，都是使用的GO-CQHTTP 版。我是使用win版登录qq后，获取session.token后复制到服务器登录的，
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/40013519/cbc802dc-1813-439e-9275-b7497279ac7d)

**Comment by zhuddd** [comment]
测试1
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/40013519/1b17cdc6-8790-4d91-bb4f-aa283a324fbb)
![new ducument](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/40013519/8fa1bb42-a6af-4ac7-9917-3e679b423b4b)

**Comment by zhuddd** [comment]
测试1
![new ducument](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/40013519/806b5b3f-e7f3-4e1a-ae37-d1937ea224a3)

![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/40013519/13f20307-2a45-40ff-b440-b84132f95e73)

**Comment by zhuddd** [comment]
测试2
![new ducument](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/40013519/98e333ff-67c5-44d3-8d91-0cabd492089b)
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/40013519/3c016139-2fb6-4322-8be0-5eabaa33cf02)

**Comment by zhuddd** [comment]
目前的情况是在重置会话之后：立马切换模型就不会报错，如果重置会话和切换模型之间有其他对话就会报错 @Haibersut

**Comment by Haibersut** [comment]
了解了，你可以试试在config中的openai.accounts加上model的参数
```
[openai]
api_endpoint = "xxxx"

[[openai.accounts]]
# # 你的 API key，可以在这里看： https://platform.openai.com/account/api-keys
api_key="xxxx"
model="gpt-3.5-turbo"
```

虽说我还是建议你检查一下docker镜像，我确实是无法复现你的情况（
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/117586514/87b92f77-cc2a-4115-bfc0-27581e3f86f0)

**Comment by zhuddd** [comment]
> 加上model的参数后暂时不会报错了，感谢帮助

**Comment by zhuddd** [comment]
> 了解了，你可以试试在config中的openai.accounts加上model的参数
> 
> ```
> [openai]
> api_endpoint = "xxxx"
> 
> [[openai.accounts]]
> # # 你的 API key，可以在这里看： https://platform.openai.com/account/api-keys
> api_key="xxxx"
> model="gpt-3.5-turbo"
> ```
> 
> 虽说我还是建议你检查一下docker镜像，我确实是无法复现你的情况（ ![image](https://user-images.githubusercontent.com/117586514/253841936-87b92f77-cc2a-4115-bfc0-27581e3f86f0.png)

加上model的参数后暂时不会报错了，感谢帮助
