### ISSUE TITLE
[BUG] <Bard> 报错 "list index out of range"

### ISSUE THREAD

**Issue by gebederry** [lss233/chatgpt-mirai-qq-bot#1054]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
佬。切换至 Bard 后，发送消息报错 "list index out of range"。

**运行环境:**  
- 操作系统：linux
- Docker： 否
- 项目版本：v2.5.2

**截图**  
![bard-issue](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/3938353/a30b39da-cf67-4d03-95d3-c8d94b869aaa)

**Comment by linxp001** [comment]
我说一下解决办法吧，因为我有两个账号，一个行一个不行，我就对比了一下两个账号的cookie，发现有一个SSID属性不太一样，出问题的cookie的SSID长度比较短，所以我就在F12的cookie详细内容里重新找到了这个SSID，发现是一个比较长的值，替换了这个SSID的值就好了。

**Comment by gebederry** [comment]
> 我说一下解决办法吧，因为我有两个账号，一个行一个不行，我就对比了一下两个账号的cookie，发现有一个SSID属性不太一样，出问题的cookie的SSID长度比较短，所以我就在F12的cookie详细内容里重新找到了这个SSID，发现是一个比较长的值，替换了这个SSID的值就好了。

感谢分享经验。今天受了你的启发，也试着查了查 cookie。发现 chrome 取得的 cookie 有效，firefox 取得的 cookie 无效。之前用的是小号的 cookie，在 firefox 上登录并获取的。chrome 取得的 cookie 比 firefox 的 cookie 多了几组键值对。

**Comment by linxp001** [comment]
有道理，看来火狐获取cookie不靠谱，我一直用火狐获取的，第一个账号没事儿，第二个账号就出错了。

**Comment by gebederry** [comment]
附个图，供大佬们日后参详
![chrome_firefox_cookie](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/3938353/29be0ffc-9339-4783-842a-adcc0720aeb4)

**Comment by Nothingness-Void** [comment]
> 附个图，供大佬们日后参详 ![chrome_firefox_cookie](https://user-images.githubusercontent.com/3938353/255810705-29be0ffc-9339-4783-842a-adcc0720aeb4.png)
大佬我看你左边这个有22组值，但是我用corome获取的cookie只有10多组值

**Comment by gebederry** [comment]
> > 附个图，供大佬们日后参详 ![chrome_firefox_cookie](https://user-images.githubusercontent.com/3938353/255810705-29be0ffc-9339-4783-842a-adcc0720aeb4.png)
> > 大佬我看你左边这个有22组值，但是我用corome获取的cookie只有10多组值

不明白的地方就在这了..

**Comment by Nothingness-Void** [comment]
> > > 大佬我看你左边这个有22组值，但是我用corome获取的cookie只有10多组值
> 
> 不明白的地方就在这了..

我用edge和Chrome都试了，全都是报错，用不了

**Comment by taoj1114** [comment]
通过在console输入命令 `document.cookie` 获取的cookie ，目前使用没有问题
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/96367675/64fec16e-1a6c-43d3-954c-fa38cf82aa1b)

**Comment by taoj1114** [comment]
我在这个地方获取的cookie，刷新了三次所获得的值都可以用，不知道是不是巧合。
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/96367675/43699c66-1957-4901-819f-80f57e0f1f3a)

**Comment by thomashooo** [comment]
这个token过一会就失效报这个错，大家都这样吗，有好的解决办法吗
