### ISSUE TITLE
gpt接入点，解决风控，cod45，237，238。程序code500报错

### ISSUE THREAD

**Issue by alancu** [lss233/chatgpt-mirai-qq-bot#1055]
## 🍳临时可用CHAT接入点，随时**跑路**
```plaintext
browserless_endpoint = "https://chat.alanx.cn/" #web

api_endpoint = "https://api.alanx.cn/v1"        #api
```

运行状态
https://run.alanx.cn/

## 🍸快速搭建qq签名服务，需要注册抱脸账号
https://github.com/alancu/qqsign

**Comment by lIlIlllllmeng** [comment]
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/94682166/023154cc-9c8e-4ccc-be69-e48c1be63403)
 没有配置对导致的？

**Comment by lIlIlllllmeng** [comment]
谢谢大佬，已经可以登录了：）

**Comment by yanqing8** [comment]
谢谢大佬，已经可以登录了：）

**Comment by yanqing8** [comment]
browserless_endpoint = "https://chat.alanx.cn/" #web

api_endpoint = "https://api.alanx.cn/v1"        #api

大佬，这个接入点有搭建教程嘛

**Comment by alancu** [comment]
跑路了，接入点不能使用了
