### ISSUE TITLE
[BUG] 其他全部正常但是响应消息为空

### ISSUE THREAD

**Issue by KCenove** [lss233/chatgpt-mirai-qq-bot#1071]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
其他全部正常但是响应消息为空

**运行环境:**  
- 操作系统：Centos8
- Docker： 24.0.4
- 项目版本：2.5.2

**复现步骤**  
正常配置后出现这个问题

**预期行为**  
返回gpt3.5生成的内容

**截图**  
![截图](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/136214077/9b732ebb-32f5-440b-96a2-29bfe1ee298e)

**其他内容**  
无

**Comment by Haibersut** [comment]
请检查你的apikey是否正常

**Comment by KCenove** [comment]
> 请检查你的apikey是否正常

apikey没问题，而且从openai官网能看到最后使用时间的变化。

**Comment by Haibersut** [comment]
> > 请检查你的apikey是否正常
> 
> apikey没问题，而且从openai官网能看到最后使用时间的变化。

在运行bot的电脑上，你curl请求没问题吗

**Comment by KCenove** [comment]
> > > 请检查你的apikey是否正常
> > 
> > 
> > apikey没问题，而且从openai官网能看到最后使用时间的变化。
> 
> 在运行bot的电脑上，你curl请求没问题吗

没问题

**Comment by Haibersut** [comment]
你拉一下最新的镜像，然后再试试

**Comment by KCenove** [comment]
> 你拉一下最新的镜像，然后再试试

就是最新的。。。
我再试试去吧，不行的话换别的项目看看。
谢谢啦

**Comment by Haibersut** [comment]
> > 你拉一下最新的镜像，然后再试试
> 
> 就是最新的。。。 我再试试去吧，不行的话换别的项目看看。 谢谢啦

刚才更新了一些，你现在的应该不是最新的了

**Comment by KCenove** [comment]
> > > 你拉一下最新的镜像，然后再试试
> > 
> > 
> > 就是最新的。。。 我再试试去吧，不行的话换别的项目看看。 谢谢啦
> 
> 刚才更新了一些，你现在的应该不是最新的了

ok我看看去

**Comment by Haibersut** [comment]
怎么说（

**Comment by AirOxO** [comment]
> 怎么说（

我也遇到同样的问题 刚刚更新过了.. 也是其他都正常 但是QQ回不了消息 网页端GPT能看到问题正常回答 后台也正常 但就是回复不了消息

**Comment by Haibersut** [comment]
> > 怎么说（
> 
> 我也遇到同样的问题 刚刚更新过了.. 也是其他都正常 但是QQ回不了消息 网页端GPT能看到问题正常回答 后台也正常 但就是回复不了消息

这个是api请求的，web的不太清楚，可能revChatGPT这个库还有点问题

**Comment by Haibersut** [comment]
> > 怎么说（
> 
> 我也遇到同样的问题 刚刚更新过了.. 也是其他都正常 但是QQ回不了消息 网页端GPT能看到问题正常回答 后台也正常 但就是回复不了消息

看看你的日记，是不是风控了

**Comment by KCenove** [comment]
> > 怎么说（
> 
> 我也遇到同样的问题 刚刚更新过了.. 也是其他都正常 但是QQ回不了消息 网页端GPT能看到问题正常回答 后台也正常 但就是回复不了消息

我的问题和你不一样。我这个后台也看不到正常回答。

**Comment by KCenove** [comment]
> > > 你拉一下最新的镜像，然后再试试
> > 
> > 
> > 就是最新的。。。 我再试试去吧，不行的话换别的项目看看。 谢谢啦
> 
> 刚才更新了一些，你现在的应该不是最新的了 ![image](https://user-images.githubusercontent.com/117586514/255134293-f20ef57e-8c85-4caf-b5aa-401426ed7312.png)

还是没用。我换个服务器试试，说不定真是网络的问题

**Comment by Haibersut** [comment]
> > > > 你拉一下最新的镜像，然后再试试
> > > 
> > > 
> > > 就是最新的。。。 我再试试去吧，不行的话换别的项目看看。 谢谢啦
> > 
> > 
> > 刚才更新了一些，你现在的应该不是最新的了 ![image](https://user-images.githubusercontent.com/117586514/255134293-f20ef57e-8c85-4caf-b5aa-401426ed7312.png)
> 
> 还是没用。我换个服务器试试，说不定真是网络的问题

你发一下完整的日记我看看，从开始到请求

**Comment by KCenove** [comment]
> > > > > 你拉一下最新的镜像，然后再试试
> > > > 
> > > > 
> > > > 就是最新的。。。 我再试试去吧，不行的话换别的项目看看。 谢谢啦
> > > 
> > > 
> > > 刚才更新了一些，你现在的应该不是最新的了 ![image](https://user-images.githubusercontent.com/117586514/255134293-f20ef57e-8c85-4caf-b5aa-401426ed7312.png)
> > 
> > 
> > 还是没用。我换个服务器试试，说不定真是网络的问题
> 
> 你发一下完整的日记我看看，从开始到请求

我换了个服务器，然后现在可以有回复了，但是回复是报错

**Comment by Haibersut** [comment]
看下完整的日记我才好知道（

**Comment by KCenove** [comment]
> 看下完整的日记我才好知道（

我知道了。是api没钱了...

**Comment by KCenove** [comment]
> > > > > > 你拉一下最新的镜像，然后再试试
> > > > > 
> > > > > 
> > > > > 就是最新的。。。 我再试试去吧，不行的话换别的项目看看。 谢谢啦
> > > > 
> > > > 
> > > > 刚才更新了一些，你现在的应该不是最新的了 ![image](https://user-images.githubusercontent.com/117586514/255134293-f20ef57e-8c85-4caf-b5aa-401426ed7312.png)
> > > 
> > > 
> > > 还是没用。我换个服务器试试，说不定真是网络的问题
> > 
> > 
> > 你发一下完整的日记我看看，从开始到请求
> 
> 我换了个服务器，然后现在可以有回复了，但是回复是报错


> > > > > > 你拉一下最新的镜像，然后再试试
> > > > > 
> > > > > 
> > > > > 就是最新的。。。 我再试试去吧，不行的话换别的项目看看。 谢谢啦
> > > > 
> > > > 
> > > > 刚才更新了一些，你现在的应该不是最新的了 ![image](https://user-images.githubusercontent.com/117586514/255134293-f20ef57e-8c85-4caf-b5aa-401426ed7312.png)
> > > 
> > > 
> > > 还是没用。我换个服务器试试，说不定真是网络的问题
> > 
> > 
> > 你发一下完整的日记我看看，从开始到请求
> 
> 我换了个服务器，然后现在可以有回复了，但是回复是报错

报错就是因为那个key没钱了，我换了个有余额的apikey，然后在这台服务器就可以用了。
但是在原来那台服务器上还是不行，应该是网络原因吧。

**Comment by Haibersut** [comment]
怎么说我也得看看日记才能知道（
