### ISSUE TITLE
[BUG] 使用bing报错：InvalidRequest: Culture is not supported. (Parameter 'name') Chinese (Simplified)-China is an invalid culture identifier.

### ISSUE THREAD

**Issue by weilai-ke-qi** [lss233/chatgpt-mirai-qq-bot#1093]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：windows 11 dev：23511
- Docker： ？
- 项目版本：v2.5.2

**复现步骤**  
描述你是如何触发这个 BUG 的
应该是每当用中文和它说话时，如何它用到搜索了就会报错

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/128122996/390943f6-b134-48b8-8870-a1f546f2d6b3)
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/128122996/c02b30d5-f386-4e0b-8c67-1b60d68b0767)
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/128122996/63fd4d5d-64eb-4ad1-8365-a094bb76f9b0)
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/128122996/1369ea61-aa68-4242-8f39-a1b6e56367d4)
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/128122996/e2d6dd98-3348-49cb-baf4-d20127324b0d)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by Haibersut** [comment]
参考
https://github.com/lss233/chatgpt-mirai-qq-bot/issues/942

**Comment by weilai-ke-qi** [comment]
> 参考 #942

谢，已解决
