### ISSUE TITLE
[BUG] docker-compose启动程序以后 报错502

### ISSUE THREAD

**Issue by codeses** [lss233/chatgpt-mirai-qq-bot#110]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ x] 我已看过其他 issue，他们不能解决我的问题 
- [x ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
使用docker-compose 的proxy方式登录以后，日志里面提示Successfully got session key，
但是发送消息以后，日志里面报错502.
![image](https://user-images.githubusercontent.com/58210554/218408433-5b343762-5247-4606-a9a6-8980002710b8.png)

**运行环境:**  
- 操作系统：debian
- Docker： 20.10.21, build baeda1f
- 项目版本: v1.5.4

**截图**  
![image](https://user-images.githubusercontent.com/58210554/218408433-5b343762-5247-4606-a9a6-8980002710b8.png)

**其他内容**

**Comment by lss233** [comment]
#108 已解决。
