### ISSUE TITLE
运行成功，但是发信息不回复

### ISSUE THREAD

**Issue by tinygeeker** [lss233/chatgpt-mirai-qq-bot#111]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
`启动ChatGPT.cmd` 脚本执行登录成功
`启动Mirai.cmd` 脚本执行成功，通过 `login 账号 密码` 登录机器人账号成功

给机器人发送信息能收到，但是不回复。

**运行环境:**  
- 操作系统：window
- 项目版本：[Windows-quickstart-refs.tags.v1.5.4.zip](https://github.com/lss233/chatgpt-mirai-qq-bot/releases/download/v1.5.4/Windows-quickstart-refs.tags.v1.5.4.zip)

**预期行为**  
给机器人发消息，应该回复

**截图**  
![W{A6JCS4XZM0 2KHCBF{OT](https://user-images.githubusercontent.com/35004749/218443979-afa77149-5f9c-4bc4-a620-d20358f16315.png)

**Comment by Ou-Rui** [comment]
我也遇到了同样的问题

**Comment by xmengweb** [comment]
![image](https://user-images.githubusercontent.com/78428475/218457931-5ee347ea-bda9-46b1-ac91-c91a5960cd5a.png)
同样

**Comment by licat233** [comment]
我的昨天晚上session突然掉了，我猜大概是网页版靠session鉴权的方法已经被官方和谐了，先换成api版本吧，网页版需要等作者修复

**Comment by BH2TYQ** [comment]
> **提交 issue 前，请先确认：**
> 
> * [x]  我已看过 **FAQ**，此问题不在列表中
> * [ ]  我已看过其他 issue，他们不能解决我的问题
> * [ ]  我认为这不是 Mirai 或者 OpenAI 的 BUG
> 
> **表现** `启动ChatGPT.cmd` 脚本执行登录成功 `启动Mirai.cmd` 脚本执行成功，通过 `login 账号 密码` 登录机器人账号成功
> 
> 给机器人发送信息能收到，但是不回复。
> 
> **运行环境:**
> 
> * 操作系统：window
> * 项目版本：[Windows-quickstart-refs.tags.v1.5.4.zip](https://github.com/lss233/chatgpt-mirai-qq-bot/releases/download/v1.5.4/Windows-quickstart-refs.tags.v1.5.4.zip)
> 
> **预期行为** 给机器人发消息，应该回复
> 
> **截图** ![W{A6JCS4XZM0 2KHCBF{OT](https://user-images.githubusercontent.com/35004749/218443979-afa77149-5f9c-4bc4-a620-d20358f16315.png)

你这个没有登陆成功OpenAI

**Comment by lss233** [comment]
浏览器验证似乎不可用了。将会在 #108 解决。
