### ISSUE TITLE
Linux部署网页版，最后卡在“Found Session Token!"

### ISSUE THREAD

**Issue by yfangz22** [lss233/chatgpt-mirai-qq-bot#113]
运行bot后，卡在Found Session Token!. (打开的chrome网页不会自己关掉）一直进不到Login successful命令行。
下面是借用了常见问题的截图。
![Inked屏幕截图 2023-02-13 181155](https://user-images.githubusercontent.com/49287247/218595867-bb1362e2-ecbd-4822-8258-1359da10cf69.jpg)

**Comment by lss233** [comment]
使用最新版，不要用旧版。
