### ISSUE TITLE
[BUG] 安装失败 缺少 asyncio.events:AbstractEventLoop

### ISSUE THREAD

**Issue by xfrqh** [lss233/chatgpt-mirai-qq-bot#1133]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
程序因为异常退出。报错信息：current environment does not contain support for asyncio.events:AbstractEventLoop

**运行环境:**  
- 操作系统：Windows 10 专业版
- 项目版本：v2.5.3 go

**复现步骤**  
1.解压"Windows-quickstart-go-cqhttp-refs.tags.v2.5.3.zip"，运行“初始化.cmd”，完成初始化。
2.运行“chatgpt-installer.exe”
3.报错 "current environment does not contain support for asyncio.events:AbstractEventLoop"

**预期行为**  
正常开启 chatgpt-mirai-qq-bot

**截图**  
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/73733485/1e057573-4d7b-499f-bd42-4c6ac651f98c)

[2023-08-07 18:34:58.989] [info] 请选择项目源：1. 官方源 2. 镜像源
[2023-08-07 18:34:58.990] [info] 一般项目源选择官方源即可，如果下不下来可以选择镜像源
2
[2023-08-07 18:35:07.443] [info] 已选择镜像源
[2023-08-07 18:35:07.457] [info] 请选择PIP下载源：1. 官方源 2. 镜像源
[2023-08-07 18:35:07.490] [info] 一般项目源选择镜像源，如果需要更新的话则选择官方源
2
[2023-08-07 18:35:08.314] [info] 已选择镜像源
[2023-08-07 18:35:15.980] [info] CHATGPT环境已存在
[2023-08-07 18:35:16.085] [info] 检查项目版本
error: Your local changes to the following files would be overwritten by merge:
        requirements.txt
Please commit your changes or stash them before you merge.
Aborting
Updating 757eac9..81402da
[2023-08-07 18:35:20.137] [info] 开始安装依赖
[2023-08-07 18:35:20.139] [info] 当前PIP镜像源是：https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: graia-ariadne==0.11.5 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 1)) (0.11.5)
Requirement already satisfied: graiax-silkcoder in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 2)) (0.3.6)
Requirement already satisfied: revChatGPT~=6.8.6 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 3)) (6.8.6)
Requirement already satisfied: toml~=0.10.2 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 4)) (0.10.2)
Requirement already satisfied: Pillow>=9.3.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 5)) (10.0.0)
Requirement already satisfied: tinydb~=4.8.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 6)) (4.8.0)
Requirement already satisfied: loguru~=0.7.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 8)) (0.7.0)
Requirement already satisfied: asyncio~=3.4.3 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 9)) (3.4.3)
Requirement already satisfied: pydantic in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 10)) (1.10.12)
Requirement already satisfied: markdown~=3.4.3 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 12)) (3.4.4)
Requirement already satisfied: python-markdown-math~=0.8 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 13)) (0.8)
Requirement already satisfied: pygments~=2.15.1 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 14)) (2.15.1)
Requirement already satisfied: imgkit~=1.2.3 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 15)) (1.2.3)
Requirement already satisfied: qrcode~=7.4.2 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 16)) (7.4.2)
Requirement already satisfied: openai~=0.27.8 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 17)) (0.27.8)
Requirement already satisfied: EdgeGPT==0.12.1 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 18)) (0.12.1)
Requirement already satisfied: aiohttp~=3.8.5 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 19)) (3.8.5)
Requirement already satisfied: OpenAIAuth>=2.0.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 20)) (3.0.0)
Requirement already satisfied: urllib3~=2.0.4 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 21)) (2.0.4)
Requirement already satisfied: BingImageCreator~=0.4.2 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 22)) (0.4.4)
Requirement already satisfied: poe-api==0.5.2 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 23)) (0.5.2)
Requirement already satisfied: requests~=2.31.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 24)) (2.31.0)
Requirement already satisfied: uuid~=1.30 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 25)) (1.30)
Requirement already satisfied: python-telegram-bot==20.4 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 27)) (20.4)
Requirement already satisfied: aiocqhttp~=1.4.4 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 28)) (1.4.4)
Requirement already satisfied: tls-client in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 29)) (0.2.1)
Requirement already satisfied: python-dateutil~=2.8.2 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 30)) (2.8.2)
Requirement already satisfied: discord.py in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 31)) (2.3.1)
Requirement already satisfied: azure-cognitiveservices-speech in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 32)) (1.31.0)
Requirement already satisfied: regex~=2023.6.3 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 35)) (2023.6.3)
Requirement already satisfied: httpx~=0.24.1 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 36)) (0.24.1)
Requirement already satisfied: Quart==0.17.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 37)) (0.17.0)
Requirement already satisfied: edge-tts in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 39)) (6.1.7)
Requirement already satisfied: wechatpy~=2.0.0a26 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 40)) (2.0.0a26)
Requirement already satisfied: pydub~=0.25.1 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 41)) (0.25.1)
Requirement already satisfied: creart~=0.2.2 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 43)) (0.2.2)
Requirement already satisfied: tiktoken~=0.4.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 44)) (0.4.0)
Requirement already satisfied: httpcore~=0.17.3 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 45)) (0.17.3)
Requirement already satisfied: creart-graia<1.0.0,>=0.1.5 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.5->-r requirements.txt (line 1)) (0.1.6)
Requirement already satisfied: graia-amnesia~=0.7.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.5->-r requirements.txt (line 1)) (0.7.1)
Requirement already satisfied: graia-broadcast~=0.19 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.5->-r requirements.txt (line 1)) (0.22.1)
Requirement already satisfied: launart<1.0.0,>=0.6.2 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.5->-r requirements.txt (line 1)) (0.6.3)
Requirement already satisfied: packaging>=23.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.5->-r requirements.txt (line 1)) (23.1)
Requirement already satisfied: typing-extensions<5.0,>=4.4 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.5->-r requirements.txt (line 1)) (4.7.1)
Requirement already satisfied: websockets in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from EdgeGPT==0.12.1->-r requirements.txt (line 18)) (11.0.3)
Requirement already satisfied: rich in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from EdgeGPT==0.12.1->-r requirements.txt (line 18)) (13.5.2)
Requirement already satisfied: certifi in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from EdgeGPT==0.12.1->-r requirements.txt (line 18)) (2023.7.22)
Requirement already satisfied: prompt-toolkit in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from EdgeGPT==0.12.1->-r requirements.txt (line 18)) (3.0.39)
Requirement already satisfied: python-socks in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from poe-api==0.5.2->-r requirements.txt (line 23)) (2.3.0)
Requirement already satisfied: quickjs in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from poe-api==0.5.2->-r requirements.txt (line 23)) (1.19.2)
Requirement already satisfied: websocket-client in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from poe-api==0.5.2->-r requirements.txt (line 23)) (1.6.1)
Requirement already satisfied: aiofiles in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 37)) (23.1.0)
Requirement already satisfied: blinker in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 37)) (1.6.2)
Requirement already satisfied: click in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 37)) (8.1.6)
Requirement already satisfied: hypercorn>=0.11.2 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 37)) (0.14.4)
Requirement already satisfied: itsdangerous in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 37)) (2.1.2)
Requirement already satisfied: jinja2 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 37)) (3.1.2)
Requirement already satisfied: markupsafe in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 37)) (2.1.3)
Requirement already satisfied: werkzeug>=2.0.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 37)) (2.3.6)
Requirement already satisfied: colorama>=0.3.4 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from loguru~=0.7.0->-r requirements.txt (line 8)) (0.4.6)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from loguru~=0.7.0->-r requirements.txt (line 8)) (1.1.0)
Requirement already satisfied: six in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from imgkit~=1.2.3->-r requirements.txt (line 15)) (1.16.0)
Requirement already satisfied: pypng in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from qrcode~=7.4.2->-r requirements.txt (line 16)) (0.20220715.0)
Requirement already satisfied: tqdm in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from openai~=0.27.8->-r requirements.txt (line 17)) (4.65.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (line 19)) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (line 19)) (3.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (line 19)) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (line 19)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (line 19)) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (line 19)) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (line 19)) (1.3.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from requests~=2.31.0->-r requirements.txt (line 24)) (3.4)
Requirement already satisfied: sniffio in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from httpx~=0.24.1->-r requirements.txt (line 36)) (1.3.0)
Requirement already satisfied: cryptography>=3.1 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from wechatpy~=2.0.0a26->-r requirements.txt (line 40)) (41.0.3)
Requirement already satisfied: optionaldict>=0.1.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from wechatpy~=2.0.0a26->-r requirements.txt (line 40)) (0.1.2)
Requirement already satisfied: requests-pkcs12<2.0,>=1.7 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from wechatpy~=2.0.0a26->-r requirements.txt (line 40)) (1.18)
Requirement already satisfied: xmltodict>=0.11.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from wechatpy~=2.0.0a26->-r requirements.txt (line 40)) (0.13.0)
Requirement already satisfied: importlib-metadata>=3.6 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from creart~=0.2.2->-r requirements.txt (line 43)) (6.8.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from httpcore~=0.17.3->-r requirements.txt (line 45)) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from httpcore~=0.17.3->-r requirements.txt (line 45)) (3.7.1)
Requirement already satisfied: exceptiongroup in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from anyio<5.0,>=3.0->httpcore~=0.17.3->-r requirements.txt (line 45)) (1.1.2)
Requirement already satisfied: cffi>=1.12 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from cryptography>=3.1->wechatpy~=2.0.0a26->-r requirements.txt (line 40)) (1.15.1)
Requirement already satisfied: statv>=0.2.2 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from graia-amnesia~=0.7.0->graia-ariadne==0.11.5->-r requirements.txt (line 1)) (0.3.2)
Requirement already satisfied: socksio==1.* in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from httpx~=0.24.1->-r requirements.txt (line 36)) (1.0.0)
Requirement already satisfied: h2>=3.1.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from hypercorn>=0.11.2->Quart==0.17.0->-r requirements.txt (line 37)) (4.1.0)
Requirement already satisfied: priority in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from hypercorn>=0.11.2->Quart==0.17.0->-r requirements.txt (line 37)) (2.0.0)
Requirement already satisfied: tomli in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from hypercorn>=0.11.2->Quart==0.17.0->-r requirements.txt (line 37)) (2.0.1)
Requirement already satisfied: wsproto>=0.14.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from hypercorn>=0.11.2->Quart==0.17.0->-r requirements.txt (line 37)) (1.2.0)
Requirement already satisfied: zipp>=0.5 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from importlib-metadata>=3.6->creart~=0.2.2->-r requirements.txt (line 43)) (3.16.2)
Requirement already satisfied: wcwidth in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from prompt-toolkit->EdgeGPT==0.12.1->-r requirements.txt (line 18)) (0.2.6)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from requests~=2.31.0->-r requirements.txt (line 24)) (1.7.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from rich->EdgeGPT==0.12.1->-r requirements.txt (line 18)) (3.0.0)
Requirement already satisfied: pycparser in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from cffi>=1.12->cryptography>=3.1->wechatpy~=2.0.0a26->-r requirements.txt (line 40)) (2.21)
Requirement already satisfied: hyperframe<7,>=6.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from h2>=3.1.0->hypercorn>=0.11.2->Quart==0.17.0->-r requirements.txt (line 37)) (6.0.1)
Requirement already satisfied: hpack<5,>=4.0 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from h2>=3.1.0->hypercorn>=0.11.2->Quart==0.17.0->-r requirements.txt (line 37)) (4.0.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\29642\miniconda3\envs\chatgpt\lib\site-packages (from markdown-it-py>=2.2.0->rich->EdgeGPT==0.12.1->-r requirements.txt (line 18)) (0.1.2)
[2023-08-07 18:35:27.209] [info] 启动程序
2023-08-07 18:35:31.673 | SUCCESS  | config:scan_presets:565 - 检查预设：聊天 <==> presets/issue402.txt [成功]
2023-08-07 18:35:31.677 | SUCCESS  | config:scan_presets:565 - 检查预设：猫娘 <==> presets/catgirl.txt [成功]
2023-08-07 18:35:31.683 | SUCCESS  | config:scan_presets:578 - 注册预设：catgirl <==> ./presets\catgirl.txt [成功]
2023-08-07 18:35:31.685 | SUCCESS  | config:scan_presets:578 - 注册预设：catgirl_en <==> ./presets\catgirl_en.txt [成功]
2023-08-07 18:35:31.687 | SUCCESS  | config:scan_presets:578 - 注册预设：issue402 <==> ./presets\issue402.txt [成功]
2023-08-07 18:35:31.689 | SUCCESS  | config:scan_presets:578 - 注册预设：预设模板 <==> ./presets\预设模板.txt [成功]
2023-08-07 18:35:31.985 | ERROR    | utils.exithooks:foo:35 - 看样子程序似乎没有正常退出。
2023-08-07 18:35:31.987 | ERROR    | utils.exithooks:foo:36 - current environment does not contain support for asyncio.events:AbstractEventLoop
NoneType: None
2023-08-07 18:35:31.991 | ERROR    | utils.exithooks:foo:37 - 你可以在这里阅读常见问题的解决方案：
2023-08-07 18:35:32.010 | ERROR    | utils.exithooks:foo:38 - https://github.com/lss233/chatgpt-mirai-qq-bot/issues/85
Exception ignored in atexit callback: <function foo at 0x000002A500903910>
Traceback (most recent call last):
  File "C:\RJ\Abao\chatgpt-mirai-qq-bot\chatgpt-mirai-qq-bot\utils\exithooks.py", line 39, in foo
    raise hooks.exception
  File "C:\RJ\Abao\chatgpt-mirai-qq-bot\chatgpt-mirai-qq-bot\bot.py", line 12, in <module>
    loop = creart.create(AbstractEventLoop)
  File "C:\Users\29642\Miniconda3\envs\chatgpt\lib\site-packages\creart\__init__.py", line 60, in create
    _assert_supported(target_type)
  File "C:\Users\29642\Miniconda3\envs\chatgpt\lib\site-packages\creart\__init__.py", line 48, in _assert_supported
    raise TypeError(f"current environment does not contain support for {_signature(target)}")
TypeError: current environment does not contain support for asyncio.events:AbstractEventLoop
[2023-08-07 18:35:32.319] [info] 按任意键退出...

**其他内容**

**Comment by weilai-ke-qi** [comment]
俺也一样

**Comment by Haibersut** [comment]
见这个issue，graia依赖库问题
https://github.com/lss233/chatgpt-mirai-qq-bot/issues/1120

**Comment by WinternetQilin** [comment]
> 见这个issue，graia依赖库问题 #1120

2.5.3 win11 尝试了更新依旧有这个问题

**Comment by Haibersut** [comment]
> > 见这个issue，graia依赖库问题 #1120
> 
> 2.5.3 win11 尝试了更新依旧有这个问题

你得确保所有的graia依赖都更新到对应版本才行
