### ISSUE TITLE
[BUG] 出现错误！返回消息为空，不添加到会话

### ISSUE THREAD

**Issue by c19373842811** [lss233/chatgpt-mirai-qq-bot#1141]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
使用chatgpt api版，有接收到api返回的文本，但是报错返回消息为空

**运行环境:**  
- 操作系统：linux
- Docker： ？
- 项目版本：2.5.3

**复现步骤**  
配置好config后，第一次启动。下面贴图

![45 AZVM@Y6YU{35R~`_TH R](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/141468612/bd741232-69b8-43e5-b874-2142e56a9618)

日志：
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/141468612/c5005a14-664a-4e2d-a41c-11965019233f)

配置文件：
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/141468612/02bd81bf-620d-4a32-a9fe-4c9d2c6fd7f0)

**Comment by Haibersut** [comment]
你转发的api格式不规范，没有返回角色

**Comment by c19373842811** [comment]
> 

![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/141468612/d8b0518a-ac15-4915-969c-738556adbfa2)
刚刚看了下有返回role参数

**Comment by c19373842811** [comment]
> 

刚刚curl了一下，同样的地址和key，有返回role参数
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/141468612/f1bb69d6-d2f9-4986-8595-d562a3bbbefc)

**Comment by c19373842811** [comment]
> 你转发的api格式不规范，没有返回角色

刚刚curl了一下试试，返回是有role的
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/141468612/828c1f26-fa6e-497b-abfa-0229681750d2)

**Comment by Haibersut** [comment]
懂了，你的那个转发是不支持流式请求的，请使用非流请求

默认是流式请求，格式如下
```
{
  "choices": [
    {
      "delta": {
        "role": "assistant"
      },
      "finish_reason": null,
      "index": 0
    }
  ],
  "created": 1677825464,
  "id": "chatcmpl-6ptKyqKOGXZT6iQnqiXAH8adNLUzD",
  "model": "gpt-3.5-turbo-0301",
  "object": "chat.completion.chunk"
}
```

**Comment by c19373842811** [comment]
> 明白，谢谢

**Comment by pandoradevin** [comment]
> > 明白，谢谢

大佬，我也是这种错误，最后如何解决的？麻烦给下解决方案呗
