### ISSUE TITLE
[BUG] NewBing 报错 "Authentication failed"

### ISSUE THREAD

**Issue by xfrqh** [lss233/chatgpt-mirai-qq-bot#1142]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/73733485/0f1e188a-b3a4-47e0-8754-954375cb7018)

我在GitHub中找到了一些网友提供的bing代理，但未能解决问题。我通过Azure在日本部署了一个Windows虚拟机，运行本项目，但问题依旧。

**运行环境:**  
- 操作系统：Windows 10 专业版 22H2
- 项目版本：2.5.2

**复现步骤**  
1. 用浏览器扩展Cookie-Editor获取Cookie，用 [jsonformatter.org](https://jsonformatter.org/json-minify) 处理，粘贴到"./chatgpt/config.cfg"中。
2. 启动项目
3. 用QQ向NewBing发消息。
4. 收到报错："Authentication failed"

**预期行为**  
能用QQ和NewBing聊天。

**截图**  

**其他内容**  
![wymxedq  108361124_p0 混沌のAI世界](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/73733485/8c98c35c-e857-4c0b-8e5b-9a776eaaddbf)
![今晨  108343831_p0 ┗( ˘ω˘ )┛](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/73733485/1de9ca4a-2c0d-4023-bd18-7ff2aa09b8da)

**Comment by Haibersut** [comment]
bing经典问题

https://github.com/lss233/chatgpt-mirai-qq-bot/issues/1103

**Comment by xfrqh** [comment]
问题解决了。我的解决办法：自建终结点。#1146

**Comment by xfrqh** [comment]
问题解决了。我的解决办法：自建终结点。#1146
