### ISSUE TITLE
关于claude2.0 接入

### ISSUE THREAD

**Issue by bincooo** [lss233/chatgpt-mirai-qq-bot#1162]
github有一个claude2转openai api接口。
诸位可以尝试通过它以openai api的方式接入。
理论上可行，我没有实践过。

https://github.com/oldweipro/claude-to-chatgpt.git

key呢，就是你在网页F12上抓取的cookies里的sessinKey

**Comment by zreozhangs** [comment]
可以用来自己尝尝鲜，自用的不确保稳定长时间运行。
其实就是简单用线程池同步转异步执行，与Claude通信用这个库https://github.com/KoushikNavuluri/Claude-API
最好的方式还是替换所有的请求为异步的去实现。没精力搞了，有谁搞定了可以提交个PR，哈哈。

**以下替换adapter/claude/slack.py**

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import asyncio
from typing import Generator
from exceptions import BotOperationNotSupportedException
from loguru import logger

from adapter.claude.claude_ai_2 import claude_manager
from adapter.botservice import BotAdapter


class ClaudeInSlackAdapter(BotAdapter):
    def __init__(self, session_id: str = ""):
        super().__init__(session_id)
        self.session_id = session_id
        self.conversation_id = None
        self.current_model = "claude"
        self.supported_models = [
            "claude"
        ]

    async def switch_model(self, model_name):
        self.current_model = model_name

    async def rollback(self):
        raise BotOperationNotSupportedException()

    async def on_reset(self):
        self.__setup_client()
        self.conversation_id = None

    async def preset_ask(self, role: str, text: str):
        if role.endswith('bot') or role in {'assistant', 'claude'}:
            logger.debug(f"[预设] 响应：{text}")
            yield text
        else:
            logger.debug(f"[预设] 发送：{text}")
            item = None
            async for item in self.ask(text): ...
            if item:
                logger.debug(f"[预设] Chatbot 回应：{item}")

    async def creart_new_conversation(self):
        loop = asyncio.get_event_loop()
        self.conversation_id = await loop.run_in_executor(claude_manager.pool, claude_manager.start_new_conversation,
                                                          self.session_id)

    async def get_all_conversations(self):
        loop = asyncio.get_event_loop()
        conversations = await loop.run_in_executor(claude_manager.pool, claude_manager.get_conversations)
        for item in conversations:
            if item['name'] == self.session_id:
                self.conversation_id = item['uuid']

    async def __setup_client(self):
        if self.conversation_id:
            return
        await self.get_all_conversations()

        if not self.conversation_id:
            await self.creart_new_conversation()

    async def ask(self, prompt) -> Generator[str, None, None]:
        await self.__setup_client()
        loop = asyncio.get_event_loop()
        response = await loop.run_in_executor(claude_manager.pool, claude_manager.send_message, prompt,
                                              self.conversation_id)
        if not response:
            response = "没有返回请重发一次"
            self.conversation_id = None
        yield response

```

**在adapter/claude/下创建claude_ai_2.py文件**

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
from concurrent.futures import ThreadPoolExecutor

from claude_api import Client


class ClaudeManager(object):

    _instance = None

    def __new__(cls, *args, **kwargs):
        if not cls._instance:
            cls._instance = super(ClaudeManager, cls).__new__(cls, *args, **kwargs)
        return cls._instance

    def __init__(self):
        cookie = self.read_cookies()
        self._claude_obj = Client(cookie)
        self.pool = ThreadPoolExecutor()

    @classmethod
    def read_cookies(cls):
        key_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'cookies.txt')
        print('cookies_path: ', key_path)
        with open(key_path, 'r', encoding='utf-8') as f:
            key = f.read().strip()
        print('cookies: ', key)
        return key

    @property
    def wrapper(self):
        return self._claude_obj

    def get_conversations(self):
        return self._claude_obj.list_all_conversations()

    def rename_conversation(self, conversation_id, title):
        renamed = self._claude_obj.rename_chat(title, conversation_id)
        if renamed:
            print("Chat conversation renamed successfully")
            return True
        else:
            print("Failed to rename chat conversation")
            return False

    def start_new_conversation(self, name, msg="Hi Claude!"):
        new_chat = self._claude_obj.create_new_chat()
        conversation_id = new_chat['uuid']
        print('new_conversation_id', conversation_id)
        if self.rename_conversation(conversation_id, name):
            return conversation_id

    def delete_conversation(self, conversation_id):
        deleted = self._claude_obj.delete_conversation(conversation_id)
        if deleted:
            print("Conversation deleted successfully")
        else:
            print("Failed to delete conversation")
        return deleted

    def send_message(self, prompt, conversation_uuid):
        response = self._claude_obj.send_message(prompt=prompt, conversation_id=conversation_uuid)
        print(response)
        return response

    def send_message_with_attachment(self, prompt, conversation_id, attachment):  # attachment is local file path
        response = self._claude_obj.send_message(prompt, conversation_id, attachment=attachment, timeout=600)
        print(response)
        return response

    def reset_all_conversation(self):
        reset = self._claude_obj.reset_all()
        if reset:
            print("All conversations reset successfully")
        else:
            print("Failed to reset conversations")
        return reset

    def get_conversation_history(self, conversation_id):
        history = self._claude_obj.chat_conversation_history(conversation_id)
        print(history)
        return history


claude_manager = ClaudeManager()

```

**参考https://github.com/KoushikNavuluri/Claude-API#usage
安装依赖库并在adapter/claude/下创建cookies.txt存放抓取到的cookies值**

然后就可以运行bot进行体验
可以将原来的slack.py备份，需要同步的时候就还原一下文件，之所以这么搞是为了方便同步，依赖也很少与主代码不冲突
网络环境需要能正常访问claude.ai

**Comment by 200542053** [comment]
> 可以用来自己尝尝鲜，自用的不确保稳定长时间运行。 其实就是简单用线程池同步转异步执行，与Claude通信用这个库https://github.com/KoushikNavuluri/Claude-API 最好的方式还是替换所有的请求为异步的去实现。没精力搞了，有谁搞定了可以提交个PR，哈哈。
> 
> **以下替换adapter/claude/slack.py**
> 
> ```python
> #!/usr/bin/env python
> # -*- coding: utf-8 -*-
> import asyncio
> from typing import Generator
> from exceptions import BotOperationNotSupportedException
> from loguru import logger
> 
> from adapter.claude.claude_ai_2 import claude_manager
> from adapter.botservice import BotAdapter
> 
> 
> class ClaudeInSlackAdapter(BotAdapter):
>     def __init__(self, session_id: str = ""):
>         super().__init__(session_id)
>         self.session_id = session_id
>         self.conversation_id = None
>         self.current_model = "claude"
>         self.supported_models = [
>             "claude"
>         ]
> 
>     async def switch_model(self, model_name):
>         self.current_model = model_name
> 
>     async def rollback(self):
>         raise BotOperationNotSupportedException()
> 
>     async def on_reset(self):
>         self.__setup_client()
>         self.conversation_id = None
> 
>     async def preset_ask(self, role: str, text: str):
>         if role.endswith('bot') or role in {'assistant', 'claude'}:
>             logger.debug(f"[预设] 响应：{text}")
>             yield text
>         else:
>             logger.debug(f"[预设] 发送：{text}")
>             item = None
>             async for item in self.ask(text): ...
>             if item:
>                 logger.debug(f"[预设] Chatbot 回应：{item}")
> 
>     async def creart_new_conversation(self):
>         loop = asyncio.get_event_loop()
>         self.conversation_id = await loop.run_in_executor(claude_manager.pool, claude_manager.start_new_conversation,
>                                                           self.session_id)
> 
>     async def get_all_conversations(self):
>         loop = asyncio.get_event_loop()
>         conversations = await loop.run_in_executor(claude_manager.pool, claude_manager.get_conversations)
>         for item in conversations:
>             if item['name'] == self.session_id:
>                 self.conversation_id = item['uuid']
> 
>     async def __setup_client(self):
>         if self.conversation_id:
>             return
>         await self.get_all_conversations()
> 
>         if not self.conversation_id:
>             await self.creart_new_conversation()
> 
>     async def ask(self, prompt) -> Generator[str, None, None]:
>         await self.__setup_client()
>         loop = asyncio.get_event_loop()
>         response = await loop.run_in_executor(claude_manager.pool, claude_manager.send_message, prompt,
>                                               self.conversation_id)
>         if not response:
>             response = "没有返回请重发一次"
>             self.conversation_id = None
>         yield response
> ```
> 
> **在adapter/claude/下创建claude_ai_2.py文件**
> 
> ```python
> #!/usr/bin/env python
> # -*- coding: utf-8 -*-
> import os
> from concurrent.futures import ThreadPoolExecutor
> 
> from claude_api import Client
> 
> 
> class ClaudeManager(object):
> 
>     _instance = None
> 
>     def __new__(cls, *args, **kwargs):
>         if not cls._instance:
>             cls._instance = super(ClaudeManager, cls).__new__(cls, *args, **kwargs)
>         return cls._instance
> 
>     def __init__(self):
>         cookie = self.read_cookies()
>         self._claude_obj = Client(cookie)
>         self.pool = ThreadPoolExecutor()
> 
>     @classmethod
>     def read_cookies(cls):
>         key_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'cookies.txt')
>         print('cookies_path: ', key_path)
>         with open(key_path, 'r', encoding='utf-8') as f:
>             key = f.read().strip()
>         print('cookies: ', key)
>         return key
> 
>     @property
>     def wrapper(self):
>         return self._claude_obj
> 
>     def get_conversations(self):
>         return self._claude_obj.list_all_conversations()
> 
>     def rename_conversation(self, conversation_id, title):
>         renamed = self._claude_obj.rename_chat(title, conversation_id)
>         if renamed:
>             print("Chat conversation renamed successfully")
>             return True
>         else:
>             print("Failed to rename chat conversation")
>             return False
> 
>     def start_new_conversation(self, name, msg="Hi Claude!"):
>         new_chat = self._claude_obj.create_new_chat()
>         conversation_id = new_chat['uuid']
>         print('new_conversation_id', conversation_id)
>         if self.rename_conversation(conversation_id, name):
>             return conversation_id
> 
>     def delete_conversation(self, conversation_id):
>         deleted = self._claude_obj.delete_conversation(conversation_id)
>         if deleted:
>             print("Conversation deleted successfully")
>         else:
>             print("Failed to delete conversation")
>         return deleted
> 
>     def send_message(self, prompt, conversation_uuid):
>         response = self._claude_obj.send_message(prompt=prompt, conversation_id=conversation_uuid)
>         print(response)
>         return response
> 
>     def send_message_with_attachment(self, prompt, conversation_id, attachment):  # attachment is local file path
>         response = self._claude_obj.send_message(prompt, conversation_id, attachment=attachment, timeout=600)
>         print(response)
>         return response
> 
>     def reset_all_conversation(self):
>         reset = self._claude_obj.reset_all()
>         if reset:
>             print("All conversations reset successfully")
>         else:
>             print("Failed to reset conversations")
>         return reset
> 
>     def get_conversation_history(self, conversation_id):
>         history = self._claude_obj.chat_conversation_history(conversation_id)
>         print(history)
>         return history
> 
> 
> claude_manager = ClaudeManager()
> ```
> 
> **参考https://github.com/KoushikNavuluri/Claude-API#usage 安装依赖库并在adapter/claude/下创建cookies.txt存放抓取到的cookies值**
> 
> 然后就可以运行bot进行体验 可以将原来的slack.py备份，需要同步的时候就还原一下文件，之所以这么搞是为了方便同步，依赖也很少与主代码不冲突 网络环境需要能正常访问claude.ai

不知为何会有证书问题

`cookies:  ********************
2023-08-24 17:55:50.084 | ERROR    | utils.exithooks:foo:36 - 看样子程序似乎没有正常退出。
2023-08-24 17:55:50.146 | ERROR    | utils.exithooks:foo:37 - Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile: D:\系统\桌面\qq bot\python3.11\Lib\site-packages\curl_cffi\cacert.pem CApath: none'
NoneType: None
2023-08-24 17:55:50.172 | ERROR    | utils.exithooks:foo:38 - 你可以在这里阅读常见问题的解决方案：
2023-08-24 17:55:50.176 | ERROR    | utils.exithooks:foo:39 - https://github.com/lss233/chatgpt-mirai-qq-bot/issues/85
Exception ignored in atexit callback: <function foo at 0x000001510DFE8900>`
