### ISSUE TITLE
slack-claude

### ISSUE THREAD

**Issue by zaixiaxiaosu** [lss233/chatgpt-mirai-qq-bot#1164]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：windows server 2012
- Docker：x
- 项目版本：2.5.2

**复现步骤**  
https://chatgpt-proxy.lss233.com/claude-in-slack/login 失效

**预期行为**  
slack-claude调用失败

**截图**  
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/116610883/e3865f16-53db-4339-9084-c7d3b2db927e)

**其他内容**  
https://chatgpt-proxy.lss233.com/claude-in-slack/login 失效

**Comment by tts2** [comment]
https://chatgpt-proxy.lss233.com/claude-in-slack/login<-这个地址打开后重新授权又可以访问了
