### ISSUE TITLE
[BUG] 表现 以一种访问权限不允许的方式做了一个访问套接字的尝试。

### ISSUE THREAD

**Issue by shenleqinau** [lss233/chatgpt-mirai-qq-bot#1168]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [ √] 我已看过其他 issue，他们不能解决我的问题 
- [√ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
PermissionError: [Errno 13] error while attempting to bind on address ('0.0.0.0', 48567): 以一种访问权限不允许的方式做了一个访问套接字的尝试。
**运行环境:**  
- 操作系统：windows 10 x64
- Docker： 无
- 项目版本：2.5.3

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 反复调整端口都会出现
2. 后台无端口占用即使有也只是mirai

**预期行为**  
应为正常WS接入
尝试 从 Mirai 服务中读取机器人 QQ 的 session key并成功

**截图**  
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/123302928/902fb00a-aebd-4843-a589-7636d93a2577)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by shenleqinau** [comment]
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/123302928/c9a73cfe-bd20-4394-9620-945b7caf0f01)

**Comment by shenleqinau** [comment]
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/123302928/1908c74d-22ab-4c36-ba62-b1c43a1ff598)

**Comment by lss233** [comment]
端口被其他程序占用了。你把那个程序关了就行。

**Comment by yejinyi** [comment]
> 端口被其他程序占用了。你把那个程序关了就行。

我的没有被端口占用，但是也显示了上面的错误
