### ISSUE TITLE
求救~~回答出错

### ISSUE THREAD

**Issue by skyyaman** [lss233/chatgpt-mirai-qq-bot#117]
使用一键安装脚本安装的。

日志：
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:27.117 | INFO     | __main__:start_background:124 - OpenAI 服务器登录成功
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:27.117 | INFO     | __main__:start_background:125 - 尝试连接到 Mirai 服务……
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:27.118 | SUCCESS  | launart.manager:launch:384 - Layer #3:[elizabeth.service] preparation completed.
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:27.118 | INFO     | launart.manager:launch:389 - All components prepared, start blocking phase.
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:27.134 | WARNING  | graia.amnesia.builtins.aiohttp:connection_manage:229 - ClientConnectorError(ConnectionKey(host='mirai', port=8080, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(111, "Connect call failed ('172.20.0.3', 8080)"))
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:27.136 | WARNING  | graia.ariadne.connection.ws:_:75 - Websocket reconnecting in 5s...
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:32.141 | WARNING  | graia.ariadne.connection.ws:_:77 - Websocket reconnecting...
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:32.152 | WARNING  | graia.amnesia.builtins.aiohttp:connection_manage:229 - ClientConnectorError(ConnectionKey(host='mirai', port=8080, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(111, "Connect call failed ('172.20.0.3', 8080)"))
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:32.154 | WARNING  | graia.ariadne.connection.ws:_:75 - Websocket reconnecting in 5s...
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:37.156 | WARNING  | graia.ariadne.connection.ws:_:77 - Websocket reconnecting...
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:37.182 | WARNING  | graia.amnesia.builtins.aiohttp:connection_manage:229 - ClientConnectorError(ConnectionKey(host='mirai', port=8080, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(111, "Connect call failed ('172.20.0.3', 8080)"))
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:37.184 | WARNING  | graia.ariadne.connection.ws:_:75 - Websocket reconnecting in 5s...
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:42.187 | WARNING  | graia.ariadne.connection.ws:_:77 - Websocket reconnecting...
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:43.882 | SUCCESS  | graia.ariadne.connection.ws:_:62 - Successfully got session key
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:58.604 | INFO     | graia.ariadne.model:log:83 - 6526211: [RECV][GPT(3486633230)] -> 机器人不不不
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:58.782 | ERROR    | __main__:handle_message:82 - Unknown error
chatgpt-qq-chatgpt-1  | Traceback (most recent call last):
chatgpt-qq-chatgpt-1  |
chatgpt-qq-chatgpt-1  |   File "/app/bot.py", line 127, in <module>
chatgpt-qq-chatgpt-1  |     app.launch_blocking()
chatgpt-qq-chatgpt-1  |     │   └ <classmethod object at 0x7f2feff66550>
chatgpt-qq-chatgpt-1  |     └ <graia.ariadne.app.Ariadne object at 0x7f2fc1449880>
chatgpt-qq-chatgpt-1  |
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/graia/ariadne/app.py", line 313, in launch_blocking
chatgpt-qq-chatgpt-1  |     cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
chatgpt-qq-chatgpt-1  |     │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
chatgpt-qq-chatgpt-1  |     │   │              │                    │   │       └ <property object at 0x7f2feff61450>
chatgpt-qq-chatgpt-1  |     │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x7f2ff1ca8520>
chatgpt-qq-chatgpt-1  |     │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
chatgpt-qq-chatgpt-1  |     │   │              └ <function Launart.launch_blocking at 0x7f2ff10e79d0>
chatgpt-qq-chatgpt-1  |     │   └ <launart.manager.Launart object at 0x7f2fc0c142e0>
chatgpt-qq-chatgpt-1  |     └ <class 'graia.ariadne.app.Ariadne'>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/launart/manager.py", line 494, in launch_blocking
chatgpt-qq-chatgpt-1  |     loop.run_until_complete(launch_task)
chatgpt-qq-chatgpt-1  |     │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /usr/local/lib/python3.9/site-packages/launart/manager....
chatgpt-qq-chatgpt-1  |     │    └ <function BaseEventLoop.run_until_complete at 0x7f2ff141eb80>
chatgpt-qq-chatgpt-1  |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
chatgpt-qq-chatgpt-1  |     self.run_forever()
chatgpt-qq-chatgpt-1  |     │    └ <function BaseEventLoop.run_forever at 0x7f2ff141eaf0>
chatgpt-qq-chatgpt-1  |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
chatgpt-qq-chatgpt-1  |     self._run_once()
chatgpt-qq-chatgpt-1  |     │    └ <function BaseEventLoop._run_once at 0x7f2ff1421670>
chatgpt-qq-chatgpt-1  |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
chatgpt-qq-chatgpt-1  |     handle._run()
chatgpt-qq-chatgpt-1  |     │      └ <function Handle._run at 0x7f2ff1544430>
chatgpt-qq-chatgpt-1  |     └ <Handle <TaskStepMethWrapper object at 0x7f2fc0129bb0>()>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
chatgpt-qq-chatgpt-1  |     self._context.run(self._callback, *self._args)
chatgpt-qq-chatgpt-1  |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
chatgpt-qq-chatgpt-1  |     │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f2fc0129bb0>()>
chatgpt-qq-chatgpt-1  |     │    │            │    └ <member '_callback' of 'Handle' objects>
chatgpt-qq-chatgpt-1  |     │    │            └ <Handle <TaskStepMethWrapper object at 0x7f2fc0129bb0>()>
chatgpt-qq-chatgpt-1  |     │    └ <member '_context' of 'Handle' objects>
chatgpt-qq-chatgpt-1  |     └ <Handle <TaskStepMethWrapper object at 0x7f2fc0129bb0>()>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/graia/broadcast/__init__.py", line 191, in Executor
chatgpt-qq-chatgpt-1  |     result = await run_always_await(target_callable, **parameter_compile_result)
chatgpt-qq-chatgpt-1  |                    │                │                  └ {'app': <graia.ariadne.app.Ariadne object at 0x7f2fc1449880>, 'friend': Friend(id=3486633230, nickname='GPT', remark='GPT'), ...
chatgpt-qq-chatgpt-1  |                    │                └ <function friend_message_listener at 0x7f2fc0c20430>
chatgpt-qq-chatgpt-1  |                    └ <function run_always_await at 0x7f2ff109baf0>
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/graia/broadcast/utilles.py", line 34, in run_always_await
chatgpt-qq-chatgpt-1  |     obj = await obj
chatgpt-qq-chatgpt-1  |                 └ <coroutine object friend_message_listener at 0x7f2fc01c7440>
chatgpt-qq-chatgpt-1  |
chatgpt-qq-chatgpt-1  |   File "/app/bot.py", line 91, in friend_message_listener
chatgpt-qq-chatgpt-1  |     response = await handle_message(friend, f"friend-{friend.id}", chain.display, source)
chatgpt-qq-chatgpt-1  |                      │              │                              │     │        └ Source(id=14961, time=datetime.datetime(2023, 2, 14, 7, 57, 57, tzinfo=datetime.timezone.utc), type='Source')
chatgpt-qq-chatgpt-1  |                      │              │                              │     └ <property object at 0x7f2ff0062540>
chatgpt-qq-chatgpt-1  |                      │              │                              └ MessageChain([Plain(text='不不不')])
chatgpt-qq-chatgpt-1  |                      │              └ Friend(id=3486633230, nickname='GPT', remark='GPT')
chatgpt-qq-chatgpt-1  |                      └ <function handle_message at 0x7f2fc0c20310>
chatgpt-qq-chatgpt-1  |
chatgpt-qq-chatgpt-1  | > File "/app/bot.py", line 75, in handle_message
chatgpt-qq-chatgpt-1  |     resp = await session.get_chat_response(message)
chatgpt-qq-chatgpt-1  |                  │       │                 └ '不不不'
chatgpt-qq-chatgpt-1  |                  │       └ <function ChatSession.get_chat_response at 0x7f2fc00d8310>
chatgpt-qq-chatgpt-1  |                  └ <chatbot.ChatSession object at 0x7f2fc0bc80d0>
chatgpt-qq-chatgpt-1  |
chatgpt-qq-chatgpt-1  |   File "/app/chatbot.py", line 90, in get_chat_response
chatgpt-qq-chatgpt-1  |     async for data in bot.ask(prompt=message, conversation_id=self.conversation_id):
chatgpt-qq-chatgpt-1  |                       │   │          │                        │    └ 'friend-3486633230'
chatgpt-qq-chatgpt-1  |                       │   │          │                        └ <chatbot.ChatSession object at 0x7f2fc0bc80d0>
chatgpt-qq-chatgpt-1  |                       │   │          └ '不不不'
chatgpt-qq-chatgpt-1  |                       │   └ <function Chatbot.ask at 0x7f2fc163f0d0>
chatgpt-qq-chatgpt-1  |                       └ <revChatGPT.V2.Chatbot object at 0x7f2fc0baef10>
chatgpt-qq-chatgpt-1  |
chatgpt-qq-chatgpt-1  |   File "/usr/local/lib/python3.9/site-packages/revChatGPT/V2.py", line 169, in ask
chatgpt-qq-chatgpt-1  |     raise Exception("Unknown error")
chatgpt-qq-chatgpt-1  |
chatgpt-qq-chatgpt-1  | Exception: Unknown error
chatgpt-qq-chatgpt-1  | 2023-02-14 07:57:59.594 | INFO     | graia.ariadne.model:log:83 - 6526211: [SEND][GPT(3486633230)] <- 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。\nUnknown error

config.cfg: 用的邮箱密码
[openai]
email = "XXXXXXXXXX"
password = "XXXXXXXXXX"

temperature = 0.5
insecure_auth = false

paid = false
[system]
accept_group_invite = false
accept_friend_request = false

[presets]
command = "加载预设 (\\w+)"
loaded_successful = "预设加载成功！"
[trigger]

prefix = [ "机器人",]
require_mention = "mention"

[presets.keywords]
"正常" = "presets/default.txt"
"猫娘" = "presets/catgirl.txt"

**Comment by skyyaman** [comment]
全部回答都是这样： 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。\nUnknown error

**Comment by 0frostmourne0** [comment]
#116

**Comment by lss233** [comment]
重复。
