### ISSUE TITLE
[Feature] 希望取得联系，并支持 InternLM 

### ISSUE THREAD

**Issue by JimmyMa99** [lss233/chatgpt-mirai-qq-bot#1172]
尊敬的 chatgpt-mirai-qq-bot 应用开发者，我是 InternLM 社区开发者&志愿者尖米, 大佬开源的工作对我的启发很大，希望可以探讨使用 InternLM 实现 chatgpt-mirai-qq-bot 的可能性和实现路径，我的微信是 mzm312，希望可以取得联系进行更深度的交流；

**Comment by lss233** [comment]
done
