### ISSUE TITLE
关于使用的api和模型问题

### ISSUE THREAD

**Issue by hisou** [lss233/chatgpt-mirai-qq-bot#118]
我自己的用java写的miraibot也粗糙地连接到了openai api(不是chatgpt)，使用的是text-danvinci-003，但是显然不像正常使用网页版chatgpt这么高质量，我看到本项目之前有使用谷歌浏览器的，也需要账号密码，还以为是直接接入的网页chatgpt(昨天刚看的reverse engineered那边，其中一个方式就是用xpath去扒网页html)，然而翻看本项目历史issue似乎不是这样么？那本项目使用哪个模型呢？光是使用api好像也不需要登录、只要有apikey就能用啊。

**Comment by Hisir0909** [comment]
有两种选择，一种使用账号登陆去使用text-chat-danvinci-003，或者就是你那个api调用

**Comment by lss233** [comment]
是这样的：以前是浏览器扒，中间有一段时间变成了官方 API.

**Comment by hisou** [comment]
> 是这样的：以前是浏览器扒，中间有一段时间变成了官方 API.

那这样应该不再需要账号了吧，这些信息是为了填在什么地方的？

**Comment by hisou** [comment]
> 有两种选择，一种使用账号登陆去使用text-chat-danvinci-003，或者就是你那个api调用

我不理解怎么登录然后去使用具体模型？chatgpt官方页面有这样的入口吗，希望告知

**Comment by lss233** [comment]
> > 是这样的：以前是浏览器扒，中间有一段时间变成了官方 API.
> 
> 那这样应该不再需要账号了吧，这些信息是为了填在什么地方的？

使用官方 API 期间不需要账号。

**Comment by hisou** [comment]
> > > 是这样的：以前是浏览器扒，中间有一段时间变成了官方 API.
> > 
> > 
> > 那这样应该不再需要账号了吧，这些信息是为了填在什么地方的？
> 
> 使用官方 API 期间不需要账号。

不好意思，因为是刚接触这一方面，我想知道得具体一些。也就是说本项目从今天2月14最新版本开始说是不再区分两种版本，那么我可以认为目前版本正在使用官方API？这样的话应该算接入openAI API而不是chartgpt吧？
但是配置文件仍然需要使用者提供账号密码，我不知道哪里我想错了，但如果现在只调用API那是不是可以去掉这部分配置了

**Comment by lss233** [comment]
并没有，只是把验证逻辑放到了后端而已。   

之前是因为出现了一种可以通过 官方API 调用 ChatGPT 的方法才这么做的。

**Comment by hisou** [comment]
好吧，java现在应该没有OpenAIAuth这种jdk包所以只能羡慕了

**Comment by lss233** [comment]
自己 port 一个也蛮快。叫 ChatGPT 帮你翻译

**Comment by wzIridium77** [comment]
你好，我成功把机器人接入qq，可以正常登录，使用切换模式及重置会话等基本功能。但是无法进行对话，显示openai.error.InvalidRequestError: That model does not exist，请问该如何解决呢
