### ISSUE TITLE
[BUG] win下无法安装

### ISSUE THREAD

**Issue by NuoFang6** [lss233/chatgpt-mirai-qq-bot#1181]
**表现**  
安装时提示无法编译quickjs，在安装了已编译的whl之后仍然无法继续，提示找不到_quickjs，多了一个_，我未能找到解决方案

**运行环境:**  
- 操作系统：win11
- 项目版本：2.5.3

**复现步骤**  
使用win安装器稳定复现，已重装过环境

**预期行为**  
成功安装

**截图**  
相关日志
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/137974286/d4d6bfeb-eee2-4e9a-b419-6056cada9cc0)
<img width="1270" alt="1" src="https://github.com/lss233/chatgpt-mirai-qq-bot/assets/137974286/7d755bb2-05cf-4add-9d84-4de753223a97">

**Comment by NuoFang6** [comment]
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/137974286/53ee8322-1eff-4373-a289-77eda6931e58)
这是我刚下载时遇到的报错

**Comment by NuoFang6** [comment]
v3.0.0-alpha0
quickjs问题仍然存在
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/137974286/f19c823f-7103-4eef-8b4c-b67d8719f8ba)

**Comment by lss233** [comment]
poe-api 的问题，下个版本会修。

**Comment by NuoFang6** [comment]
https://github.com/lss233/chatgpt-mirai-qq-bot/issues/1192
