### ISSUE TITLE
[提问]go-cqhttp文件下的device.json文件是否可以由mirai的同名文件代替

### ISSUE THREAD

**Issue by 2859371427** [lss233/chatgpt-mirai-qq-bot#1186]
![5ede448a83eec4b5a2c534022b0f424](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/118822516/2d8b2ca5-b143-4fa9-96eb-b80d371eb641)
此处的文件可以使用mirai的同名文件来代替吗

**Comment by lss233** [comment]
不知道，建议问对应项目作者
