### ISSUE TITLE
[BUG] v3.0.0-alpha1，win无法安装

### ISSUE THREAD

**Issue by NuoFang6** [lss233/chatgpt-mirai-qq-bot#1192]
**表现**  
无法安装

**运行环境:**  
- 操作系统：win11（纯新刚重装的，非常新的那种）
- 项目版本：v3.0.0-alpha1

**复现步骤**  
安装稳定复现

**预期行为**  
成功安装

**截图**  
相关日志、聊天记录的截图
<img width="1117" alt="Cache_-1557a4bdddcc478f" src="https://github.com/lss233/chatgpt-mirai-qq-bot/assets/137974286/81954372-1bb1-431e-86fa-2bbe719cd1b0">

**其他内容**  
尝试修改requirement.txt之后就弹quickjs了
上一个Issue：https://github.com/lss233/chatgpt-mirai-qq-bot/issues/1181

**Comment by NuoFang6** [comment]
![Screenshot_2023-09-10-13-54-28-36_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/137974286/2b2a8574-4b68-48c5-9178-776de585e804)

**Comment by lss233** [comment]
Try alpha2

**Comment by NuoFang6** [comment]
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/137974286/d915eccf-acb7-436e-9270-cc1f2c148eca)
问题已解决
