### ISSUE TITLE
[BUG] 明明slack_claude已经回复但是stream没法抓取到内容？

### ISSUE THREAD

**Issue by zigui123340** [lss233/chatgpt-mirai-qq-bot#1195]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
这是打印line的内容:
///
event: ping

data:

event: ping

data: 2023-09-11 01:11:48.918833

event: ping

data: 2023-09-11 01:12:03.920301

event: ping

data: 2023-09-11 01:12:18.922483

event: ping

data: 2023-09-11 01:12:33.925236
///
data:[Done]一直不出现，是一个间歇性的问题，我感到疑惑，上个星期还不会这样....
每二到三次正常回复后就会出现这种情况。

**运行环境:**  
- 操作系统: win10
- Docker： 无
- 项目版本：2.5.2

**复现步骤**  
隔了一段时间没用，但是是可以回复的，就是经常卡住。

**预期行为**  
正常回复。

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
这个我需要查一下

**Comment by Maolaohei** [comment]
确实我也遇到这个问题，有时候能正常回复，有时候无法回复，但是看slack里面claude是正常回复的。

**Comment by zigui123340** [comment]
> 

真的麻烦了，谢谢

**Comment by lss233** [comment]
发现有些时候收不到结束消息的状态。目前加了个超时，可以再看看有没有问题

**Comment by lss233** [comment]
发现有些时候收不到结束消息的状态。目前加了个超时，可以再看看有没有问题

**Comment by zigui123340** [comment]
> 发现有些时候收不到结束消息的状态。目前加了个超时，可以再看看有没有问题

好像可以了，谢谢！
