### ISSUE TITLE
docker容器内 Mirai 8080端口连接失败

### ISSUE THREAD

**Issue by tomomuy** [lss233/chatgpt-mirai-qq-bot#12]
操作系统：ubuntu20

config.json配置文件:
```json
{
    "mirai": {
        "qq": "qq账号",
        "api_key": "1234567",
        "http_url": "http://localhost:8080",
        "ws_url": "http://localhost:8080"
    },
    "openai": {
        "email": "邮箱",
        "password": "密码"
    },
    "text_to_image": {
        "font_size": 30,
        "width": 700,
        "font_path": "fonts/sarasa-mono-sc-regular.ttf",
        "offset_x": 50,
        "offset_y": 50
    }
}
```
是不是docker中 api_key 有默认值？

![image](https://user-images.githubusercontent.com/116566664/206459096-d3744c02-0a95-4d14-8e61-059d24e09cd9.png)

**Comment by lss233** [comment]
ConnectionRefusedError， 应该是端口没打开。
在容器外面 `netstat -nltp` 看一下？
确定你的 mirai 已经装了 mirai-http-api 插件了嘛？

https://graia.readthedocs.io/ariadne/quickstart/
看一下 看里面关于mirai-api-http 的配置的部分

**Comment by tomomuy** [comment]
> ConnectionRefusedError， 应该是端口没打开。 在容器外面 `netstat -nltp` 看一下？ 确定你的 mirai 已经装了 mirai-http-api 插件了嘛？
> 
> https://graia.readthedocs.io/ariadne/quickstart/ 看一下 看里面关于mirai-api-http 的配置的部分

原来容器中没有配置Mirai，需要自己部署吗
我以为容器中环境都已经配置好了，readme文档只要求一个config.json文件

**Comment by lss233** [comment]
没有嘞。。 这玩意挺玄学的……
有时间搞个吧，或者您来个 PR 也可以~

**Comment by lss233** [comment]
或者您使用这个项目提供的 docker 也可以： https://github.com/xzsk2/Mirai-Docker
使用 docker-compose 把这俩连接起来就好了。

**Comment by tomomuy** [comment]
> 

这个不太会😂
