### ISSUE TITLE
如果你想使用付费模型，就解除掉注释

### ISSUE THREAD

**Issue by seiken777** [lss233/chatgpt-mirai-qq-bot#120]
![image](https://user-images.githubusercontent.com/112504356/218691090-82266698-45a8-4bde-bc97-b483cc464314.png)
![image](https://user-images.githubusercontent.com/112504356/218691166-76c25148-5956-4270-8c6c-2b7948593d47.png)
去掉注释以后就启动不了了
root@VM-20-3-ubuntu:/home/lighthouse/chatgpt-qq# docker-compose restart
yaml: line 19: did not find expected key
root@VM-20-3-ubuntu:/home/lighthouse/chatgpt-qq# docker-compose up
yaml: line 19: did not find expected key
root@VM-20-3-ubuntu:/home/lighthouse/chatgpt-qq#

**Comment by tamakyi** [comment]
你是不是没写api_key

**Comment by seiken777** [comment]
> 你是不是没有写api_key

写了啊，我是一键部署的

**Comment by seiken777** [comment]
> 你是不是没写api_key

我把他换了个行就可以了
![image](https://user-images.githubusercontent.com/112504356/218696003-a2481fc2-3c1a-4659-9cac-6f3ae9020a2b.png)

**Comment by lss233** [comment]
你没有把空格对齐。
