### ISSUE TITLE
windows没有聊天窗口

### ISSUE THREAD

**Issue by 18735100708** [lss233/chatgpt-mirai-qq-bot#121]
2023-02-14 17:40:16 I/main: mirai-console started successfully.   

提示安装成功了  但是没打开服务聊天窗口

**Comment by 18735100708** [comment]
启动Mirai.cmd   这个初始化成功之后，是会安装一个应用程序吗？

**Comment by 18735100708** [comment]
我启动ChatGPT.cmd 后  一直报这个  graia.ariadne.connection.ws:_:89 - Websocket connection closed

**Comment by lss233** [comment]
不会。你要登录QQ。  看 FAQ 第一条就有说。

**Comment by mrcome3** [comment]
![image](https://user-images.githubusercontent.com/74747514/218780547-52b15285-8411-4707-b02d-9023bd98b5b7.png)
我也是一直报这个 graia.ariadne.connection.ws:_:89 - Websocket connection closed，怎么解决啊

**Comment by linxp001** [comment]
> ![image](https://user-images.githubusercontent.com/74747514/218780547-52b15285-8411-4707-b02d-9023bd98b5b7.png) 我也是一直报这个 graia.ariadne.connection.ws:_:89 - Websocket connection closed，怎么解决啊

在mirai那个窗口的>提示符下执行login QQ号码 QQ密码
