### ISSUE TITLE
1.5.4浏览器弹出并成功登录后卡在Found Session Token!

### ISSUE THREAD

**Issue by bai-piao** [lss233/chatgpt-mirai-qq-bot#122]
![屏幕截图 2023-02-14 183547](https://user-images.githubusercontent.com/63089566/218711067-0993ffea-b578-4e72-86b6-bec595c36594.jpg)

已全局立本
qq已登录

**Comment by bai-piao** [comment]
winserver2019

**Comment by 3517283258** [comment]
我的也是,一直卡在哪里

**Comment by linxp001** [comment]
我也是这个现象，只能等新版本了。

**Comment by lss233** [comment]
我已发布 v1.5.4.1 版本，可以尝试使用该版本，并使用第三方代理模式（见 README 或者 config.example.cfg）
