### ISSUE TITLE
[Feature] 支持OneBot12协议

### ISSUE THREAD

**Issue by PaienNate** [lss233/chatgpt-mirai-qq-bot#1236]
如题，尝试了一下搭配Shamrock使用，炸了（悲）

**Comment by LostXine** [comment]
@PaienNate 这个是协议的问题，在shamrock功能设置中选择“消息格式为CQ码”亲测可用。

**Comment by PaienNate** [comment]
> @PaienNate 这个是协议的问题，在shamrock功能设置中选择“消息格式为CQ码”亲测可用。

已解决，感谢
