### ISSUE TITLE
[BUG] 1.5.4.2发消息时报错502 Bad Gateway

### ISSUE THREAD

**Issue by linxp001** [lss233/chatgpt-mirai-qq-bot#127]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
chatgpt.bat启动成功，但发消息时报错502 Bad Gateway

**运行环境:**  
- 操作系统：Windows 10 专业版
- 项目版本：1.5.4.2

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 启动chatgpt
2. 发消息
3. 报错

**预期行为**  
收到chatgpt的答案

**截图**  
![image](https://user-images.githubusercontent.com/75927451/218791107-d1367ea4-502e-4d50-b23d-5f4d9e6a811c.png)
![image](https://user-images.githubusercontent.com/75927451/218791343-0972ca73-6108-4fde-9f20-e198bffabe90.png)

**Comment by lss233** [comment]
你是 plus 用户吗？ 设置  `paid = true`  试试。

**Comment by linxp001** [comment]
> 你是 plus 用户吗？ 设置 `paid = true` 试试。

不是plus用户，设置了paid=true，还是报一样的错误。

**Comment by linxp001** [comment]
> 你是 plus 用户吗？ 设置 `paid = true` 试试。

我是用浏览器直接访问https://chatgpt.duti.tech/就会报502错误，所以我理解这不是程序的问题，而是chatgpt的某个接口挂掉了，是这样吗？

![image](https://user-images.githubusercontent.com/75927451/218899016-f33fa26e-1312-4efb-a599-d4fb51c8021d.png)

**Comment by lss233** [comment]
你是不是改过 revChatGPT 的版本？  你不应该使用这个接口。
https://github.com/acheong08/ChatGPT/issues/735#issuecomment-1429849854

**Comment by linxp001** [comment]
> 你是不是改过 revChatGPT 的版本？ 你不应该使用这个接口。 [acheong08/ChatGPT#735 (comment)](https://github.com/acheong08/ChatGPT/issues/735#issuecomment-1429849854)

那我清空重新部署一遍试试，之前是在原来的版本上做的升级（我没改过revChatGPT 的版本，我都不知道在哪改）。

**Comment by linxp001** [comment]
重新部署解决了，谢谢。
