### ISSUE TITLE
[BUG] 无法正常退出--cannot import name  'url_decode' from 'werkzeug.urls' 

### ISSUE THREAD

**Issue by imRhoAias** [lss233/chatgpt-mirai-qq-bot#1276]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
Requirement already satisfied: Quart==0.17.0 in c:\users\administrator\miniconda
3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 42)) (0.17.0)
Requirement already satisfied: pydub~=0.25.1 in c:\users\administrator\miniconda
3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 43)) (0.25.1)
Requirement already satisfied: httpcore~=0.17.3 in c:\users\administrator\minico
nda3\envs\chatgpt\lib\site-packages (from -r requirements.txt (line 44)) (0.17.3
)
Requirement already satisfied: graia-broadcast~=0.23.0 in c:\users\administrator
\miniconda3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.7->-r requi
rements.txt (line 2)) (0.23.4)
Requirement already satisfied: typing-extensions<5.0,>=4.4 in c:\users\administr
ator\miniconda3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.7->-r r
equirements.txt (line 2)) (4.9.0)
Requirement already satisfied: graia-amnesia~=0.7.0 in c:\users\administrator\mi
niconda3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.7->-r requirem
ents.txt (line 2)) (0.7.1)
Requirement already satisfied: launart<0.7,>=0.6.4 in c:\users\administrator\min
iconda3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.7->-r requireme
nts.txt (line 2)) (0.6.4)
Requirement already satisfied: packaging>=23.0 in c:\users\administrator\minicon
da3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.7->-r requirements.
txt (line 2)) (23.2)
Requirement already satisfied: creart~=0.3.0 in c:\users\administrator\miniconda
3\envs\chatgpt\lib\site-packages (from graia-ariadne==0.11.7->-r requirements.tx
t (line 2)) (0.3.0)
Requirement already satisfied: websockets in c:\users\administrator\miniconda3\e
nvs\chatgpt\lib\site-packages (from EdgeGPT==0.13.2->-r requirements.txt (line 1
1)) (12.0)
Requirement already satisfied: rich in c:\users\administrator\miniconda3\envs\ch
atgpt\lib\site-packages (from EdgeGPT==0.13.2->-r requirements.txt (line 11)) (1
3.7.0)
Requirement already satisfied: certifi in c:\users\administrator\miniconda3\envs
\chatgpt\lib\site-packages (from EdgeGPT==0.13.2->-r requirements.txt (line 11))
 (2023.7.22)
Requirement already satisfied: prompt-toolkit in c:\users\administrator\minicond
a3\envs\chatgpt\lib\site-packages (from EdgeGPT==0.13.2->-r requirements.txt (li
ne 11)) (3.0.43)
Requirement already satisfied: python-socks in c:\users\administrator\miniconda3
\envs\chatgpt\lib\site-packages (from poe-api==0.5.2->-r requirements.txt (line
14)) (2.4.4)
Requirement already satisfied: quickjs in c:\users\administrator\miniconda3\envs
\chatgpt\lib\site-packages (from poe-api==0.5.2->-r requirements.txt (line 14))
(1.19.4)
Requirement already satisfied: websocket-client in c:\users\administrator\minico
nda3\envs\chatgpt\lib\site-packages (from poe-api==0.5.2->-r requirements.txt (l
ine 14)) (1.7.0)
Requirement already satisfied: aiofiles in c:\users\administrator\miniconda3\env
s\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 42))
(23.2.1)
Requirement already satisfied: blinker in c:\users\administrator\miniconda3\envs
\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 42)) (
1.7.0)
Requirement already satisfied: click in c:\users\administrator\miniconda3\envs\c
hatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 42)) (8.
1.7)
Requirement already satisfied: hypercorn>=0.11.2 in c:\users\administrator\minic
onda3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (l
ine 42)) (0.15.0)
Requirement already satisfied: itsdangerous in c:\users\administrator\miniconda3
\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 4
2)) (2.1.2)
Requirement already satisfied: jinja2 in c:\users\administrator\miniconda3\envs\
chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 42)) (3
.1.2)
Requirement already satisfied: markupsafe in c:\users\administrator\miniconda3\e
nvs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (line 42)
) (2.1.3)
Requirement already satisfied: werkzeug>=2.0.0 in c:\users\administrator\minicon
da3\envs\chatgpt\lib\site-packages (from Quart==0.17.0->-r requirements.txt (lin
e 42)) (3.0.1)
Requirement already satisfied: cryptography>=3.1 in c:\users\administrator\minic
onda3\envs\chatgpt\lib\site-packages (from wechatpy~=2.0.0a26->-r requirements.t
xt (line 6)) (41.0.7)
Requirement already satisfied: optionaldict>=0.1.0 in c:\users\administrator\min
iconda3\envs\chatgpt\lib\site-packages (from wechatpy~=2.0.0a26->-r requirements
.txt (line 6)) (0.1.2)
Requirement already satisfied: requests-pkcs12<2.0,>=1.7 in c:\users\administrat
or\miniconda3\envs\chatgpt\lib\site-packages (from wechatpy~=2.0.0a26->-r requir
ements.txt (line 6)) (1.22)
Requirement already satisfied: xmltodict>=0.11.0 in c:\users\administrator\minic
onda3\envs\chatgpt\lib\site-packages (from wechatpy~=2.0.0a26->-r requirements.t
xt (line 6)) (0.13.0)
Requirement already satisfied: tqdm in c:\users\administrator\miniconda3\envs\ch
atgpt\lib\site-packages (from openai~=0.27.8->-r requirements.txt (line 10)) (4.
66.1)
Requirement already satisfied: colorama>=0.3.4 in c:\users\administrator\minicon
da3\envs\chatgpt\lib\site-packages (from loguru~=0.7.0->-r requirements.txt (lin
e 25)) (0.4.6)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\administrator\m
iniconda3\envs\chatgpt\lib\site-packages (from loguru~=0.7.0->-r requirements.tx
t (line 25)) (1.1.0)
Requirement already satisfied: six in c:\users\administrator\miniconda3\envs\cha
tgpt\lib\site-packages (from imgkit~=1.2.3->-r requirements.txt (line 31)) (1.16
.0)
Requirement already satisfied: pypng in c:\users\administrator\miniconda3\envs\c
hatgpt\lib\site-packages (from qrcode~=7.4.2->-r requirements.txt (line 32)) (0.
20220715.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\administrator\miniconda
3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (line
 33)) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\administ
rator\miniconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r require
ments.txt (line 33)) (3.3.2)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\administrator\min
iconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt
 (line 33)) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\administr
ator\miniconda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirem
ents.txt (line 33)) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\administrator\minicond
a3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (lin
e 33)) (1.9.4)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\administrator\minic
onda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (
line 33)) (1.4.1)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\administrator\minico
nda3\envs\chatgpt\lib\site-packages (from aiohttp~=3.8.5->-r requirements.txt (l
ine 33)) (1.3.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\administrator\miniconda3
\envs\chatgpt\lib\site-packages (from requests~=2.31.0->-r requirements.txt (lin
e 35)) (3.6)
Requirement already satisfied: sniffio in c:\users\administrator\miniconda3\envs
\chatgpt\lib\site-packages (from httpx~=0.24.1->-r requirements.txt (line 41)) (
1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\administrator\minicon
da3\envs\chatgpt\lib\site-packages (from httpcore~=0.17.3->-r requirements.txt (
line 44)) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\administrator\minicon
da3\envs\chatgpt\lib\site-packages (from httpcore~=0.17.3->-r requirements.txt (
line 44)) (4.1.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\administrator\m
iniconda3\envs\chatgpt\lib\site-packages (from anyio<5.0,>=3.0->httpcore~=0.17.3
->-r requirements.txt (line 44)) (1.2.0)
Requirement already satisfied: importlib-metadata>=3.6 in c:\users\administrator
\miniconda3\envs\chatgpt\lib\site-packages (from creart~=0.3.0->graia-ariadne==0
.11.7->-r requirements.txt (line 2)) (7.0.0)
Requirement already satisfied: cffi>=1.12 in c:\users\administrator\miniconda3\e
nvs\chatgpt\lib\site-packages (from cryptography>=3.1->wechatpy~=2.0.0a26->-r re
quirements.txt (line 6)) (1.16.0)
Requirement already satisfied: statv>=0.2.2 in c:\users\administrator\miniconda3
\envs\chatgpt\lib\site-packages (from graia-amnesia~=0.7.0->graia-ariadne==0.11.
7->-r requirements.txt (line 2)) (0.3.2)
Requirement already satisfied: socksio==1.* in c:\users\administrator\miniconda3
\envs\chatgpt\lib\site-packages (from httpx[socks]>=0.24.0->EdgeGPT==0.13.2->-r
requirements.txt (line 11)) (1.0.0)
Requirement already satisfied: h2>=3.1.0 in c:\users\administrator\miniconda3\en
vs\chatgpt\lib\site-packages (from hypercorn>=0.11.2->Quart==0.17.0->-r requirem
ents.txt (line 42)) (4.1.0)
Requirement already satisfied: priority in c:\users\administrator\miniconda3\env
s\chatgpt\lib\site-packages (from hypercorn>=0.11.2->Quart==0.17.0->-r requireme
nts.txt (line 42)) (2.0.0)
Requirement already satisfied: taskgroup in c:\users\administrator\miniconda3\en
vs\chatgpt\lib\site-packages (from hypercorn>=0.11.2->Quart==0.17.0->-r requirem
ents.txt (line 42)) (0.0.0a4)
Requirement already satisfied: tomli in c:\users\administrator\miniconda3\envs\c
hatgpt\lib\site-packages (from hypercorn>=0.11.2->Quart==0.17.0->-r requirements
.txt (line 42)) (2.0.1)
Requirement already satisfied: wsproto>=0.14.0 in c:\users\administrator\minicon
da3\envs\chatgpt\lib\site-packages (from hypercorn>=0.11.2->Quart==0.17.0->-r re
quirements.txt (line 42)) (1.2.0)
Requirement already satisfied: wcwidth in c:\users\administrator\miniconda3\envs
\chatgpt\lib\site-packages (from prompt-toolkit->EdgeGPT==0.13.2->-r requirement
s.txt (line 11)) (0.2.12)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\administrator\
miniconda3\envs\chatgpt\lib\site-packages (from requests[socks]->poe-api==0.5.2-
>-r requirements.txt (line 14)) (1.7.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\administrator\m
iniconda3\envs\chatgpt\lib\site-packages (from rich->EdgeGPT==0.13.2->-r require
ments.txt (line 11)) (3.0.0)
Requirement already satisfied: pycparser in c:\users\administrator\miniconda3\en
vs\chatgpt\lib\site-packages (from cffi>=1.12->cryptography>=3.1->wechatpy~=2.0.
0a26->-r requirements.txt (line 6)) (2.21)
Requirement already satisfied: hyperframe<7,>=6.0 in c:\users\administrator\mini
conda3\envs\chatgpt\lib\site-packages (from h2>=3.1.0->hypercorn>=0.11.2->Quart=
=0.17.0->-r requirements.txt (line 42)) (6.0.1)
Requirement already satisfied: hpack<5,>=4.0 in c:\users\administrator\miniconda
3\envs\chatgpt\lib\site-packages (from h2>=3.1.0->hypercorn>=0.11.2->Quart==0.17
.0->-r requirements.txt (line 42)) (4.0.0)
Requirement already satisfied: zipp>=0.5 in c:\users\administrator\miniconda3\en
vs\chatgpt\lib\site-packages (from importlib-metadata>=3.6->creart~=0.3.0->graia
-ariadne==0.11.7->-r requirements.txt (line 2)) (3.17.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\administrator\miniconda3\e
nvs\chatgpt\lib\site-packages (from markdown-it-py>=2.2.0->rich->EdgeGPT==0.13.2
->-r requirements.txt (line 11)) (0.1.2)
[2023-12-15 18:24:41.296] [info] 启动程序
2023-12-15 18:24:42.662 | ERROR    | config:scan_presets:567 - 检查预设：玲珑 <=
=> presets/linglong.txt [失败：文件不存在]
2023-12-15 18:24:42.678 | SUCCESS  | config:scan_presets:565 - 检查预设：猫娘 <=
=> presets/catgirl.txt [成功]
2023-12-15 18:24:42.678 | SUCCESS  | config:scan_presets:578 - 注册预设：catgirl
 <==> ./presets\catgirl.txt [成功]
2023-12-15 18:24:42.678 | SUCCESS  | config:scan_presets:578 - 注册预设：catgirl
_en <==> ./presets\catgirl_en.txt [成功]
2023-12-15 18:24:42.678 | SUCCESS  | config:scan_presets:578 - 注册预设：issue40
2 <==> ./presets\issue402.txt [成功]
2023-12-15 18:24:42.678 | SUCCESS  | config:scan_presets:578 - 注册预设：预设模
板 <==> ./presets\预设模板.txt [成功]
2023-12-15 18:24:42.740 | INFO     | manager.bot:login_bing:219 - 正在解析第 1
个 Bing 账号
2023-12-15 18:24:42.740 | SUCCESS  | manager.bot:login_bing:224 - 解析成功！
2023-12-15 18:24:42.740 | SUCCESS  | manager.bot:login_bing:230 - 成功解析 1/1
个 Bing 账号！
2023-12-15 18:24:42.740 | INFO     | manager.bot:login_slack:254 - 正在解析第 1
个 Claude (Slack) 账号
2023-12-15 18:24:42.740 | SUCCESS  | manager.bot:login_slack:258 - 解析成功！
2023-12-15 18:24:42.740 | SUCCESS  | manager.bot:login_slack:264 - 成功解析 1/1
个 Claude (Slack) 账号！
2023-12-15 18:24:42.740 | INFO     | manager.bot:handle_openai:107 - 当前的 brow
serless_endpoint 为：https://chatgpt-proxy.lss233.com/api/
2023-12-15 18:24:42.740 | INFO     | manager.bot:handle_openai:123 - 当前的 api_
endpoint 为：https://api.chatanywhere.com.cn/v1
2023-12-15 18:24:42.740 | INFO     | manager.bot:login_openai:340 - 正在登录第 1
 个 OpenAI 账号
2023-12-15 18:24:42.756 | INFO     | manager.bot:__login_openai_apikey:527 - 尝
试使用 api_key 登录中...
2023-12-15 18:24:42.756 | INFO     | manager.bot:__login_openai_apikey:531 - 当
前检查的 API Key 为：sk-U6LMe******eflj
2023-12-15 18:24:42.756 | WARNING  | manager.bot:__login_openai_apikey:534 - 在
查询 API 额度时遇到问题，请自行确认额度。
2023-12-15 18:24:42.756 | SUCCESS  | manager.bot:login_openai:354 - 登录成功！
2023-12-15 18:24:42.756 | INFO     | manager.bot:login_openai:340 - 正在登录第 2
 个 OpenAI 账号
2023-12-15 18:24:42.756 | INFO     | manager.bot:__login_openai_apikey:527 - 尝
试使用 api_key 登录中...
2023-12-15 18:24:42.756 | INFO     | manager.bot:__login_openai_apikey:531 - 当
前检查的 API Key 为：sk-ZxHpA******oXvC
2023-12-15 18:24:42.756 | WARNING  | manager.bot:__login_openai_apikey:534 - 在
查询 API 额度时遇到问题，请自行确认额度。
2023-12-15 18:24:42.756 | SUCCESS  | manager.bot:login_openai:354 - 登录成功！
2023-12-15 18:24:42.772 | SUCCESS  | manager.bot:login_openai:375 - 成功登录 2/2
 个 OpenAI 账号！
2023-12-15 18:24:42.772 | INFO     | manager.bot:login:173 - AI 类型：chatgpt-we
b - 可用账号： 0 个
2023-12-15 18:24:42.772 | INFO     | manager.bot:login:173 - AI 类型：openai-api
 - 可用账号： 2 个
2023-12-15 18:24:42.772 | INFO     | manager.bot:login:173 - AI 类型：poe-web -
可用账号： 0 个
2023-12-15 18:24:42.772 | INFO     | manager.bot:login:173 - AI 类型：bing-cooki
e - 可用账号： 1 个
2023-12-15 18:24:42.772 | INFO     | manager.bot:login:173 - AI 类型：bard-cooki
e - 可用账号： 0 个
2023-12-15 18:24:42.772 | INFO     | manager.bot:login:173 - AI 类型：yiyan-cook
ie - 可用账号： 0 个
2023-12-15 18:24:42.772 | INFO     | manager.bot:login:173 - AI 类型：xinghuo-co
okie - 可用账号： 0 个
2023-12-15 18:24:42.772 | INFO     | manager.bot:login:173 - AI 类型：chatglm-ap
i - 可用账号： 0 个
2023-12-15 18:24:42.772 | INFO     | manager.bot:login:173 - AI 类型：slack-acce
sstoken - 可用账号： 1 个
2023-12-15 18:24:42.787 | INFO     | __main__:<module>:25 - 检测到 Onebot 配置，
将启动 Onebot 模式……
2023-12-15 18:24:42.975 | ERROR    | utils.exithooks:foo:35 - 看样子程序似乎没有
正常退出。
2023-12-15 18:24:42.975 | ERROR    | utils.exithooks:foo:36 - cannot import name
 'url_decode' from 'werkzeug.urls' (C:\Users\Administrator\Miniconda3\envs\chatg
pt\lib\site-packages\werkzeug\urls.py)
NoneType: None
2023-12-15 18:24:42.990 | ERROR    | utils.exithooks:foo:37 - 你可以在这里阅读常
见问题的解决方案：
2023-12-15 18:24:42.990 | ERROR    | utils.exithooks:foo:38 - https://github.com
/lss233/chatgpt-mirai-qq-bot/issues/85
Exception ignored in atexit callback: <function foo at 0x0000002AA5F1A7A0>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2
.5.3\chatgpt-mirai-qq-bot\utils\exithooks.py", line 39, in foo
    raise hooks.exception
  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2
.5.3\chatgpt-mirai-qq-bot\bot.py", line 26, in <module>
    from platforms.onebot_bot import start_task
  File "C:\Users\Administrator\Desktop\Windows-quickstart-go-cqhttp-refs.tags.v2
.5.3\chatgpt-mirai-qq-bot\platforms\onebot_bot.py", line 7, in <module>
    from aiocqhttp import CQHttp, Event, MessageSegment
  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\site-packages\aiocqht
tp\__init__.py", line 19, in <module>
    from quart import Quart, request, abort, jsonify, websocket, Response
  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\site-packages\quart\_
_init__.py", line 7, in <module>
    from .app import Quart
  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\site-packages\quart\a
pp.py", line 46, in <module>
    from .asgi import ASGIHTTPConnection, ASGILifespan, ASGIWebsocketConnection
  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\site-packages\quart\a
sgi.py", line 29, in <module>
    from .debug import traceback_response
  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\site-packages\quart\d
ebug.py", line 8, in <module>
    from .wrappers import Response
  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\site-packages\quart\w
rappers\__init__.py", line 4, in <module>
    from .request import Body, Request
  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\site-packages\quart\w
rappers\request.py", line 23, in <module>
    from ..formparser import FormDataParser
  File "C:\Users\Administrator\Miniconda3\envs\chatgpt\lib\site-packages\quart\f
ormparser.py", line 23, in <module>
    from werkzeug.urls import url_decode
ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (C:\Users\Admi
nistrator\Miniconda3\envs\chatgpt\lib\site-packages\werkzeug\urls.py)
[2023-12-15 18:24:43.193] [info] 按任意键退出...

**运行环境:*windows*  
- 操作系统：2012r2
- Docker： ？
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
有看到Linux的解决方案，但是Windows如何解决）求教

**Comment by shuaigejason** [comment]
哥你是怎么解决的

**Comment by imRhoAias** [comment]
![39IJU~%55%$(W3ZFB2FL(GT](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/133833496/c8cc47ca-0f61-45c9-b2ad-4cba1d96c0e6)
有个issues里面有人发了这个包，你直接把这个包丢在目录下面就行了，那个issues也是提的这个问题，你可以找找

**Comment by imRhoAias** [comment]
> 哥你是怎么解决的
![39IJU~%55%$(W3ZFB2FL(GT](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/133833496/196e50d9-a8a4-4ef6-874a-676408433717)
有个issues里面有人发了这个包，你直接把这个包丢在目录下面就行了，那个issues也是提的这个问题，你可以找找

**Comment by Hooray0012** [comment]
werkzeug版本太新了（指3.0以上）降级到2.x就好了
