### ISSUE TITLE
[Feature] 请在此处填写标题 DALL-E 3 新增

### ISSUE THREAD

**Issue by joep1000** [lss233/chatgpt-mirai-qq-bot#1277]
您好，ChatGPT-QQ 开发团队。
我是来自海外的 ChatGPT-QQ 用户，非常喜欢在我的 Discord 服务器上使用你们的机器人。我注意到该机器人目前支持 DALL-E 2 API，但我想问一下，你们是否可以考虑添加对 DALL-E 3 API 的支持，或者给我指出一个方向，告诉我如何在 linux 服务器上的 docker compose 容器的机器人设置中启用该 API？
DALL-E 3确实是图像生成方面的一个巨大进步，我相信添加这个功能会让ChatGPT-QQ机器人变得更好。再次感谢你们付出的时间和努力，因为这是一个了不起的机器人，我也会一如既往地期待你们的回复和更新！
提前感谢您！
乔普

**Comment by huangzhitian** [comment]
> 您好，ChatGPT-QQ 开发团队。 我是来自海外的 ChatGPT-QQ 用户，非常喜欢在我的 Discord 服务器上使用你们的机器人。我注意到该机器人目前支持 DALL-E 2 API，但我想问一下，你们是否可以考虑添加对 DALL-E 3 API 的支持，或者给我指出一个方向，告诉我如何在 linux 服务器上的 docker compose 容器的机器人设置中启用该 API？ DALL-E 3确实是图像生成方面的一个巨大进步，我相信添加这个功能会让ChatGPT-QQ机器人变得更好。再次感谢你们付出的时间和努力，因为这是一个了不起的机器人，我也会一如既往地期待你们的回复和更新！ 提前感谢您！ 乔普

![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/129321746/ddc3c962-c4df-4fcb-bba2-b2c1e355d486)

**Comment by joep1000** [comment]
非常感谢！这真是个奇迹

**Comment by joep1000** [comment]
> > 您好，ChatGPT-QQ 开发团队。 我是来自海外的 ChatGPT-QQ 用户，非常喜欢在我的 Discord 服务器上使用你们的机器人。我注意到该机器人目前支持 DALL-E 2 API，但我想问一下，你们是否可以考虑添加对 DALL-E 3 API 的支持，或者给我指出一个方向，告诉我如何在 linux 服务器上的 docker compose 容器的机器人设置中启用该 API？ DALL-E 3确实是图像生成方面的一个巨大进步，我相信添加这个功能会让ChatGPT-QQ机器人变得更好。再次感谢你们付出的时间和努力，因为这是一个了不起的机器人，我也会一如既往地期待你们的回复和更新！ 提前感谢您！ 乔普
> 
> ![image](https://private-user-images.githubusercontent.com/129321746/291227765-ddc3c962-c4df-4fcb-bba2-b2c1e355d486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTA5MDgsIm5iZiI6MTcwMjkxMDYwOCwicGF0aCI6Ii8xMjkzMjE3NDYvMjkxMjI3NzY1LWRkYzNjOTYyLWM0ZGYtNGZjYi1iYmEyLWIyYzFlMzU1ZDQ4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQxNDQzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZmI0MmYxMTlhZmZlMDYwNWVlOWY2NmFmMjg0MGIzZDQyOTU0NDNjYWVkODVjNmJjZjk5YWVkMjIzZWU2YTZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E7eyco3lTL186ovbU5yLGBin1TW5HX6BjEsf21QX-ws)


非常感谢！这真是个奇迹
