### ISSUE TITLE
[BUG] 1.5.4.2浏览器版本部署后聊天无反应

### ISSUE THREAD

**Issue by LayerLwb** [lss233/chatgpt-mirai-qq-bot#129]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
使用xpra登录后，服务端没有获取sessionkey的动作，和机器人聊天没有反应

**运行环境:**  
- 操作系统：Centos
- Docker： 一键部署脚本
- 项目版本：1.5.4.2

**复现步骤**  
描述你是如何触发这个 BUG 的
1. docker-compose up

**截图**  
启动日志如下：
[root@VM-0-12-centos chatgpt-qq]# docker-compose up
[+] Running 3/3
 ? Network chatgpt-qq_default      Created                                                                                                                                              0.0s
 ? Container chatgpt-qq-chatgpt-1  Created                                                                                                                                              0.1s
 ? Container chatgpt-qq-mirai-1    Created                                                                                                                                              0.1s
Attaching to chatgpt-qq-chatgpt-1, chatgpt-qq-mirai-1
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  | Warning: running as root
chatgpt-qq-mirai-1    |   00:55:43 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
chatgpt-qq-mirai-1    |   00:55:43 [INFO] Runtime: OpenJDK 64-Bit Server VM 17.0.2 (arch: 64)
chatgpt-qq-mirai-1    |   00:55:43 [INFO] https://github.com/iTXTech/mirai-console-loader
chatgpt-qq-mirai-1    |   00:55:43 [INFO] This program is licensed under GNU AGPL v3
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:43,632 Warning: cannot enable SSH socket upgrades
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:43,632  No module named 'paramiko'
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:43,632 created tcp socket '0.0.0.0:14500'
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:43,661 no uinput module (not usually needed)
chatgpt-qq-mirai-1    |   00:55:43 [INFO] BouncyCastle is installed because OracleJDK is detected.
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,413 pointer device emulation using XTest
chatgpt-qq-mirai-1    |   00:55:45 [INFO] Mirai Console Loader Announcement:
chatgpt-qq-mirai-1    | Mirai Console Loader 公告栏
chatgpt-qq-mirai-1    | 
chatgpt-qq-mirai-1    | 如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
chatgpt-qq-mirai-1    | `- 如 Unsupported image type for ExternalResource *
chatgpt-qq-mirai-1    | `  considering use gif/png/bmp/jpg format.
chatgpt-qq-mirai-1    | `- Tracker: https://github.com/mamoe/mirai/issues/new/choose
chatgpt-qq-mirai-1    | 
chatgpt-qq-mirai-1    | 常用资源整合
chatgpt-qq-mirai-1    | `- https://mirai.mamoe.net/topic/653
chatgpt-qq-mirai-1    |  
chatgpt-qq-mirai-1    | MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。
chatgpt-qq-mirai-1    | 
chatgpt-qq-mirai-1    |   00:55:45 [INFO] Verifying "net.mamoe:mirai-console" v2.14.0
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,506 serving html content from '/usr/share/xpra/www'
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,509 wrote pid 7 to '/tmp/0/server.pid'
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,602 Warning: socket directory '/tmp/0'
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,602  expected permissions 700 but found 750
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,603 created unix domain socket '/run/user/1000/xpra/8da651fc9de3-0'
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,603 created unix domain socket '/tmp/0/socket'
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,606 xvfb pid=11
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,718 Warning: cannot watch for application menu changes without pyinotify:
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,719  No module named 'pyinotify'
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,728 Warning: cannot load menu data
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,729  No module named 'xdg'
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,816 Warning: webcam forwarding is disabled
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,817  the virtual video directory '/sys/devices/virtual/video4linux' was not found
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,817  make sure that the 'v4l2loopback' kernel module is installed and loaded
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,817  or use the 'webcam=no' option
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,817 found 0 virtual video devices for webcam forwarding
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:45,820 started command `xterm -e python bot.py 2>&1 | tee /tmp/log.txt` with pid 37
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:46,148 1.9GB of system memory
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:46,244 Warning: OpenGL support check failed:
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:46,244  unknown error
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:46,246 xpra is ready.
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:46,247 xpra X11 seamless version 4.4.3-r0 64-bit
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:46,247  uid=0 (root), gid=0 (root)
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:46,247  running with pid 7 on Linux Debian 11 bullseye
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:46,248  connected to X11 display :0 with 24 bit colors
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:47.227 | INFO     | chatbot:<module>:16 - 登录 OpenAI 中...
chatgpt-qq-mirai-1    |   00:55:47 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.14.0
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:47.599 | INFO     | chatbot:<module>:23 - 当前模式：浏览器直接访问
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:47.599 | INFO     | chatbot:<module>:24 - 这需要你拥有最新版的 Chrome 浏览器。
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:47.599 | INFO     | chatbot:<module>:25 - 即将打开浏览器窗口……
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:47.599 | INFO     | chatbot:<module>:26 - 提示：如果你看见了 Cloudflare 验证码，请手动完成验证。
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:47.599 | INFO     | chatbot:<module>:27 - 如果浏览器反复弹出，请阅读项目 FAQ。
chatgpt-qq-chatgpt-1  | 2023-02-15 00:55:47.599 | INFO     | chatbot:<module>:30 - 如果您使用 xpra，请使用自己的浏览器访问 xpra 程序的端口，以访问到本程序启动的浏览器。
chatgpt-qq-mirai-1    |   00:55:47 [INFO] Verifying "net.mamoe:mirai-core-all" v2.14.0
chatgpt-qq-mirai-1    |   00:55:48 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
chatgpt-qq-mirai-1    |   00:55:49 [INFO] Verifying "net.mamoe:mirai-api-http" v2.8.0
chatgpt-qq-mirai-1    |   00:55:49 [INFO] Verifying "xyz.cssxsh.mirai:mirai-device-generator" v1.1.3
chatgpt-qq-mirai-1    |   00:55:49 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on"
chatgpt-qq-mirai-1    |   00:55:49 [INFO] File "bcprov-jdk15on-1.64.jar" has been deleted.
chatgpt-qq-mirai-1    |   00:55:49 [INFO] File "bcprov-jdk15on-1.64.jar.sha1" has been deleted.
chatgpt-qq-mirai-1    |   00:55:49 [INFO] Updating "org.bouncycastle:bcprov-jdk15on" to v1.64
 Downloading bcprov-jdk15on-1.64.jar [==============================] 4.55 MB                        B / 4.55 MB (0.0%)   
 Downloading bcprov-jdk15on-1.64.jar.sha1 [==============================] 40 B                    40 B / 40 B (100.0%)   
chatgpt-qq-mirai-1    | 2023-02-15 00:55:56 I/main: Starting mirai-console...
chatgpt-qq-mirai-1    | 2023-02-15 00:55:56 I/main: 
chatgpt-qq-mirai-1    | 
chatgpt-qq-mirai-1    | ==================================[ Mirai consosle 2.14.0 ]===================================
chatgpt-qq-mirai-1    |  __       __ __                   __  ______                                      __
chatgpt-qq-mirai-1    | |  \     /  \  \                 |  \/      \                                    |  \
chatgpt-qq-mirai-1    | | ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
chatgpt-qq-mirai-1    | | ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
chatgpt-qq-mirai-1    | | ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
chatgpt-qq-mirai-1    | | ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
chatgpt-qq-mirai-1    | | ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
chatgpt-qq-mirai-1    | | ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
chatgpt-qq-mirai-1    |  \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓
chatgpt-qq-mirai-1    | 
chatgpt-qq-mirai-1    | 
chatgpt-qq-mirai-1    | 2023-02-15 00:55:56 I/main: Backend: version 2.14.0, built on 2023-02-06 06:25:21.
chatgpt-qq-mirai-1    | 2023-02-15 00:55:56 I/main: Frontend Terminal: version 2.14.0, provided by Mamoe Technologies
chatgpt-qq-mirai-1    | 2023-02-15 00:55:56 I/main: Welcome to visit https://mirai.mamoe.net/
chatgpt-qq-mirai-1    | 2023-02-15 00:55:58 I/plugin: Successfully loaded plugin mirai-api-http v2.8.0
chatgpt-qq-mirai-1    | 2023-02-15 00:55:58 I/plugin: Successfully loaded plugin mirai-device-generator v1.1.3
chatgpt-qq-mirai-1    | 2023-02-15 00:55:58 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
chatgpt-qq-mirai-1    | 2023-02-15 00:55:58 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
chatgpt-qq-mirai-1    | 2023-02-15 00:55:58 I/Mirai HTTP API: ********************************************************
chatgpt-qq-mirai-1    | 2023-02-15 00:55:59 I/MahKtorAdapter[http,ws]: Autoreload is disabled because the development mode is off.
chatgpt-qq-mirai-1    | 2023-02-15 00:55:59 I/MahKtorAdapter[http,ws]: Application started in 0.342 seconds.
chatgpt-qq-mirai-1    | 2023-02-15 00:55:59 I/MahKtorAdapter[http,ws]: Responding at http://mirai:8080
chatgpt-qq-mirai-1    | 2023-02-15 00:55:59 I/http adapter: >>> [http adapter] is listening at http://mirai:8080
chatgpt-qq-mirai-1    | 2023-02-15 00:55:59 I/ws adapter: >>> [ws adapter] is listening at ws://mirai:8080
chatgpt-qq-mirai-1    | 2023-02-15 00:55:59 I/Mirai HTTP API: Http api server is running with verifyKey: 1234567890
chatgpt-qq-mirai-1    | 2023-02-15 00:55:59 I/Mirai HTTP API: adaptors: [http,ws]
chatgpt-qq-mirai-1    | 2023-02-15 00:55:59 I/Mirai HTTP API: ********************************************************
chatgpt-qq-mirai-1    | 2023-02-15 00:55:59 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
chatgpt-qq-mirai-1    | 2023-02-15 00:55:59 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
chatgpt-qq-mirai-1    | 2023-02-15 00:55:59 I/main: 3 plugin(s) enabled.
chatgpt-qq-mirai-1    | 2023-02-15 00:55:59 I/main: Auto-login 372841461, protocol: ANDROID_WATCH, heartbeatStrategy: STAT_HB
chatgpt-qq-mirai-1    | 2023-02-15 00:56:00 I/Bot.372841461: Loaded account secrets from local cache.
chatgpt-qq-mirai-1    | 2023-02-15 00:56:01 I/Bot.372841461: Saved account secrets to local cache for fast login.
chatgpt-qq-mirai-1    | 2023-02-15 00:56:01 I/Bot.372841461: Login successful.
chatgpt-qq-mirai-1    | 2023-02-15 00:56:03 V/Bot.372841461: Event: BotOnlineEvent(bot=Bot(372841461))
chatgpt-qq-mirai-1    | 2023-02-15 00:56:03 I/Bot.372841461: Bot login successful.
chatgpt-qq-mirai-1    | 2023-02-15 00:56:03 I/main: mirai-console started successfully.
chatgpt-qq-mirai-1    | > 2023-02-15 00:56:03 W/console: Closing input service...
chatgpt-qq-mirai-1    | 2023-02-15 00:56:03 V/Bot.372841461: NULL(195111923) -> 你好
chatgpt-qq-mirai-1    | 2023-02-15 00:56:53 V/Bot.372841461: NULL(195111923) -> 你好
![1676425838339](https://user-images.githubusercontent.com/125333571/218907059-f290dc1f-ec05-4369-abc4-81eda5add1b7.png)

**Comment by lss233** [comment]
你这 ChatGPT 都没启动起来，估计是卡 Found session token了， 改成 第三方代理模式 登陆吧。 https://github.com/lss233/chatgpt-mirai-qq-bot/issues/122#issuecomment-1429605530

**Comment by LayerLwb** [comment]
第三方代理
![1676426770270](https://user-images.githubusercontent.com/125333571/218908924-1d275eea-75b7-4067-bafe-f98a48f0d119.jpg)

**Comment by lss233** [comment]
你的镜像太旧了。 在这里看升级方法：https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v1.5.4.2

**Comment by LayerLwb** [comment]
> 你的镜像太旧了。 在这里看升级方法：https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v1.5.4.2

您好，确实是使用https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v1.5.4.2的

`bash -c "$(curl -fsSL https://gist.githubusercontent.com/lss233/54f0f794f2157665768b1bdcbed837fd/raw/chatgpt-mirai-installer-154-16RC3.sh)"`
进行一键部署的

**Comment by lss233** [comment]
你应该看升级方法，而不是部署。

**Comment by LayerLwb** [comment]
> 你应该看升级方法，而不是部署。

感谢解惑，问题已解决
