### ISSUE TITLE
[BUG] 无法登录，captcha.go-cqhttp.com连不上

### ISSUE THREAD

**Issue by 006lp** [lss233/chatgpt-mirai-qq-bot#1290]
**提交 issue 前，请先确认：**
- [✓] 我已看过 **FAQ**，此问题不在列表中
- [✓] 我已看过其他 issue，他们不能解决我的问题 
- [✓] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
无法验证QQ号

**运行环境:**  
- 操作系统：Ubuntu22.04
- Docker：24.0.7
- 项目版本：2.5.3

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 正常一键部署脚本时

**预期行为**  
应该弹出滑动验证码

**截图**  

![Screenshot_2024-01-11-11-49-08-17_61c78dc80ee02b53007c815fefe993e3.jpg](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/144674902/2bfcd87b-813a-43b4-8c99-4313e6b5adc6)

![Screenshot_2024-01-11-11-49-25-19_82b10d9f3584360f08225ddcebbb4f6d.jpg](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/144674902/c714d818-c236-408c-b3b4-ed19187bdcc8)

**其他内容**  

我尝试过直连，更换我的节点到很多地方，均不可访问

**Comment by 006lp** [comment]
有没有解决方案啊？

**Comment by LZDTK** [comment]
[2024-02-17 19:26:22] [WARNING]: 登录需要滑条验证码, 请验证后重试. 
[2024-02-17 19:26:22] [WARNING]: 请选择提交滑块ticket方式: 
[2024-02-17 19:26:22] [WARNING]: 1. 自动提交 
[2024-02-17 19:26:22] [WARNING]: 2. 手动抓取提交 
[2024-02-17 19:26:22] [WARNING]: 请输入(1 - 2)： 
这个地方选择手动抓取提交即可

**Comment by lIlIlllllmeng** [comment]
可以使用手动抓取，手动抓取是可以的，

**Comment by 006lp** [comment]
好的谢谢
