### ISSUE TITLE
启动后报错(104, Connection reset by peer)

### ISSUE THREAD

**Issue by thunder410426** [lss233/chatgpt-mirai-qq-bot#13]
启动后报如下错误
![image](https://user-images.githubusercontent.com/52324730/206662518-6cf91cc4-9e1d-4c56-9b7d-f16b0f160e4c.png)

**Comment by thunder410426** [comment]
是不是那个verufykey需要填，在哪获取呢

**Comment by lss233** [comment]
这个报错应该是你没连上你的 mirai-http-api 吧。  
检查一下配置里面的 `http_url` 和 `ws_url` 所填的地址是不是你 mirai-http-api 配置的地址。
