### ISSUE TITLE
[Feature] 请求支持 LagrangeDev/Lagrange.Core 机器人框架

### ISSUE THREAD

**Issue by HoshinoDesu** [lss233/chatgpt-mirai-qq-bot#1302]
使用QQNT协议，比GOCQ/Mirai稳定

**Comment by lss233** [comment]
Lagrange.Core 使用的是 onebot 协议，应该可以按照 onebot 的方法接入吧？

**Comment by huang583824382** [comment]
> > Lagrange.Core使用的是onebot协议，应该可以按照onebot的方法接入吧？
> 
> 可以的，修改了一些参数成功接入了~

请问修改了哪些参数呢
