### ISSUE TITLE
[BUG] 当QQ中消息为空时，报错free variable 'conversation_handler' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by TNTcraftHIM** [lss233/chatgpt-mirai-qq-bot#1306]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
在发送空消息时，机器人会发送reponse的placeholder，但是后续会马上报错free variable 'conversation_handler' referenced before assignment in enclosing scope

**运行环境:**  
- 操作系统：Debian 11
- Docker： N/A
- 项目版本：d61e547e962403c569620eb00cc206def3937c27

**复现步骤**  
设置机器人为群聊中at触发，不需要其他任何条件
群聊中直接at机器人并不要附上任何文字并发送（或者打空格也可以）
或者私聊发送一个空格给机器人也一样会触发

**预期行为**  
此时应该只发送placeholder，没有后续报错
我尝试在ignore_regex中添加 ^\s*$ 正则来忽略空白，但是似乎不好使，私聊和群聊都是

**截图**  
![日志截图](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/35992542/7791d87b-8eb8-48aa-bc07-c54575cd16ed)

**Comment by lss233** [comment]
感谢建议
