### ISSUE TITLE
[BUG] 1.5.4.2快速部署版本，运行启动chatGPT.cmd，卡在“Found Cloudflare Cookie!”这步

### ISSUE THREAD

**Issue by wayneCui628** [lss233/chatgpt-mirai-qq-bot#131]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
1.5.4.2快速部署版本，使用session token登录，运行启动chatGPT.cmd，自动打开了一个未登录的chrome浏览器；
到了“Found Cloudflare Cookie!”这步，浏览器要求我登录chatGPT，使用google账号登陆之后，终端一直卡在“Found Cloudflare Cookie!”没有变化。

**运行环境:**  
- 操作系统：win 11
- 项目版本：1.5.4.2

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 配置文件：
![HTJ})7Q5~ZLEOOD)DU 0N)6](https://user-images.githubusercontent.com/67955418/218912461-6d0fbacd-77e1-4f66-84ce-3d1bce5b5a2e.png)
2. 运行“启动chatGPT.cmd”
4. 在弹出的未登录chrome浏览器中使用google账号登录chatGPT
5. 发现终端一直卡在“Found Cloudflare Cookie!”没有变化

**Comment by QAQKB** [comment]
我登陆成功后，网页没有自动退出
![image](https://user-images.githubusercontent.com/39039283/218913546-694cf126-feae-4791-ae6a-d7e82c8001ce.png)

**Comment by lss233** [comment]
更新至 https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v1.5.4.3
然后使用第三方代理模式，试试。

**Comment by thechen130** [comment]
> 

网页登录的方式不行了吗

**Comment by lss233** [comment]
> > 
> 
> 网页登录的邮箱密码方式不行了吗

他是 Google 账号登录的。
