### ISSUE TITLE
gohttp安装报错cannot import name 'url_decode' from 'werkzeug.urls'

### ISSUE THREAD

**Issue by Maizi-G** [lss233/chatgpt-mirai-qq-bot#1313]
chatgpt-qq-chatgpt-1     | 2024-02-14 12:20:33.285 | ERROR    | utils.exithooks:foo:35 - 看样子程序似乎没有正常退出。
chatgpt-qq-chatgpt-1     | 2024-02-14 12:20:33.285 | ERROR    | utils.exithooks:foo:36 - cannot import name 'url_decode' from 'werkzeug.urls' (/usr/local/lib/python3.10/site-packages/werkzeug/urls.py)
chatgpt-qq-chatgpt-1     | NoneType: None
chatgpt-qq-chatgpt-1     | 2024-02-14 12:20:33.286 | ERROR    | utils.exithooks:foo:37 - 你可以在这里阅读常见问题的解决方案：
chatgpt-qq-chatgpt-1     | 2024-02-14 12:20:33.286 | ERROR    | utils.exithooks:foo:38 - https://github.com/lss233/chatgpt-mirai-qq-bot/issues/85
错误日志

**Comment by LeSnran** [comment]
刚试了一下，回滚版本，别安装最新版就行

**Comment by lq204710475** [comment]
> 刚试了一下，回滚版本，别安装最新版就行

佬，我用的linux的一键部署脚本，也是这个样子，这咋办呀

**Comment by GarenGoh** [comment]
> 刚试了一下，回滚版本，其他安装最新版本就行

请问一下需要回滚到哪个版本？

**Comment by GarenGoh** [comment]
试了版本改成 v2.5.2 就好了。
详细点就是修改docker-compose.yaml文件，改：image: lss233/chatgpt-mirai-qq-bot:v2.5.2，然后 docker compose up -d
