### ISSUE TITLE
[BUG] 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8566/ws 时出现错误

### ISSUE THREAD

**Issue by ZhuJap** [lss233/chatgpt-mirai-qq-bot#1324]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：windows 11
- Docker： 无
- 项目版本：v3.0.0

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 下载运行初始化.cmd
2. 依赖正常安装
3. 启动ChatGPT.cmd
4. ChatGPT.cmd运行正常
5. 启动go-cqhttp.cmd
6. 扫码登陆后出现连接到反向WebSocket Universal服务器 ws://127.0.0.1:8566/ws 时出现错误

**预期行为**  
扫码运行成功

**截图**  
![微信截图_20240224195041](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/92317850/546744e2-8778-4259-8285-d5f4b299ce0c)
![微信截图_20240224200903](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/92317850/c293530e-ca9a-4665-9ac4-c717f67aca22)
![3](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/92317850/d3ad049e-5de9-46bd-bcd6-81e3f0e35d77)
![4](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/92317850/45406e7c-552e-4199-a2d5-1f37d0a02822)

**其他内容**  
使用Clash加速代理 代理点为香港
**我已按照使用文档解决这问题但是并没有成功**

**Comment by chenxi2333** [comment]
所以是怎么解决的？

**Comment by fangyuan99** [comment]
> > 所以是怎么解决的？
> 
> 我放弃使用最新的版本改用2.5.3后出现（ws://127.0.0.1:8566/ws 时出现错误）时然后按照[https://chatgpt-qq.lss233.com/pei-zhi-wen-jian-jiao-cheng/dui-jie-liao-tian-ping-tai/dui-jie-onebot-gocqhttp#gocqhttp-de-she-zhi-jiao-cheng](url)解决办法成功启用
> 
> 但是我现在不用这个机器人了

有没有别的机器人推荐

**Comment by clark-2468** [comment]
https://github.com/lss233/chatgpt-mirai-qq-bot/issues/1263
我之前也有差不多的问题 可以参考我的步骤解决

**Comment by Zawinzala** [comment]
解决方法：
先去启动chatgpt-installer。应该是会出现： 看样子程序似乎没有正常退出
其实是和那个werkzeug文件有关系，去：https://github.com/lss233/chatgpt-mirai-qq-bot/issues/1261
找到那个文件，替换到你报错的红色目录内的文件
就正常了。

**Comment by MrCuriosity74** [comment]
> > 所以是怎么解决的？
> 
> 我放弃使用最新的版本改用2.5.3后出现（ws://127.0.0.1:8566/ws 时出现错误）时然后按照[https://chatgpt-qq.lss233.com/pei-zhi-wen-jian-jiao-cheng/dui-jie-liao-tian-ping-tai/dui-jie-onebot-gocqhttp#gocqhttp-de-she-zhi-jiao-cheng](url)解决办法成功启用
> 
> 但是我现在不用这个机器人了

你现在用的啥
