### ISSUE TITLE
[BUG] No matching distribution found for 'xxxx'

### ISSUE THREAD

**Issue by thechen130** [lss233/chatgpt-mirai-qq-bot#133]
![image](https://user-images.githubusercontent.com/74664452/218923437-30eba6c0-7054-4ce7-8f5c-1e920d73cff4.png)

**Comment by lss233** [comment]
https://github.com/lss233/chatgpt-mirai-qq-bot/issues/131#issuecomment-1430675756

**Comment by lss233** [comment]
![image](https://user-images.githubusercontent.com/8984680/218927273-197a3f34-d9c5-4545-b476-e3fee947aa94.png)
阿里云更新了，应该是可以了。

**Comment by thechen130** [comment]
还是错误
![image](https://user-images.githubusercontent.com/74664452/218928142-01a4b921-6a8b-4862-9c39-f67f8785dad7.png)

**Comment by thechen130** [comment]
> ![image](https://user-images.githubusercontent.com/8984680/218927273-197a3f34-d9c5-4545-b476-e3fee947aa94.png) 阿里云更新了，应该是可以了。

你好，我该如何操作“初始化.cmd，换一个 pypi 源”，我不太懂

**Comment by lss233** [comment]
阿里云应该已经更新了这个依赖，不需要操作了。

**Comment by thechen130** [comment]
还是失败，看提示应该“No matching distribution found for revChatGPT[unofficial]==2.2.3”，应该是找不到这个2.2.3的版本？
![image](https://user-images.githubusercontent.com/74664452/218931320-fd48d181-4455-46b7-9bec-b9d5f2ca34a8.png)

**Comment by lss233** [comment]
那你编辑 初始化.cmd，然后参考 https://github.com/lss233/chatgpt-mirai-qq-bot/blob/aed689f796ea8e17c9012af31ffcc5ebaa47e57b/.github/quickstarts/windows/scripts/%E5%88%9D%E5%A7%8B%E5%8C%96.cmd#L43
进行修改。

**Comment by thechen130** [comment]
> 

我是在linux上运行的，找不到”初始化.cmd“，尴尬

**Comment by lss233** [comment]
那就不是我的问题了，是你现在用的那个软件源更新太慢。  
你可以   
```
pip3 install -i https://pypi.org/simple/  -r requirements.txt
```

另外，建议你用一键脚本部署，比较方便。
