### ISSUE TITLE
网站里的Windows 快速部署教程（go-cqhttp版)视频挂了

### ISSUE THREAD

**Issue by huangzi0721** [lss233/chatgpt-mirai-qq-bot#1348]
网站里的Windows 快速部署教程（go-cqhttp版)视频挂了

**Comment by qilingseed** [comment]
去西瓜视频搜那个人的名字

**Comment by huangzi0721** [comment]
> 去西瓜视频搜那个人的名字
> 
> 

ok找到了，顺便贴一下视频链接
https://v.ixigua.com/iMhQNJ6p/
