### ISSUE TITLE
[BUG] mirai auto login failed

### ISSUE THREAD

**Issue by woltium** [lss233/chatgpt-mirai-qq-bot#135]
hatgpt-qq-mirai-1  | 2023-02-15 06:08:02 I/main: 3 plugin(s) enabled.
chatgpt-qq-mirai-1  | 2023-02-15 06:08:02 I/main: Auto-login 2546518385, protocol: ANDROID_WATCH, heartbeatStrategy: STAT_HB
chatgpt-qq-mirai-1  | 2023-02-15 06:08:02 I/Bot.2546518385: [SliderCaptcha] 需要滑动验证码, 请按照以下链接的步骤完成滑动验证码, 然后输入获取到的 ticket
chatgpt-qq-mirai-1  | 2023-02-15 06:08:02 I/Bot.2546518385: [SliderCaptcha] Slider captcha required. Please solve the captcha with following link. Type ticket here after completion.
chatgpt-qq-mirai-1  | 2023-02-15 06:08:02 I/Bot.2546518385: [SliderCaptcha] @see https://github.com/project-mirai/mirai-login-solver-selenium
chatgpt-qq-mirai-1  | 2023-02-15 06:08:02 I/Bot.2546518385: [SliderCaptcha] @see https://docs.mirai.mamoe.net/mirai-login-solver-selenium/
chatgpt-qq-mirai-1  | 2023-02-15 06:08:02 I/Bot.2546518385: [SliderCaptcha] 或者输入 TxCaptchaHelper 来使用 TxCaptchaHelper 完成滑动验证码
chatgpt-qq-mirai-1  | 2023-02-15 06:08:02 I/Bot.2546518385: [SliderCaptcha] Or type `TxCaptchaHelper` to resolve slider captcha with TxCaptchaHelper.apk
chatgpt-qq-mirai-1  | 2023-02-15 06:08:02 I/Bot.2546518385: [SliderCaptcha] Captcha link: https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=2546518385&sid=5433990872228984514&cap_cd=xJtE8cz_IQ9J3Oqbu3NfjZzfRqiWd3mj-6UCZsSHeA2jZuteQErLqA**&clientype=1&apptype=2
chatgpt-qq-mirai-1  | LOGIN> > 2023-02-15 06:08:02 E/main: org.jline.reader.EndOfFileException
chatgpt-qq-mirai-1  | org.jline.reader.EndOfFileException
chatgpt-qq-mirai-1  | 	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:653)
chatgpt-qq-mirai-1  | 	at net.mamoe.mirai.console.terminal.JLineInputDaemon.run(JLineInputDaemon.kt:78)
chatgpt-qq-mirai-1  | 	at java.base/java.lang.Thread.run(Thread.java:833)
chatgpt-qq-mirai-1  | 
chatgpt-qq-mirai-1  | 2023-02-15 06:08:02 I/main: mirai-console started successfully.
chatgpt-qq-mirai-1  | > 2023-02-15 06:08:02 W/console: Closing input service...
chatgpt-qq-mirai-1  | 2023-02-15 06:08:02 I/Bot.2546518385: Bot cancelled: Bot closed

**Comment by lss233** [comment]
怎么了
