### ISSUE TITLE
linux一键部署到docker-compose up -d,显示连接超时

### ISSUE THREAD

**Issue by heyuzhou12345675** [lss233/chatgpt-mirai-qq-bot#1362]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
执行命令
bash -c "$(wget -O- https://gist.githubusercontent.com/lss233/2fdd75be3f0724739368d0dcd9d1367d/raw/62a790da4a391af096074b3355c2c2b7ecab3c28/chatgpt-mirai-installer-gocqhttp.sh)"
执行后到
很棒！你已经完成了所有的初始化步骤。
接下来为你启动程序……
+ docker-compose up -d
报
error pulling image configuration: download failed after attempts=6: dial tcp 199.59.149.234:443: i/o timeout

**运行环境:**  
- 操作系统：CentOS
- Docker： Docker version 26.1.4
- 项目版本：[v2.5.3]

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
正常执行安装

**截图**  
![image](https://github.com/user-attachments/assets/65003726-60a0-4a8f-9eb4-a8f9a5321118)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by null0034** [comment]
如果是国内的服务器那需要使用代理，国内无法使用docker官方的镜像仓库 你可以试试我自己建的加速源 https://docker-r.2002xin.cc

**Comment by heyuzhou12345675** [comment]
好的，谢谢。
