### ISSUE TITLE
ERROR    | graia.amnesia.transport.rider:trigger_callbacks:37 - 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by zinc3938** [lss233/chatgpt-mirai-qq-bot#14]
2022-12-09 16:58:31.983 | ERROR    | graia.amnesia.transport.rider:trigger_callbacks:37 - 'NoneType' object has no attribute 'get'
Traceback (most recent call last):

> File "C:\Python39\lib\site-packages\graia\amnesia\transport\common\websocket\shortcut.py", line 20, in wrapper
    return await func(self, io, data)
                 │    │     │   └ '{"_post_method":2,"meta_event_type":"lifecycle","post_type":"meta_event","self_id":2771689516,"sub_type":"connect","time":16...
                 │    │     └ <graia.amnesia.builtins.aiohttp.AiohttpClientWebsocketIO object at 0x000001DFF0702F40>
                 │    └ <WebsocketClientConnection <ConnectionStatus connected=False alive=True verified=False stage=blocking> with 2 callbacks>
                 └ <function WebsocketConnectionMixin._ at 0x000001DFCAF88790>

  File "C:\Python39\lib\site-packages\graia\ariadne\connection\ws.py", line 55, in _
    data = validate_response(data, raising=False)
           │                 └ None
           └ <function validate_response at 0x000001DFCAE55EE0>

  File "C:\Python39\lib\site-packages\graia\ariadne\connection\util.py", line 57, in validate_response
    return data.get("data", data)
           │                └ None
           └ None

**Comment by lss233** [comment]
检查一下配置里面的 http_url 和 ws_url 所填的地址是不是你 mirai-http-api 配置的地址。
以及所用的软件版本是多少？

**Comment by BlueGlassBlock** [comment]
合理怀疑你使用了 `go-cqhttp` 而不是 `mirai-api-http`。二者通信协议完全不同且不能混用。
