### ISSUE TITLE
[BUG] QQ和网页ChatGPT都登录成功了，QQ就是没有回复

### ISSUE THREAD

**Issue by joe12801** [lss233/chatgpt-mirai-qq-bot#143]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
![image](https://user-images.githubusercontent.com/70465495/219265949-450b1dfc-fdb4-4083-8569-5bfa8745f5ca.png)
![image](https://user-images.githubusercontent.com/70465495/219265995-933e0e77-8d75-426c-81a0-73206f14e169.png)

![image](https://user-images.githubusercontent.com/70465495/219266406-e0185893-ee49-44fe-b77b-0affae3ddaec.png)
我的机器是debin
我使用新人Docker那个脚本安装的，所有东西都安装成功了，QQ机器 都没有回复

**Comment by lss233** [comment]
浏览器登录模式似乎是坏了。
先用无浏览器登录模式吧。

**Comment by dutengfei** [comment]
浏览器模式  Found session token,无浏览器模式就报这个
![图片](https://user-images.githubusercontent.com/24752247/219282591-b6b3dbef-5612-411b-8191-93841aa5f5cc.png)

**Comment by lss233** [comment]
> 浏览器模式 Found session token,无浏览器模式就报这个
> ![图片](https://user-images.githubusercontent.com/24752247/219282591-b6b3dbef-5612-411b-8191-93841aa5f5cc.png)

原因暂不详，试试无浏览器 session token 登录？

**Comment by lss233** [comment]
关于这个问题的跟进，这里有一个小调查： #147

**Comment by dutengfei** [comment]
我还是无法登录，使用无浏览器 session token 也是同样的结果

**Comment by lss233** [comment]
试试 v1.5.6 的 accessToken 登录吧。

**Comment by lss233** [comment]
stale
