### ISSUE TITLE
[BUG] Mirai登录成功发送消息机器无回复

### ISSUE THREAD

**Issue by CCl333** [lss233/chatgpt-mirai-qq-bot#144]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [ √] 我已看过其他 issue，他们不能解决我的问题 
- [√ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况
使用docker-compose up 启动之后，发送消息无回复，chatgpt_1好像没有启动成功
![image](https://user-images.githubusercontent.com/48637219/219274075-1a8cb77a-d6cf-480d-98e6-da4518a4bf51.png)
![image](https://user-images.githubusercontent.com/48637219/219274297-1fb20e6d-18f5-4293-ad20-410d02ee506d.png)
是通过
Linux: 通过 Docker Compose 部署 （自带 Mirai)
方式部署的
**运行环境:**  
- 操作系统：阿里云 Linux
- Docker： ？
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
chatgpt的日志发一下，看不见启动情况。

**Comment by CCl333** [comment]
> chatgpt的日志发一下，看不见启动情况。

![image](https://user-images.githubusercontent.com/48637219/219281281-07d8cbc2-f387-4eee-a5ea-8880d8c23dea.png)

**Comment by lss233** [comment]
> > chatgpt的日志发一下，看不见启动情况。
> 
> ![image](https://user-images.githubusercontent.com/48637219/219281281-07d8cbc2-f387-4eee-a5ea-8880d8c23dea.png)

后面没有了吗？

**Comment by CCl333** [comment]
> > > chatgpt的日志发一下，看不见启动情况。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/48637219/219281281-07d8cbc2-f387-4eee-a5ea-8880d8c23dea.png)
> 
> 后面没有了吗？

是的

**Comment by lss233** [comment]
服务器配置是怎样的？

**Comment by CCl333** [comment]
> 服务器配置是怎样的？

[mirai]
# Mirai 相关设置

qq = 32XXXXX

# 以下设置如果不懂 无需理会

api_key = "1234567890" # mirai-http-api 中的 verifyKey
http_url = "http://mirai:8080" # mirai-http-api 中的 http 回调地址
ws_url = "http://mirai:8080"# mirai-http-api 中的 ws 回调地址

[openai]
# OpenAI 相关设置

# 模式选择，详情见下方 README
mode = "browserless"

# 你的 OpenAI 邮箱
email = "32XXXXX@qq.com" 
# 你的 OpenAI 密码
password = "XXXXX"

# 对于通过 Google 登录或者微软登录的同学，可以使用 session_token 登录
# 此时 email 和 password 可以直接删除
# session_token = "一串 ey 开头的东西"

# 如果你在国内，需要配置代理
#proxy="http://8.219.136.178"

# 使用 ChatGPT Plus（plus 用户此项设置为 true）
paid = false

[text_to_image]
# 文字转图片
font_size = 30 # 字体大小
width = 700  # 图片宽度
font_path = "fonts/sarasa-mono-sc-regular.ttf"  # 字体
offset_x = 50  # 起始点 X
offset_y = 50 # 起始点 Y

[trigger]
# 配置机器人要如何响应，下面所有项均可选 (也就是可以直接删掉那一行)

# 符合前缀才会响应，可以自己增减
prefix = [ "",]

# 配置群里如何让机器人响应，"at" 表示需要群里 @ 机器人，"mention" 表示 @ 或
require_mention = "at"

# 重置会话的命令
reset_command = [ "重置会话",]

# 回滚会话的命令
rollback_command = [ "回滚会话",]

[response]
# 匹配指令成功但没有对话内容时发送的消息
placeholder = "您好！我是 Assistant，一个由 OpenAI 训练的大型语言模型。我不是真正的人，而是一个计算机程序，可以通过文本聊天来帮助您解决问题。如果您有任何问题，请随时告诉我，我将尽力回答。\n如果您需要重置我们的会话，请回复`重置会话`。"

# 发生错误时要发送的消息
error_format = "出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。\n{exc}"

# 是否要回复触发指令的消息
quote = true

# 发送下面那个提醒之前的等待时间
timeout = 30.0

# 超过响应时间时要发送的提醒
timeout_format = "我还在思考中，请再等一下~"

# 重置会话时发送的消息
reset = "会话已重置。"

# 回滚成功时发送的消息
rollback_success = "已回滚至上一条对话，你刚刚发的我就忘记啦！"

# 回滚失败时发送的消息
rollback_fail = "回滚失败，没有更早的记录了！"

# 服务器提示 429 错误时的回复
request_too_fast = "当前正在处理的请求太多了，请稍等一会再发吧！"

# 等待处理的消息的最大数量，如果要关闭此功能，设置为 0
max_queue_size = 10

# 队列满时的提示
queue_full = "抱歉！我现在要回复的人有点多，暂时没有办法接收新的消息了，请过会儿再给我发吧！"

# 新消息加入队列会发送通知的长度最小值
queued_notice_size = 3

# 新消息进入队列时，发送的通知。 queue_size 是当前排队的消息数
queued_notice = "消息已收到！当前我还有{queue_size}条消息要回复，请您稍等。"

[system]
# 是否自动同意进群邀请
accept_group_invite = true

# 是否自动同意好友请求
accept_friend_request = false

[presets]
# 切换预设的命令： 加载预设 猫娘
command = "加载预设 (\\w+)"

loaded_successful = "预设加载成功！"

[presets.keywords]
# 预设关键词 <-> 实际文件
"正常" = "presets/default.txt"
"猫娘" = "presets/catgirl.txt"

**Comment by lss233** [comment]
硬件配置

**Comment by CCl333** [comment]
> 硬件配置
![image](https://user-images.githubusercontent.com/48637219/219294926-9a8021cb-20cb-4d2a-8d89-b5b7666074c2.png)
两核1G轻量服务器

**Comment by lss233** [comment]
感觉没什么问题，检查一下 docker 版本。pull一下最新镜像吧

**Comment by Everytimeyumi** [comment]
![image](https://user-images.githubusercontent.com/30947975/219605436-a7a19991-99fe-4e3b-8330-41f2ca2fe402.png)

![image](https://user-images.githubusercontent.com/30947975/219605093-89cb3508-2a1f-40fc-b014-14250bcb12c8.png)
![image](https://user-images.githubusercontent.com/30947975/219605904-8e76c949-c93c-4ed9-b4da-c015145e9e96.png)

linux快速部署   机器人没有消息回复   显示账号登录成功了

**Comment by lss233** [comment]
> linux快速部署 机器人没有消息回复 显示账号登录成功了

没有看见账号登录成功，看一下 mirai 那边的日志
```
docker-compose logs -f mirai
```

**Comment by Yumemi8** [comment]
我也是这个问题 aliyun Ubuntu22 QQ登陆成功  但是不会回复任何内容 同时会有两个错误
![image](https://user-images.githubusercontent.com/71859504/222961878-75d10285-7954-45bd-ba7e-325a80531a14.png)
![image](https://user-images.githubusercontent.com/71859504/222961889-93ef5cf9-ddf8-42bf-8ee0-06aaed7e4632.png)

**Comment by lss233** [comment]
容器的启动方法错了。你需要 docker-compose up -d

**Comment by Yumemi8** [comment]
![image](https://user-images.githubusercontent.com/71859504/224671341-c2b5087e-a455-42a0-be5c-ec7948703c77.png)
chatgpt似乎依然有问题  无回复
