### ISSUE TITLE
会封号！！才用了4个小时

### ISSUE THREAD

**Issue by thechen130** [lss233/chatgpt-mirai-qq-bot#150]
![IMG_20230216_175344](https://user-images.githubusercontent.com/74664452/219331281-92332817-5f15-4449-a5ea-41f5f9f5e599.jpg)

**Comment by lss233** [comment]
和你的用法有关。

**Comment by thechen130** [comment]
> 和你的用法有关。

请问该注意什么，有什么用法。
目前你们使用了有多久没被封啊

**Comment by joe12801** [comment]
被人举报了

**Comment by bigtengfei** [comment]
登录方式改为安卓手表可以挂很久，我挂了几天都没问题，用其它方式一下子就封
