### ISSUE TITLE
[Feature] ChatGPT Plus现在有Default和Legacy两种模式，请添加一个设置项用于切换这两种模式。

### ISSUE THREAD

**Issue by 333mhz** [lss233/chatgpt-mirai-qq-bot#152]
关于这两种模式的区别可以参考：https://www.reddit.com/r/ChatGPT/comments/111skny/the_differences_between_default_and_legacy_models/
希望添加一个可以选择切换Default和Legacy两种模式的功能及其设置项。
- [x] 浏览器版
- [ ] API 版

**Comment by lss233** [comment]
这个应该要在 revChatGPT 那边做

**Comment by lss233** [comment]
plus = false 时即为 default 模式
plus = true 时即为 legacy 模式
