### ISSUE TITLE
[BUG] qq无法回馈chatgpt信息

### ISSUE THREAD

**Issue by RWFYS** [lss233/chatgpt-mirai-qq-bot#155]
实际上我用浏览器登录chatgpt查看是回复了信息，但是qq这边就提示故障
![image](https://user-images.githubusercontent.com/125631079/219660764-e8b535a7-ff1e-49f3-8387-4fe84062d4ca.png)
后台报错这个：
requests.exceptions.ProxyError: HTTPSConnectionPool(host='chatgpt.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

**Comment by RWFYS** [comment]
看见已关闭的问题讨论，是不是需要1.5.4版本

**Comment by lss233** [comment]
`Cannot connect to proxy` 就是没有连接上代理，   
检查一下你的 `proxy=` 这段配置吧。

**Comment by RWFYS** [comment]
![image](https://user-images.githubusercontent.com/125631079/219664662-65be9559-c5a4-40b0-8e40-5f9452471ef2.png)
一开始都连的上，其实就是只有说你好，才会正常回复，往下就没啦

**Comment by lss233** [comment]
如果你没有好的代理的话，建议部署在国外服务器

**Comment by lss233** [comment]
v1.5.7 改进了此类情况的错误提示。
