### ISSUE TITLE
[BUG]'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Apricityx** [lss233/chatgpt-mirai-qq-bot#158]
**提交 issue 前，请先确认：**
- [✓] 我已看过 **FAQ**，此问题不在列表中
- [✓] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
qq回复
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
'NoneType' object is not subscriptable

**运行环境:**  
- 操作系统ubuntu
- Docker： 
- 项目版本：1.5.6

**复现步骤**  
描述你是如何触发这个 BUG 的
就挺神奇的，有时行有时不行
聊着聊着就报错了

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
这个是因为你触发了 OpenAI 的 `Too many requests in 1 hour, Try later.`    

但是上游依赖把报错处理写的特别奇特，导致我不能捕获它。  所以就变成了这种报错，我也很无奈。  

一种可能的方法是：使用多账户机制，减小被聊爆的概率。

**Comment by Apricityx** [comment]
好的，感谢回复，不知道可以去哪里搞到新的账号，现在官网好像取消注册了



---Original---
From: "Dark ***@***.***&gt;
Date: Sat, Feb 18, 2023 01:21 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [lss233/chatgpt-mirai-qq-bot] [BUG]'NoneType' object is notsubscriptable (Issue #158)




 
这个是因为你触发了 OpenAI 的 Too many requests in 1 hour, Try later.
 
但是上游依赖把报错处理写的特别奇特，导致我不能捕获它。  所以就变成了这种报错，我也很无奈。
 
一种可能的方法是：使用多账户机制，减小被聊爆的概率。

**Comment by lss233** [comment]
> 好的，感谢回复，不知道可以去哪里搞到新的账号，现在官网好像取消注册了


我刚刚还注册了一个……

**Comment by Apricityx** [comment]
> > 好的，感谢回复，不知道可以去哪里搞到新的账号，现在官网好像取消注册了
> 
> 
> 我刚刚还注册了一个……

我这边显示sign up unavailable 
是需要特定地区的ip吗

**Comment by lss233** [comment]
> 我这边显示sign up unavailable 是需要特定地区的ip吗

那就不得而知了……

**Comment by Apricityx** [comment]
> > 我这边显示sign up unavailable 是需要特定地区的ip吗
> 
> 那就不得而知了……

好，谢谢

**Comment by lss233** [comment]
先开着这个 issue 吧，说不定有别人用得到。

**Comment by lss233** [comment]
v1.5.7 改进了此类情况的错误提示。
