### ISSUE TITLE
graia ClientConnectorError

### ISSUE THREAD

**Issue by lxy5513** [lss233/chatgpt-mirai-qq-bot#159]
**提交 issue 前，请先确认：**
- [] 我已看过 **FAQ**，此问题不在列表中
- [] 我已看过其他 issue，他们不能解决我的问题 
- [] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
![image](https://user-images.githubusercontent.com/39720528/219825235-f454038c-7932-4f6e-9dcf-fca94d540d03.png)

**运行环境:**  
- 操作系统：macos 
- 项目版本：web

**复现步骤**  
描述你是如何触发这个 BUG 的
python bot.py

**预期行为**  
没有报错：ConnectionRefusedError(61, "Connect call failed ('127.0.0.1', 8080)")

**其他内容**  
config.cfg
![image](https://user-images.githubusercontent.com/39720528/219825435-33a1dea8-dc0e-4bc2-95f3-894d4bc78967.png)

![image](https://user-images.githubusercontent.com/39720528/219825455-4b38ab20-62e5-4261-b064-d2378905ce2e.png)

**Comment by lxy5513** [comment]
@lss233 大佬麻烦帮忙看下 🙏

**Comment by lss233** [comment]
你先看 #142
