### ISSUE TITLE
[BUG] ChatGPT.cmd 闪退

### ISSUE THREAD

**Issue by XKaguya** [lss233/chatgpt-mirai-qq-bot#160]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
使用 启动ChatGPT.cmd 后，会正常无提示符加载几秒，随后变为当前目录。无任何报错。
手动启动bot.py依旧如此。
![image](https://user-images.githubusercontent.com/96401952/219840030-1273df30-39b3-4db5-a54d-f4c6c26a9855.png)
![image](https://user-images.githubusercontent.com/96401952/219839993-9eaab94d-30d6-4690-aac8-54bff47c25ee.png)

**运行环境:**  
- 操作系统：Windows 10
- Docker： ？
- 项目版本：v1.5.6 - 网页版 - access_token 登录、稳定性提升

**复现步骤**  
python bot.py
启动ChatGPT.cmd

**预期行为**  
![image](https://user-images.githubusercontent.com/96401952/219840218-508fef5d-7bdb-4e97-8527-88c7fdc7d893.png)
正常情况下，这个是API版本，但是API版本提示我
That model does not exist
根据Issue我去尝试网页版，就这样了。

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by XKaguya** [comment]
> 我觉得可能是有些依赖没装好导致的。 你要不然从仓库里面下载最新的 `manager.py` 替换你本地那个看看？

依赖安装我看过几眼，基本上没有问题，只出现过有些已经安装的。感谢回复，我从仓库中下载了最新的manager.py并替换，现在已经可以正常开启了

**Comment by lss233** [comment]
> 依赖安装我看过几眼，基本上没有问题，只出现过有些已经安装的。感谢回复，我从仓库中下载了最新的manager.py并替换，现在已经可以正常开启了

神奇！
