### ISSUE TITLE
[BUG] 微软账号登录后不管是plus还是非plus登录后输入返回值都是OpenAI 在返回结果时出现了错误

### ISSUE THREAD

**Issue by 877kc6** [lss233/chatgpt-mirai-qq-bot#161]
我已看过 **FAQ**，此问题不在列表中
微软账号登录后不管是plus还是非plus登录后输入返回值都是OpenAI 在返回结果时出现了错误
windows10
1.5.6
chatgpt plus
![image](https://user-images.githubusercontent.com/55058992/219854480-1b3f8489-bad6-4fc3-a89c-c2bd15b1735a.png)

**Comment by lss233** [comment]
有可能和它有关：
https://github.com/acheong08/ChatGPT/issues/795

**Comment by 877kc6** [comment]
> 有可能和它有关： [acheong08/ChatGPT#795](https://github.com/acheong08/ChatGPT/issues/795)

并没有相关的解决方案

**Comment by lss233** [comment]
> A few ways this could happen:
> 
> 1. You're in China: OpenAI is geo restricted
> 2. You're using a known Chinese VPN or proxy: Also subject to geo restrictions
> 3. You're using a Google/Microsoft account: Those aren't supported
> 4. Other
> 
> Solution: Go to https://chat.openai.com/api/auth/session and use `access_token` in config (remove email/password)

**Comment by LamKappa** [comment]
https://github.com/acheong08/ChatGPT/issues/166 疑似跟这个是一个问题 从给出的图片信息中: "Field missing" 这部分是 revChatGPT.V1 中打印的错误信息。

**Comment by lss233** [comment]
新的版本中已经对错误信息提示做了优化.
