### ISSUE TITLE
[BUG] docker compose部署mirai可以用，但是chatgpt出现如下报错请问如何解决

### ISSUE THREAD

**Issue by miku8miku** [lss233/chatgpt-mirai-qq-bot#163]
![image](https://user-images.githubusercontent.com/52441374/219909536-255ab3f1-a09a-4a97-93eb-8bb656b49a38.png)
![image](https://user-images.githubusercontent.com/52441374/219909550-43921e49-4af7-4e70-848d-85f23043b3b7.png)

**Comment by lss233** [comment]
Windows 可能跑不了 xpra，建议使用 Windows 快速部署包部署。
