### ISSUE TITLE
[BUG] openai登陆成功了，但是发消息测试提示这个

### ISSUE THREAD

**Issue by wxyww2049** [lss233/chatgpt-mirai-qq-bot#166]
![image](https://user-images.githubusercontent.com/45908507/219937946-682705f7-394d-41ff-bcae-a4830004e201.png)

**Comment by lss233** [comment]
如果你在国内，那么需要使用本地代理，否则无法正常使用。

**Comment by wxyww2049** [comment]
但是我运行chatgpt的时候显示如下内容，openai登陆成功是不是表明我的代理是有效的，还是说我哪里的配置有问题，我使用了v2rayn进行代理，端口配置在1080。
![image](https://user-images.githubusercontent.com/45908507/219958314-8b189e4c-e668-4fa7-b7f2-69e525d67cf9.png)

**Comment by wxyww2049** [comment]
> 如果你在国内，那么需要使用本地代理，否则无法正常使用。

但是我运行chatgpt的时候显示如下内容，openai登陆成功是不是表明我的代理是有效的，还是说我哪里的配置有问题，我使用了v2rayn进行代理，端口配置在1080。
![image](https://user-images.githubusercontent.com/45908507/219958314-8b189e4c-e668-4fa7-b7f2-69e525d67cf9.png)

**Comment by xiaotong6666** [comment]
楼主解决了嘛，同问
我也是这样的问题，使用了全局代理
浏览器能正常和chatgpt聊天，qq不行，在chatgpt也没看见新的会话

**Comment by lss233** [comment]
> 楼主解决了嘛，同问 我也是这样的问题，使用了全局代理 浏览器能正常和chatgpt聊天，qq不行，在chatgpt也没看见新的会话

那 mirai 那边有看见新的消息吗？给 机器人发消息的时候是好友吗？

**Comment by LamKappa** [comment]
同样遇到此问题，显示 "OpenAI服务器登录成功" 但发送消息会返回 "OpenAI 在返回结果时出现了错误" 。

谷歌账号故使用 browserless 模式，浏览器 cookie 中对应的 __Secure-next-auth.session-token 字段 ("ey.....") 随着刷新会变化，更改为变化前的 value 也能够保持登陆状态，但是刷新仍会导致此字段变化，不知道是不是这个缘由。

**Comment by wsdjj220** [comment]
我也是一样

**Comment by winds99** [comment]
![image](https://user-images.githubusercontent.com/125882575/220104391-e754042e-245d-499e-8e58-9f1eb24e26a3.png)mi


> > 楼主解决了嘛，同问 我也是这样的问题，使用了全局代理 浏览器能正常和chatgpt聊天，qq不行，在chatgpt也没看见新的会话
> 
> 那 mirai 那边有看见新的消息吗？给 机器人发消息的时候是好友吗？

![image](https://user-images.githubusercontent.com/125882575/220104616-3d74fa54-bdee-42c2-8c36-34149b2c54f2.png)
mirai是这样的

**Comment by winds99** [comment]
> 本人已解决，方法是将配置文件的 email 和 password 注释，因为发现这会导致 revChatGPT.V1 中 58 行不会调用 __refresh_headers（access_token） ，尝试注释后我的错误消失了。

谢谢大佬，解决了

**Comment by lss233** [comment]
是不是大家都觉得配置文件的优先级应该是 `access_token`  > `session_token` > `email + password`?

**Comment by LamKappa** [comment]
主要是以为使用 browserless 模式后 email 和 password 就不会被采用了，没想到 manager.py 中是全部传过去的。

**Comment by lss233** [comment]
因为 browserless 也是可以用 email + password 的……

**Comment by LamKappa** [comment]
哈哈，不过这里确实因为 access_token 字段有值导致 __login() 其实也没调用，导致返回说 "OpenAI服务器登录成功" ，其实根本就没成功。主要还是懒得注释就几种都填了内容 ......

**Comment by dearxu486** [comment]
这是一个程序的错误日志，出现在2023年2月20日23时28分19秒。根据日志的记录，这是一个在处理用户消息时出现的错误。

日志的第一部分显示了一些正在运行的组件的准备情况，包括一个名为"elizabeth.service"的组件已经准备好。第二部分表示所有组件都已准备就绪，现在进入阻塞阶段。接下来的一行显示了一个成功的会话密钥获取。

然而，在日志的后半部分，出现了一个错误，提示"Access token is missing"，意味着缺少访问令牌。这通常是由于身份验证失败或未正确配置令牌导致的。在本例中，日志的下一行显示了一个由OpenAI返回的错误消息，指示在返回结果时出现了错误。可能需要进一步调查和排除问题。
有问题可以问ai啊

**Comment by xiaotong6666** [comment]
真的，注释掉就好了，谢谢大佬
