### ISSUE TITLE
[Feature]预设选项允许添加某一路径

### ISSUE THREAD

**Issue by Febtw** [lss233/chatgpt-mirai-qq-bot#167]
希望预设选项可以设置成允许添加某一路径（即添加路径下所有文件（或某一扩展名的文件），默认用文件名（不含扩展名）充当关键词）
并且允许为关键词设置别名（即两个关键词都能触发同一预设）

**Comment by lss233** [comment]
这是一个很不错的想法，计划在下一版支持。
