### ISSUE TITLE
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。

### ISSUE THREAD

**Issue by xiaotong6666** [lss233/chatgpt-mirai-qq-bot#170]
回复这个
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
_Originally posted by @lss233 in https://github.com/lss233/chatgpt-mirai-qq-bot/issues/166#issuecomment-1436147758_

**Comment by maduit** [comment]
解决不了！
回复了重置会话没用！

**Comment by maduit** [comment]
![image](https://user-images.githubusercontent.com/77372388/220296519-6eac2e37-de69-45b0-a60b-d587eaa4b375.png)

**Comment by lss233** [comment]
> ![image](https://user-images.githubusercontent.com/77372388/220296519-6eac2e37-de69-45b0-a60b-d587eaa4b375.png)

status.openai.com

OpenAI 服务器正在经历大规模宕机

**Comment by Anzu0831** [comment]
![image](https://user-images.githubusercontent.com/122810457/220570976-545ee54f-61bd-4dc0-bd7b-1836edbc0f22.png)

**Comment by Anzu0831** [comment]
怎么回事呢

**Comment by lss233** [comment]
v1.5.7 版本已发布，接下来此类错误信息将会减少。遇到类似问题的同学可以先试试升级到 v1.5.7。
