### ISSUE TITLE
[Feature] 添加一个限制提问次数的功能

### ISSUE THREAD

**Issue by SteveJiyu** [lss233/chatgpt-mirai-qq-bot#171]
# 希望添加一个限制提问次数的功能
希望可以添加一个每个人（识别qq_id）每小时/天提问次数设置的功能。
因为放到群里1小时2个号就全被限制了。。。

**Comment by lss233** [comment]
下一版本支持

**Comment by SteveJiyu** [comment]
你好。已收到你的邮件，我会在稍后尽快处理。————————————这是来自Jiyu的自动回复邮件。
