### ISSUE TITLE
[Feature] 添加Markdown渲染成图片

### ISSUE THREAD

**Issue by Hakureirm** [lss233/chatgpt-mirai-qq-bot#172]
可以加个可选功能，把文字渲染图片的方式改为Markdown渲染成图片吗，这样更美观一点，可读性也高，代码、公式也好看了

**Comment by lss233** [comment]
一直想做这个功能，但是感觉纯 Python 渲染难度有点大……

**Comment by Hakureirm** [comment]
我在尝试引入一些现成库做一下，不过不知道能不能搞出来，不太会写。。

**Comment by lss233** [comment]
> 我在尝试引入一些现成库做一下，不过不知道能不能搞出来，不太会写。。

我认为可以用 pandoc 来实现这个功能，把 Markdown 转成图片。 Typora 就是这么做的。  

不过这个东西基本上是一个独立的程序了，所以估计得搞成 pandoc-server

**Comment by Hakureirm** [comment]
![image](https://user-images.githubusercontent.com/60978629/220697809-70e7ef8e-cdfc-4a2b-b6fc-4f4f2e5ef75a.png)
目前已经能正常渲染公式，代码的内容了
试用了很多方法，最后是使用了 python-markdown 和他的插件库 python-markdown-math，将 Markdown 转换为了 HTML，再使用 wkhtmlimage（安装wkhtmltopdf附带）和调用它的库 imgkit 将 HTML 渲染为图片。代码量不多，环境安装简单，体积都很小，CPU性能和内存占用也很小，电脑没电了，明天我再整理一下。

**Comment by lss233** [comment]
此功能已经加入了，接下来就是修 bug 的时候了……
