### ISSUE TITLE
[Feature] 添加权限管理

### ISSUE THREAD

**Issue by frankcwl** [lss233/chatgpt-mirai-qq-bot#173]
希望添加白名单（或黑名单）功能，只有在白名单上的群聊或者好友能够触发chatGPT会话

**Comment by Febtw** [comment]
> 希望添加白名单（或黑名单）功能，只有在白名单上的群聊或者好友能够触发chatGPT会话

感觉和issue#171重复了，提问数设为0就可以了。
不过我觉得如果有管理权限，可以用来管理mirai和本项目，比如查询版本信息，查询openai登录情况及重新登录等等

**Comment by lss233** [comment]
我认为 @Febtw 的说法有道理。  

通过额度限制，如果默认的额度为 0，则相当于开启白名单功能，  只有指定用户额度 > 0 的人可以发送消息。  

相反，如果设定默认额度 > 0, 当指定用户额度 == 0 时相当于被列入黑名单.

**Comment by ColdFoam** [comment]
> 

大佬重置和回滚能加权限管理吗，不想别人都能重置，把设定重置了，或者给指定群聊默认预设的功能，现在好像是全局默认预设？

**Comment by ColdFoam** [comment]
> 我认为 @Febtw 的说法有道理。
> 
> 通过额度限制，如果默认的额度为 0，则相当于开启白名单功能， 只有指定用户额度 > 0 的人可以发送消息。
> 
> 相反，如果设定默认额度 > 0, 当指定用户额度 == 0 时相当于被列入黑名单.

大佬重置和回滚能加权限管理吗，不想别人都能重置，把设定重置了，或者给指定群聊默认预设的功能，现在好像是全局默认预设？
