### ISSUE TITLE
[Feature] 建议加入图片转文字时自动解码数学转义符的功能

### ISSUE THREAD

**Issue by Pretend-to** [lss233/chatgpt-mirai-qq-bot#174]
受到QQ自身的局限性影响，在利用chatgpt求解数学问题的时候会遇到数学符号直接呈现为转义符的情况影响了使用体验，
![Screenshot_2023-02-21-07-43-38-78_9d26c6446fd7bb8e41d99b6262b17def](https://user-images.githubusercontent.com/98372256/220214164-70bfc3ba-d415-45c7-9f8f-a82ea2b14062.jpg)
所以希望能在文字转图片时把他正确地表示出来。

**Comment by lss233** [comment]
确实是这样。这是 LaTex，只能渲染成图片。  我认为可以通过 #172 实现。
