### ISSUE TITLE
[BUG] 增加部分配置后openai和bot不回复消息

### ISSUE THREAD

**Issue by creeper263** [lss233/chatgpt-mirai-qq-bot#175]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：debian 11
手动部署

**复现步骤**  
描述你是如何触发这个 BUG 的
1.在默认config.cfg末尾空格后添加配置
```
[trigger]
# 配置机器人要如何响应，下面所有项均可选 (也就是可以直接删掉那一行)

# 符合前缀才会响应，可以自己增减
prefix = [ "ai","msg",]
```
2.正常启动bot直至Successfully got session key.
3.私聊bot，后台可见他人聊天信息显示，但不回复（后台也没有显示），无报错，无任何其他信息。
4.删除增加的配置（ctrl + Z）后恢复正常功能

**Comment by lss233** [comment]
所以你是怎么私聊的

**Comment by creeper263** [comment]
我是机器人的好友，直接给他发消息，没添加trigger的时候会正常回复。

**Comment by creeper263** [comment]
在群里输入：ai xxx
不回复

**Comment by lss233** [comment]
群里还得看个 require_mention
所以你应该 @机器人 ai xxx

**Comment by creeper263** [comment]
![image](https://user-images.githubusercontent.com/55615278/220303949-450c9c73-8d32-4c80-817b-559f92d52db9.png)
我想达成的功能是在群里直接发送ai xxx，然后交互，不使用@，我应该怎么做呢，上图中没有说明清楚（或者我没有理解）。

**Comment by lss233** [comment]
不好意思,这里应该是文档缺失了 
原意为:```配置群里如何让机器人响应，"at" 表示需要群里 @ 机器人，"mention" 表示 @ 或者以机器人名字开头都可以，"none" 表示不需要```  

现已修复.

**Comment by creeper263** [comment]
好的，解决问题了，谢谢。
