### ISSUE TITLE
[BUG] 提示“程序未正常退出”，py报“'type' object is not subscriptable”错误

### ISSUE THREAD

**Issue by KleePaimon** [lss233/chatgpt-mirai-qq-bot#176]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
配置好config.cfg后使用python3 bot.py执行，提示“未正常退出错误”，py报出“'type' object is not subscriptable”错误

**运行环境:**  
- 操作系统：Ubuntu 20.04.1 LTS x86_64(Py3.7.9)　
- Docker： 非Docker
- 项目版本：1.5.6

**预期行为**  
正常情况下应该继续启动，但我没有看到

**截图**  
[这是截图](https://s1.ax1x.com/2023/02/21/pSjdzRS.png)

**Comment by lss233** [comment]
不支持 Python 3.8，请使用 Python 3.9 或以上版本
