### ISSUE TITLE
[Feature] 可否接入openai DALL·E

### ISSUE THREAD

**Issue by shoulder0902** [lss233/chatgpt-mirai-qq-bot#181]
dalle是openai旗下一个根据自然语言生成图片的引擎。
它的介绍页面：https://openai.com/dall-e-2/
它的交互入口：https://labs.openai.com/
在labs页面中点击右上角头像有访问api的入口，因此我想不用逆向交互页面，可以直接使用api接入dalle（需要付费，每月有免费额度，第一次进入labs会提示）。
如果贵组开发者能实现这个功能将使bot有趣并且实用得多，在此先行感谢！！！

**Comment by creeper263** [comment]
目前labs.openai.com的服务情况已可从https://status.openai.com/查看。

**Comment by lss233** [comment]
好的，安排上。

**Comment by Febtw** [comment]
这比novelai香多了呀
![image](https://user-images.githubusercontent.com/96163355/220542231-62af8365-cfcc-464f-9987-ebd52441d598.png)
不知道15点券一个月能用多久

**Comment by creeper263** [comment]
查找一番，dalle的网页版与API版似乎有区别：
网页版首次使用获得35credits，每月15credits，而API版

> the default rate limit is 50 images per minute

[API doc](https://platform.openai.com/docs/guides/images)
[网页版](https://labs.openai.com/)

**Comment by creeper263** [comment]
在[help](https://help.openai.com/en/articles/6705023-dall-e-api-faq)页面找到的dalle API FAQ：
> All you need to know about how to use the DALL·E API
> Raf avatar
> Written by Raf
> Updated over a week ago
> 1. What is the DALL·E API and how can I access it?
> 
> The DALL·E API allows you to integrate state of the art image generation capabilities directly into your product. To get started, visit our [developer guide](https://beta.openai.com/docs/guides/images).
> 
> 2. How do I pay for the DALL·E API?
> 
> The API usage is offered on a pay-as-you-go basis and is billed separately from labs.openai.com. You can find pricing information on our [pricing page](https://openai.com/api/pricing).
> 
> For large volume discounts (>$5k/month), please [contact sales](https://openai.com/contact-sales/).
> 
> 3. Can I use my OpenAI API trial credits ($18) or labs.openai.com credits on the DALL·E API?
> 
> You can use the OpenAI API free trial credits ($18) to make DALL·E API requests.
> 
> DALL·E API is billed separately from labs.openai.com. Credits granted/purchased on
> 
> labs.openai.com do not apply to DALL·E API.
> 
> For the latest information on pricing, please see our [pricing page](https://openai.com/api/pricing).
> 
> 4. Are there any API usage limits that I should be aware of?
> 
> The DALL·E API shares the usage limits with other OpenAI API services, which you can find in your [billing settings](https://beta.openai.com/account/billing/limits). Paid accounts have a default monthly quota set to $120, which can be increased by filling out the Quota Increase Request Form.
> 
> Additionally, org-level rate limits enforce a cap on the number of images you can generate per minute. To learn more, we encourage you to read our help article, "What's[ the rate limit for the DALL·E API?](https://help.openai.com/en/articles/6696591)", which provides additional detail.
> 
> 5. Are there any restrictions on the type of content I can generate?
> 
> Yes - please read our [content policy](https://labs.openai.com/policies/content-policy) to learn what's not allowed on the DALL·E API.
> 
> 6. Can I sell the images I generate with the API? Can I use it in my application?
> 
> Subject to the [Content Policy](https://labs.openai.com/policies/content-policy) and [Terms](https://openai.com/api/policies/terms/), you own the images you create with DALL·E, including the right to reprint, sell, and merchandise - regardless of whether an image was generated through a free or paid credit.
> 
> 7. What do I need to do before I start serving API outputs to my users?
> 
> Before you launch your product, please make sure you're in compliance with our [use case policy](https://beta.openai.com/docs/usage-policies/use-case-policy) and include [end-user IDs](https://beta.openai.com/docs/usage-policies/end-user-ids) with requests.
> 
> 8. How are images returned by the endpoint?
> 
> The API can output images as URLs (response_format =url) or b64_json. Our [developer guide](https://beta.openai.com/docs/guides/images) includes more details.
> 
> 9, Which version of DALL·E is available via the API?
> 
> The API uses the latest version of DALL·E 2.
> 
> 10. Are the Edit function and Variations features available in the API?
> 
> Yes - for more detailed instructions, please see our [developer guide](https://beta.openai.com/docs/guides/images).
> 
> 11. Does it support outpainting?
> 
> Yes! There are many ways to use the /edits endpoint, including inpainting and outpainting. You can try it out firsthand in the [DALL·E Editor](https://labs.openai.com/editor).
> 
> 12. How can I save output images as files?
> 
> The API can output images as URLs. You'll need to convert these to the format you need. Our [developer guide](https://beta.openai.com/docs/guides/images) includes more details.
> 
> 13. How long do the generated URLs persist?
> 
> The URLs from the API will remain valid for one hour.
> 
> 14. I'm stuck. How do I get help?
> 
> For general help, you can consult our [developer guide](https://beta.openai.com/docs/guides/images) and [help center](https://help.openai.com/en/), or ask questions on our [Community forum](https://community.openai.com/).
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>

**Comment by creeper263** [comment]
api版本使用的同样是dalle 2，而与openai其他API共享18美元的 free trial credits。

**Comment by VarPower1989** [comment]
> 总结来说： API版本使用的同样是dalle 2，与openai其他API共享一次性的18美元的 free trial credits。 在图片分辨率的基础上pay as you go按图像数量付费，如下图： ![image](https://user-images.githubusercontent.com/55615278/220547829-56988676-53c0-4a10-8482-c35027eac67a.png)
> 
> 而网页版与API版费用独立，一次性获得35credits，每月15credits。 一次生成获得四张图片，消耗1credit（只是测试，可能某些情况下会消耗更多）。

这么看DALL-E2还是很贵的嘛

**Comment by creeper263** [comment]
> > 总结来说： API版本使用的同样是dalle 2，与openai其他API共享一次性的18美元的 free trial credits。 在图片分辨率的基础上pay as you go按图像数量付费，如下图： ![image](https://user-images.githubusercontent.com/55615278/220547829-56988676-53c0-4a10-8482-c35027eac67a.png)
> > 而网页版与API版费用独立，一次性获得35credits，每月15credits。 一次生成获得四张图片，消耗1credit（只是测试，可能某些情况下会消耗更多）。
> 
> 这么看DALL-E2还是很贵的嘛

api版免费额度18美元，一张图一毛钱，还行。感觉比ChatGPT plus便宜。

**Comment by lss233** [comment]
v2.2.0 已发布  现已支持 AI 画图功能

**Comment by VarPower1989** [comment]
威武
