### ISSUE TITLE
[Feature] 希望增加requests token长度设置的参数

### ISSUE THREAD

**Issue by qd915149091** [lss233/chatgpt-mirai-qq-bot#182]
api版本调用text-ada-001模型时返回了token超出长度限制的报错,只有text-davinci-003支持4000token,其他三个模型都是2000

小白找了一圈源码也没看到请求在那个函数发的,希望指点一下临时解决
![image](https://user-images.githubusercontent.com/41196703/220547282-98e6b393-05ad-4e65-a741-ac6635410933.png)

**Comment by LamKappa** [comment]
这个问题是出在 `revChatGPT` 库里的，`revChatGPT.Official` 里可以看到硬编码的 4000 和 3200 等，要在这个项目里改起来不太容易，所以推荐自己去库源码里改，弄个全局变量替换一下改成 2000 就能用另外的几个模型啦。

**Comment by LamKappa** [comment]
具体是在 `.\chatgpt\python3.9\Lib\site-packages\revChatGPT\Official.py` 中，有两处 4000 和一处 3200 的硬编码，可以适当使用全局变量 `MAX_REQUEST` ，替换成 `MAX_REQUEST` 和 `MAX_REQUEST-800`。

**Comment by lss233** [comment]
已经支持了。
