### ISSUE TITLE
[BUG] 运行一段时候后出现 revChatGPT.V1.Error

### ISSUE THREAD

**Issue by Anzu0831** [lss233/chatgpt-mirai-qq-bot#185]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
运行一段时间后，日志里出现 revChatGPT.V1.Error，同时bot会回复“ 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。”
**运行环境:**  
- 操作系统：WINDOWS
- Docker： ？
- 项目版本：1.5.7网页版， 为手动部署。
- 

**复现步骤**  
描述你是如何触发这个 BUG 的
1.启动chatgpt.cmd和mirai.cmd后 将bot放置在群里进行聊天。
2.多个群友对bot进行提问 ，bot回复缓慢 ，同时回复 "消息已收到！当前我还有X条消息要回复，请您稍等。"
3.bot回答完某个问题后，bot对剩下的提问的回复都是“出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。”
**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
![UQW1~28{_(J@DQ}K8_X(E%4](https://user-images.githubusercontent.com/122810457/220829317-f15615e7-70c2-45d1-8265-5c314a7e6813.png)
![UB0}JMT26~8R}PR0GDL@BOT](https://user-images.githubusercontent.com/122810457/220829337-dbcc2169-55ab-4865-b406-41ff3cec11eb.png)

**其他内容**  
很奇怪，有时候回复 重置会话 就能接着用。有时候就一直回复“ 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。”。重新启动过 chatgpt.cmd 。bot甚至不鸟我了

**Comment by lss233** [comment]
429 错误 一般是因为限流了吧

**Comment by twturbo** [comment]
我同样遇到了这个问题，应该是问太多或者重复问题太多次。去chatgpt网页登录后和它聊就会报错 Too many requests in 1 hour. Try again later.
![DVKNM4OSKDX$O5%}R~E919H](https://user-images.githubusercontent.com/102146524/221111977-6bf45dae-2f8c-4be6-a739-5755f4e8855f.png)

**Comment by MikeQu223** [comment]
+1

**Comment by magisk317** [comment]
+1，同样的问题，有什么解决办法吗？

另外，怎么看API用量呢？设置里看一直是空的，没数据：
![image](https://user-images.githubusercontent.com/93979778/221367213-01984ff2-3396-4109-bb60-31f59e009d5a.png)

**Comment by h621233** [comment]
+1，但是我的不是因为账号问太多次了 绑了8个号仍然出现这个问题

**Comment by lss233** [comment]
1.5.8-beta 已对错误提示进行改进，升级后可以看到更准确的错误原因。
