### ISSUE TITLE
docker-compose启动报错

### ISSUE THREAD

**Issue by thunder410426** [lss233/chatgpt-mirai-qq-bot#19]
![image](https://user-images.githubusercontent.com/52324730/206860035-187bfa95-e16f-4d2d-8d25-29f37fe9cc86.png)
看起来是chatgpt bot启动失败

**Comment by thunder410426** [comment]
这个是setting.xml
![image](https://user-images.githubusercontent.com/52324730/206860072-fab5f3d6-9e54-4a6e-8c12-543dd4f62c89.png)

**Comment by thunder410426** [comment]
这个是config.json
![image](https://user-images.githubusercontent.com/52324730/206860136-20fd11cf-3568-4976-9a76-5e1576b3b1cb.png)

**Comment by lss233** [comment]
`config.json` 里面的注释要删掉！！ #15
