### ISSUE TITLE
[Feature] 发送特定命令后将回复的消息用图片发送

### ISSUE THREAD

**Issue by laoutiao** [lss233/chatgpt-mirai-qq-bot#191]
前提：我没有将回复都转为照片

我今天在跟ChatGPT玩五子棋，用markdown，但显示出来的格式比较奇怪，感觉用图片形式会比较清楚，但是我又不想在文字回复的时候用图片的形式回复我

![image](https://user-images.githubusercontent.com/54140010/221106775-0b6ce3e0-7c01-4a9d-9100-752406895890.png)

我有个想法，不知道实现起来会不会很困难
就跟那个预设一样
两个command，一个“图片模式”，一个“文字模式” 命令

**Comment by lss233** [comment]
好的，已加入计划

**Comment by laoutiao** [comment]
> 好的，已加入计划

辛苦！！：）

**Comment by lss233** [comment]
v2.0 已支持
