### ISSUE TITLE
[Feature] 建议添加关键词文本审核和智能云文本审核功能

### ISSUE THREAD

**Issue by ColdFoam** [lss233/chatgpt-mirai-qq-bot#194]
作为一个智能语言模型，ChatGPT虽然已经受到OpenAI的限制，但还是有方法绕过并回复不适宜内容，导致账号和群聊出现被封禁的情况，甚至可能影响自身。

建议对机器人从ChatGPT获取的内容做判断后再根据情况发送至群聊，限制方法像关键词检查，接入百度、腾讯智能云审核等。

我不太会编程，问ChatGPT后写了个最简单的对接百度智能云文本审核，效果还不错，所以来提个建议。大多数人应该不需要用到智能审核，所以可以给个开关选项吧，关键词审核我觉得是有必要的。

![1](https://user-images.githubusercontent.com/30315539/221267422-5215219a-a19b-4fec-9ab9-b73bf2bfe4bd.png)

bot.py
![2](https://user-images.githubusercontent.com/30315539/221267434-7571e286-6b33-4ae6-a7d1-59ab6edfd274.png)

**Comment by lss233** [comment]
我觉得不错，请问你可以发一个 PR 吗

**Comment by lss233** [comment]
智能云文本审核在 v2.1.0 已经由 @Haibersut 加入
