### ISSUE TITLE
[Feature] 关于加载预设

### ISSUE THREAD

**Issue by fangyuan99** [lss233/chatgpt-mirai-qq-bot#196]
不知道作者有没有看过这个项目，里面内置了很多非常好用的预设，不知道能不能整合一下：
[f/awesome-chatgpt-prompts: This repo includes ChatGPT prompt curation to use ChatGPT better.](https://github.com/f/awesome-chatgpt-prompts)

**Comment by lss233** [comment]
这两个项目是可以很好地兼容的。  不过我还是比较鼓励大家自己写预设。  如果你有觉得不错的预设，可以添加到 https://github.com/lss233/awesome-chatgpt-qq-presets 这个项目里。
