### ISSUE TITLE
项目的开源许可证使用不正确

### ISSUE THREAD

**Issue by BlueGlassBlock** [lss233/chatgpt-mirai-qq-bot#20]
嗨，我是 `Ariadne` 的主要开发者。

`Ariadne` 使用的是 `GNU AGPL-3.0` 开源许可证，该许可证要求依赖它的项目使用 `AGPL-3.0` （及以后版本）的许可证。

麻烦更改项目的许可证至 `AGPL-3.0`，谢谢。

**Comment by lss233** [comment]
感谢提醒
