### ISSUE TITLE
[BUG] 机器人不能正确显示mathml公式，他是一个正常现象吗，我的版本是1.5.7

### ISSUE THREAD

**Issue by sjakdsjific** [lss233/chatgpt-mirai-qq-bot#201]
![IIM~(Q @1)%RG{S@@2(8I%9](https://user-images.githubusercontent.com/109020499/221358042-09c69a78-f5c2-41ff-af0d-ebb2dcd722ac.png)

**Comment by sjakdsjific** [comment]
没事了，我没看到beta版更新日志

**Comment by lss233** [comment]
1.5.8-alpha 正在尝试支持公式中，有问题可以反馈哈~
