### ISSUE TITLE
[BUG] linux用户，docker-compose安装，没有preset目录

### ISSUE THREAD

**Issue by r5rinimaa** [lss233/chatgpt-mirai-qq-bot#203]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：？
- Docker： ？
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
docker-compose安装确实是没有这些文件啊。。你需要自己准备。

**Comment by r5rinimaa** [comment]
您好 我准备好了 该放到哪里吖

**Comment by r5rinimaa** [comment]
放到哪个目录下

**Comment by lss233** [comment]
我写的 docker-compose.yaml 样例里是放到和 docker-compose.yaml 同级的目录下，具体想放哪里取决于你，只要在 docker-compose.yaml 里修改它的位置就行。

**Comment by r5rinimaa** [comment]
你好 我确实放到同级目录下了 然后怕配置了"胡锡进“=“huxijin.txt” 还是报预设文件不存在欸

**Comment by r5rinimaa** [comment]
config:scan_presets:182 - 检查预设：胡锡进 <==> huxijin.txt [失败：文件不存在]
chatgpt_1     | 2023-02-25 18:25:21.249 | ERROR    | config:scan_presets:182 - 检查预设：ikun <==> ./ikun.txt [失败：文件不存在]
chatgpt_1     | 2023-02-25 18:25:21.250 | SUCCESS  | config:scan_presets:193 - 注册预设：catgirl <==> ./presets/catgirl.txt [成功]
chatgpt_1     | 2023-02-25 18:25:21.250 | SUCCESS  | config:scan_presets:193 - 注册预设：预设模板 <==> ./presets/预设模板.txt [成功]

**Comment by r5rinimaa** [comment]
报错信息如上所示 但是其实我根本没有presets这个文件夹

**Comment by guoluyuan** [comment]
> 报错信息如上所示 但是其实我根本没有presets这个文件夹

你可以尝试把presets文件夹放在docker-compose.yaml文件同目录下使用以下命令
docker cp 你的presets文件夹路径 你的容器ID:/app/presets
即可
容器id使用
docker ps 查看
00550bec4617   lss233/chatgpt-mirai-qq-bot:browser-version   "/bin/bash /app/dock…"  选这一行，00550bec4617 就是容器ID

**Comment by xxsoul** [comment]
> 报错信息如上所示 但是其实我根本没有presets这个文件夹

presets这个目录是在构建Docker镜像时打到镜像里的而且在docker-compose.yml中没有映射出来，所以有两个方式：
1. clone项目，把老胡（笑）的文件放到项目根目录的“presets”文件夹中，然后重新使用命令构建镜像
2. 如guoluyuan（https://github.com/lss233/chatgpt-mirai-qq-bot/issues/203#issuecomment-1445296363）所述，把老胡的文件复制到容器里或进到容器里修改文件
可以简单尝试下2：
```bash
cd path/to/laohu.txt # 假如想把laohu.txt拷贝到容器里，先进到文件的目录中
docker cp laohu.txt chatgpt-qq-mirai-qq-bot-chatgpt-1:/app/presets/laohu.txt # 拷贝到容器里，docker-compose默认会给chatgpt容器起这个名
docker exec chatgpt-qq-mirai-qq-bot-chatgpt-1 ls /app/presets # 看看文件是不是真的拷进去了
```
如果在执行中找不到“chatgpt-qq-mirai-qq-bot-chatgpt-1”这个容器，则需要通过guoluyuan（https://github.com/lss233/chatgpt-mirai-qq-bot/issues/203#issuecomment-1445296363）提供的方法获取容器id，替换“chatgpt-qq-mirai-qq-bot-chatgpt-1”执行命令即可

**Comment by lss233** [comment]
不需要这么麻烦。只需要两步：
1. 编辑 docker-compose.yaml，找到关于预设的那一行注释，解除注释
2. 执行 docker-compose up -d 更新容器
然后你就能看见 presets 文件夹了。  

我下次更新的时候把这个注释默认解除吧，这样你们看着会更容易一些。

**Comment by knigth95** [comment]
> 不需要这么麻烦。只需要两步：
> 
> 1. 编辑 docker-compose.yaml，找到关于预设的那一行注释，解除注释
> 2. 执行 docker-compose up -d 更新容器
>    然后你就能看见 presets 文件夹了。
> 
> 我下次更新的时候把这个注释默认解除吧，这样你们看着会更容易一些。

![image](https://user-images.githubusercontent.com/91075975/221497985-d44d59d4-c46f-45a8-be4c-1f090a743369.png)
已经消除注释
![image](https://user-images.githubusercontent.com/91075975/221498095-dca31828-2d47-46eb-ad6b-9c50c23c1d56.png)

最后一行也没有回车
