### ISSUE TITLE
[BUG] 点击启动mirai.cmd后没有任何反应

### ISSUE THREAD

**Issue by Jasonxuan666** [lss233/chatgpt-mirai-qq-bot#205]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
点击启动mirai.cmd后除了闪现一时的某个命令框，其他什么都没有。

**运行环境:**  
- 操作系统：win10
- Docker： ？
- 项目版本：1.5.7

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 初始化非常顺利，提示我打开mirai.cmd
2. 打不开（也许是闪退）

**预期行为**  
正常情况应该能打得开

**截图**  
无

**其他内容**  
我用的是google登录的，我在打开chatgpt.cmd之后，除了链接不上mirai（因为我根本打不开）以外，其他运行一切正常。

**Comment by lss233** [comment]
Mirai 无法启动是 Mirai 的问题，建议向 Mirai 开发团队寻求帮助。  

如果你使用的是Windows 快速部署包部署，这有可能是你在初始化的时候忽略了某个错误造成的。你需要提供相关运行结果的输出或截图，这样我才能确定问题。

另外，你可以使用 1.5.8-alpha 版本，此版本现已内嵌运行环境，可以避免此类问题发生。

**Comment by Jasonxuan666** [comment]
谢谢。问题已解决

**Comment by Jasonxuan666** [comment]
> Mirai 无法启动是 Mirai 的问题，建议向 Mirai 开发团队寻求帮助。
> 
> 如果你使用的是Windows 快速部署包部署，这有可能是你在初始化的时候忽略了某个错误造成的。你需要提供相关运行结果的输出或截图，这样我才能确定问题。
> 
> 另外，你可以使用 1.5.8-alpha 版本，此版本现已内嵌运行环境，可以避免此类问题发生。

谢谢。问题已解决
