### ISSUE TITLE
可否同时挂多个账号

### ISSUE THREAD

**Issue by xiaotong6666** [lss233/chatgpt-mirai-qq-bot#208]
您好，作者，最近我弄了这个机器人，在我的几个群里有人需要将他的账号挂来我这里，mirai可以同时登录多个账号，这个chatgpt的机器人不行，目前我的解决办法是，启动一次登录一个账号，然后修改配置文件再启动，就是想拥有一个这样的功能，如果已经实现，能否告诉我该如何操作（恼
还有，我还希望能够有个白名单/黑名单啥的，避免我小号有的群不想使用chatgpt但是还能被别人乱用（比如一些人疯狂用，搞到我被1小时限制了（如果已经实现，能否告诉我该如何操作（awa

**Comment by fubostudy** [comment]
我也想知道，求教

**Comment by magisk317** [comment]
> mirai可以同时登录多个账号，这个chatgpt的机器人不行

后半句是哪里来的结论？配置文档里有写多个账号的示例吧，看下56-70行
https://github.com/lss233/chatgpt-mirai-qq-bot/blob/browser-version/config.example.cfg

```
# # 第 2 个账号信息
# [[openai.accounts]]
# mode = 'browser'
# email = "xxxxx" 
# password = "xxxxx"
# # proxy="http://127.0.0.1:1080"
# paid = false

# # 第 3 个账号信息
# [[openai.accounts]]
# mode = 'browser'
# email = "xxxxx" 
# password = "xxxxx"
# # proxy="http://127.0.0.1:1080"
# paid = false

```

**Comment by fubostudy** [comment]
> > mirai可以同时登录多个账号，这个chatgpt的机器人不行
> 
> 后半句是哪里来的结论？配置文档里有写多个账号的示例吧，看下56-70行 https://github.com/lss233/chatgpt-mirai-qq-bot/blob/browser-version/config.example.cfg
> 
> ```
> # # 第 2 个账号信息
> # [[openai.accounts]]
> # mode = 'browser'
> # email = "xxxxx" 
> # password = "xxxxx"
> # # proxy="http://127.0.0.1:1080"
> # paid = false
> 
> # # 第 3 个账号信息
> # [[openai.accounts]]
> # mode = 'browser'
> # email = "xxxxx" 
> # password = "xxxxx"
> # # proxy="http://127.0.0.1:1080"
> # paid = false
> ```

我理解想说的是一个服务器如何挂多个这个项目

**Comment by magisk317** [comment]
> > > mirai可以同时登录多个账号，这个chatgpt的机器人不行
> > 
> > 
> > 后半句是哪里来的结论？配置文档里有写多个账号的示例吧，看下56-70行 https://github.com/lss233/chatgpt-mirai-qq-bot/blob/browser-version/config.example.cfg
> > ```
> > # # 第 2 个账号信息
> > # [[openai.accounts]]
> > # mode = 'browser'
> > # email = "xxxxx" 
> > # password = "xxxxx"
> > # # proxy="http://127.0.0.1:1080"
> > # paid = false
> > 
> > # # 第 3 个账号信息
> > # [[openai.accounts]]
> > # mode = 'browser'
> > # email = "xxxxx" 
> > # password = "xxxxx"
> > # # proxy="http://127.0.0.1:1080"
> > # paid = false
> > ```
> 
> 我理解想说的是一个服务器如何挂多个这个项目

为啥要挂多个呢？mirai可以登多个，ChatGPT也可以登多个，你的意思是想多个账号在线回复你，是吧？我觉得这个应该叫实例。。。等开发大佬看看吧

**Comment by lss233** [comment]
多个实例就复制多个程序然后分开运行就好了……  
程序本身是没有对实例数量进行限制的。  
唯一需要考虑的是 mirai api http 端口冲突，这种问题改下端口就行了。

**Comment by xiaotong6666** [comment]
![Screenshot](https://user-images.githubusercontent.com/110387028/221950770-1bf0c505-31ed-4c25-9ed2-24effd1ee3bd.png)
我蒸乌鱼了。。。
解决方法如图所示，一个mirai，好几个chatgp机器人t的py程序，其他的每个代表不同的QQ号，端口用同一个没有问题
只不过麻烦了点（awa

**Comment by xiaotong6666** [comment]
![Screenshot](https://user-images.githubusercontent.com/110387028/221952269-6afe24af-6831-42bb-bf95-c48c7d32a999.png)


> > mirai可以同时登录多个账号，这个chatgpt的机器人不行
> 
> 后半句是哪里来的结论？配置文档里有写多个账号的示例吧，看下56-70行 https://github.com/lss233/chatgpt-mirai-qq-bot/blob/browser-version/config.example.cfg
> 
> ```
> # # 第 2 个账号信息
> # [[openai.accounts]]
> # mode = 'browser'
> # email = "xxxxx" 
> # password = "xxxxx"
> # # proxy="http://127.0.0.1:1080"
> # paid = false
> 
> # # 第 3 个账号信息
> # [[openai.accounts]]
> # mode = 'browser'
> # email = "xxxxx" 
> # password = "xxxxx"
> # # proxy="http://127.0.0.1:1080"
> # paid = false
> ```
![Screenshot](https://user-images.githubusercontent.com/110387028/221952269-6afe24af-6831-42bb-bf95-c48c7d32a999.png)
我蒸乌鱼了。。。
解决方法如图所示，一个mirai，好几个chatgp机器人t的py程序，其他的每个代表不同的QQ号，端口用同一个没有问题
只不过麻烦了点（qwq

**Comment by xiaotong6666** [comment]
> 多个实例就复制多个程序然后分开运行就好了…… 程序本身是没有对实例数量进行限制的。 唯一需要考虑的是 mirai api http 端口冲突，这种问题改下端口就行了。

怎么说呢，我是启动一次改（配置文件）一次机器人QQ号，然后再接入mirai（只不过稍有麻烦，希望可以添加多个机器人QQ，主要是帮别人挂）

**Comment by lss233** [comment]
不考虑此功能。
你完全可以复制多份程序，每个程序使用不同的配置。
