### ISSUE TITLE
[BUG] 登录时返回certificate verify failed错误

### ISSUE THREAD

**Issue by DomeenoH** [lss233/chatgpt-mirai-qq-bot#209]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
![image](https://user-images.githubusercontent.com/29730075/221424056-877e5097-d815-4fd8-a538-48f9f35af8b2.png)
登录时返回
```
HTTPSConnectionPool(host='chatgpt.duti.tech', port=443): Max retries exceeded with url: /api/conversations?offset=0&limit=1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1129)')))
```
不知道是不是与浏览器有关系？服务器上只有IE，访问openAI网页会提示版本过旧
![image](https://user-images.githubusercontent.com/29730075/221424152-9ad01dc5-fc1d-4282-8fb7-55eebdcd4f54.png)

**运行环境:**  
- 操作系统：Windows Server 2019 Datacenter
- 项目版本：[v1.5.8-beta](https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v1.5.8-beta)

**复现步骤**  
描述你是如何触发这个 BUG 的
无浏览器登录返回错误

**Comment by DomeenoH** [comment]
尝试了使用http代理，同样能够复现这个问题
![image](https://user-images.githubusercontent.com/29730075/221424950-d76ff367-e6ac-4a14-8e44-0c024ae5a651.png)

**Comment by DomeenoH** [comment]
尝试使用http代理，但还是遇到了同样的报错![image](https://user-images.githubusercontent.com/29730075/221425011-0ac499cd-c286-41e9-b0c8-5cfa8229002f.png)

**Comment by lss233** [comment]
这个就是你连接OpenAI的网络不佳而已。红字已经把情况说明了。
