### ISSUE TITLE
[BUG] 卡在Found Session Token，但并不是issue之前提到的原因

### ISSUE THREAD

**Issue by xixixi2000** [lss233/chatgpt-mirai-qq-bot#211]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
卡在Found Session Token，但不是登录不成功，浏览器上看是登录成功了，呆在了ChatGPT,, "This is a free research preview"和chrome的保存登录账户密码弹窗，然后就没动作了，手动可以操作

**运行环境:**  
- 操作系统：Centos7
- Docker： 手动跑的，没用Docker
- 项目版本：2.27日当前最新版zip文件，刚下的

**复现步骤**  
描述你是如何触发这个 BUG 的
1. Go to '...'  手动运行 python3 bot.py (python3版本3.9.16)

**预期行为**  
描述你认为正常情况下应该看见的情况，登录成功后，机器人应该干活，而不是卡在那

**截图**  
相关日志、聊天记录的截图，没有可跳过

![d9cea8092248deffe6cb29a8ffb8370](https://user-images.githubusercontent.com/54608209/221475509-d698403b-f741-4701-aa5b-a861ed9af781.png)
![238829594c09b321af127a7174c591f](https://user-images.githubusercontent.com/54608209/221475546-3569a311-b1b5-46a1-bdc0-2744bb90fda1.png)

**其他内容**  
此处填写其他内容，没有可跳过

之前按照指引用browserless，不过第三方代理似乎爆满了，从昨天开始出现了链接不上的问题
另外，一直出下面的提示
2023-02-27 12:30:31,788 - urllib3.connectionpool - WARNING - _put_conn - Connection pool is full, discarding connection: localhost. Connection pool size: 1

**Comment by lss233** [comment]
browserless 恢复了。换回去就可以了。浏览器模式只有特定  IP 可以用。

**Comment by xixixi2000** [comment]
![25228dcfec1e4e3986dfd6f0f8ee602](https://user-images.githubusercontent.com/54608209/221786431-1c31afd7-251b-4136-b23d-8d4108e0dd06.png)
问题出在Unofficial里面，一直等待puid_cookie，去掉就行了

**Comment by lss233** [comment]
不过即便去掉了 puid， 还是有可能会出现重新获取 cf_clearance 的情况

**Comment by xixixi2000** [comment]
是的，问题出现在获取api/auth/session的时候报403，可是我用driver打开的浏览器操作是可以正常打开的，但是session_token跟获取的不一样，真是百思不得其解
