### ISSUE TITLE
群聊时和私聊不一样，感觉模式反了，私聊时会回复消息，群聊却不会[BUG] 请填写标题

### ISSUE THREAD

**Issue by knigth95** [lss233/chatgpt-mirai-qq-bot#215]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
群聊时和私聊不一样，感觉模式反了，私聊时会回复消息，群聊却不会

**运行环境:**  
- 操作系统：cenos7
- Docker： 自动部署
- 项目版本：新版

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
就是私聊的情况应该是群聊才会有的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过
![image](https://user-images.githubusercontent.com/91075975/221509238-0fdafae1-e4df-4aaa-87db-e7ce7cf474bc.png)
![image](https://user-images.githubusercontent.com/91075975/221509307-d93d3348-8b5a-4735-9486-b16eac28b7ec.png)
**其他内容**  
此处填写其他内容，没有可跳过

**Comment by hejun041** [comment]
我的群聊也没有消息了呢，私聊正常

**Comment by magisk317** [comment]
@hejun041 @knigth95 是不是需要艾特呢，试试群里带艾特

**Comment by lss233** [comment]
你指的是机器人发送消息时没有引用原文吗？

**Comment by knigth95** [comment]
我群聊唤醒机器人一直有@发自我的手机-------- 原始邮件 --------发件人： magisk317 ***@***.***>日期： 2023年2月27日周一 17:42收件人： lss233/chatgpt-mirai-qq-bot ***@***.***>抄送： knight_zzm ***@***.***>, Mention ***@***.***>主    题： Re: [lss233/chatgpt-mirai-qq-bot] 群聊时和私聊不一样，感觉模式反了，私聊时会回复消息，群聊却不会[BUG] 请填写标题 (Issue #215)

@hejun041 @knigth95 是不是需要艾特呢，试试群里带艾特

**Comment by knigth95** [comment]
对，私聊正常，群聊没有发自我的手机-------- 原始邮件 --------发件人： Dark Litss ***@***.***>日期： 2023年2月27日周一 22:03收件人： lss233/chatgpt-mirai-qq-bot ***@***.***>抄送： knight_zzm ***@***.***>, Mention ***@***.***>主    题： Re: [lss233/chatgpt-mirai-qq-bot] 群聊时和私聊不一样，感觉模式反了，私聊时会回复消息，群聊却不会[BUG] 请填写标题 (Issue #215)

你指的是机器人发送消息时没有引用原文吗？

**Comment by lss233** [comment]
你确定你用的是最新版吗？ 看看你的docker-compose.yaml 文件

**Comment by knigth95** [comment]
我是昨天还是前天拉的docker，按照描述是新版的，文件明天再截图，现在电脑不在身边，平板连登上去看文件中文会乱码（用aidlux连）发自我的手机-------- 原始邮件 --------发件人： Dark Litss ***@***.***>日期： 2023年2月28日周二 00:07收件人： lss233/chatgpt-mirai-qq-bot ***@***.***>抄送： knight_zzm ***@***.***>, Mention ***@***.***>主    题： Re: [lss233/chatgpt-mirai-qq-bot] 群聊时和私聊不一样，感觉模式反了，私聊时会回复消息，群聊却不会[BUG] 请填写标题 (Issue #215)

你确定你用的是最新版吗？ 看看你的docker-compose.yaml 文件

**Comment by hejun041** [comment]
> 你确定你用的是最新版吗？ 看看你的docker-compose.yaml 文件

我的是最新版的，但是使用甲骨文搭的
用的这个[https://github.com/lss233/chatgpt-mirai-qq-bot/issues/81#issuecomment-1435927345](url)
昨天骚操作了可以看见群聊了，但是今天好像又不行了，什么都没有修改
[https://github.com/lss233/chatgpt-mirai-qq-bot/issues/190#issuecomment-1445998045](url)

**Comment by knigth95** [comment]
> 你确定你用的是最新版吗？ 看看你的docker-compose.yaml 文件

![image](https://user-images.githubusercontent.com/91075975/221782978-b5d076ff-3d45-46ce-a22e-057509021e7b.png)

**Comment by KPotter0413** [comment]
应该是新版的，我今天刚安装的，也出现这个问题了，装的是api版本的
