### ISSUE TITLE
[BUG] 代码没完全渲染成功（附图）

### ISSUE THREAD

**Issue by Laurc2004** [lss233/chatgpt-mirai-qq-bot#216]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
上面有些代码没完全渲染成功

**运行环境:**  
- 操作系统：Windows 10
- Docker： 无 Windows一键部署
- 项目版本：1.5.8 beta

**复现步骤**  
描述你是如何触发这个 BUG 的
我：写一个带dao操作的JavaBean
ChatGPT：（如下截图）

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
![iss](https://user-images.githubusercontent.com/119660750/221545279-c696df31-d566-4916-8456-6375ee2636ee.png)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by Laurc2004** [comment]
首先排除ChatGPT本身的问题，找到原对话
![image](https://user-images.githubusercontent.com/119660750/221546142-943cca81-a5de-4ca2-8d46-e61cc146a3b5.png)

**Comment by lss233** [comment]
好的，保持关注

**Comment by lss233** [comment]
现在已经不会出现此问题了。
