### ISSUE TITLE
[Feature] 重置会话时重新载入 default 预设

### ISSUE THREAD

**Issue by zyf722** [lss233/chatgpt-mirai-qq-bot#218]
现有情况下遇到 OpenAI 服务器问题（“Something went wrong, please try reloading the conversation.”）后尝试重置会话，默认预设人格不会被载入，希望能够在重置会话时重新载入 default 预设。

**Comment by lss233** [comment]
此bug已被修复。

**Comment by xixixi2000** [comment]
重置会话后，是不是用了新的会话？原来的会话能不能找回？

**Comment by lss233** [comment]
是的。

**Comment by lss233** [comment]
这个错误一般来说是 OpenAI 的问题。 我已改进了错误提示

**Comment by xixixi2000** [comment]
这个问题出现非常随机，原因之一是因为parent_id不对。比如同一个账号两边登录，打开同一个conversation id说话，立马就会得到这个错误，也就是多线程访问同一个会话，甚至只是同一个账号不同会话，就有可能出现。可是即使不这么做，这个错误也会随机出现，不知道是不是revChat GPT的处理过程有漏洞，出现之后的处理方法就是把parent id重置成None，让服务器自己根据conversation id重新生成一个parent id
