### ISSUE TITLE
运行启动Mirai报错

### ISSUE THREAD

**Issue by knbnaz** [lss233/chatgpt-mirai-qq-bot#221]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：Windows10
- Docker： ？
- 项目版本：1.5.7

**复现步骤**  
描述你是如何触发这个 BUG 的
运行启动Mirai时，频繁报错
**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
![image](https://user-images.githubusercontent.com/107289432/221821683-a9da2d52-f9fc-46f3-af63-692fab3fc554.png)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by xixixi2000** [comment]
貌似是地址和端口被占用了，可以把地址用127.0.0.1或者localhost，端口用8080试下，记得mcl和bot都要改成一样的

**Comment by knbnaz** [comment]
> 貌似是地址和端口被占用了，可以把地址用127.0.0.1或者localhost，端口用8080试下，记得mcl和bot都要改成一样的 每次重启之前把残留的进程都干掉清理干净再启动

**Comment by knbnaz** [comment]
滑块验证助手没了，那个网页抓取秘钥看不懂哇
