### ISSUE TITLE
滑块验证助手没了

### ISSUE THREAD

**Issue by knbnaz** [lss233/chatgpt-mirai-qq-bot#222]

**Comment by Jiongoh** [comment]
同样无法加载滑块助手，而且提供的url滑块验证无法获取到ticket

**Comment by lss233** [comment]
是的，目前只能使用此方法来完成滑块验证。 https://github.com/takayama-lily/node-onebot/issues/28
无法获取 ticket 的话先确保自己把所有的验证码都完成了，然后看最后一个请求里有没有 ticket。  如果都没有，那就重新登录一次
