### ISSUE TITLE
[BUG] 根据issues修改后仍出现 Websocket reconnecting in 5s

### ISSUE THREAD

**Issue by Cookies514** [lss233/chatgpt-mirai-qq-bot#234]
**提交 issue 前，请先确认：**
- [] 我已看过 **FAQ**，此问题不在列表中
- [√ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
根据#142全流程检查，端口等等都正确，但最后仍旧出现websocket reconnecting in5s

**运行环境:**  
- 操作系统：windows10
- Docker： 快速部署
- 项目版本：Windows-quickstart-refs.tags.v1.5.7

**截图**  
![QQ截图20230302221905](https://user-images.githubusercontent.com/126750076/222454440-1e7d85fe-6396-4b66-8c56-4aff06d0c47f.png)
![QQ截图20230302221935](https://user-images.githubusercontent.com/126750076/222454453-049cf5aa-f6d7-47ba-9ea6-049758776472.png)

**Comment by byzp** [comment]
api被墙了，你需要配置代理

**Comment by lss233** [comment]
1. 不要关闭 mirai 窗口
2. 确保你的 qq 写的是正确的
从你提供的两个两份日志里我无法确认这两点

**Comment by Cookies514** [comment]
> 1. 不要关闭 mirai 窗口
> 2. 确保你的 qq 写的是正确的
>    从你提供的两个两份日志里我无法确认这两点是否正确，你可以看看

qq是成功登录上了的，同时mirai也开着 如下图
![QQ截图20230304174502](https://user-images.githubusercontent.com/126750076/222892297-77d282d1-ccc9-4337-a01c-ce52b1764c43.png)

**Comment by raoyang1231** [comment]
> > 1. 不要关闭 mirai 窗口
> > 2. 确保你的 qq 写的是正确的
> >    从你提供的两个两份日志里我无法确认这两点是否正确，你可以看看
> 
> qq是成功登录上了的，同时mirai也开着 如下图 ![QQ截图20230304174502](https://user-images.githubusercontent.com/126750076/222892297-77d282d1-ccc9-4337-a01c-ce52b1764c43.png)

我也是，开了代理也经常与到！

**Comment by raoyang1231** [comment]
> 1. 不要关闭 mirai 窗口
> 2. 确保你的 qq 写的是正确的
>    从你提供的两个两份日志里我无法确认这两点是否正确，你可以看看

我也经常遇到！开了代理也不行（所有窗口都开着）！

**Comment by raoyang1231** [comment]
我觉得加一个websocket心跳重连！可以解决这个问题！

**Comment by GentsunCheng** [comment]
同 x86 openwrt docker-compose部署，相同情况，openai账号登录成功，mirai账号正常登录

**Comment by lss233** [comment]
此issue过于遥远，已close。
现在的最新版本已经默认配置好了 mirai连接的相关设置，不需要手动配置即可使用。
如果还有问题，可以尝试恢复到默认配置，并确保正确启动了程序。
