### ISSUE TITLE
[Feature] system prompt

### ISSUE THREAD

**Issue by DevHaoZi** [lss233/chatgpt-mirai-qq-bot#236]
revChatGPT V3在初始化的时候可以传入一个system_prompt，用来自定义角色（开车）。

也许可以考虑结合现有的预设使用。

**Comment by DevHaoZi** [comment]
使用system_prompt比现有的预设模板要简单很多，一句话即可完成设定。

可能要新开一个设置项？

**Comment by lss233** [comment]
在 v2.0 中，在预设中按照
```
system: xxx
```
这种写法即可使用 system prompt 。
