### ISSUE TITLE
启动报错no such file or directory

### ISSUE THREAD

**Issue by HuanKongzzz** [lss233/chatgpt-mirai-qq-bot#237]
如图
![Screenshot_20230303_105917](https://user-images.githubusercontent.com/119497994/222620375-1246306e-2a85-4a74-a7ea-d7878ecf802a.jpg)

**Comment by HuanKongzzz** [comment]
配置文件已放在对应目录且多次确认内容无误

**Comment by lss233** [comment]
你启动的方式不太对吧，我看你CMD的工作路径不在 chatgpt 文件夹

不要以管理员模式启动脚本，再试试看

**Comment by HuanKongzzz** [comment]
解决了，谢谢

**Comment by kerna60** [comment]
咋解决的啊，我就以普通权限运行程序报这个错
