### ISSUE TITLE
 [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。

### ISSUE THREAD

**Issue by CraneHuang6** [lss233/chatgpt-mirai-qq-bot#238]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FC12BA9D90>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。'))

**运行环境:**  
- 操作系统：win10
![image](https://user-images.githubusercontent.com/13868737/222632999-31eaa126-5c3e-4b9c-830d-e55dba0daaa6.png)

**Comment by shenhuyong** [comment]
用API时不走代理端口，我也发现了，Clash开系统代理就正常了

**Comment by lss233** [comment]
stale
