### ISSUE TITLE
只能收到信息，不回

### ISSUE THREAD

**Issue by 666Thanos** [lss233/chatgpt-mirai-qq-bot#240]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：ubuntu22. 04
- Docker： ？
- 项目版本：1. 5. 7

**截图**  
chatgpt-qq-mirai-1 | 2023-03-03 07:30:54 V/Bot.3373755250: 24k纯 帅 (1805172633) -> 6 chatgpt-qq-chatgpt-1 | chatgpt-qq-chatgpt-1 | Warning: running as root chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:12,701 Warning: cannot enable SSH socket upgrades chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:12,701 No module named 'paramiko' chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:12,702 created tcp socket '0.0.0.0:14500' chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:12,704 no uinput module (not usually needed) chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:13,910 pointer device emulation using XTest chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:13,944 serving html content from '/usr/share/xpra/www' chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:13,946 wrote pid 7 to '/tmp/0/server.pid' chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:13,958 Warning: socket directory '/tmp/0' chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:13,959 expected permissions 700 but found 750 chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:13,959 created unix domain socket '/run/user/1000/xpra/0c6ddaef5b97-0' chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:13,959 created unix domain socket '/tmp/0/socket' chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:13,960 xvfb pid=11 chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,028 Warning: cannot watch for application menu changes without pyinotify: chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,029 No module named 'pyinotify' chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,035 Warning: webcam forwarding is disabled chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,035 the virtual video directory '/sys/devices/virtual/video4linux' was not found chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,036 make sure that the 'v4l2loopback' kernel module is installed and loaded chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,036 or use the 'webcam=no' option chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,036 found 0 virtual video devices for webcam forwarding chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,040 Warning: cannot load menu data chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,041 started command `xterm -e python bot.py 2>&1 | tee /tmp/log.txt` with pid 29 chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,041 No module named 'xdg' chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,139 1.9GB of system memory chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,227 waiting for initialization thread to complete chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,228 xpra is ready. chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,229 xpra X11 seamless version 4.4.3-r0 64-bit chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,229 uid=0 (root), gid=0 (root) chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,229 running with pid 7 on Linux Debian 11 bullseye chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,229 connected to X11 display :0 with 24 bit colors chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,267 Warning: OpenGL support check failed: chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:14,267 unknown error chatgpt-qq-chatgpt-1 | 2023-03-03 07:31:15.081 | ERROR | config:load_config:261 - invalid literal for int() with base 0: '请 修 改 为 机 器 人 管 理 员 的 QQ号 ' (line 9 column 1 char 115) chatgpt-qq-chatgpt-1 | Traceback (most recent call last): chatgpt-qq-chatgpt-1 | chatgpt-qq-chatgpt-1 | File "/usr/local/lib/python3.9/site-packages/toml/decoder.py", line 511, in loads chatgpt-qq-chatgpt-1 | ret = decoder.load_line(line, currentlevel, multikey, chatgpt-qq-chatgpt-1 | │ │ │ │ └ None chatgpt-qq-chatgpt-1 | │ │ │ └ {'qq': 3373755250} chatgpt-qq-chatgpt-1 | │ │ └ 'manager_qq = 请 修 改 为 机 器 人 管 理 员 的 QQ号 ' chatgpt-qq-chatgpt-1 | │ └ chatgpt-qq-chatgpt-1 | └ chatgpt-qq-chatgpt-1 | File "/usr/local/lib/python3.9/site-packages/toml/decoder.py", line 778, in load_line chatgpt-qq-chatgpt-1 | value, vtype = self.load_value(pair[1], strictly_valid) chatgpt-qq-chatgpt-1 | │ │ │ └ True chatgpt-qq-chatgpt-1 | │ │ └ ['manager_qq', '请 修 改 为 机 器 人 管 理 员 的 QQ号 '] chatgpt-qq-chatgpt-1 | │ └ chatgpt-qq-chatgpt-1 | └ chatgpt-qq-chatgpt-1 | File "/usr/local/lib/python3.9/site-packages/toml/decoder.py", line 918, in load_value chatgpt-qq-chatgpt-1 | v = int(v, 0) chatgpt-qq-chatgpt-1 | └ '请 修 改 为 机 器 人 管 理 员 的 QQ号 ' chatgpt-qq-chatgpt-1 | chatgpt-qq-chatgpt-1 | ValueError: invalid literal for int() with base 0: '请 修 改 为 机 器 人 管 理 员 的 QQ号 ' chatgpt-qq-chatgpt-1 | chatgpt-qq-chatgpt-1 | chatgpt-qq-chatgpt-1 | During handling of the above exception, another exception occurred: chatgpt-qq-chatgpt-1 | chatgpt-qq-chatgpt-1 | chatgpt-qq-chatgpt-1 | Traceback (most recent call last): chatgpt-qq-chatgpt-1 | chatgpt-qq-chatgpt-1 | File "/app/bot.py", line 28, in chatgpt-qq-chatgpt-1 | import chatbot chatgpt-qq-chatgpt-1 | chatgpt-qq-chatgpt-1 | File "", line 1007, in _find_and_load chatgpt-qq-chatgpt-1 | File "", line 986, in _find_and_load_unlocked chatgpt-qq-chatgpt-1 | File "", line 680, in _load_unlocked chatgpt-qq-chatgpt-1 | File "", line 850, in exec_module chatgpt-qq-chatgpt-1 | File "", line 228, in _call_with_frames_removed chatgpt-qq-chatgpt-1 | chatgpt-qq-chatgpt-1 | File "/app/chatbot.py", line 4, in chatgpt-qq-chatgpt-1 | from 
![Screenshot_20230303_153206_Termius](https://user-images.githubusercontent.com/106792549/222659180-7b826e69-0797-4c9d-b5b9-737f2fb71961.jpg)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by KPotter0413** [comment]
你把config文件里面的“manager_qq = 请修改为机器人管理员的QQ号”这一行前面加个#，然后restart一下试试

**Comment by gngpp** [comment]
我这就只能私聊回，群怎么at好像都没反应
