### ISSUE TITLE
[BUG] 在使用完一键配置后，无法正常使用机器人

### ISSUE THREAD

**Issue by matthewsunasd** [lss233/chatgpt-mirai-qq-bot#241]
**提交 issue 前，请先确认：**
- [ ] 我已看过 **FAQ**，此问题不在列表中
- [ x ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
在使用api模式设置完成之后，无法得到回复，按照设置看出来是超时了，并且从openai的api的使用记录来看是完全没使用过
**运行环境:**  
- 操作系统：CentOS7.6
- Docker： Ubuntu20.04-Docker20
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
![QQ图片20230303195000](https://user-images.githubusercontent.com/70087041/222675145-dae41896-804c-414c-aa51-a2d5ba8169f6.png)

**其他内容**  
配置
![屏幕截图 2023-03-03 195218](https://user-images.githubusercontent.com/70087041/222675509-53567dde-898d-4427-ba5a-5bbdd95920c4.png)

**Comment by matthewsunasd** [comment]
![QQ图片20230303200823](https://user-images.githubusercontent.com/70087041/222679208-010b2c98-dd57-41bb-aeb4-d73b7bd277a0.png)
随后出现了这一段文字

**Comment by jinzhuer** [comment]
你好像使用了一个早已过期的模型，davinci002。如果你想使用之前的GPT3版本，请设置环境变量为text-davinci-003。如果想使用最新的chatgpt API，请升级最新版

**Comment by lss233** [comment]
#82
