### ISSUE TITLE
渲染公式时字符集错误

### ISSUE THREAD

**Issue by Einstein1905** [lss233/chatgpt-mirai-qq-bot#242]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [ √] 我已看过其他 issue，他们不能解决我的问题 
- [ √] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
正常输出图片时，有二维码样式，渲染这个的时候没有二维码等样式

**运行环境:**  
- 操作系统：win10
- 项目版本：1.5.8正式版

**复现步骤**  

问薛定谔方程一维势阱解

**预期行为**  
正常的时候图片带有二维码

**截图**  
相关日志、聊天记录的截图，没有可跳过
2023-03-03 16:52:43.996 | INFO     | graia.ariadne.model:log:82 - 3243056529: [RECV][归尘(717283466)] -> /薛定谔方程的一维势阱解
2023-03-03 16:53:01.548 | DEBUG    | __main__:handle_message:123 - friend-717283466 - 0

薛定谔方程描述了量子力学中粒子的波函数随时间和空间的演化，其中粒子的运动状态由波函数 ψ(x,t) 描述。对于一维势阱问题，我们可以将其势函数表示为：

V(x) = 0, 0 < x < a

V(x) = ∞, x < 0 或 x > a

其中，a表示势阱的宽度，V(x)表示在位置x处的势能。

薛定谔方程的一维势阱解可以通过以下步骤求解：

1. 写出薛定谔方程

薛定谔方程可以表示为：

iħ ∂ψ/∂t = -ħ^2/2m ∂^2ψ/∂x^2 + V(x)ψ

其中，i表示虚数单位，ħ表示约化普朗克常数，m表示粒子的质量，V(x)表示在位置x处的势能，ψ表示波函数。

2. 将波函数表示为展开系数的形式

我们将波函数表示为一个无穷级数的形式：

ψ(x,t) = Σ cn(t) φn(x)

其中，cn(t) 是时间的函数， φn(x) 是空间的函数，而 n 表示能量本征态的编号。

3. 求解时间演化方程

将波函数的展开式代入薛定谔方程中，我们可以得到：

iħ ∂/∂t (Σ cn(t) φn(x)) = -ħ^2/2m ∂^2/∂x^2 (Σ cn(t) φn(x)) + V(x) Σ cn(t) φn(x)

将波函数中的不同能量本征态分别考虑，可以得到一组耦合的微分方程：

iħ ∂cn/∂t = En cn(t) + Σ cn'(t) En'm φm(x)

其中，En = ħ^2 n^2 π^2 / 2ma^2 是能量本征值，cn'(t) 是展开系数的导数，而 En'm = ∫0^a φn(x) (-ħ^2/2m) ∂^2φm(x)/∂x^2 dx 表示不同能级之间的耦合项。

4. 求解空间波函数

通过求解一组耦合的微分方程，我们可以得到展开系数 cn(t) 随时间的演化规律。然后，我们可以将 cn(t) 代入波函数的展开式中，得到波函数在时刻 t 的形式。

对于一维势阱问题，空间波函数 φn(x) 可以表示为：

φn(x) = sqrt(2/a) sin(nπx/a)

其中，n 表示能量本征态的编号。

因此，一维势阱的波函数可以表示为：

ψ(x,t) = Σ cn(t) sqrt(2/a) sin(nπx/a)

其中，cn(t) 是展开系数，而 n 表示能量本征态的编号。
2023-03-03 16:53:01.973 | ERROR    | utils.text_to_img:text_to_image:348 - 'gbk' codec can't encode character '\u0127' in position 1262: illegal multibyte sequence
Traceback (most recent call last):

  File "C:\Users\Administrator\Desktop\gpt\chatgpt\bot.py", line 274, in <module>
    app.launch_blocking()
    │   └ <classmethod object at 0x00000250A8208160>
    └ <graia.ariadne.app.Ariadne object at 0x00000250A520A400>

  File "C:\Users\Administrator\Desktop\gpt\chatgpt\python3.9\lib\site-packages\graia\ariadne\app.py", line 312, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x00000250A821E3B0>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x00000250A520A1C0>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x00000250A75F80D0>
    │   └ <launart.manager.Launart object at 0x00000250D3D68370>
    └ <class 'graia.ariadne.app.Ariadne'>

  File "C:\Users\Administrator\Desktop\gpt\chatgpt\python3.9\lib\site-packages\launart\manager.py", line 494, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at C:\Users\Administrator\Desktop\gpt\chatgpt\python3.9\li...
    │    └ <function BaseEventLoop.run_until_complete at 0x00000250A6FE3550>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 634, in run_until_complete
    ', '.join(str(exc) for exc in exceptions)))
                                  └ <module 'asyncio.exceptions' from 'C:\\Users\\Administrator\\Desktop\\gpt\\chatgpt\\python3.9\\python39.zip\\asyncio\\excepti...

  File "asyncio\windows_events.py", line 321, in run_forever

  File "asyncio\base_events.py", line 601, in run_forever
    exc.errno, 'error while '

  File "asyncio\base_events.py", line 1905, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x00000250D414A7C0>()>

  File "C:\Users\Administrator\Desktop\gpt\chatgpt\python3.9\lib\site-packages\graia\broadcast\__init__.py", line 191, in Executor
    result = await run_always_await(target_callable, **parameter_compile_result)
                   │                │                  └ {'app': <graia.ariadne.app.Ariadne object at 0x00000250A520A400>, 'friend': Friend(id=717283466, nickname='归尘', remark='归尘'),...
                   │                └ <function friend_message_listener at 0x00000250D3D810D0>
                   └ <function run_always_await at 0x00000250A763A0D0>

  File "C:\Users\Administrator\Desktop\gpt\chatgpt\python3.9\lib\site-packages\graia\broadcast\utilles.py", line 34, in run_always_await
    obj = await obj
                └ <coroutine object friend_message_listener at 0x00000250D40E7440>

  File "C:\Users\Administrator\Desktop\gpt\chatgpt\bot.py", line 180, in friend_message_listener
    await respond(friend, source, response)
          │       │       │       └ "薛定谔方程描述了量子力学中粒子的波函数随时间和空间的演化，其中粒子的运动状态由波函数 ψ(x,t) 描述。对于一维势阱问题，我 们可以将其势函数表示为：\n\nV(x) = 0, 0 < x < a\n\nV(x) = ∞, x < 0 或 x > ...
          │       │       └ Source(id=37362, time=datetime.datetime(2023, 3, 3, 8, 52, 43, tzinfo=datetime.timezone.utc), type='Source')
          │       └ Friend(id=, nickname='归尘', remark='归尘')
          └ <function respond at 0x00000250D3D73E50>

  File "C:\Users\Administrator\Desktop\gpt\chatgpt\bot.py", line 61, in respond
    await respond_as_image(target, source, response)
          │                │       │       └ "薛定谔方程描述了量子力学中粒子的波函数随时间和空间的演化，其中粒子的运动状态由波函数 ψ(x,t) 描述。对于一维势阱问题，我们可以将其势函数表示为：\n\nV(x) = 0, 0 < x < a\n\nV(x) = ∞, x < 0 或 x > ...
          │                │       └ Source(id=37362, time=datetime.datetime(2023, 3, 3, 8, 52, 43, tzinfo=datetime.timezone.utc), type='Source')
          │                └ Friend(id=, nickname='归尘', remark='归尘')
          └ <function respond_as_image at 0x00000250D3D73D30>

  File "C:\Users\Administrator\Desktop\gpt\chatgpt\bot.py", line 51, in respond_as_image
    return await app.send_message(target, await to_image(response),
                 │   │            │             │        └ "薛定谔方程描述了量子力学中粒子的波函数随时间和空间的演化，其中粒子的运动状态由波函数 ψ(x,t) 描述。对于一维势阱问题，我们可以将其势函数表示为：\n\nV(x) = 0, 0 < x < a\n\nV(x) = ∞, x < 0 或 x > ...
                 │   │            │             └ <function to_image at 0x00000250D3D02670>
                 │   │            └ Friend(id=717283466, nickname='归尘', remark='归尘')
                 │   └ <function Ariadne.send_message at 0x00000250A8227F70>
                 └ <graia.ariadne.app.Ariadne object at 0x00000250A520A400>

  File "C:\Users\Administrator\Desktop\gpt\chatgpt\utils\text_to_img.py", line 366, in to_image
    img = await text_to_image(text=text)
                │                  └ "薛定谔方程描述了量子力学中粒子的波函数随时间和空间的演化，其中粒子的运动状态由波函数 ψ(x,t) 描述。对于一维势阱问题，我们可以将其势函数表示为：\n\nV(x) = 0, 0 < x < a\n\nV(x) = ∞, x < 0 或 x > ...
                └ <function text_to_image at 0x00000250D3D025E0>

> File "C:\Users\Administrator\Desktop\gpt\chatgpt\utils\text_to_img.py", line 334, in text_to_image
    temp_html_file.write(output_file.getvalue())
    │              │     │           └ <method 'getvalue' of '_io.StringIO' objects>
    │              │     └ <_io.StringIO object at 0x00000250D4145310>
    │              └ <function TextIOWrapper.write at 0x00000250D4145430>
    └ <tempfile._TemporaryFileWrapper object at 0x00000250D4129C40>

  File "tempfile.py", line 478, in func_wrapper

UnicodeEncodeError: 'gbk' codec can't encode character '\u0127' in position 1262: illegal multibyte sequence
C:\Users\ADMINI~1\AppData\Local\Temp\2\tmp0tnckowq.png
C:\Users\ADMINI~1\AppData\Local\Temp\2\tmp12uy5ysk.html
![000000000-000000000-D71A3D5E55E08581C23FC91B053DA87E](https://user-images.githubusercontent.com/126863247/222678707-838b520a-3fb3-4c7e-9875-96b23ef21454.png)
**其他内容**  
此处填写其他内容，没有可跳过

**Comment by magisk317** [comment]
这个问题我一直想问，你们说的渲染，在QQ里可以看到效果吗？我记得QQ不支持这些吧？你们搞的这些又是在哪里用的呢？

**Comment by lss233** [comment]
这是 Markdown 渲染失败之后进入的一种备用模式，你需要提供日志，这样我才能知道为什么 Markdown 渲染失败了。

**Comment by Einstein1905** [comment]
> 这是 Markdown 渲染失败之后进入的一种备用模式，你需要提供日志，这样我才能知道为什么 Markdown 渲染失败了。

日志已经粘上去了
