### ISSUE TITLE
一直在等待，这正常吗[BUG] 请填写标题

### ISSUE THREAD

**Issue by knigth95** [lss233/chatgpt-mirai-qq-bot#243]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：Ubuntu 22.0
- Docker： docker自动部署
- 项目版本：docker自动部署

**复现步骤**  
描述你是如何触发这个 BUG 的
运行完指令，测试就是成这样

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过
![image](https://user-images.githubusercontent.com/91075975/222679992-7dd9a453-b0ff-4220-8ddd-26580e0f6d13.png)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
我觉得不正常，请提供一下 ChatGPT 和 Mirai 的**日志**

**Comment by lss233** [comment]
v2.2.0 已发布  已修复此问题

**Comment by knigth95** [comment]
> v2.2.0 已发布 已修复此问题

docker用户只需docker-compose pull && docker-compose up -d就行了吗，里面的配置（api-key）要不要重新更新

**Comment by knigth95** [comment]
> v2.2.0 已发布 已修复此问题

更新完后如何查询版本是否对应最新的

**Comment by knigth95** [comment]
> v2.2.0 已发布 已修复此问题

![image](https://user-images.githubusercontent.com/91075975/223022340-bd63de4f-a360-4815-99f0-390e725709fc.png)
这是更新重启docker后的chatgpt的log
