### ISSUE TITLE
[BUG] ChatGPT.cmd启动报错

### ISSUE THREAD

**Issue by Xingheee** [lss233/chatgpt-mirai-qq-bot#244]
**提交 issue 前，请先确认：**
- [ ] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：winserver2022
- Docker： ？
- 项目版本：1.5.8正式版

**复现步骤**  
描述你是如何触发这个 BUG 的
按照说明更新最新版本后，启动chatgpt.cmd时出现错误
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ChatGPTQQ\chatgpt\bot.py", line 28, in <module>
    import chatbot
  File "C:\Users\Administrator\Desktop\ChatGPTQQ\chatgpt\chatbot.py", line 4, in <module>
    from manager.bot import BotManager, BotInfo
ModuleNotFoundError: No module named 'manager.bot'; 'manager' is not a package
按照FAQ重新初始化以及安装依赖都没用,也尝试了重新下载也不行，稍早发布的1.58的测试版本可以正常运行
**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过
![image](https://user-images.githubusercontent.com/126763396/222683563-66db39ba-1c20-473a-8ce1-af4194bbe47c.png)
![image](https://user-images.githubusercontent.com/126763396/222687700-b15d0d64-c710-42be-b2c6-a4393a544fd7.png)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by yingweijun** [comment]
我也是，请问楼主有没有解决这个问题，蹲

**Comment by Xingheee** [comment]
> 我也是，请问楼主有没有解决这个问题，蹲

我现在用的上一个测试版，可以正常用，但是没法用api，等作者看下怎么解决吧

**Comment by lss233** [comment]
重新安装试试吧，我觉得你可能是覆盖升级导致的

**Comment by Xingheee** [comment]
> 

我在另一个目录重新下载初始化，也是同样的问题

**Comment by horizon86** [comment]
这8成是工作目录不对

**Comment by lss233** [comment]
stale
