### ISSUE TITLE
机器人收到私聊或者艾特报错

### ISSUE THREAD

**Issue by NanJiu533** [lss233/chatgpt-mirai-qq-bot#245]
![image](https://user-images.githubusercontent.com/79090449/222713655-c1b15c68-0199-45b6-89f2-4349712e8bdd.png)

**Comment by lss233** [comment]
日志不完整，无法判断　　
请提供下完整的报错信息。　　
另外，可以试试 v2.0 版能否解决你的问题

**Comment by lss233** [comment]
stale
