### ISSUE TITLE
[BUG] 修改了字体大小和字体，但返回的图片字体没有变动

### ISSUE THREAD

**Issue by 29Day** [lss233/chatgpt-mirai-qq-bot#246]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：windowsServer、Linux
- Docker： ？
- 项目版本：1.5.7

**复现步骤**  
描述你是如何触发这个 BUG 的

1. 修改config.cfg中关于文字转图片的字体大小、字体类型和图片宽度
2. 重启项目

**截图**  
![OI2HW3O7QW09N2_$4UV84YL](https://user-images.githubusercontent.com/112742019/222726244-d92813ec-f041-447e-a4c8-65c74705e3a3.jpg)

**其他内容**  
字体大小和类型不变，只有图片宽度改变了

**Comment by lss233** [comment]
我更新了配置文件中的描述。配置文件中的字体是备用模式的字体。
想要修改markdown模式的字体，需要修改assets/texttoimg中的html文件，需要一点html知识。
