### ISSUE TITLE
无法正常工作[BUG]

### ISSUE THREAD

**Issue by woshigenm** [lss233/chatgpt-mirai-qq-bot#250]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
无法正常运行

**运行环境:**  
- 操作系统：aarch64 debian
- Docker：No
- 项目版本：api 最新

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
正常运行

**截图**  
[nm.log](https://github.com/lss233/chatgpt-mirai-qq-bot/files/10886722/nm.log)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
看报错应该是你的配置文件哪里写错了。看看是不是什么地方漏了引号。

**Comment by woshigenm** [comment]
> 
![IMG_20230304_070223](https://user-images.githubusercontent.com/99122353/222851232-8d2004f5-1b99-4678-8cf1-55578c037851.jpg)

**Comment by lss233** [comment]
我觉得应该是你的 tempature 写了 1 导致的。设置成 0.9 吧。

**Comment by woshigenm** [comment]
> 我觉得应该是你的 tempature 写了 1 导致的。设置成 0.9 吧。
> 
> 另外 mirai 的 api key 是你 mirai api http 的 verifyKey，不是 OpenAI 的 api key，不要搞错了。

还是无法运行，一样的错误

**Comment by woshigenm** [comment]
将toml降级到0.9.0，运行正常

**Comment by lss233** [comment]
我的建议是你不要用这个版本了 
这是 text-davinci-003   不仅不适合聊天  还很贵
