### ISSUE TITLE
建议多账号多通道通过prefix来控制

### ISSUE THREAD

**Issue by chung1912** [lss233/chatgpt-mirai-qq-bot#254]
建议多账号多通道通过prefix来控制，每个账号但单独设置prefix，从而实现调用机器人不同的通道
比如prefix = [ "",]使用账号1，prefix = [ "！",]使用bing，prefix = [ "？",]使用账号4（chatGPT-api）

**Comment by lss233** [comment]
下一版本加入

**Comment by lss233** [comment]
2.2.0 版本已发布,现已支持此功能,具体用法请见 README
