### ISSUE TITLE
OPEN API验证失败

### ISSUE THREAD

**Issue by knbnaz** [lss233/chatgpt-mirai-qq-bot#256]
**提交 issue 前，请先确认：**
- [] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

![image](https://user-images.githubusercontent.com/107289432/222874275-879ad676-4401-4121-ae4a-ab2d858321b7.png)

**Comment by lss233** [comment]
与我无关
