### ISSUE TITLE
[BUG] Windows上似乎不支持"readline"包

### ISSUE THREAD

**Issue by Veloctor** [lss233/chatgpt-mirai-qq-bot#258]
**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：Windows 11 22H2
- Docker：无
- 项目版本：2023.3.4 14:30的browser-version分支最新状态

**复现步骤**  
描述你是如何触发这个 BUG 的
1.github desktop拉新
2.启动bot.py

**预期行为**  
可以跑起来

**截图**  
![image](https://user-images.githubusercontent.com/55224044/222879790-f562743b-10c3-4bc9-ab1d-65f8d7426acc.png)
当试图在requirements里加上'readline'包的时候: 
![image](https://user-images.githubusercontent.com/55224044/222879821-c0fc5e8d-e225-4244-926a-8bdc0a51137e.png)

**Comment by lss233** [comment]
可以试试这个方法：https://stackoverflow.com/questions/51157443/pythons-readline-module-not-available-for-windows

**Comment by magisk317** [comment]
> 可以试试这个方法：https://stackoverflow.com/questions/51157443/pythons-readline-module-not-available-for-windows

按照这个安装之后报这个错：

```
Traceback (most recent call last):
  File "D:\ROM\Windows-quickstart-refs.tags.v2.0.1\chatgpt\bot.py", line 34, in <module>
    from conversation import ConversationHandler
  File "D:\ROM\Windows-quickstart-refs.tags.v2.0.1\chatgpt\conversation.py", line 7, in <module>
    from adapter.ms.bing import BingAdapter
  File "D:\ROM\Windows-quickstart-refs.tags.v2.0.1\chatgpt\adapter\ms\bing.py", line 5, in <module>
    from EdgeGPT import Chatbot as EdgeChatbot
  File "D:\ROM\Windows-quickstart-refs.tags.v2.0.1\chatgpt\python3.9\lib\site-packages\EdgeGPT.py", line 117, in <module>
    class Conversation:
  File "D:\ROM\Windows-quickstart-refs.tags.v2.0.1\chatgpt\python3.9\lib\site-packages\EdgeGPT.py", line 122, in Conversation
    def __init__(self, cookiePath: str = "", cookies: dict | None = None) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
NativeCommandExitException: Program "python.exe" ended with non-zero exit code: 1.
```

**Comment by EvolvedGhost** [comment]
同Windows用户，在开Linux虚拟机了，缺包

已尝试：
· 安装`pyreadline3` ：`TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'`
· 将`\lib\site-packages\EdgeGPT.py`的`import readline`改为`from pyreadline3 import Readline` ：同上

**Comment by lss233** [comment]
我就说怎么我自己用就好好的呢，原来是刚加的 https://github.com/acheong08/EdgeGPT/pull/93/commits/43d07da7b927042d0a255ab314b727a3a8abc1aa

**Comment by lss233** [comment]
我发布了 2.0.2，锁定了用旧版，可以试试。

**Comment by Veloctor** [comment]
ok
