### ISSUE TITLE
简化部署流程

### ISSUE THREAD

**Issue by lss233** [lss233/chatgpt-mirai-qq-bot#26]
从 Issue 和 交流群 的反馈情况来看，跑通本项目的步骤还是比较复杂，可以探索更简便的方法。

**Comment by paradox8599** [comment]
我写了个临时docker脚本，大概可以简化一点流程。

https://github.com/paradox8599/mirai-chatgpt-setup

**Comment by paradox8599** [comment]
> 我写了个临时docker脚本，大概可以简化一点流程。
> 
> https://github.com/paradox8599/mirai-chatgpt-setup

我人傻了，忘记把自己的账号去掉了，一会儿重新传一份

**Comment by lss233** [comment]
感谢，我已经在 README.md 中介绍了你的脚本。

> 我写了个临时docker脚本，大概可以简化一点流程。
> 
> https://github.com/paradox8599/mirai-chatgpt-setup
