### ISSUE TITLE
[BUG] 在配置代理后无法正常连接api.openai.com

### ISSUE THREAD

**Issue by MrSnake0208** [lss233/chatgpt-mirai-qq-bot#262]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
在配置了代理的情况下无法连接api.openai.com，报错如下：
HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09124a76a0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**运行环境:**  
- 操作系统：CentOS 7.8
- Docker： 23.01
- 项目版本：2.02

**复现步骤**  
描述你是如何触发这个 BUG 的
1. docker-compose up启动
2. 向机器人发送消息
3. 后台Timeout开始计时
4. 报错

**预期行为**  
能够正常连接api.openai.com

**截图**  
报错中疑似相关部分
```
 File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
chatgpt_1     |     retries = retries.increment(
chatgpt_1     |               │       └ <function Retry.increment at 0x7f09576ece50>
chatgpt_1     |               └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
chatgpt_1     |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
chatgpt_1     |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
chatgpt_1     |           │             │      │    │        │             └ 'unknown'
chatgpt_1     |           │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
chatgpt_1     |           │             │      │    └ NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09124a76a0>: Failed to establish a new connection: [Err...
chatgpt_1     |           │             │      └ '/v1/chat/completions'
chatgpt_1     |           │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7f09124a77c0>
chatgpt_1     |           └ <class 'urllib3.exceptions.MaxRetryError'>
chatgpt_1     | 
chatgpt_1     | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f09124a76a0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```
代理配置部分
使用的Clash代理，端口为7890
# 如果你在国内，需要配置代理
proxy="http://127.0.0.1:7890"

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
那就换代理

**Comment by MrSnake0208** [comment]
> 那就换代理

其他应用都可以走代理访问外网，就是这个不行，设置全局代理、网桥、容器内代理都没有效果

容器内代理设置好之后可以wget到api.openai.com，但是应用还是无法连接到api.openai.com

**Comment by lss233** [comment]
代理的设置方法是在配置文件的账号里面加 `proxy=xxxx`

**Comment by hanwsf** [comment]
我也设置好了代理，但是问题相同：
chatgpt-qq-mirai-1    | 2023-03-04 13:42:15 V/Bot.xx: Friend(xxx) <- [mirai:quote:[mirai:source:ids=[11650], internalIds=[301887084], from friend xxx to xxx at 1677936942], content=chatgpt现在的版本是多少？]出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。\nError communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines/text-davinci-003/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f941f941df0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by lss233** [comment]
连接超时了  建议更换代理服务器  

而且你用的是 GPT-3 的 API 版本,现在建议用 ChatGPT 的 API 版本(2.x)

**Comment by MrSnake0208** [comment]
> 连接超时了 建议更换代理服务器
> 
> 而且你用的是 GPT-3 的 API 版本,现在建议用 ChatGPT 的 API 版本(2.x)

1. 使用的是目前2.1的ChatGPT的API版本即在配置文件中直接配置api_key与proxy
2. 改了很多次代理，都是其他应用都能正常调用代理翻墙，本应用不行

**Comment by MrSnake0208** [comment]
该图能够证明我代理配置是有效的正常的，在config.cfg中我设置的也是127.0.01:7890，但是确确实实是无效的
![image](https://user-images.githubusercontent.com/74225450/222940901-d19fa562-272e-4b7a-b648-77c83852299e.png)

**Comment by lss233** [comment]
如果你设置的是 `localhost:7890` 那就说明你设置错了  

你在容器里面网络是隔离的  
使用 localhost 访问不到你宿主机上运行的代理

**Comment by ElementQi** [comment]
同样的问题，我是在树莓派上搭建的，是armv7l架构。

在之前我的使用流程是在mirai文件夹内使用命令`sudo ./mcl`开启mirai终端，继而在项目文件夹下用`sudo python ./bot.py`开启项目机器人。

但是后来不能用了。我发现在pc上最近使用ChatGPT也需要爬梯子了，我之前是不用爬的。于是在树莓派上搭建了Clash，并且配置好了代理，和楼主一样能正常访问google。我的问题和楼主几乎一样，就是我没有使用docker。我将环境变量中的proxy和config.cfg中的代理用127.0.0.1和路由器下地址192.168.3.12都试了，一样在本应用中无法成功访问代理。

在我开启clash terminal后，我开启本应用，以下是Ariadne应用的报错情况：
```bash
2023-03-05 21:38:44.489 | INFO     | manager:login:110 - 正在登录第 1 个 OpenAI 账号

2023-03-05 21:38:44.528 | INFO     | manager:__login_V1:152 - 模式：无浏览器登录

2023-03-05 21:38:44.538 | INFO     | manager:__login_V1:154 - 正在检查代理配置：http://192.168.3.12:7890

2023-03-05 21:38:48.840 | ERROR    | manager:login:123 - 无法连接至本地代理服务器，请检查配置文件中的 proxy 是否正确！

登录 OpenAI ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
2023-03-05 21:38:48.872 | ERROR    | manager:login:134 - 所有账号均登录失败，无法继续启动！
```

此时，clash终端中同步出现了：
```
INFO[0366] [TCP] 192.168.3.12:45080 --> explorer.api.openai.com:443 match Match() using XX机场[XX XX | XX]
```

意味着监听到了端口的使用情况，但是没有访问成功。

**Comment by lss233** [comment]
```
无法连接至本地代理服务器，请检查配置文件中的 proxy 是否正确！
```
说明程序无法连接到 `192.168.3.12:7890`

至于你在日志中看见的 `explorer.api.openai.com` 和我的程序没有关系   

因为我在这一步的检测中只是尝试连接到那个地址，并没有进行代理访问

**Comment by MrSnake0208** [comment]
> 如果你设置的是 `localhost:7890` 那就说明你设置错了
> 
> 你在容器里面网络是隔离的 使用 localhost 访问不到你宿主机上运行的代理

我在进行了相关设置后，保证容器能够访问到代理了，使用docker-compose up然后出现了如下报错，并且导致容器无法正常开启（与我初始提出的问题处于两个阶段）
```
chatgpt_1     | requests.exceptions.ProxyError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe04a61cb50>: Failed to establish a new connection: [Errno 111] Connection refused')))
```
我怀疑是代理错误，我进行了一下操作
1. 我将代理关掉了，依旧报错
2. 我将代理取消，让他直接进行连接，依旧报错无法连接
3. 将所有后续更改的回档到我第一次报错的状态，依旧无法连接
4. 直接删除所有文件，重新按照教程进行搭建，依旧无法连接

**Comment by lss233** [comment]
> 2\. 改了很多次代理，都是其他应用都能正常调用代理翻墙，本应用不行



> > 如果你设置的是 `localhost:7890` 那就说明你设置错了
> > 你在容器里面网络是隔离的 使用 localhost 访问不到你宿主机上运行的代理
> 
> 我在进行了相关设置后，保证容器能够访问到代理了，使用docker-compose up然后出现了如下报错，并且导致容器无法正常开启（与我初始提出的问题处于两个阶段）
> 
> ```
> chatgpt_1     | requests.exceptions.ProxyError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe04a61cb50>: Failed to establish a new connection: [Errno 111] Connection refused')))
> ```
> 
> 我怀疑是代理错误，我进行了一下操作
> 
> 1. 我将代理关掉了，依旧报错
> 2. 我将代理取消，让他直接进行连接，依旧报错无法连接
> 3. 将所有后续更改的回档到我第一次报错的状态，依旧无法连接
> 4. 直接删除所有文件，重新按照教程进行搭建，依旧无法连接

我们要解决的是程序没有使用上代理的问题。  建议使用以下排查方式：
1.  关掉代理软件，启动程序，预期情况是：程序在登录 OpenAI 阶段提示 `无法连接至代理服务器，xxxx`  这说明你配置了让程序通过代理登录 OpenAI
2.  启动代理软件，启动程序，预期情况是：`requests.exceptions.ProxyError: HTTPSConnectionPool(host='xxxx` 这说明程序正在试图通过你的代理连接 OpenAI，但你的代理在连接过程中发生了错误  
3. 更换节点，然后重新启动程序，直到你的节点可以访问到 OpenAI

另外，建议附上完整的日志，我不知道程序启动到什么阶段了

**Comment by MrSnake0208** [comment]
> > 2. 改了很多次代理，都是其他应用都能正常调用代理翻墙，本应用不行
> 
> > > 如果你设置的是 `localhost:7890` 那就说明你设置错了
> > > 你在容器里面网络是隔离的 使用 localhost 访问不到你宿主机上运行的代理
> > 
> > 
> > 我在进行了相关设置后，保证容器能够访问到代理了，使用docker-compose up然后出现了如下报错，并且导致容器无法正常开启（与我初始提出的问题处于两个阶段）
> > ```
> > chatgpt_1     | requests.exceptions.ProxyError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe04a61cb50>: Failed to establish a new connection: [Errno 111] Connection refused')))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我怀疑是代理错误，我进行了一下操作
> > 
> > 1. 我将代理关掉了，依旧报错
> > 2. 我将代理取消，让他直接进行连接，依旧报错无法连接
> > 3. 将所有后续更改的回档到我第一次报错的状态，依旧无法连接
> > 4. 直接删除所有文件，重新按照教程进行搭建，依旧无法连接
> 
> 我们要解决的是程序没有使用上代理的问题。 建议使用以下排查方式：
> 
> 1. 关掉代理软件，启动程序，预期情况是：程序在登录 OpenAI 阶段提示 `无法连接至代理服务器，xxxx`  这说明你配置了让程序通过代理登录 OpenAI
> 2. 启动代理软件，启动程序，预期情况是：`requests.exceptions.ProxyError: HTTPSConnectionPool(host='xxxx` 这说明程序正在试图通过你的代理连接 OpenAI，但你的代理在连接过程中发生了错误
> 3. 更换节点，然后重新启动程序，直到你的节点可以访问到 OpenAI
> 
> 另外，建议附上完整的日志，我不知道程序启动到什么阶段了

感谢您的回复与推测，按照您的思路，我对代理软件进行了重新配置并配置好了并进行了如下操作，最终Robot能够正常工作：
1. 我选择直接在docker-compose中添加代理
```
      http_proxy: 'http://localhost:7890'
      https_proxy: 'http://localhost:7890'
```
2. **在进行这样配置后能够正常访问openai了，但是出现了新的问题，始终无法与mirai的http与Websocket产生连接，排查后是发现该容器无法访问到mirai这个网络，不知道这个网络，我选择使用**docker inspect mirai-chatgpt_mirai_1**查看mirai容器IP地址并最终获得了其容器内地址为172.xx.x.x，将这个IP地址加入到config.cfg中，最终Robot能够正常运行了，非常感谢！！

**Comment by lss233** [comment]
不用填IP地址，直接填mirai  它会自动解析的。

**Comment by MrSnake0208** [comment]
> 不用填IP地址，直接填mirai  它会自动解析的。

因为填了mirai它一直提示Name unknown，我只能去手动找ip地址了

**Comment by kai04420** [comment]
> 

我也遇到了这个问题，请问如何在docker-compose中添加代理呀，试了好多次都没成功

**Comment by kai04420** [comment]
> > > 2. 改了很多次代理，都是其他应用都能正常调用代理翻墙，本应用不行
> > 
> > 
> > > > 如果你设置的是 `localhost:7890` 那就说明你设置错了
> > > > 你在容器里面网络是隔离的 使用 localhost 访问不到你宿主机上运行的代理
> > > 
> > > 
> > > 我在进行了相关设置后，保证容器能够访问到代理了，使用docker-compose up然后出现了如下报错，并且导致容器无法正常开启（与我初始提出的问题处于两个阶段）
> > > ```
> > > chatgpt_1     | requests.exceptions.ProxyError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe04a61cb50>: Failed to establish a new connection: [Errno 111] Connection refused')))
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我怀疑是代理错误，我进行了一下操作
> > > 
> > > 1. 我将代理关掉了，依旧报错
> > > 2. 我将代理取消，让他直接进行连接，依旧报错无法连接
> > > 3. 将所有后续更改的回档到我第一次报错的状态，依旧无法连接
> > > 4. 直接删除所有文件，重新按照教程进行搭建，依旧无法连接
> > 
> > 
> > 我们要解决的是程序没有使用上代理的问题。 建议使用以下排查方式：
> > 
> > 1. 关掉代理软件，启动程序，预期情况是：程序在登录 OpenAI 阶段提示 `无法连接至代理服务器，xxxx`  这说明你配置了让程序通过代理登录 OpenAI
> > 2. 启动代理软件，启动程序，预期情况是：`requests.exceptions.ProxyError: HTTPSConnectionPool(host='xxxx` 这说明程序正在试图通过你的代理连接 OpenAI，但你的代理在连接过程中发生了错误
> > 3. 更换节点，然后重新启动程序，直到你的节点可以访问到 OpenAI
> > 
> > 另外，建议附上完整的日志，我不知道程序启动到什么阶段了
> 
> 感谢您的回复与推测，按照您的思路，我对代理软件进行了重新配置并配置好了并进行了如下操作，最终Robot能够正常工作：
> 
> 1. 我选择直接在docker-compose中添加代理
> 
> ```
>       http_proxy: 'http://localhost:7890'
>       https_proxy: 'http://localhost:7890'
> ```
> 
> 2. **在进行这样配置后能够正常访问openai了，但是出现了新的问题，始终无法与mirai的http与Websocket产生连接，排查后是发现该容器无法访问到mirai这个网络，不知道这个网络，我选择使用**docker inspect mirai-chatgpt_mirai_1**查看mirai容器IP地址并最终获得了其容器内地址为172.xx.x.x，将这个IP地址加入到config.cfg中，最终Robot能够正常运行了，非常感谢！！

我也遇到了这个问题，请问如何在docker-compose中添加代理呀，试了好多次都没成功

**Comment by MrSnake0208** [comment]
等今天白天我会发一下我的配置，麻烦您等一等😄

**Comment by kai04420** [comment]
> 等今天白天我会发一下我的配置，麻烦您等一等😄

嗯嗯，麻烦您啦

**Comment by MrSnake0208** [comment]
> > 等今天白天我会发一下我的配置，麻烦您等一等😄
> 
> 嗯嗯，麻烦您啦

对不起！！我忘记了！！
```
  chatgpt:
    image: lss233/chatgpt-mirai-qq-bot:browser-version
    restart: always
    environment:
      LANG: 'C.UTF-8'
      XPRA_PASSWORD: 'lss233' # XPRA 密码，建议修改
      http_proxy: 'http://localhost:7890'
      https_proxy: 'http://localhost:7890'
```
像这样添加就行
