### ISSUE TITLE
[BUG] v2.0.2中，所有群内和私聊会话都是同一个会话

### ISSUE THREAD

**Issue by Qianmo2** [lss233/chatgpt-mirai-qq-bot#265]

**Comment by lss233** [comment]
是什么模式?

**Comment by Yandy61** [comment]
> 是什么 AI 有这种情况?

chatgpt-web存在这个情况，且会话重命名失效，在web上显示的是new chat而不是qq-{session_id}

**Comment by Veloctor** [comment]
+1

**Comment by MikeQu223** [comment]
api也是

**Comment by wu1724** [comment]
添加了title_pattern是会修改会话的名称，但是在chatgpt的消息加载完成之后又会变成new chat

**Comment by EvenVestan** [comment]
+1，重置会话后会切换账号但是会话依然全部都在同一个里，无论是私聊还是群

**Comment by LinusLieu** [comment]
+1，目前测试了一下在管理员账号进行加载预设后，会在web里面创建根据规则的会话，但其他人私聊或者群里@的话都会继续在这一会话下回复。

在进一步的测试下，每次发送“加载预设 $$”后都会新开一个Chat，但是之后所有的回复都是在最新创建的chat下进行回复，而并不会根据账号来调用指定的chat。

同时，非管理员同样能进行加载预设的命令，不太清楚管理员具体的作用？

**Comment by lss233** [comment]
下一版本修复
