### ISSUE TITLE
脚本全部闪退

### ISSUE THREAD

**Issue by knbnaz** [lss233/chatgpt-mirai-qq-bot#267]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**运行环境:**  
- 操作系统：Windows sever 2012
- Docker： ？
- 项目版本：2.0.2 
除了初始化正常，其他脚本全部闪退
 
git版本2.9.3
依赖全部正常
python版本3.9

**Comment by lss233** [comment]
试试用Powershell中的cmd来启动脚本吧    

仅凭你提供的信息我无法判断具体是什么清空

**Comment by knbnaz** [comment]
> 试试用Powershell中的cmd来启动脚本吧
> 
> 仅凭你提供的信息我无法判断具体是什么情况

没用，照样闪退

**Comment by knbnaz** [comment]
> 试试用Powershell中的cmd来启动脚本吧
> 
> 仅凭你提供的信息我无法判断具体是什么情况

他是会先打开cmd窗口，然后闪退，接着弹出git bash的会话窗口，然后git bash的窗口闪退

**Comment by knbnaz** [comment]
> 试试用Powershell中的cmd来启动脚本吧
> 
> 仅凭你提供的信息我无法判断具体是什么情况

你可以加我的微信或者QQ，我给你服务器的情况，或者给你地址你连上去看看
