### ISSUE TITLE
ws连接不上是什么问题

### ISSUE THREAD

**Issue by keleiya** [lss233/chatgpt-mirai-qq-bot#27]
![image](https://user-images.githubusercontent.com/98154493/206892462-aa0d6830-d423-4f48-866c-323bc8dd756e.png)
这里一直连不上是什么原因，我看设置是对的

**Comment by keleiya** [comment]
![image](https://user-images.githubusercontent.com/98154493/206891732-7d393e9f-e801-41ed-8591-b0739cd5ffb0.png)

**Comment by keleiya** [comment]
不用了，自己解决了

**Comment by keleiya** [comment]
他就在这一直连接，一直都连不上

**Comment by lss233** [comment]
把 `config.json` 亮出来看看，隐私部分记得打码。

**Comment by keleiya** [comment]
![image](https://user-images.githubusercontent.com/98154493/206895135-62135993-bbc6-4b4e-8126-b7d0e97fa2eb.png)

**Comment by lss233** [comment]
你没有在 mirai 那边登录机器人

**Comment by keleiya** [comment]
我先启动了mirai并且成功登录后依旧是这样的

**Comment by keleiya** [comment]
好了，我解决了，我把自动登录的文件里的MD5改成了PLAIN后解决了
