### ISSUE TITLE
[BUG] v2.1.0中，仅在图片模式且开启了百度云审核的情况下报错：'MessageChain' object has no attribute 'encode'

### ISSUE THREAD

**Issue by Qianmo2** [lss233/chatgpt-mirai-qq-bot#270]
**提交 issue 前，请先确认：**
- [✓] 我已看过 **FAQ**，此问题不在列表中
- [✓] 我已看过其他 issue，他们不能解决我的问题 
- [✓] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
报错：
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话。如果报错仍旧存在，请与号主2657447616联系。
'MessageChain' object has no attribute 'encode'

**运行环境:**  
- 操作系统：Debian 11
- Docker： ？
- 项目版本：v2.2.0

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 启动后，切换为图片模式
2. 发送任意消息
3. 得到报错
![Screenshot_2023_0305_073432](https://user-images.githubusercontent.com/73323948/222933548-810b4c5a-d93d-4921-8907-01765ad5c917.jpg)

**截图**

**Comment by Haibersut** [comment]
已经修复，下一个版本中百度云将不会对打开default状态下的文转图做处理

如果需要对所有文件处理，只开启always即可
```
[text_to_image]
# 文字转图片

# 是否强制开启，设置后所有的消息强制以图片发送，减小风控概率  
always = true

# 是否默认开启，设置后所有的消息默认以图片发送，减小风控概率  
default = true
```

**Comment by lss233** [comment]
v2.2.0 已发布
