### ISSUE TITLE
[Feature] 希望能够给私聊提供独立的响应前缀

### ISSUE THREAD

**Issue by EvolvedGhost** [lss233/chatgpt-mirai-qq-bot#271]
**使用情景：**
我的Mirai上还有其他功能的机器人插件，这些可通过私聊触发，但同时我需要群聊环境下仅@即可触发响应，因此我的设置为
```
[trigger]
prefix = [ "",]
require_mention = "at"
```
但这样设置的话，机器人会响应所有私聊的信息，造成指令冲突浪费ChatGPT的额度：
![6DF({J9HWODT_F$QV027BC9](https://user-images.githubusercontent.com/92856393/222935043-35db68b8-931c-429a-8b86-adf7bdd691ec.png)

**希望功能：**
给私聊提供独立的prefix使其与群聊触发规则分离

**Comment by lss233** [comment]
下一版本支持

**Comment by lss233** [comment]
v2.2.0 已发布,使用方法见 README
