### ISSUE TITLE
[BUG] markdown的数学公式无法渲染

### ISSUE THREAD

**Issue by Leo01234** [lss233/chatgpt-mirai-qq-bot#275]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
使用图片模式时，回答中有需要渲染的数学公式会报错，并生成一张公式未渲染的图片。

**运行环境:**  
- 操作系统：ubuntu22.04
- Docker： Docker version 23.0.1, Docker Compose version v2.16.0
- 项目版本：v2.1.0

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 私聊发送“请用markdown写一个数学公式”
2. 返回的图片中数学公式未渲染，日志报错

**预期行为**  
正常渲染数学公式

**截图**  
![QQ图片20230305210038](https://user-images.githubusercontent.com/40910694/222961917-a112f2fb-d8d6-4835-98a7-cbc8a25c942a.png)

![屏幕截图 2023-03-05 210452](https://user-images.githubusercontent.com/40910694/222962312-ed3d3a4b-9d9f-4880-8666-a3090559a1d4.png)
![屏幕截图 2023-03-05 210611](https://user-images.githubusercontent.com/40910694/222962319-c49de56a-f8b0-4d9e-8aa4-8eb42855c937.png)
![屏幕截图 2023-03-05 210652](https://user-images.githubusercontent.com/40910694/222962324-5d7f7166-b4cc-42d7-b61d-eb2c3e7405fe.png)
![屏幕截图 2023-03-05 210731](https://user-images.githubusercontent.com/40910694/222962328-ece7615f-6593-4f4e-a3f0-1e65e93448e5.png)

**其他内容**  
图片模式下，程序代码的渲染效果是正常的
以及在图片模式，没有数学公式的情况下，依然会有最后的那一段invalid state的报错

**Comment by lss233** [comment]
可以试试 v2.2.0 版还会不会有这个问题

**Comment by Leo01234** [comment]
> 可以试试 v2.2.0 版还会不会有这个问题

更新之后运行出错 Exception: Proxy must be a string!
我没有使用代理连接OpenAI服务器，配置文件里没有写proxy那一行。
尝试将配置文件里添加proxy=""，依然出错 Exception: 登录失败! 无法连接至本地代理服务器，请检查配置文件中的 proxy 是否正确！

**Comment by lss233** [comment]
这是 #278   的问题

**Comment by Leo01234** [comment]
> 可以试试 v2.2.0 版还会不会有这个问题

除了有时会有invalid state的错误之外，已经没有问题了，markdown渲染也正常。
