### ISSUE TITLE
无法成功登陆openai账号

### ISSUE THREAD

**Issue by RyuraeleN** [lss233/chatgpt-mirai-qq-bot#278]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：Ubuntu 20.04 LTS Server - 64 Bit
- Docker：20.10.12
- 项目版本：2.1.0

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 在服务器中输入指令docker-compose pull && docker-compose up -d更新
2.使用docker-compose logs -f查看日志
3.发现账号登陆（无浏览器）方法无法成功登陆

**截图**  
此处为登陆情况（账号一使用账号密码且无浏览器登陆）服务器在洛杉矶，所以未启用代理。

![531VP%% ODFIBT4V{DQW__5](https://user-images.githubusercontent.com/127030570/222963570-95340dfe-d162-4cf5-98b9-c58892afa3ec.png)
![MBX7GE5W6{D1TAD CGM~2KS](https://user-images.githubusercontent.com/127030570/222963586-36e34233-c7bb-4b8a-972d-0990f03ac22e.png)

**Comment by lss233** [comment]
proxy 写错了

**Comment by RyuraeleN** [comment]
我没写proxy诶

**Comment by lss233** [comment]
请提供配置文件

**Comment by RyuraeleN** [comment]
在qq上提供了空投快传链接

**Comment by lss233** [comment]
已确认是 BUG   稍等 一会儿后重新拉取容器试试
