### ISSUE TITLE
[BUG] v2.2.0中群聊聊天前缀配置无效

### ISSUE THREAD

**Issue by Qianmo2** [lss233/chatgpt-mirai-qq-bot#279]
本人配置：
![Uploading IMG_20230305_224856.jpg…]()

**Comment by Qianmo2** [comment]
![IMG_20230305_224856](https://user-images.githubusercontent.com/73323948/222967870-e63c77ad-551e-4f9d-aeb8-980c85593b9d.jpg)

**Comment by tHaxWLa** [comment]
挖一下，请问是怎么解决的呢
