### ISSUE TITLE
一直显示java.net.SocketTimeoutException: Connect timed out

### ISSUE THREAD

**Issue by Dsehen** [lss233/chatgpt-mirai-qq-bot#282]
新手跟着视频一路走，在滑动验证时出现上诉文字，开始步骤应该是没错的，反复确认过。貌似进到miral项目里面，显示旧的miral用不了了，新的不会使用，求教

**Comment by lss233** [comment]
mirai 的问题和我这里是无关的。  不过我可以给你指一条路：
https://github.com/lss233/chatgpt-mirai-qq-bot/issues/222#issuecomment-1451243631
