### ISSUE TITLE
[BUG] 请填写标题

### ISSUE THREAD

**Issue by sylva2012** [lss233/chatgpt-mirai-qq-bot#283]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
登陆openai失败

**运行环境:**  
- 操作系统：centos7.6
- Docker： ？
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的

**docker log**  
`<!DOCTYPE html>
chatgpt-qq-chatgpt-1  | <html lang="en-US">
chatgpt-qq-chatgpt-1  |    <head>
chatgpt-qq-chatgpt-1  |       <title>Access denied</title>
chatgpt-qq-chatgpt-1  |       <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
chatgpt-qq-chatgpt-1  |       <meta name="robots" content="noindex, nofollow" />
chatgpt-qq-chatgpt-1  |       <meta name="viewport" content="width=device-width,initial-scale=1" />
chatgpt-qq-chatgpt-1  |       <link rel="stylesheet" href="/cdn-cgi/styles/errors.css" media="screen" />
chatgpt-qq-chatgpt-1  |       <script>
chatgpt-qq-chatgpt-1  | (function(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById("error-feedback-survey"),d=document.getElementById("error-feedback-success"),b=new XMLHttpRequest;a={event:"feedback clicked",properties:{errorCode:1020,helpful:a,version:5}};b.open("POST","https://sparrow.cloudflare.com/api/v1/event");b.setRequestHeader("Content-Type","application/json");b.setRequestHeader("Sparrow-Source-Key","c771f0e4b54944bebf4261d44bd79a1e");
chatgpt-qq-chatgpt-1  | b.send(JSON.stringify(a));c.classList.add("feedback-hidden");d.classList.remove("feedback-hidden")};document.addEventListener("DOMContentLoaded",function(){var a=document.getElementById("error-feedback"),c=document.getElementById("feedback-button-yes"),d=document.getElementById("feedback-button-no");"classList"in a&&(a.classList.remove("feedback-hidden"),c.addEventListener("click",function(){e(!0)}),d.addEventListener("click",function(){e(!1)}))})}})();
chatgpt-qq-chatgpt-1  | </script>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |       <script>
chatgpt-qq-chatgpt-1  |       (function(){function d(c){var b=document.getElementById("copy-label"),a=document.getElementById("cf-details-wrapper-expandable");c.target.checked?a.classList.add("expanded"):(a.classList.remove("expanded"),b.innerText="Click to copy")}if(document.addEventListener){var e=function(){var c=document.getElementById("copy-label");var b=document.getElementById("error-details").textContent;if(navigator.clipboard)navigator.clipboard.writeText(b);else{var a=document.createElement("textarea");a.value=b;a.style.top="0";a.style.left="0";a.style.position="fixed";document.body.appendChild(a);a.focus();a.select();document.execCommand("copy");document.body.removeChild(a)}c.innerText="Copied text to clipboard"};document.addEventListener("DOMContentLoaded",function(){var c=document.getElementById("error-details-checkbox"),b=document.getElementById("click-to-copy-btn");document.getElementById("copy-label").classList.remove("hidden");c.addEventListener("change",d);b.addEventListener("click",e)})}})();
chatgpt-qq-chatgpt-1  |       </script>
chatgpt-qq-chatgpt-1  |       <script defer src="https://performance.radar.cloudflare.com/beacon.js"></script>
chatgpt-qq-chatgpt-1  |    </head>
chatgpt-qq-chatgpt-1  |    <body>
chatgpt-qq-chatgpt-1  |    <div class="cf-main-wrapper" role="main">
chatgpt-qq-chatgpt-1  |       <div class="cf-header cf-section">
chatgpt-qq-chatgpt-1  |          <div class="cf-error-title">
chatgpt-qq-chatgpt-1  |             <h1>Access denied</h1>
chatgpt-qq-chatgpt-1  |             <span class="cf-code-label">Error code <span>1020</span></span>
chatgpt-qq-chatgpt-1  |          </div>
chatgpt-qq-chatgpt-1  |          <div class="cf-error-description">
chatgpt-qq-chatgpt-1  |             <p>You do not have access to chatgpt.duti.tech.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>
chatgpt-qq-chatgpt-1  |          </div>
chatgpt-qq-chatgpt-1  |       </div>
chatgpt-qq-chatgpt-1  |    </div>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |    <div class="cf-details-wrapper">
chatgpt-qq-chatgpt-1  |       <div class="cf-section" role="region">
chatgpt-qq-chatgpt-1  |          <div class="cf-expandable" id="cf-details-wrapper-expandable">
chatgpt-qq-chatgpt-1  |             <label for="error-details-checkbox" title="Error details" class="cf-expandable-btn">
chatgpt-qq-chatgpt-1  |                <p class="cf-dropdown-title">Error details</p>
chatgpt-qq-chatgpt-1  |                <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAElBMVEUAAAAwMDAxMTEyMjIwMDAxMTF+89HTAAAABXRSTlMAf2CAMKS61bwAAABTSURBVCjPzcq7DcAgFENR5zMATfo06TNCViAS+6+CeFi6gglw4eLqaPVtaQpXnkApaQT/k0dw70EAUhCA1AnABGACMAGYAEwAkCOAydv+I5xaZhXWbQrD80TkkQAAAABJRU5ErkJggg=="
chatgpt-qq-chatgpt-1  |                class="cf-caret-icon" id="caret-icon" alt="Caret icon" />
chatgpt-qq-chatgpt-1  |             </label>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |             <input id="error-details-checkbox" class="hidden" type="checkbox">
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |             <div class="cf-expandable-error-info hidden">
chatgpt-qq-chatgpt-1  |                <p class="cf-error-copy-description">Provide the site owner this information.</p>
chatgpt-qq-chatgpt-1  |                <button class="cf-click-to-copy-btn" id="click-to-copy-btn" title="Click to copy" type="button">
chatgpt-qq-chatgpt-1  | <div class="cf-error-wrapper" id="error-details"><p class="cf-error-details-endpoint">I got an error when visiting chatgpt.duti.tech/api/conversations?offset=0&amp;limit=1.</p>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  | <p>Error code: 1020</p>
chatgpt-qq-chatgpt-1  | <p>Ray ID: 7a379c033b0480db</p>
chatgpt-qq-chatgpt-1  | <p>Country: JP</p>
chatgpt-qq-chatgpt-1  | <p>Data center: nrt08</p>
chatgpt-qq-chatgpt-1  | <p>IP: 43.163.232.51</p>
chatgpt-qq-chatgpt-1  | <p>Timestamp: 2023-03-06 03:46:03 UTC</p>
chatgpt-qq-chatgpt-1  | </div>
chatgpt-qq-chatgpt-1  |                   <p class="cf-copy-label hidden" id="copy-label">Click to copy</p>
chatgpt-qq-chatgpt-1  |                </button>
chatgpt-qq-chatgpt-1  |             </div>
chatgpt-qq-chatgpt-1  |          </div>
chatgpt-qq-chatgpt-1  |       </div>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |       <div class="clearfix cf-footer cf-section" role="contentinfo">
chatgpt-qq-chatgpt-1  |       <div class="cf-column">
chatgpt-qq-chatgpt-1  |            <div class="feedback-hidden py-8 text-center" id="error-feedback">
chatgpt-qq-chatgpt-1  |     <div id="error-feedback-survey" class="footer-line-wrapper">
chatgpt-qq-chatgpt-1  |         Was this page helpful?
chatgpt-qq-chatgpt-1  |         <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-yes" type="button">Yes</button>
chatgpt-qq-chatgpt-1  |         <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-no" type="button">No</button>
chatgpt-qq-chatgpt-1  |     </div>
chatgpt-qq-chatgpt-1  |     <div class="feedback-success feedback-hidden" id="error-feedback-success">
chatgpt-qq-chatgpt-1  |         Thank you for your feedback!
chatgpt-qq-chatgpt-1  |     </div>
chatgpt-qq-chatgpt-1  | </div>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  |       </div>
chatgpt-qq-chatgpt-1  |          <div class="cf-column cf-footer-line-wrapper text-center">
chatgpt-qq-chatgpt-1  |             <p>
chatgpt-qq-chatgpt-1  |                Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=1020_error" target="_blank">Cloudflare <img class="external-link" title="Opens in new tab" src="/cdn-cgi/images/external.png" alt="External link"></a>
chatgpt-qq-chatgpt-1  |             </p>
chatgpt-qq-chatgpt-1  |          </div>
chatgpt-qq-chatgpt-1  |       </div>
chatgpt-qq-chatgpt-1  |    </div>
chatgpt-qq-chatgpt-1  | <script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"7a379c033b0480db","version":"2023.2.0","r":1,"token":"b03bb9f1bc4449dc8acd4ae196519534","si":100}' crossorigin="anonymous"></script>
chatgpt-qq-chatgpt-1  | </body>
chatgpt-qq-chatgpt-1  | </html>
chatgpt-qq-chatgpt-1  | 
chatgpt-qq-chatgpt-1  | /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
chatgpt-qq-chatgpt-1  |   return _Gtk_main(*args, **kwargs)
chatgpt-qq-chatgpt-1  | 2023-03-06 03:46:03,530 child 'xterm -e 'python bot.py 2>&1 | tee /tmp/log.txt'' with pid 38 has terminated
chatgpt-qq-chatgpt-1  | 2023-03-06 03:46:03,530 all children have exited and --exit-with-children was specified, exiting
chatgpt-qq-chatgpt-1  | 2023-03-06 03:46:03,530 xpra X11 seamless server is terminating
chatgpt-qq-chatgpt-1  | 2023-03-06 03:46:03,548 closing tcp socket '0.0.0.0:14500'
chatgpt-qq-chatgpt-1  | 2023-03-06 03:46:03,548 removing unix domain socket '/run/user/1000/xpra/460e5c73a451-0'
chatgpt-qq-chatgpt-1  | 2023-03-06 03:46:03,548 removing unix domain socket '/tmp/0/socket'
chatgpt-qq-chatgpt-1  | 2023-03-06 03:46:03,549 killing xvfb with pid 12
`

**Comment by sylva2012** [comment]
是否意味主机IP被限制访问了

**Comment by lss233** [comment]
是
