### ISSUE TITLE
[BUG] 机器人无法处理多条信息

### ISSUE THREAD

**Issue by EvolvedGhost** [lss233/chatgpt-mirai-qq-bot#287]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
当提交多条信息时，机器人表现为一条一条处理，控制台信息卡死，疑似处理信息时线程被阻塞（？）
2.0版本之前好像是正常的

**运行环境:**  
- 操作系统：Windows Server 2019 （1809）
- Docker： 无
- 项目版本：2.2.0

**复现步骤**  
描述你是如何触发这个 BUG 的
我的配置项主要修改部分为：
```
[response]
timeout = 15.0
max_queue_size = 5
queued_notice_size = 0
```
同时询问机器人多个问题即可触发

**预期行为**  
机器人正常处理每个信息
```
用户：问题1
用户：问题2
机器人：消息已收到！当前我还有1条消息要回复，请您稍等。
用户：问题3
机器人：消息已收到！当前我还有2条消息要回复，请您稍等。
机器人：回答1
机器人：回答2
机器人：回答3
```
并且控制台正常滚动

**实际行为**
```
用户：问题1
用户：问题2
用户：问题3
机器人：回答1
机器人：回答2
机器人：回答3
```
机器人在回答1之前，控制台卡在
```
时间 | INFO     | graia.ariadne.model:log:82 - 群号: [RECV][用户] -> 问题1
时间 | DEBUG    | middlewares.timeout:create_timeout_task:14 - [Timeout] 开始计时……
```
并不会显示任何问题2、3的Log，直到发出回答1

**Comment by lss233** [comment]
已知问题，正在测试最新的代码能不能解决此问题

**Comment by magisk317** [comment]
dup https://github.com/lss233/chatgpt-mirai-qq-bot/issues/280
