### ISSUE TITLE
[BUG] requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

### ISSUE THREAD

**Issue by DrgZong** [lss233/chatgpt-mirai-qq-bot#288]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
使用cookiePath运行到此处时会报错
![image](https://user-images.githubusercontent.com/19589495/223094183-6e34ff98-45bd-4476-a7e0-dab64cb3305b.png)

**运行环境:**  
- 操作系统：MacOS（Apple M1 Pro）
- Docker： 无
- 项目版本：0.0.55

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 启动时报错

**预期行为**  
正常启动

**截图**  
![image](https://user-images.githubusercontent.com/19589495/223094514-47d9eb13-fb1d-439c-8109-a3a164ea6043.png)

**Comment by FENG-MASTER** [comment]
我也遇到了，这个是什么问题，怎么解决的
