### ISSUE TITLE
关于持续性的"Not a JSON response"错误

### ISSUE THREAD

**Issue by HK560** [lss233/chatgpt-mirai-qq-bot#29]
昨天上午部署之后没什么问题功能也正常，但从昨晚晚上突然就开始这个Not a JSON response报错，重置会话没有作用，到现在一直是这个错误。
已经排查chatgpt账号网络等问题，也尝试过更新重写部署，但未能解决。
能提供更多的错误信息报告或者相关排查错误措施吗？

**Comment by lss233** [comment]
你可以先试试在[这里](https://github.com/lss233/chatgpt-mirai-qq-bot/blob/ebe2e0f8a49e5c6d37bc3ed3e2e5b60647d87caa/chatbot.py#LL7C59-L7C59)加一个 `debug=True` 参数  
看看有没有什么奇怪的输出。

**Comment by lss233** [comment]
最新的提交已经会将 traceback 输出在终端。

**Comment by henuyuanxiao** [comment]
session_token换一下就好了吧，这个有时限性

**Comment by HK560** [comment]
@henuyuanxiao @lss233 已解决，确实是token过期了，因为我用的是accessToken，所以当初没考虑过期的问题，重新获取accessToken解决了。
