### ISSUE TITLE
[Feature] 提高bingGPT回复上限至8条

### ISSUE THREAD

**Issue by FuryMartin** [lss233/chatgpt-mirai-qq-bot#290]
[Microsoft Loosens Bing ChatGPT Limit to 8 Turns Per Conversation, Alongside New Turn Counter Feature](https://www.gizmochina.com/2023/03/05/bing-chatgpt-limit-to-8-per-conversation-new-turn-counter/)
微软已将bingGPT的回复上限提高至8条，希望能够调整bot的上限

![](https://www.gizmochina.com/wp-content/uploads/2023/03/Bing-Joke.png)

**Comment by magisk317** [comment]
已经是8了吧，具体忘了哪个版本了，2.2肯定是


![Screenshot_2023-03-07-00-27-02-585_com tencent mobileqq](https://user-images.githubusercontent.com/93979778/223171327-cbd0f709-b4a7-465f-bf17-b46abb56ba98.jpg)

**Comment by lss233** [comment]
好的，改回去了。
