### ISSUE TITLE
[BUG] ask bing 模式无法用文字回复

### ISSUE THREAD

**Issue by Southpl** [lss233/chatgpt-mirai-qq-bot#291]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
在默认图片模式打开，强制图片模式关闭的情况下，先命令机器人“文本模式”，机器人在默认的chatgpt-web模式可以用文字回复，但在ask bing时仍然以图片形式回复。
![image](https://user-images.githubusercontent.com/124554376/223129839-69688efc-60ac-4c70-9b62-c258afe30d7b.png)

**Comment by lss233** [comment]
![image](https://user-images.githubusercontent.com/8984680/223167093-302133a0-8030-4a78-9e43-eb1c90f0f7cf.png)

这就是说明你这条消息以文本模式发送被吞了呗，所以又切回图片了。  

这个功能本身是没问题的。

**Comment by Southpl** [comment]
但是我关闭了default图片模式后，所有的回复都是文字形式的，我觉得并不是因为文本被吞的原因，当时我测试了许多问题，返回的内容也是很正常的内容，但均以图片返回，

**Comment by Southpl** [comment]
但是我关闭了default图片模式后，所有的回复都是文字形式的，我觉得并不是因为文本被吞的原因，当时我测试了许多问题，返回的内容也是很正常的内容，但均以图片返回，

**Comment by Southpl** [comment]
> 

但是我关闭了default图片模式后，所有的回复都是文字形式的，我觉得并不是因为文本被吞的原因，当时我测试了许多问题，返回的内容也是很正常的内容，但均以图片返回，
