### ISSUE TITLE
[BUG] 2.0以后版本的prefix配置项似乎并不生效

### ISSUE THREAD

**Issue by HeyuChick** [lss233/chatgpt-mirai-qq-bot#295]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
2.0以后版本的prefix配置项似乎并不生效

**运行环境:**  
- 操作系统：CentOS8
- Docker： 手动部署
- 项目版本：2.2.1

**复现步骤**  
已经根据提示修改了配置，但bot运行后依然对所有消息都响应
![image](https://user-images.githubusercontent.com/41606290/223298883-3a55cce1-8dc3-4752-9e84-b563ce8189c7.png)

![F084F481027EBE2F6C99484950FEEA3E](https://user-images.githubusercontent.com/41606290/223299325-fe976576-714d-4bb1-b3ad-eb06f9bea6fb.png)

**预期行为**  
bot在群聊和私聊中，收到符合配置文件中设置前缀的消息才会响应

**Comment by budongsir** [comment]
遇到同样问题

**Comment by lss233** [comment]
你加个 prefix_friend=[] 试试

**Comment by HeyuChick** [comment]
> 你加个 prefix_friend=[] 试试

解决了，感谢！
我看注释那里写的选项可选还以为可以直接不用这个prefix_friend

**Comment by lss233** [comment]
那就是我默认配置的问题，下一版本修复
