### ISSUE TITLE
docker-compose run --rm mirai报错

### ISSUE THREAD

**Issue by thechen130** [lss233/chatgpt-mirai-qq-bot#298]
![image](https://user-images.githubusercontent.com/74664452/223392992-c1892b58-002e-46d9-a45b-6afa5c6463df.png)
![image](https://user-images.githubusercontent.com/74664452/223393130-8d5f6870-30bc-4e38-8e69-6f938e8ade07.png)

**Comment by lss233** [comment]
已修复，请重新 pull 容器。
