### ISSUE TITLE
异世相遇 | 关于近期 Mirai 或 OpenAI 登录失败的解决方法

### ISSUE THREAD

**Issue by lss233** [lss233/chatgpt-mirai-qq-bot#303]
## 1. Mirai 登录失败  
由于腾讯正在调整登录协议， Mirai 登录目前处于不稳定的状态。  

请关注 [Mirai 官方论坛](https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88)来了解最新的解决方法。  

### 【3月11日】 的缓解措施

因为 go-cqhttp 对新协议的支持良好，所以我们支持了 go-cqhttp 协议。具体操作可以看 https://github.com/lss233/chatgpt-mirai-qq-bot/issues/311#issuecomment-1464953081

### 【3月9日】 的缓解措施

考虑到有部分同学非常想再次和 ChatGPT 见面，所以我接了一个 Telegram Bot 的协议。  
使用方法见：https://github.com/lss233/chatgpt-mirai-qq-bot/issues/303#issuecomment-1462449540
### 【3月8日】 的缓解措施

根据 Mirai 官方论坛帖子的消息，目前可以使用 fix-protocol-version 插件 + ANDROID_PAD 协议来登录机器人。  

#### 插件安装 

你可以在 [这里](https://github.com/cssxsh/fix-protocol-version/releases/download/v1.0.0/fix-protocol-version-1.0.0.mirai2.jar) 下载插件，将它放到 mirai 的 plugins 文件夹，然后重新启动 mirai。  

#### 协议修改

在登录  mirai 时，使用 `login QQ号 QQ密码 协议` 即可指定协议登录。  
举个例子，如果你机器人的 QQ 是 123456789， 密码是 password，使用 ANDROID_PAD 协议登录，那么你可以输入：
```
login 12346789 password ANDROID_PAD
```
然后回车。  
成功之后，你需要修改当前自动登录时的协议，那么你可以用这个命令：
```
autologin setConfig 1234556789 protocol ANDROID_PAD
``` 

> 目前发现配合 fix-protocol-version 和 MACOS 协议也可以成功登录。  

#### 我的回应  

最新的 Docker 镜像和一键脚本已经使用了 【3月8日】 的缓解措施，此前安装的同学可以尝试重新部署，或根据我上面说的方法自己调整。  

Windows端在【3月8日】之后发布的快速部署包也将具备此缓解措施（目前还未发布）。

如果你的问题和上文不同，也可以尝试这些方法： #107 和 #177。
## 2. TxCaptchaHelper 出现 SocketTimeout 异常

由于某些原因，此服务在部分地区无法使用。  

你可以使用 https://github.com/takayama-lily/node-onebot/issues/28 提到的方法手动获取 ticket 完成验证码。

## 3.  OpenAI 登录失败  

此问题主要影响使用 ChatGPT-web 的机器人，主要表现为登录时提示 Access denied。

此问题的原因和解决方法请见 #294 。

使用 gpt3.5-turbo 的 API 版 ChatGPT 和 New Bing 不受此影响，可以正常使用。  

你可以暂时性的将配置文件中有关 OpenAI 网页版账号登录信息移除，仅保留 OpenAI `api_key` 的登录方法，即可使用 gpt3.5-turbo 的 API 版 ChatGPT。
```toml
[openai]
[openai.accounts]
# OpenAI 的 api key
api_key = "sk-xxxxxx"
# 如果你在国内，需要设置代理
proxy = "http://127.0.0.1:1080"
```

**Comment by jixiuy** [comment]
目前发现配合 fix-protocol-version 和 MACOS 协议也可以成功登录。这个在哪里改

**Comment by jixiuy** [comment]
目前发现配合 fix-protocol-version 和 MACOS 协议也可以成功登录。这个在哪里改

**Comment by lss233** [comment]
> 目前发现配合 fix-protocol-version 和 MACOS 协议也可以成功登录。这个在哪里改

已更新文档

**Comment by King-Of-Knights** [comment]
@lss233 作者大大好啊，今天上午重启了以后发现Mirai和ChatGPT access_token都登不上去了，已经用了最新脚本重装，Mirai这边：

```
2023-03-08 06:28:39 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(0000000), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(000000), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
网络我确定没有问题，是不是新设备不让登？

ChatGPT这边，access_token一直是显示代理问题，浏览器模式好像没有问题

**Comment by knbnaz** [comment]
没用啊，照样登录不上

**Comment by FFff731767** [comment]
昨天出现237，238，45 ，没配合 fix-protocol-version，用macos能登上去了，但是今天又掉了

**Comment by IZege** [comment]
用ANDROID_PAD登不上，错误码45，看前面兄弟的，用MACOS登上去了

**Comment by xinge3787** [comment]
windows端，使用PAD和PHONE都登录不上，提示45

**Comment by CJwens** [comment]
感谢大佬  用MACOS协议可以

**Comment by knbnaz** [comment]
linuxQQ协议还没掉，作者可以加加看

**Comment by yasurido** [comment]
用MACOS登不上，显示code=235是什么意思啊

**Comment by lss233** [comment]
## 【异世相遇】

由于我自己现在也登不了 mirai 和 go-cqhttp，所以为了测试我就接了一个 telegram bot 的协议放在 `browser-version-dev` 分支，现在介绍一下怎么用。  

### 1. 获取程序  
**提醒： `browser-version-dev`  分支是专门用来测试未发布版本的开发分支，因此你极有可能下载到富含 BUG 且无文档介绍的代码，在使用前请确保自己具备自己解决这些问题的能力，我不会提供过多的支持。**  

如果你使用 docker 或 docker-compose 部署，只需要将原来镜像的 tag 由 `browser-version` 修改为 `browser-version-dev` 然后重新拉取镜像并更新容器即可。  

如果你使用 Windows， 可以在这个 [![Create Quickstart for Windows 64 on dev](https://github.com/lss233/chatgpt-mirai-qq-bot/actions/workflows/quickstart-windows-dev.yaml/badge.svg)](https://github.com/lss233/chatgpt-mirai-qq-bot/actions/workflows/quickstart-windows-dev.yaml) （图片可点击）中下载到对应的 Windows 快速部署包。

![image](https://user-images.githubusercontent.com/8984680/224103870-e474a9d5-fd47-4f95-a6d8-00b1ea169490.png)


### 2. 配置

打开 config.cfg，在文件的最开始加入以下配置：
```properties
[telegram]
# 这个 token 是找 BotFather 要的
bot_token = "你的 Bot token"
# 如果部署在国内，就填这个设置代理
# 不填的话就会读取系统的代理设置
proxy = "http://localhost:1080"
```

### 3. 启动
还是和之前一样启动。如果准确无误的话，在启动时你会看到这么一行提示：
  
![image](https://user-images.githubusercontent.com/8984680/224104686-b6d55411-d975-4e34-ba96-514ba6e30df7.png)

![image](https://user-images.githubusercontent.com/8984680/224105237-54c83332-e2eb-4972-88be-2b23f00fb6c1.png)

然后找你的 bot 聊天就可以了！

**Comment by King-Of-Knights** [comment]
目前，昨天晚上MACOS登录的被踢下线了，各种协议都235了

**Comment by luckywangxi** [comment]
如何同时支持mirai和TG呢

**Comment by lss233** [comment]
> 如何同时支持mirai和TG呢

暂不支持，你可以开两个实例

**Comment by Cacarot** [comment]
已经显示：2023-03-11 19:29:30.043 | INFO     | telegram_bot:<module>:41 - 启动完毕，接收消息中……

**Comment by lss233** [comment]
> 已经显示：2023-03-11 19:29:30.043 | INFO | telegram_bot::41 - 启动完毕，接收消息中……
> 
> 然后直接给bot发消息就可以了是吧？为啥我发了消息啥反应也没有呢？哪里姿势不对？

信息过少，不知道啥情况。

**Comment by lss233** [comment]
现在我们也支持了 go-cqhttp 使用的  OneBot 协议，能用 go-cqhttp 登录的同学可以试试看。

**Comment by King-Of-Knights** [comment]
> 现在我们也支持了 go-cqhttp 使用的 OneBot 协议，能用 go-cqhttp 登录的同学可以试试看。

爱死你了！！！作者大大

**Comment by King-Of-Knights** [comment]
@lss233 作者大大，docker镜像是还没更新吗？我pull以后，config.py还是没有读取反向代理的选项

**Comment by lss233** [comment]
> @lss233 作者大大，docker镜像是还没更新吗？我pull以后，config.py还是没有读取反向代理的选项

**放在 browser-version-dev 分支**

**Comment by King-Of-Knights** [comment]
@lss233 大大好啊，我基本都成功了，现在还有最后一步了，我目前用的是API，但是好像现在`api.openai.com`连不上了，我确定不是我梯子的问题，测试：

```
wget https://api.openai.com
--2023-03-12 01:44:07--  https://api.openai.com/
Connecting to 127.0.0.1:10809... connected.
Proxy request sent, awaiting response... 404 NOT FOUND
2023-03-12 01:44:08 ERROR 404: NOT FOUND.
```

**Comment by King-Of-Knights** [comment]
> > @lss233 作者大大，docker镜像是还没更新吗？我pull以后，config.py还是没有读取反向代理的选项
> 
> **放在 browser-version-dev 分支**
大大好啊，我其他都成功了，但是现在和“api.openai.com”连不上，好像是新版的没有被代理上吧

**Comment by King-Of-Knights** [comment]
@lss233 大大好，browser-version-dev access_token 一直显示连不上OpenAI, 我同样的配置用browser-version是可以的，API版的也是，总是有超时的问题

**Comment by lss233** [comment]
目前 Mirai 通过 fix-protocol-version 1.2.0 版本和 MACOS 协议可以正常登录 QQ。 若仍然失败，可以使用开发分支的 go-cqhttp。  
支持 go-cqhttp 的 v2.2.3 版本已发布， 此问题视为解决。

**Comment by tHaxWLa** [comment]
@lss233 作者你好,我在启动bot的时候出现了这个问题,看上去像是网络不通?
```
$ python3 bot.py

blobfile: error message=request failed with exception (<urllib3.connection.HTTPSConnection object at 0x7f8807bb20>, 'Connection to openaipublic.blob.core.windows.net timed out. (connect timeout=10)'), request=<Request method=HEAD url=https://openaipublic.blob.core.windows.net/gpt-2/encodings%2Fmain%2Fvocab.bpe params={}>, status=0, error=None, error_description=None, error_headers=None when executing http request <Request method=HEAD url=https://openaipublic.blob.core.windows.net/gpt-2/encodings%2Fmain%2Fvocab.bpe params={}> attempt 0, sleeping for 0.0 seconds before retrying
```

**Comment by hxt1234** [comment]
使用的onebot也是显示[2023-04-04 21:07:48] [WARNING]: 登录失败: 当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。 Code: 237 这个该怎么办呢

**Comment by lss233** [comment]
> 使用的onebot也是显示[2023-04-04 21:07:48] [WARNING]: 登录失败: 当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。 Code: 237 这个该怎么办呢

建议到对应的社区寻找帮助。

**Comment by qq875871130** [comment]
问一下gocqhttp可以设置自动登录吗，我在服务器部署的。。难道只能每次使用都要挂着终端扫码吗? (0_0)

**Comment by lss233** [comment]
> 问一下gocqhttp可以设置自动登录吗，我在服务器部署的。。难道只能每次使用都要挂着终端扫码吗? (0_0)

登录成功之后下次不是可以直接登录吗？

**Comment by qq875871130** [comment]
> > 问一下gocqhttp可以设置自动登录吗，我在服务器部署的。。难道只能每次使用都要挂着终端扫码吗? (0_0)
> 
> 登录成功之后下次不是可以直接登录吗？

大大还没睡的吗。。这么说我在service注册一下指令就可以开机后台启动了呗，不戳
