### ISSUE TITLE
bing版QQ机器人在哪里用

### ISSUE THREAD

**Issue by knbnaz** [lss233/chatgpt-mirai-qq-bot#308]
配置文件里没有

**Comment by Ctrini** [comment]
在github上仔细找找

**Comment by magisk317** [comment]
> 配置文件里没有

你但凡Ctrl-F一下，也不会睁着眼说“**配置文件里没有**”的话，你这已经不是单纯的伸手党了

![image](https://user-images.githubusercontent.com/93979778/223981058-d6f33138-f777-4305-a4f4-739bd3db246e.png)
