### ISSUE TITLE
[Feature] 求一个gocqhttp的版本，或者可以扫码的

### ISSUE THREAD

**Issue by Laurc2004** [lss233/chatgpt-mirai-qq-bot#311]
修复插件 [fix-protocol-version](https://github.com/cssxsh/fix-protocol-version)也用了，登录协议什么的都试了，不起作用，我哭死。gocqhttp可用。

**Comment by lss233** [comment]
Working on it

**Comment by lss233** [comment]
https://github.com/lss233/chatgpt-mirai-qq-bot/issues/303#issuecomment-1464938791
待测试完毕，即发布正式版

**Comment by lss233** [comment]
以下是简易的 go-cqhttp 使用方法：
# 1. 下载最新 dev 分支的 go-cqhttp  和本程序的最新开发分支
go-cqhttp 可以在这里找到：  
https://github.com/Mrs4s/go-cqhttp/actions/  

本程序可以在 #303 找到  

# 2. 解压并启动 go-cqhttp，选 3 然后回车，退出程序
![E$ER7F G39G1MY%4E2YO4LY](https://user-images.githubusercontent.com/8984680/224497145-c5457a73-6a98-4ad7-aba3-cabd52ba9044.jpg)

# 3. 编辑 go-cqhttp 的 config.yaml，设置 （机器人） QQ 号 和反向 Universal 地址  （这个反向 Universal 地址和后面的有关）  
![image](https://user-images.githubusercontent.com/8984680/224497246-080561e4-4819-4889-8de4-7fcb41c71d7a.png)
![image](https://user-images.githubusercontent.com/8984680/224497325-3e3326a8-b214-4031-a97f-2ab694890406.png)

# 4. 修改 docker-compose.yaml，暴露端口  
![CBD{30%G3SW(UAP`WA1SD X](https://user-images.githubusercontent.com/8984680/224497505-5728fd86-cefc-4a3d-b58d-c5133ef56da7.jpg)

# 5. 修改 config.cfg，加入 onebot 的配置  
![image](https://user-images.githubusercontent.com/8984680/224497665-39578b91-f917-40a7-8a6b-80f84690e7cc.png)

# 6. 执行 docker-compose up -d 更新容器  （也就是 Windows 上的 重启程序）

![I`4 L944LV% W1TW1F$0MKC](https://user-images.githubusercontent.com/8984680/224497791-abd08516-0fc9-4e4b-a180-27fa82a198a0.jpg)

# 7. 启动一次 go-cqhttp，生成虚拟配置文件
![{FCTM5J${_3QE34%S9{~IC](https://user-images.githubusercontent.com/8984680/224498133-70550752-19f9-43dd-85c5-2932102c59fe.jpg)

# 8. 打开 go-cqhttp 的 device.json 把 protocol 改成 2
![~X%VD}KE@5W0I_61TJ%@2_F](https://user-images.githubusercontent.com/8984680/224498231-b76711a2-1a0a-4520-8606-e633f707dd74.jpg)

# 9. 重启 go-cqhttp，扫码即可使用机器人

![QM$VQ% UP@%$KDME))}BI0](https://user-images.githubusercontent.com/8984680/224498339-114c95f9-d7f3-46b4-ba25-7298041adafc.jpg)

# 注意事项：
这个go-cqhttp 的扫码登录，是需要你自己的手机 QQ 和 go-cqhttp 在同一个网络环境下的才能成功的。  

所以你们在服务器上跑 go-cqhttp 的话基本上是没戏（除非给你的手机使用代理）

因此，我的建议是在你自己的电脑上跑 go-cqhttp，然后在服务器跑 chatgpt

然后通过 go-cqhttp 的反向 websocket 功能，让你电脑上的 go-cqhttp 连接上服务器的 chatgpt 程序。  

唯一要修改的就是：在第2步里面将 `127.0.0.1` 就换成你运行 chatgpt 服务器的公网 IP 地址。

**Comment by lss233** [comment]
已发布。

**Comment by immengzi** [comment]
补充一下步骤 1，构建 dev 分支的 go-cqhttp 源代码

1. Linux下载 dev 分支的 go-cqhttp 源代码

```sh
git clone -b dev https://github.com/Mrs4s/go-cqhttp
```

2. 下载最新版 golang
```sh
wget https://golang.google.cn/dl/go1.20.2.linux-amd64.tar.gz
```

3. 切换到 go-cqhttp 源代码目录，输入
``` 
go build -ldflags "-s -w -extldflags '-static'"
```

**Comment by immengzi** [comment]
补充步骤 5:
先删除`[mirai] `的所有配置，再加入`[onebot] `的配置。

**Comment by LonePheasantWarrior** [comment]
> 

云里雾里的.请问`mirai`的所有配置是指那些配置呢?在`mirai`中有`bots`,`config`,`config.json`,`data`四个文件夹,其下有不少配置文件
此外`onebot`的配置应该放在什么路径下呢?

我根据引导配置了`docker-compose.yaml`,通过`mirai`登录提示:
```
Login failed: Error(bot=Bot(1870289887), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
```
然后就再查看issues一路到这里来了,相信有不少用户也是像我这样一路过来的,然后就尬在这里了...

**Comment by lss233** [comment]
> > 
> 
> 云里雾里的.请问要删除的`mirai`的所有配置是指那些配置呢?在`mirai`中有`bots`,`config`,`config.json`,`data`四个文件夹,其下有不少配置文件 此外`onebot`的配置应该放在什么路径下呢?
> 
> 我根据引导配置了`docker-compose.yaml`,通过`mirai`登录提示:
> 
> ```
> Login failed: Error(bot=Bot(1870289887), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
> ```
> 
> 然后就再查看issues一路到这里来了,相信有不少用户也是像我这样一路过来的,然后就尬在这里了...

我们只有一个配置文件，叫 `config.cfg`。  

另外，此部分部署方法已经合并至[项目文档](https://chatgpt-qq.lss233.com/pei-zhi-wen-jian-jiao-cheng/dui-jie-liao-tian-ping-tai/dui-jie-onebot)。

如果你有其他问题，建议发 issue 或者 Discussion。 在已经 close 的 issue 下提问此类问题容易被人忽略（我们收不到通知）。

**Comment by Anzu0831** [comment]
> 以下是简易的 go-cqhttp 使用方法：
> 
> ## 1. 下载最新 dev 分支的 go-cqhttp 和本程序的最新开发分支
> go-cqhttp 可以在这里找到： https://github.com/Mrs4s/go-cqhttp/actions/
> 
> 本程序可以在 [#303](https://github.com/lss233/chatgpt-mirai-qq-bot/issues/303#issuecomment-1462449540) 找到
> 
> ## 2. 解压并启动 go-cqhttp，选 后回车，退出程序`3`
> ![E$ER7F G39G1MY%4E2YO4LY](https://user-images.githubusercontent.com/8984680/224497145-c5457a73-6a98-4ad7-aba3-cabd52ba9044.jpg)
> 
> ## 3. 编辑 go-cqhttp 的 ，设置 （机器人） QQ 号 和反向 Universal 地址 （这个反向 Universal 地址和后面的有关）`config.yaml`
> ![图像](https://user-images.githubusercontent.com/8984680/224497246-080561e4-4819-4889-8de4-7fcb41c71d7a.png) ![图像](https://user-images.githubusercontent.com/8984680/224497325-3e3326a8-b214-4031-a97f-2ab694890406.png)
> 
> ## 4. 修改 docker-compose.yaml，暴露端口（Windows 跳过此步骤）
> ![CBD{30%G3SW（UAP'WA1SD X](https://user-images.githubusercontent.com/8984680/224497505-5728fd86-cefc-4a3d-b58d-c5133ef56da7.jpg)
> 
> ## 5. 修改 config.cfg，加入 的配置`[onebot]`
> ![image](https://user-images.githubusercontent.com/8984680/224497665-39578b91-f917-40a7-8a6b-80f84690e7cc.png)
> 
> ## 6. 执行 docker-compose up -d 更新容器 （在 Windows 上的话就是重启 chatgpt 程序）
> ![I`4 L944LV% W1TW1F$0MKC](https://user-images.githubusercontent.com/8984680/224497791-abd08516-0fc9-4e4b-a180-27fa82a198a0.jpg)
> 
> ## 7. 启动一次 go-cqhttp，生成虚拟配置文件
> ![{FCTM5J${_3QE34%S9{~IC](https://user-images.githubusercontent.com/8984680/224498133-70550752-19f9-43dd-85c5-2932102c59fe.jpg)
> 
> ## 8. 打开 go-cqhttp 的 device.json 把 改成 2`protocol`
> ![~X%VD}KE@5W0I_61TJ%@2_F](https://user-images.githubusercontent.com/8984680/224498231-b76711a2-1a0a-4520-8606-e633f707dd74.jpg)
> 
> ## 9. 重启 go-cqhttp，扫码即可使用机器人
> ![QM$VQ% UP@%$KDME))}BI0](https://user-images.githubusercontent.com/8984680/224498339-114c95f9-d7f3-46b4-ba25-7298041adafc.jpg)
> 
> ## 注意事项：
> 这个go-cqhttp 的扫码登录，是需要你自己的手机 QQ 和 go-cqhttp 在同一个网络环境下的才能成功的。
> 
> 这个问题有两种解决方法：
> 
> ### 方法一：代理
> 在你的服务器上搭个代理，让你的手机通过代理再进行扫码。
> 
> ### 方法二：同步 session.token 文件
> 在你自己的电脑上用同样的 device.json 来登陆一次 go-cqhttp，扫码登录成功后，把这个 session.token 放到服务器上
> 
> ### 方法三：在自己电脑运行
> 你自己的电脑上跑 go-cqhttp，然后在服务器跑 chatgpt
> 
> 然后通过 go-cqhttp 的反向 websocket 功能，让你电脑上的 go-cqhttp 连接上服务器的 chatgpt 程序。
> 
> 唯一要修改的就是：在第2步里面将 就换成你运行 chatgpt 服务器的公网 IP 地址。`127.0.0.1`

手贱把用linux一键部署生成的那个gocqhttp文件夹里的congfig和device都个删了，我怎么重新生成这两个文件？使用docker-compose up -d 或restart 或 stop后 start 依然无法生成该两个文件😥

**Comment by Anzu0831** [comment]
> > 以下是简易的 go-cqhttp 使用方法：
> > ## 1. 下载最新 dev 分支的 go-cqhttp 和本程序的最新开发分支
> > go-cqhttp 可以在这里找到： https://github.com/Mrs4s/go-cqhttp/actions/
> > 本程序可以在 [#303](https://github.com/lss233/chatgpt-mirai-qq-bot/issues/303#issuecomment-1462449540) 找到
> > ## 2. 解压并启动 go-cqhttp，选 后回车，退出程序`3`
> > ![E$ER7F G39G1MY%4E2YO4LY](https://user-images.githubusercontent.com/8984680/224497145-c5457a73-6a98-4ad7-aba3-cabd52ba9044.jpg)
> > ## 3. 编辑 go-cqhttp 的 ，设置 （机器人） QQ 号 和反向 Universal 地址 （这个反向 Universal 地址和后面的有关）`config.yaml`
> > ![图像](https://user-images.githubusercontent.com/8984680/224497246-080561e4-4819-4889-8de4-7fcb41c71d7a.png) ![图像](https://user-images.githubusercontent.com/8984680/224497325-3e3326a8-b214-4031-a97f-2ab694890406.png)
> > ## 4. 修改 docker-compose.yaml，暴露端口（Windows 跳过此步骤）
> > ![CBD{30%G3SW（UAP'WA1SD X](https://user-images.githubusercontent.com/8984680/224497505-5728fd86-cefc-4a3d-b58d-c5133ef56da7.jpg)
> > ## 5. 修改 config.cfg，加入 的配置`[onebot]`
> > ![image](https://user-images.githubusercontent.com/8984680/224497665-39578b91-f917-40a7-8a6b-80f84690e7cc.png)
> > ## 6. 执行 docker-compose up -d 更新容器 （在 Windows 上的话就是重启 chatgpt 程序）
> > ![I`4 L944LV% W1TW1F$0MKC](https://user-images.githubusercontent.com/8984680/224497791-abd08516-0fc9-4e4b-a180-27fa82a198a0.jpg)
> > ## 7. 启动一次 go-cqhttp，生成虚拟配置文件
> > ![{FCTM5J${_3QE34%S9{~IC](https://user-images.githubusercontent.com/8984680/224498133-70550752-19f9-43dd-85c5-2932102c59fe.jpg)
> > ## 8. 打开 go-cqhttp 的 device.json 把 改成 2`protocol`
> > ![~X%VD}KE@5W0I_61TJ%@2_F](https://user-images.githubusercontent.com/8984680/224498231-b76711a2-1a0a-4520-8606-e633f707dd74.jpg)
> > ## 9. 重启 go-cqhttp，扫码即可使用机器人
> > ![QM$VQ% UP@%$KDME))}BI0](https://user-images.githubusercontent.com/8984680/224498339-114c95f9-d7f3-46b4-ba25-7298041adafc.jpg)
> > ## 注意事项：
> > 这个go-cqhttp 的扫码登录，是需要你自己的手机 QQ 和 go-cqhttp 在同一个网络环境下的才能成功的。
> > 这个问题有两种解决方法：
> > ### 方法一：代理
> > 在你的服务器上搭个代理，让你的手机通过代理再进行扫码。
> > ### 方法二：同步 session.token 文件
> > 在你自己的电脑上用同样的 device.json 来登陆一次 go-cqhttp，扫码登录成功后，把这个 session.token 放到服务器上
> > ### 方法三：在自己电脑运行
> > 你自己的电脑上跑 go-cqhttp，然后在服务器跑 chatgpt
> > 然后通过 go-cqhttp 的反向 websocket 功能，让你电脑上的 go-cqhttp 连接上服务器的 chatgpt 程序。
> > 唯一要修改的就是：在第2步里面将 就换成你运行 chatgpt 服务器的公网 IP 地址。`127.0.0.1`
> 
> 手贱把用linux一键部署生成的那个gocqhttp文件夹里的congfig和device都个删了，我怎么重新生成这两个文件？使用docker-compose up -d 或restart 或 stop后 start 依然无法生成该两个文件😥

已从其他issue中找到答案，docker-compose run --rm gocqhttp
