### ISSUE TITLE
exceptions.NoAvailableBotException: chatgpt-web

### ISSUE THREAD

**Issue by jixiuy** [lss233/chatgpt-mirai-qq-bot#313]
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/93036363/223902683-4687225e-f325-42c3-bc12-23956f45e7c1.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/93036363/223902712-91aa2d1e-67ea-4b5e-a7c7-028d303673d2.png">

**Comment by lss233** [comment]
这是因为你的 ChatGPT 账号全部登录失败导致的。

**Comment by broweigit** [comment]
我也遇到了一模一样的问题，而且log中提示了OpenAI服务器登录成功，这是否就是chatGPT账号登录成功的意思呢？

**Comment by benny502** [comment]
我也遇到了同样的问题

**Comment by benny502** [comment]
我知道了，在配置文件下修改default_api，改成下面这样就好了
default_ai = "chatgpt-api"
