### ISSUE TITLE
[BUG] 群聊前缀设置无效

### ISSUE THREAD

**Issue by EdouardRichard** [lss233/chatgpt-mirai-qq-bot#316]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:*linux*  
- 操作系统：centos7
- Docker： 是
- 项目版本：3.4

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
群聊中发前缀后，机器人会回复。

**截图**  
![Screenshot_2023-03-09-17-46-02-275_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/125583616/223984664-10877a02-994b-46cb-843f-d53d86b326da.jpg)

![IMG_20230309_174909.jpg](https://user-images.githubusercontent.com/125583616/223984709-67ca322d-089a-4a21-b433-97498363fe08.jpg)

![IMG_20230309_174945.jpg](https://user-images.githubusercontent.com/125583616/223985413-354b4da8-ca44-46fe-bf4a-6ca186f58ec3.jpg)

**其他内容**  
实时查看日志发现mirai已经接收到信息并且转发给chatgpt-qq了

**Comment by lss233** [comment]
不是 BUG。
你写的 `prefix = [""]` 这行相当于无前缀。  
把它改成 `prefix = []` 就行。
