### ISSUE TITLE
插件需要更新，现在都不能用了

### ISSUE THREAD

**Issue by surf08** [lss233/chatgpt-mirai-qq-bot#32]
https://github.com/acheong08/ChatGPT/issues/261

**Comment by Xxpain** [comment]
同样的问题，无法正常工作，

**Comment by lss233** [comment]
可以使用反向代理功能绕过 Cloudflare，具体实施方案稍后更新

**Comment by xmexg** [comment]
发生错误
![image](https://user-images.githubusercontent.com/42137636/206965056-3e56ce3b-957c-4778-907c-7a35789503a0.png)
我的配置文件如下
![image](https://user-images.githubusercontent.com/42137636/206965287-2db1f89e-fb45-4d78-b316-99087292e8dd.png)

**Comment by lss233** [comment]
> 发生错误 ![image](https://user-images.githubusercontent.com/42137636/206965056-3e56ce3b-957c-4778-907c-7a35789503a0.png) 我的配置文件如下 ![image](https://user-images.githubusercontent.com/42137636/206965287-2db1f89e-fb45-4d78-b316-99087292e8dd.png)

你需要把 revChatGPT 升级到 0.0.37.3 或以上

**Comment by xmexg** [comment]
依旧无法登录,下图尝试使用cookie登录
![image](https://user-images.githubusercontent.com/42137636/206969269-0c1e0cca-16a7-4d6c-9f35-d2a4c4f26998.png)
下图尝试使用密码登录
![image](https://user-images.githubusercontent.com/42137636/206969446-97f5e438-a78f-4aaa-9266-fdd9c898edd5.png)

**Comment by PlexPt** [comment]
请检查以上参数是否正确，是否过期。并且获取以上参数的浏览器要和本程序在同一IP地址

**Comment by PlexPt** [comment]
需要加上这俩
![image](https://user-images.githubusercontent.com/15922823/206970534-cde360c5-4c27-46b3-96e5-a2c6c6098504.png)

**Comment by lss233** [comment]
一个暂时性的解决方案已更新， 由上游 [revChatGPT](https://github.com/acheong08/ChatGPT) 提供。当前正在使用的用户，可以根据以下步骤升级到最新版。  

1. 更新至最新版 revChatGPT
```bash
pip install --upgrade revChatGPT
```

2. 下载并安装 Chrome  
3. 
Ubuntu 用户安装教程: https://askubuntu.com/questions/510056/how-to-install-google-chrome  

(云服务器用户如果没有图形界面，可以安装 Xvfb）

4. 使用 `session_token` 登录，此方法已在 [README](https://github.com/lss233/chatgpt-mirai-qq-bot#openai-%E7%99%BB%E5%BD%95%E4%B8%8D%E4%BA%86) 中介绍。 

5. 重新启动 `bot.py`，等待验证通过即可使用！
