### ISSUE TITLE
[Feature] 增加对指定群聊启用/禁用bot的功能

### ISSUE THREAD

**Issue by NFHr** [lss233/chatgpt-mirai-qq-bot#324]

**Comment by lss233** [comment]
有这功能，请阅读：[🧵 额度限制 & 黑白名单](https://github.com/lss233/chatgpt-mirai-qq-bot/wiki/%F0%9F%A7%B5-%E9%A2%9D%E5%BA%A6%E9%99%90%E5%88%B6-&-%E9%BB%91%E7%99%BD%E5%90%8D%E5%8D%95)  
如果你需要更深程度的禁用，为什么不直接用 Mirai 的群管插件呢？

**Comment by NFHr** [comment]
感谢
