### ISSUE TITLE
[Feature] 希望地址能反向代理地址

### ISSUE THREAD

**Issue by beiyaohhhc** [lss233/chatgpt-mirai-qq-bot#325]
https://github.com/transitive-bullshit/chatgpt-api
希望能支持此仓库的反向代理地址

**Comment by lss233** [comment]
您要找的是不是：
`browserless_endpoint`

**Comment by beiyaohhhc** [comment]
是 但配置文件内没有

**Comment by lss233** [comment]
没有可以自己加。  
我已经把所有的配置项都写出来了。
