### ISSUE TITLE
[BUG] AI画图功能回复异常

### ISSUE THREAD

**Issue by pamaforce** [lss233/chatgpt-mirai-qq-bot#328]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
使用画图命令后可以从日志中看到拿到了正确的回复，但是发送到聊天窗口的却只有“,type=show,id=40000”

**运行环境:**  
- 操作系统：Windows Server 2012
- Docker： 非Docker
- 项目版本：browser-version-dev分支

**复现步骤**  
切换至chatgpt-api
对AI发出指令：画一只小猫，简约线条
即回复：,type=show,id=40000

**预期行为**  
返回由AI生成的图片

**截图**  
![F8Y@6IC8N}2T$UY91QW3%AJ](https://user-images.githubusercontent.com/72378846/224504253-1dbe0640-2f29-4868-b8c4-634878440ed7.jpg)
![JN(I@)MW}R{XR_Q 0J9SGSW](https://user-images.githubusercontent.com/72378846/224504267-58b02e10-3baa-45cc-a672-2892b8aee9c2.png)

**Comment by lss233** [comment]
最新的 dev 分支已提交修复。
