### ISSUE TITLE
[BUG] Bot 不会自动回复消息

### ISSUE THREAD

**Issue by Admmmmmmin** [lss233/chatgpt-mirai-qq-bot#329]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  

Bot 在回复消息时不会自动选中正在回复的消息

**运行环境:**  
- 操作系统：Ubuntu 18.04.6 LTS
- Docker： ？
- 项目版本：Dev 版本

**预期行为**  

正常应该出现图一的形式，Dev 版本部署后出现的却是图二的样式。

![图一](https://user-images.githubusercontent.com/78294316/224504201-d236791c-f32c-4879-9e99-b10e9c478546.jpg)

![图二](https://user-images.githubusercontent.com/78294316/224504212-2d80692d-dc7d-4dbe-9d56-8886a9ca0d00.jpg)

```
chat-chatgpt-1     | 2023-03-11 17:51:43.795 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中<utils.QueueInfo object at 0x7fddca548c50>，前面还有 0 个人！
chat-chatgpt-1     | 2023-03-11 17:51:43.796 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
chat-chatgpt-1     | 2023-03-11 17:51:43.801 | DEBUG    | middlewares.timeout:create_timeout_task:12 - [Timeout] 开始计时……
chat-chatgpt-1     | 2023-03-11 17:51:57.572 | DEBUG    | adapter.chatgpt.api:ask:75 - [ChatGPT-API] 响应：入睡通常需要放松和减少烦恼的情绪，以下是一些方法
可以帮助你快速入睡：
chat-chatgpt-1     |
chat-chatgpt-1     | 1. 建立一个稳定的睡眠时间表，每晚睡前大约在同一个时间上床，并尽量保持规律的睡眠时间。
```

** Config.cfg 中的项也已改为 true**
```
# 是否要回复触发指令的消息
quote = true
```

**Comment by lss233** [comment]
已知问题，暂时没在 aiocqhttp 找到改成 quote 的方法，之后再修。

**Comment by lss233** [comment]
已支持。
