### ISSUE TITLE
[BUG] 无法读取到Mirai的聊天信息

### ISSUE THREAD

**Issue by Atomseek** [lss233/chatgpt-mirai-qq-bot#337]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
更新到2.2.3版本并使用正向连接mirai，mirai-http能正常收到信息，但是chatgpt-mirai这边没任何反应，即使mirai-http容器关闭了也没有反应。之前用2.2.1版本没有这个问题，而且以前版本即使mirai关闭了，也会有一直尝试重连的提示。我删掉了之前的配置文件和data文件夹，重新配置依旧如此。
按照wiki更换为反向连接模式情况依旧。

**运行环境:**  
- 操作系统：群晖
- Docker： 20.10.3-0554
- 项目版本：2.2.3

**截图**  
![Screenshot_20230313_013239](https://user-images.githubusercontent.com/67729048/224562028-026036f3-8fd3-4d05-8d54-3b54f35a4ad2.png)

**其他内容**  
mirai的setting:
![Screenshot_20230313_013603](https://user-images.githubusercontent.com/67729048/224562158-16615daf-f573-4ca2-995c-9adf9a58e0f9.png)

chatgpt-mirai的config:
![Screenshot_20230313_013632](https://user-images.githubusercontent.com/67729048/224562183-77cef4fc-3f90-4ee9-b055-4262493e1f54.png)

mirai-http内各插件版本：
![Screenshot_20230313_015153](https://user-images.githubusercontent.com/67729048/224563003-dc223104-b8fd-44cb-9a01-c33a8a6ce70d.png)

查看端口mirai-http是在正常监听，两个docker容器均设置为与本机网络相同，两个容器均拉取最新版本。

**Comment by wangmw3617** [comment]
同

**Comment by lss233** [comment]
最新的容器没有这个问题，你的应该不是最新的。

使用正向连接时chatgpt里的两个url应该填mirai，而不是localhost

**Comment by Atomseek** [comment]
> 
手动选择2.2.3版本的容器也是这样，2.2.1则一切正常

在1.5.x版本时候，mirai-http那边设置host:mirai，port:8080，
chatgpt里填http://mirai:8080会报错。

我删掉host:mirai后，chatgpt直接用127.0.0.1或者localhost才正常

**Comment by lss233** [comment]
使用 browser-version 才能保证你拿到的是最新版本镜像。

**Comment by Atomseek** [comment]
> 使用 browser-version 才能保证你拿到的是最新版本镜像。
好的，拉取今天新发布的browser-version问题解决了

**Comment by dellnoantechnp** [comment]
拉取最新镜像  重启恢复。
