### ISSUE TITLE
hello作者大大，我用最新的安装包部署的，但是tg模式发消息没有回应

### ISSUE THREAD

**Issue by yu1101610062** [lss233/chatgpt-mirai-qq-bot#342]
![J68(ETM8`U P2SC7 YORAJI](https://user-images.githubusercontent.com/48397834/224628255-f0216cdc-d108-4e44-9a28-d42147a8a69f.jpg)
![image](https://user-images.githubusercontent.com/48397834/224628563-69339e10-33e8-4c2a-940b-e9897454f499.png)
我的服务器是可以连上外网的，而且日志也没有报错，不知道哪里出了问题

**Comment by yu1101610062** [comment]
![image](https://user-images.githubusercontent.com/48397834/224628810-eead6dd7-03fd-4be6-a54c-d1f924bf0600.png)

**Comment by yu1101610062** [comment]
> 

好的，谢谢提醒！这个是日志
![image](https://user-images.githubusercontent.com/48397834/224639107-1e26e391-c20f-4bbf-9cf5-2d10fe802f81.png)
看起来好像很正常，但是tg模式也会用到mirai吗？

**Comment by yu1101610062** [comment]
> 建议贴一下mirai日志 还有你qq机器人账号没打码

好的，谢谢提醒！这个是日志
![image](https://user-images.githubusercontent.com/48397834/224639584-49d5cf13-20de-4f86-9693-1c2102ebb36e.png)

看起来好像很正常，但是tg模式也会用到mirai吗？

**Comment by yu1101610062** [comment]
虽然群聊@机器人没反应，但是私聊机器人可以收到错误信息和日志
![image](https://user-images.githubusercontent.com/48397834/224641953-6339af54-19a3-4e2a-9557-ccc499c0284b.png)

![image](https://user-images.githubusercontent.com/48397834/224641905-07e4c8de-f8d7-4364-a76a-1abcb9c1f99c.png)

**Comment by yu1101610062** [comment]
群聊不回复是我的问题，我改了bot设置，现在群聊也会报这个错误了

**Comment by yu1101610062** [comment]
我在历史bug中找到了这个报错，但是显示bug已经修复了，但是我已经是docker compose pull过了，是升级的有问题吗

**Comment by lss233** [comment]
tg 模式不需要启动mirai。  看日志已经有反应了，估计是你账号问题导致提问不了。

**Comment by yu1101610062** [comment]
> 

好我换一下账号试试，但是很奇怪，我qq都正常

**Comment by lss233** [comment]
你的 browserless_endpoint 可能是多了个 api/
删了试试。

**Comment by yu1101610062** [comment]
> 你的 browserless_endpoint 可能是多了个 api/ 删了试试。

好了！！！感谢！！！
