### ISSUE TITLE
[Feature] 可否设置ChatGPT对某些内容不响应，方便与其他插件兼容

### ISSUE THREAD

**Issue by Febtw** [lss233/chatgpt-mirai-qq-bot#344]
我看到了Feature #271 的实现，但是对于想要将ChatGPT作为bot的主要功能的人来说，每次对话都要加前缀并不是很好的体验。
如果可以设置一个列表，本项目不响应这个列表中的内容，那么只要将其他插件的命令添加到这个列表中，就可以自然地将其他插件当成扩展功能了；
如果可以在本项目加载mirai插件就更好了，或许这样还能改写其他插件的命令，统一命令格式。

**Comment by lss233** [comment]
好的，之后会加入

**Comment by Febtw** [comment]
> 好的，之后会加入

好的，谢谢

**Comment by wangmw3617** [comment]
加个对指定前缀不响应也不错

**Comment by lss233** [comment]
> 加个对指定前缀不响应也不错

这个本来就有

**Comment by lss233** [comment]
v2.2.4 已支持  
通过设置 ignore_regex 来屏蔽一些特定的 prompt。  
ignore_regex 可以填写正则表达式数组，你可以在 https://regex101.com 测试你的正则表达式，也可以让 ChatGPT 教/帮你写正则表达式。

**Comment by Febtw** [comment]
> v2.2.4 已支持 通过设置 ignore_regex 来屏蔽一些特定的 prompt。 ignore_regex 可以填写正则表达式数组，你可以在 https://regex101.com 测试你的正则表达式，也可以让 ChatGPT 教/帮你写正则表达式。

OK，已经用上了，不过不知道怎么设置大小写不敏感，比如 "/^ */mcl(x|)($| .*)/gi" 这样设置会出错

**Comment by lss233** [comment]
看看这个：https://stackoverflow.com/questions/500864/case-insensitive-regular-expression-without-re-compile

**Comment by Febtw** [comment]
> 看看这个：https://stackoverflow.com/questions/500864/case-insensitive-regular-expression-without-re-compile

好的
