### ISSUE TITLE
[BUG] 无法登录openai

### ISSUE THREAD

**Issue by wsx11** [lss233/chatgpt-mirai-qq-bot#346]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问e题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：ubuntu 18.04
- Docker： ？
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的
1. restart

**截图**  
chatgpt-qq-chatgpt-1     | 2023-03-13 15:11:37.824 | INFO     | ariadne_bot:start_background:129 - OpenAI 服务器登录中……
chatgpt-qq-chatgpt-1     | 2023-03-13 15:11:37.824 | INFO     | manager.bot:login_openai:110 - 正在登录第 1 个 OpenAI 账号
chatgpt-qq-chatgpt-1     | 2023-03-13 15:11:37.825 | INFO     | manager.bot:__login_V1:203 - 模式：无浏览器登录
chatgpt-qq-chatgpt-1     | 2023-03-13 15:11:37.826 | INFO     | manager.bot:__check_proxy:174 - [代理测试] 正在检查代理配置：http://127.0.0.1:1080
chatgpt-qq-chatgpt-1     | 2023-03-13 15:11:37.826 | ERROR    | manager.bot:login_openai:140 - 未知错误：
chatgpt-qq-chatgpt-1     | 2023-03-13 15:11:37.826 | ERROR    | manager.bot:login_openai:141 - 登录失败! 无法连接至本地代理服务器，请检查配置文件中的 proxy 是否正确！

**Comment by lss233** [comment]
看样子你是 docker 部署的。 docker容器之间 IP 是隔离的，你不能用 127.0.0.1 这个 IP来连接代理。
