### ISSUE TITLE
[BUG] web正常，但无法使用chatgpt-api+bing

### ISSUE THREAD

**Issue by Xzcy** [lss233/chatgpt-mirai-qq-bot#347]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
无法使用ChatGPT API版和bing功能.

**运行环境:**  
- 操作系统：CentOS Linux release 7.6.1810 (Core)
- Python：3.11.2
- Docker：Mirai及该项目均未使用docker
- 项目版本：截至2023/3/14 00:34 brower-version的克隆
- Mirai版本：Mirai-core/console-2.14.0 + mirai-api-http-2.8.0
- 代理方式：socks5 + Privoxy转为http/https代理

**复现步骤**  
使用该项目前已部署Mirai及proxy等，且以下尝试中未修改。
1、最初使用V1.5.8网页版+邮箱密码无浏览器登录，可正常运行
2、从v2.0.2版本开始问题层出不穷
1. 编译安装Python3.11.2后出现SSL证书问题，遂再编译时指定OpenSSL 1.1.1g（可能是随后问题伏笔）
2. v2.0.2版中，web、api、bing三者均无法使用。
bing报SSL: CERTIFICATE_VERIFY_FAILED错误，一路追查至site-packages/EdgeGPT.py。添加如下代码后，bing功能可用。
> import ssl
import certifi
ssl_context = ssl.create_default_context()
ssl_context.load_verify_locations(certifi.where())
232 websocks.connect()中追加ssl=ssl_context参数
> 
 但web和api依然不可用（当时错误代码未留，但与下文错误不同）

3. 更新至V2.2.3.1后，再次出现web、api、bing均无法使用，且报错内容各不相同。
bing：requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
web：直接报的revChatGPT.V1之类的错误，没留错误信息
api：HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb7409d97d0>: Failed to establish a new connection: [Errno 113] No route to host'))

3、clone截至2023/3/14 00:34的brower-version后，目前web可正常工作。api和bing报错同前，报错内容见下文。
*redirect问题可能与allow-redirect参数有关？

**预期行为**  
web、api、bing版均可正常运行

**截图**  
1、可正常登陆web、api、bing账户
![image](https://user-images.githubusercontent.com/47129094/224775258-ebf4a2cf-5365-456d-b8af-2d6715c4f4d6.png)
2、web反应正常
![image](https://user-images.githubusercontent.com/47129094/224775645-a65fc3dd-bb7c-4bbc-8adf-0fe6deb2b38a.png)
3、bing无法使用
[bing.txt](https://github.com/lss233/chatgpt-mirai-qq-bot/files/10959856/bing.txt)
4、api无法使用
[api.txt](https://github.com/lss233/chatgpt-mirai-qq-bot/files/10959887/api.txt)

**其他内容**  
配置文件（抹去了bing cookie和GPT登陆信息）
[config.txt](https://github.com/lss233/chatgpt-mirai-qq-bot/files/10959921/config.txt)

**Comment by chung1912** [comment]
是有这个bug

**Comment by tHaxWLa** [comment]
我是拉项目手动运行的，x86的机子没问题，arm的bing用不了，也是报requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by JCCER996** [comment]
坏，我也这样，api跟bing用不了

**Comment by JCCER996** [comment]
> 坏，我也这样，api跟bing用不了

但是挂全局代理就正常了

**Comment by tHaxWLa** [comment]
应该可以给bing也加个代理...在国内会一直重定向

**Comment by lss233** [comment]
> 应该可以给bing也加个代理...在国内会一直重定向

这个已经在努力了

**Comment by lss233** [comment]
v2.2.4 已修复此问题
