### ISSUE TITLE
[BUG] 机器人对于处理超时的消息不会剔除消息队列

### ISSUE THREAD

**Issue by MIKU-N** [lss233/chatgpt-mirai-qq-bot#349]
**表现**  
在群聊情况下，机器人可能会对部分消息的处理发生超时，此时，该群的消息队列将会被超时的消息卡住，无法处理其他内容

**运行环境:**  
- 操作系统：Debian10(ARM64)
- Docker： Docker version 23.0.1, build a5ee5b1/Docker Compose version v2.2.2
- 项目版本：v2.2.3.1

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 发送消息
2. 后台日志观察到消息处理已超时，机器人返回超时消息“正在思考中”
3. 再发送其他消息，此时队列已经被卡住

**预期行为**  
我建议是给每一条消息定义一个最大超时时间，超过此时间的问题将被强制结束或返回其他消息
或者，将重置会话的功能处理优先级调高，如果检测到此关键词将忽略正在处理/等待返回的消息强制重置对话

**截图**  
![image](https://user-images.githubusercontent.com/61493780/225003656-e210d247-d16a-4db8-9384-466070142f96.png)
![image](https://user-images.githubusercontent.com/61493780/225003741-2a2b8574-2f78-413e-899c-2f72245cd6d6.png)

**Comment by MIKU-N** [comment]
另外，对于机器人的重新``.重新加载配置文件``命令，此命令似乎并不会重新读取预设的配置，只能重启手动重启容器，如果可以不妨将预设页可以重新读取

**Comment by lss233** [comment]
2.2.4 已加入最长等待时间。

**Comment by MIKU-N** [comment]
> 2.2.4 已加入最长等待时间。

似乎此次的更新出现了一些BUG，现在对于较长内容的回复，BOT对OpenAI返回结果的处理不正确，譬如询问BOT“你可以介绍一下OpenAI么？”得到的返回是下图这样:
![image](https://user-images.githubusercontent.com/61493780/225304393-d22064b3-659d-4456-882b-24bf21447695.png)
![image](https://user-images.githubusercontent.com/61493780/225304411-90a8493c-4079-4883-a8b8-d30b840f70ae.png)
