### ISSUE TITLE
使用token+cf_clearance无法独立会话

### ISSUE THREAD

**Issue by chenxiangxingxie** [lss233/chatgpt-mirai-qq-bot#35]
使用token+cf_clearance无法独立会话（之前的邮箱+密码是可以的），只能首个会话，再次创建会话（换个群），就会报错
![image](https://user-images.githubusercontent.com/66203683/207004824-88e6d759-8aaf-44cd-8e41-5ee514bd17eb.png)

**Comment by lss233** [comment]
更新最新的代码试试看

**Comment by chenxiangxingxie** [comment]
更新最新代码后，问题不再发生，但所有窗口为同一会话ID
