### ISSUE TITLE
[BUG] 使用bing时，总是回复“已结束本次会话。继续发送消息将重新开启一个新会话”

### ISSUE THREAD

**Issue by wuzenghui** [lss233/chatgpt-mirai-qq-bot#353]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
1.运行一段时间后。再次使用bing时，总是回复“已结束本次会话。继续发送消息将重新开启一个新会话”。
2.重启容器没有恢复。

**运行环境:**  
- 操作系统：CentOS 7.9
- Docker： 23.0.1
- Python：3.9.5
- 项目版本：lss233/chatgpt-mirai-qq-bot:browser-version-dev

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 使用bing，必现此问题，而且重启容器没有恢复。

**预期行为**  
bing正常运行，并回答正确的内容。

**截图**  
![image](https://user-images.githubusercontent.com/51453629/225177282-9f7b9dfa-8a29-415a-b09f-118d7786a681.png)
![image](https://user-images.githubusercontent.com/51453629/225177447-9c818ca6-4853-4a54-8187-6b7e87f63c01.png)
![image](https://user-images.githubusercontent.com/51453629/225177509-348b571a-ecef-4783-901b-799c12fd12a3.png)
![image](https://user-images.githubusercontent.com/51453629/225177685-f17ea7f7-6d03-4f45-9a26-77b5ac8b253d.png)

**Comment by AngalPeng** [comment]
https://github.com/acheong08/EdgeGPT/pull/124#issue-1624462893
这条链接有解决办法
在python包里找EdgeGPT.py，在里面找到if response.get("type") == 1这行
用这行替换掉它if response.get("type") == 1 and response["arguments"][0].get("messages"):

**Comment by wuzenghui** [comment]
感谢~
