### ISSUE TITLE
[Feature] 请支持revChatGPT4.0.0

### ISSUE THREAD

**Issue by SaithZhang** [lss233/chatgpt-mirai-qq-bot#355]
今天发布了chatgpt 4.0版本，麻烦作者大大支持一下逆向库网页版，谢谢！

**Comment by xslingcn** [comment]
我自己改了个支持到revChatGPT 4.0的版本，现在看来有一个问题是本项目依赖已经被revChatGPT弃用的Unofficial.py进行浏览器登录，直接pull最新版本会导致该功能不可用。我图方便的做法是直接把这个文件单独放在本地，但对项目来讲肯定不是很好的方案。

**Comment by SaithZhang** [comment]
我刚也试了直接upgrade，运行bot就报错了Unofficial找不到，后面就没细弄

**Comment by xslingcn** [comment]
> 我刚也试了直接upgrade，运行bot就报错了Unofficial找不到，后面就没细弄

要改的话很快，upgrade之后config里加一下model这个键，然后在login逻辑里读一下这个值就可以了。但是Unofficial这个怎么弄还是要看作者的设计决策。

**Comment by SaithZhang** [comment]
> > 我刚也试了直接upgrade，运行bot就报错了Unofficial找不到，后面就没细弄
> 
> 要改的话很快，upgrade之后config里加一下model这个键，然后在login逻辑里读一下这个值就可以了。但是Unofficial这个怎么弄还是要看作者的设计决策。

可以的，多谢大佬，中午试试~

**Comment by xslingcn** [comment]
我用我改的方案提了个[PR](https://github.com/lss233/chatgpt-mirai-qq-bot/pull/359)，供您参考下。

**Comment by SaithZhang** [comment]
> 我用我改的方案提了个[PR](https://github.com/lss233/chatgpt-mirai-qq-bot/pull/359)，供您参考下。

感谢，我patch了下，不过还是有点报错（404），可能是我网络环境的问题，晚上下班再试试，谢谢大佬！

**Comment by xslingcn** [comment]
> > 我用我改的方案提了个[PR](https://github.com/lss233/chatgpt-mirai-qq-bot/pull/359)，供您参考下。
> 
> 感谢，我patch了下，不过还是有点报错（404），可能是我网络环境的问题，晚上下班再试试，谢谢大佬！

如果你的`browserless_endpoint` 是 `https://bypass.duti.tech/` 的话需要在最后加上`api/`，改成`https://bypass.duti.tech/api/`。这个可能是`revChatGPT`那边更新之后把这个路径拿掉了。

**Comment by lss233** [comment]
好了，我发布了 2.2.4
