### ISSUE TITLE
使用go-cqhttp的时候发送图片出错

### ISSUE THREAD

**Issue by benny502** [lss233/chatgpt-mirai-qq-bot#357]
不知道是go-cqhttp的问题还是什么原因
当我打开text_to_image的时候，chatgpt的回复可以返回，但是在发送群消息这一步出错，提示：SEND_MSG_API_ERROR:send group message failed，blocked by server
关闭text_to_image，消息就可以正常发送到群里

**Comment by lss233** [comment]
请按照模板重写issue

**Comment by lss233** [comment]
v2.2.4 已修复此问题
