### ISSUE TITLE
OpenAI账户被封了，我想知道是否与mirai http api的正向连接方式有关

### ISSUE THREAD

**Issue by Kersonz** [lss233/chatgpt-mirai-qq-bot#358]
之前在[v1.5.6.1]运行了一段时间，隔了一段时间没用，昨天升级了[v2.2.3.1]，今天就被account deactivated了。
因为并不了解反向连接怎么设置，我选择把mirai和本项目都部署到本地，mirai http api都选择正向连接，还当旧版本那么用，其余设置均没有变化。
我是知道openAI会封国区账号，但是目前我部署mirai的这台机器在不通过代理的情况下是不能访问OpenAI的。
现在换了个账号能够正常运行，只是不知道之前的账号为什么被封，是我哪个环节出现了问题吗？

**Comment by Kersonz** [comment]
> 刚封 非公测地区请求api 会封号 把代理出口改到公测地区

不知道公测地区有哪些？
我姑且改成美国ip先用吧

**Comment by 1396698241** [comment]
我也是这样被停用了，这个还能解封嘛？

**Comment by fireinrain** [comment]
> 我也是这样被停用了，这个还能解封嘛？

不太可能 我的账号 还是老号 已经被deactive了 发邮件给官方也没用

**Comment by fungaren** [comment]
> > 刚封 非公测地区请求api 会封号 把代理出口改到公测地区
> 
> 不知道公测地区有哪些？ 我姑且改成美国ip先用吧

老哥，你试了咋样？

**Comment by 1396698241** [comment]
> 

这个官方邮件地址是什么啊？我想去试试 我也是老号😭

**Comment by 1396698241** [comment]
> > 我也是这样被停用了，这个还能解封嘛？
> 
> 不太可能 我的账号 还是老号 已经被deactive了 发邮件给官方也没用

这个官方邮件地址是什么啊？我想去试试 我也是老号😭

**Comment by lss233** [comment]
和 mirai 如何设置没有关系。

**Comment by syccxdr** [comment]
还能解封吗？

**Comment by lss233** [comment]
> 还能解封吗？

你应该问的是 OpenAI

**Comment by syccxdr** [comment]
是啊，主要我充了plus 然后用chatgpt plus 做毕设 ，已经给那边发了邮件了 不知道行不行

**Comment by syccxdr** [comment]
不能解封至少把我的钱退给我吧hh

**Comment by AI-Rocket-Camp** [comment]
搭建了一个微信群，面向ChatGPT开发者，探讨以下问题：1、openai ai不明原因被封的；2、如何选择海外服务器；3、如何提高国内用户访问速度；4、变现相关经验探讨。等等，面向ChatGPT api生态的开发者：
![开发者群聊二维码](https://user-images.githubusercontent.com/50973253/227759107-6d5729e4-c45a-48e7-b20a-39f735eb5b64.png)

**Comment by AI-Rocket-Camp** [comment]
搭建了一个微信群，面向ChatGPT开发者，探讨以下问题：1、openai ai不明原因被封的；2、如何选择海外服务器；3、如何提高国内用户访问速度；4、变现相关经验探讨。等等，面向ChatGPT api生态的开发者：
![WX20230401-184113@2x](https://user-images.githubusercontent.com/50973253/229283056-9f12fac1-ae37-4a95-b93d-a9df2b5b0d57.png)
如果进不去，可能超过200人了，请加微信AI-camp-666
