### ISSUE TITLE
[BUG] openai-api没有经过代理

### ISSUE THREAD

**Issue by cjj490168650** [lss233/chatgpt-mirai-qq-bot#360]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
使用docker-compose部署，在配置文件`docker-compose.yaml`中的environment设置了代理，使用时chatgpt-web和bing-cookie成功经过了代理，但openai-api没有，使用画图功能时提示`openai.error.APIConnectionError: Error communicating with OpenAI`

**运行环境:**  
- 操作系统：Linux VM-0-10-ubuntu 5.15.0-56-generic 62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Docker： docker-compose version 1.29.2
- 项目版本：2.2.3.1

**复现步骤**  
1. 在`docker-compose.yaml`中的environment设置代理
2. 在`config.cfg`中分别设置chatgpt-web、bing-cookie和openai-api的账号
3. 分别测试三个账号的功能
4. 在代理日志中，发现chatgpt-web、bing-cookie成功经过了代理，但是使用openai-api画图时没有代理日志

**预期行为**  
三种账号都能经过代理

**截图**  
![image](https://user-images.githubusercontent.com/45029740/225227636-fb7f6ea2-2516-4791-ae39-a70d7e5598ca.png)
![image](https://user-images.githubusercontent.com/45029740/225216141-e9148a4f-01d8-4610-9a7d-7554892f72c5.png)
![image](https://user-images.githubusercontent.com/45029740/225216238-c12f3972-4747-4bfb-a2ba-d3e3ad08d2a5.png)
![image](https://user-images.githubusercontent.com/45029740/225216368-7b30de02-148d-4cda-9111-d49d0ab0da97.png)
![image](https://user-images.githubusercontent.com/45029740/225216396-56eb2424-c4bc-44ec-9043-afd0c483b948.png)

**其他内容**  
关于为什么不在`config.cfg`中设置代理，因为之前在这里面设置代理时会提示“无法连接至代理服务器”，而在`docker-compose.yaml`中设置是可以成功的

**Comment by DevHaoZi** [comment]
#307
