### ISSUE TITLE
[BUG] gocqhttp报错 malformed ws or wss URL

### ISSUE THREAD

**Issue by Apricityx** [lss233/chatgpt-mirai-qq-bot#361]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
gocqhttp后台报错malformed ws or wss URL
ChatGPT后台报错 Connection to chatgpt:8554/ interrupted
配置文件如下，找不到哪个地方配置错了
**截图**  
*docker-compose.yml的内容*
![EOXNFV839~4YHAPIBBHBZBX](https://user-images.githubusercontent.com/78242039/225220692-4711f341-c091-4a3e-9302-94dd0b9d65a3.png)
*gocqhttp的内容*
![2](https://user-images.githubusercontent.com/78242039/225220722-6baa538a-96c9-48c2-8a40-f1724dafeaa4.png)
*config.ymal的内容*
![3](https://user-images.githubusercontent.com/78242039/225220732-cf589815-ca16-4f03-b798-368f536c6e1b.png)

**Comment by lss233** [comment]
写错了， 你 universal 应该写 ws://chatgpt:8566/ws

**Comment by Apricityx** [comment]
所以说W/reverse-ws adapter: [reverse-ws] Connection to chatgpt:8554/ interrupted. Trying reconnect in 5000 ms.
这个报错就不管吗





---原始邮件---
发件人: "Dark ***@***.***&gt;
发送时间: 2023年3月15日(周三) 下午5:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lss233/chatgpt-mirai-qq-bot] [BUG] gocqhttp报错 malformed ws or wss URL (Issue #361)




 
写错了， 你 universal 应该写 ws://chatgpt:8566/ws

**Comment by Apricityx** [comment]
只有gocqhttp那边加了/ws



---原始邮件---
发件人: "Dark ***@***.***&gt;
发送时间: 2023年3月15日(周三) 下午5:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lss233/chatgpt-mirai-qq-bot] [BUG] gocqhttp报错 malformed ws or wss URL (Issue #361)




 
你后面加了 /ws 了吗？
 两边程序都启动了吗？

**Comment by Apricityx** [comment]
> 你后面加了 /ws 了吗？
> 两边程序都启动了吗？

gocqhttp那边跳报错变成了
连接到反向WebSocket Universal服 务器 ws://chatgpt:8566/ws 时出现错误: dial tcp: lookup chatgpt on 127.2.0.17:53: no such host

**Comment by lss233** [comment]
这个应该是 chatgpt 那个容器没启动成功

**Comment by Apricityx** [comment]
有没有可能是我config.ymal里地址填的0.0.0.0而没有填docker外部的ip导致的



---原始邮件---
发件人: "Dark ***@***.***&gt;
发送时间: 2023年3月15日(周三) 下午5:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lss233/chatgpt-mirai-qq-bot] [BUG] gocqhttp报错 malformed ws or wss URL (Issue #361)




 
这个应该是 chatgpt 那个容器没启动成功

**Comment by lss233** [comment]
没有可能

**Comment by Apricityx** [comment]
ChatGPT那边是正常的，已经报登录上账号了，我ChatGPT丢容器的，gocqhttp单独运行



---原始邮件---
发件人: "Dark ***@***.***&gt;
发送时间: 2023年3月15日(周三) 下午5:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lss233/chatgpt-mirai-qq-bot] [BUG] gocqhttp报错 malformed ws or wss URL (Issue #361)




 
没有可能

**Comment by lss233** [comment]
如果你这么运行的话，可以 url 可以改成 ws://localhost:8554/ws

启动成功后就不会继续提示错误了。

**Comment by Apricityx** [comment]
> 如果你这么运行的话，可以 url 可以改成 ws://localhost:8554/ws
> 
> 启动成功后就不会继续提示错误了。

改完了提示如下
连接到反向WebSocket Universal服 务器 ws://localhost:8554/ws 时出现错误: unexpected EOF
docker-compose配置如下
![Screenshot_20230315-182645.png](https://user-images.githubusercontent.com/78242039/225281636-47ae7724-d6d9-4d35-90c3-949d1c84b318.png)

**Comment by GudaoO** [comment]
![QQ截图20230502173354](https://user-images.githubusercontent.com/113413850/235631682-122517c1-10bc-4aab-acd2-399e2bd52cee.png) 大佬能帮我看看不，我全按官网弄得但是一直不行

**Comment by GudaoO** [comment]
一直报错

**Comment by lss233** [comment]
https://chatgpt-qq.lss233.com/chang-jian-wen-ti-jie-da/gocqhttp-qi-dong-guo-cheng-zhong-de-chang-jian-wen-ti

> 一直报错，感觉使用教程有问题

**Comment by lss233** [comment]
https://chatgpt-qq.lss233.com/chang-jian-wen-ti-jie-da/gocqhttp-qi-dong-guo-cheng-zhong-de-chang-jian-wen-ti

> 一直报错，感觉使用教程有问题
