### ISSUE TITLE
[BUG] 对于较长内容的回复，BOT对OpenAI返回结果的处理不正确

### ISSUE THREAD

**Issue by MIKU-N** [lss233/chatgpt-mirai-qq-bot#364]
**表现**  
似乎此次的更新出现了一些BUG，现在对于较长内容的回复，BOT对OpenAI返回结果的处理不正确

**运行环境:**  
- 操作系统：Debian10(ARM64)
- Docker： Docker version 23.0.1, build a5ee5b1/Docker Compose version v2.2.2
- 项目版本：V2.2.4(Build Commit [e002a25])

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 任意询问一个问题，只要让BOT回复的内容较长即可,例如询问它”可以介绍一下OpenAI吗？“
2. Bot将会发送请求，但由于处理的异常，会有三分钟左右的处理时间
3. 返回异常的文本

**预期行为**  
正常输出完整的内容

**截图**  
![image](https://user-images.githubusercontent.com/61493780/225304393-d22064b3-659d-4456-882b-24bf21447695.png)
![image](https://user-images.githubusercontent.com/61493780/225304411-90a8493c-4079-4883-a8b8-d30b840f70ae.png)
![image](https://user-images.githubusercontent.com/61493780/225309231-e29e170e-9cc0-4c8b-a970-4557e55c46d2.png)

**Comment by lss233** [comment]
有点离谱，试试调整一下 gpt3_params

**Comment by MIKU-N** [comment]
> 有点离谱，试试调整一下 gpt3_params

@lss233 问题就在这，我并没有调整``gpt3_params`` 就存在此问题，我尝试调整了一下``temperature``参数，并没有什么效果

**Comment by lss233** [comment]
你可能要设置一下 max_tokens ? 
我给它默认 3000

**Comment by MIKU-N** [comment]
> 你可能要设置一下 max_tokens ? 我给它默认 3000

@lss233 
![image](https://user-images.githubusercontent.com/61493780/225325950-c8303184-f309-4d3e-aeb0-15137f1dc2d1.png)
设置了，但没什么效果，下面是完整的config配置
```
[mirai]
# Mirai 相关设置

qq = xxxxx

manager_qq = xxxxx

# 以下设置如果不懂 无需理会

api_key = "1234567890" # mirai-http-api 中的 verifyKey
http_url = "http://mirai:8080" # mirai-http-api 中的 http 回调地址
ws_url = "http://mirai:8080"# mirai-http-api 中的 ws 回调地址

# ==== OpenAI 账号部分开始
[openai]

[openai.gpt3_params]
temperature = 1
max_tokens = 3000
top_p = 1
presence_penalty = 1.0
frequency_penalty = -1.0

[[openai.accounts]]
api_key = "sk-LOxxxxxx"
[[openai.accounts]]
api_key = "sk-2Vhxxxxxxx"


# === OpenAI 账号部分结束
# === Bing 设置部分开始
# 如果你没有 Bing 账号，可以直接删除这部分
[bing]
# 第 1 个 Bing 账号
# 理论上，你可以添加无限多个 Bing 账号。  
# 多账号的配置方法和 OpenAI 的一样。
[[bing.accounts]]
# 你的账号 Cookie，获取方法见 README
cookie_content = 'MUID=20CFA2202xxxxx
# === Bing 设置部分结束

[trigger]
# 配置机器人要如何响应，下面所有项均可选 (也就是可以直接删掉那一行)
# 全局聊天前缀，在群聊和私聊中，符合下面的前缀才会响应，可以自己增减
prefix = [ "" ]

# 私聊聊天前缀，在私聊中，符合下面的前缀也会响应，可以自己增减
prefix_friend = [ "","/ask"]

# 群聊聊天前缀，在群聊中，符合下面的前缀也会响应，可以自己增减
prefix_group = [ "" ]

prefix_ai = { "chatgpt-web" = ["gpt"], "bing-p" = ["精确必应"], "bing-c" = ["创造必应"], "bing-b" = ["平衡必应"] }

# AI 画图的前缀
# 需要有 OpenAI 的 api_key 才能使用
prefix_image = ["画", "看"]
# 配置群里如何让机器人响应，"at" 表示需要群里 @ 机器人，"mention" 表示 @ 或者以机器人名字开头都可以，"none" 表示不需要
require_mention = "at"

# 重置会话的命令
reset_command = [ "重置会话" ]

# 回滚会话的命令
rollback_command = [ "回滚会话" ]

# 满足以下正则表达式则忽略此条消息
ignore_regex = []
[response]
# 默认使用的 AI 类型，不填写时自动推测
# 目前支持的类型：
# chatgpt-api: API 版 ChatGPT (GPT3.5-turbo)
default_ai = "chatgpt-api"
# 匹配指令成功但没有对话内容时发送的消息
placeholder = "你好！我是雨，一个由 OpenAI 训练的大型语言模型。我不是真正的人，而是一个计算机程序，可以通过文本聊天来帮助您解决问题。如果您有任何问题，请随时告诉我，我将尽力回答。\n如果您需要重置我们的会话，请回复`重置会话`。"

# 发生错误时要发送的消息
error_format = "出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。\n{exc}"

# 发生网络错误时发送的消息，请注意可以插入 {exc} 作为异常占位符
error_network_failure = "网络故障！连接 OpenAI 服务器失败，我需要更好的网络才能服务！\n{exc}"

# OpenAI 提示 Too many requests（太多请求） 时的提示
error_request_too_many = "糟糕！当前收到的请求太多了，我需要一段时间冷静冷静。你可以选择“重置会话”，或者过一会儿再来找我！\n{exc}"

# 服务器提示 Server overloaded(过载) 时的提示
error_server_overloaded = "抱歉，当前服务器压力有点大，请稍后再找我吧！"

# 是否要回复触发指令的消息
quote = true

# 发送下面那个提醒之前的等待时间
timeout = 30.0

# 超过响应时间时要发送的提醒
timeout_format = "我还在思考中，请再等一下~"

max_timeout = 240

# 超过最长等待时间后发送的信息
cancel_wait_too_long = "啊哦，这个问题有点难，让我想了好久也没想明白。试试换个问法？"

# 重置会话时发送的消息
reset = "会话已重置。"

# 回滚成功时发送的消息
rollback_success = "已回滚至上一条对话，你刚刚发的我就忘记啦！"

# 回滚失败时发送的消息
rollback_fail = "回滚失败，没有更早的记录了！"

# 等待处理的消息的最大数量，如果要关闭此功能，设置为 0
max_queue_size = 10

# 队列满时的提示
queue_full = "抱歉！我现在要回复的人有点多，暂时没有办法接收新的消息了，请过会儿再给我发吧！"

# 新消息加入队列会发送通知的长度最小值
queued_notice_size = 3

# 新消息进入队列时，发送的通知。 queue_size 是当前排队的消息数
queued_notice = "消息已收到！当前我还有{queue_size}条消息要回复，请您稍等。"

[system]
# 是否自动同意进群邀请
accept_group_invite = true

# 是否自动同意好友请求
accept_friend_request = true

[presets]
# 切换预设的命令： 加载预设 猫娘
command = "加载预设 (\\w+)"

loaded_successful = "预设加载成功！"

[presets.keywords]
# 预设关键词 <-> 实际文件
"正常" = "presets/default.txt"
"猫娘" = "presets/catgirl.txt"


[ratelimit]
# 额度限制功能，可以在 wiki 中了解此功能的用法

# 额度使用达到此比例时进行警告
warning_rate = 0.8

# 警告消息
warning_msg = "\n\n警告：额度即将耗尽！\n目前已发送：{usage}条消息，最大限制为{limit}条消息/小时，请调整您的节奏。\n额度限制整点重置，当前服务器时间：{current_time}"

# 超额消息
exceed = "已达到额度限制，请等待下一小时继续和我对话。\n如需更多配额，请联系我的主人！"
```
另外我想问一下，docker-compose部署的话，如何指定容器内的时区呢,TimeZone吗

**Comment by lss233** [comment]
设置时区的话在docker-compose里面通过环境变量指定就可以了。具体操作你可以问 ChatGPT呀

**Comment by byzp** [comment]
> 你可以试试直接把那段
> 
> ```
> [openai.gpt3_params]
> temperature = 1
> max_tokens = 3000
> top_p = 1
> presence_penalty = 1.0
> frequency_penalty = -1.0
> ```
> 
> 删了试试。我这里测试是没有问题的。

我沿用了旧版本的配置文件(4天前的版本)，没有这一段，但是也出现了这样的问题。

**Comment by lss233** [comment]
试试这段配置：
[openai.gpt3_params]
temperature = 0.5
max_tokens = 3000
top_p = 1
presence_penalty = 0.0
frequency_penalty = 0.0

**Comment by MIKU-N** [comment]
> 试试这段配置： [openai.gpt3_params] temperature = 0.5 max_tokens = 3000 top_p = 1 presence_penalty = 0.0 frequency_penalty = 0.0

@lss233  我知道问题出在哪了
经过测试，问题出在``presence_penalty`` 和 ``frequency_penalty `` 这两个配置的值
之前的``presence_penalty = 1.0``与``frequency_penalty = -1.0``指定的不正确
正常的默认值应当是0，也就是说，之前的ReadMe写错了这两个值
![image](https://user-images.githubusercontent.com/61493780/225596003-5e4cd60b-7798-4fdb-9465-afdf48514d0a.png)

![image](https://user-images.githubusercontent.com/61493780/225595815-f1221eed-570b-4cf1-a123-9d2083ac0985.png)
