### ISSUE TITLE
[BUG] 重复出现“Bing 已结束本次会话。继续发送消息将重新开启一个新会话。”

### ISSUE THREAD

**Issue by HE-SI-QI** [lss233/chatgpt-mirai-qq-bot#366]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [ √] 我已看过其他 issue，他们不能解决我的问题 
- [ √] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：Ubuntu
- 项目版本：最新

**复现步骤**  
描述你是如何触发这个 BUG 的
向Bing提问

**截图**  
![SFKAD~M Z4 U~WNQBB$}CC9](https://user-images.githubusercontent.com/69979084/225313808-e10e6220-05d0-44cc-90b1-4d90e68b12a0.png)

chatgpt_1     | 2023-03-15 12:45:11.036 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中<utils.QueueInfo object at 0x7fb92a94ced0>，前面还有 0 个人！
chatgpt_1     | 2023-03-15 12:45:11.036 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
chatgpt_1     | 2023-03-15 12:45:11.037 | DEBUG    | middlewares.timeout:create_timeout_task:12 - [Timeout] 开始计时……
chatgpt_1     | 2023-03-15 12:45:11.247 | ERROR    | adapter.ms.bing:ask:64 - 'messages'
chatgpt_1     | Traceback (most recent call last):
chatgpt_1     | 
chatgpt_1     |   File "/app/bot.py", line 11, in <module>
chatgpt_1     |     import onebot_bot
chatgpt_1     | 
chatgpt_1     |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
chatgpt_1     |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
chatgpt_1     |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
chatgpt_1     |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
chatgpt_1     |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
chatgpt_1     | 
chatgpt_1     |   File "/app/onebot_bot.py", line 183, in <module>
chatgpt_1     |     bot.run(host=config.onebot.reverse_ws_host, port=config.onebot.reverse_ws_port)
chatgpt_1     |     │   │        │      │      │                     │      │      └ 8566
chatgpt_1     |     │   │        │      │      │                     │      └ Onebot(qq=2055068681, manager_qq=3334991525, reverse_ws_host='0.0.0.0', reverse_ws_port=8566)
chatgpt_1     |     │   │        │      │      │                     └ Config(onebot=Onebot(qq=2055068681, manager_qq=3334991525, reverse_ws_host='0.0.0.0', reverse_ws_port=8566), mirai=Mirai(qq=2...
chatgpt_1     |     │   │        │      │      └ '0.0.0.0'
chatgpt_1     |     │   │        │      └ Onebot(qq=2055068681, manager_qq=3334991525, reverse_ws_host='0.0.0.0', reverse_ws_port=8566)
chatgpt_1     |     │   │        └ Config(onebot=Onebot(qq=2055068681, manager_qq=3334991525, reverse_ws_host='0.0.0.0', reverse_ws_port=8566), mirai=Mirai(qq=2...
chatgpt_1     |     │   └ <function CQHttp.run at 0x7fb928c88040>
chatgpt_1     |     └ <aiocqhttp.CQHttp object at 0x7fb913b229d0>
chatgpt_1     | 
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/aiocqhttp/__init__.py", line 222, in run
chatgpt_1     |     self._server_app.run(host=host, port=port, *args, **kwargs)
chatgpt_1     |     │    │           │        │          │      │       └ {'use_reloader': False}
chatgpt_1     |     │    │           │        │          │      └ ()
chatgpt_1     |     │    │           │        │          └ 8566
chatgpt_1     |     │    │           │        └ '0.0.0.0'
chatgpt_1     |     │    │           └ <function Quart.run at 0x7fb928c625c0>
chatgpt_1     |     │    └ <Quart ''>
chatgpt_1     |     └ <aiocqhttp.CQHttp object at 0x7fb913b229d0>
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/quart/app.py", line 1423, in run
chatgpt_1     |     loop.run_until_complete(asyncio.gather(*tasks))
chatgpt_1     |     │    │                  │       │       └ [<Task pending name='Task-1' coro=<serve() running at /usr/local/lib/python3.11/site-packages/hypercorn/asyncio/__init__.py:4...
chatgpt_1     |     │    │                  │       └ <function gather at 0x7fb95ac61b20>
chatgpt_1     |     │    │                  └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>
chatgpt_1     |     │    └ <function BaseEventLoop.run_until_complete at 0x7fb95ac82840>
chatgpt_1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
chatgpt_1     |     self.run_forever()
chatgpt_1     |     │    └ <function BaseEventLoop.run_forever at 0x7fb95ac827a0>
chatgpt_1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
chatgpt_1     |     self._run_once()
chatgpt_1     |     │    └ <function BaseEventLoop._run_once at 0x7fb95ac845e0>
chatgpt_1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
chatgpt_1     |     handle._run()
chatgpt_1     |     │      └ <function Handle._run at 0x7fb95b1f6c00>
chatgpt_1     |     └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
chatgpt_1     |     self._context.run(self._callback, *self._args)
chatgpt_1     |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
chatgpt_1     |     │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt_1     |     │    │            │    └ <member '_callback' of 'Handle' objects>
chatgpt_1     |     │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt_1     |     │    └ <member '_context' of 'Handle' objects>
chatgpt_1     |     └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt_1     | 
chatgpt_1     |   File "/app/onebot_bot.py", line 96, in _
chatgpt_1     |     await handle_message(response, f"friend-{event.user_id}", msg.display, chain)
chatgpt_1     |           │              │                                    │   │        └ MessageChain([Plain(text='hi？')])
chatgpt_1     |           │              │                                    │   └ <property object at 0x7fb913b41d00>
chatgpt_1     |           │              │                                    └ MessageChain([Plain(text='hi？')])
chatgpt_1     |           │              └ <function _.<locals>.response at 0x7fb9135a2480>
chatgpt_1     |           └ <function handle_message at 0x7fb928c896c0>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 155, in handle_message
chatgpt_1     |     await action(session_id, message.strip(), conversation_context, respond)
chatgpt_1     |           │      │           │       │        │                     └ <function handle_message.<locals>.respond at 0x7fb9135a23e0>
chatgpt_1     |           │      │           │       │        └ None
chatgpt_1     |           │      │           │       └ <method 'strip' of 'str' objects>
chatgpt_1     |           │      │           └ 'hi？'
chatgpt_1     |           │      └ 'friend-3334991525'
chatgpt_1     |           └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fb9135a2160>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 47, in call
chatgpt_1     |     await m.handle_request(session_id, message, respond, conversation_context, n)
chatgpt_1     |           │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fb9135a1e40>
chatgpt_1     |           │ │              │           │        │        └ None
chatgpt_1     |           │ │              │           │        └ <function handle_message.<locals>.respond at 0x7fb9135a23e0>
chatgpt_1     |           │ │              │           └ 'hi？'
chatgpt_1     |           │ │              └ 'friend-3334991525'
chatgpt_1     |           │ └ <function MiddlewareConcurrentLock.handle_request at 0x7fb91376ade0>
chatgpt_1     |           └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x7fb92a90c050>
chatgpt_1     | 
chatgpt_1     |   File "/app/middlewares/concurrentlock.py", line 43, in handle_request
chatgpt_1     |     await action(session_id, prompt, conversation_context, respond)
chatgpt_1     |           │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7fb9135a23e0>
chatgpt_1     |           │      │           │       └ None
chatgpt_1     |           │      │           └ 'hi？'
chatgpt_1     |           │      └ 'friend-3334991525'
chatgpt_1     |           └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fb9135a1e40>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 47, in call
chatgpt_1     |     await m.handle_request(session_id, message, respond, conversation_context, n)
chatgpt_1     |           │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fb9135a2520>
chatgpt_1     |           │ │              │           │        │        └ None
chatgpt_1     |           │ │              │           │        └ <function handle_message.<locals>.respond at 0x7fb9135a23e0>
chatgpt_1     |           │ │              │           └ 'hi？'
chatgpt_1     |           │ │              └ 'friend-3334991525'
chatgpt_1     |           │ └ <function Middleware.handle_request at 0x7fb91376a700>
chatgpt_1     |           └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x7fb928c96310>
chatgpt_1     | 
chatgpt_1     |   File "/app/middlewares/middleware.py", line 9, in handle_request
chatgpt_1     |     await action(session_id, prompt, conversation_context, respond)
chatgpt_1     |           │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7fb9135a23e0>
chatgpt_1     |           │      │           │       └ None
chatgpt_1     |           │      │           └ 'hi？'
chatgpt_1     |           │      └ 'friend-3334991525'
chatgpt_1     |           └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fb9135a2520>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 47, in call
chatgpt_1     |     await m.handle_request(session_id, message, respond, conversation_context, n)
chatgpt_1     |           │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fb9135a2700>
chatgpt_1     |           │ │              │           │        │        └ None
chatgpt_1     |           │ │              │           │        └ <function handle_message.<locals>.respond at 0x7fb9135a23e0>
chatgpt_1     |           │ │              │           └ 'hi？'
chatgpt_1     |           │ │              └ 'friend-3334991525'
chatgpt_1     |           │ └ <function MiddlewareRatelimit.handle_request at 0x7fb9136e5440>
chatgpt_1     |           └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x7fb9137719d0>
chatgpt_1     | 
chatgpt_1     |   File "/app/middlewares/ratelimit.py", line 25, in handle_request
chatgpt_1     |     await action(session_id, prompt, conversation_context, respond)
chatgpt_1     |           │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7fb9135a23e0>
chatgpt_1     |           │      │           │       └ None
chatgpt_1     |           │      │           └ 'hi？'
chatgpt_1     |           │      └ 'friend-3334991525'
chatgpt_1     |           └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fb9135a2700>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 47, in call
chatgpt_1     |     await m.handle_request(session_id, message, respond, conversation_context, n)
chatgpt_1     |           │ │              │           │        │        │                     └ <function handle_message.<locals>.request at 0x7fb9135a2660>
chatgpt_1     |           │ │              │           │        │        └ None
chatgpt_1     |           │ │              │           │        └ <function handle_message.<locals>.respond at 0x7fb9135a23e0>
chatgpt_1     |           │ │              │           └ 'hi？'
chatgpt_1     |           │ │              └ 'friend-3334991525'
chatgpt_1     |           │ └ <function MiddlewareTimeout.handle_request at 0x7fb91376bce0>
chatgpt_1     |           └ <middlewares.timeout.MiddlewareTimeout object at 0x7fb928ba6d90>
chatgpt_1     | 
chatgpt_1     |   File "/app/middlewares/timeout.py", line 30, in handle_request
chatgpt_1     |     await action(session_id, prompt, conversation_context, respond)
chatgpt_1     |           │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7fb9135a23e0>
chatgpt_1     |           │      │           │       └ None
chatgpt_1     |           │      │           └ 'hi？'
chatgpt_1     |           │      └ 'friend-3334991525'
chatgpt_1     |           └ <function handle_message.<locals>.request at 0x7fb9135a2660>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 114, in request
chatgpt_1     |     async for rendered in task:
chatgpt_1     |                           └ <async_generator object ConversationContext.ask at 0x7fb9136f5210>
chatgpt_1     | 
chatgpt_1     |   File "/app/conversation.py", line 85, in ask
chatgpt_1     |     async for item in self.adapter.ask(prompt):
chatgpt_1     |                       │    │       │   └ 'hi？'
chatgpt_1     |                       │    │       └ <function BingAdapter.ask at 0x7fb928b9c400>
chatgpt_1     |                       │    └ <adapter.ms.bing.BingAdapter object at 0x7fb913702050>
chatgpt_1     |                       └ <conversation.ConversationContext object at 0x7fb9135a5950>
chatgpt_1     | 
chatgpt_1     | > File "/app/adapter/ms/bing.py", line 46, in ask
chatgpt_1     |     async for final, response in self.bot.ask_stream(prompt=prompt,
chatgpt_1     |                                  │    │   │                 └ 'hi？'
chatgpt_1     |                                  │    │   └ <function Chatbot.ask_stream at 0x7fb928b17740>
chatgpt_1     |                                  │    └ <EdgeGPT.Chatbot object at 0x7fb9135a4ad0>
chatgpt_1     |                                  └ <adapter.ms.bing.BingAdapter object at 0x7fb913702050>
chatgpt_1     | 
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/EdgeGPT.py", line 295, in ask_stream
chatgpt_1     |     async for response in self.chat_hub.ask_stream(
chatgpt_1     |                           │    │        └ <function ChatHub.ask_stream at 0x7fb928b17420>
chatgpt_1     |                           │    └ <EdgeGPT.ChatHub object at 0x7fb912c8f650>
chatgpt_1     |                           └ <EdgeGPT.Chatbot object at 0x7fb9135a4ad0>
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/EdgeGPT.py", line 242, in ask_stream
chatgpt_1     |     yield False, response["arguments"][0]["messages"][0][
chatgpt_1     |                  └ {'type': 1, 'target': 'update', 'arguments': [{'requestId': '81bb66a9-315c-40c0-8138-3ad8b88d9d1b', 'throttling': {'maxNumUse...
chatgpt_1     | 
chatgpt_1     | KeyError: 'messages'
chatgpt_1     | 2023-03-15 12:45:11.745 | DEBUG    | middlewares.timeout:handle_respond:42 - [Timeout] 取消计时……

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
docker-compose pull && docker-compose up -d 更新一下镜像，记得是 browser-version 这个 tag

**Comment by HE-SI-QI** [comment]
好了，谢谢大佬
