### ISSUE TITLE
[BUG] chatgpt-api模式无法正常加载预设

### ISSUE THREAD

**Issue by EnchStudio** [lss233/chatgpt-mirai-qq-bot#368]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [X] 我已看过其他 issue，他们不能解决我的问题 
- [X] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
在chatgpt-api模式无法正常加载预设，控制台报错

**运行环境:**  
- 操作系统：Ubuntu 20.04.5 LTS
- Docker： None
- 项目版本：v2.2.4

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 切换到chatgpt-api
2. 加载预设

**预期行为**  
预设成功被加载

**截图**  
[控制台日志](https://privatebin.net/?f640ed7840e892a9#7UM25tnnGM9Bjfym3uzt6QWeVWBhBJbv8XaXAQXFggcy)

**其他内容**  
None

**Comment by lss233** [comment]
执行 docker-compose pull && docker-compose up -d 更新一下容器

**Comment by Steve0134** [comment]
> p

我是Windows版本，也遇到了这个问题，应该如何操作？

**Comment by lss233** [comment]
v2.2.4.1 已发布，修复预设问题。
