### ISSUE TITLE
[BUG] Bing成功登录后无法回复消息

### ISSUE THREAD

**Issue by 200542053** [lss233/chatgpt-mirai-qq-bot#369]
**提交 issue 前，请先确认：**

- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
Bing登录成功后无法进行对话，发任何消息都回“Bing 已结束本次会话。继续发送消息将重新开启一个新会话。”
重置会话也无效。

**运行环境:**  
- 操作系统：win10
- Docker： 无
- 项目版本：2.2.4（文件名是2.2.3.1只是因为忘了改文件名）

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 登录cqhttp
2. 运行 启动ChatGPT.cmd 
3. 发任何消息给机器人
4. 收到：“Bing 已结束本次会话。继续发送消息将重新开启一个新会话。”

**预期行为**  
正常回复

**截图**  
[日志
](https://pastebin.mozilla.org/MtNhnNEy)[截图](https://user-images.githubusercontent.com/52939604/225329164-a5bc7940-f994-44b8-a213-e17c95f14fda.jpg)

**其他内容**  
试过在pc浏览器和手机的Bing app上都能正常回复

**Comment by lss233** [comment]
日志无法阅读

**Comment by 200542053** [comment]
> 日志无法阅读

重新上传了日志

**Comment by lss233** [comment]
这很奇怪，我看了一下报错的代码位置和实际 2.2.4 版本里代码的位置不一样。  

这可能是由于你没有正确升级导致的，建议你重新下载一次，然后把原来的 config.cfg 移到新的 chatgpt 文件夹进行升级。

**Comment by 200542053** [comment]
> 这很奇怪，我看了一下报错的代码位置和实际 2.2.4 版本里代码的位置不一样。
> 
> 这可能是由于你没有正确升级导致的，建议你重新下载一次，然后把原来的 config.cfg 移到新的 chatgpt 文件夹进行升级。

非常感谢！问题解决了！

我之前把所有文件都删了只留了config.cfg也不行。
这次新建了个文件夹重新解压后就行了，怪
