### ISSUE TITLE
[Feature] New bing可以挂代理吗

### ISSUE THREAD

**Issue by horizon86** [lss233/chatgpt-mirai-qq-bot#370]
ChatGPT没挂代理已经被封号了，new bing可以使用代理吗？在bing账号设置那段里写了个proxy="http://....."好像也没起作用，还是没走代理

**Comment by lss233** [comment]
关于代理的支持正在进行中：https://github.com/acheong08/EdgeGPT/pull/122

**Comment by horizon86** [comment]
> 关于代理的支持正在进行中：[acheong08/EdgeGPT#122](https://github.com/acheong08/EdgeGPT/pull/122)

tql，（~这就去大佬mc服务器里支持支持~悲，刚发现已经关了

**Comment by lss233** [comment]
v2.2.4.1 已发布，加入 Bing 反代。
