### ISSUE TITLE
[BUG] api代理不生效

### ISSUE THREAD

**Issue by QAQLuceQAQ** [lss233/chatgpt-mirai-qq-bot#372]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
api代理不生效

**运行环境:**  
- 操作系统：windows10
- Docker： ？
- 项目版本：v2.2.4

**复现步骤**  
描述你是如何触发这个 BUG 的
未使用全局代理的情况下，可以登录openai服务器但是无法通过代理进行会话，代理软件也没有抓到api相关请求
在使用全局代理情况下，可以登录openai服务器，可以进行会话，并且代理软件抓到相关请求
推测为代理不生效，issue#307的并未修复

**预期行为**  
使用代理链接api

**截图**  
![image](https://user-images.githubusercontent.com/89503747/225358283-b840fa0b-d015-41cf-9bc0-40fdf2481340.png)

**其他内容**  
无

**Comment by lss233** [comment]
有没有可能你的情况和 https://github.com/lss233/chatgpt-mirai-qq-bot/issues/369#issuecomment-1470426941 一样，是没有升级干净导致的？

**Comment by chung1912** [comment]
同样的情况，API代理只有验证登录的时候生效，问问题的时候不会走代理

**Comment by 1045925330** [comment]
+1

**Comment by QAQLuceQAQ** [comment]
我很确定，我是重新部署的，配置文件也重新写过一遍，应该是这个bug未修复的问题

**Comment by chung1912** [comment]
> 我很确定，我是重新部署的，配置文件也重新写过一遍，应该是这个bug未修复的问题

而且我docker下的环境变量设置代理，也不行

**Comment by horizon86** [comment]
改一下代码：

https://github.com/lss233/chatgpt-mirai-qq-bot/blob/5a40bc45ee2dc897c84c71ba8c494257c76305dd/adapter/chatgpt/api.py#L30-L37

添加一个参数：
`proxy=self.api_info.proxy`

**Comment by lss233** [comment]
> 改一下代码：
> 
> https://github.com/lss233/chatgpt-mirai-qq-bot/blob/5a40bc45ee2dc897c84c71ba8c494257c76305dd/adapter/chatgpt/api.py#L30-L37
> 
> 添加一个参数： `proxy=self.api_info.proxy`

可以直接 PR

**Comment by 1045925330** [comment]
![image](https://user-images.githubusercontent.com/30003970/225797296-d7a5d71b-a77b-4cd6-8d54-8b0b8dbf297b.png)
我是直接设置环境变量后就可以用了

**Comment by QAQLuceQAQ** [comment]
好的谢谢

**Comment by Angusvencent** [comment]
> > 改一下代码：
> > https://github.com/lss233/chatgpt-mirai-qq-bot/blob/5a40bc45ee2dc897c84c71ba8c494257c76305dd/adapter/chatgpt/api.py#L30-L37
> > 
> > 添加一个参数： `proxy=self.api_info.proxy`
> 
> 可以直接 PR

请问Linux系统VPS用docker-compose运行的怎么修改代码，找不到本地文件在哪

**Comment by RogersSteve** [comment]
问问题的时候走代理，可以修改一下docker-compose.yaml
添加几行
environment:
      LANG: 'C.UTF-8'
      http_proxy: "http://host.docker.internal:7890"
      https_proxy: "http://host.docker.internal:7890"
extra_hosts:
      - "host.docker.internal:host-gateway"
<img width="719" alt="截屏2024-03-20 10 33 25" src="https://github.com/lss233/chatgpt-mirai-qq-bot/assets/69096042/e0a88297-171b-468b-a265-2a3e426ebfe2">
