### ISSUE TITLE
[BUG]  ('未能使用所配置的账号激活 sessionKey, 请检查 mirai_session 配置.', {'code': 2, 'msg': '指定Bot不存在'})

### ISSUE THREAD

**Issue by yg9538** [lss233/chatgpt-mirai-qq-bot#373]
('未能使用所配置的账号激活 sessionKey, 请检查 mirai_session 配置.', {'code': 2, 'msg': '指定Bot不存在'})

**Comment by lss233** [comment]
这是 aridane 或者 mirai api http 的 BUG，  此提示无需理会。
