### ISSUE TITLE
[BUG] api代理在docker环境下不生效

### ISSUE THREAD

**Issue by chung1912** [lss233/chatgpt-mirai-qq-bot#375]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x]  我已看过其他 issue，他们不能解决我的问题 
- [x]  我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
在docker环境下，配置了api的代理，只有登录验证的时候会通过走代理验证，但是正常问问题的时候，不会走代理
并且不会弹出错误提示，只是超时；
当向机器人问问题的时候，在代理的日志里面并没有任何连接记录，因此确定为没有走代理
issue#307的并未修复

**运行环境:**  
操作系统：linux
Docker： lss233/chatgpt-mirai-qq-bot:browser-version
项目版本：v2.2.4

**截图**  
![000000000-000000000-02972F01C3747889203CE205A4F30BCB](https://user-images.githubusercontent.com/38153111/225495821-50f6cbf8-0bcf-43f8-b09d-1749f2ddd282.png)
等待许久后会发送如上信息

**Comment by lss233** [comment]
duplicated of #372
