### ISSUE TITLE
[BUG] 在图片模式下 Bing 的回复显示不全

### ISSUE THREAD

**Issue by lingboshuiyue** [lss233/chatgpt-mirai-qq-bot#376]
**提交 issue 前，请先确认：**
- [ √] 我已看过 **FAQ**，此问题不在列表中
- [ √] 我已看过其他 issue，他们不能解决我的问题 
- [ √] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
在图片模式下，bing 的回复没有带上相关的来源链接。而在文本模式下则能正常显示。

**运行环境:**  
- 操作系统：CentOS Linux release 8.5.2111
- Docker：Docker version 23.0.1
- 项目版本：v2.2.4

**复现步骤**  
1. 默认以图片模式启动，在 bing 模式下发送提问后，bing 的回复没有带上相应的来源链接。

**预期行为**  
1. 在图片模式下 bing 的回复能带上相关的来源链接。

**截图**  
图片模式下：
![QQ图片20230316103955](https://user-images.githubusercontent.com/24492313/225496204-2c142a64-3911-4c2a-98b7-215b4f62da85.png)
文本模式下：
![Snipaste_2023-03-16_10-42-03](https://user-images.githubusercontent.com/24492313/225496542-493af006-3cef-4219-97d2-4dcad784d178.png)
相关配置：
![image](https://user-images.githubusercontent.com/24492313/225496796-3c83dc21-5aee-4f7b-8ce2-43d4549fb57a.png)

**其他内容**  
无

**Comment by G37H9** [comment]
问一下Linux下面怎么切换成bing啊

**Comment by G37H9** [comment]
问一下大佬Linux怎么从openai切换成new bing啊

**Comment by lingboshuiyue** [comment]
> 

参考 wiki，对话中输入：切换AI bing 就行了。修改默认可以在 config.cfg 中修改 default_ai 项：
[response]
# 默认使用的 AI 类型，不填写时自动推测
# 目前支持的类型：
# chatgpt-web: 网页版 ChatGPT
# chatgpt-api: API 版 ChatGPT (GPT3.5-turbo)
# bing-c: New Bing (新必应对话风格-创造力)
# bing-p: New Bing (新必应对话风格-精确)
# bing-b: New Bing (新必应对话风格-平衡)
default_ai = "bing-p"

**Comment by lss233** [comment]
这个是 Markdown 解析导致的，毕竟图片里的链接也不能点，所以可以扫描二维码查看原文后直接点击。  
这个问题的解决方法应该是采用更好的消息展现发送（如使用 QQ 的转发消息功能）来解决这个问题。

**Comment by lss233** [comment]
现在已经改了链接的样式了，能看见链接了。
