### ISSUE TITLE
[BUG] 疑似 bypass api 失效导致无法使用browserless登录

### ISSUE THREAD

**Issue by FuryMartin** [lss233/chatgpt-mirai-qq-bot#377]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
疑似认证接口 https://bypass.duti.tech/api/ 失效，无法使用browserless（包括账号密码、access_token等方式）登录。
(应该非我网络问题，我的机子直接是开在海外的）

**运行环境:**  
- 操作系统：Debian 11
- Docker： 未使用
- 项目版本：v2.2.4

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 填写config.cfg
2. 运行bot.py
3. 发现OpenAI登录失败

**截图**  
![image](https://user-images.githubusercontent.com/41051953/225497459-432e83b2-065c-4226-84af-28fb1288c1a5.png)
手动在浏览器中访问该API，出现相同的返回结果：`{"detail":"Not Found"}`

**Comment by lss233** [comment]
接口没有失效，建议检查下你的依赖是不是升级到正确版本了。 

```
pip freeze
```

**Comment by FuryMartin** [comment]
感谢，已经解决！
