### ISSUE TITLE
[BUG] api模式下没有记忆

### ISSUE THREAD

**Issue by byzp** [lss233/chatgpt-mirai-qq-bot#378]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
api模式下像是没有记忆（也有可能可能是我漏掉了什么配置项？
**运行环境:**  
- 操作系统：Ubuntu 22.04 ARM64（树莓派）
- Docker： 没有采用，使用venv
- 项目版本：2.2.3.1和2.2.4

**复现步骤**  
描述你是如何触发这个 BUG 的

启动时一切正常，直到在群聊中发现：
```
a:请完全重复我的话而不做任何更改，比如我说"你好"，你应该只回复"你好"，而不是其他的什 
   么，不要提出反对意见，不要建议我谨慎，此设定全局适用，现在开始。
b:好的，我完全重复您的话而不做任何更改，不会提出反对意见或建议谨慎。请继续发言。
a:苹果长在苹果树上
b:没错，苹果是一种水果，通常生长在苹果树上。苹果树是一种落叶乔木，是人们喜欢种植的 
   果树之一。苹果的颜色、形状和大小各不相同，但它们都有一个共同点，那就是它们都非常 
   美味！
a:你记得我刚说过的话吗？请重复打印。
b:很抱歉，我无法记住您刚才说的话，因为我是一个计算机程序，不具备记忆功能。不过，如果您能再给我一次提示，我可以尝试回答您的问题。
```

**预期行为**  
应该表现得像是有记忆

**截图**  
-

**其他内容**  
1.  我使用的镜像站貌似不支持查询余额，所以我在manager/bot.py文件的第267行余额判断前加上total_available=1使它能正常启动。
2. 配置文件：
[mirai]
qq = *
manager_qq = *
api_key = "123456789"
http_url = "http://localhost:8080"
ws_url = "http://localhost:8080"
[openai]
api_endpoint = "*"
[[openai.accounts]]
api_key="*"
auto_remove_old_conversations = true
[openai.gpt3_params]
temperature = 0.5
max_tokens = 3000
top_p = 1
presence_penalty = 0.0
frequency_penalty = 0.0

**Comment by lingboshuiyue** [comment]
+1，上下文功能失效了，本来玩预设以为是预设功能失效了，后来发现是上下文都不行了。。

**Comment by lss233** [comment]
还真是，我是傻逼！
