### ISSUE TITLE
[BUG] 只填写Bing的情况下无法使用

### ISSUE THREAD

**Issue by Leo01234** [lss233/chatgpt-mirai-qq-bot#379]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
v2.2.4删除openai相关配置后报错

```
Traceback (most recent call last):
   File "/app/bot.py", line 8, in <module>
     from constants import config
   File "/app/constants.py", line 7, in <module>
     botManager = BotManager(config)
                  ^^^^^^^^^^^^^^^^^^
   File "/app/manager/bot.py", line 48, in __init__
     if config.openai.browserless_endpoint:
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'NoneType' object has no attribute 'browserless_endpoint'
 /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
   return _Gtk_main(*args, **kwargs)
```

**运行环境:**  
- 操作系统：ubuntu22.04
- Docker： Docker version 23.0.1, Docker Compose version v2.16.0
- 项目版本：v2.2.4

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 更新至最新版本
2. 删除配置文件中openai有关内容
3. docker compose up -d

**预期行为**  
可以正常使用new bing

**其他内容**  
添加openai.browserless_endpoint配置信息后会报找不到openai账号的错误

_Originally posted by @Leo01234 in https://github.com/lss233/chatgpt-mirai-qq-bot/issues/363#issuecomment-1471309042_

**Comment by benzcls63amg** [comment]
我试了一下，不删除openai登录部分·的代码bing就可以运行。注释掉openai部分就异常
