### ISSUE TITLE
[BUG] Telegram Bot 在闲置一段时间后运行异常

### ISSUE THREAD

**Issue by lingboshuiyue** [lss233/chatgpt-mirai-qq-bot#380]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
使用 Telegram Bot 协议，开始时对话正常，闲置一段时间（几分钟或半小时）后控制台报错，继续对话则被阻塞住无响应，待重启后 bot 才会回复之前的问题。

**运行环境:**  
- 操作系统：CentOS Linux release 8.5.2111
- Docker： Docker version 23.0.1
- 项目版本：v2.2.4

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 使用 telegram bot 协议
2. bot 在闲置一段时间（几分钟或半小时）后控制台报错

**预期行为**  
1. telegram bot 在闲置一段时间后也能正常进行对话。

**截图&日志**
 bot 配置：
![Snipaste_2023-03-16_14-34-35](https://user-images.githubusercontent.com/24492313/225534451-1d8b42d0-99c4-4478-adae-feb83b6830b1.png)

对话截图：
![Snipaste_2023-03-16_14-49-27](https://user-images.githubusercontent.com/24492313/225538014-33931896-8df4-4f7b-a6f8-d445d5155f0e.png)

错误日志：
[error.txt](https://github.com/lss233/chatgpt-mirai-qq-bot/files/10987472/error.txt)

**其他内容**  
无

**Comment by lss233** [comment]
似乎和 https://github.com/python-telegram-bot/python-telegram-bot/issues/3556 有关，我切到 http 1.1 吧

**Comment by ling6668** [comment]
我也是闲置一段时间大概半小时后就不会回复了，端口也没显示接收到消息

**Comment by lingboshuiyue** [comment]
> 我也是闲置一段时间大概半小时后就不会回复了，端口也没显示接收到消息
我后面 http 协议降级到 1.1 后还会出现同样的问题，最后定位到是 vpn 的问题，telegram bot 为维持连接每隔一段时间都会发送心跳检测，我的 vpn 时不时抽风，经常会导致 timeout 超时从而断开与 telegram 的连接，你如果用的是 vpn 的话可以查下访问日志有没有报错，如果你用的是海外的服务器的话当我没说。
