### ISSUE TITLE
[BUG] 无法连接代理服务器

### ISSUE THREAD

**Issue by VastCosmic** [lss233/chatgpt-mirai-qq-bot#381]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√ ] 我已看过其他 issue，他们不能解决我的问题 
- [√ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
docker环境，使用apikey，
无法连接至代理服务器，
登陆不了openai账号，
代理服务器经postman测试没有问题

**运行环境:**  
- 操作系统：Ubuntu Server 20.04 LTS 64bit
- Docker： 20.10.21
- 项目版本: 2.2.4

***********************************************
graia-amnesia: 0.7.1
chatgpt_1     | graia-ariadne: 0.11.1
chatgpt_1     | graia-broadcast: 0.19.2
chatgpt_1     | launart: 0.6.3
chatgpt_1     | statv: 0.3.2
chatgpt_1     | 2023-03-16 09:07:34.184 | INFO     | launart.manager:_launchable_task_done_callback:68 - [elizabeth.connection.1612324756.websocket_server_connection] completed.
chatgpt_1     | 2023-03-16 09:07:34.185 | INFO     | graia.amnesia.builtins.aiohttp:launch:513 - starting server on 0.0.0.0:8554
chatgpt_1     | 2023-03-16 09:07:34.186 | SUCCESS  | launart.manager:launch:384 - Layer #1:[cache.client/memcache, http.server/aiohttp, http.client/aiohttp] preparation completed.
chatgpt_1     | 2023-03-16 09:07:34.186 | INFO     | ariadne_bot:start_background:129 - OpenAI 服务器登录中……
chatgpt_1     | 2023-03-16 09:07:34.187 | INFO     | manager.bot:login_openai:110 - 正在登录第 1 个 OpenAI 账号
chatgpt_1     | 2023-03-16 09:07:34.187 | INFO     | manager.bot:__login_openai_apikey:260 - 尝试使用 api_key 登录中...
chatgpt_1     | 2023-03-16 09:07:34.188 | INFO     | manager.bot:__check_proxy:174 - [代理测试] 正在检查代理配置：https://service-pc1nw098-(马赛克).hk.apigw.tencentcs.com
chatgpt_1     | 2023-03-16 09:07:34.188 | ERROR    | manager.bot:login_openai:140 - 未知错误：
chatgpt_1     | 2023-03-16 09:07:34.188 | ERROR    | manager.bot:login_openai:141 - 登录失败! 无法连接至本地代理服务器，请检查配置文件中的 proxy 是否正确！
chatgpt_1     | Traceback (most recent call last):
chatgpt_1     | 
chatgpt_1     |   File "/app/bot.py", line 17, in <module>
chatgpt_1     |     import ariadne_bot
chatgpt_1     | 
chatgpt_1     |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
chatgpt_1     |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
chatgpt_1     |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
chatgpt_1     |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
chatgpt_1     |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
chatgpt_1     | 
chatgpt_1     |   File "/app/ariadne_bot.py", line 199, in <module>
chatgpt_1     |     app.launch_blocking()
chatgpt_1     |     │   └ <classmethod(<function Ariadne.launch_blocking at 0x7fe373f2bd80>)>
chatgpt_1     |     └ <graia.ariadne.app.Ariadne object at 0x7fe3804d5fd0>
chatgpt_1     | 
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/graia/ariadne/app.py", line 312, in launch_blocking
chatgpt_1     |     cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
chatgpt_1     |     │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
chatgpt_1     |     │   │              │                    │   │       └ <property object at 0x7fe373f32c50>
chatgpt_1     |     │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x7fe3ac09a150>
chatgpt_1     |     │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
chatgpt_1     |     │   │              └ <function Launart.launch_blocking at 0x7fe380313100>
chatgpt_1     |     │   └ <launart.manager.Launart object at 0x7fe3804c7410>
chatgpt_1     |     └ <class 'graia.ariadne.app.Ariadne'>
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/launart/manager.py", line 494, in launch_blocking
chatgpt_1     |     loop.run_until_complete(launch_task)
chatgpt_1     |     │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /usr/local/lib/python3.11/site-packages/launart/manager...
chatgpt_1     |     │    └ <function BaseEventLoop.run_until_complete at 0x7fe3b053a840>
chatgpt_1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
chatgpt_1     |     self.run_forever()
chatgpt_1     |     │    └ <function BaseEventLoop.run_forever at 0x7fe3b053a7a0>
chatgpt_1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
chatgpt_1     |     self._run_once()
chatgpt_1     |     │    └ <function BaseEventLoop._run_once at 0x7fe3b053c5e0>
chatgpt_1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
chatgpt_1     |     handle._run()
chatgpt_1     |     │      └ <function Handle._run at 0x7fe3b0aaec00>
chatgpt_1     |     └ <Handle <TaskStepMethWrapper object at 0x7fe373038520>()>
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
chatgpt_1     |     self._context.run(self._callback, *self._args)
chatgpt_1     |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
chatgpt_1     |     │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7fe373038520>()>
chatgpt_1     |     │    │            │    └ <member '_callback' of 'Handle' objects>
chatgpt_1     |     │    │            └ <Handle <TaskStepMethWrapper object at 0x7fe373038520>()>
chatgpt_1     |     │    └ <member '_context' of 'Handle' objects>
chatgpt_1     |     └ <Handle <TaskStepMethWrapper object at 0x7fe373038520>()>
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/graia/broadcast/__init__.py", line 191, in Executor
chatgpt_1     |     result = await run_always_await(target_callable, **parameter_compile_result)
chatgpt_1     |                    │                │                  └ {}
chatgpt_1     |                    │                └ <function start_background at 0x7fe373012b60>
chatgpt_1     |                    └ <function run_always_await at 0x7fe3803316c0>
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/graia/broadcast/utilles.py", line 34, in run_always_await
chatgpt_1     |     obj = await obj
chatgpt_1     |                 └ <coroutine object start_background at 0x7fe373ea1220>
chatgpt_1     | 
chatgpt_1     |   File "/app/ariadne_bot.py", line 130, in start_background
chatgpt_1     |     botManager.login()
chatgpt_1     |     │          └ <function BotManager.login at 0x7fe3af78a200>
chatgpt_1     |     └ <manager.bot.BotManager object at 0x7fe3805ad2d0>
chatgpt_1     | 
chatgpt_1     |   File "/app/manager/bot.py", line 73, in login
chatgpt_1     |     self.login_openai()
chatgpt_1     |     │    └ <function BotManager.login_openai at 0x7fe38046f880>
chatgpt_1     |     └ <manager.bot.BotManager object at 0x7fe3805ad2d0>
chatgpt_1     | 
chatgpt_1     | > File "/app/manager/bot.py", line 113, in login_openai
chatgpt_1     |     bot = self.__login_openai_apikey(account)
chatgpt_1     |           │                          └ OpenAIAPIKey(mode='browserless', proxy='https://service-pc1nw098-(马赛克).hk.apigw.tencentcs.com', driver_exec_path=None, b...
chatgpt_1     |           └ <manager.bot.BotManager object at 0x7fe3805ad2d0>
chatgpt_1     | 
chatgpt_1     |   File "/app/manager/bot.py", line 261, in __login_openai_apikey
chatgpt_1     |     if proxy := self.__check_proxy(account.proxy):
chatgpt_1     |                 │                  │       └ 'https://service-pc1nw098-1313154504.hk.apigw.tencentcs.com'
chatgpt_1     |                 │                  └ OpenAIAPIKey(mode='browserless', proxy='https://service-pc1nw098-(马赛克).hk.apigw.tencentcs.com', driver_exec_path=None, b...
chatgpt_1     |                 └ <manager.bot.BotManager object at 0x7fe3805ad2d0>
chatgpt_1     | 
chatgpt_1     |   File "/app/manager/bot.py", line 177, in __check_proxy
chatgpt_1     |     raise Exception("登录失败! 无法连接至本地代理服务器，请检查配置文件中的 proxy 是否正确！")
chatgpt_1     | 
chatgpt_1     | Exception: 登录失败! 无法连接至本地代理服务器，请检查配置文件中的 proxy 是否正确！
chatgpt_1     | 2023-03-16 09:07:34.196 | SUCCESS  | manager.bot:login_openai:144 - 成功登录 0/1 个 OpenAI 账号！
chatgpt_1     | 2023-03-16 09:07:34.197 | ERROR    | manager.bot:login:76 - 没有登录成功的账号，程序无法启动！
chatgpt_1     | 2023-03-16 09:07:34.197 | ERROR    | ariadne_bot:start_background:132 - OpenAI 服务器登录失败！
chatgpt_1     | /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
chatgpt_1     |   return _Gtk_main(*args, **kwargs)
chatgpt_1     | 2023-03-16 09:07:34,372 child 'xterm -e 'python bot.py 2>&1 | tee /tmp/log.txt'' with pid 44 has terminated
chatgpt_1     | 2023-03-16 09:07:34,372 all children have exited and --exit-with-children was specified, exiting
chatgpt_1     | 2023-03-16 09:07:34,373 xpra X11 seamless server is terminating
chatgpt_1     | 2023-03-16 09:07:34,398 closing tcp socket '0.0.0.0:14500'
chatgpt_1     | 2023-03-16 09:07:34,399 removing unix domain socket '/run/user/1000/xpra/213a782f62ed-0'
chatgpt_1     | 2023-03-16 09:07:34,399 removing unix domain socket '/tmp/0/socket'
chatgpt_1     | 2023-03-16 09:07:34,400 killing xvfb with pid 12
chatgpt-qq_chatgpt_1 exited with code 1

**Comment by VastCosmic** [comment]
[IMG_20230316_172146](https://vc-image-1313154504.cos.ap-shanghai.myqcloud.com/image/202303161722056.png)

**Comment by horizon86** [comment]
用个正常的http代理试试，https是不是不支持

**Comment by lss233** [comment]
建议自查，我这里无法复现

**Comment by ZKfun** [comment]
> 理 蚌

curl测试了连接openai  ,服务器换过公网ip   还是一样的bug

**Comment by lss233** [comment]
你可以在代理后面指定端口号试试。

**Comment by lss233** [comment]
你写的这个东西应该是 api_endpoint，而不是代理。
