### ISSUE TITLE
[BUG] Bing 出错不能用

### ISSUE THREAD

**Issue by joe12801** [lss233/chatgpt-mirai-qq-bot#387]
**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：debian
- Docker： 是
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的

![image](https://user-images.githubusercontent.com/70465495/226056007-f89fa990-6040-4a45-ae12-c76999d1ce83.png)

**Comment by lss233** [comment]
检查一下你的cookie 是不是有问题，重新登录bing拿一下cookie。要把所有的bing cookie都写在配置文件里面

**Comment by joe12801** [comment]
找到 控制台（或 Console），输入 document.cookie 然后回车,我是用这个命令获取取的

**Comment by linxp001** [comment]
> 检查一下你的cookie 是不是有问题，重新登录bing拿一下cookie。要把所有的bing cookie都写在配置文件里面

我也遇到同样的错误，重新拿了一下cookie，解决了。

**Comment by yasurido** [comment]
同样的错误，重新登录拿cookie也没解决TT，给GPT看了代码好像说是身份验证的问题？机器人没有访问权限

**Comment by IanChen0713** [comment]
好像是微软封ip了，我的账号是没问题的，但是用这个ip当梯子开全局始终转跳到cnbing，换个别的ip就能进newbing，并且能聊天

**Comment by benzcls63amg** [comment]
我也是重拿了cookie也不行，账号还能用网页版。我也认为可能是楼上说的封IP

**Comment by meixiayvmeiyisi** [comment]
感觉应该不是封IP，相同的代理 相同的cookie，使用“https://github.com/acheong08/EdgeGPT”没问题，但是这个就会提示Authentication failed. You have not been accepted into the beta.

**Comment by Yoak3n** [comment]
用的自己在国外的服务器，是封ip几率很小
重新拿了几次cookie还是同样的提示，最重要的是用的自己那台服务器的ip在本地（用另一个清空了缓存的浏览器）是可以登录并使用的，基本排除封ip的可能

**Comment by IanChen0713** [comment]
是这样的，我的服务器在洛杉矶，然后我发现这个问题之后重新抓了几次cookie都不行，docker也更新了。然后我尝试使用这台服务器架了个梯子，但是无论怎么开全局始终都是转跳cnbing，换个梯子节点就完美解决该问题。

**Comment by Yoak3n** [comment]
> 是这样的，我的服务器在洛杉矶，然后我发现这个问题之后重新抓了几次cookie都不行，docker也更新了。然后我尝试使用这台服务器架了个梯子，但是无论怎么开全局始终都是转跳cnbing，换个梯子节点就完美解决该问题。

换个梯子节点是指服务器换个节点？暂且理解为本地换个梯子节点。
这有一定可能是浏览器缓存的问题，导致了你用自己服务器的ip仍然跳转cnbing。

问题是，我用自己服务器架的梯子，全局模式下**在本地（用另一个清空了缓存的浏览器**）是可以登录并使用的，和你说的情况不一样，也就基本排除了我自己节点出问题的可能性，至少我的这个ip应该没被限制浏览器使用。

我把从上述流程中获得的cookie放入国外那台服务器上运行的程序后，还是同样的提示，没有设置代理的情况下，除了newBing，chatgpt的api和网页版都能用。
之后搬到本地挂代理运行再试试看吧……

**Comment by IanChen0713** [comment]
> > 是这样的，我的服务器在洛杉矶，然后我发现这个问题之后重新抓了几次cookie都不行，docker也更新了。然后我尝试使用这台服务器架了个梯子，但是无论怎么开全局始终都是转跳cnbing，换个梯子节点就完美解决该问题。
> 
> 
> 
> 换个梯子节点是指服务器换个节点？暂且理解为本地换个梯子节点。
> 
> 这有一定可能是浏览器缓存的问题，导致了你用自己服务器的ip仍然跳转cnbing。
> 
> 
> 
> 问题是，我用自己服务器架的梯子，全局模式下**在本地（用另一个清空了缓存的浏览器**）是可以登录并使用的，和你说的情况不一样，也就基本排除了我自己节点出问题的可能性，至少我的这个ip应该没被限制浏览器使用。
> 
> 
> 
> 我把从上述流程中获得的cookie放入国外那台服务器上运行的程序后，还是同样的提示，没有设置代理的情况下，除了newBing，chatgpt的api和网页版都能用。
> 
> 之后搬到本地挂代理运行再试试看吧……

是本地梯子节点，cookie缓存我都是清除过的 但是不起作用 尝试了dev版本的edge 无痕浏览 修改header 都不行 只有更换其他节点才能正常进入newbing。但是我并不知道是否可以通过限制对应ip强制转跳到cnbing 网上也没有看到这样的案例所以我不确定是否是ip被禁。在使用方面我也没有违规行为使用频率也不高...chatgpt我是被封了网页端ip的但是可以用api进行对话

**Comment by wanleya** [comment]
我也遇到了这个问题，用同样的cookie，使用https://github.com/acheong08/EdgeGPT是正常的，应该也不是IP被锁，因为两个项目是在同一个机器上面使用的。

**Comment by jiangyuyi** [comment]
> 我也遇到了这个问题，用同样的cookie，使用[https://github.com/acheong08/EdgeGPT是正常的，应该也不是IP被锁，因为两个项目是在同一个机器上面使用的。](https://github.com/acheong08/EdgeGPT%E6%98%AF%E6%AD%A3%E5%B8%B8%E7%9A%84%EF%BC%8C%E5%BA%94%E8%AF%A5%E4%B9%9F%E4%B8%8D%E6%98%AFIP%E8%A2%AB%E9%94%81%EF%BC%8C%E5%9B%A0%E4%B8%BA%E4%B8%A4%E4%B8%AA%E9%A1%B9%E7%9B%AE%E6%98%AF%E5%9C%A8%E5%90%8C%E4%B8%80%E4%B8%AA%E6%9C%BA%E5%99%A8%E4%B8%8A%E9%9D%A2%E4%BD%BF%E7%94%A8%E7%9A%84%E3%80%82)

我也遇到了一样的问题，也试了EdgeGPT是正常的，同样的代理/机器和cookie，个人感觉可能代理模式有bug，目前能用的小伙伴大概率是直接放在境外vps上的

**Comment by linxp001** [comment]
> 我也遇到了这个问题，用同样的cookie，使用[https://github.com/acheong08/EdgeGPT是正常的，应该也不是IP被锁，因为两个项目是在同一个机器上面使用的。](https://github.com/acheong08/EdgeGPT%E6%98%AF%E6%AD%A3%E5%B8%B8%E7%9A%84%EF%BC%8C%E5%BA%94%E8%AF%A5%E4%B9%9F%E4%B8%8D%E6%98%AFIP%E8%A2%AB%E9%94%81%EF%BC%8C%E5%9B%A0%E4%B8%BA%E4%B8%A4%E4%B8%AA%E9%A1%B9%E7%9B%AE%E6%98%AF%E5%9C%A8%E5%90%8C%E4%B8%80%E4%B8%AA%E6%9C%BA%E5%99%A8%E4%B8%8A%E9%9D%A2%E4%BD%BF%E7%94%A8%E7%9A%84%E3%80%82)

最新版本已经改成EdgeGPT了，我升级到最新版好使了。
