### ISSUE TITLE
[BUG?] 关于群组的触发响应前缀问题

### ISSUE THREAD

**Issue by Muziyun0010** [lss233/chatgpt-mirai-qq-bot#388]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况
最新版本的前缀识别似乎有些问题,我不知道这个问题是只有我存在还是普遍存在,但在检查代码后我发现了可行的暂时修补方法。
因为我用的是gochttp登录所以mirai有没有这方面的问题也不清楚。

**运行环境:**  
- 操作系统：Windows10
- Docker： 无
- 项目版本：2.2.4.1

**复现步骤**  
描述你是如何触发这个 BUG 的
尝试添加多个前缀触发词

**预期行为**  
描述你认为正常情况下应该看见的情况
在我提到任意触发词时可以收到回复

**截图**  
![image](https://user-images.githubusercontent.com/127690470/226073665-a4d2fe18-80c4-4f2a-ac0e-92acf741b06e.png)

**其他内容**  
修改了one-bot.py文件中的循环之后实现了本来的效果,基于自身的需求添加了后缀唤醒功能(没学过python用了很暴力的方法,暂时可行)似乎在用for循环数组内容超过两个时判断会出现问题(?不清楚)希望可以帮忙解答疑问或者给出更好的解决方案。

**Comment by lss233** [comment]
所以到底是什么问题

**Comment by Muziyun0010** [comment]
当我试图通过编写config文件里的前缀参数唤醒机器人时,并不能得到正确的响应

**Comment by Robop1** [comment]
你说的这个我也遇到了，我添加了一个在群内开关自由回复的命令。

首先在代码开始时添加一个字典:

free_reply_groups = {}

然后替换原有的GroupTrigger：

async def group_trigger(chain: MessageChain, event: Event) -> Optional[MessageChain]:
    if event.group_id in free_reply_groups:
        return chain
    else:
        try:
            for it in [MentionMe(config.trigger.require_mention != "at"), DetectPrefix(
                config.trigger.prefix + config.trigger.prefix_group)]:
                chain = await it(chain, event)
        except:
            logger.debug(f"丢弃群聊消息：{event.message}（原因：不符合触发前缀）")
            return
    return chain

最后在 bot.on_message('group') 事件处理器添加一个新的条件来处理 .开始自由回复 和 .关闭自由回复 指令下面是修改好的代码:

@bot.on_message('group')
async def _(event: Event):
    # 处理 .开始自由回复 和 .关闭自由回复
    if event.message.strip() == ".开启自由回复":
        if event.user_id != config.onebot.manager_qq:
            return await bot.send(event, "您没有权限执行这个操作")
        free_reply_groups[event.group_id] = True
        return await bot.send(event, "已开启自由回复！")
    elif event.message.strip() == ".关闭自由回复":
        if event.user_id != config.onebot.manager_qq:
            return await bot.send(event, "您没有权限执行这个操作")
        free_reply_groups.pop(event.group_id, None)
        return await bot.send(event, "已关闭自由回复！")

    # 处理其他消息
    chain = transform_message_chain(event.message)
    chain = await group_trigger(chain, event)
    if not chain:
        return

    logger.debug(f"群聊消息：{event.message}")

    await handle_message(
        response(event, True),
        f"group-{event.group_id}",
        chain.display,
        is_manager=event.user_id == config.onebot.manager_qq,
        nickname=event.sender.get("nickname", "群友")
    )

这样在群内发送.开启自由回复时，机器人就会回复任何消息，.关闭自由回复时机器人就只会回复被@的消息了😁
