### ISSUE TITLE
[Feature] 希望能让 QQ 和 Telegram Bot 可在一个实例中被同时支持

### ISSUE THREAD

**Issue by Bejukoro** [lss233/chatgpt-mirai-qq-bot#393]
如题

**Comment by lss233** [comment]
之后会考虑。  
其实你可以通过修改 bot.py 来实现这个功能

**Comment by shyu216** [comment]
hi, 我打算用socket解决，在chatgpt开一个服务器，然后不同平台，或者不同账号作为客户端连接。作者大大觉得这个方法怎么样，或是有什么建议吗。

**Comment by lss233** [comment]
我觉得你可以这样：
https://github.com/lss233/chatgpt-mirai-qq-bot/blob/9f6b4bcd291e4ae0178114ceb4fa2a2d56456be0/bot.py#L22-L23

**Comment by shyu216** [comment]
> 我觉得你可以这样：
> 
> https://github.com/lss233/chatgpt-mirai-qq-bot/blob/9f6b4bcd291e4ae0178114ceb4fa2a2d56456be0/bot.py#L22-L23

有道理，我试试，感谢

**Comment by lss233** [comment]
v2.3.0 已支持。
