### ISSUE TITLE
[Feature] 那个......百度的文心一言也发布了，要不要......

### ISSUE THREAD

**Issue by horizon86** [lss233/chatgpt-mirai-qq-bot#394]
RT（）

**Comment by lss233** [comment]
你给我个 API Key?

**Comment by HinataYiacc** [comment]
![123](https://user-images.githubusercontent.com/38227422/226124503-ba4ddbb5-c8cb-4aa2-98d2-378e73c32ed7.png)

**Comment by HinataYiacc** [comment]
文心一言
![GGH Y6)A MI8CQOV3XXE@F1](https://user-images.githubusercontent.com/38227422/226124594-7e60b1d1-7952-44a5-9b04-5c010714c4c0.png)

**Comment by horizon86** [comment]
> 你给我个 API Key?

api还没开放，只有网页。yiyan.baidu.com申请，大概一天会有:)文心是多模态的，可以生成图片

**Comment by lss233** [comment]
v2.2.5-rc1 加入了文心一言的支持，可以来试试。

**Comment by horizon86** [comment]
> v2.2.5-rc1 加入了文心一言的支持，可以来试试。

不行，网页可以用，但是qq让登录

![image](https://user-images.githubusercontent.com/49552732/227761533-7beb1b93-b7d9-4641-91a3-047497b5351e.png)
