### ISSUE TITLE
[Feature] 希望能实现文本模式与图片模式的自动切换

### ISSUE THREAD

**Issue by Winnie0408** [lss233/chatgpt-mirai-qq-bot#395]
希望能实现：当使用纯文本模式时，若检测到回复的内容中有Markdown语法或者LaTex语法时，能够自动将本次的回答临时切换为图片格式。

**Comment by lss233** [comment]
v2.2.5-alpha 加入了图文混合模式，支持在检测到富文本的时候把当前段落切换至图片格式。

**Comment by shuyaoyao** [comment]
> v2.2.5-alpha 加入了图文混合模式，支持在检测到富文本的时候把当前段落切换至图片格式。

目前会出现一段连续的文本回复变成文字+图片+文字的形式

**Comment by lanybass** [comment]
大哥,我不想要自动啊,我已经配置了 mode= "force-text" 也没用,还是会有图片,怎么去掉图片?

**Comment by Winnie0408** [comment]
> 大哥,我不想要自动啊,我已经配置了 mode= "force-text" 也没用,还是会有图片,怎么去掉图片?

@lanybass 
wiki中有详细的设置方法，还请您仔细阅读~

![Screenshot_2023-04-05-17-28-36-356_com.android.browser.jpg](https://user-images.githubusercontent.com/42741874/230040809-330f8372-7d6e-4107-b8a5-53b6356dd648.jpg)

![Screenshot_2023-04-05-17-28-55-418_com.android.browser.jpg](https://user-images.githubusercontent.com/42741874/230040842-f82674fd-59cf-4b9a-80ad-ac2d0fdfcd23.jpg)

**Comment by lanybass** [comment]
@Winnie0408 谢谢...我看过,只是没看到 最后张图片这段.
最后去看源码发现是 text
