### ISSUE TITLE
docker 容器启动报错

### ISSUE THREAD

**Issue by Xxpain** [lss233/chatgpt-mirai-qq-bot#40]
![image](https://user-images.githubusercontent.com/44777634/207088112-f16c67ee-831b-4e93-9ebe-debf74cc6971.png)
![image](https://user-images.githubusercontent.com/44777634/207088184-47e5a040-19b5-4355-ae21-5816572a6f1c.png)

拉取的最新镜像启动报错，不太懂这个是为啥，求助一下 😥

**Comment by lss233** [comment]
`session_token` 有问题，重新拿一个。

**Comment by znhooo** [comment]
> `session_token` 有问题，重新拿一个。

![image](https://user-images.githubusercontent.com/89447619/207251089-10a60022-d011-4b10-a001-f8bd1b299e87.png)
我这个是为什么

**Comment by Xxpain** [comment]
![image](https://user-images.githubusercontent.com/44777634/207317708-b8197104-fcbb-40e1-aa12-73f287dd8fa9.png)
换了个token，跟楼上一样了，我看 dockerfile 里好像有写命令在容器内内嵌了个chrome，应该不需要我再去在弄一个吧
