### ISSUE TITLE
[Feature] 希望大家能在同一个GPT会话中交流，而不是按照各自的QQ号分开

### ISSUE THREAD

**Issue by timeance** [lss233/chatgpt-mirai-qq-bot#400]
有时候想在群里玩coc 让GPT担任kp，希望大家能在同一个GPT会话中交流，而不是按照各自的QQ号分开（也就是按群分会话）

另外，能否增加一个私聊白名单，以防止有人滥用私聊？

**Comment by lss233** [comment]
v2.2.4.2 已修复。  
白名单功能可以参考：https://github.com/lss233/chatgpt-mirai-qq-bot/wiki/%F0%9F%A7%B5-%E9%A2%9D%E5%BA%A6%E9%99%90%E5%88%B6-&-%E9%BB%91%E7%99%BD%E5%90%8D%E5%8D%95
