### ISSUE TITLE
[Feature] 希望增加语音回复功能，在另一个qbot项目中看到了实现， 但是他的项目其他功能太少

### ISSUE THREAD

**Issue by Steve0134** [lss233/chatgpt-mirai-qq-bot#403]
https://lucent.blog/?p=151
自己测试了是可以用的。

接口也很方便
本来想自己折腾出来，结果自己半吊子python水平想要自己改造实在太难，但是理论上应该会很简单。

**Comment by lss233** [comment]
duplicated of #204
