### ISSUE TITLE
docker镜像browser-version版本，Mirai与Chatgpt连接问题

### ISSUE THREAD

**Issue by Astro-Lee** [lss233/chatgpt-mirai-qq-bot#404]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [X] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  

- Mirai
![image](https://user-images.githubusercontent.com/61745903/226650921-4454c8a8-264b-4c7f-867d-d97c9adf9474.png)
- chatgpt
![image](https://user-images.githubusercontent.com/61745903/226648218-ca666be3-7a4f-4c76-8755-aa700b41122b.png)

**运行环境:**  
- 操作系统：Almalinux 9
- Docker： v23.0.1
- 项目版本：browser-version

**复现步骤**  
`docker compose up -d`

**预期行为**  
正常连接

**描述**
刚才更新了一下镜像就报错了  

**其他内容**  
- `docker-compose.yaml`
![image](https://user-images.githubusercontent.com/61745903/226649840-2cbf6c4c-a7b1-4a03-9664-7131d5bb9f7d.png)

- `config.cfg`
![image](https://user-images.githubusercontent.com/61745903/226650032-e9bca66b-7849-4720-bef0-82ba7831d2cc.png)

- `mirai/config/net.mamoe.mirai-api-http/setting.yml`
![image](https://user-images.githubusercontent.com/61745903/226652252-c87cadda-4730-4668-a734-0572a6cce70c.png)

**Comment by lss233** [comment]
建议你读一下图片里 chatgpt 日志的那几句中文提示。

**Comment by Astro-Lee** [comment]
mirai和chatgpt都在同一个服务器上，用正向代理没错吧？
