### ISSUE TITLE
在混合模式不会回复消息原文

### ISSUE THREAD

**Issue by fjaokdp** [lss233/chatgpt-mirai-qq-bot#409]
在群聊图文混合模式不会回复消息原文而是直接发送消息到群聊，不能定位到消息原文在分段发送的时候可能会造成混乱，阅读困难

**Comment by LittIeRed** [comment]
而且富文本的判定好像也有点问题，我只是正常和扮演的角色闲聊一些没什么营养的东西，部分回答会转成图片发送，分段能不能单独做成一个选项，不和混合模式绑定呢

**Comment by lss233** [comment]
已确认此问题，下版本修复

**Comment by lss233** [comment]
v2.2.5-beta 已发布，修复此问题。
