### ISSUE TITLE
这种情况该如何处理“from chrome not reachable”

### ISSUE THREAD

**Issue by R1nkwh** [lss233/chatgpt-mirai-qq-bot#41]
![image](https://user-images.githubusercontent.com/111223971/207093470-e620be5e-27f5-4d4f-8db3-e36f4a34db12.png)
chrome chromedriver Xvfb均已安装

**Comment by lss233** [comment]
多试试？
你可以反馈这个问题给 https://github.com/acheong08/ChatGPT/issues/261

**Comment by R1nkwh** [comment]
okok

**Comment by R1nkwh** [comment]
很奇怪，我将mirai-api-https的端口设置为8080后，并且重启云服务器后，允许bot.py有概率成功，现在可以使用了，但有时候会报错httpx:readTimeout
