### ISSUE TITLE
[BUG] Bing 在新的混合模式下输出有问题

### ISSUE THREAD

**Issue by Winnie0408** [lss233/chatgpt-mirai-qq-bot#410]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
配置文件：
- 最新Alpha版本
- 使用混合模式
- 开启输出Bing的猜你喜欢与参考资料

问题：
- “猜你喜欢”会重复输出两次
- “参考资料”不会像之前版本一样，在回答中的“[1] [2]”中创建超链接

**运行环境:**  
- 操作系统：Ubuntu 22.04 s390x
- Docker： 无
- 项目版本：2.2.5-alpha

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 使用混合模式
2. 开启Bing的参考资料与猜你喜欢
3. 向Bing提问

**预期行为**  
- “猜你喜欢”只输出一次
- 回答中的[1] [2]有超链接，可点击

**截图**  
![Screenshot_2023-03-23-14-48-08-781_com.tencent.mobileqq.png](https://user-images.githubusercontent.com/42741874/227125510-819c2973-87aa-4f4a-be8f-cede0dd07f6f.png)

![606a1424f4c92ea0.png](https://user-images.githubusercontent.com/42741874/227125569-8d6ab65c-444f-4b67-a065-b88211dfe3cf.png)

![Screenshot_2023-03-23-14-48-42-314_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/42741874/227125608-4e46e6ea-343c-41f0-ba64-087d12f2c243.jpg)

![-4334581a30b0035d.png](https://user-images.githubusercontent.com/42741874/227125645-9f4ee46f-1622-4cc5-8417-4b660bd776f9.png)

**其他内容**  
纯文本或者纯图片模式下，猜你喜欢正常。
图片模式下，[1][2]也没有超链接，无法点击。

**Comment by lss233** [comment]
v2.2.5-beta 已发布，修复此问题。
