### ISSUE TITLE
[Feature]发送随机的提醒内容

### ISSUE THREAD

**Issue by fjaokdp** [lss233/chatgpt-mirai-qq-bot#417]
希望增加一个功能可以在超过响应时间时发送提醒的时候随机发送某个txt文本内的一行内容，例如一些有意义的语录，机器人的使用小技巧等，而不是一直重复 "我还在思考中，请再等一下~"

**Comment by lss233** [comment]
可以发一个 PR 来加入这个功能。只需要修改一下 timeout 那个 middleware 就行了。
