### ISSUE TITLE
[BUG] 登录qq失败，日志显示W/console: Closing input service...

### ISSUE THREAD

**Issue by youtianmeng** [lss233/chatgpt-mirai-qq-bot#419]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√ ] 我已看过其他 issue，他们不能解决我的问题 
- [ √] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
与机器人对话没反应，日志显示openai登录正常，但是卡在W/console: Closing input service...
![image](https://user-images.githubusercontent.com/106040493/227466603-91c13ac7-cef2-4ed0-b3a5-573925d0d5cb.png)

**运行环境:linux
- 操作系统：ubuntu20.04
- Docker： 23.0.1
- 项目版本：v2.x

**复现步骤**  
用一键脚本在纯净ubuntu下安装，最后发现机器人没有响应，打开日志后发现显示W/console: Closing input service...

**截图**  
![image](https://user-images.githubusercontent.com/106040493/227466603-91c13ac7-cef2-4ed0-b3a5-573925d0d5cb.png)

**Comment by lss233** [comment]
一键部署脚本在安装完之后有告诉你遇到这个情况要怎么做的。
如果你忘记了，可以看 https://github.com/lss233/chatgpt-mirai-qq-bot/issues/142 里【QQ没登录】那个环节。
