### ISSUE TITLE
[Feature] 加入new bing 绘画

### ISSUE THREAD

**Issue by d4renk** [lss233/chatgpt-mirai-qq-bot#421]
https://github.com/acheong08/EdgeGPT#image-generator

**Comment by lss233** [comment]
Bing 绘画实际上还是基于 DALL-E。  我们本来就支持 DALL-E 绘图。

如果你真的希望通过 Bing 来绘图，可以发一个 PR。

**Comment by lss233** [comment]
你可以发一个 PR 过来
