### ISSUE TITLE
[Feature] 请求一个限制上下文对话轮数的功能

### ISSUE THREAD

**Issue by aitsc** [lss233/chatgpt-mirai-qq-bot#423]
感觉不需要每次带上前面所有的对话，有点浪费token

**Comment by aitsc** [comment]
以及多少分钟后的对话就不放入上下文？

**Comment by lss233** [comment]
可以把你的需求说具体一点么？  如果你不想浪费token，其实是可以在配置文件里面修改 max_token 的。

通过合理配置 max_token 和 min_token 这两个参数（比如说 max 1000， min 100，  
这样AI 就只会记忆大概 100~1000 个 token。
