### ISSUE TITLE
[BUG] docker compose命令启动mirai和gpt顺序错误,导致无法连接

### ISSUE THREAD

**Issue by Katerina0926** [lss233/chatgpt-mirai-qq-bot#424]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：linux
- Docker： ？
- 项目版本：最新版

**复现步骤**  
docker compose up后出现如下情况
![image](https://user-images.githubusercontent.com/104199092/227725377-be0cf7a9-ced6-4b59-9dfb-8be40c780572.png)
docker compose .yaml文件中是先启动mirai再启动gpt,但是用上述命令后mirai还没启动成功先启动gpt了,导致连接失败.再mirai再次连接后才能成功连接.
而且出现了掉线不会自动重连的情况.

**预期行为**  
输出docker compose后先启动mirai再启动gpt
同时在掉线情况的时候,能够按照如上顺序重新启动mirai再启动gpt

**Comment by Katerina0926** [comment]
![image](https://user-images.githubusercontent.com/104199092/227726513-4e956f69-0332-443b-9724-3a4b4cea9220.png)
dodocker-compose.yaml

**Comment by Katerina0926** [comment]
![image](https://user-images.githubusercontent.com/104199092/227728252-64ead877-8ea0-4671-b193-074d4f45229e.png)
![image](https://user-images.githubusercontent.com/104199092/227728265-7d49406e-c850-402e-9384-c3456fb55e04.png)
mirai正常 chatgpt掉线

**Comment by lss233** [comment]
这和启动顺序没什么关系，Aridane 有自动重新连接的功能，它会不断重试直到 mirai 登录成功。  另外，掉线不重连是 mirai 的已知 bug，是设计原因无法解决（在哪看见的我忘了），所以后来我加入了对 reverse-ws 的支持，让 mirai 主动连接 Aridane。
