### ISSUE TITLE
我在window快速部署过程中遇到了问题，提示未能使用所配置的账号激活SessionKey

### ISSUE THREAD

**Issue by 3293406747** [lss233/chatgpt-mirai-qq-bot#425]
chatgpt日志

![b28b725e4e8db0847c7e6675db8cb2c](https://user-images.githubusercontent.com/98522540/227725562-ea55c3b2-b24c-4ecc-b977-b32ddfaef9e6.png)

mirai日志
![image](https://user-images.githubusercontent.com/98522540/227725650-cbf4a3f2-e015-415c-b769-6ddf24ef6221.png)

**Comment by lss233** [comment]
这是一个 mirai api http 或者 Aridane 的 bug，请到对应的项目下发issue。  

出现这个问题的原因可能是因为你的mirai没有登录qq导致的，一般情况下不影响正常使用。

**Comment by AkkaDuilin** [comment]
同问 报错后没有其他显示直接无反应了 :)

**Comment by 3293406747** [comment]
> 这是一个mirai api http或者作者Aridane的bug，请到对应的项目下发issue。
> 
> 出现这个问题的原因可能是因为你的mirai没有登录qq引导致的，一般情况下并不影响正常使用。

mirai怎么登录qq呢？无法正常使用。
