### ISSUE TITLE
[BUG] 文心一言不能用

### ISSUE THREAD

**Issue by horizon86** [lss233/chatgpt-mirai-qq-bot#428]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
```
> File "d:\project\QQbot\chatgpt-mirai-qq-bot\universal.py", line 137, in request
    async for rendered in task:
                          └ <async_generator object ConversationContext.ask at 0x0000020A5DF11CC0>

  File "d:\project\QQbot\chatgpt-mirai-qq-bot\conversation.py", line 140, in ask
    async for item in self.adapter.ask(prompt):
                      │    │       │   └ '你好'
                      │    │       └ <function YiyanAdapter.ask at 0x0000020A5DD6E2A0>
                      │    └ <adapter.baidu.yiyan.YiyanAdapter object at 0x0000020A5E001890>
                      └ <conversation.ConversationContext object at 0x0000020A5DFD0390>

  File "d:\project\QQbot\chatgpt-mirai-qq-bot\adapter\baidu\yiyan.py", line 83, in ask
    await self.new_conversation(prompt)
          │    │                └ '你好'
          │    └ <function YiyanAdapter.new_conversation at 0x0000020A5DD6E200>
          └ <adapter.baidu.yiyan.YiyanAdapter object at 0x0000020A5E001890>

  File "d:\project\QQbot\chatgpt-mirai-qq-bot\adapter\baidu\yiyan.py", line 75, in new_conversation
    self.__check_response(req.json())
    │                     │   └ <function Response.json at 0x0000020A5AED7CE0>
    │                     └ <Response [200 OK]>
    └ <adapter.baidu.yiyan.YiyanAdapter object at 0x0000020A5E001890>

  File "d:\project\QQbot\chatgpt-mirai-qq-bot\adapter\baidu\yiyan.py", line 158, in __check_response
    raise Exception(resp['msg'])
                    └ {'code': 1, 'msg': '请先登录', 'data': None, 'logId': '118000000366076895'}
```

**运行环境:**  
- 操作系统：Windows 11
- Docker： no
- 项目版本：v2.2.5-rc1

**复现步骤**  
描述你是如何触发这个 BUG 的
让一言回答问题。

另外一言也会用openai的代理不合理吧。

**预期行为**  
正确回答

**截图**  
https://github.com/lss233/chatgpt-mirai-qq-bot/issues/394#issuecomment-1484018577

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by horizon86** [comment]
上述测试是我没有让百度使用代理的结果。同时浏览器可用。

**Comment by lss233** [comment]
已更新 Cookie 获取方法，请查看：
https://github.com/lss233/chatgpt-mirai-qq-bot/wiki/%E6%96%87%E5%BF%83%E4%B8%80%E8%A8%80-Cookie-%E8%8E%B7%E5%8F%96%E6%95%99%E7%A8%8B

**Comment by horizon86** [comment]
> 已更新 Cookie 获取方法，请查看： https://github.com/lss233/chatgpt-mirai-qq-bot/wiki/%E6%96%87%E5%BF%83%E4%B8%80%E8%A8%80-Cookie-%E8%8E%B7%E5%8F%96%E6%95%99%E7%A8%8B

还是不能用，不知作者是否测试成功？

**Comment by lss233** [comment]
看一下你的 Cookie 里面是不是没有 BDUSS 这个字段。 我们这里好几个人测都没问题。

**Comment by horizon86** [comment]
> 看一下你的 Cookie 里面是不是没有 BDUSS 这个字段。 我们这里好几个人测都没问题。

没有。只有BDUSS_BFESS

**Comment by lss233** [comment]
> > 看一下你的 Cookie 里面是不是没有 BDUSS 这个字段。 我们这里好几个人测都没问题。
> 
> 没有。只有BDUSS_BFESS

那就是不行的。重新获取吧。

**Comment by horizon86** [comment]
> > > 看一下你的 Cookie 里面是不是没有 BDUSS 这个字段。 我们这里好几个人测都没问题。
> > 
> > 
> > 没有。只有BDUSS_BFESS
> 
> 那就是不行的。重新获取吧。

好了，退出重新登录有了这个字段了
