### ISSUE TITLE
[BUG] W/reverse-ws adapter: [reverse-ws] Connection to chatgpt:8554/ interrupted. Trying reconnect in 5000 ms.

### ISSUE THREAD

**Issue by lIlIlllllmeng** [lss233/chatgpt-mirai-qq-bot#431]
**表现**  
W/reverse-ws adapter: [reverse-ws] Connection to chatgpt:8554/ interrupted. Trying reconnect in 5000 ms.

**运行环境:**  
- 操作系统：Ubuntu 20
- Docker： Docker version 23.0.1, build a5ee5b1
- 项目版本：Linux: 通过快速部署脚本部署 （新人推荐)

**复现步骤**  
使用Linux: 通过快速部署脚本部署 （新人推荐)的方式进行部署的

**截图**  
![image](https://user-images.githubusercontent.com/94682166/227782231-3a2bdc5e-c93c-48b5-a5fd-a2724a88527d.png)
![image](https://user-images.githubusercontent.com/94682166/227782262-5d56fec2-a0ba-48c2-a6f1-e1602e043a48.png)

**Comment by lss233** [comment]
chatgpt 日志呢？
你这 mirai 的 QQ 也没登录呀，有验证码。

**Comment by lIlIlllllmeng** [comment]
![image](https://user-images.githubusercontent.com/94682166/227890209-55c399ad-88c4-4750-8e0f-1f9b09d565d5.png)

**Comment by AresQQQQQ** [comment]
我使用 onebot模式登录也有此问题
![image](https://user-images.githubusercontent.com/91429185/228163268-b963682b-8241-4def-a14b-95b811f5e9fa.png)
![image](https://user-images.githubusercontent.com/91429185/228163516-49cd03d6-f7e0-46fd-a840-1c34d8bf943f.png)

配置文件
![image](https://user-images.githubusercontent.com/91429185/228163789-f7c82eef-8cb5-4764-9ed9-79aae5479f74.png)

**Comment by 4everhope** [comment]
<img width="828" alt="截屏2023-03-28 17 55 18" src="https://user-images.githubusercontent.com/88260395/228200058-bad020db-c810-4368-bd79-506b9fbfe89f.png">
ubuntu 20.04 手动部署，可能是由于网段设置有问题，本人能力不足，请大佬们帮助，谢谢

**Comment by lss233** [comment]
> 我使用 onebot模式登录也有此问题 ![image](https://user-images.githubusercontent.com/91429185/228163268-b963682b-8241-4def-a14b-95b811f5e9fa.png) ![image](https://user-images.githubusercontent.com/91429185/228163516-49cd03d6-f7e0-46fd-a840-1c34d8bf943f.png)
> 
> 配置文件 ![image](https://user-images.githubusercontent.com/91429185/228163789-f7c82eef-8cb5-4764-9ed9-79aae5479f74.png)

用 onebot 那你的 onebot 呢？

**Comment by lss233** [comment]
> <img alt="截屏2023-03-28 17 55 18" width="828" src="https://user-images.githubusercontent.com/88260395/228200058-bad020db-c810-4368-bd79-506b9fbfe89f.png">
> 
> ubuntu 20.04 手动部署，可能是由于网段设置有问题，本人能力不足，请大佬们帮助，谢谢

你在 mirai 设置了 反向 ws 模式，又在 chatgpt 设置了正向 ws 模式。
你需要将其中一个修改成另外一种模式，才能连接上。

#142

**Comment by 4everhope** [comment]
谢谢您的回复，目前尝试了正向连接，http+ws，使用http://mirai:8080,能够正常连接，但是只要发信息就报错，看了issue尝试重新pull镜像，使用新的版本创建容器，仍然不行，更换版本仍然不行，正向连接会报错：Java.nio.channels.UnresolvedAddressException: null，尝试了反向ws，使用chatgpt的host，然后mirai提示无法连接，5秒后重试，可能是由于docker compose没有设定网络的原因，之前曾经使用您的项目成功部署过，迁移服务器之后重新安装发现新产生以下问题……我能力不足，还请麻烦您指教，谢谢了。

**Comment by 4everhope** [comment]
> > <img alt="截屏2023-03-28 17 55 18" width="828" src="https://user-images.githubusercontent.com/88260395/228200058-bad020db-c810-4368-bd79-506b9fbfe89f.png">
> > ubuntu 20.04 手动部署，可能是由于网段设置有问题，本人能力不足，请大佬们帮助，谢谢
> 
> 你在 mirai 设置了 反向 ws 模式，又在 chatgpt 设置了正向 ws 模式。 你需要将其中一个修改成另外一种模式，才能连接上。
> 
> #142
谢谢您的回复，目前尝试了正向连接，http+ws，使用[http://mirai:8080,能够正常连接，但是只要发信息就报错，看了issue尝试重新pull镜像，使用新的版本创建容器，仍然不行，更换版本仍然不行，正向连接会报错：Java.nio.channels.UnresolvedAddressException](http://mirai:8080,%E8%83%BD%E5%A4%9F%E6%AD%A3%E5%B8%B8%E8%BF%9E%E6%8E%A5%EF%BC%8C%E4%BD%86%E6%98%AF%E5%8F%AA%E8%A6%81%E5%8F%91%E4%BF%A1%E6%81%AF%E5%B0%B1%E6%8A%A5%E9%94%99%EF%BC%8C%E7%9C%8B%E4%BA%86issue%E5%B0%9D%E8%AF%95%E9%87%8D%E6%96%B0pull%E9%95%9C%E5%83%8F%EF%BC%8C%E4%BD%BF%E7%94%A8%E6%96%B0%E7%9A%84%E7%89%88%E6%9C%AC%E5%88%9B%E5%BB%BA%E5%AE%B9%E5%99%A8%EF%BC%8C%E4%BB%8D%E7%84%B6%E4%B8%8D%E8%A1%8C%EF%BC%8C%E6%9B%B4%E6%8D%A2%E7%89%88%E6%9C%AC%E4%BB%8D%E7%84%B6%E4%B8%8D%E8%A1%8C%EF%BC%8C%E6%AD%A3%E5%90%91%E8%BF%9E%E6%8E%A5%E4%BC%9A%E6%8A%A5%E9%94%99%EF%BC%9AJava.nio.channels.UnresolvedAddressException): null，尝试了反向ws，使用chatgpt的host，然后mirai提示无法连接，5秒后重试，可能是由于docker compose没有设定网络的原因，之前曾经使用您的项目成功部署过，迁移服务器之后重新安装发现新产生以下问题……我能力不足，还请麻烦您指教，谢谢了。

**Comment by lss233** [comment]
此问题已收录项目文档的常见问题解答。
