### ISSUE TITLE
连接OpenAI服务器失败！

### ISSUE THREAD

**Issue by ChenhWu** [lss233/chatgpt-mirai-qq-bot#435]
**表现**  
代理配置成功，
new bing session 连接成功
只有ChatGPT api连接失败

**运行环境:**  
- 操作系统：windows
- 项目版本：git获取的最新版本

**截图**  
[2023-03-27-11-39-41.png](https://i.postimg.cc/13chqjFg/2023-03-27-11-39-41.png)

**其他内容**  
同样的配置在 MacOS 下可以正常工作。但是换到windows平台就无法连接服务器。
目前我怀疑是python环境或库的问题。
应该不是代理问题。我也换过不同的代理软件，端口配置都正常。

**Comment by QAQLuceQAQ** [comment]
我也遇到了这个问题

**Comment by lss233** [comment]
可以看看下面这个帖子能不能帮到你。
https://stackoverflow.com/questions/63347818/aiohttp-client-exceptions-clientconnectorerror-cannot-connect-to-host-stackover

**Comment by MeiXiaoKe1212** [comment]
你好，我也出现了这个问题，请问你解决了吗？

**Comment by lss233** [comment]
用 access_token 的方式登录试试
