### ISSUE TITLE
[BUG] 文心一言画图报错

### ISSUE THREAD

**Issue by DevHaoZi** [lss233/chatgpt-mirai-qq-bot#438]
**提交 issue 前，请先确认：**
- [√ ] 我已看过 **FAQ**，此问题不在列表中
- [√ ] 我已看过其他 issue，他们不能解决我的问题 
- [√ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
文心一言画图报错：
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。
('网络异常: 无头客户端处发生错误, 你应该检查其输出的错误日志.', {'code': 500, 'msg': 'Unsupported image type (mirai) for ExternalResource net.mamoe.mirai.internal.utils.ExternalResourceImplByFile@506a7100, considering use gif/png/bmp/jpg format. image header: 52 49 46 46 48 9E 00 00 57 45 42 50 56 50 38 20 3C 9E 00 00 30 84 02 9D 01 2A 00 02 00 02'})

**运行环境:**  
- 操作系统：Windows 10 LTSC
- Docker： 无
- 项目版本：v2.2.5-rc2

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 设置好文心一言账号启动，无报错
2. 群里at它发送消息“画一个鼠标”，收到报错消息

**预期行为**  
返回画好的图片

**截图**  
![image](https://user-images.githubusercontent.com/115467771/227915441-41f88118-7516-42e4-927d-5a95227df8ac.png)

**其他内容**  
没有

**Comment by lss233** [comment]
已知问题 下个版本修复。

**Comment by lss233** [comment]
v2.2.5 正式版已修复。
