### ISSUE TITLE
openai token不停更换？

### ISSUE THREAD

**Issue by JoshK622** [lss233/chatgpt-mirai-qq-bot#44]
登上chatgpt后发现
要用的token过十几秒就会换
换了token再运行bot.py也一直得到Wrong response code

**Comment by lss233** [comment]
请把 bug 反馈给 https://github.com/acheong08/ChatGPT

也可以试试 Authorization 登录

**Comment by leihao** [comment]
其实我想说,都用chrome处理CF了,为啥不直接用浏览器弹出登录好了...上游越来越别扭了

**Comment by lss233** [comment]
> 其实我想说,都用chrome处理CF了,为啥不直接用浏览器弹出登录好了...上游越来越别扭了

我也觉得，不过他们说今天会搞这个出来
