### ISSUE TITLE
[Feature] 添加微信支持？

### ISSUE THREAD

**Issue by shyu216** [lss233/chatgpt-mirai-qq-bot#443]
我逛了好些个chatgpt机器人的项目，就这家的ai的种类是最多的，所以想问下能不能接一下微信

这是一个python的微信机器人项目：https://github.com/littlecodersh/ItChat

**Comment by lss233** [comment]
我看着挺简单的，也许你可以发一个 PR。  
可以参考现有的平台支持的代码，你只需要在 `platforms` 文件夹里加一个 `wechat.py` 就可以了。

**Comment by joe12801** [comment]
> > 我看着挺简单的，也许你可以发一个 PR。 可以参考现有的平台支持的代码，你只需要在 `platforms` 文件夹里加一个 `wechat.py` 就可以了。
> 
> ok，我明天弄
我想弄，我不会python

**Comment by shyu216** [comment]
> > > 我看着挺简单的，也许你可以发一个 PR。 可以参考现有的平台支持的代码，你只需要在 `platforms` 文件夹里加一个 `wechat.py` 就可以了。
> > 
> > 
> > ok，我明天弄
> > 我想弄，我不会python

那你会js吗

开始前看看这个。。。https://github.com/lss233/chatgpt-mirai-qq-bot/pull/448

**Comment by lss233** [comment]
可以试试这个：https://github.com/lich0821/WeChatFerry

**Comment by lss233** [comment]
微信功能已由 https://github.com/lcjqyml/wechatbot 提供支持
