### ISSUE TITLE
[BUG] FileNotFoundError

### ISSUE THREAD

**Issue by zyoung1212** [lss233/chatgpt-mirai-qq-bot#447]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
最新2.2.5版，windows快速部署下，报错，实际上已确认该文件存在，.net已安装
![image](https://user-images.githubusercontent.com/20473104/228120150-feb4447d-e3b0-4d20-b51d-b5acb2e7362e.png)

**运行环境:**  
- 操作系统：Win10
- Docker： 无
- 项目版本：2.2.5

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 初始化
2. go-cq启动
3. 启动chatgpt

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
可以先试试看这个：https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/780#issuecomment-682222819

**Comment by zyoung1212** [comment]
> 

可以，已解决，感谢。
 Download and install it from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads.
