### ISSUE TITLE
[BUG] 如果要求带上口音，程序会崩溃重启。

### ISSUE THREAD

**Issue by linxp001** [lss233/chatgpt-mirai-qq-bot#452]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况
对机器人发送“接下来说话都带上山东口音。你吃了什么？”
然后会得到文本答复，无语音输出。
后台发现程序崩溃重启了。

**运行环境:**  
- 操作系统：CentOS Linux release 7.9.2009 (Core)
- Docker：  Docker Engine - Community 23.0.1
- 项目版本：2.2.5

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 对机器人发送“接下来说话都带上山东口音。你吃了什么？”
2. 等待回复
3. 会收到文本回答，但没有语音输出
4. 后台可以看到错误日志

**预期行为**  
描述你认为正常情况下应该看见的情况
转换口音输出语音？或者至少别出错，以默认口音输出语音。
另外顺便问一下，目前的程序是否支持通过指令进行口音转换呢？

**截图**  
相关日志、聊天记录的截图，没有可跳过
![image](https://user-images.githubusercontent.com/75927451/228277773-74fec6f0-a1dc-4f1e-9438-11747a3dd177.png)
![image](https://user-images.githubusercontent.com/75927451/228278071-01ff7624-e398-4cbb-a60e-a8bc10833a87.png)

**其他内容**  
此处填写其他内容，没有可跳过
希望可以实现通过指令进行口音转换的功能。

**Comment by lss233** [comment]
重复 #451
