### ISSUE TITLE
[question] Bard cookie选哪一条？

### ISSUE THREAD

**Issue by HE-SI-QI** [lss233/chatgpt-mirai-qq-bot#453]
Bard cookie选这里的哪一个呀？
![IMG_3927](https://user-images.githubusercontent.com/69979084/228318415-9a958623-98f0-4825-b32d-43582de3fff6.PNG)

**Comment by lss233** [comment]
![image](https://user-images.githubusercontent.com/8984680/228400530-4a0490b7-dbbf-4899-a720-cd26f533db97.png)

大概像这样

**Comment by lss233** [comment]
我更新了 wiki，你可以看看。

**Comment by HE-SI-QI** [comment]
好的谢谢

**Comment by yxuan-li** [comment]
> 我更新了 wiki，你可以看看。

你好，network中没有info这个文件了

**Comment by lss233** [comment]
> > 我更新了 wiki，你可以看看。
> 
> 你好，network中没有info这个文件了

不用选 info，选其他的也可以。

**Comment by XokoukioX** [comment]
> > > 我更新了 wiki，你可以看看。
> > 
> > 
> > 你好，network中没有info这个文件了
> 
> 不用选 info，选其他的也可以。

![Inked屏幕截图 2023-08-31 165250](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/52972345/10198c5f-6500-45dc-af7b-60d3ab5fb157)
佬 现在获取的cookie长这样 但是贴进去之后Bot会报错
 the JSON object must be str, bytes or bytearray, not NoneType
