### ISSUE TITLE
[BUG] ImportError: DLL load failed while importing _silkv3:找不到指定的模块。

### ISSUE THREAD

**Issue by asdmiss520** [lss233/chatgpt-mirai-qq-bot#454]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG
![image](https://user-images.githubusercontent.com/125500336/228346739-02b67c37-0288-44dc-b3d0-311a177a1ae9.png)

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：？
- Docker： ？
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
我已发布 v2.2.6 版本，当出现运行库未安装的情况时程序不会自动崩溃。
