### ISSUE TITLE
[BUG] README和universal.py里的POE “Claude”单词拼写错误

### ISSUE THREAD

**Issue by kimino-muki** [lss233/chatgpt-mirai-qq-bot#457]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
README和universal.py中POE的模型，Claude单词拼写错成了Calude

**运行环境:**  
- 操作系统：？
- Docker： ？
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的
按照提示给bot发送“切换AI calude”时返回AI类型不存在。😂

**预期行为**  
README和universal.py的calude修改为claude。

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
感谢提醒！
