### ISSUE TITLE
想法

### ISSUE THREAD

**Issue by wfq3212592665** [lss233/chatgpt-mirai-qq-bot#458]
能不能开发一个能接入腾讯的QQ机器人来使用，这样qq号就不容易被封或者冻结

**Comment by lss233** [comment]
QQ 官方的机器人只能在 QQ 频道里面用，并且限制很多：https://bot.q.qq.com/wiki/#_9-1-%E8%AF%AD%E6%96%99%E9%85%8D%E7%BD%AE
