### ISSUE TITLE
[BUG] 拉取最新镜像后new bing依然提示Bing 已结束本次会话。继续发送消息将重新开启一个新会话。

### ISSUE THREAD

**Issue by youtianmeng** [lss233/chatgpt-mirai-qq-bot#459]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

chatgpt-qq-chatgpt-1     | 2023-03-29 14:16:07.304 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
chatgpt-qq-chatgpt-1     | 2023-03-29 14:16:07.306 | DEBUG    | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时……
chatgpt-qq-chatgpt-1     | 2023-03-29 14:16:17.310 | ERROR    | adapter.ms.bing:ask:77 - 
chatgpt-qq-chatgpt-1     | Traceback (most recent call last):
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 666, in __await_impl__
chatgpt-qq-chatgpt-1     |     await protocol.handshake(
chatgpt-qq-chatgpt-1     |           │        └ <function WebSocketClientProtocol.handshake at 0x7fb7d7ddf1a0>
chatgpt-qq-chatgpt-1     |           └ <websockets.legacy.client.WebSocketClientProtocol object at 0x7fb7d41ea590>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 332, in handshake
chatgpt-qq-chatgpt-1     |     raise InvalidStatusCode(status_code, response_headers)
chatgpt-qq-chatgpt-1     |           │                 │            └ Headers([('Set-Cookie', '_C_ETH=1; domain=.bing.com; path=/; secure; httponly'), ('Accept-CH', 'Sec-CH-UA-Bitness, Sec-CH-UA-...
chatgpt-qq-chatgpt-1     |           │                 └ 502
chatgpt-qq-chatgpt-1     |           └ <class 'websockets.exceptions.InvalidStatusCode'>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | During handling of the above exception, another exception occurred:
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | Traceback (most recent call last):
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/tasks.py", line 490, in wait_for
chatgpt-qq-chatgpt-1     |     return fut.result()
chatgpt-qq-chatgpt-1     |            │   └ <method 'result' of '_asyncio.Task' objects>
chatgpt-qq-chatgpt-1     |            └ <Task cancelled name='Task-107' coro=<Connect.__await_impl__() done, defined at /usr/local/lib/python3.11/site-packages/webso...
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 680, in __await_impl__
chatgpt-qq-chatgpt-1     |     await protocol.wait_closed()
chatgpt-qq-chatgpt-1     |           │        └ <function WebSocketCommonProtocol.wait_closed at 0x7fb7d7dde020>
chatgpt-qq-chatgpt-1     |           └ <websockets.legacy.client.WebSocketClientProtocol object at 0x7fb7d41ea590>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | asyncio.exceptions.CancelledError
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | The above exception was the direct cause of the following exception:
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | Traceback (most recent call last):
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/bot.py", line 32, in <module>
chatgpt-qq-chatgpt-1     |     main()
chatgpt-qq-chatgpt-1     |     └ <function main at 0x7fb7d53f1da0>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/platforms/ariadne_bot.py", line 302, in main
chatgpt-qq-chatgpt-1     |     app.launch_blocking()
chatgpt-qq-chatgpt-1     |     │   └ <classmethod(<function Ariadne.launch_blocking at 0x7fb7d7f02c00>)>
chatgpt-qq-chatgpt-1     |     └ <graia.ariadne.app.Ariadne object at 0x7fb7d88a9f50>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/graia/ariadne/app.py", line 312, in launch_blocking
chatgpt-qq-chatgpt-1     |     cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
chatgpt-qq-chatgpt-1     |     │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
chatgpt-qq-chatgpt-1     |     │   │              │                    │   │       └ <property object at 0x7fb7d7efa2a0>
chatgpt-qq-chatgpt-1     |     │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x7fb7d7f25ed0>
chatgpt-qq-chatgpt-1     |     │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
chatgpt-qq-chatgpt-1     |     │   │              └ <function Launart.launch_blocking at 0x7fb7d82abf60>
chatgpt-qq-chatgpt-1     |     │   └ <launart.manager.Launart object at 0x7fb7d888ab50>
chatgpt-qq-chatgpt-1     |     └ <class 'graia.ariadne.app.Ariadne'>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/launart/manager.py", line 494, in launch_blocking
chatgpt-qq-chatgpt-1     |     loop.run_until_complete(launch_task)
chatgpt-qq-chatgpt-1     |     │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /usr/local/lib/python3.11/site-packages/launart/manager...
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop.run_until_complete at 0x7fb7dac64680>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
chatgpt-qq-chatgpt-1     |     self.run_forever()
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop.run_forever at 0x7fb7dac645e0>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
chatgpt-qq-chatgpt-1     |     self._run_once()
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop._run_once at 0x7fb7dac663e0>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
chatgpt-qq-chatgpt-1     |     handle._run()
chatgpt-qq-chatgpt-1     |     │      └ <function Handle._run at 0x7fb7dabb8900>
chatgpt-qq-chatgpt-1     |     └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
chatgpt-qq-chatgpt-1     |     self._context.run(self._callback, *self._args)
chatgpt-qq-chatgpt-1     |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt-qq-chatgpt-1     |     │    │            │    └ <member '_callback' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt-qq-chatgpt-1     |     │    └ <member '_context' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/universal.py", line 186, in request
chatgpt-qq-chatgpt-1     |     async for rendered in task:
chatgpt-qq-chatgpt-1     |                           └ <async_generator object ConversationContext.ask at 0x7fb7d52b1340>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/conversation.py", line 151, in ask
chatgpt-qq-chatgpt-1     |     async for item in self.adapter.ask(prompt):
chatgpt-qq-chatgpt-1     |                       │    │       │   └ '你好'
chatgpt-qq-chatgpt-1     |                       │    │       └ <function BingAdapter.ask at 0x7fb7d74ff060>
chatgpt-qq-chatgpt-1     |                       │    └ <adapter.ms.bing.BingAdapter object at 0x7fb7d541cf50>
chatgpt-qq-chatgpt-1     |                       └ <conversation.ConversationContext object at 0x7fb7d4199810>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | > File "/app/adapter/ms/bing.py", line 46, in ask
chatgpt-qq-chatgpt-1     |     async for final, response in self.bot.ask_stream(prompt=prompt,
chatgpt-qq-chatgpt-1     |                                  │    │   │                 └ '你好'
chatgpt-qq-chatgpt-1     |                                  │    │   └ <function Chatbot.ask_stream at 0x7fb7d7e86660>
chatgpt-qq-chatgpt-1     |                                  │    └ <EdgeGPT.Chatbot object at 0x7fb7d4199610>
chatgpt-qq-chatgpt-1     |                                  └ <adapter.ms.bing.BingAdapter object at 0x7fb7d541cf50>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/EdgeGPT.py", line 355, in ask_stream
chatgpt-qq-chatgpt-1     |     async for response in self.chat_hub.ask_stream(
chatgpt-qq-chatgpt-1     |                           │    │        └ <function ChatHub.ask_stream at 0x7fb7d7e86340>
chatgpt-qq-chatgpt-1     |                           │    └ <EdgeGPT.ChatHub object at 0x7fb7d4205cd0>
chatgpt-qq-chatgpt-1     |                           └ <EdgeGPT.Chatbot object at 0x7fb7d4199610>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/EdgeGPT.py", line 269, in ask_stream
chatgpt-qq-chatgpt-1     |     self.wss = await websockets.connect(
chatgpt-qq-chatgpt-1     |     │    │           │          └ <class 'websockets.legacy.client.Connect'>
chatgpt-qq-chatgpt-1     |     │    │           └ <module 'websockets.client' from '/usr/local/lib/python3.11/site-packages/websockets/client.py'>
chatgpt-qq-chatgpt-1     |     │    └ None
chatgpt-qq-chatgpt-1     |     └ <EdgeGPT.ChatHub object at 0x7fb7d4205cd0>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
chatgpt-qq-chatgpt-1     |     return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
chatgpt-qq-chatgpt-1     |                  │       │        │    │                 │    └ 10
chatgpt-qq-chatgpt-1     |                  │       │        │    │                 └ <websockets.legacy.client.Connect object at 0x7fb7d41bf290>
chatgpt-qq-chatgpt-1     |                  │       │        │    └ <function Connect.__await_impl__ at 0x7fb7d7ddf740>
chatgpt-qq-chatgpt-1     |                  │       │        └ <websockets.legacy.client.Connect object at 0x7fb7d41bf290>
chatgpt-qq-chatgpt-1     |                  │       └ <function wait_for at 0x7fb7dac53380>
chatgpt-qq-chatgpt-1     |                  └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/tasks.py", line 492, in wait_for
chatgpt-qq-chatgpt-1     |     raise exceptions.TimeoutError() from exc
chatgpt-qq-chatgpt-1     |           │          └ <class 'TimeoutError'>
chatgpt-qq-chatgpt-1     |           └ <module 'asyncio.exceptions' from '/usr/local/lib/python3.11/asyncio/exceptions.py'>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | TimeoutError
chatgpt-qq-chatgpt-1     | 2023-03-29 14:16:20.993 | DEBUG    | middlewares.timeout:handle_respond:46 - [Timeout] 取消计时……
chatgpt-qq-mirai-1       | 2023-03-29 14:16:21 V/Bot.2900323862: Friend(1830242183) <- [mirai:quote:[mirai:source:ids=[29022], internalIds=[85152794], from friend 1830242183 to 2900323862 at 1680099366], content=你好]Bing 已结束本次会话。继续发送消息将重新开启一个新会话。

**Comment by lss233** [comment]
TimeoutError 连接超时了，你上个代理试试。

**Comment by youtianmeng** [comment]
这台是日本的服务器，应该不是网络的问题，在另一台美国服务器上运行也出现了相同的问题

**Comment by youtianmeng** [comment]
> 

这台是日本的服务器，应该不是网络的问题，在另一台美国服务器上运行也出现了相同的问题

**Comment by youtianmeng** [comment]
> TimeoutError 连接超时了，你上个代理试试。

这台是日本的服务器，应该不是网络的问题，在另一台美国服务器上运行也出现了相同的问题

**Comment by youtianmeng** [comment]
chatgpt_1     | 2023-03-30 05:36:45.919 | DEBUG    | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时……
chatgpt_1     | 2023-03-30 05:36:45.921 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
chatgpt_1     | 2023-03-30 05:36:45.923 | DEBUG    | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时……
chatgpt_1     | 2023-03-30 05:36:46.233 | ERROR    | adapter.ms.bing:ask:77 - 'throttling'
chatgpt_1     | Traceback (most recent call last):
chatgpt_1     | 
chatgpt_1     |   File "/app/bot.py", line 32, in <module>
chatgpt_1     |     main()
chatgpt_1     |     └ <function main at 0x7fc46b6d89a0>
chatgpt_1     | 
chatgpt_1     |   File "/app/platforms/ariadne_bot.py", line 302, in main
chatgpt_1     |     app.launch_blocking()
chatgpt_1     |     │   └ <classmethod(<function Ariadne.launch_blocking at 0x7fc46e1ea3e0>)>
chatgpt_1     |     └ <graia.ariadne.app.Ariadne object at 0x7fc46e240350>
chatgpt_1     | 
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/graia/ariadne/app.py", line 312, in launch_blocking
chatgpt_1     |     cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
chatgpt_1     |     │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
chatgpt_1     |     │   │              │                    │   │       └ <property object at 0x7fc46e1e5800>
chatgpt_1     |     │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x7fc46e817d10>
chatgpt_1     |     │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
chatgpt_1     |     │   │              └ <function Launart.launch_blocking at 0x7fc46e587740>
chatgpt_1     |     │   └ <launart.manager.Launart object at 0x7fc46e8779d0>
chatgpt_1     |     └ <class 'graia.ariadne.app.Ariadne'>
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/launart/manager.py", line 494, in launch_blocking
chatgpt_1     |     loop.run_until_complete(launch_task)
chatgpt_1     |     │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at /usr/local/lib/python3.11/site-packages/launart/manager...
chatgpt_1     |     │    └ <function BaseEventLoop.run_until_complete at 0x7fc470f54680>
chatgpt_1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
chatgpt_1     |     self.run_forever()
chatgpt_1     |     │    └ <function BaseEventLoop.run_forever at 0x7fc470f545e0>
chatgpt_1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
chatgpt_1     |     self._run_once()
chatgpt_1     |     │    └ <function BaseEventLoop._run_once at 0x7fc470f563e0>
chatgpt_1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
chatgpt_1     |     handle._run()
chatgpt_1     |     │      └ <function Handle._run at 0x7fc470ea8900>
chatgpt_1     |     └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
chatgpt_1     |     self._context.run(self._callback, *self._args)
chatgpt_1     |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
chatgpt_1     |     │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt_1     |     │    │            │    └ <member '_callback' of 'Handle' objects>
chatgpt_1     |     │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt_1     |     │    └ <member '_context' of 'Handle' objects>
chatgpt_1     |     └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 191, in request
chatgpt_1     |     async for rendered in task:
chatgpt_1     |                           └ <async_generator object ConversationContext.ask at 0x7fc46cd7a3e0>
chatgpt_1     | 
chatgpt_1     |   File "/app/conversation.py", line 151, in ask
chatgpt_1     |     async for item in self.adapter.ask(prompt):
chatgpt_1     |                       │    │       │   └ '你好'
chatgpt_1     |                       │    │       └ <function BingAdapter.ask at 0x7fc46d7da200>
chatgpt_1     |                       │    └ <adapter.ms.bing.BingAdapter object at 0x7fc46b6eae10>
chatgpt_1     |                       └ <conversation.ConversationContext object at 0x7fc46b7a5e50>
chatgpt_1     | 
chatgpt_1     | > File "/app/adapter/ms/bing.py", line 58, in ask
chatgpt_1     |     max_messages = response["item"]["throttling"]["maxNumUserMessagesInConversation"]
chatgpt_1     |                    └ {'type': 2, 'invocationId': '0', 'item': {'firstNewMessageIndex': None, 'conversationId': '51D|BingProd|42804CDD4F2A557BF1522...
chatgpt_1     | 
chatgpt_1     | KeyError: 'throttling'
再次重新安装之后的报错好像出现了变化

**Comment by G37H9** [comment]
我这边也是美国的服务器 bing好像用不了了不知道怎么了

**Comment by youtianmeng** [comment]
已解决，好像是cookie的问题，今天重新获取了一个就好了
