### ISSUE TITLE
[BUG] 登录失败! 连接 OpenAI 服务器失败,请更换代理节点重试

### ISSUE THREAD

**Issue by lIlIlllllmeng** [lss233/chatgpt-mirai-qq-bot#462]
**表现**  
登录失败! 连接 OpenAI 服务器失败,请更换代理节点重试

**运行环境:** Ubuntu
- 操作系统：20
- Docker： Docker version 20.10.7, build f0df350
- 项目版本：Linux: 通过快速部署脚本部署 （新人推荐)

**复现步骤**  

docker -compose up

**截图**  
![image](https://user-images.githubusercontent.com/94682166/228703996-382ce6d4-128d-462a-813b-f20b2ce144f3.png)

**Comment by lss233** [comment]
按照提示操作即可。如果你实在无法解决代理节点的问题，也可以使用 access token 登录。

**Comment by lIlIlllllmeng** [comment]
![image](https://user-images.githubusercontent.com/94682166/228704343-ffe0433b-9ceb-4b85-a9b0-f0629244d9b2.png)
全局代理，虚拟机也可以打开Chatgpt

**Comment by lIlIlllllmeng** [comment]
已解决

**Comment by lIlIlllllmeng** [comment]
已解决，谢谢大佬，两分钟内就得到了回复。赞

**Comment by fkxxyz** [comment]
https://explorer.api.openai.com 握手失败，一直以为是我节点的问题，直到发现用什么节点都连不上😂

**Comment by huayuprophet** [comment]
似乎access token也登不上了，不知道是我环境的问题还是bug问题
![image](https://user-images.githubusercontent.com/106079510/229050371-7fe830e9-673e-4fb9-9817-1c7dbb8ae4ba.png)
![image](https://user-images.githubusercontent.com/106079510/229050393-a6e73a2c-97f3-4137-99fe-b73ff41e627e.png)
![image](https://user-images.githubusercontent.com/106079510/229050415-1865ceb5-bd55-4f2d-99dc-267d5ec92409.png)
看样子似乎是ssl认证过程有问题

**Comment by lss233** [comment]
> 似乎access token也登不上了，不知道是我环境的问题还是bug问题 ![image](https://user-images.githubusercontent.com/106079510/229050371-7fe830e9-673e-4fb9-9817-1c7dbb8ae4ba.png) ![image](https://user-images.githubusercontent.com/106079510/229050393-a6e73a2c-97f3-4137-99fe-b73ff41e627e.png) ![image](https://user-images.githubusercontent.com/106079510/229050415-1865ceb5-bd55-4f2d-99dc-267d5ec92409.png) 看样子似乎是ssl认证过程有问题

#462

**Comment by lss233** [comment]
> 似乎access token也登不上了，不知道是我环境的问题还是bug问题 ![image](https://user-images.githubusercontent.com/106079510/229050371-7fe830e9-673e-4fb9-9817-1c7dbb8ae4ba.png) ![image](https://user-images.githubusercontent.com/106079510/229050393-a6e73a2c-97f3-4137-99fe-b73ff41e627e.png) ![image](https://user-images.githubusercontent.com/106079510/229050415-1865ceb5-bd55-4f2d-99dc-267d5ec92409.png) 看样子似乎是ssl认证过程有问题

请使用最新版。
