### ISSUE TITLE
[Feature] 建议维护现有功能，暂缓快速更新

### ISSUE THREAD

**Issue by bk1412** [lss233/chatgpt-mirai-qq-bot#469]
目前支持的bot平台和gpt平台已经足够多，建议首先维护好目前的平台，否则体验并不是特别好，比如切换为discord模式的，docker的启动方式只能通过观看日志来观察是否启动成功，但是观看日志的话，旧日志也会输出，docker如果一直在运行，日志文件累积几十mb的情况下也会全部输出，大概加载几十秒log的进度还是显示半个月前的log，诸如此类的问题还有很多，比如discord的触发方式看了源码只支持@触发，poe的聊天模式只支持gpt3.5，虽然别的模式通过常量已经写进去了，并且使用手顺文档之类的也没有完善，一个好的文档可以解决很多问题，还有config都累加在一起的方式似乎不是一个长久之计，总之建议维护和完善好现有功能的体验，缩小新功能的更新进度，除非再出现什么跨阶段的新gpt模式或者平台，但是感觉很难了，以上都是个人看法，写的很乱，见谅

**Comment by lss233** [comment]
你好，关于文档更新的事宜已在 #440 提上议程，欢迎有能力的同学一起来帮忙。
配置文件本身其实并不大，在文档完善以后我会删除README中的大片儿文档，改成引导用户到项目文档中自行配置需要调整的功能。  
目前项目的更新频率较之前相比确实已经放缓，主要的更新均为bugfix。由于个人精力有限，我无法保证各项功能的稳定性。在这里很感谢测试组的同学积极参与新代码的测试。    
关于日志的问题，这和你使用docker的方式有关。如果你想看最近的日志，可以用 docker-compose logs -f --tail=100 chatgpt

**Comment by bk1412** [comment]
> 你好，关于文档更新的事宜已在 #440 提上议程，欢迎有能力的同学一起来帮忙。 配置文件本身其实并不大，在文档完善以后我会删除README中的大片儿文档，改成引导用户到项目文档中自行配置需要调整的功能。 目前项目的更新频率较之前相比确实已经放缓，主要的更新均为bugfix。由于个人精力有限，我无法保证各项功能的稳定性。在这里很感谢测试组的同学积极参与新代码的测试。 关于日志的问题，这和你使用docker的方式有关。如果你想看最近的日志，可以用 docker-compose logs -f --tail=100 chatgpt

关于日志的查看命令明白了，以后可能将docker-compose logs -f --tail=500 chatgpt作为启动日志和错误调试时使用的log命令比较合适，因为像小白或者我这类没有用过docker的群体，使用安装完成后提示的log命令会一脸懵

**Comment by bk1412** [comment]
.
