### ISSUE TITLE
启动后会不停的重启浏览器，怎么办呢

### ISSUE THREAD

**Issue by islanddddddd** [lss233/chatgpt-mirai-qq-bot#47]
![0AF2F09C](https://user-images.githubusercontent.com/38216943/207336542-55a43b35-55fb-48e9-aa93-e2b55d2e82fb.png)

**Comment by islanddddddd** [comment]
mirai已经登录成功了，config里的session应该也没问题

**Comment by lss233** [comment]
更新最新版的 revChatGPT 试试

**Comment by shuimen666** [comment]
同，更新了revChatGPT之后，revChatGPT自己的--debug不会反复重启了，但点启动还是会

**Comment by lss233** [comment]
可以尝试一下最新的 https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v1.4.3-alpha

**Comment by GooWen** [comment]
> 可以尝试一下最新的 https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v1.4.3-alpha

我还是会自动重启

**Comment by leihao** [comment]
我也遇到了,开了调试看了一下,就是浏览器里获取过cf需要UA和cookie获取成功之后,下一次尝试的时候依旧被cf拦住了,导致了无限循环重试.原因不明,需要上游修复了.
原先的过cf盾的思路是一个cookie,UA,IP三者一致就能过,我原先以为因为python内的代理设置和打开的chrome的代理设置差异导致访问的IP不一致,后来我试过了别的方式设置代理,发现一样.
没办法了,可能是IP被cf特殊照顾了,总之让上游去处理吧...

**Comment by Kawasumii** [comment]
> 我也遇到了,开了调试看了一下,就是浏览器里获取过cf需要UA和cookie获取成功之后,下一次尝试的时候依旧被cf拦住了,导致了无限循环重试.原因不明,需要上游修复了. 原先的过cf盾的思路是一个cookie,UA,IP三者一致就能过,我原先以为因为python内的代理设置和打开的chrome的代理设置差异导致访问的IP不一致,后来我试过了别的方式设置代理,发现一样. 没办法了,可能是IP被cf特殊照顾了,总之让上游去处理吧...

同样的问题。其实这个问题很好判断出来，就是不挂任何代理的时候打开ChatGPT的网页看看CF墙是几次过的；如果一次就能过基本就没问题了，但我需要三四次才可以通过人机认证，不知怎么样才能减少这个频率。总之现在只能等待上游了。

**Comment by xiaoyanmiao** [comment]
我也是，打开一按登录就又关闭了，根本没办法

**Comment by Cxuan66** [comment]
我也是出现这种情况，似乎在不停地登入网站，已经登陆进去后面也会关闭窗口再次重新登陆

**Comment by zwz15008** [comment]
+1

**Comment by lss233** [comment]
请更新至最新版，然后重试，如果有问题，请重新打开此 issue。
