### ISSUE TITLE
[BUG] 使用网页版 ChatGPT时切换模型报错

### ISSUE THREAD

**Issue by linxp001** [lss233/chatgpt-mirai-qq-bot#471]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

在使用网页版 ChatGPT时，发送切换模型的指令后报错：此 AI 暂不支持切换模型的操作！

**运行环境:**  
- 操作系统：CentOS Linux release 7.9.2009 (Core)
- Docker： Docker Compose version v2.14.0
- 项目版本：v2.2.6

**复现步骤**  
描述你是如何触发这个 BUG 的

1. 给机器人发送指令：“切换模型 text-davinci-002-render-sha”
2. 得到回复：“出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。
此 AI 暂不支持切换模型的操作！”

**预期行为**  
描述你认为正常情况下应该看见的情况

得到回复：“已切换至  text-davinci-002-render-sha 模型，让我们聊天吧！”

**截图**  
相关日志、聊天记录的截图，没有可跳过

![image](https://user-images.githubusercontent.com/75927451/228774947-0f647f0a-5719-48b9-ac3a-0ec6d1f9ebd1.png)
![image](https://user-images.githubusercontent.com/75927451/228775168-7fd8beed-82b2-4f24-9f39-6bbf80a58f21.png)
![image](https://user-images.githubusercontent.com/75927451/228776658-7775c40f-f5be-433d-a4f4-f54ed7325ee4.png)
![image](https://user-images.githubusercontent.com/75927451/228775500-019c33b8-9443-4c78-8919-a787ee550bd8.png)

**其他内容**  
此处填写其他内容，没有可跳过

我使用API 版 ChatGPT时是可以正常切换模型的，没有报错。
我配置的是默认AI使用网页版 ChatGPT，默认开启GPT-4，配置文件的相关内容如下：
[[openai.accounts]]
mode = "browserless"
access_token = "eyXXX"
paid = true
gpt4 = true
...
[trigger]
...
switch_model = "切换模型 (.+)"
allowed_models = ['text-davinci-002-render-sha', 'text-davinci-002-render-paid', 'gpt-4', 'gpt-3.5-turbo', 'gpt-3.5-turbo-0301', 'gpt-4-0314', 'gpt-4-32k', 'gpt-4-32k-0314']
allow_switching_ai = true
[response]
...
default_ai = "chatgpt-web"
...

**Comment by lss233** [comment]
网页版暂不支持切换模型。

**Comment by linxp001** [comment]
![image](https://user-images.githubusercontent.com/75927451/230905440-6e19484a-1897-45a7-bc0c-5b524df6e42e.png)
默认使用的是GPT-4模型，切换到3.5以后，无法切换回GPT-4模型

**Comment by linxp001** [comment]
> ![image](https://user-images.githubusercontent.com/75927451/230905440-6e19484a-1897-45a7-bc0c-5b524df6e42e.png) 默认使用的是GPT-4模型，切换到3.5以后，无法切换回GPT-4模型 ![image](https://user-images.githubusercontent.com/75927451/230905610-9ba52a85-beb0-4e58-8b17-7006562a650e.png)

相关配置如下：
[openai]
[[openai.accounts]]
mode = "browserless"
model="gpt-4"

[trigger]
switch_model = "切换模型 (.+)"
allowed_models = ['text-davinci-002-render-sha', 'text-davinci-002-render-paid', 'gpt-4', 'gpt-3.5-turbo', 'gpt-3.5-turbo-0301', 'gpt-4-0314', 'gpt-4-32k', 'gpt-4-32k-0314']
allow_switching_ai = true
