### ISSUE TITLE
连接 OpenAI 服务器失败

### ISSUE THREAD

**Issue by MeiXiaoKe1212** [lss233/chatgpt-mirai-qq-bot#472]
![问题截图](https://mxk-images.oss-cn-shanghai.aliyuncs.com/20230330165440.png)
> manager.bot:login_openai:247 - 登录失败! 连接 OpenAI 服务器失败,请更换代理节点重试
！HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/csrf (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:992)')))

_Originally posted by @MeiXiaoKe1212 in https://github.com/lss233/chatgpt-mirai-qq-bot/issues/435#issuecomment-1489940102_

**Comment by lss233** [comment]
用 access_token 的方式登录试试

**Comment by MeiXiaoKe1212** [comment]
已解决，使用access_token方式登录~谢谢佬
