### ISSUE TITLE
[BUG] azure 语音转换没有回复

### ISSUE THREAD

**Issue by lIlIlllllmeng** [lss233/chatgpt-mirai-qq-bot#473]
**表现**  
azure 语音转换没有回复

**运行环境:**  
- 操作系统：Ubuntu 20
- Docker： Docker version 23.0.1, build a5ee5b1
- 项目版本：Linux: 通过快速部署脚本部署 （新人推荐)

**截图**  
![image](https://user-images.githubusercontent.com/94682166/228794373-e4176872-a9f5-4d9a-98f6-d8c2d82ae5bf.png)
![image](https://user-images.githubusercontent.com/94682166/228794404-b08d4fd9-d5e7-4a6a-9098-2dd90b0d3696.png)

**Comment by lss233** [comment]
看不出问题

**Comment by lIlIlllllmeng** [comment]
我发送语音，没有任何反应，会是那些地方出问题吗
