### ISSUE TITLE
[BUG] OpenAI 服务器登录失败！

### ISSUE THREAD

**Issue by lIlIlllllmeng** [lss233/chatgpt-mirai-qq-bot#476]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
OpenAI 服务器登录失败！

**运行环境:** Ubuntu
- 操作系统：20
- Docker： Docker version 20.10.7, build f0df350
- 项目版本：Linux: 通过快速部署脚本部署 （新人推荐)

**复现步骤**  
docker-compose up

**截图**  

token和邮箱的方式都有尝试，报错如下
![image](https://user-images.githubusercontent.com/94682166/229008148-78c6b75e-1008-480f-80bc-adbd5dc0360b.png)
![image](https://user-images.githubusercontent.com/94682166/229008433-3a9d10eb-6120-41aa-8123-ca0c382294cb.png)
![image](https://user-images.githubusercontent.com/94682166/229008561-dac334d5-4567-4d09-8871-fe2a607fc540.png)

**Comment by q23339860** [comment]
我也出这个错误头疼

**Comment by lss233** [comment]
此问题的解决方案与 #478 相同，升级至最新版即可。
