### ISSUE TITLE
[BUG] SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by qingshanlanshan** [lss233/chatgpt-mirai-qq-bot#478]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

启动时出现：
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'bypass.duti.tech'. (_ssl.c:992)

**运行环境:**  
- 操作系统：MacOS
- 项目版本：最新版，手动部署

**复现步骤**  
描述你是如何触发这个 BUG 的

conda环境 python 3.11 
启动时即出现，重新启动仍存在
只尝试了使用access token登录
正常浏览器访问没问题

可能和#476 是同一问题

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/68636377/229014220-40579611-f42b-49c5-802d-d3f82a33aad1.png">
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/68636377/229014288-6243c589-e374-484f-a082-f6c1017dfd13.png">
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/68636377/229014333-22a56a66-39d7-4fef-8e7a-a8ad24b7ed1a.png">
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/68636377/229014365-4c06171a-0842-4996-b2fa-d0e4a2cef01d.png">

**Comment by zhmou** [comment]
config配置文件里面的browserless_endpoint改成"https://bypass.churchless.tech/api/"这个试试，原来的这个https://bypass.duti.tech/api/好像不能用了，不确定

**Comment by qingshanlanshan** [comment]
> config配置文件里面的browserless_endpoint改成 https://bypass.churchless.tech/api/ 这个试试，原来的这个https://bypass.duti.tech/api/ 好像不能用了，不确定

解决了，谢谢

**Comment by lss233** [comment]
发布了新版，现在改了。
