### ISSUE TITLE
配置文件的内容越来越多,可以出一份配置文件的界面面板吗

### ISSUE THREAD

**Issue by wutong0320** [lss233/chatgpt-mirai-qq-bot#479]
把配置文件可视化,可以用输入框自动监视配置文件的修改,显示在输入框内,修改输入框的内容自动修改config.cfg内的内容,初始化,和启动mirai和启动chatGPT,都可以变成按钮,点击即启动,把各个账号的输入内容变成选项卡,各种账号的选项卡,让windows的配置傻瓜化,解释内容不用显示在控制界面,只要显示让新手添什么就可以,真正懂的会去找配置文件.

**Comment by wutong0320** [comment]
我之前用tkinter试了下,是可行的,虽然界面比较丑.

**Comment by lss233** [comment]
我的提议是写成 Web 的管理页面，这样连跨平台的问题都一并解决了。

**Comment by wutong0320** [comment]
这个想法也是很好的,现在的配置文件看的比较繁琐,大部分都是说明文档性质,如果能简化到只写必须配置,默认配置隐藏掉,会更清晰,希望早日出现此功能,群主辛苦.

**Comment by lss233** [comment]
> 这个想法也是很好的,现在的配置文件看的比较繁琐,大部分都是说明文档性质,如果能简化到只写必须配置,默认配置隐藏掉,会更清晰,希望早日出现此功能,群主辛苦.

现在的配置文件要改的只有 4 行，我觉得应该不繁琐了

**Comment by wutong0320** [comment]
只有4行吗,我感觉我每次都要改8-9行,我不用网页版的,不需要把默认的openai账号1注释掉吗?我每次都注释,我之前只用一个bing,现在是只用一个API,所以我说的看起来很"繁琐",就是不知道哪些要改,哪些不要改,希望网页的配置文件更清晰.

**Comment by lss233** [comment]
> 只有4行吗,我感觉我每次都要改8-9行,我不用网页版的,不需要把默认的openai账号1注释掉吗?我每次都注释,我之前只用一个bing,现在是只用一个API,所以我说的看起来很"繁琐",就是不知道哪些要改,哪些不要改,希望网页的配置文件更清晰.

我建议你再看看。

**Comment by ZS629** [comment]
臣附议

![cc55dfc3eba72099dc38aedaf7f391f](https://user-images.githubusercontent.com/127756463/230524802-9147c193-0005-47bd-bbd3-2b7d001cef5c.png)

![340f8598410c8db6e24254f5d36c6cd](https://user-images.githubusercontent.com/127756463/230524828-cb0aea7d-4de5-4dde-b478-26082526c4cf.png)

![ec486d8f72149ac0c94af0beda165aa](https://user-images.githubusercontent.com/127756463/230524848-968c515d-77d5-4f7f-a3e1-d14c350c7666.png)

![46b8e16674c2319f5b9c5982dd14542](https://user-images.githubusercontent.com/127756463/230524864-e2c18b7c-104c-4468-9cde-46895fc2bfc3.png)

![c3748fc26192cb3265da637f32f7298](https://user-images.githubusercontent.com/127756463/230524880-cc07cb83-1b23-4123-b3a3-fe249d1813f2.png)

![66ecce1bd1210efadbe602461666742](https://user-images.githubusercontent.com/127756463/230524900-62334342-5182-4bfa-b277-e893cea8caaf.png)

![9097993fedcb9baf788c318f75e6b71](https://user-images.githubusercontent.com/127756463/230524907-1fbe4dac-0543-4252-a582-1cc5f53d07dc.png)

要改这些，还真是有点“繁琐”

**Comment by wutong0320** [comment]
群主在开发一个通过Web导入配置文件的了,耐心等待吧

**Comment by azz212** [comment]
> 臣附议 ![cc55dfc3eba72099dc38aedaf7f391f](https://user-images.githubusercontent.com/127756463/230524802-9147c193-0005-47bd-bbd3-2b7d001cef5c.png)
> 
> ![340f8598410c8db6e24254f5d36c6cd](https://user-images.githubusercontent.com/127756463/230524828-cb0aea7d-4de5-4dde-b478-26082526c4cf.png)
> 
> ![ec486d8f72149ac0c94af0beda165aa](https://user-images.githubusercontent.com/127756463/230524848-968c515d-77d5-4f7f-a3e1-d14c350c7666.png)
> 
> ![46b8e16674c2319f5b9c5982dd14542](https://user-images.githubusercontent.com/127756463/230524864-e2c18b7c-104c-4468-9cde-46895fc2bfc3.png)
> 
> ![66ecce1bd1210efadbe602461666742](https://user-images.githubusercontent.com/127756463/230524900-62334342-5182-4bfa-b277-e893cea8caaf.png)
> 
> ![9097993fedcb9baf788c318f75e6b71](https://user-images.githubusercontent.com/127756463/230524907-1fbe4dac-0543-4252-a582-1cc5f53d07dc.png)
> 
> 要改这些，还真是有点“繁琐”

可以共享下配置文件吗

**Comment by zsanjin-p** [comment]
> 我的提议是写成 Web 的管理页面，这样连跨平台的问题都一并解决了。

问下web管理界面默认密码是啥呀
