### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by whiteme-laki** [lss233/chatgpt-mirai-qq-bot#48]

**Comment by whiteme-laki** [comment]
![image](https://user-images.githubusercontent.com/111164817/207342345-fbd78f42-34be-463d-84e5-cdb684a76dfa.png)
linux的安装出现这个问题，大佬求助

**Comment by lss233** [comment]
json 格式有问题

**Comment by Robinfxa** [comment]
config.json写了没
