### ISSUE TITLE
[BUG] ‘看’字也会被当作chatgpt-api画图前缀

### ISSUE THREAD

**Issue by mio2333** [lss233/chatgpt-mirai-qq-bot#480]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
chatgpt-api 会将看字当作画图，类似下图，感觉这个不是合理的
![image](https://user-images.githubusercontent.com/74481573/229063116-e0d030ce-1976-40e0-8164-5edb5a8497e1.png)

**运行环境:**  
- 操作系统：？
- Docker： ？
- 项目版本：？

**复现步骤**  
直接输入“看来你在人最无助的时候没有办法帮助他们”

**Comment by Yoak3n** [comment]
需要改配置文件里的```prefix_image```，默认配置如下：
![](https://yoaken-1316330335.cos.ap-chongqing.myqcloud.com/markdownPic/202303311629340.png)
比如改为```prefix_image = ["画",]```就能不识别“看”

**Comment by mio2333** [comment]
感谢解答，已经解决这个问题了，虽然感觉该项目默认配置直接把‘看’字去掉更好
