### ISSUE TITLE
登录成功，获取地址信息失败11001错误

### ISSUE THREAD

**Issue by Alfred676** [lss233/chatgpt-mirai-qq-bot#481]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [ √] 我已看过其他 issue，他们不能解决我的问题 
- [ √] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：window11
- onebot登录
- Docker： ？
- 项目版本：2.2.6.3

**复现步骤**  
描述你是如何触发这个 BUG 的
openai登录成功，出现11001错误，获取地址失败

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
![屏幕截图 2023-03-31 170954](https://user-images.githubusercontent.com/76623468/229081040-bcccb862-1b6d-4c01-8a77-e661faabf9e4.png)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
配置文件写错了导致的。  

但由于你没有提供配置文件，我也不知道哪里写错了。

**Comment by Alfred676** [comment]
解决了解决了，感谢感谢
