### ISSUE TITLE
[BUG] 新版本access_token登录出现401错误

### ISSUE THREAD

**Issue by AnyMoonS** [lss233/chatgpt-mirai-qq-bot#483]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：Windowserver2016
- Docker： ？
- 项目版本：2.2.6.3

**复现步骤**  
更新新版本之后，启动提示401错误

**预期行为**  
正常运行

**截图**  
相关日志、聊天记录的截图，没有可跳过
![图片](https://user-images.githubusercontent.com/72291751/229114421-5e173282-dc63-41c2-ba49-d1b756374e4d.png)

**其他内容**

**Comment by lss233** [comment]
检查下是不是你 access_token 出问题了。

**Comment by AnyMoonS** [comment]
> 

感谢回复，已检查，确认access_token无误

**Comment by lss233** [comment]
这个地址应该是通过 https://github.com/acheong08/ChatGPT-Proxy-V4 这个项目搭建的， 
找到类似的问题是这个：https://github.com/acheong08/ChatGPT-Proxy-V4/issues/10
根据里面的描述确实，access_token 过期或者不完整会导致此问题的发生，你可以按照里面的说法来检查你的 access_token，或者重新拿一个。  
你也可以换一个 browserless_endpoint。

**Comment by AnyMoonS** [comment]
> 这个地址应该是通过 https://github.com/acheong08/ChatGPT-Proxy-V4 这个项目搭建的， 找到类似的问题是这个：[acheong08/ChatGPT-Proxy-V4#10](https://github.com/acheong08/ChatGPT-Proxy-V4/issues/10) 根据里面的描述确实，access_token 过期或者不完整会导致此问题的发生，你可以按照里面的说法来检查你的 access_token，或者重新拿一个。 你也可以换一个 browserless_endpoint。

经过更换access_token成功解决该问题，不过原来的确实没过期(感谢解答

**Comment by loinhahaha** [comment]
> 这个地址应该是通过 https://github.com/acheong08/ChatGPT-Proxy-V4 这个项目搭建的， 找到类似的问题是这个：[acheong08/ChatGPT-Proxy-V4#10](https://github.com/acheong08/ChatGPT-Proxy-V4/issues/10) 根据里面的描述确实，access_token 过期或者不完整会导致此问题的发生，你可以按照里面的说法来检查你的 access_token，或者重新拿一个。 你也可以换一个 browserless_endpoint。

你好，我在部署中也出现此401错误，但更换access_token无效，具体配置如下：
[openai]
[[openai.accounts]]
access_token = "sk-xxx"
[openai.gpt3_params]
temperature = 0.5
max_tokens = 4000
top_p = 1.0
presence_penalty = 0.0
frequency_penalty = 0.0
min_tokens = 1000
