### ISSUE TITLE
[BUG] window一键部署，一切正常，但聊天机器人无回复

### ISSUE THREAD

**Issue by liaoyiqiao** [lss233/chatgpt-mirai-qq-bot#485]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中

**表现**  
![image](https://user-images.githubusercontent.com/119860470/229136904-9ec60003-bce2-47bd-b5bb-430214bf3e8a.png)
**运行环境:**  
- 操作系统：Windows

**Comment by liaoyiqiao** [comment]
聊天机器人能够看到我的对话，但并不回复

**Comment by liaoyiqiao** [comment]
我知道了，因为我手机qq是在线状态，下线就好了，打扰了。

**Comment by Syctiyil** [comment]
你的是可以收到机器人QQ的消息吗？我已经跟着教程完成部署了，但是我发给机器人QQ却没有回复。
