### ISSUE TITLE
大佬，这个怎么解决啊

### ISSUE THREAD

**Issue by ZS629** [lss233/chatgpt-mirai-qq-bot#492]
![a2727cabfe3b8d42e9557722f5968cd](https://user-images.githubusercontent.com/127756463/229287765-68248ca7-b0b6-46f0-b7bc-f473b73283c8.png)

**Comment by lss233** [comment]
![image](https://user-images.githubusercontent.com/8984680/229288293-8afbe614-3ab0-423e-9099-b4e00eecf3ba.png)

**Comment by ZS629** [comment]
搞定了，谢谢
![image](https://user-images.githubusercontent.com/127756463/229290734-8ed58b90-03ed-44c6-9657-89c466e680e1.png)
