### ISSUE TITLE
大佬，这个配置在哪设置

### ISSUE THREAD

**Issue by ZS629** [lss233/chatgpt-mirai-qq-bot#494]
![image](https://user-images.githubusercontent.com/127756463/229294982-71fa860d-86be-45a8-9859-9c28bbc46f85.png)

**Comment by lss233** [comment]
config.cfg

**Comment by ZS629** [comment]
这么快回复的，搞得我以为是机器人回复的[doge]

**Comment by ZS629** [comment]
这个吗
![image](https://user-images.githubusercontent.com/127756463/229295191-15c6bbf6-e0df-4285-8711-55cc1c51d0f0.png)

没找到代理相关配置![0CCE8091](https://user-images.githubusercontent.com/127756463/229295226-8548762c-4988-41cf-adbf-2a6b990c32c7.png)

![image](https://user-images.githubusercontent.com/127756463/229295173-2325eab1-3f03-4f93-bb91-de64503eb35c.png)

**Comment by lss233** [comment]
自己补充。拜托你看教程可以吗
![](https://user-images.githubusercontent.com/127756463/229295226-8548762c-4988-41cf-adbf-2a6b990c32c7.png)

**Comment by ZS629** [comment]
好的，刚看到那个gitbook的教程链接![0CD2D0B2](https://user-images.githubusercontent.com/127756463/229295470-6543993e-cacb-41f7-958c-41ebad56921e.png)

https://darks-organization.gitbook.io/chatgpt-qq/

**Comment by ZS629** [comment]
到这一步了，出现了这个提示
![image](https://user-images.githubusercontent.com/127756463/229298565-f394c65a-96e6-401f-a02e-f5a98148cf14.png)

**Comment by ZS629** [comment]
原来是我代理网络设置错了，现在搞定了
![image](https://user-images.githubusercontent.com/127756463/229300818-81ba3f4c-3c0b-4ccc-8fdf-c61f0fb12a63.png)

**Comment by ZS629** [comment]
重启遇到了这个问题
![image](https://user-images.githubusercontent.com/127756463/229302920-f08d4e44-509b-43b4-b387-c3070ef4aa8b.png)

gitbook上好像没有
![image](https://user-images.githubusercontent.com/127756463/229302962-4be699e3-4d62-416c-ac99-9dc8ab3628d4.png)

**Comment by lss233** [comment]
mirai-api-http 的问题请反馈给 mirai api http

**Comment by ZS629** [comment]
![image](https://user-images.githubusercontent.com/127756463/229304928-d734b69b-21f2-4fff-9e8a-52eb6e455e27.png)
大佬还在吗

**Comment by ZS629** [comment]
解决了
