### ISSUE TITLE
[BUG] Authentication failed. You have not been accepted into the beta.

### ISSUE THREAD

**Issue by beizhaibei** [lss233/chatgpt-mirai-qq-bot#495]
2023-04-02 00:51:24.941 | INFO     | platforms.ariadne_bot:start_background:192 - OpenAI 服务器登录中……
2023-04-02 00:51:24.942 | INFO     | manager.bot:login_bing:151 - 正在解析第 1 个 Bing 账号
2023-04-02 00:51:24.944 | SUCCESS  | manager.bot:login_bing:156 - 解析成功！
2023-04-02 00:51:24.945 | SUCCESS  | manager.bot:login_bing:162 - 成功解析 1/1 个 Bing 账号！

切换AI bing-p

2023-04-02 00:52:58.483 | DEBUG    | middlewares.concurrentlock:handle_request:25 - [Concurrent] 使用 Adapter 内部的 Queue
2023-04-02 00:52:58.484 | DEBUG    | middlewares.concurrentlock:handle_request:27 - [Concurrent] 排队中，前面还有 0 个人！
2023-04-02 00:52:58.485 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！
2023-04-02 00:52:58.486 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
2023-04-02 00:52:58.488 | DEBUG    | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时……
2023-04-02 00:53:07.066 | ERROR    | universal:request:242 - Authentication failed. You have not been accepted into the beta.
Traceback (most recent call last):

  File "F:\QQbot\chatgpt\python3.11\Lib\site-packages\EdgeGPT.py", line 233, in __init__
    raise NotAllowedToAccess(self.struct["result"]["message"])
          │                  │    └ {'result': {'value': 'UnauthorizedRequest', 'message': 'Sorry, you need to login first to access this service.'}}
          │                  └ <EdgeGPT.Conversation object at 0x000002196BD97250>
          └ <class 'EdgeGPT.NotAllowedToAccess'>

EdgeGPT.NotAllowedToAccess: Sorry, you need to login first to access this service.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "F:\QQbot\chatgpt\bot.py", line 32, in <module>
    main()
    └ <function main at 0x000002196BD8C5E0>

  File "F:\QQbot\chatgpt\platforms\ariadne_bot.py", line 302, in main
    app.launch_blocking()
    │   └ <classmethod(<function Ariadne.launch_blocking at 0x000002196A351DA0>)>
    └ <graia.ariadne.app.Ariadne object at 0x0000021969E52CD0>

  File "F:\QQbot\chatgpt\python3.11\Lib\site-packages\graia\ariadne\app.py", line 312, in launch_blocking
    cls.launch_manager.launch_blocking(loop=cls.service.loop, stop_signal=stop_signals)
    │   │              │                    │   │       │                 └ (<Signals.SIGINT: 2>,)
    │   │              │                    │   │       └ <property object at 0x000002196A34D3F0>
    │   │              │                    │   └ <graia.ariadne.service.ElizabethService object at 0x0000021969E52E10>
    │   │              │                    └ <class 'graia.ariadne.app.Ariadne'>
    │   │              └ <function Launart.launch_blocking at 0x0000021969F39440>
    │   └ <launart.manager.Launart object at 0x000002196BACF850>
    └ <class 'graia.ariadne.app.Ariadne'>
  File "F:\QQbot\chatgpt\python3.11\Lib\site-packages\launart\manager.py", line 494, in launch_blocking
    loop.run_until_complete(launch_task)
    │    │                  └ <Task pending name='amnesia-launch' coro=<Launart.launch() running at F:\QQbot\chatgpt\python3.11\Lib\site-packages\launart\m...
    │    └ <function BaseEventLoop.run_until_complete at 0x00000219675FF240>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "asyncio\base_events.py", line 640, in run_until_complete
    sock.setblocking(False)

  File "asyncio\base_events.py", line 607, in run_forever
    sock.close()

  File "asyncio\base_events.py", line 1922, in _run_once

  File "asyncio\events.py", line 80, in _run
    self._loop = loop
    │    └ <member '_loop' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x000002196BD6A5F0>()>

> File "F:\QQbot\chatgpt\universal.py", line 118, in request
    conversation_handler.current_conversation = await conversation_handler.create(
    │                    │                            │                    └ <function ConversationHandler.create at 0x000002196BACA160>
    │                    │                            └ <conversation.ConversationHandler object at 0x000002196A233150>
    │                    └ <conversation.ConversationContext object at 0x000002196BF61FD0>
    └ <conversation.ConversationHandler object at 0x000002196A233150>

  File "F:\QQbot\chatgpt\conversation.py", line 243, in create
    conversation = ConversationContext(_type, self.session_id)
                   │                   │      │    └ 'friend-727827420'
                   │                   │      └ <conversation.ConversationHandler object at 0x000002196A233150>
                   │                   └ 'bing-p'
                   └ <class 'conversation.ConversationContext'>

  File "F:\QQbot\chatgpt\conversation.py", line 82, in __init__
    self.adapter = BingAdapter(self.session_id, ConversationStyle.precise)
    │              │           │    │           │                 └ <ConversationStyle.precise: 'h3precise'>
    │              │           │    │           └ <enum 'ConversationStyle'>
    │              │           │    └ 'friend-727827420'
    │              │           └ <conversation.ConversationContext object at 0x000002196BE7BAD0>
    │              └ <class 'adapter.ms.bing.BingAdapter'>
    └ <conversation.ConversationContext object at 0x000002196BE7BAD0>

  File "F:\QQbot\chatgpt\adapter\ms\bing.py", line 33, in __init__
    self.bot = EdgeChatbot(cookies=self.cookieData, proxy=account.proxy)
    │          │                   │    │                 │       └ None
    │          │                   │    │                 └ BingCookiePath(cookie_content='MUID=1A1F6D5F3EC16D5D070B634D3FEF6C12; SRCHD=AF=NOFORM; SRCHUID=V=2&GUID=AC836F3BEC854F9688332...
    │          │                   │    └ [{'name': 'MUID', 'value': '1A1F6D5F3EC16D5D070B634D3FEF6C12'}, {'name': 'SRCHD', 'value': 'AF=NOFORM'}, {'name': 'SRCHUID', ...
    │          │                   └ <adapter.ms.bing.BingAdapter object at 0x000002196BD97310>
    │          └ <class 'EdgeGPT.Chatbot'>
    └ <adapter.ms.bing.BingAdapter object at 0x000002196BD97310>

  File "F:\QQbot\chatgpt\python3.11\Lib\site-packages\EdgeGPT.py", line 325, in __init__
    Conversation(self.cookiePath, self.cookies, self.proxy)
    │            │    │           │    │        │    └ None
    │            │    │           │    │        └ <EdgeGPT.Chatbot object at 0x000002196BF20A90>
    │            │    │           │    └ [{'name': 'MUID', 'value': '1A1F6D5F3EC16D5D070B634D3FEF6C12'}, {'name': 'SRCHD', 'value': 'AF=NOFORM'}, {'name': 'SRCHUID', ...
    │            │    │           └ <EdgeGPT.Chatbot object at 0x000002196BF20A90>
    │            │    └ ''
    │            └ <EdgeGPT.Chatbot object at 0x000002196BF20A90>
    └ <class 'EdgeGPT.Conversation'>
  File "F:\QQbot\chatgpt\python3.11\Lib\site-packages\EdgeGPT.py", line 235, in __init__
    raise Exception(

Exception: Authentication failed. You have not been accepted into the beta.

**Comment by beizhaibei** [comment]
windows11
版本 v2.2.6.3

**Comment by ZS629** [comment]
这么一大段文字，要不直接截图吧，你这是用的新必应？cookie配置对了吗
![image](https://user-images.githubusercontent.com/127756463/229306116-ae482ce7-b58a-4cd4-bb3b-f04cc2760ab7.png)

![image](https://user-images.githubusercontent.com/127756463/229306620-9368555d-9674-448d-bc3d-be9bb8881629.png)

**Comment by beizhaibei** [comment]
![QQ截图20230402015303](https://user-images.githubusercontent.com/89172126/229306760-0a8330a5-face-4b0d-bcc9-e47cbed8059a.png)
cookie没问题吧，提示解析成功的，切换就报错了

**Comment by beizhaibei** [comment]
> 这么一大段文字，要不直接截图吧，你这是用的新必应？cookie配置对了吗 ![image](https://user-images.githubusercontent.com/127756463/229306116-ae482ce7-b58a-4cd4-bb3b-f04cc2760ab7.png)
> 
> ![image](https://user-images.githubusercontent.com/127756463/229306620-9368555d-9674-448d-bc3d-be9bb8881629.png)

已截图

**Comment by ZS629** [comment]
我的是出现了这个问题
![image](https://user-images.githubusercontent.com/127756463/229306884-cec27d6b-6d30-4f7c-a978-d5d1de4ad2db.png)

**Comment by ZS629** [comment]
不知道出了啥问题。大佬可能睡觉了，自己研究一下，或者明天再问问

**Comment by ZS629** [comment]
我把这个设置成了false，然后切换bing-p模式，又出现了这个问题
![image](https://user-images.githubusercontent.com/127756463/229307519-ad0b4f00-1adb-47a5-b5df-012fb27c5880.png)

**Comment by ZS629** [comment]
切换成chatgpt-web搞定了
![image](https://user-images.githubusercontent.com/127756463/229307939-ec912854-1d9a-4d1f-8e7f-89195f6058fa.png)

**Comment by beizhaibei** [comment]
> 切换成chatgpt-web搞定了 ![image](https://user-images.githubusercontent.com/127756463/229307939-ec912854-1d9a-4d1f-8e7f-89195f6058fa.png)

网页chatgpt可以正常使用，但是想用一下newbing，newbing信息的实时性更强一点

**Comment by ZS629** [comment]
newbing不知道出了什么事，对了，你有创建chatgpt的什么交流群吗，想要一起交流讨论一下这玩意

**Comment by ZS629** [comment]
试了这个方法
![image](https://user-images.githubusercontent.com/127756463/229308369-592591a7-794e-4154-9482-77390cc83c45.png)


还是不行
![image](https://user-images.githubusercontent.com/127756463/229308349-2ec796f4-7a21-4298-971f-234908b463e0.png)

**Comment by lss233** [comment]
`Sorry, you need to login first to access this service`  
根据日志来看，可能你的cookie过期或者不完整。

**Comment by Wangmomo667** [comment]
大佬，问下怎么确定是哪个账号返回此错误，我这有10个账号的全部显示登陆成功，但有一个号好像不能使用，返回
`Exception: Authentication failed. You have not been accepted into the beta.`，如何定位出错的账号呢
![image](https://user-images.githubusercontent.com/94622958/229328355-04144709-2def-4d36-9f6f-58be9687615b.png)

**Comment by lss233** [comment]
> 大佬，问下怎么确定是哪个账号返回此错误，我这有10个账号的全部显示登陆成功，但有一个号好像不能使用，返回 `Exception: Authentication failed. You have not been accepted into the beta.`，如何定位出错的账号呢 ![image](https://user-images.githubusercontent.com/94622958/229328355-04144709-2def-4d36-9f6f-58be9687615b.png)

不好意思，这个暂时没什么办法。  正常来说一个号能用所有的号都能用

**Comment by Wangmomo667** [comment]
同时会不断返回“Bing 已结束本次会话。继续发送消息将重新开启一个新会话。”
![image](https://user-images.githubusercontent.com/94622958/229328618-7d1e9a4e-709e-4a64-813e-c859c13c0369.png)
我用另外一个QQ问则正常回复，这个也不能定位是哪个机器人回复的吗
谢谢谢谢

**Comment by lss233** [comment]
> 同时会不断返回“Bing 已结束本次会话。继续发送消息将重新开启一个新会话。” ![image](https://user-images.githubusercontent.com/94622958/229328618-7d1e9a4e-709e-4a64-813e-c859c13c0369.png) 我用另外一个QQ问则正常回复，这个也不能定位是哪个机器人回复的吗 谢谢谢谢

是的，目前也没办法

**Comment by beizhaibei** [comment]
> `Sorry, you need to login first to access this service` 根据日志来看，可能你的cookie过期或者不完整。

cookie是在bing主页登录后f12然后控制台输入document.cookie返回的，这样的做法有没有问题呢

**Comment by lss233** [comment]
> > `Sorry, you need to login first to access this service` 根据日志来看，可能你的cookie过期或者不完整。
> 
> cookie是在bing主页登录后f12然后控制台输入document.cookie返回的，这样的做法有没有问题呢

有个问题，你输入了`document.cookie` 之后按下回车了吗？

**Comment by beizhaibei** [comment]
> > > `Sorry, you need to login first to access this service` 根据日志来看，可能你的cookie过期或者不完整。
> > 
> > 
> > cookie是在bing主页登录后f12然后控制台输入document.cookie返回的，这样的做法有没有问题呢
> 
> 有个问题，你输入了`document.cookie` 之后按下回车了吗？

是的

**Comment by beizhaibei** [comment]
> > > `Sorry, you need to login first to access this service` 根据日志来看，可能你的cookie过期或者不完整。
> > 
> > 
> > cookie是在bing主页登录后f12然后控制台输入document.cookie返回的，这样的做法有没有问题呢
> 
> 有个问题，你输入了`document.cookie` 之后按下回车了吗？

![QQ截图20230402131619](https://user-images.githubusercontent.com/89172126/229332960-138edad6-6b34-452b-aa5a-d09e8ae04476.png)

**Comment by beizhaibei** [comment]
有无大佬救救

**Comment by lss233** [comment]
根据  #537 所述， Bing Cookie 的获取方式已修改，可以用新的方法再试试。

**Comment by beizhaibei** [comment]
> 根据 #537 所述， Bing Cookie 的获取方式已修改，可以用新的方法再试试。

更新至v2.3.2，按原方式重新获取了bing的cookie，提示
EdgeGPT.NotAllowedToAccess: Sorry, you need to login first to access this service.
![QQ截图20230408004809](https://user-images.githubusercontent.com/89172126/230646384-f422caba-008b-4087-aa21-5bb3bae44b98.png)

**Comment by lss233** [comment]
> > 根据 #537 所述， Bing Cookie 的获取方式已修改，可以用新的方法再试试。
> 
> 更新至v2.3.2，按原方式重新获取了bing的cookie，提示 EdgeGPT.NotAllowedToAccess: Sorry, you need to login first to access this service. ![QQ截图20230408004809](https://user-images.githubusercontent.com/89172126/230646384-f422caba-008b-4087-aa21-5bb3bae44b98.png)

再设置下代理试试

**Comment by beizhaibei** [comment]
> > > 根据 #537 所述， Bing Cookie 的获取方式已修改，可以用新的方法再试试。
> > 
> > 
> > 更新至v2.3.2，按原方式重新获取了bing的cookie，提示 EdgeGPT.NotAllowedToAccess: Sorry, you need to login first to access this service. ![QQ截图20230408004809](https://user-images.githubusercontent.com/89172126/230646384-f422caba-008b-4087-aa21-5bb3bae44b98.png)
> 
> 再设置下代理试试

挂了全局代理的vpn还是切不过去，仍然提示Sorry, you need to login first to access this service.

**Comment by lss233** [comment]
我注意到你的 cookie_content 和教程所述的样子不太一样，你确定按照最新教程获取 Cookie 了吗？

**Comment by beizhaibei** [comment]
> 我注意到你的 cookie_content 和教程所述的样子不太一样，你确定按照最新教程获取 Cookie 了吗？
最新的教程是指什么呢，控制台document.cookie返回的cookie_content目前是有问题对吗

**Comment by beizhaibei** [comment]
> 我注意到你的 cookie_content 和教程所述的样子不太一样，你确定按照最新教程获取 Cookie 了吗？

装了cookie editor插件，然后在bing登录页面选择export as json，把cookie_content更换之后，仍然报错
![QQ截图20230409005326](https://user-images.githubusercontent.com/89172126/230733604-59594871-edff-42c5-88f7-705449b34669.png)

![QQ截图20230409005630](https://user-images.githubusercontent.com/89172126/230733618-b360141d-2359-427a-91dd-14e33a0ee7f9.png)

**Comment by lss233** [comment]
你没有设置代理，也没有修改 Bing 的 wss_link和 endpoint 吗？

**Comment by beizhaibei** [comment]
> 

这要怎么弄呢，有没有具体的步骤，我只会挂梯子

**Comment by lss233** [comment]
> > 
> 
> 这要怎么弄呢，有没有具体的步骤，我只会挂梯子

https://chatgpt-qq.lss233.com/pei-zhi-wen-jian-jiao-cheng/jie-ru-ai-ping-tai/jie-ru-new-bing-sydney#xiang-guan-she-zhi

**Comment by beizhaibei** [comment]
> > > 
> > 
> > 
> > 这要怎么弄呢，有没有具体的步骤，我只会挂梯子
> 
> https://chatgpt-qq.lss233.com/pei-zhi-wen-jian-jiao-cheng/jie-ru-ai-ping-tai/jie-ru-new-bing-sydney#xiang-guan-she-zhi

挂上了梯子，下了个clash-windows-amd64.exe，运行之后，在config里面设置了代理端口127.0.0.1:7890，
![QQ截图20230409013037](https://user-images.githubusercontent.com/89172126/230735014-a8288525-bcb1-4500-859b-b4a0260992b6.png)

**Comment by lss233** [comment]
你确定你的 clash 代理了 bing 的请求了吗？而不是让它直连？
你的 clash 是全局模式？

**Comment by lss233** [comment]
另外你也可以试试运行  https://github.com/acheong08/EdgeGPT 这个项目，这有助于我区分到底是本项目的bug，还是他们的bug。

**Comment by beizhaibei** [comment]
> 你确定你的 clash 代理了 bing 的请求了吗？而不是让它直连？ 你的 clash 是全局模式？

跟教程里面的clash界面好像差距有点大，clash-windows-amd64.exe运行之后是一个控制台来着，提示 edgeservices.bing.com:443 doesn't match any rule using DIRECT，是在直连？要怎么设置全局模式呢
![QQ截图20230409014329](https://user-images.githubusercontent.com/89172126/230735603-1ca1beeb-7759-44ef-89ab-91d677d4c2d9.png)

**Comment by lss233** [comment]
确实是在直连。你的这个 clash 我没用过，我建议你用 Clash for Windows。

**Comment by beizhaibei** [comment]
> 确实是在直连。你的这个 clash 我没用过，我建议你用 Clash for Windows。
有没有链接来个

**Comment by beizhaibei** [comment]
> 确实是在直连。你的这个 clash 我没用过，我建议你用 Clash for Windows。

装了个好像差不多的，运行之后还是切不过去
![QQ截图20230409115655](https://user-images.githubusercontent.com/89172126/230753469-9fe9ed10-4501-4821-8e2a-a5322b213066.png)

![QQ截图20230409115706](https://user-images.githubusercontent.com/89172126/230753477-586ef054-d827-4750-b0f2-1e65b6a1fe45.png)

**Comment by WangYijun-OUC** [comment]
> > > > 
> > > 
> > > 
> > > 这要怎么弄呢，有没有具体的步骤，我只会挂梯子
> > 
> > 
> > https://chatgpt-qq.lss233.com/pei-zhi-wen-jian-jiao-cheng/jie-ru-ai-ping-tai/jie-ru-new-bing-sydney#xiang-guan-she-zhi
> 
> 挂上了梯子，下了个clash-windows-amd64.exe，运行之后，在config里面设置了代理端口127.0.0.1:7890， ![QQ截图20230409013037](https://user-images.githubusercontent.com/89172126/230735014-a8288525-bcb1-4500-859b-b4a0260992b6.png)

你好，请问你的问题解决了吗？我也出现You need to login first的问题了

**Comment by liu2-3zhi** [comment]
我出现了这个问题，使用bing就出现

    chatgpt-qq-chatgpt-1     | 2023-06-24 13:34:29.819 | DEBUG    | platforms.onebot_bot:_:148 - 私聊消息：你好
    chatgpt-qq-chatgpt-1     | 2023-06-24 13:34:31.292 | ERROR    | universal:handle_message:295 - Authentication failed
    chatgpt-qq-chatgpt-1     | Traceback (most recent call last):
    chatgpt-qq-chatgpt-1     | 
    chatgpt-qq-chatgpt-1     |   File "/app/bot.py", line 54, in <module>
    chatgpt-qq-chatgpt-1     |     loop.run_until_complete(asyncio.gather(*bots))
    chatgpt-qq-chatgpt-1     |     │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at /app/platforms/onebot_bot.py:356> wait_for=<_GatheringFuture pendi...
    chatgpt-qq-chatgpt-1     |     │    │                  │       └ <function gather at 0x7f5c89ba45e0>
    chatgpt-qq-chatgpt-1     |     │    │                  └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>
    chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop.run_until_complete at 0x7f5c89bb53a0>
    chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    chatgpt-qq-chatgpt-1     | 
    chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    chatgpt-qq-chatgpt-1     |     self.run_forever()
    chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop.run_forever at 0x7f5c89bb5300>
    chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    chatgpt-qq-chatgpt-1     |     self._run_once()
    chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop._run_once at 0x7f5c89bb7100>
    chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    chatgpt-qq-chatgpt-1     |     handle._run()
    chatgpt-qq-chatgpt-1     |     │      └ <function Handle._run at 0x7f5c8a114040>
    chatgpt-qq-chatgpt-1     |     └ <Handle <TaskStepMethWrapper object at 0x7f5c426d2980>()>
    chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    chatgpt-qq-chatgpt-1     |     self._context.run(self._callback, *self._args)
    chatgpt-qq-chatgpt-1     |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    chatgpt-qq-chatgpt-1     |     │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f5c426d2980>()>
    chatgpt-qq-chatgpt-1     |     │    │            │    └ <member '_callback' of 'Handle' objects>
    chatgpt-qq-chatgpt-1     |     │    │            └ <Handle <TaskStepMethWrapper object at 0x7f5c426d2980>()>
    chatgpt-qq-chatgpt-1     |     │    └ <member '_context' of 'Handle' objects>
    chatgpt-qq-chatgpt-1     |     └ <Handle <TaskStepMethWrapper object at 0x7f5c426d2980>()>
    chatgpt-qq-chatgpt-1     | 
    chatgpt-qq-chatgpt-1     |   File "/app/platforms/onebot_bot.py", line 151, in _
    chatgpt-qq-chatgpt-1     |     await handle_message(
    chatgpt-qq-chatgpt-1     |           └ <function handle_message at 0x7f5c4269f4c0>
    chatgpt-qq-chatgpt-1     | 
    chatgpt-qq-chatgpt-1     | > File "/app/universal.py", line 261, in handle_message
    chatgpt-qq-chatgpt-1     |     conversation_handler.current_conversation = await conversation_handler.create(
    chatgpt-qq-chatgpt-1     |     │                    │                            │                    └ <function ConversationHandler.create at 0x7f5c426dc900>
    chatgpt-qq-chatgpt-1     |     │                    │                            └ <conversation.ConversationHandler object at 0x7f5c43151490>
    chatgpt-qq-chatgpt-1     |     │                    └ None
    chatgpt-qq-chatgpt-1     |     └ <conversation.ConversationHandler object at 0x7f5c43151490>
    chatgpt-qq-chatgpt-1     | 
    chatgpt-qq-chatgpt-1     |   File "/app/conversation.py", line 294, in create
    chatgpt-qq-chatgpt-1     |     conversation = ConversationContext(_type, self.session_id)
    chatgpt-qq-chatgpt-1     |                    │                   │      │    └ 'friend-2727192843'
    chatgpt-qq-chatgpt-1     |                    │                   │      └ <conversation.ConversationHandler object at 0x7f5c43151490>
    chatgpt-qq-chatgpt-1     |                    │                   └ 'bing-b'
    chatgpt-qq-chatgpt-1     |                    └ <class 'conversation.ConversationContext'>
    chatgpt-qq-chatgpt-1     | 
    chatgpt-qq-chatgpt-1     |   File "/app/conversation.py", line 100, in __init__
    chatgpt-qq-chatgpt-1     |     self.adapter = BingAdapter(self.session_id, ConversationStyle.balanced)
    chatgpt-qq-chatgpt-1     |     │              │           │    │           │                 └ <ConversationStyle.balanced: ['nlu_direct_response_filter', 'deepleo', 'disable_emoji_spoken_text', 'responsible_ai_policy_23...
    chatgpt-qq-chatgpt-1     |     │              │           │    │           └ <enum 'ConversationStyle'>
    chatgpt-qq-chatgpt-1     |     │              │           │    └ 'friend-2727192843'
    chatgpt-qq-chatgpt-1     |     │              │           └ <conversation.ConversationContext object at 0x7f5c42706450>
    chatgpt-qq-chatgpt-1     |     │              └ <class 'adapter.ms.bing.BingAdapter'>
    chatgpt-qq-chatgpt-1     |     └ <conversation.ConversationContext object at 0x7f5c42706450>
    chatgpt-qq-chatgpt-1     | 
    chatgpt-qq-chatgpt-1     |   File "/app/adapter/ms/bing.py", line 47, in __init__
    chatgpt-qq-chatgpt-1     |     self.bot = EdgeChatbot(cookies=self.cookieData, proxy=account.proxy)
    chatgpt-qq-chatgpt-1     |     │          │                   │    │                 │       └ None
    chatgpt-qq-chatgpt-1     |     │          │                   │    │                 └ BingCookiePath(cookie_content='[{"domain":".bing.com","expirationDate":1721308921,"hostOnly":false,"httpOnly":false,"name":"S...
    chatgpt-qq-chatgpt-1     |     │          │                   │    └ [{'domain': '.bing.com', 'expirationDate': 1721308921, 'hostOnly': False, 'httpOnly': False, 'name': 'SRCHUSR', 'path': '/', ...
    chatgpt-qq-chatgpt-1     |     │          │                   └ <adapter.ms.bing.BingAdapter object at 0x7f5c4269b7d0>
    chatgpt-qq-chatgpt-1     |     │          └ <class 'EdgeGPT.Chatbot'>
    chatgpt-qq-chatgpt-1     |     └ <adapter.ms.bing.BingAdapter object at 0x7f5c4269b7d0>
    chatgpt-qq-chatgpt-1     | 
    chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/EdgeGPT.py", line 710, in __init__
    chatgpt-qq-chatgpt-1     |     _Conversation(self.proxy, cookies=cookies),
    chatgpt-qq-chatgpt-1     |     │             │    │              └ [{'domain': '.bing.com', 'expirationDate': 1721308921, 'hostOnly': False, 'httpOnly': False, 'name': 'SRCHUSR', 'path': '/', ...
    chatgpt-qq-chatgpt-1     |     │             │    └ None
    chatgpt-qq-chatgpt-1     |     │             └ <EdgeGPT.Chatbot object at 0x7f5c426bb250>
    chatgpt-qq-chatgpt-1     |     └ <class 'EdgeGPT._Conversation'>
    chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/EdgeGPT.py", line 437, in __init__
    chatgpt-qq-chatgpt-1     |     raise Exception("Authentication failed")
    chatgpt-qq-chatgpt-1     | 
    chatgpt-qq-chatgpt-1     | Exception: Authentication failed

**Comment by liu2-3zhi** [comment]
问题解决了，解决办法：修改代理软件，跳过证书验证
