### ISSUE TITLE
[BUG] 请填写标题

### ISSUE THREAD

**Issue by q23339860** [lss233/chatgpt-mirai-qq-bot#497]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

![CL7@{9C4O@0R295A6NKTM38](https://user-images.githubusercontent.com/58033184/229324334-0573116b-4f38-48f7-b5f2-5d6c2708389c.png)

换了服务器依然出问题
![CL7@{9C4O@0R295A6NKTM38](https://user-images.githubusercontent.com/58033184/229324221-1f56b9e5-3d22-4a7d-abac-991fdbb52a2b.png)

**运行环境:**  
- 操作系统：OpenCloudOS 8.6
- Docker：Docker version 23.0.2, build 569dd73
- 项目版本：PULL最新版

**预期行为**  
登陆成功

**Comment by lss233** [comment]
重复 #496
