### ISSUE TITLE
[BUG] vits文字转语音，标点符号不能正确识别

### ISSUE THREAD

**Issue by aolanya** [lss233/chatgpt-mirai-qq-bot#498]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
![image](https://user-images.githubusercontent.com/129636844/229327203-08271d5e-e163-48c4-9684-2b7c9b7448e4.png)

**运行环境:**  
- 操作系统：Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-206-generic x8)
- Docker： Docker version 23.0.1, build a5ee5b1
- 项目版本：[v2.3.0-pre-1 VITS 语音转文字支持]

**复现步骤**  
描述你是如何触发这个 BUG 的
1.向机器人发送消息
2.机器人发送的文字正常，但语音不太对
3.查看moegoe日志，文字中的标点被转为乱码再转化为语音

**预期行为**  
标点符号应该被正确识别

**截图**
![image](https://user-images.githubusercontent.com/129636844/229327382-811d6a0a-2dd5-464f-93a1-3f400b2d8ea9.png)
![image](https://user-images.githubusercontent.com/129636844/229327412-91da157b-ac56-47da-8995-014ac6380b64.png)

**Comment by lss233** [comment]
这个分词问题目前暂时没什么办法解决。 如果使用 `lang="zh"` 的话会好一些。

**Comment by aolanya** [comment]
![image](https://user-images.githubusercontent.com/129636844/229328972-d5f15758-d491-49ca-a5a4-72ea253cf52a.png)
换成zh之后没有标点符号了

**Comment by Haibersut** [comment]
目前正则是全部过滤掉除了正常语言外的其他符号，后续考虑优化正则或者在服务端进行判断

**Comment by Haibersut** [comment]
现在可以将.\utils\vits_tts.py按一下步骤修改以解决标点符号不存在的问题：

1. 将vits_tts.py的第2行内容
```
import re
```
替换为
```
import regex as re
```
2. 将vits_tts.py的71行到93行替换为以下内容
```
def linguistic_process(self, text):
    if len(text) > 150:
        text = "这句话太长了，抱歉"

    lang = self.lang
    patterns = {
        "mix": r'[\u4e00-\u9fff]+|[\u3040-\u309f\u30a0-\u30ff]+|\w+|[^\u4e00-\u9fff\u3040-\u309f\u30a0-\u30ff\w]+',
        "zh": r'[\u4e00-\u9fff\p{P}]+',
        "ja": r'[\u3040-\u309f\u30a0-\u30ff\p{P}]+',
    }
    regex = patterns.get(lang, '')
    matches = re.findall(regex, text)
    if lang == "mix":
        matched_text = ''.join(
            '[ZH]' + match + '[ZH]' if re.search('[\u4e00-\u9fff]+', match) else
            '[JA]' + match + '[JA]' if re.search('[\u3040-\u309f\u30a0-\u30ff]+', match) else
            match if re.search('[^\u4e00-\u9fff\u3040-\u309f\u30a0-\u30ff\w]+', match) else
            "[ZH]还有一些我不会说，抱歉[ZH]"
            for match in matches
        )
    else:
        matched_text = ''.join(matches)

    return matched_text

```

**Comment by aolanya** [comment]
![image](https://user-images.githubusercontent.com/129636844/229330461-587b3882-3531-4767-ba44-e2bac6d726ae.png)
标点有了，但是字母会被吞掉

**Comment by Haibersut** [comment]
> ![image](https://user-images.githubusercontent.com/129636844/229330461-587b3882-3531-4767-ba44-e2bac6d726ae.png) 标点有了，但是字母会被吞掉

因为模型不支持英语，你可以找支持英语的模型，~~但是目前正则没考虑那么多~~，只匹配了中文和日语，其他的会被过滤掉不然不能正常输出或者很怪

**Comment by Haibersut** [comment]
看走眼了，你用的ZH模式下只允许中文字符，其他都会被过滤掉，JA模式也是如此，mix模式下支持中日混合。。。
所以具体可以等等后面修改服务端自动识别

**Comment by aolanya** [comment]
mix模式下，日文汉字会按照中文的读法被念出来

**Comment by Haibersut** [comment]
> mix模式下，日文汉字会按照中文的读法被念出来

这是因为日文的汉字的unicode跟中文的是一样的，这个没办法，所以具体可以等等后面修改服务端自动识别，以获得更好的语音体验

**Comment by aolanya** [comment]
好的，辛苦了

**Comment by lss233** [comment]
v2.3.0-pre-2 已发布，保留了标点符号。
