### ISSUE TITLE
[BUG] 登录时出现无效的 verifyKey 或其配置.'

### ISSUE THREAD

**Issue by Sparky579** [lss233/chatgpt-mirai-qq-bot#499]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：windows
- Docker： ？
- 项目版本：2.2.6.4

**复现步骤**  
描述你是如何触发这个 BUG 的
使用账号密码和access_token都会出现

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过
![image](https://user-images.githubusercontent.com/48359461/229329688-97f336b3-2154-4e52-b19a-bd9f530f655e.png)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
重复 #484

**Comment by Sparky579** [comment]
> 重复 #484

好像不太一样，我这里可以登录上账号，mirai那边收得到消息但chatgpt端没有，感觉是web连接的时候有问题

**Comment by lss233** [comment]
参考 https://github.com/lss233/chatgpt-mirai-qq-bot/issues/484#issuecomment-1491950748
