### ISSUE TITLE
有提高机器人响应速度的解决方案么

### ISSUE THREAD

**Issue by VCE1** [lss233/chatgpt-mirai-qq-bot#5]
在发送消息后，openai响应时间将近一分钟，延迟非常高，很难进行交互。我是部署在国内服务器上的。有什么解决方案吗？

**Comment by VCE1** [comment]
ok！明白了

**Comment by leihao** [comment]
隔壁项目看到提供了一个用cf works做一个反向代理的方案，是否考虑吸收这个方案？https://github.com/Quan666/ELFChatBot

**Comment by lss233** [comment]
> 隔壁项目看到提供了一个用cf works做一个反向代理的方案，是否考虑吸收这个方案？https://github.com/Quan666/ELFChatBot

支持这个操作。稍后我更新一下文档介绍一下代理的配置方法。

**Comment by lss233** [comment]
好吧，上游发的那个 PR 合并之后又被改掉了，所以暂时还不支持。  
可以先用[正向代理](https://github.com/lss233/chatgpt-mirai-qq-bot#%E6%AD%A3%E5%90%91%E4%BB%A3%E7%90%86)的方案 。反代的方案要等上游依赖支持了才行

> 隔壁项目看到提供了一个用cf works做一个反向代理的方案，是否考虑吸收这个方案？https://github.com/Quan666/ELFChatBot
