### ISSUE TITLE
快速部署包安装完修改config.json之后启动cmd显示系统找不到指定的路径

### ISSUE THREAD

**Issue by MisterQX** [lss233/chatgpt-mirai-qq-bot#50]
这是配置文件
![image](https://user-images.githubusercontent.com/51272049/207804220-5653d4f4-aa7d-48cc-96d4-e30360a5e8f5.png)
![image](https://user-images.githubusercontent.com/51272049/207804245-b5660959-5acf-49a1-a678-805f12eaa0f6.png)

**Comment by lss233** [comment]
可以把启动.cmd、chatgpt目录里的内容截图给我看看嘛

**Comment by MisterQX** [comment]
![image](https://user-images.githubusercontent.com/51272049/207824413-af52a829-3383-461d-a842-67cde45c8a4f.png)

**Comment by lss233** [comment]
其实就是你截图里面那个 `启动.cmd`，只是放错位置了。
v1.4.3.1 已修复此问题。
