### ISSUE TITLE
[BUG] 使用VITS版本语音下载失败

### ISSUE THREAD

**Issue by GTian28** [lss233/chatgpt-mirai-qq-bot#502]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
文字转语音没有问题，也能收到。但是我发送语音后，go-cqhttp日志显示语音下载失败。

**运行环境:**  
- 操作系统：win10
- Docker： ？
- 项目版本：v2.3.0-pre-1

**复现步骤**  
文字转语音没有问题，也能收到。但是我发送语音后，go-cqhttp日志显示语音下载失败。
1、我发送语音
2、go-http提示语音下载失败

**预期行为**  
下载语音，语音转文字，发送给chatgpt

**截图**  
![image](https://user-images.githubusercontent.com/115866194/229340927-42ae61bf-7610-43d3-8c6f-1691014c28fc.png)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
这看起来是一个 go-cqhttp 的bug，请向他们反馈。
另外，我们不支持接收语音

**Comment by GTian28** [comment]
> 这看起来是一个 go-cqhttp 的bug，请向他们反馈。 另外，我们不支持接收语音

哦哦，还不支持接收语音啊，只是暂时文字转语音的接口从azure换成VITS了。而且CjangCjengh/TTSModels的中文模型好少，只有中文+日语的模型，说的虽然是中文，但日语味儿太浓了。。
