### ISSUE TITLE
[Feature] 希望能新增一个命令切换音色的功能

### ISSUE THREAD

**Issue by magisk317** [lss233/chatgpt-mirai-qq-bot#503]

**Comment by lss233** [comment]
你好，切换音色的命令是： `切换音色 音色的ID或名字`  
在vits下是角色ID，在azure下是名字。

**Comment by magisk317** [comment]
> 你好，切换音色的命令是： `切换音色 音色的ID或名字` 在vits下是角色ID，在azure下是名字。

666666666666666666666，试了下，可以

**Comment by magisk317** [comment]
试了下，好像还是提示不太行，提示切换成功，但是实际还是原来的音色，重新加载配置也不行。。。

**Comment by magisk317** [comment]
> 试了下，好像还是不太行，提示切换成功，但是实际还是原来的音色，重新加载配置也不行。。。

看了下文档，还有个`切换语音`的命令，这个好使
