### ISSUE TITLE
api账号登不上，切换ai命令报错

### ISSUE THREAD

**Issue by cyclone12314** [lss233/chatgpt-mirai-qq-bot#504]
我是用Linux 一键脚本搭的，有几个问题
chagpt api账号获取不了，配置文件应该没啥问题。
![api key](https://user-images.githubusercontent.com/124062140/229349986-49568574-b267-416f-804c-64e7c3deef35.png)

切换 ai的命令报错了，还有就是，我想改一下修改文本模式，图像模式的命令，改成其他的，该怎么改啊，用一键脚本部署到Linux后不晓得代码放哪里的

![774E6794FD5D40827E52B1628BA0099E](https://user-images.githubusercontent.com/124062140/229349762-00025b4d-a115-4257-8d50-21e138f08720.jpg)

**Comment by lss233** [comment]
请按照模板填写 issue。
