### ISSUE TITLE
一直提示请求太多，一小时后再试

### ISSUE THREAD

**Issue by R1nkwh** [lss233/chatgpt-mirai-qq-bot#51]
![image](https://user-images.githubusercontent.com/111223971/207837356-620f6f21-68df-4087-befc-b5b0ab572afa.png)
第一句话还可以回我，然后紧接着第二个问题就开始出现这个，重置会话也无效

**Comment by R1nkwh** [comment]
等待足够长的时间后，依旧只能回复第一句话

**Comment by lss233** [comment]
OpenAI 的问题，无法解决。
