### ISSUE TITLE
[Feature] 完全免费的微软文字转语音的功能

### ISSUE THREAD

**Issue by joe12801** [lss233/chatgpt-mirai-qq-bot#510]

**Comment by joe12801** [comment]
https://github.com/rany2/edge-tts   
完全免费 不用密钥  可以考虑接入QQ机器人

**Comment by ZS629** [comment]
这个不好说，不开源谁也不知道后面会不会开始收费

**Comment by ZS629** [comment]
看错了，这是GitHub的链接![038C0FBE](https://user-images.githubusercontent.com/127756463/229389333-fe0edad9-f458-4b26-b5dd-ab985d1a6c04.png)

**Comment by joe12801** [comment]
这是免费开源的，我测试过，管用，不用钱
