### ISSUE TITLE
[Feature] 建议画图功能对接多个平台

### ISSUE THREAD

**Issue by ZS629** [lss233/chatgpt-mirai-qq-bot#511]
![image](https://user-images.githubusercontent.com/127756463/229388430-6dc25623-fd16-4887-923a-d5380f096693.png)

如图，画图功能如果能对接多个平台就好了

比如：

DALL-E还有其它的免费的AI画图平台（包括但不限于MidJourney）

**Comment by lss233** [comment]
有需要你可以自己发 PR。  GO-CQHTTP 和 Mirai 也有很多别的画图插件，可以自己加。

**Comment by ZS629** [comment]
好的
