### ISSUE TITLE
[BUG] OneBot平台下，群聊消息里机器人会丢弃掉回复机器人的消息，即无法作出回复。

### ISSUE THREAD

**Issue by zhmou** [lss233/chatgpt-mirai-qq-bot#519]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
群聊消息里机器人会丢弃掉回复机器人的消息

**运行环境:**  
- 操作系统：Windows 11 / Linux下
- Docker： 无
- 项目版本：release/v2.2.6，把platforms/onebot_bot.py替换为 [目前最新的onebot_bot,py](https://github.com/lss233/chatgpt-mirai-qq-bot/blob/aa16fe3e2e368f21969f5090b84baf640a357364/platforms/onebot_bot.py) 依旧能复现此问题。
- go-cqhttp版本：[v1.0.0-rc5](https://github.com/Mrs4s/go-cqhttp/releases/tag/v1.0.0-rc5)

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 在群聊中对机器人所发出的消息进行回复。

**预期行为**  
类似Mirai，机器人能正确对回复它的消息进行处理。

**截图**  
在群聊中对机器人所发的消息进行回复：
![LZ 1QUPG80~{_%JID2$SKMR](https://user-images.githubusercontent.com/43105172/229405892-9a4360fd-d30d-4b98-837b-320be1da30dc.png)
控制台中显示丢弃了这条消息：
![image](https://user-images.githubusercontent.com/43105172/229405769-bf8109c7-dc70-4c15-9361-6dedd3fb31c9.png)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
请修改你的 go-cqhttp 设置，让它在上报消息时不要带上 `[CQ:reply,id=xxx]`

**Comment by zhmou** [comment]
> 请修改你的 go-cqhttp 设置，让它在上报消息时不要带上 `[CQ:reply,id=xxx]`

抱歉，我在go-cqhttp的配置文件config.yml中似乎没有看到这项设置。自己实验了一下，用了一个比较hardcode的手段解决了这个问题：
在这里：
https://github.com/lss233/chatgpt-mirai-qq-bot/blob/aa16fe3e2e368f21969f5090b84baf640a357364/platforms/onebot_bot.py#L61
把这里的条件替换成
```
if text_segment and not text_segment.startswith('[CQ:reply,'):
```
暂时还没有发现其它影响。

**Comment by lss233** [comment]
下一版本修复
