### ISSUE TITLE
启动后报错

### ISSUE THREAD

**Issue by TaoXiaoBai** [lss233/chatgpt-mirai-qq-bot#52]
`Traceback (most recent call last):
  File "I:\quickstart-windows-amd64\chatgpt\bot.py", line 19, in <module>
    import chatbot
  File "I:\quickstart-windows-amd64\chatgpt\chatbot.py", line 1, in <module>
    from revChatGPT.revChatGPT import AsyncChatbot, generate_uuid
  File "I:\quickstart-windows-amd64\chatgpt\python3.9\lib\site-packages\revChatGPT\revChatGPT.py", line 14, in <module>
    from playwright.async_api import async_playwright
  File "I:\quickstart-windows-amd64\chatgpt\python3.9\lib\site-packages\playwright\async_api\__init__.py", line 25, in <module>
    import playwright.async_api._generated
  File "I:\quickstart-windows-amd64\chatgpt\python3.9\lib\site-packages\playwright\async_api\_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "I:\quickstart-windows-amd64\chatgpt\python3.9\lib\site-packages\playwright\_impl\_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "I:\quickstart-windows-amd64\chatgpt\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 23, in <module>
    from greenlet import greenlet
  File "I:\quickstart-windows-amd64\chatgpt\python3.9\lib\site-packages\greenlet\__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ImportError: DLL load failed while importing _greenlet: 找不到指定的模块。`

**Comment by lss233** [comment]
重新初始化下看看，估计是初始化的时候有东西丢了

**Comment by TaoXiaoBai** [comment]
> 重新初始化下看看，估计是初始化的时候有东西丢了

重新初始化了好几次，还是一样的结果...

**Comment by Micor5oft** [comment]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\quickstart-windows-amd64\chatgpt\bot.py", line 19, in <module>
    import chatbot
  File "C:\Users\Administrator\Desktop\quickstart-windows-amd64\chatgpt\chatbot.py", line 15, in <module>
    config = Config.parse_obj(json.loads(str(guessed_json)))
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 9 (char 50)

**Comment by Micor5oft** [comment]
chuehihuajici dousuizheyang

**Comment by lss233** [comment]
> Traceback (most recent call last): File "C:\Users\Administrator\Desktop\quickstart-windows-amd64\chatgpt\bot.py", line 19, in import chatbot File "C:\Users\Administrator\Desktop\quickstart-windows-amd64\chatgpt\chatbot.py", line 15, in config = Config.parse_obj(json.loads(str(guessed_json))) File "json__init__.py", line 346, in loads File "json\decoder.py", line 337, in decode File "json\decoder.py", line 353, in raw_decode json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 9 (char 50)

config.json 有语法问题

**Comment by Micor5oft** [comment]
> Traceback (most recent call last): File "C:\Users\Administrator\Desktop\quickstart-windows-amd64\chatgpt\bot.py", line 19, in import chatbot File "C:\Users\Administrator\Desktop\quickstart-windows-amd64\chatgpt\chatbot.py", line 15, in config = Config.parse_obj(json.loads(str(guessed_json))) File "json__init__.py", line 346, in loads File "json\decoder.py", line 337, in decode File "json\decoder.py", line 353, in raw_decode json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 9 (char


> > Traceback (most recent call last): File "C:\Users\Administrator\Desktop\quickstart-windows-amd64\chatgpt\bot.py", line 19, in import chatbot File "C:\Users\Administrator\Desktop\quickstart-windows-amd64\chatgpt\chatbot.py", line 15, in config = Config.parse_obj(json.loads(str(guessed_json))) File "json__init__.py", line 346, in loads File "json\decoder.py", line 337, in decode File "json\decoder.py", line 353, in raw_decode json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 9 (char 50)
> 
> config.json 有语法问题

"session_token": 后边的token超大一串 换了好几行 不知道是不是这个的问题 token需要加引号吗”

**Comment by lss233** [comment]
> > Traceback (most recent call last): File "C:\Users\Administrator\Desktop\quickstart-windows-amd64\chatgpt\bot.py", line 19, in import chatbot File "C:\Users\Administrator\Desktop\quickstart-windows-amd64\chatgpt\chatbot.py", line 15, in config = Config.parse_obj(json.loads(str(guessed_json))) File "json__init__.py", line 346, in loads File "json\decoder.py", line 337, in decode File "json\decoder.py", line 353, in raw_decode json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 9 (char
> 
> > > Traceback (most recent call last): File "C:\Users\Administrator\Desktop\quickstart-windows-amd64\chatgpt\bot.py", line 19, in import chatbot File "C:\Users\Administrator\Desktop\quickstart-windows-amd64\chatgpt\chatbot.py", line 15, in config = Config.parse_obj(json.loads(str(guessed_json))) File "json__init__.py", line 346, in loads File "json\decoder.py", line 337, in decode File "json\decoder.py", line 353, in raw_decode json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 9 (char 50)
> > 
> > 
> > config.json 有语法问题
> 
> "session_token": 后边的token超大一串 换了好几行 不知道是不是这个的问题 token需要加引号吗”

那就改成不换行的。引号肯定要加……
https://jsonlint.com/
可以在这里验证你的 JSON

**Comment by Micor5oft** [comment]
> > > Traceback (most recent call last): File "C:\Users\Administrator\Desktop\quickstart-windows-amd64\chatgpt\bot.py", line 19, in import chatbot File "C:\Users\Administrator\Desktop\quickstart-windows-amd64\chatgpt\chatbot.py", line 15, in config = Config.parse_obj(json.loads(str(guessed_json))) File "json__init__.py", line 346, in loads File "json\decoder.py", line 337, in decode File "json\decoder.py", line 353, in raw_decode json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 9 (char
> > 
> > 
> > > > Traceback (most recent call last): File "C:\Users\Administrator\Desktop\quickstart-windows-amd64\chatgpt\bot.py", line 19, in import chatbot File "C:\Users\Administrator\Desktop\quickstart-windows-amd64\chatgpt\chatbot.py", line 15, in config = Config.parse_obj(json.loads(str(guessed_json))) File "json__init__.py", line 346, in loads File "json\decoder.py", line 337, in decode File "json\decoder.py", line 353, in raw_decode json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 9 (char 50)
> > > 
> > > 
> > > config.json 有语法问题
> > 
> > 
> > "session_token": 后边的token超大一串 换了好几行 不知道是不是这个的问题 token需要加引号吗”
> 
> 那就改成不换行的。引号肯定要加…… https://jsonlint.com/ 可以在这里验证你的 JSON

搞定了，原来是填自己qq的时候把逗号弄丢了。感谢美女！

**Comment by Micor5oft** [comment]
为什么会启动chromium浏览器的无痕模式呢？我用谷歌账号登录chatgpt，提示浏览器不安全，被拒绝登录了

**Comment by Micor5oft** [comment]
> 为什么会启动chromium浏览器的无痕模式呢？我用谷歌账号登录chatgpt，提示浏览器不安全，被拒绝登录了

服务器是winserver 2022

**Comment by lss233** [comment]
请更新至最新版，然后重试。如果还有问题，请重新打开此 issue。
