### ISSUE TITLE
API key余额查询失败导致无法使用API key

### ISSUE THREAD

**Issue by clark-2468** [lss233/chatgpt-mirai-qq-bot#521]
Windows10
就是没法用API key登录OpenAI了，感觉像是官方更改了拉取余额的接口？可能需要改一些文件？我2周前还能用的，这中间没动过啥
这个错误很好理解就是从OpenAI那里没拉回来值，所以比较出错了。能不能把比较这一步删了
"I am unable to log in to OpenAI using my API key. It seems like the official interface for checking my balance has been changed. Perhaps I need to modify some files? I was able to use it two weeks ago and haven't made any changes since then. The error is easy to understand as it indicates that the value was not retrieved from OpenAI, causing the error. Is it possible to skip the comparison step?"
(translated by CHATGPT)

 File "C:\ProgramData\Anaconda3\envs\qqgpt\chatgpt\manager\bot.py", line 418, in __login_openai_apikey
    if int(total_available) <= 0:
           └ None

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

![image](https://user-images.githubusercontent.com/39589318/229434499-d50e4585-19f0-4579-911b-fd0a3d3f874e.png)

![image](https://user-images.githubusercontent.com/39589318/229434634-26c10aaf-45f8-48be-8a49-4121b257f4b1.png)

**Comment by lss233** [comment]
你好，这部分代码已经删除了，请下载最新版，谢谢。
