### ISSUE TITLE
[BUG] httpx.ReadTimeout: The read operation timed out

### ISSUE THREAD

**Issue by Moonkey233** [lss233/chatgpt-mirai-qq-bot#522]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
![image](https://user-images.githubusercontent.com/69099850/229499126-45c2bfda-67f6-4e8f-9630-492bb133965d.png)
**运行环境:**  
- 操作系统：Windows
- Docker： NULL
- 项目版本：2.3.0 pre2

**复现步骤**  
正常获取bing cookie登录，bot无回复，控制台输出httpx.ReadTimeout: The read operation timed out

**截图**  
![image](https://user-images.githubusercontent.com/69099850/229499459-9e8ac943-6df2-477a-a89d-1aff7e2efe82.png)

**Comment by lss233** [comment]
上个代理吧，或者反代。参考项目教程文档。
