### ISSUE TITLE
[BUG] 按照教程走的，退出登录程序后不能监听

### ISSUE THREAD

**Issue by LuvQi** [lss233/chatgpt-mirai-qq-bot#524]
**提交 issue 前，请先确认：**
- [ 是] 我已看过 **FAQ**，此问题不在列表中
- [是 ] 我已看过其他 issue，他们不能解决我的问题 
- [ 是] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况
退出mirai程序后，重新启动chatgpt程序，但是这个时候我登录不是已经退了吗，那么QQ机器人也接收不了信息啊。最后我看了一下日志信息，发现并没有mirai运行的信息，但是chatgpt能登录
![image](https://user-images.githubusercontent.com/128845248/229596748-ba18fa5a-6a1c-4f41-b7f0-8610ed646763.png)

![image](https://user-images.githubusercontent.com/128845248/229597560-6d1af6db-d77d-45ba-b0fe-2c9332cb5795.png)
发送信息的时候这里没有相应的信息

我在windows上面可以开两个窗口，一个运行登录程序，一个运行chatgpt程序，这样是可以的
但是在服务器上面应该怎么弄呢

**运行环境:**  
- 操作系统：centos 7.9
- Docker： 23.0.2
- 项目版本：？

**Comment by LuvQi** [comment]
![image](https://user-images.githubusercontent.com/128845248/229598048-8af9715b-faee-493a-bd65-5ee1cd46a43b.png)
mirai能收到信息，项目版本是2.3.0

**Comment by LuvQi** [comment]
![image](https://user-images.githubusercontent.com/128845248/229601027-fb164ca5-e648-45c8-9b96-e5aace22d3a5.png)
就是每次都会这样，QQ退出了就收不到消息

**Comment by LuvQi** [comment]
我开了两个终端，然后docker容器变成这样了
![image](https://user-images.githubusercontent.com/128845248/229602540-d8e119f8-1a76-47eb-89f1-d53ff3079538.png)

**Comment by lss233** [comment]
你的截图很微妙地避开了所有关键日志。请重新发送完整的日志。
