### ISSUE TITLE
[BUG] 使用MoeGoe-Simple-API服务进行文字转换语音时出现故障.

### ISSUE THREAD

**Issue by AILANTEL** [lss233/chatgpt-mirai-qq-bot#531]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：windows11 
- Docker： ？
- 项目版本：2.3.0 pre-2

**复现步骤**  
描述你是如何触发这个 BUG 的
在2023/4/4之后在 windows11 WSL2 ubuntu下载拉取最新的MoeGoe-Simple-API服务后接入到机器人，机器人报错。
![_PUK89WJNQ9N0N)N%MG MB4](https://user-images.githubusercontent.com/95335008/229744261-afcb575f-1459-4fe3-9063-1dd2c39cea23.png)

**预期行为**  
应该正常向qq输出语音。

**截
![YMI8D1YF$1Y)N2{OMS52( F](https://user-images.githubusercontent.com/95335008/229744534-94e564bd-9cc1-4b98-85ca-d60fbcfef139.png)
图**  
在服务机进行测试显示语音服务在docker上正常运作。

**其他内容**  
与MoeGoe-Simple-API的开发者取得了联系，问题疑似出在最近一次更新上。

**Comment by lss233** [comment]
会在下个版本跟进

**Comment by Artrajz** [comment]
有个临时的解决方法，在vits_tts.py中的第29行
`result = self.check_id_exists(json_array, integer_number)`
改成
`result = self.check_id_exists(json_array["VITS"], integer_number)`
已测试可以正常使用

**Comment by Haibersut** [comment]
你也可以把位于./utils/vits_tts.py中的29行注释掉就行，也就是result = self.check_id_exists(json_array, integer_number)

**Comment by AILANTEL** [comment]
经测试可用，本地平台运行无障碍，问题已解决.

**Comment by lss233** [comment]
请保持此 issue 为开启状态，直到修复版发布。
