### ISSUE TITLE
[Feature] 部分账号使用bingAI提示Authentication failed. You have not been accepted into the beta.的解决方法

### ISSUE THREAD

**Issue by meixiayvmeiyisi** [lss233/chatgpt-mirai-qq-bot#537]
我之前在这个项目上使用bing一直提示Authentication failed. You have not been accepted into the beta.
![image](https://user-images.githubusercontent.com/35397289/229816575-4d68c799-8bbf-4aa3-9717-dc814e99fe00.png)
但我单独使用"https://github.com/acheong08/EdgeGPT"是一切正常，今天我看了下这个项目调用的代码逻辑，我之前使用"https://github.com/acheong08/EdgeGPT"的使用都是使用的json文件读取的是一个完整的json字符串，
![image](https://user-images.githubusercontent.com/35397289/229817752-2c3df117-8bbf-412c-a78b-e23aa79c8d9e.png)
这个项目直接使用的是一个键值对的字符串，我尝试修改了下bing.py文件，来实现在配置里直接写json字符串，
![image](https://user-images.githubusercontent.com/35397289/229820561-0dfd1b62-fe10-40eb-9d67-f3cd4d2bc508.png)
![image](https://user-images.githubusercontent.com/35397289/229818678-d0027a80-24c1-4a96-9601-96e2104d6593.png)
修改之后bingAI可以正常工作了。
![image](https://user-images.githubusercontent.com/35397289/229819218-d58c0a9d-4c9f-4445-8c1b-9da1cc1dcc59.png)
我感觉可能有的账号光有cookie的键值对的话不行，所以才会提示Authentication failed. You have not been accepted into the beta.，bing的配置项希望可以同时支持配置键值对和json字符串，让两个中配置一个就能运行。

**Comment by lss233** [comment]
居然有这种事情！我改改

**Comment by lss233** [comment]
实际上原始 JSON 传入之后， EdgeGPT 解析时仍然是拆出 name 和 value 进行解析。   我认为问题的本质原因是目前的 Cookie 获取方法有问题，缺少了一些 HttpOnly 的 Cookie。

**Comment by meixiayvmeiyisi** [comment]
好吧，我json的cookie是用Cookie Editor插件提取的，键值对是控制台获取的，并没有对比两边的cookie数量是否一致，单纯的以为是用到的有键值对以外的参数。
