### ISSUE TITLE
chatgpt和mirai连接问题。

### ISSUE THREAD

**Issue by ClISOK** [lss233/chatgpt-mirai-qq-bot#538]
mirai了解正常，可接受到信息。但打开chatgpt.cmd到最后一步一直连接不上。config和mirai的配置是正向传输，默认的没有改动。但是就是连不上。
![Uploading -42167fcdbe219bb1.png…]()

**Comment by lss233** [comment]
图片加载失败

**Comment by ClISOK** [comment]
![Uploading -42167fcdbe219bb1.png…]()
