### ISSUE TITLE
在Ubuntu上使用docker部署后打开:14500端口提示400错误

### ISSUE THREAD

**Issue by imouup** [lss233/chatgpt-mirai-qq-bot#54]
![image](https://user-images.githubusercontent.com/61614535/208278821-54973c2a-cf1b-4ed5-b6ea-5670999bc5e8.png)

</br>

终端输出：
> `Waiting for xpra to start
> 
> Warning: running as root
> 2022-12-18 02:40:43,340 Warning: cannot enable SSH socket upgrades
> 2022-12-18 02:40:43,340  No module named 'paramiko'
> 2022-12-18 02:40:43,340 created tcp socket '0.0.0.0:14500'
> 2022-12-18 02:40:43,343 no uinput module (not usually needed)
> 2022-12-18 02:40:44,555 pointer device emulation using XTest
> 2022-12-18 02:40:44,605 Error: cannot find the html web root
> 2022-12-18 02:40:44,605  '/usr/local/share/xpra/www' does not exist
> 2022-12-18 02:40:44,605  install the `xpra-html5` package
> 2022-12-18 02:40:44,606 wrote pid 7 to '/tmp/99/server.pid'
> 2022-12-18 02:40:44,625 Warning: socket directory '/tmp/99'
> 2022-12-18 02:40:44,625  expected permissions 700 but found 750
> 2022-12-18 02:40:44,626 created unix domain socket '/run/user/1000/xpra/iznyaku-99'
> 2022-12-18 02:40:44,626 created unix domain socket '/tmp/99/socket'
> 2022-12-18 02:40:44,626 xvfb pid=12
> 2022-12-18 02:40:44,689 Warning: cannot watch for application menu changes without pyinotify:
> 2022-12-18 02:40:44,691  No module named 'pyinotify'
> 2022-12-18 02:40:44,701 Warning: cannot load menu data
> 2022-12-18 02:40:44,701  No module named 'xdg'
> 2022-12-18 02:40:44,706 Warning: webcam forwarding is disabled
> 2022-12-18 02:40:44,706  the virtual video directory '/sys/devices/virtual/video4linux' was not found
> 2022-12-18 02:40:44,706  make sure that the 'v4l2loopback' kernel module is installed and loaded
> 2022-12-18 02:40:44,706  or use the 'webcam=no' option
> 2022-12-18 02:40:44,706 found 0 virtual video devices for webcam forwarding
> 2022-12-18 02:40:44,817 1.8GB of system memory
> 2022-12-18 02:40:45,012 Warning: OpenGL support check failed:
> 2022-12-18 02:40:45,012  unknown error
> 2022-12-18 02:40:45,014 xpra is ready.
> 2022-12-18 02:40:45,015 xpra X11 seamless version 4.4.3-r0 64-bit
> 2022-12-18 02:40:45,015  uid=0 (root), gid=0 (root)
> 2022-12-18 02:40:45,015  running with pid 7 on Linux Debian 11 bullseye
> 2022-12-18 02:40:45,015  connected to X11 display :99 with 24 bit colors
> 2022-12-18 02:40:53.881 | INFO     | chatbot:<module>:18 - 登录 OpenAI 中……
> 2022-12-18 02:40:53.881 | INFO     | chatbot:<module>:19 - 请在新打开的浏览器窗口中完成验证
> 2022-12-18 02:40:53.881 | INFO     | chatbot:<module>:21 - 如果您使用 xpra，请使用自己的浏览器访问 xpra 程序的端口，以访问到本程序启动的浏览器。`

**Comment by MWWQFSPG** [comment]
请问大佬怎么解决的

**Comment by imouup** [comment]
没有解决（笑哭）
