### ISSUE TITLE
[BUG] Poe刚获取的cookie p-b总是出现Poe Client Error

### ISSUE THREAD

**Issue by ZS629** [lss233/chatgpt-mirai-qq-bot#540]
Poe Client返回data为error

![image](https://user-images.githubusercontent.com/127756463/229979780-b76f4f8e-1c9c-43ab-92e6-c8a97e93f0e4.png)

其它的如ChatGPT API的方法是可以的

![image](https://user-images.githubusercontent.com/127756463/229979956-3351b27f-3f87-45d2-8b9e-7ee34d395f60.png)

**Comment by jijunhao** [comment]
升级poe-api到0.2.5版本

**Comment by ZS629** [comment]
更新了吗

**Comment by ZS629** [comment]
看到了，两小时前发布的

**Comment by bk1412** [comment]
> 

替换这个项目里的poe.py文件为poe-ai 0.2.5的poe.py就行了？

**Comment by bk1412** [comment]
> 升级poe-api到0.2.5版本

替换这个项目里的poe.py文件为poe-ai 0.2.5的poe.py就行了？

**Comment by ZS629** [comment]
我用最新版2.3.0覆盖了所有文件，然后按照教程把那两个旧版文件夹覆盖掉了最新版的

**Comment by ZS629** [comment]
还是不行
![image](https://user-images.githubusercontent.com/127756463/229985288-5068781c-f459-41d9-bbab-f1a03ac61962.png)

**Comment by bk1412** [comment]
> 还是不行 ![image](https://user-images.githubusercontent.com/127756463/229985288-5068781c-f459-41d9-bbab-f1a03ac61962.png)

服务器执行pip3 install poe-api==0.2.5

**Comment by bk1412** [comment]
@lss233 pip3 install poe-api==0.2.5，更新一下requirements.txt

**Comment by lss233** [comment]
fixed。

**Comment by ZS629** [comment]
执行了

![image](https://user-images.githubusercontent.com/127756463/230291615-e578310a-1c7b-4dfd-b3a2-40fa8b402ce5.png)

0.2.7了，我再试试

![image](https://user-images.githubusercontent.com/127756463/230291564-4c6f14ee-8fa0-477a-94f0-c7623e8ea0df.png)
