### ISSUE TITLE
[BUG] VITS 文字转语音报错

### ISSUE THREAD

**Issue by lingboshuiyue** [lss233/chatgpt-mirai-qq-bot#541]
**提交 issue 前，请先确认：**
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
照着文档 接入 vits 文字转语音功能，在拉取最新的 docker 镜像 lss233/moegoe-simple-api:latest 并进行相关配置后，无法读取到 speakers 的数据：
```json
{
    "HuBert-VITS": [],
    "VITS": [],
    "W2V2-VITS": []
}
```
将 config.py 进行映射后，读取数据正常，但接入 qq 后尝试进行语音转换时报错：
```json
{
    "HuBert-VITS": [],
    "VITS": [
        {
            "0": "綾地寧々"
        },
        {
            "1": "在原七海"
        },
        {
            "2": "小茸"
        },
        {
            "3": "唐乐吟"
        }
    ],
    "W2V2-VITS": []
}
```

![image](https://user-images.githubusercontent.com/24492313/229982030-38696548-a077-4ef1-86bf-64baf38a7133.png)

**运行环境:**  
- 操作系统：CentOS Linux release 8.5.2111
- Docker： Docker version 23.0.1
- 项目版本：v2.3.0

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 拉取最新docker 镜像 lss233/moegoe-simple-api:latest 
2. 照着文档进行 vits 语音功能接入
3. 无法读取到 speakers 数据，将config.py 进行映射后获取数据正常，但接入qq 时报错

**预期行为**  
能正常切换语音和语音转换

**截图**  
配置文件
chatgpt-mirai-qq-bot/config.cfg
![image](https://user-images.githubusercontent.com/24492313/229986022-8f9184bd-2582-4de7-aa62-fc51c40868bc.png)
moegoe-config.json
![image](https://user-images.githubusercontent.com/24492313/229986191-2e0ab247-fb3e-48c4-9acc-b3919fc7ec05.png)
moegoe-simple-api/config.py
![image](https://user-images.githubusercontent.com/24492313/229987440-86bd112a-1c8b-47cd-a2c1-ff58a72f7f94.png)

**其他内容**  
无

**Comment by tamakyi** [comment]
+1

**Comment by gudong-mengxi** [comment]
+1

**Comment by Haibersut** [comment]
收到，目前缓解措施如下：
将位于./utils下的vits_tts.py的第24行由
```
return json_dict.get(str(given_id), False)
```
改为
```
return given_id
```

**Comment by tamakyi** [comment]
![image](https://user-images.githubusercontent.com/25850853/230030463-975d3d6b-48da-464b-86a5-7034de1c0bea.png)
现在能用了，但是在返回的语音中一直会夹带“还有一些我不会说，抱歉”

**Comment by Haibersut** [comment]
> ![image](https://user-images.githubusercontent.com/25850853/230030463-975d3d6b-48da-464b-86a5-7034de1c0bea.png) 现在能用了，但是在返回的语音中一直会夹带“还有一些我不会说，抱歉”

已知问题，因为存在多个不是zh或者ja的字符串就会被替换，如果你想的话可以把110行的 "[ZH]还有一些我不会说，抱歉[ZH]"替换为""，这个后续版本会优化

**Comment by gudong-mengxi** [comment]
> 收到，目前缓解措施如下： 将位于./utils下的vits_tts.py的第24行由
> 
> ```
> return json_dict.get(str(given_id), False)
> ```
> 
> 改为
> 
> ```
> return given_id
> ```

![image](https://user-images.githubusercontent.com/126675675/230051372-a0c68385-ba04-4aac-877a-452818d1f629.png)
修改vits_tts.py后出现新的问题
![image](https://user-images.githubusercontent.com/126675675/230051752-6eb7b170-2f03-4a23-ac8b-0e6fe0900f66.png)

**Comment by Enderbear** [comment]
> 问题已解决，将return json_dict.get(str(given_id), False)改为return json_dict[given_id].get(str(given_id), False)即可

感谢，情况和你相同，按照你的方法改暂时没问题了
给后面有相同情况的人说下，我的缓解方式是，在[MoeGoe-Simple-API]的code里下载config.py并进行配置，在本项目的code下位于./utils下载vits_tts.py并按照上述方法修改，然后把这两个文件上传到服务器端，并修改docker-compose.yaml进行映射，之后语音问题就得到了缓解
