### ISSUE TITLE
[BUG] 自己编写的预设不存在

### ISSUE THREAD

**Issue by yoshino2333** [lss233/chatgpt-mirai-qq-bot#545]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**版本是Releases包里最新的mirai一键部署版**

**config.cfg**
[presets.keywords]
"cixiaogui" = “presets/role-play/cixiaogui.txt”
"zhenxun" = "presets/role-play/zhenxun.txt"

这是config.cfg的配置，命令不管是中文还是英文都说不存在，zhenxun是我编写的预设，但说不存在，反而雌小鬼的预设是原先就有的，却能用

![图片](https://user-images.githubusercontent.com/105909793/230140672-4f21b5a1-09e9-4811-96be-d8dc147bd58f.png)

这是目录下存在着我编写好的预设文本

![QQ图片20230406001310](https://user-images.githubusercontent.com/105909793/230141151-40d30384-6bc3-4271-bf37-d261fda3a9d0.png)

以下是我的猜想

![QQ图片20230406001616](https://user-images.githubusercontent.com/105909793/230141792-ecf75253-6931-418b-ae75-e5e96d1ee26e.png)
会跟这个报错有关吗？

作者帮忙看看吧，我还是个小白不知道怎么解决

**Comment by yoshino2333** [comment]
> 看看 docker-compose.yaml
![QQ图片20230406005316](https://user-images.githubusercontent.com/105909793/230150299-43dd68c6-3afa-454e-80eb-856521011177.png)

**Comment by lss233** [comment]
启动的时候会显示出注册成功的预设，看看那部分日志

**Comment by yoshino2333** [comment]
> 启动的时候会显示出注册成功的预设，看看那部分日志
![QQ截图20230406012342](https://user-images.githubusercontent.com/105909793/230156784-260c8119-1909-41e1-8fcf-ecdc2ef7aaf3.png)

是这个吗？

**Comment by lss233** [comment]
是程序启动时输出的日志

**Comment by yoshino2333** [comment]
> 是程序启动时输出的日志

![QQ截图20230406012815](https://user-images.githubusercontent.com/105909793/230157716-e370eed9-7459-4854-bd41-dbf2bc634d49.png)
好像并没有。。。。
谢谢作者大大这么晚还回答我的问题

**Comment by lss233** [comment]
不是这里的日志，你这是 mirai的日志，要看的是 chatgpt 端启动的日志。

**Comment by yoshino2333** [comment]
> 不是这里的日志，你这是 mirai的日志，要看的是 chatgpt 端启动的日志。

还是不清楚在哪看chatgpt端启动的日志，我接入的是网页版的gpt，也不清楚预设部分的日志在哪wwwwww，纯小白

**Comment by lss233** [comment]
![IMG_20230406_024306](https://user-images.githubusercontent.com/8984680/230175307-f238007e-6641-4db7-9783-50a7a2d210de.jpg)

另外，你也可以试试不在配置文件里面写它。默认情况下会根据文件名自动注册。

**Comment by yoshino2333** [comment]
> ![IMG_20230406_024306](https://user-images.githubusercontent.com/8984680/230175307-f238007e-6641-4db7-9783-50a7a2d210de.jpg)
> 
> 另外，你也可以试试不在配置文件里面写它。默认情况下会根据文件名自动注册。

已解决，不在配置文件里面写入就行，谢谢作者的解答
