### ISSUE TITLE
[Feature] 希望VITS语音能增加微调参数

### ISSUE THREAD

**Issue by timeance** [lss233/chatgpt-mirai-qq-bot#546]
今天找模型的时候发现，对于部分模型来说，可以通过调节`noise`和`noisew`参数显著提升语音的质量。

请问可以考虑将这两个参数加入配置文件吗？

例如这里有个在线合成的demo，随便选个角色，然后将两个noice设置为0.4，能获得不错的效果。https://huggingface.co/spaces/sayashi/vits-uma-genshin-honkai

**Comment by lss233** [comment]
这个东西我觉得交给 VITS 端来做比较合适。

**Comment by timeance** [comment]
就是希望调用语音请求时，可以附加这两个参数。目前使用的 VITS 推理端已经支持这两个可选参数。


尽管这两个参数的使用并不十分普遍，但在需要时，可以直接修改 VITS 端的 `app.py` 文件中的默认参数。
