### ISSUE TITLE
[Feature] 建议根据预设功能调整api方式下的tokens清理

### ISSUE THREAD

**Issue by Enderbear** [lss233/chatgpt-mirai-qq-bot#548]
昨天在测试预设功能时，出现对话内容过多后遗忘自身人设的现象。
我知道这是常见且正常的，但日志的tokens清理提示带给我一些思考：
也许可以在达到上限清理tokens的时候，保留人设部分的内容，而从对话部分开始进行清理，通过这种方式一定程度上改善机器人遗忘自身人设？
我翻阅了api.py文件，在第87行存在self.bot.conversation[self.session_id].pop(1)语句
个人能力水平有限，没能了解api状态预设文件的作用形式，不清楚到达上限开始清理token时是会把整个预设文件当成一次对话pop掉，还是从预设文件的第一句话开始pop。（个人猜测是后者）
继续猜测，如果是前者，可以直接将1改成2。如果是后者，则可以从预设文件内获取对话次数+1填入到这条语句中。而如果没开启预设模式就设置为1。
另一方面的猜测，也许某种程度上，通过这种方式保留人设，或许将最大tokens调小，也就是增加了人设部分在tokens所占的比例，提前清理了人设部分以外的对话记录的tokens，反而可能更好地改善机器人遗忘自身人设的现象？
个人简单测试了一下，因为不知道具体作用形式，我先将1改成了10，在日志提示达到最大tokens开始清理后，在维持人设上确实得到了显著改善
故提出这个功能建议，希望我的建议对项目有所帮助。

**Comment by lss233** [comment]
这确实是一个问题，下个版本看看能不能加入对这个的优化。
