### ISSUE TITLE
docker部署后报错

### ISSUE THREAD

**Issue by imouup** [lss233/chatgpt-mirai-qq-bot#55]
> root@iznyaku:~# docker run --name mirai-chatgpt-bot -e XPRA_PASSWORD=xxxxxx -v /home/yaziapps/chatgpt/config.json:/app/config.json --network host lss233/chatgpt-mirai-qq-bot:latest
> Waiting for xpra to start
> 
> Warning: running as root
> 2022-12-20 01:20:44,832 Warning: cannot enable SSH socket upgrades
> 2022-12-20 01:20:44,832  No module named 'paramiko'
> 2022-12-20 01:20:44,833 created tcp socket '0.0.0.0:14500'
> 2022-12-20 01:20:44,838 no uinput module (not usually needed)
> 2022-12-20 01:20:46,144 pointer device emulation using XTest
> 2022-12-20 01:20:46,228 Error: cannot find the html web root
> 2022-12-20 01:20:46,228  '/usr/local/share/xpra/www' does not exist
> 2022-12-20 01:20:46,228  install the `xpra-html5` package
> 2022-12-20 01:20:46,230 wrote pid 7 to '/tmp/99/server.pid'
> 2022-12-20 01:20:46,259 Warning: socket directory '/tmp/99'
> 2022-12-20 01:20:46,259  expected permissions 700 but found 750
> 2022-12-20 01:20:46,260 created unix domain socket '/run/user/1000/xpra/iznyaku-99'
> 2022-12-20 01:20:46,260 created unix domain socket '/tmp/99/socket'
> 2022-12-20 01:20:46,260 xvfb pid=12
> 2022-12-20 01:20:46,322 Warning: cannot watch for application menu changes without pyinotify:
> 2022-12-20 01:20:46,322  No module named 'pyinotify'
> 2022-12-20 01:20:46,330 Warning: cannot load menu data
> 2022-12-20 01:20:46,330  No module named 'xdg'
> 2022-12-20 01:20:46,394 Warning: webcam forwarding is disabled
> 2022-12-20 01:20:46,395  the virtual video directory '/sys/devices/virtual/video4linux' was not found
> 2022-12-20 01:20:46,396  make sure that the 'v4l2loopback' kernel module is installed and loaded
> 2022-12-20 01:20:46,396  or use the 'webcam=no' option
> 2022-12-20 01:20:46,397 found 0 virtual video devices for webcam forwarding
> 2022-12-20 01:20:46,604 1.8GB of system memory
> 2022-12-20 01:20:46,791 Warning: OpenGL support check failed:
> 2022-12-20 01:20:46,791  unknown error
> 2022-12-20 01:20:46,794 xpra is ready.
> 2022-12-20 01:20:46,794 xpra X11 seamless version 4.4.3-r0 64-bit
> 2022-12-20 01:20:46,795  uid=0 (root), gid=0 (root)
> 2022-12-20 01:20:46,795  running with pid 7 on Linux Debian 11 bullseye
> 2022-12-20 01:20:46,796  connected to X11 display :99 with 24 bit colors
> 2022-12-20 01:20:55,546 New tcp connection received
> 2022-12-20 01:20:55,548  from 'xxx.xxx.xxx.xxx:5920'
> 2022-12-20 01:20:55,548  on '0.0.0.0:14500'
> 2022-12-20 01:20:55.679 | INFO     | chatbot:<module>:18 - 登录 OpenAI 中……
> 2022-12-20 01:20:55.679 | INFO     | chatbot:<module>:19 - 请在新打开的浏览器窗口中完成验证
> 2022-12-20 01:20:55.679 | INFO     | chatbot:<module>:21 - 如果您使用 xpra，请使用自己的浏览器访问 xpra 程序的端口，以访问到本程序启动的浏览器。
> 2022-12-20 01:21:01,186 Error: tcp connection failed:
> 2022-12-20 01:21:01,186  packet from xxx.xxx.xxx.xxx:5875
> 2022-12-20 01:21:01,186  received on 0.0.0.0:14500
> 2022-12-20 01:21:01,186  this packet looks like a 'http' packet
> 2022-12-20 01:21:01,186  http upgrades are not enabled
> 2022-12-20 01:21:16,550 Error: connection timed out: tcp socket: 172.24.79.186:14500 <- xxx.xxx.xxx.xxx:5920
> 2022-12-20 01:21:16,550  after 21 seconds
> 2022-12-20 01:21:16,550  sent 0 bytes
> 2022-12-20 01:21:16,550  received 0 bytes

### 问题
**无法在浏览器打开http://ip:14500,无法使用VNCviewer连接**
**端口已开放**

**部署方法：使用了第二种部署方法（已安装mirai）**

**登录方式：OpenAI 半自动登录**
（如果用手动登录就会直接报错）

> /usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1649: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
>   return _Gtk_main(*args, **kwargs)
> 2022-12-20 01:26:15.340 | ERROR    | chatbot:<module>:38 - cf challenge fail
> Traceback (most recent call last):
> 
>   File "/app/bot.py", line 19, in <module>
>     import chatbot
> 
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> 
> > File "/app/chatbot.py", line 23, in <module>
>     bot = AsyncChatbot(config=config.openai.dict(exclude_none=True, by_alias=False), conversation_id=None, base_url=config.openai.base_url)
>           │                   │      │      │                                                                       │      │      └ 'https://chat.openai.com/'
>           │                   │      │      │                                                                       │      └ OpenAISessionTokenAuth(Authorization=None, proxy=None, base_url='https://chat.openai.com/', cf_clearance=None, user_agent=Non...
>           │                   │      │      │                                                                       └ Config(mirai=Mirai(qq=2841125587, api_key='INITKEYNR1v34o3', http_url='http://39.103.142.157:2345', ws_url='http://39.103.142...
>           │                   │      │      └ <cyfunction BaseModel.dict at 0x7ff0a1496790>
>           │                   │      └ OpenAISessionTokenAuth(Authorization=None, proxy=None, base_url='https://chat.openai.com/', cf_clearance=None, user_agent=Non...
>           │                   └ Config(mirai=Mirai(qq=2841125587, api_key='INITKEYNR1v34o3', http_url='http://39.103.142.157:2345', ws_url='http://39.103.142...
>           └ <class 'revChatGPT.revChatGPT.AsyncChatbot'>
> 
>   File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 116, in __init__
>     self.refresh_session()
>     │    └ <function AsyncChatbot.refresh_session at 0x7ff0a02d0ee0>
>     └ <revChatGPT.revChatGPT.AsyncChatbot object at 0x7ff0a03ade20>
>   File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 295, in refresh_session
>     asyncio.run(self.get_cf_cookies())
>     │       │   │    └ <function AsyncChatbot.get_cf_cookies at 0x7ff0a02d0f70>
>     │       │   └ <revChatGPT.revChatGPT.AsyncChatbot object at 0x7ff0a03ade20>
>     │       └ <function run at 0x7ff0a298bc10>
>     └ <module 'asyncio' from '/usr/local/lib/python3.9/asyncio/__init__.py'>
>   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>            │    │                  └ <coroutine object AsyncChatbot.get_cf_cookies at 0x7ff0a05946c0>
>            │    └ <function BaseEventLoop.run_until_complete at 0x7ff0a21d8790>
>            └ <_UnixSelectorEventLoop running=False closed=True debug=False>
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
>     return future.result()
>            │      └ <method 'result' of '_asyncio.Task' objects>
>            └ <Task finished name='Task-1' coro=<AsyncChatbot.get_cf_cookies() done, defined at /usr/local/lib/python3.9/site-packages/revC...
>   File "/usr/local/lib/python3.9/site-packages/revChatGPT/revChatGPT.py", line 390, in get_cf_cookies
>     raise Exception("cf challenge fail")
> 
> Exception: cf challenge fail
> 2022-12-20 01:26:15.346 | ERROR    | chatbot:<module>:39 - OpenAI 登录失败，可能是 session_token 过期或无法通过 CloudFlare 验证，建议歇息一下再重试。

**Comment by lss233** [comment]
> `2022-12-20 01:26:15.346 | ERROR | chatbot::39 - OpenAI 登录失败，可能是 session_token 过期或无法通过 CloudFlare 验证，建议歇息一下再重试。`
