### ISSUE TITLE
[Feature] 关于文本转语音功能的优化建议

### ISSUE THREAD

**Issue by SternChiri** [lss233/chatgpt-mirai-qq-bot#553]
- ~~希望可以用`语音模式`或类似的指令实现文本转语音功能的开关，有时候不想有语音时要到`config.py`中去改，改完还要重启，比较麻烦~~
- ~~希望可以实现在不同聊天中文本转语音功能的开启/关闭是独立的，即在一个群里会发送语音时，其他聊天不受影响~~

以上两个功能都存在，是我没有找到正确的使用方法（悲）

- 当开启语音模式时，自动将回答分割为多个短文本以保证VITS不会因为文本过长而放弃生成（如自动修改`config.py`中`buffer_delay: float = 5`）；当语音模式关闭时，`buffer_delay`恢复原始设定（我个人设定是120，因为更倾向于让它一次性说完）。

**Comment by lss233** [comment]
然而实际上就是这么设计的：https://github.com/lss233/chatgpt-mirai-qq-bot/wiki#5-%E5%88%87%E6%8D%A2%E8%AF%AD%E9%9F%B3-xxx

**Comment by SternChiri** [comment]
> 然而实际上就是这么设计的：https://github.com/lss233/chatgpt-mirai-qq-bot/wiki#5-%E5%88%87%E6%8D%A2%E8%AF%AD%E9%9F%B3-xxx

啊…是我没仔细看，因为我`切换语音`这个功能用不了（每次切换后仍为原音色），我就没管过这条指令……
第二条功能实现起来复杂嘛🤔

**Comment by lss233** [comment]
不同聊天中文本转语音功能的开启/关闭 本来就是独立的

**Comment by SternChiri** [comment]
> 不同聊天中文本转语音功能的开启/关闭 本来就是独立的

再次抱歉…是我没有认真测试，抱歉抱歉

**Comment by lss233** [comment]
改 buffer_delay 也不太行。 低于 15 会有 race condition 问题，    关于文本长度的问题已经反馈给 VITS Server 作者去改进了。

**Comment by SternChiri** [comment]
> 改 buffer_delay 也不太行。 低于 15 会有 race condition 问题， 关于文本长度的问题已经反馈给 VITS Server 作者去改进了。

明白了，作者大大辛苦了捏🌹
