### ISSUE TITLE
vist配置好之后，可以形成语音但是回复一段代码，如图所示

### ISSUE THREAD

**Issue by Alfred676** [lss233/chatgpt-mirai-qq-bot#558]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [ √] 我已看过其他 issue，他们不能解决我的问题 
- [ √] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：window11
- Docker： 无
- 项目版本：2.3.1

**复现步骤**  
描述你是如何触发这个 BUG 的
1配置vist
2配置好之后可以转换语音，但是出现如图编码
![1](https://user-images.githubusercontent.com/76623468/230409999-9af8510a-4438-41f1-b54f-af46d8645b46.png)

![2](https://user-images.githubusercontent.com/76623468/230410541-fc24c347-a901-4bed-aab2-e1c388e9e59f.png)

请问是什么原因呢

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
提供一下配置文件

**Comment by Alfred676** [comment]
![3](https://user-images.githubusercontent.com/76623468/230509377-ffdd9011-be38-436a-9c1c-a6f8b59fb6c8.png)
好的，下面是语音合成图![4](https://user-images.githubusercontent.com/76623468/230509903-60c44420-4b11-46ab-a9ed-c6f99dc69758.png)



> 提供一下配置文件

![3](https://user-images.githubusercontent.com/76623468/230509866-915861b1-ead4-4514-90e0-c6327b4d19de.png)
下面是语音合成
![Uploading 4.png…]()

**Comment by Alfred676** [comment]
> 提供一下配置文件

![3](https://user-images.githubusercontent.com/76623468/230509957-a7163675-a91a-4f27-961a-556356072063.png)
好的，下面是语音合成图
![4](https://user-images.githubusercontent.com/76623468/230509967-2de27d16-7e8d-4f30-a7e7-74218c016ee0.png)

**Comment by Alfred676** [comment]
用的go-cq

**Comment by lss233** [comment]
可以用最新版试试，另外  你还需要提供一下我们程序的日志。

**Comment by Artrajz** [comment]
> **提交 issue 前，请先确认：**
> 
> * [√] 我已看过 **FAQ**，此问题不在列表中
> * [ √] 我已看过其他 issue，他们不能解决我的问题
> * [ √] 我认为这不是 Mirai 或者 OpenAI 的 BUG
> 
> **表现** 描述 BUG 的表现情况
> 
> **运行环境:**
> 
> * 操作系统：window11
> * Docker： 无
> * 项目版本：2.3.1
> 
> **复现步骤** 描述你是如何触发这个 BUG 的 1配置vist 2配置好之后可以转换语音，但是出现如图编码 ![1](https://user-images.githubusercontent.com/76623468/230409999-9af8510a-4438-41f1-b54f-af46d8645b46.png)
> 
> ![2](https://user-images.githubusercontent.com/76623468/230410541-fc24c347-a901-4bed-aab2-e1c388e9e59f.png)
> 
> 请问是什么原因呢
> 
> **预期行为** 描述你认为正常情况下应该看见的情况
> 
> **截图** 相关日志、聊天记录的截图，没有可跳过
> 
> **其他内容** 此处填写其他内容，没有可跳过

gocqhttp的运行环境没有装ffmpeg
