### ISSUE TITLE
[BUG] 文字转VITS语音报错

### ISSUE THREAD

**Issue by K1nako0** [lss233/chatgpt-mirai-qq-bot#560]
上日志

chatgpt_1     | aiohttp.client_exceptions.InvalidURL: 101.33.231.208/speakers
chatgpt_1     | 2023-04-06 16:16:09.620 | INFO     | graia.ariadne.model:log:82 - 1439592902: [SEND][K1nako(1442017318)] <- 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。\n原因：101.33.231.208/speakers
chatgpt_1     | 2023-04-06 16:16:09.620 | DEBUG    | utils.text_to_speech:get_tts_voice:20 - [TextToSpeech] 开始转换语音 - /tmp/tmpuciggrxc.wav - friend-1442017318
chatgpt_1     | 2023-04-06 16:16:09.621 | ERROR    | graia.ariadne.util:loguru_exc_callback:76 - Exception:
chatgpt_1     | Traceback (most recent call last):
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 205, in request
chatgpt_1     |     await action(session_id, prompt, rendered, respond)
chatgpt_1     |           │      │           │       │         └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |           │      │           │       └ MessageChain([Plain(text='你好！有什么我可以为您提供帮助的吗？')])
chatgpt_1     |           │      │           └ '你好'
chatgpt_1     |           │      └ 'friend-1442017318'
chatgpt_1     |           └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x7fc248ede660>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 67, in call
chatgpt_1     |     await m.handle_respond(session_id, message, rendered, respond, n)
chatgpt_1     |           │ │              │           │        │         │        └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x7fc248ede700>
chatgpt_1     |           │ │              │           │        │         └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |           │ │              │           │        └ MessageChain([Plain(text='你好！有什么我可以为您提供帮助的吗？')])
chatgpt_1     |           │ │              │           └ '你好'
chatgpt_1     |           │ │              └ 'friend-1442017318'
chatgpt_1     |           │ └ <function Middleware.handle_respond at 0x7fc24aabdbc0>
chatgpt_1     |           └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x7fc24aab9410>
chatgpt_1     | 
chatgpt_1     |   File "/app/middlewares/middleware.py", line 12, in handle_respond
chatgpt_1     |     await action(session_id, prompt, rendered, respond)
chatgpt_1     |           │      │           │       │         └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |           │      │           │       └ MessageChain([Plain(text='你好！有什么我可以为您提供帮助的吗？')])
chatgpt_1     |           │      │           └ '你好'
chatgpt_1     |           │      └ 'friend-1442017318'
chatgpt_1     |           └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x7fc248ede700>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 67, in call
chatgpt_1     |     await m.handle_respond(session_id, message, rendered, respond, n)
chatgpt_1     |           │ │              │           │        │         │        └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x7fc248edf060>
chatgpt_1     |           │ │              │           │        │         └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |           │ │              │           │        └ MessageChain([Plain(text='你好！有什么我可以为您提供帮助的吗？')])
chatgpt_1     |           │ │              │           └ '你好'
chatgpt_1     |           │ │              └ 'friend-1442017318'
chatgpt_1     |           │ └ <function MiddlewareBaiduCloud.handle_respond at 0x7fc24aabe480>
chatgpt_1     |           └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x7fc24aab9390>
chatgpt_1     | 
chatgpt_1     |   File "/app/middlewares/baiducloud.py", line 86, in handle_respond
chatgpt_1     |     return await action(session_id, prompt, rendered, respond)
chatgpt_1     |                  │      │           │       │         └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |                  │      │           │       └ MessageChain([Plain(text='你好！有什么我可以为您提供帮助的吗？')])
chatgpt_1     |                  │      │           └ '你好'
chatgpt_1     |                  │      └ 'friend-1442017318'
chatgpt_1     |                  └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x7fc248edf060>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 67, in call
chatgpt_1     |     await m.handle_respond(session_id, message, rendered, respond, n)
chatgpt_1     |           │ │              │           │        │         │        └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x7fc248edf740>
chatgpt_1     |           │ │              │           │        │         └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |           │ │              │           │        └ MessageChain([Plain(text='你好！有什么我可以为您提供帮助的吗？')])
chatgpt_1     |           │ │              │           └ '你好'
chatgpt_1     |           │ │              └ 'friend-1442017318'
chatgpt_1     |           │ └ <function Middleware.handle_respond at 0x7fc24aabdbc0>
chatgpt_1     |           └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x7fc24aab9490>
chatgpt_1     | 
chatgpt_1     |   File "/app/middlewares/middleware.py", line 12, in handle_respond
chatgpt_1     |     await action(session_id, prompt, rendered, respond)
chatgpt_1     |           │      │           │       │         └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |           │      │           │       └ MessageChain([Plain(text='你好！有什么我可以为您提供帮助的吗？')])
chatgpt_1     |           │      │           └ '你好'
chatgpt_1     |           │      └ 'friend-1442017318'
chatgpt_1     |           └ <function handle_message.<locals>.wrap_respond.<locals>.call at 0x7fc248edf740>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 67, in call
chatgpt_1     |     await m.handle_respond(session_id, message, rendered, respond, n)
chatgpt_1     |           │ │              │           │        │         │        └ <function handle_message.<locals>.request.<locals>.<lambda> at 0x7fc248edfc40>
chatgpt_1     |           │ │              │           │        │         └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |           │ │              │           │        └ MessageChain([Plain(text='你好！有什么我可以为您提供帮助的吗？')])
chatgpt_1     |           │ │              │           └ '你好'
chatgpt_1     |           │ │              └ 'friend-1442017318'
chatgpt_1     |           │ └ <function MiddlewareTimeout.handle_respond at 0x7fc24aabe8e0>
chatgpt_1     |           └ <middlewares.timeout.MiddlewareTimeout object at 0x7fc24ce797d0>
chatgpt_1     | 
chatgpt_1     |   File "/app/middlewares/timeout.py", line 48, in handle_respond
chatgpt_1     |     await action(session_id, prompt, rendered, respond)
chatgpt_1     |           │      │           │       │         └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |           │      │           │       └ MessageChain([Plain(text='你好！有什么我可以为您提供帮助的吗？')])
chatgpt_1     |           │      │           └ '你好'
chatgpt_1     |           │      └ 'friend-1442017318'
chatgpt_1     |           └ <function handle_message.<locals>.request.<locals>.<lambda> at 0x7fc248edfc40>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 95, in respond
chatgpt_1     |     voice = await voice_task
chatgpt_1     |                   └ <Task finished name='Task-1387' coro=<get_tts_voice() done, defined at /app/utils/text_to_speech.py:13> exception=<InvalidURL...
chatgpt_1     | 
chatgpt_1     |   File "/app/utils/text_to_speech.py", line 25, in get_tts_voice
chatgpt_1     |     if await vits_api_instance.process_message(str(elem), output_file.name):
chatgpt_1     |              │                 │                   │      │           └ '/tmp/tmpq_wgc4ar.silk'
chatgpt_1     |              │                 │                   │      └ <tempfile._TemporaryFileWrapper object at 0x7fc24a1dbd10>
chatgpt_1     |              │                 │                   └ Plain(text='你好！有什么我可以为您提供帮助的吗？')
chatgpt_1     |              │                 └ <function VitsAPI.process_message at 0x7fc248eddda0>
chatgpt_1     |              └ <utils.vits_tts.VitsAPI object at 0x7fc24a1d9610>
chatgpt_1     | 
chatgpt_1     |   File "/app/utils/vits_tts.py", line 126, in process_message
chatgpt_1     |     await self.initialize()
chatgpt_1     |           │    └ <function VitsAPI.initialize at 0x7fc248edd800>
chatgpt_1     |           └ <utils.vits_tts.VitsAPI object at 0x7fc24a1d9610>
chatgpt_1     | 
chatgpt_1     |   File "/app/utils/vits_tts.py", line 19, in initialize
chatgpt_1     |     self.id = await self.voice_speakers_check()
chatgpt_1     |     │    │          │    └ <function VitsAPI.voice_speakers_check at 0x7fc248edda80>
chatgpt_1     |     │    │          └ <utils.vits_tts.VitsAPI object at 0x7fc24a1d9610>
chatgpt_1     |     │    └ None
chatgpt_1     |     └ <utils.vits_tts.VitsAPI object at 0x7fc24a1d9610>
chatgpt_1     | 
chatgpt_1     |   File "/app/utils/vits_tts.py", line 44, in voice_speakers_check
chatgpt_1     |     json_array = await self.get_json_array()
chatgpt_1     |                        │    └ <function VitsAPI.get_json_array at 0x7fc248edd9e0>
chatgpt_1     |                        └ <utils.vits_tts.VitsAPI object at 0x7fc24a1d9610>
chatgpt_1     | 
chatgpt_1     |   File "/app/utils/vits_tts.py", line 40, in get_json_array
chatgpt_1     |     async with session.post(url=url) as res:
chatgpt_1     |                │       │        └ '101.33.231.208/speakers'
chatgpt_1     |                │       └ <function ClientSession.post at 0x7fc24d130860>
chatgpt_1     |                └ <aiohttp.client.ClientSession object at 0x7fc248ef7d50>
chatgpt_1     | 
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
chatgpt_1     |     self._resp = await self._coro
chatgpt_1     |     │    │             │    └ <member '_coro' of '_BaseRequestContextManager' objects>
chatgpt_1     |     │    │             └ <aiohttp.client._RequestContextManager object at 0x7fc248f236d0>
chatgpt_1     |     │    └ <member '_resp' of '_BaseRequestContextManager' objects>
chatgpt_1     |     └ <aiohttp.client._RequestContextManager object at 0x7fc248f236d0>
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 508, in _request
chatgpt_1     |     req = self._request_class(
chatgpt_1     |           │    └ <class 'aiohttp.client_reqrep.ClientRequest'>
chatgpt_1     |           └ <aiohttp.client.ClientSession object at 0x7fc248ef7d50>
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
chatgpt_1     |     self.update_host(url)
chatgpt_1     |     │    │           └ URL('101.33.231.208/speakers')
chatgpt_1     |     │    └ <function ClientRequest.update_host at 0x7fc24d0a96c0>
chatgpt_1     |     └ <aiohttp.client_reqrep.ClientRequest object at 0x7fc24a1c3510>
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 364, in update_host
chatgpt_1     |     raise InvalidURL(url)
chatgpt_1     |           │          └ URL('101.33.231.208/speakers')
chatgpt_1     |           └ <class 'aiohttp.client_exceptions.InvalidURL'>
chatgpt_1     | 
chatgpt_1     | aiohttp.client_exceptions.InvalidURL: 101.33.231.208/speakers
chatgpt_1     | 
chatgpt_1     | 
chatgpt_1     | During handling of the above exception, another exception occurred:
chatgpt_1     | 
chatgpt_1     | 
chatgpt_1     | Traceback (most recent call last):
chatgpt_1     | 
chatgpt_1     |   File "/app/bot.py", line 46, in <module>
chatgpt_1     |     loop.run_until_complete(asyncio.gather(*bots))
chatgpt_1     |     │    │                  │       │       └ [<Task pending name='Task-4' coro=<start_task() running at /app/platforms/ariadne_bot.py:297> wait_for=<Task pending name='Ta...
chatgpt_1     |     │    │                  │       └ <function gather at 0x7fc24e5cbf60>
chatgpt_1     |     │    │                  └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>
chatgpt_1     |     │    └ <function BaseEventLoop.run_until_complete at 0x7fc24e03ce00>
chatgpt_1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt_1     | 
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
chatgpt_1     |     self.run_forever()
chatgpt_1     |     │    └ <function BaseEventLoop.run_forever at 0x7fc24e03cd60>
chatgpt_1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
chatgpt_1     |     self._run_once()
chatgpt_1     |     │    └ <function BaseEventLoop._run_once at 0x7fc24e03eb60>
chatgpt_1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
chatgpt_1     |     handle._run()
chatgpt_1     |     │      └ <function Handle._run at 0x7fc24e5839c0>
chatgpt_1     |     └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
chatgpt_1     |     self._context.run(self._callback, *self._args)
chatgpt_1     |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
chatgpt_1     |     │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt_1     |     │    │            │    └ <member '_callback' of 'Handle' objects>
chatgpt_1     |     │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt_1     |     │    └ <member '_context' of 'Handle' objects>
chatgpt_1     |     └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt_1     | > File "/usr/local/lib/python3.11/site-packages/graia/broadcast/__init__.py", line 191, in Executor
chatgpt_1     |     result = await run_always_await(target_callable, **parameter_compile_result)
chatgpt_1     |                    │                │                  └ {'app': <graia.ariadne.app.Ariadne object at 0x7fc24b61fa10>, 'target': Friend(id=1442017318, nickname='K1nako', remark='K1na...
chatgpt_1     |                    │                └ <function friend_message_listener at 0x7fc24a1bc4a0>
chatgpt_1     |                    └ <function run_always_await at 0x7fc24dde96c0>
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/graia/broadcast/utilles.py", line 34, in run_always_await
chatgpt_1     |     obj = await obj
chatgpt_1     |                 └ <coroutine object friend_message_listener at 0x7fc24a1d3ab0>
chatgpt_1     | 
chatgpt_1     |   File "/app/platforms/ariadne_bot.py", line 149, in friend_message_listener
chatgpt_1     |     await handle_message(
chatgpt_1     |           └ <function handle_message at 0x7fc24aabe5c0>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 254, in handle_message
chatgpt_1     |     await action(session_id, message.strip(), conversation_context, respond)
chatgpt_1     |           │      │           │       │        │                     └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |           │      │           │       │        └ <conversation.ConversationContext object at 0x7fc248e94b50>
chatgpt_1     |           │      │           │       └ <method 'strip' of 'str' objects>
chatgpt_1     |           │      │           └ '你好'
chatgpt_1     |           │      └ 'friend-1442017318'
chatgpt_1     |           └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fc248edfec0>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 61, in call
chatgpt_1     |     await m.handle_request(session_id, message, respond, conversation_context, n)
chatgpt_1     |           │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fc248dada80>
chatgpt_1     |           │ │              │           │        │        └ None
chatgpt_1     |           │ │              │           │        └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |           │ │              │           └ '你好'
chatgpt_1     |           │ │              └ 'friend-1442017318'
chatgpt_1     |           │ └ <function MiddlewareConcurrentLock.handle_request at 0x7fc24aabe700>
chatgpt_1     |           └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x7fc24aab9410>
chatgpt_1     | 
chatgpt_1     |   File "/app/middlewares/concurrentlock.py", line 43, in handle_request
chatgpt_1     |     await action(session_id, prompt, conversation_context, respond)
chatgpt_1     |           │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |           │      │           │       └ None
chatgpt_1     |           │      │           └ '你好'
chatgpt_1     |           │      └ 'friend-1442017318'
chatgpt_1     |           └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fc248dada80>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 61, in call
chatgpt_1     |     await m.handle_request(session_id, message, respond, conversation_context, n)
chatgpt_1     |           │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fc248dad300>
chatgpt_1     |           │ │              │           │        │        └ None
chatgpt_1     |           │ │              │           │        └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |           │ │              │           └ '你好'
chatgpt_1     |           │ │              └ 'friend-1442017318'
chatgpt_1     |           │ └ <function Middleware.handle_request at 0x7fc24aabdb20>
chatgpt_1     |           └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x7fc24aab9390>
chatgpt_1     | 
chatgpt_1     |   File "/app/middlewares/middleware.py", line 9, in handle_request
chatgpt_1     |     await action(session_id, prompt, conversation_context, respond)
chatgpt_1     |           │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |           │      │           │       └ None
chatgpt_1     |           │      │           └ '你好'
chatgpt_1     |           │      └ 'friend-1442017318'
chatgpt_1     |           └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fc248dad300>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 61, in call
chatgpt_1     |     await m.handle_request(session_id, message, respond, conversation_context, n)
chatgpt_1     |           │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fc248daf920>
chatgpt_1     |           │ │              │           │        │        └ None
chatgpt_1     |           │ │              │           │        └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |           │ │              │           └ '你好'
chatgpt_1     |           │ │              └ 'friend-1442017318'
chatgpt_1     |           │ └ <function MiddlewareRatelimit.handle_request at 0x7fc24aabd1c0>
chatgpt_1     |           └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x7fc24aab9490>
chatgpt_1     | 
chatgpt_1     |   File "/app/middlewares/ratelimit.py", line 26, in handle_request
chatgpt_1     |     await action(session_id, prompt, conversation_context, respond)
chatgpt_1     |           │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |           │      │           │       └ None
chatgpt_1     |           │      │           └ '你好'
chatgpt_1     |           │      └ 'friend-1442017318'
chatgpt_1     |           └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7fc248daf920>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 61, in call
chatgpt_1     |     await m.handle_request(session_id, message, respond, conversation_context, n)
chatgpt_1     |           │ │              │           │        │        │                     └ <function handle_message.<locals>.request at 0x7fc248dad3a0>
chatgpt_1     |           │ │              │           │        │        └ None
chatgpt_1     |           │ │              │           │        └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     |           │ │              │           └ '你好'
chatgpt_1     |           │ │              └ 'friend-1442017318'
chatgpt_1     |           │ └ <function MiddlewareTimeout.handle_request at 0x7fc24aabe7a0>
chatgpt_1     |           └ <middlewares.timeout.MiddlewareTimeout object at 0x7fc24ce797d0>
chatgpt_1     | 
chatgpt_1     |   File "/app/middlewares/timeout.py", line 27, in handle_request
chatgpt_1     |     await asyncio.wait_for(coro_task, config.response.max_timeout)
chatgpt_1     |           │       │        │          │      │        └ 600.0
chatgpt_1     |           │       │        │          │      └ Response(mode='mixed', buffer_delay=15, default_ai='chatgpt-web', error_format='出现故障 ！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚...
chatgpt_1     |           │       │        │          └ Config(onebot=None, mirai=Mirai(qq=1439592902, manager_qq=1442017318, api_key='1234567890', http_url='http://localhost:8080',...
chatgpt_1     |           │       │        └ <Task finished name='Task-1373' coro=<handle_message.<locals>.request() done, defined at /app/universal.py:101> exception=<In...
chatgpt_1     |           │       └ <function wait_for at 0x7fc24e5cb9c0>
chatgpt_1     |           └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>
chatgpt_1     | 
chatgpt_1     |   File "/usr/local/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
chatgpt_1     |     return fut.result()
chatgpt_1     |            │   └ <method 'result' of '_asyncio.Task' objects>
chatgpt_1     |            └ <Task finished name='Task-1373' coro=<handle_message.<locals>.request() done, defined at /app/universal.py:101> exception=<In...
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 247, in request
chatgpt_1     |     await respond(config.response.error_format.format(exc=e))
chatgpt_1     |           │       │      │        │            └ <method 'format' of 'str' objects>
chatgpt_1     |           │       │      │        └ '出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。\n原因：{exc}'
chatgpt_1     |           │       │      └ Response(mode='mixed', buffer_delay=15, default_ai='chatgpt-web', error_format='出现故障！如果这个问题持续出 现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚...
chatgpt_1     |           │       └ Config(onebot=None, mirai=Mirai(qq=1439592902, manager_qq=1442017318, api_key='1234567890', http_url='http://localhost:8080',...
chatgpt_1     |           └ <function handle_message.<locals>.respond at 0x7fc248dae340>
chatgpt_1     | 
chatgpt_1     |   File "/app/universal.py", line 95, in respond
chatgpt_1     |     voice = await voice_task
chatgpt_1     |                   └ <Task finished name='Task-1390' coro=<get_tts_voice() done, defined at /app/utils/text_to_speech.py:13> exception=<InvalidURL...
chatgpt_1     | 
chatgpt_1     |   File "/app/utils/text_to_speech.py", line 25, in get_tts_voice
chatgpt_1     |     if await vits_api_instance.process_message(str(elem), output_file.name):
chatgpt_1     |              │                 │                   │      │           └ '/tmp/tmpuciggrxc.silk'
chatgpt_1     |              │                 │                   │      └ <tempfile._TemporaryFileWrapper object at 0x7fc24a1e9110>
chatgpt_1     |              │                 │                   └ Plain(text='出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。\n原因：101.33.231.208/speakers')
chatgpt_1     |              │                 └ <function VitsAPI.process_message at 0x7fc248eddda0>
chatgpt_1     |              └ <utils.vits_tts.VitsAPI object at 0x7fc24a1d9610>
chatgpt_1     | 
chatgpt_1     |   File "/app/utils/vits_tts.py", line 126, in process_message
chatgpt_1     |     await self.initialize()
chatgpt_1     |           │    └ <function VitsAPI.initialize at 0x7fc248edd800>
chatgpt_1     |           └ <utils.vits_tts.VitsAPI object at 0x7fc24a1d9610>
chatgpt_1     | 
chatgpt_1     |   File "/app/utils/vits_tts.py", line 19, in initialize
chatgpt_1     |     self.id = await self.voice_speakers_check()
chatgpt_1     |     │    │          │    └ <function VitsAPI.voice_speakers_check at 0x7fc248edda80>
chatgpt_1     |     │    │          └ <utils.vits_tts.VitsAPI object at 0x7fc24a1d9610>
chatgpt_1     |     │    └ None
chatgpt_1     |     └ <utils.vits_tts.VitsAPI object at 0x7fc24a1d9610>
chatgpt_1     | 
chatgpt_1     |   File "/app/utils/vits_tts.py", line 44, in voice_speakers_check
chatgpt_1     |     json_array = await self.get_json_array()
chatgpt_1     |                        │    └ <function VitsAPI.get_json_array at 0x7fc248edd9e0>
chatgpt_1     |                        └ <utils.vits_tts.VitsAPI object at 0x7fc24a1d9610>
chatgpt_1     | 
chatgpt_1     |   File "/app/utils/vits_tts.py", line 40, in get_json_array
chatgpt_1     |     async with session.post(url=url) as res:
chatgpt_1     |                │       │        └ '101.33.231.208/speakers'
chatgpt_1     |                │       └ <function ClientSession.post at 0x7fc24d130860>
chatgpt_1     |                └ <aiohttp.client.ClientSession object at 0x7fc24a1e9610>
chatgpt_1     | 
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
chatgpt_1     |     self._resp = await self._coro
chatgpt_1     |     │    │             │    └ <member '_coro' of '_BaseRequestContextManager' objects>
chatgpt_1     |     │    │             └ <aiohttp.client._RequestContextManager object at 0x7fc248ea00a0>
chatgpt_1     |     │    └ <member '_resp' of '_BaseRequestContextManager' objects>
chatgpt_1     |     └ <aiohttp.client._RequestContextManager object at 0x7fc248ea00a0>
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 508, in _request
chatgpt_1     |     req = self._request_class(
chatgpt_1     |           │    └ <class 'aiohttp.client_reqrep.ClientRequest'>
chatgpt_1     |           └ <aiohttp.client.ClientSession object at 0x7fc24a1e9610>
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
chatgpt_1     |     self.update_host(url)
chatgpt_1     |     │    │           └ URL('101.33.231.208/speakers')
chatgpt_1     |     │    └ <function ClientRequest.update_host at 0x7fc24d0a96c0>
chatgpt_1     |     └ <aiohttp.client_reqrep.ClientRequest object at 0x7fc24a1dba90>
chatgpt_1     |   File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 364, in update_host
chatgpt_1     |     raise InvalidURL(url)
chatgpt_1     |           │          └ URL('101.33.231.208/speakers')
chatgpt_1     |           └ <class 'aiohttp.client_exceptions.InvalidURL'>
chatgpt_1     | 
chatgpt_1     | aiohttp.client_exceptions.InvalidURL: 101.33.231.208/speakers
chatgpt_1     | 2023-04-06 16:16:26.386 | INFO     | graia.ariadne.connection.ws:_:92 - Websocket connection closed

![QQ截图20230407002110](https://user-images.githubusercontent.com/105909793/230438683-27d00dd7-d1b2-4735-9a27-6b5f5c94d170.png)
![QQ截图20230407002205](https://user-images.githubusercontent.com/105909793/230438835-ee975f39-f9e5-4b3c-8b07-596e2d79c4d8.png)
![QQ截图20230407002317](https://user-images.githubusercontent.com/105909793/230439070-eb5595d1-a563-4173-858c-c26e1f3bf2fe.png)

麻烦帮解决一下，谢谢

**Comment by lss233** [comment]
api url 有误，请读文档，谢谢。
