### ISSUE TITLE
[BUG] 未能使用所配置的账号激活 session key, 请检查配置.', {'code': 2, 'msg': '指定Bot不存在'}

### ISSUE THREAD

**Issue by Rrobinvip** [lss233/chatgpt-mirai-qq-bot#562]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
通过chatgpt log 可以发现以下报错：
```
| ERROR    | graia.amnesia.transport.rider:trigger_callbacks:37 - ('未能使用所配置的账号激活 session key, 请检查配置.', {'code': 2, 'msg': '指定Bot不存在'})
```

**运行环境:**  
- 操作系统：Ubuntu 22.04 LTS
- Docker：23.0.1
- 项目版本：2.2.4.2

**复现步骤**  
描述你是如何触发这个 BUG 的
`docker-compose up`

**预期行为**  
正常运行

**截图**  
<img width="804" alt="Xnip2023-04-06_18-32-16" src="https://user-images.githubusercontent.com/38164021/230505751-7f02789a-7539-4eab-acf6-fec0a799b20b.png">

**其他内容**  
之前一直正常运行，机器人突然停止回复信息了，重启出现此回复。

**Comment by lss233** [comment]
#373
