### ISSUE TITLE
运行QQ on Bing，显示invalid header value

### ISSUE THREAD

**Issue by ansonlianson** [lss233/chatgpt-mirai-qq-bot#563]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
Illegal header value b'\n[ \n    { \n        "domain": ".bing.com", \n  ………………

**运行环境:**  
- 操作系统：Windows 10 Server
- Docker： ？
- 项目版本：V2.3.2

**复现步骤**  
描述你是如何触发这个 BUG 的
上个版本的时候bing正常运行，今天发现循环回复”Bing 已结束本次会话。继续发送消息将重新开启一个新会话。“，于是打算更新版本解决，看到新版本的Bing Cookie设置似乎更新了，于是按照新教程设置（https://chatgpt-qq.lss233.com/pei-zhi-wen-jian-jiao-cheng/jie-ru-ai-ping-tai/jie-ru-new-bing-sydney）已经确认Bing正常登录，可以使用Chat

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
![image](https://user-images.githubusercontent.com/45104824/230537501-ead3117c-7c52-4e34-b27c-bff46d82870b.png)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by ansonlianson** [comment]
![image](https://user-images.githubusercontent.com/45104824/230537588-3f89f9fa-58bf-4be1-8704-094e3dd39571.png)

**Comment by meixiayvmeiyisi** [comment]
把json串里面的换行和空格之类的给去除，还有你配置文件里面为啥后面是3个双引号？这个json串是用单引号来包裹。
![image](https://user-images.githubusercontent.com/35397289/230697540-9d194ba6-17c0-4b2e-ba15-b52be7510a44.png)
