### ISSUE TITLE
[BUG] 请填写标题

### ISSUE THREAD

**Issue by 643063150** [lss233/chatgpt-mirai-qq-bot#570]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：win11
- Docker： 无
- 项目版本：v2.3.2

**复现步骤**  
### 登陆失败

![}G6I@JLGOQZ V}Z`~HAHK5S](https://user-images.githubusercontent.com/11732536/230701200-a75af8c3-dede-431d-8140-9df1e1601ce2.png)

### tooken是通过

![W(2KIPULO@6W8_$QKVGYT2D](https://user-images.githubusercontent.com/11732536/230701241-af4d6763-5df7-4208-9555-d8b647bbdac1.png)

**Comment by lss233** [comment]
1. 目前 ChatGPT 网页版仅可使用 accessToken 登录。
2. 你需要修改 endpoint：
  请在升级后修改配置文件，将

browserless_endpoint = "https://bypass.duti.tech/api/"
修改为

browserless_endpoint = "https://bypass.churchless.tech/api/"
或者直接删除该行！

3. 请填写标题。

**Comment by 643063150** [comment]
> 1. 目前 ChatGPT 网页版仅可使用 accessToken 登录。
> 2. 你需要修改 endpoint：
>    请在升级后修改配置文件，将
> 
> browserless_endpoint = "https://bypass.duti.tech/api/" 修改为
> 
> browserless_endpoint = "https://bypass.churchless.tech/api/" 或者直接删除该行！
> 
> 3. 请填写标题。

还是不行
![image](https://user-images.githubusercontent.com/11732536/230701498-eb96b625-ac88-4f51-92c1-79fb606e6679.png)

**Comment by lss233** [comment]
![image](https://user-images.githubusercontent.com/8984680/230701549-f0aaa362-3dc9-485f-99db-665fdc4656c0.png)
似乎你没有使用 access_token  登录

**Comment by 643063150** [comment]
> access_token

我的，刚开时时在掘金上看的教程 不太全 修改了之后成功了

**Comment by lss233** [comment]
你可以建议掘金文章的作者更新一下教程

**Comment by 643063150** [comment]
> 你可以提醒掘金文章的作者更新一下教程

好的 谢谢
