### ISSUE TITLE
建议在配置文件中增加关键词自定义回复功能

### ISSUE THREAD

**Issue by UrsaBear** [lss233/chatgpt-mirai-qq-bot#571]
目前的实现中已经支持通过 `加载预设` 或 `.设置` 这类关键词修改系统设置；
那能否实现让用户定义关键词，触发指定的回复？这样可以让我们自定义帮助信息或者设置一些留言。

例如：

### 配置文件

`config.cfg`

>[response]
>
>[[response.keywords]]
>#定义触发关键词
>keyword = "help"
>#定义回复内容
>message = "The 1st line of help message\nThe 2nd line of help message"

### 用户发送
>help

### Bot响应
>The 1st line of help message
>The 2nd line of help message

---

看了下源码，感觉可以在 `universal.py` 的 `# 加载预设` 和 `# 没有任务那就聊天吧！` 两段逻辑中间加入，来避免自定义关键词影响原有系统设置功能，也能省去重复关键词校验

虽然很想贡献pr，无奈没写过python，我是废物，私密马赛。

**Comment by lss233** [comment]
Mirai 和  GO-CQHTTP 均有类似功能插件，这不属于 ChatGPT 该有的东西。

**Comment by UrsaBear** [comment]
> Mirai 和 GO-CQHTTP 均有类似功能插件，这不属于 ChatGPT 该有的东西。

感谢指点，对这块的了解比较少，请问能否麻烦指路一个GO-CQHTTP支持类似功能的插件？

**Comment by lss233** [comment]
https://github.com/shitianshiwa/guanjianci
