### ISSUE TITLE
[Feature] 建议接入免费API

### ISSUE THREAD

**Issue by VegetableChichen** [lss233/chatgpt-mirai-qq-bot#574]
很多人体验的金额快到期了，部分地区又不方便注册或充值。目前Github有不少ChatGPT的免费API，希望能增加选项接入，如ayaka14732/ChatGPTAPIFree这种。

**Comment by lss233** [comment]
你可以通过修改 api_endpoint 随便用任何 API。

**Comment by VegetableChichen** [comment]
我在config.cfg中更改了api_endpoint的值，但是运行“启动ChatGPT”后依旧需要提供正确的OpenAI的API key，否则就报错“Incorrect API key provided”。请问在使用原API能运行的基础上，还要进行那些设置？谢谢。

**Comment by lss233** [comment]
随便写api key
