### ISSUE TITLE
[BUG] VITS不能使用切换语音指令切换音色

### ISSUE THREAD

**Issue by PinkOcelot-0w0** [lss233/chatgpt-mirai-qq-bot#577]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：Windows server 2016
- Docker： 无
- 项目版本：2.3.3

**复现步骤**  
1.配置文件里默认角色设置成4，向bot发送 切换语音 2
2.bot回复 2 并附带一条没有任何内容的语音
3.向bot发送任何其他消息，bot正常回复文本和语音，但是音色并没有切换成2号角色

**预期行为**  
机器人可以正常切换音色
![image](https://user-images.githubusercontent.com/85439221/230750197-9ac485d5-3934-45e2-8746-2f7b91746ba9.png)

**截图**  
与机器人对话截图
![image](https://user-images.githubusercontent.com/85439221/230750288-6288d63e-c83f-4917-885c-440aaec90285.png)
![image](https://user-images.githubusercontent.com/85439221/230750273-0bb001a5-a7f0-47c6-8210-9f1c8f5968f4.png)
相关配置
![image](https://user-images.githubusercontent.com/85439221/230750396-8790f370-77f9-4159-a4d4-22b7168a608b.png)

**其他内容**  
无

**Comment by Haibersut** [comment]
已知问题，~~又是一款我的问题~~

**Comment by Haibersut** [comment]
缓解措施如下：
在./utils的vits_tts.py中第28行前插入下放代码即可解决
```
vits_list = json_array["VITS"]
```

原因：
由于之前返回 JSON 结构的改变，导致直接获得的是列表进而无法遍历，程序在此处有异常，后续版本会优化调整

**Comment by PinkOcelot-0w0** [comment]
> 缓解措施如下： 在./utils的vits_tts.py中第28行前插入下方代码即可解决
> 
> ```
> vits_list = json_array["VITS"]
> ```
> 
> 原因： 由于之前返回 JSON 结构的改变，导致直接获得的是列表进而无法遍历，程序在此处有异常，后续版本会优化调整

插入代码之后将29行修改为以下代码成功解决
```
voice_name = self.check_id_exists(vits_list, new_id)
```
![image](https://user-images.githubusercontent.com/85439221/230758535-53b2ff52-4ee9-412d-878c-d968a1120f0c.png)

**Comment by Haibersut** [comment]
> > 缓解措施如下： 在./utils的vits_tts.py中第28行前插入下方代码即可解决
> > ```
> > vits_list = json_array["VITS"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 原因： 由于之前返回 JSON 结构的改变，导致直接获得的是列表进而无法遍历，程序在此处有异常，后续版本会优化调整
> 
> 插入代码之后将29行修改为以下代码成功解决
> 
> ```
> voice_name = self.check_id_exists(vits_list, new_id)
> ```
> 
> ![image](https://user-images.githubusercontent.com/85439221/230758535-53b2ff52-4ee9-412d-878c-d968a1120f0c.png)

对的变量名也要一起改，我的疏忽

**Comment by Haibersut** [comment]
已经在 #581 中修复
