### ISSUE TITLE
如何使用Edge TTS

### ISSUE THREAD

**Issue by ken0414** [lss233/chatgpt-mirai-qq-bot#595]
在config中配置了如下：

[text_to_speech]

engine = "edge"

default = "wuu-CN-XiaotongNeural"

===========
请问配置完成之后，还需要进行什么操作吗
使用的是onebot，ffmpeg安装在了onebot的Ubuntu系统上

**Comment by lss233** [comment]
不需要了，你可以试试。

**Comment by lss233** [comment]
edge 应该不支持这个音色吧？建议你看下教程里面那个有关音色的链接。

> > 不需要了，你可以试试。
> 
> ![QQ图片20230410195408](https://user-images.githubusercontent.com/102132588/231040622-572f51dd-37be-44fb-8dad-e17e5e5b6126.png) ![%32(~ 1UN6_ %A}{M~X} 1E](https://user-images.githubusercontent.com/102132588/231041158-82ec8acb-4bb4-42b5-8851-0768ea66ebf4.png) 2.3.4版本 mirai+openai cookie +ffmpeg4.6 对话正常，网络正常 语音没法使用，打开存放的语音位置都是0M的损坏文件 helphelp

**Comment by huangzhitian** [comment]
你看看 ffmpeg -version有没有
