### ISSUE TITLE
[BUG] 请填写标题

### ISSUE THREAD

**Issue by Jxells** [lss233/chatgpt-mirai-qq-bot#597]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

![image](https://user-images.githubusercontent.com/94813798/231023168-529cb361-3ae8-4f1b-a8e5-308ee7042e59.png)

**Comment by lss233** [comment]
这是啥？
