### ISSUE TITLE
启动出错

### ISSUE THREAD

**Issue by fangyuan99** [lss233/chatgpt-mirai-qq-bot#60]
`ModuleNotFoundError: No module named 'revChatGPT.revChatGPT'`

**Comment by lss233** [comment]
根据 #59 ，需要进行一些修改，稍后我会发布新版。

**Comment by lss233** [comment]
[v1.4.3.2](https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v1.4.3.2) 已发布。
