### ISSUE TITLE
[Feature] 教程中内容修改

### ISSUE THREAD

**Issue by andy-lee-cat** [lss233/chatgpt-mirai-qq-bot#605]
Windows 快速部署教程
https://chatgpt-qq.lss233.com/bu-shu-jiao-cheng/kuai-su-bu-shu-jiao-cheng/windows-kuai-su-bu-shu-jiao-cheng
0x02 首次启动 ChatGPT
如果你遇到了错误，别急，请参考下面这个链接来排查你的问题：
下方链接指向“接入 OpenAI 的 ChatGPT”
https://chatgpt-qq.lss233.com/pei-zhi-wen-jian-jiao-cheng/jie-ru-ai-ping-tai/jie-ru-openai-de-chatgpt
应该更好一些

**Comment by lss233** [comment]
可以解释下为什么吗？

**Comment by andy-lee-cat** [comment]
原链接指向快速部署教程，再点击Windows教程就又回到出问题的位置。实际上对于ChatGPT配置出错问题的处理是在 接入OpenAI的ChatGPT 中给出详细处理方法的

**Comment by lss233** [comment]
可以具体说说你是遇到了什么 配置出错问题的吗？

**Comment by andy-lee-cat** [comment]
我遇到的问题在“接入OpenAI的ChatGPT” 中均给出了详细处理方法，比如一开始我以为access_token就是apikey，错误添加后出现的报错信息又和issues中另一些操作的报错一致，这带给我了一些误导，但实际上我的这一问题在“接入OpenAI的ChatGPT”是详细说明了的
