### ISSUE TITLE
Docker里面的内容不对

### ISSUE THREAD

**Issue by seagullz4** [lss233/chatgpt-mirai-qq-bot#609]
- [ ![Screenshot_20230412_144334_com.yjllq.kito.jpg](https://user-images.githubusercontent.com/96653729/231373765-ace8c4ca-edb7-436a-912a-3ee4c01bac3e.jpg)

![Screenshot_20230412_144329_bin.mt.plus.jpg](https://user-images.githubusercontent.com/96653729/231373766-abf5a56b-8747-4644-84c7-419039e8a883.jpg)

看这两张图片

**Comment by lss233** [comment]
这就是让你加上的……
