### ISSUE TITLE
[BUG]  Client error '401 Unauthorized' for url 'https://bypass.churchless.tech/api/conversations?offset=0&limit=1'

### ISSUE THREAD

**Issue by 15764697077** [lss233/chatgpt-mirai-qq-bot#615]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [√ ] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
httpx.HTTPStatusError: Client error '401 Unauthorized' for url 'https://bypass.churchless.tech/api/conversations?offset=0&limit=1'
For more information check: https://httpstatuses.com/401
2023-04-12 19:16:21.385 | SUCCESS  | manager.bot:login_openai:264 - 成功登录 0/1 个 OpenAI 账号！
2023-04-12 19:16:21.388 | ERROR    | manager.bot:login:119 - 没有登录成功的账号，程序无法启动！
**运行环境:**
- 操作系统：win10
- Docker： 
- 项目版本：2.34

![QQ图片20230412191950](https://user-images.githubusercontent.com/130561593/231443984-093ade30-2c67-4e66-94d9-9dad97e62ad0.png)

**Comment by lss233** [comment]
与此问题重复： #483

**Comment by 15764697077** [comment]
已找到问题 谢谢



---- 回复的原邮件 ----
| 发件人 | Dark ***@***.***> |
| 日期 | 2023年04月13日 00:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [lss233/chatgpt-mirai-qq-bot] [BUG] Client error '401 Unauthorized' for url 'https://bypass.churchless.tech/api/conversations?offset=0&limit=1' (Issue #615) |

与此问题重复： #483
