### ISSUE TITLE
[BUG] 文心一言不能发语音，newbing不能绘画

### ISSUE THREAD

**Issue by bobandbrony** [lss233/chatgpt-mirai-qq-bot#616]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

使用文心一言发一句话的语音，只返回了链接
newbing提示不能绘画，而在网页版是可以绘画的

**运行环境:**  
- 操作系统：Windows11 21H2
- Docker： 无
- 项目版本：2.3.4

**复现步骤**  
描述你是如何触发这个 BUG 的
发送对应消息

**预期行为**  
文心一言应该直接发语音
newbing可以发图

**截图**  
![image](https://user-images.githubusercontent.com/129247570/231517297-797ff372-2538-40bd-b84b-6514e32f014b.png)
![image](https://user-images.githubusercontent.com/129247570/231517580-bc4fe0ad-571b-408f-9b0f-cd70b1739212.png)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by bobandbrony** [comment]
https://lucent.blog/?p=118此项目的newbing可以发图（有些时候会发图的链接），或许可以借鉴？
文心一言我可以提供账号

**Comment by lss233** [comment]
过了两周我才发现原来理解错这个 issue 了……


实际上语言模型不支持语音，目前的语音功能是根据语言模型的结果再使用独立的文字转语音引擎来实现的。

如果你要使用语音功能，请参考教程来开启语音功能。

你看见了现在这样一个链接，其实是由语言模型根据自身训练数据生成的链接，和这个项目本身其实是无关的。
