### ISSUE TITLE
[BUG] windows 无法进行群聊

### ISSUE THREAD

**Issue by lao-zei** [lss233/chatgpt-mirai-qq-bot#617]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：windows
- Docker： 无
- 项目版本：v2.3.4

只是设置了require_mention = "mention"
又或者require_mention = "at"都不能通过@或者名字触发 require_mention = "none"可以

![Screenshot_2023-04-13-00-30-49-720-edit_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/101307321/231524032-ad0f808d-ccbf-428c-89d2-20f6f91783d8.jpg)

![ENC9)U[X[8XN[BN7WDJ~_)J.png](https://user-images.githubusercontent.com/101307321/231524054-3e371e86-db2d-46b9-82c2-dc1a515aec41.png)

![W{WQI2{9$AC18Z@_6@8Z1`1.png](https://user-images.githubusercontent.com/101307321/231524071-2702f17f-2e48-4fda-abb7-be939b7fe95b.png)

**Comment by Yoak3n** [comment]
默认是设置了群聊前缀的
![image](https://user-images.githubusercontent.com/120039624/231588425-84997b73-a9ce-4be7-9e60-9aa322ef8793.png)
你可以试试改为```prefix_group = [""]```
或者取消干脆需要被at，全部使用前缀词来触发

**Comment by lao-zei** [comment]
改为none后使用全局前缀可以群聊不可以

**Comment by lao-zei** [comment]
![ENC9)U[X[8XN[BN7WDJ~_)J(1).png](https://user-images.githubusercontent.com/101307321/231630392-084b166f-79d0-4c33-9d81-4e9cb47ea8d1.png)

抱歉忘了上传之前的配置文件了

**Comment by lao-zei** [comment]
![ENC9)U[X[8XN[BN7WDJ~_)J(1).png](https://user-images.githubusercontent.com/101307321/231630511-0108c5eb-4c6f-4b40-9132-5941ecc0d33d.png)

**Comment by lao-zei** [comment]
![ENC9)U[X[8XN[BN7WDJ~_)J(1).png](https://user-images.githubusercontent.com/101307321/231630554-1d4b515a-8264-42de-bf04-a11ce99a2804.png)

抱歉忘了上传之前的配置文件了

**Comment by lao-zei** [comment]
> 使用

改为none后使用全局前缀可以群聊不可以

**Comment by lao-zei** [comment]
![ENC9)U X 8XN BN7WDJ~_)J(1)](https://user-images.githubusercontent.com/101307321/231631557-bbba0b82-68dc-437c-86ff-cdbf9ba1e2c1.png)
这是之前的配置文件忘记上传了

**Comment by Yoak3n** [comment]
在linux上使用这种配置以及你上面给的配置（后来我把正则匹配的注释也取消了），都可以达成你原本想要的效果，操作系统的差异暂且不考虑
![image](https://user-images.githubusercontent.com/120039624/231635336-faa5e6db-4096-49be-9802-628f3c1cf3e9.png)
![image](https://user-images.githubusercontent.com/120039624/231635189-c1422a9f-0e33-43da-b73c-8bdc47f86c12.png)
![image](https://user-images.githubusercontent.com/120039624/231636543-53efa2fd-72eb-4a8d-8be6-0c3d7a6dbd43.png)
像你上面说的使用```require_mention = "none"```，依旧可以触发
![image](https://user-images.githubusercontent.com/120039624/231641665-1646ff50-c831-422e-9444-8d81df0b7f6f.png)
至少我目前没法复现这个bug

**Comment by lao-zei** [comment]
我在linux用docker也没问题用的windows出现了

**Comment by lao-zei** [comment]
> 在linux上使用这种配置以及你上面给的配置（后来我把正则匹配的注释也取消了），都可以达成你原本想要的效果，操作系统的差异暂且不考虑
> ![image](https://user-images.githubusercontent.com/120039624/231635336-faa5e6db-4096-49be-9802-628f3c1cf3e9.png)
> ![image](https://user-images.githubusercontent.com/120039624/231635189-c1422a9f-0e33-43da-b73c-8bdc47f86c12.png)
> ![image](https://user-images.githubusercontent.com/120039624/231636543-53efa2fd-72eb-4a8d-8be6-0c3d7a6dbd43.png)
> 像你上面说的使用```require_mention = "none"```，依旧可以触发
> ![image](https://user-images.githubusercontent.com/120039624/231641665-1646ff50-c831-422e-9444-8d81df0b7f6f.png)
> 至少我目前没法复现你说的这个bug

我在linux用docker也没问题用的windows出现了
