### ISSUE TITLE
[BUG] 每隔一段时间就会不回复消息，需要重启

### ISSUE THREAD

**Issue by unoexp** [lss233/chatgpt-mirai-qq-bot#624]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
每隔半天至一天的时间，发送任何消息都不会再回复，包括重置会话，此时是能够收到消息的。
已经尝试过删除重装。

**运行环境:**  
- 操作系统：ubuntu
- 项目版本：2.3.4

**截图**  
![Screenshot_2023-04-13-21-42-53-76_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/44316768/231796200-22686929-14e3-4a8e-8eb0-aec161ecd4ba.jpg)
在这里chatgpt自动重启后就不会回复消息了。

**Comment by lss233** [comment]
你可以执行一下
docker-compose logs -f chatgpt 
看看 chatgpt 为什么崩溃了

**Comment by superboyyy** [comment]
我也碰到了，只有重启才能解决，并且没有报错

**Comment by unoexp** [comment]
之前我一直用的mirai，前两天登录不进去了，就换了go-cqhttp。现在已经运行两天了，暂时没有再遇到这个问题，可能是mirai的问题。

**Comment by superboyyy** [comment]
好的，我尝试一下

**Comment by lss233** [comment]
这个问题确实是 mirai 或者 go-cqhttp 掉线了导致的。
解决方法就是重启。
你可以用下面的命令来重启：
```
docker-compose restart mirai # 此命令重启 Mirai
docker-compsoe restart gocqhttp # 此命令重启 Go-cqhttp
```
ChatGPT for Bot 不需要重启。
