### ISSUE TITLE
[BUG] revChatGPT.typings.APIConnectionError: 404 Not Found 

### ISSUE THREAD

**Issue by flyweiyu** [lss233/chatgpt-mirai-qq-bot#629]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：CentOS 7.6
- Docker：Docker version 23.0.3
- 项目版本：v2.3.4

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 机器人部署好后使用api-key的调度模式，回复消息的时候就出现这个问题，换了账号和API-key也一样

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
![2Y}35EWGJS_Y1BX)B}Y7~Z5](https://user-images.githubusercontent.com/9267328/232013486-51371c82-5aba-4ba8-92af-e20193728fea.png)

**其他内容**  
root-chatgpt-1     | 2023-04-14 09:45:45.606 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！
root-chatgpt-1     | 2023-04-14 09:45:45.607 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
root-chatgpt-1     | 2023-04-14 09:45:45.609 | DEBUG    | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时……
root-chatgpt-1     | 2023-04-14 09:45:46.383 | ERROR    | universal:request:239 - 404 Not Found {
root-chatgpt-1     |     "error": {
root-chatgpt-1     |         "message": "Invalid URL (POST /v1//chat/completions)",
root-chatgpt-1     |         "type": "invalid_request_error",
root-chatgpt-1     |         "param": null,
root-chatgpt-1     |         "code": null
root-chatgpt-1     |     }
root-chatgpt-1     | }
root-chatgpt-1     |
root-chatgpt-1     | Traceback (most recent call last):
root-chatgpt-1     |
root-chatgpt-1     |   File "/app/bot.py", line 41, in <module>
root-chatgpt-1     |     loop.run_until_complete(asyncio.gather(*bots))
root-chatgpt-1     |     │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at /app/platforms/ariadne_bot.py:296> wait_for=<Task pending name='Ta...
root-chatgpt-1     |     │    │                  │       └ <function gather at 0x7f2b5a14c0e0>
root-chatgpt-1     |     │    │                  └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>
root-chatgpt-1     |     │    └ <function BaseEventLoop.run_until_complete at 0x7f2b5a150f40>
root-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
root-chatgpt-1     |
root-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
root-chatgpt-1     |     self.run_forever()
root-chatgpt-1     |     │    └ <function BaseEventLoop.run_forever at 0x7f2b5a150ea0>
root-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
root-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
root-chatgpt-1     |     self._run_once()
root-chatgpt-1     |     │    └ <function BaseEventLoop._run_once at 0x7f2b5a152ca0>
root-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
root-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
root-chatgpt-1     |     handle._run()
root-chatgpt-1     |     │      └ <function Handle._run at 0x7f2b5a0e3b00>
root-chatgpt-1     |     └ <Handle <TaskStepMethWrapper object at 0x7f2b549c6350>()>
root-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
root-chatgpt-1     |     self._context.run(self._callback, *self._args)
root-chatgpt-1     |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
root-chatgpt-1     |     │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f2b549c6350>()>
root-chatgpt-1     |     │    │            │    └ <member '_callback' of 'Handle' objects>
root-chatgpt-1     |     │    │            └ <Handle <TaskStepMethWrapper object at 0x7f2b549c6350>()>
root-chatgpt-1     |     │    └ <member '_context' of 'Handle' objects>
root-chatgpt-1     |     └ <Handle <TaskStepMethWrapper object at 0x7f2b549c6350>()>
root-chatgpt-1     |
root-chatgpt-1     | > File "/app/universal.py", line 205, in request
root-chatgpt-1     |     async for rendered in task:
root-chatgpt-1     |                           └ <async_generator object retry.<locals>.decorator.<locals>.wrapper at 0x7f2b566351c0>
root-chatgpt-1     |
root-chatgpt-1     |   File "/app/utils/retry.py", line 21, in wrapper
root-chatgpt-1     |     async for result in func(*args, **kwargs):
root-chatgpt-1     |                         │     │       └ {'prompt': '，茴字有几种写法', 'chain': MessageChain([Plain(text='，茴字有几种写法')]), 'name': '猛喝牛奶君'}
root-chatgpt-1     |                         │     └ (<conversation.ConversationContext object at 0x7f2b55015c10>,)
root-chatgpt-1     |                         └ <function ConversationContext.ask at 0x7f2b56f12520>
root-chatgpt-1     |
root-chatgpt-1     |   File "/app/conversation.py", line 160, in ask
root-chatgpt-1     |     async for item in self.adapter.ask(prompt):
root-chatgpt-1     |                       │    │       │   └ '，茴字有几种写法'
root-chatgpt-1     |                       │    │       └ <function ChatGPTAPIAdapter.ask at 0x7f2b574dafc0>
root-chatgpt-1     |                       │    └ <adapter.chatgpt.api.ChatGPTAPIAdapter object at 0x7f2b55015750>
root-chatgpt-1     |                       └ <conversation.ConversationContext object at 0x7f2b55015c10>
root-chatgpt-1     |
root-chatgpt-1     |   File "/app/adapter/chatgpt/api.py", line 85, in ask
root-chatgpt-1     |     async for resp in self.bot.ask_stream_async(prompt=prompt, role=self.hashed_user_id, convo_id=self.session_id):
root-chatgpt-1     |                       │    │   │                       │            │    │                        │    └ 'group-583465517'
root-chatgpt-1     |                       │    │   │                       │            │    │                        └ <adapter.chatgpt.api.ChatGPTAPIAdapter object at 0x7f2b55015750>
root-chatgpt-1     |                       │    │   │                       │            │    └ 'user-3b8680e47dcd427f'
root-chatgpt-1     |                       │    │   │                       │            └ <adapter.chatgpt.api.ChatGPTAPIAdapter object at 0x7f2b55015750>
root-chatgpt-1     |                       │    │   │                       └ '，茴字有几种写法'
root-chatgpt-1     |                       │    │   └ <function Chatbot.ask_stream_async at 0x7f2b574da660>
root-chatgpt-1     |                       │    └ <revChatGPT.V3.Chatbot object at 0x7f2b55016990>
root-chatgpt-1     |                       └ <adapter.chatgpt.api.ChatGPTAPIAdapter object at 0x7f2b55015750>
root-chatgpt-1     |
root-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/revChatGPT/V3.py", line 271, in ask_stream_async
root-chatgpt-1     |     raise t.APIConnectionError(
root-chatgpt-1     |           │ └ <class 'revChatGPT.typings.APIConnectionError'>
root-chatgpt-1     |           └ <module 'revChatGPT.typings' from '/usr/local/lib/python3.11/site-packages/revChatGPT/typings.py'>
root-chatgpt-1     | revChatGPT.typings.APIConnectionError: 404 Not Found {
root-chatgpt-1     |     "error": {
root-chatgpt-1     |         "message": "Invalid URL (POST /v1//chat/completions)",
root-chatgpt-1     |         "type": "invalid_request_error",
root-chatgpt-1     |         "param": null,
root-chatgpt-1     |         "code": null
root-chatgpt-1     |     }
root-chatgpt-1     | }
root-chatgpt-1     |
root-chatgpt-1     | Please check if there is a problem with your network connection
root-chatgpt-1     | Please check that the input is correct, or you can resolve this issue by filing an issue
root-chatgpt-1     |
root-chatgpt-1     | Project URL: https://github.com/acheong08/ChatGPT
root-mirai-1       | 2023-04-14 09:45:53 V/Bot.1249482803: Group(583465517) <- [mirai:quote:[mirai:source:ids=[332], internalIds=[849990135], from group 460550306 to 583465517 at 1681465544], content=[mirai:at:1249482803] gpt，茴字有几种写法][mirai:image:{70A3D2DA-2194-7032-014A-3C110C038BAC}.png, width=700, height=980, size=90878, type=PNG, isEmoji=false]

[我看到另外一个issue，认为是openAI的bug，需要新版的openAI方法，但是我不知道怎么解决](https://github.com/openai/openai-python/issues/271)

**Comment by lss233** [comment]
目测是你 api_endpoint 写错了，建议提供一下配置文件

**Comment by flyweiyu** [comment]
> 目测是你 api_endpoint 写错了，建议提供一下配置文件

# 这里是 ChatGPT for QQ 的所有配置文件
# 请注意：以 "#" 开头的文本均为注释
# 不会被程序读取
# 如果你想要使用某个设置，请确保前面没有 "#" 号
[mirai]
# Mirai 相关设置

qq = **********

manager_qq = **********

# 以下设置如果不懂 无需理会

api_key = "1234567890" # mirai-http-api 中的 verifyKey
# mirai api http 反向连接模式
# 使用此模式可以将本项目与 mirai 分离在两个不同服务器部署
reverse_ws_host = "0.0.0.0"
reverse_ws_port = 8554
# mirai api http 正向连接模式
# 使用此模式时需注释上面的反向连接模式
#http_url = "http://mirai:8080"
#ws_url = "http://mirai:8080"

# Discord 设置，开启后可以支持 Discord 机器人
# [discord]
# bot_token = "xxx"

# Telegram 设置，开启后可以支持 Telegram 机器人
# [telegram]
# # 这个 token 是找 BotFather 要的
# bot_token = "你的 Bot token"
# # 如果部署在国内，就填这个设置代理
# # 不填的话就会读取系统的代理设置
# proxy = "http://localhost:1080"
# # 管理员的 chat id
# manager_chat = 1234567890

# ==== OpenAI 部分开始
[openai]
# OpenAI 相关设置
# 自定义 ChatGPT 的 browserless 接入点
# 自 3月9日 开始，不设置此项将无法正常使用 browserless 模式下的网页版 ChatGPT
browserless_endpoint = "https://chatgpt-proxy.lss233.com/api"


# 自定义 OpenAI 的 API 接口基础地址
# 通过此功能，你可以搭建一个 OpenAI 的反向代理来避免网络问题
# 例如此项目：https://github.com/Ice-Hazymoon/openai-scf-proxy
api_endpoint = "https://chatgpt-proxy.lss233.com/v1/"

# 以下是 GPT3(.5) 和 GPT4 的模型参数
# 在使用 API 调用时有效
# 参数具体含义可以见 https://platform.openai.com/docs/api-reference/completions/create
# 如果你不了解，可以保持默认
[openai.gpt3_params]
temperature = 1.0
max_tokens = 4000
top_p = 1.0
presence_penalty = 0.5
frequency_penalty = 0.5
min_tokens = 1000

# 以下是 OpenAI 账号设置

# 你可以用多种不同的方式登录 OpenAI
# 你也可以登录很多个不同的账号（无限多个）
# 下面的例子会向你演示使用不同方式登录时
# 配置文件的写法

# 第 2 个 OpenAI 账号
# 使用 api key 登录
# 当你设置了 API Key 之后
# 你就可以使用 OpenAI 中收费的 ChatGPT API、AI 画图等功能
# 优点：
# 1. 响应快
# 2. 不咋封号
# 3， 可以调参
# 缺点：
# 1. 烧钱
# 2. 暂不支持 GPT4 (3月15日)
#[[openai.accounts]]
# 你的 API key，可以在这里看： https://platform.openai.com/account/api-keys
#api_key="sk-**********"

[[openai.accounts]]
# 你的 API key，可以在这里看： https://platform.openai.com/account/api-keys
api_key="sk-**********"

# 使用 ChatGPT Plus（plus 用户此项设置为 true 使用 legacy 模型）
paid = false

# 是否开启标题自动重命名
title_pattern="qq-{session_id}"

# 是否自动删除旧的对话
auto_remove_old_conversations = true

# === OpenAI 账号部分结束


[text_to_speech]
# 语音转文字
always = false
engine="edge"
# 默认音色
# 可参考 Azure：
# https://learn.microsoft.com/zh-CN/azure/cognitive-services/speech-service/language-support?tabs=tts#neural-voices

default = "zh-CN-XiaoyouNeural"


[text_to_image]
# 文字转图片

# 是否强制开启，设置后所有的消息强制以图片发送，减小风控概率  
always = true

# 字体大小
font_size = 30

# 图片宽度
width = 700

# 字体
font_path = "fonts/sarasa-mono-sc-regular.ttf" 

# [备用模式]起始点 X
offset_x = 50 

# [备用模式]起始点 Y
offset_y = 50 

[trigger]
# 配置机器人要如何响应，下面所有项均可选 (也就是可以直接删掉那一行)

# 全局聊天前缀，在群聊和私聊中，符合下面的前缀【才】会响应，可以自己增减
prefix = [ "gpt",]

# 私聊聊天前缀，在私聊中，符合下面的前缀【也】会响应，可以自己增减
prefix_friend = [ "ask",]

# 群聊聊天前缀，在群聊中，符合下面的前缀【也】会响应，可以自己增减
prefix_group = [ "ai",]

# 满足以下正则表达式则忽略此条消息
ignore_regex = []

# 直接和指定的 AI 对话（不切换AI）
# 此处的前缀是在上面的前缀之后的
# 例： 
# prefix = [ "ask" ]
# prefix_ai = { "bing-c" = ["bing"] }
# 则用户发送： ask bing 你好
# 则会直接把 “你好” 两个字发给 New Bing AI
prefix_ai = { "chatgpt-web" = ["gpt"], "bing-c" = ["bing"] }

# AI 画图的前缀
# 需要有 OpenAI 的 api_key 才能使用
prefix_image = ["画", "看"]
# 配置群里如何让机器人响应，"at" 表示需要群里 @ 机器人，"mention" 表示 @ 或者以机器人名字开头都可以，"none" 表示不需要
require_mention = "at"

# 重置会话的命令
reset_command = [ "重置会话",]

# 回滚会话的命令
rollback_command = [ "回滚会话",]

# 切换模型的命令
switch_model = "切换模型 (.+)"

# 允许普通用户切换的模型
allowed_models = ["gpt-3.5-turbo", "gpt-3.5-turbo-0301", "text-davinci-002-render-sha", "text-davinci-002-render-paid"]

# 允许普通用户切换AI
allow_switching_ai = true

[response]
# 默认的响应模式，支持：
# mixed - 图文混合 （实验性）
# text  - 文字模式
# image - 图片模式
mode = "mixed"

# 分段发送延迟，消息会等待一段时间再发送，避免刷屏
# 该功能目前仅在 mixed 模式有效
# 设置为 0 关闭分段发送功能
# 若要开启此功能，建议设置为 15 左右
buffer_delay = 15

# 默认使用的 AI 类型，不填写时自动推测
# 目前支持的类型：
# chatgpt-web: 网页版 ChatGPT
# chatgpt-api: API 版 ChatGPT (GPT3.5-turbo)
# bing-c: New Bing (新必应对话风格-创造力)
# bing-p: New Bing (新必应对话风格-精确)
# bing-b: New Bing (新必应对话风格-平衡)
# bard - Google Bard
# yiyan - 百度 文心一言 网页版
# chatglm-api - 清华 ChatGLM-API 接口
# sage - POE Sage 模型
# beaver - POE GPT4 模型
# claude2 - POE Claude2 模型
# claude - POE Claude 模型
# chinchilla - POE ChatGPT 模型
# nutria - POE Dragonfly 模型
default_ai = "chatgpt-api"
# 匹配指令成功但没有对话内容时发送的消息
placeholder = "您好！我是 Assistant，一个由 OpenAI 训练的大型语言模型。我不是真正的人，而是一个计算机程序，可以通过文本聊天来帮助您解决问题。如果您有任何问题，请随时告诉我，我将尽力回答。\n如果您需要重置我们的会话，请回复`重置会话`。"

# 发生错误时要发送的消息
error_format = "出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。\n{exc}"

# 发生网络错误时发送的消息，请注意可以插入 {exc} 作为异常占位符
error_network_failure = "网络故障！连接 OpenAI 服务器失败，我需要更好的网络才能服务！\n{exc}"

# OpenAI 账号登录失效时的提示
error_session_authenciate_failed = "身份验证失败！无法登录至 ChatGPT 服务器，请检查账号信息是否正确！\n{exc}"

# OpenAI 提示 Too many requests（太多请求） 时的提示
error_request_too_many = "糟糕！当前收到的请求太多了，我需要一段时间冷静冷静。你可以选择“重置会话”，或者过一会儿再来找我！\n{exc}"

# 服务器提示 Server overloaded(过载) 时的提示
error_server_overloaded = "抱歉，当前服务器压力有点大，请稍后再找我吧！"

# 是否要回复触发指令的消息
quote = true

# 发送下面那个提醒之前的等待时间
timeout = 30.0

# 超过响应时间时要发送的提醒
timeout_format = "我还在思考中，请再等一下~"

max_timeout = 600
# 对于每个提问的最长等待时间，超过此时间不再等待

cancel_wait_too_long = "啊哦，这个问题有点难，让我想了好久也没想明白。试试换个问法？"
# 超过最长等待时间后发送的信息

# 重置会话时发送的消息
reset = "会话已重置。"

# 回滚成功时发送的消息
rollback_success = "已回滚至上一条对话，你刚刚发的我就忘记啦！"

# 回滚失败时发送的消息
rollback_fail = "回滚失败，没有更早的记录了！"

# 等待处理的消息的最大数量，如果要关闭此功能，设置为 0
max_queue_size = 10

# 队列满时的提示
queue_full = "抱歉！我现在要回复的人有点多，暂时没有办法接收新的消息了，请过会儿再给我发吧！"

# 新消息加入队列会发送通知的长度最小值
queued_notice_size = 3

# 新消息进入队列时，发送的通知。 queue_size 是当前排队的消息数
queued_notice = "消息已收到！当前我还有{queue_size}条消息要回复，请您稍等。"

[baiducloud]
# 是否启动百度云内容安全审核
# 注册地址: http://console.bce.baidu.com/ai/#/ai/antiporn/overview/index
check = false

# 百度云API_KEY 24位英文数字字符串
baidu_api_key = ""

# 百度云SECRET_KEY 32位的英文数字字符串
baidu_secret_key =""

# 不合规消息自定义返回
illgalmessage = "[百度云]请珍惜机器人，当前返回内容不合规"

[system]
# 是否自动同意进群邀请
accept_group_invite = false

# 是否自动同意好友请求
accept_friend_request = false

[presets]
# 切换预设的命令： 加载预设 猫娘
command = "加载预设 (\\w+)"

loaded_successful = "预设加载成功！"

[presets.keywords]
# 预设关键词 <-> 实际文件
"正常" = "presets/default.txt"
"猫娘" = "presets/catgirl.txt"

[ratelimit]
# 额度限制功能，可以在 wiki 中了解此功能的用法

# 额度使用达到此比例时进行警告
warning_rate = 0.8

# 警告消息
warning_msg = "\n\n警告：额度即将耗尽！\n目前已发送：{usage}条消息，最大限制为{limit}条消息/小时，请调整您的节奏。\n额度限制整点重置，当前服务器时间：{current_time}"

# 超额消息
exceed = "已达到额度限制，请等待下一小时继续和我对话。"

**Comment by flyweiyu** [comment]
我按照api_endpoint上的流程搭了一个代理（我这台是美国地区的服务器）
![image](https://user-images.githubusercontent.com/9267328/232169920-8d9d03b1-0554-41ee-b8dd-6ceb6245b0d3.png)
把api_endpoint改成
![image](https://user-images.githubusercontent.com/9267328/232170001-b07f312f-04ba-4b9f-8c8d-3fe7993e3dfd.png)
最后出现
![image](https://user-images.githubusercontent.com/9267328/232170090-a424154e-e507-4a58-979f-2975464e9ffa.png)
![image](https://user-images.githubusercontent.com/9267328/232170116-c4c6d8dd-33f6-4e36-b3f5-26c0a013fc45.png)
![image](https://user-images.githubusercontent.com/9267328/232170149-f2ebfc3d-0a2f-4228-9c48-81bafbb68ca4.png)
这是end_point没搭好吗

**Comment by lss233** [comment]
你这完全写错了。  
你不能在容器内用 localhost 这个地址，因为 IP 是隔离的。  另外，你要写到/v1 这个url，但你没有写。  

另外，你这样在本机上搭反代和直连的效果是完全一样的，只是白白增加了复杂度，没有意义。

**Comment by flyweiyu** [comment]
> 

所以容器内是不需要设置api_endpoint吗
因为我这个可以直连所以不用设置反代是吗

**Comment by lss233** [comment]
我不知道你能不能直连。

教程里面说来如果你的网络不能直连的话可以用反代。

**Comment by flyweiyu** [comment]
> 我不知道你能不能直连。
> 
> 教程里面说来如果你的网络不能直连的话可以用反代。

我可以直连。
这样的话就不需要用反代了吧。需要在配置里修改哪些部分呢？请指教

**Comment by lss233** [comment]
可以直连就把反代部分删了就行。
