### ISSUE TITLE
[BUG] 接入的poe 请求poe的地址总是失败

### ISSUE THREAD

**Issue by Renjiangfeng** [lss233/chatgpt-mirai-qq-bot#633]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
使用的docker安装，接入的poe,2个问题，

1.过一会就是就无法回复消息的，报
 “chatgpt-qq-chatgpt-1 | WARNING:root:Websocket closed with status None: None
chatgpt-qq-chatgpt-1 | ERROR:websocket:Connection to remote host was lost. - goodbye”

2. 代理已经成功了，但是依然报请求poe的地址失败，错误看截图

**运行环境:**  
- 操作系统：ubuntu
- Docker：Docker version 20.10.13
- 项目版本：lss233/chatgpt-mirai-qq-bot:browser-version

**截图**  
![image](https://user-images.githubusercontent.com/33890971/232178673-dfcf1b04-f2fe-4dab-98ec-06ecbd52f3a3.png)
**其他内容**

**Comment by Cold-Stars** [comment]
![image](https://user-images.githubusercontent.com/113192545/232181633-164fee6c-94e9-4328-9873-bca578cd8791.png)
![image](https://user-images.githubusercontent.com/113192545/232181688-a99aa67d-d7fa-4b82-b5a9-e5769382c16c.png)
类似的问题，我的获取到了poe的cookie，并且已经配置了，但不能用。

**Comment by TheThirdSanta** [comment]
自己去poe网站试过没有问题，但是windows部署包里也有问题

**Comment by TheThirdSanta** [comment]
补充一下，今天更新2.3.4.1后解析poe账号时偶尔还是会出现问题，然后也会报issue创建者说的一样的错误

**Comment by Renjiangfeng** [comment]
> 补充一下，今天更新2.3.4.1后解析poe账号时偶尔还是会出现问题，然后也会报issue创建者说的一样的错误

更新后，还是会出现第一个问题，但是已经可以正常用了.

**Comment by TheThirdSanta** [comment]
今天使用又出现新的问题了。。。会给我报远程主机关闭连接的错误
 Poe connection error HTTPSConnectionPool(host='poe.com', port=443): Max retries exceeded with url: /api/gql_POST (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
感觉是不是要定时重启poe的client服务才行。。。

**Comment by lss233** [comment]
这单纯是你网络问题

> 今天使用又出现新的问题了。。。会给我报远程主机关闭连接的错误 Poe connection error HTTPSConnectionPool(host='poe.com', port=443): Max retries exceeded with url: /api/gql_POST (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))) 感觉是不是要定时重启poe的client服务才行。。。

**Comment by TheThirdSanta** [comment]
> 这单纯是你网络问题
> 
> > 今天使用又出现新的问题了。。。会给我报远程主机关闭连接的错误 Poe connection error HTTPSConnectionPool(host='poe.com', port=443): Max retries exceeded with url: /api/gql_POST (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))) 感觉是不是要定时重启poe的client服务才行。。。

好的我也觉得哈哈，因为我刚刚看了一下poe的代码发现有重置client的部分，我再去查一下我自己问题怎么解决吧
