### ISSUE TITLE
[Feature] docker字体配置

### ISSUE THREAD

**Issue by Sevenyine** [lss233/chatgpt-mirai-qq-bot#634]
使用linux docker，在config.cfg中配置的fontpath不能从根目录开始写，还需要把字体文件放到docker目录下比较麻烦，希望可以出一个方便的自定义字体配置，能够配置环境外的字体，不过我也不太清楚能不能实现，能不能像config.cfg那种直接让字体在安装目录下配置呢

**Comment by lss233** [comment]
我觉得应该是你的写法有问题。  
你写了路径以后，要把字体文件挂载到容器里对应的位置下才行

**Comment by Sevenyine** [comment]
> 我觉得应该是你的写法有问题。
> 你写了路径以后，要把字体文件挂载到容器里对应的位置下才行

诶，挂载就是直接去docker那个路径下，还是有其他的挂载方法
不过我已经实现了修改字体了，就是修改需要找docker对应的路径有点麻烦（）
