### ISSUE TITLE
[BUG] 完成初始化步骤但启动程序出错

### ISSUE THREAD

**Issue by yuyongchengxuyuan** [lss233/chatgpt-mirai-qq-bot#636]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况
Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

**运行环境:**  
- 操作系统：cent os 
- Docker：23.0.3
- 项目版本：最新
- 
**复现步骤**  
描述你是如何触发这个 BUG 的
执行linux一键部署命令之后,完成了所有的初始步骤

**预期行为**  
预期开始登录了

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
看样子是你docker-compose该升级了。
