### ISSUE TITLE
[openai api调用问题]

### ISSUE THREAD

**Issue by Splatoon3-bing** [lss233/chatgpt-mirai-qq-bot#637]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [ √] 我已看过其他 issue，他们不能解决我的问题 
- [ √] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
win11

我在腾讯云上部署了一个云函数用于反代，这样我电脑就不需要挂梯子了，经过我的测试，其他浏览器更换url后可以正常调用这个api，但是本项目早config文件修改后就不能连接了，还得搭梯子
![image](https://user-images.githubusercontent.com/113076115/232224567-5e8bdf32-e223-494a-a5bc-178122d1c199.png)

**Comment by Splatoon3-bing** [comment]
![image](https://user-images.githubusercontent.com/113076115/232224804-3551642c-57a5-40ba-ad18-fa394a1088df.png)

**Comment by Splatoon3-bing** [comment]
![image](https://user-images.githubusercontent.com/113076115/232225812-75a9a569-51d1-4294-a60f-b149e40426ff.png)
我直接改代码里的默认url就好了

**Comment by lss233** [comment]
你改错了，建议你认真看看项目教程。里面有完整的例子可以参考。
