### ISSUE TITLE
[BUG] Web版 ChatGPT 无法使用

### ISSUE THREAD

**Issue by Nan1chen** [lss233/chatgpt-mirai-qq-bot#639]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：windows
- Docker： ？
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过
![O7B~{YUFTNM9PLE4P`{~Y`H](https://user-images.githubusercontent.com/130864106/232247951-d4aa0aea-6b74-4f29-84eb-7350c706eea3.png)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by DesolateYH** [comment]
同样问题

**Comment by lss233** [comment]
由于OpenAI 的改动，网页版 ChatGPT 目前来看没得玩了。

**Comment by Nan1chen** [comment]
> 由于OpenAI公司的改动,网页版ChatGPT聊天机器人目前来看没得玩了。

大佬，我进下交流群

**Comment by MeiXiaoKe1212** [comment]
一样的问题

**Comment by VoltaDusk** [comment]
网页版问题+1，改用api正常使用

**Comment by MeiXiaoKe1212** [comment]
使用了api后直接不回复了怎么办？
![image](https://user-images.githubusercontent.com/83281832/232265993-c123d7cd-56ce-4e37-a3a3-03e76c64289f.png)

**Comment by lanybass** [comment]
现在已经变502了

**Comment by TaoismDeepLake** [comment]
502, +1
![image](https://user-images.githubusercontent.com/19328867/232324847-962ce9a5-da44-4025-a2d2-538aa53efb2a.png)

**Comment by lss233** [comment]
已有了暂时性的解决方法，参考：https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v2.4.0

**Comment by lanybass** [comment]
以后呢？说好的幸福呢？
