### ISSUE TITLE
安装 Chrome 或者 Chromium 的教程

### ISSUE THREAD

**Issue by 1847905557** [lss233/chatgpt-mirai-qq-bot#64]
最新版使用了 selenium，也就是说 Linux 上的 Playwright 大概寄了
我们是不是应该在 README 或者其它什么地方写写如何在 Linux 安装 Chrome 或者 Chromium，或者指个路？

**Comment by lss233** [comment]
确实要提醒一下需要安装浏览器。  
至于安装教程，网络上应该有很多。 主要是不同发行版之间的方法可能不太一样。  
Linux 用户其实还是建议通过 Docker 来部署比较方便的。  
Ubuntu 下安装的方式可以参考这个：
https://gist.github.com/Austcool-Walker/3f898ff04e5e0a9644ab487984e5eeec

**Comment by wangyijin209** [comment]
如果无桌面环境如何解决？
