### ISSUE TITLE
[Feature] 疑问

### ISSUE THREAD

**Issue by ivotai** [lss233/chatgpt-mirai-qq-bot#641]
为什么微软的语音可以转换很长的文字，并且最后没有转成 slik 格式。
自己模型的语音只能转换很短的文字，并且因为转成 slik 格式，音质变得很差。
我用自己训练的模型或者教程里推荐的模型，浏览器里效果很好，到机器人就很差了。

**Comment by lss233** [comment]
发到QQ上都会转成silk。音质差应该是QQ的问题
