### ISSUE TITLE
连接不上本地代理

### ISSUE THREAD

**Issue by LuvQi** [lss233/chatgpt-mirai-qq-bot#645]
**提交 issue 前，请先确认：**
- [否] 我已看过 **FAQ**，此问题不在列表中
- [是 ] 我已看过其他 issue，他们不能解决我的问题 
- [是 ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**运行环境:**  
- 操作系统：linux
- Docker： ？
- 项目版本：最新版

**复现步骤**  
描述你是如何触发这个 BUG 的
在config.cfg里，增加代理：
![L@LACTBDBM1G 543` _T9DA](https://user-images.githubusercontent.com/128845248/232306874-466aae82-1f9d-40dc-8cbe-08686c806e70.png)
然后重启的时候发现连接不上本地代理
![A }CLC3T@ `) ORBC~Z{ZQN](https://user-images.githubusercontent.com/128845248/232306895-d2c119bb-b3c2-430b-ae31-ef6bfce10087.png)
我设置了全局变量，使用下载指令，流量会经过这个代理，说明代理是没有问题的：
![image](https://user-images.githubusercontent.com/128845248/232307016-9a9fa4c9-27b9-4fbe-88da-eefb6a221b8d.png)

![TA8$%)@V0X6`O2`~LE_5SFF](https://user-images.githubusercontent.com/128845248/232306970-cb439526-94e4-4469-877b-89eb3037f4a1.png)
而且监听也有反应：
![)N@XQ{BI @A H5$4`BN8WGV](https://user-images.githubusercontent.com/128845248/232306988-434442e8-b668-40b8-b436-48df31c3e03b.png)

另外，我之后把上面的配置改回去，在compose里设置代理，gocqhttp和chatgpt日志都没有报错，可是就是没反应
![image](https://user-images.githubusercontent.com/128845248/232307516-b18175ef-3803-41d0-bc38-7af9b851383c.png)
![image](https://user-images.githubusercontent.com/128845248/232307558-e81ddf18-6695-4f91-9121-76b4b5f49e59.png)
机器人正常：
![image](https://user-images.githubusercontent.com/128845248/232307809-bedefeec-a1db-4d2d-9328-ebad826f35db.png)
chatgpt正常：
![image](https://user-images.githubusercontent.com/128845248/232307839-254740ff-3ce7-4563-91d8-86c892548a0d.png)
机器人反应：
![image](https://user-images.githubusercontent.com/128845248/232307900-1c3901de-19c6-4a03-8d84-66d7270a01c9.png)
chatgpt反应：
![image](https://user-images.githubusercontent.com/128845248/232307935-003c0ecf-91b9-47b6-a168-f175810d741b.png)

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**Comment by LuvQi** [comment]
这是config.cfg的截图：
![Uploading L@LACTBDBM1G]543`[_T9DA.png…]()

**Comment by LuvQi** [comment]
![L@LACTBDBM1G 543` _T9DA](https://user-images.githubusercontent.com/128845248/232308536-63dab608-92d4-4726-95ca-9366efdd865f.png)

**Comment by lss233** [comment]
写错了。你要写`proxy="http://127.0.0.1:1080"`

**Comment by guogegod** [comment]
解决了吗？
