### ISSUE TITLE
[BUG] 用户成功切换模型以后，openai显示的调用还是调用gpt3.5turbo

### ISSUE THREAD

**Issue by DEzioA** [lss233/chatgpt-mirai-qq-bot#646]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x ] 我已看过其他 issue，他们不能解决我的问题 
- [x ] 我认为这不是 Mirai 或者 OpenAI 的 BUG（我有gpt4的api资格，我在cursor之类的地方调用是成功的）

**表现**  
描述 BUG 的表现情况
后台用户输入“切换模型 gpt-4” 以后是成功切换模型的，但是最后我去openai账户的usage界面看到的所有调用都还是调用gpt-3.5-turbo 

**运行环境:**  
- 操作系统：windows
- Docker： ？
- 项目版本：最新，昨天刚配置的

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  

**截图**  
![image](https://user-images.githubusercontent.com/122096924/232312999-68e6ced5-86a5-41ec-97a9-64e243ab5e06.png)
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=7133251806677874174 skey=@crypt_15221ccd_378783c96240006c65a0cb59ae02a6c3 mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/122096924/232313194-1be9da27-b504-41d5-ab44-255c975186a6.jpg)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
这似乎是一个 OpenAI 的 BUG。 具体表现为：当请求使用 gpt-3.5-turbo 模型时，响应却为  gpt-3.5-turbo-0301。  
我用别的 API Key 测试，也是这个情况。
