### ISSUE TITLE
[BUG] python依赖问题，导致bot无法正常启动

### ISSUE THREAD

**Issue by Winnie0408** [lss233/chatgpt-mirai-qq-bot#648]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
更新到2.3.4.1，并更新python依赖
`pip install -r requirements.txt`
后，运行bot，提示
`No module named 'base'`

使用
`pip install base`
自行安装base

再次尝试运行bot
提示
`cannot import name 'DrawingAPI' from 'base' (/usr/local/lib/python3.10/dist-packages/base/__init__.py)`
且bot无法正常启动

降级回2.3.4，并再次更新python依赖
`pip install -r requirements.txt`
后，运行bot，一切正常

**运行环境:**  
- 操作系统：Ubuntu 22.04
- Docker： 无
- 项目版本：2.3.4.1

**复现步骤**  
描述你是如何触发这个 BUG 的
1. git clone 最新版本bot
2. pip安装依赖
3. 启动bot

**预期行为**  
bot能正常启动

**截图**  
![Screenshot_2023-04-16-23-40-22-732_com.server.auditor.ssh.client.png](https://user-images.githubusercontent.com/42741874/232324549-7d64f947-64b1-4dde-9735-0d20b9bcfef2.png)

**其他内容**  
无

**Comment by lss233** [comment]
更新代码即可。
