### ISSUE TITLE
502网关错误

### ISSUE THREAD

**Issue by ZyL0NG** [lss233/chatgpt-mirai-qq-bot#649]
**提交 issue 前，请先确认：**
我已看过 **FAQ**，此问题不在列表中
 我已看过其他 issue，他们不能解决我的问题 
 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：ubuntu
- Docker： docker-compose
- 项目版本：2.3.4

**复现步骤**  
描述你是如何触发这个 BUG 的
    机器人回复：
      糟糕！当前收到的请求太多了，我需要一段时间冷静冷静。你可以选择“重置会话”，或者过一会儿再来找我！
      预计恢复时间：Server error '502 Bad Gateway' for url 'https://bypass.churchless.tech/api/conversation'
      For more information check: https://httpstatuses.com/502

**截图**  
![image](https://user-images.githubusercontent.com/84181020/232324749-9a4432e1-d008-4b51-bd5b-db6c7ddc6dca.png)
![image](https://user-images.githubusercontent.com/84181020/232324772-abddef78-e3d6-4fcb-a407-2053a1be89fb.png)
![image](https://user-images.githubusercontent.com/84181020/232324809-1b0dd94b-3e5f-4606-9f7e-ef6e2bcf1363.png)

**Comment by lss233** [comment]
Web 版现在不能用了，看 #639
