### ISSUE TITLE
我有chrome，打开启动的时候chrome界面闪退

### ISSUE THREAD

**Issue by oldsheep0205** [lss233/chatgpt-mirai-qq-bot#65]
如题。还有一个是mirai提示Failed to load class "org.slf4j.impl.StaticLoggerBinder"，试了几次无法解决，是程序本身的bug嘛

**Comment by oldsheep0205** [comment]
已解决，卸载重装chrome即可

**Comment by lss233** [comment]
`Failed to load class "org.slf4j.impl.StaticLoggerBinder` 无视即可。 Mirai 的问题，和本项目无关，也不影响功能
