### ISSUE TITLE
尝试使用access token登录但抛出未知错误，但以前可以正常登录

### ISSUE THREAD

**Issue by ken0414** [lss233/chatgpt-mirai-qq-bot#650]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
登陆失败

**运行环境:**  
- 操作系统：debian
- Docker： docker compose 
- 项目版本：最新

**复现步骤**  
使用往常一样的登陆方式，在config中写入access token（ey开头），重启容器

**截图**  
日志如下

2023-04-17 01:33:19.385 | SUCCESS  | manager.bot:__check_proxy:322 - [代理测试] 连接成功！
2023-04-17 01:33:19.385 | INFO     | manager.bot:__login_V1:363 - 尝试使用 access_token 登录中...
2023-04-17 01:33:19.913 | ERROR    | manager.bot:login_openai:279 - 未知错误：
2023-04-17 01:33:19.913 | ERROR    | manager.bot:login_openai:280 - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/bot.py", line 16, in <module>
    loop.run_until_complete(botManager.login())
    │    │                  │          └ <function BotManager.login at 0x7ffa5cf99120>
    │    │                  └ <manager.bot.BotManager object at 0x7ffa5dafb690>
    │    └ <function BaseEventLoop.run_until_complete at 0x7ffa5eed91c0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7ffa5eed9120>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7ffa5eedaf20>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7ffa5f41fce0>
    └ <Handle <TaskStepMethWrapper object at 0x7ffa5ccd3d00>()>
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7ffa5ccd3d00>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7ffa5ccd3d00>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7ffa5ccd3d00>()>
  File "/app/manager/bot.py", line 112, in login
    await self.login_openai()
          │    └ <function BotManager.login_openai at 0x7ffa5cfb62a0>
          └ <manager.bot.BotManager object at 0x7ffa5dafb690>
> File "/app/manager/bot.py", line 256, in login_openai
    bot = await self.__login_V1(account)
                │               └ OpenAIAccessTokenAuth(mode='browserless', proxy='http://192.168.31.2:22222', driver_exec_path=None, browser_exec_path=None, c...
                └ <manager.bot.BotManager object at 0x7ffa5dafb690>
  File "/app/manager/bot.py", line 366, in __login_V1
    if await __V1_check_auth():
  File "/app/manager/bot.py", line 354, in __V1_check_auth
    await bot.get_conversations(0, 1)
          │   └ <function AsyncChatbot.get_conversations at 0x7ffa5cf98680>
          └ <revChatGPT.V1.AsyncChatbot object at 0x7ffa5d011910>
  File "/usr/local/lib/python3.11/site-packages/revChatGPT/V1.py", line 788, in get_conversations
    data = json.loads(response.text)
           │    │     │        └ <property object at 0x7ffa5d874e50>
           │    │     └ <Response [200 OK]>
           │    └ <function loads at 0x7ffa5ee11bc0>
           └ <module 'json' from '/usr/local/lib/python3.11/json/__init__.py'>
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ '<html>\n  <head>\n    <style global>body{font-family:Arial,Helvetica,sans-serif}.container{align-items:center;display:flex;f...
           │                └ <function JSONDecoder.decode at 0x7ffa5ee114e0>
           └ <json.decoder.JSONDecoder object at 0x7ffa5ee14dd0>
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ '<html>\n  <head>\n    <style global>body{font-family:Arial,Helvetica,sans-serif}.container{align-items:center;display:flex;f...
               │    │          │      └ <built-in method match of re.Pattern object at 0x7ffa5edf5630>
               │    │          └ '<html>\n  <head>\n    <style global>body{font-family:Arial,Helvetica,sans-serif}.container{align-items:center;display:flex;f...
               │    └ <function JSONDecoder.raw_decode at 0x7ffa5ee11580>
               └ <json.decoder.JSONDecoder object at 0x7ffa5ee14dd0>
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
          │                                  └ '<html>\n  <head>\n    <style global>body{font-family:Arial,Helvetica,sans-serif}.container{align-items:center;display:flex;f...
          └ <class 'json.decoder.JSONDecodeError'>
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-04-17 01:33:19.916 | SUCCESS  | manager.bot:login_openai:283 - 成功登录 0/1 个 OpenAI 账号！

**Comment by lss233** [comment]
#639
