### ISSUE TITLE
[BUG] 必应绘图报错：Redirect failed

### ISSUE THREAD

**Issue by tamakyi** [lss233/chatgpt-mirai-qq-bot#659]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
使用最新版本源码，在触发必应绘图功能，如“画一只狗”时报错，报错具体信息如下。

**运行环境:**  
- 操作系统：Debian 11 
- Docker： None
- 项目版本：最新源码

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 发送“画一只狗”
2. See error

**预期行为**  
正常回复图片

**截图**  
![image](https://user-images.githubusercontent.com/25850853/232544575-7a785ba8-cedf-49de-805a-3771b3d8ae23.png)

**其他内容**  
日志内容：
```
ERROR: <bound method ClientResponse.text of <ClientResponse(https://www.bing.com/images/create?q=%E4%B8%80%E5%8F%AA%E7%8B%97&rt=3&FORM=GENCRE) [200 OK]>
<CIMultiDictProxy('Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Content-Length': '41179', 'Content-Type': 'text/html; charset=utf-8', 'Content-Encoding': 'gzip', 'Expires': '-1', 'Vary': 'Accept-Encoding', 'P3P': 'CP="NON UNI COM NAV STA LOC CURa DEVa PSAa PSDa OUR IND"', 'Set-Cookie': 'XXXXX; expires=Sat, 11-May-2024 15:57:54 GMT; path=/; HttpOnly', 'Set-Cookie': 'GI_FRE_COOKIE=gi_prompt=2; domain=.bing.com; path=/; secure; SameSite=None', 'UserAgentReductionOptOut': 'XXXXX', 'Content-Security-Policy-Report-Only': "script-src https: 'strict-dynamic' 'report-sample' 'nonce-SLCMvYBA/FUvN5LUYnP0195M8dkg7GJHO69IReyhahQ='; base-uri 'self';report-to csp-endpoint", 'Report-To': '{"group":"csp-endpoint","max_age":86400,"endpoints":[{"url":"https://aefd.nelreports.net/api/report?cat=bingcsp"}]}', 'X-Cache': 'CONFIG_NOCACHE', 'Accept-CH': 'Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version', 'X-MSEdge-Ref': 'Ref A: D9C25F4B687240BC9B630EA416323862 Ref B: BOM02EDGE0411 Ref C: 2023-04-17T15:57:53Z', 'Date': 'Mon, 17 Apr 2023 15:57:53 GMT')>
>
2023-04-17 23:57:54.703 | ERROR    | universal:request:239 - Redirect failed
Traceback (most recent call last):

  File "/root/chatgpt-mirai-qq-bot/bot.py", line 41, in <module>
    loop.run_until_complete(asyncio.gather(*bots))
    │    │                  │       │       └ [<Task pending name='Task-2' coro=<start_task() running at /root/chatgpt-mirai-qq-bot/platforms/ariadne_bot.py:296> wait_for=...
    │    │                  │       └ <function gather at 0x7efd7a1e68e0>
    │    │                  └ <module 'asyncio' from '/root/miniconda3/envs/chatbot/lib/python3.11/asyncio/__init__.py'>
    │    └ <function BaseEventLoop.run_until_complete at 0x7efd7a20b7e0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/root/miniconda3/envs/chatbot/lib/python3.11/asyncio/base_events.py", line 637, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7efd7a20b740>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/root/miniconda3/envs/chatbot/lib/python3.11/asyncio/base_events.py", line 604, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7efd7a20d580>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/root/miniconda3/envs/chatbot/lib/python3.11/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7efd7a7322a0>
    └ <Handle <TaskStepMethWrapper object at 0x7efd7593f130>()>
  File "/root/miniconda3/envs/chatbot/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7efd7593f130>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7efd7593f130>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7efd7593f130>()>

> File "/root/chatgpt-mirai-qq-bot/universal.py", line 205, in request
    async for rendered in task:
                          └ <async_generator object retry.<locals>.decorator.<locals>.wrapper at 0x7efd76be39c0>

  File "/root/chatgpt-mirai-qq-bot/utils/retry.py", line 21, in wrapper
    async for result in func(*args, **kwargs):
                        │     │       └ {'prompt': '画一只狗', 'chain': MessageChain([Plain(text='画一只狗')]), 'name': '狼'}
                        │     └ (<conversation.ConversationContext object at 0x7efd7742ba50>,)
                        └ <function ConversationContext.ask at 0x7efd7709e480>

  File "/root/chatgpt-mirai-qq-bot/conversation.py", line 148, in ask
    images = await self.drawing_adapter.text_to_img(prompt)
                   │    │               │           └ '一只狗'
                   │    │               └ <function BingAdapter.text_to_img at 0x7efd7731f7e0>
                   │    └ <adapter.ms.bing.BingAdapter object at 0x7efd75979bd0>
                   └ <conversation.ConversationContext object at 0x7efd7742ba50>

  File "/root/chatgpt-mirai-qq-bot/adapter/ms/bing.py", line 104, in text_to_img
    images = await image_generator.get_images(prompt)
                   │               │          └ '一只狗'
                   │               └ <function ImageGenAsync.get_images at 0x7efd7731f420>
                   └ <BingImageCreator.ImageGenAsync object at 0x7efd75013f10>

  File "/root/miniconda3/envs/chatbot/lib/python3.11/site-packages/BingImageCreator.py", line 237, in get_images
    raise Exception("Redirect failed")

Exception: Redirect failed
```

**Comment by lss233** [comment]
已知问题，无法解决。

**Comment by gosick39** [comment]
可以尝试的解决办法：在浏览器上使用bing让他画图，访问www.bing.com/create让他画图，关键词只能用英文，例如：画cat

**Comment by tamakyi** [comment]
> bing画图关键词只能用英文
> 
> ![IMG_20230418_212619](https://user-images.githubusercontent.com/109009825/232791945-62e534f2-aab2-4d32-a4da-262c5afa5b5e.jpg)
> 
> 

![image](https://user-images.githubusercontent.com/25850853/232794453-3240e8fc-870d-47d2-8e53-d42659b9615a.jpeg)
感谢。但是我配置好关键词之后使用英文依旧无法触发，报错和之前一样。

**Comment by tamakyi** [comment]
> 你 要先在你的bin上开启画图https://www.bing.com/images/create
> 
> ![image](https://user-images.githubusercontent.com/109009825/232796146-da179476-d5a5-4f8a-929b-c8470b611320.png)
> 
> 

酷 登陆一次之后正常运行了！谢谢！

**Comment by yqs6666** [comment]
![image](https://user-images.githubusercontent.com/106430842/233033208-f1e95e57-2a07-4db3-bbd5-48625ad8d614.png)
这又是为啥呢

**Comment by IYATT-yx** [comment]
> ![image](https://user-images.githubusercontent.com/106430842/233033208-f1e95e57-2a07-4db3-bbd5-48625ad8d614.png) 这又是为啥呢

我也是遇到这种情况

**Comment by qy0625** [comment]
一样也不行

**Comment by IYATT-yx** [comment]
我更新了cookie又好了

**Comment by qy0625** [comment]
> 我更新了cookie又好了

我去试试 接入点用的默认么

**Comment by lss233** [comment]
> > 我更新了cookie又好了
> 
> 我去试试 接入点用的默认么

你可以执行 `ping www.bing.com` 看看是不是你的 DNS 配置有问题。

**Comment by laoqin6** [comment]
> > > 我更新了cookie又好了
> > 
> > 
> > 我去试试 接入点用的默认么
> 
> 你可以执行 `ping www.bing.com` 看看是不是你的 DNS 配置有问题。

重新抓了 还是一样 ping 没问题  还是报 画图失败！原因： Cannot connect to host www.bing.comhttps:443 ssl:default [Name or service not known]

**Comment by IYATT-yx** [comment]
好像是在 config.cfg 中 bing 账号设置的 proxy 并没有生效，我直接给运行的终端设置了 http_proxy 和 https_proxy 环境变量（Debian 11），再运行机器人就可以画了

**Comment by laoqin6** [comment]
&nbsp;我也设置了的也，还是不行，奇怪




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lss233/chatgpt-mirai-qq-bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月27日(星期四) 上午10:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lss233/chatgpt-mirai-qq-bot] [BUG] 必应绘图报错：Redirect failed (Issue #659)





 
好像是在 config.cfg 中 bing 账号设置的 proxy 并没有生效，我直接给运行的终端设置了 http_proxy 和 https_proxy 环境变量（Debian 11），再运行机器人就可以画了

**Comment by Huangxingyu0621** [comment]
> &nbsp;我也设置了的也，还是不行，奇怪
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lss233/chatgpt-mirai-qq-bot" ***@***.***&gt;; 发送时间:&nbsp;2023年4月27日(星期四) 上午10:06 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [lss233/chatgpt-mirai-qq-bot] [BUG] 必应绘图报错：Redirect failed (Issue #659) 好像是在 config.cfg 中 bing 账号设置的 proxy 并没有生效，我直接给运行的终端设置了 http_proxy 和 https_proxy 环境变量（Debian 11），再运行机器人就可以画了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你ping bing.com看看是不是跳到china bing123.com了，如果是的话就是config里的proxy没生效，你检查一下有没有被注释掉

**Comment by laoqin6** [comment]
没有跳，配置也在，没事，不管他，弄不好算了.


老秦博客
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lss233/chatgpt-mirai-qq-bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月27日(星期四) 下午2:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lss233/chatgpt-mirai-qq-bot] [BUG] 必应绘图报错：Redirect failed (Issue #659)





  
&nbsp;我也设置了的也，还是不行，奇怪
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lss233/chatgpt-mirai-qq-bot" @.&gt;; 发送时间:&nbsp;2023年4月27日(星期四) 上午10:06 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [lss233/chatgpt-mirai-qq-bot] [BUG] 必应绘图报错：Redirect failed (Issue #659) 好像是在 config.cfg 中 bing 账号设置的 proxy 并没有生效，我直接给运行的终端设置了 http_proxy 和 https_proxy 环境变量（Debian 11），再运行机器人就可以画了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
你ping bing.com看看是不是跳到china bing123.com了，如果是的话就是config里的proxy没生效，你检查一下有没有被注释掉

**Comment by lelelemr** [comment]
> > 你 要先在你的bin上开启画图https://www.bing.com/images/create
> > ![image](https://user-images.githubusercontent.com/109009825/232796146-da179476-d5a5-4f8a-929b-c8470b611320.png)
> 
> 酷 登陆一次之后正常运行了！谢谢！

有效

**Comment by lige47** [comment]
> 你要先在你的垃圾桶上启动图片https://www.bing.com/images/create ![图像](https://user-images.githubusercontent.com/109009825/232796146-da179476-d5a5-4f8a-929b-c8470b611320.png)

有用

**Comment by WhSong2000** [comment]
> > 你要先在你的垃圾桶上启动图片https://www.bing.com/images/create ![图像](https://user-images.githubusercontent.com/109009825/232796146-da179476-d5a5-4f8a-929b-c8470b611320.png)
> 
> 有用

请问如何启动图片？

**Comment by thomashooo** [comment]
要重新导入cookie，可能是我之前没登录？

**Comment by p1aintiff** [comment]
bing绘画失败
```
 File "/home/ubuntu/qqchat/chatqq/chatgpt-mirai-qq-bot/conversation.py", line 182, in ask
    raise DrawingFailedException from e
          └ <class 'exceptions.DrawingFailedException'>

exceptions.DrawingFailedException
2023-09-30 21:39:56.053 | DEBUG    | platforms.onebot_bot:respond:112 - [OneBot] 尝试发送消息：画图失败！原因： [Errno -2] Name or service not known
```

**Comment by wuq123** [comment]
> bing绘画失败
> 
> ```
>  File "/home/ubuntu/qqchat/chatqq/chatgpt-mirai-qq-bot/conversation.py", line 182, in ask
>     raise DrawingFailedException from e
>           └ <class 'exceptions.DrawingFailedException'>
> 
> exceptions.DrawingFailedException
> 2023-09-30 21:39:56.053 | DEBUG    | platforms.onebot_bot:respond:112 - [OneBot] 尝试发送消息：画图失败！原因： [Errno -2] Name or service not known
> ```

请问你解决了吗，我也报了个这个错😂

**Comment by zhou123tie** [comment]
2024-05-22 13:07:39.263 | DEBUG    | platforms.onebot_bot:respond:112 - [OneBot] 尝试发送消息：画图失败！原因： /rp/gmZtdJVd-klWl3XWpa6-ni1FU3M.svg
2024-05-22 13:07:40.033 | DEBUG    | adapter.ms.bing:__download_image:155 - [Bing AI] 下载完成：image/jpeg https://tse1.mm.bing.net/th/id/OIG2.WSqk.OlGrfYJ4kpXVKzd
2024-05-22 13:07:40.034 | DEBUG    | adapter.ms.bing:__download_image:155 - [Bing AI] 下载完成：image/jpeg https://tse2.mm.bing.net/th/id/OIG2.L5Hqi0Ik1AGimpyGN4Ac
2024-05-22 13:07:40.052 | DEBUG    | adapter.ms.bing:__download_image:155 - [Bing AI] 下载完成：image/jpeg https://tse2.mm.bing.net/th/id/OIG2.rDE5mtLvwxH37fMsnNxH
2024-05-22 13:07:40.925 | DEBUG    | adapter.ms.bing:__download_image:155 - [Bing AI] 下载完成：image/jpeg https://tse4.mm.bing.net/th/id/OIG2.g31QD5aByiGEOabTQxAx
2024-05-22 13:07:50.654 | DEBUG    | platforms.onebot_bot:respond:112 - [OneBot] 尝试发送消息：我还在思考中，请再等一下~
2024-05-22 13:07:50.665 | DEBUG    | middlewares.timeout:on_respond:40 - [Timeout] 取消计时……
2024-05-22 13:07:50.666 | DEBUG    | middlewares.timeout:create_timeout_task:58 - [Timeout] 等待过久，发送提示



我这个问题能绘制图片，但是发送不出来
