### ISSUE TITLE
TelegramBot 手动部署不了

### ISSUE THREAD

**Issue by Suyuan406** [lss233/chatgpt-mirai-qq-bot#660]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
2023-04-17 17:59:34.799 | INFO     | __main__:<module>:25 - 检测到 telegram 配置，将启动 telegram bot 模式……
2023-04-17 17:59:35.106 | ERROR    | utils.exithooks:foo:33 - 看样子程序似乎没有正常退出。
2023-04-17 17:59:35.106 | ERROR    | utils.exithooks:foo:34 - cannot import name 'ApplicationBuilder' from 'telegram.ext' (/root/miniconda3/envs/bot/lib/python3.11/site-packages/telegram/ext/__init__.py)
NoneType: None
2023-04-17 17:59:35.107 | ERROR    | utils.exithooks:foo:35 - 你可以在这里阅读常见问题的解决方案：
2023-04-17 17:59:35.107 | ERROR    | utils.exithooks:foo:36 - https://github.com/lss233/chatgpt-mirai-qq-bot/issues/85

**运行环境:**  
- 操作系统：ubuntu20.04
- miniconda上的python 3.11环境
- 项目版本：最新

**复现步骤**  
按照手动部署方式
git clone https://github.com/lss233/chatgpt-mirai-qq-bot
cd chatgpt-mirai-qq-bot
pip3 install -r requirements.txt
python3 bot.py

**预期行为**  
正常来说应该是可以启动的，麻烦作者大大看一下

**截图**  
相关日志、聊天记录的截图，没有可跳过
![屏幕截图 2023-04-18 015942](https://user-images.githubusercontent.com/73843390/232573032-0140b2de-9607-4578-b7eb-fe914f18b1ff.png)

**Comment by eomly** [comment]
遇到了一模一样的问题 @lss233

**Comment by lss233** [comment]
有点奇怪. 你打一下 pip freeze 看看现在装的是什么版本的依赖?

**Comment by Suyuan406** [comment]
root@cloud:~/chatgpt-mirai-qq-bot# pip freeze
aiocqhttp==1.4.3
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
anyio==3.6.2
APScheduler==3.6.3
async-timeout==4.0.2
asyncio==3.4.3
attrs==23.1.0
azure-cognitiveservices-speech==1.27.0
BingImageCreator==0.1.2.1
blinker==1.6.2
cachetools==4.2.2
certifi==2022.12.7
charset-normalizer==3.1.0
click==8.1.3
creart==0.2.2
creart-graia==0.1.5
discord.py==2.2.2
edge-tts==6.1.3
EdgeGPT==0.1.25.1
frozenlist==1.3.3
graia-amnesia==0.7.1
graia-ariadne==0.11.3
graia-broadcast==0.19.2
graiax-silkcoder==0.3.6
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==0.17.0
httpx==0.24.0
hypercorn==0.14.3
hyperframe==6.0.1
idna==3.4
imgkit==1.2.3
importlib-metadata==6.4.1
itsdangerous==2.1.2
Jinja2==3.1.2
launart==0.6.3
loguru==0.7.0
Markdown==3.4.3
markdown-it-py==2.2.0
MarkupSafe==2.1.2
mdurl==0.1.2
mkl-fft==1.3.1
mkl-random @ file:///work/ci_py311/mkl_random_1676828032909/work
mkl-service==2.4.0
multidict==6.0.4
numpy @ file:///work/ci_py311/numpy_and_numpy_base_1676823870601/work
openai==0.27.4
OpenAIAuth==0.3.6
packaging==23.1
Pillow==9.5.0
poe-api==0.2.12
priority==2.0.0
prompt-toolkit==3.0.38
pydantic==1.10.7
Pygments==2.15.0
pypng==0.20220715.0
PySocks==1.7.1
python-dateutil==2.8.2
python-markdown-math==0.8
python-socks==2.2.0
python-telegram-bot==13.15
pytz==2023.3
pytz-deprecation-shim==0.1.0.post0
qrcode==7.4.2
quart==0.17.0
regex==2023.3.23
requests==2.28.2
revChatGPT==4.2.3
rich==13.3.4
six @ file:///tmp/build/80754af9/six_1644875935023/work
sniffio==1.3.0
socksio==1.0.0
statv==0.3.2
tiktoken==0.3.3
tinydb==4.7.1
tls-client==0.2
toml==0.10.2
tornado==6.1
tqdm==4.65.0
typing_extensions==4.5.0
tzdata==2023.3
tzlocal==4.3
urllib3==1.26.15
uuid==1.30
wcwidth==0.2.6
websocket-client==1.5.1
websockets==11.0.1
Werkzeug==2.2.3
wsproto==1.2.0
yarl==1.8.2
zipp==3.15.0

**Comment by Suyuan406** [comment]
> 有点奇怪. 你打一下 pip freeze 看看现在装的是什么版本的依赖?

root@cloud:~/chatgpt-mirai-qq-bot# pip freeze
aiocqhttp==1.4.3
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
anyio==3.6.2
APScheduler==3.6.3
async-timeout==4.0.2
asyncio==3.4.3
attrs==23.1.0
azure-cognitiveservices-speech==1.27.0
BingImageCreator==0.1.2.1
blinker==1.6.2
cachetools==4.2.2
certifi==2022.12.7
charset-normalizer==3.1.0
click==8.1.3
creart==0.2.2
creart-graia==0.1.5
discord.py==2.2.2
edge-tts==6.1.3
EdgeGPT==0.1.25.1
frozenlist==1.3.3
graia-amnesia==0.7.1
graia-ariadne==0.11.3
graia-broadcast==0.19.2
graiax-silkcoder==0.3.6
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==0.17.0
httpx==0.24.0
hypercorn==0.14.3
hyperframe==6.0.1
idna==3.4
imgkit==1.2.3
importlib-metadata==6.4.1
itsdangerous==2.1.2
Jinja2==3.1.2
launart==0.6.3
loguru==0.7.0
Markdown==3.4.3
markdown-it-py==2.2.0
MarkupSafe==2.1.2
mdurl==0.1.2
mkl-fft==1.3.1
mkl-random @ file:///work/ci_py311/mkl_random_1676828032909/work
mkl-service==2.4.0
multidict==6.0.4
numpy @ file:///work/ci_py311/numpy_and_numpy_base_1676823870601/work
openai==0.27.4
OpenAIAuth==0.3.6
packaging==23.1
Pillow==9.5.0
poe-api==0.2.12
priority==2.0.0
prompt-toolkit==3.0.38
pydantic==1.10.7
Pygments==2.15.0
pypng==0.20220715.0
PySocks==1.7.1
python-dateutil==2.8.2
python-markdown-math==0.8
python-socks==2.2.0
python-telegram-bot==13.15
pytz==2023.3
pytz-deprecation-shim==0.1.0.post0
qrcode==7.4.2
quart==0.17.0
regex==2023.3.23
requests==2.28.2
revChatGPT==4.2.3
rich==13.3.4
six @ file:///tmp/build/80754af9/six_1644875935023/work
sniffio==1.3.0
socksio==1.0.0
statv==0.3.2
tiktoken==0.3.3
tinydb==4.7.1
tls-client==0.2
toml==0.10.2
tornado==6.1
tqdm==4.65.0
typing_extensions==4.5.0
tzdata==2023.3
tzlocal==4.3
urllib3==1.26.15
uuid==1.30
wcwidth==0.2.6
websocket-client==1.5.1
websockets==11.0.1
Werkzeug==2.2.3
wsproto==1.2.0
yarl==1.8.2
zipp==3.15.0

**Comment by qq875871130** [comment]
我一键部署的也出现了这个问题

**Comment by lss233** [comment]
你的依赖版本有点旧了. 
pip install -U python-telegram-bot==20.2 试试

**Comment by lss233** [comment]
配置文件问题, 自行查找相关issue解决吧
