### ISSUE TITLE
[BUG] sd 503 错误

### ISSUE THREAD

**Issue by ivotai** [lss233/chatgpt-mirai-qq-bot#662]
糟糕！当前收到的请求太多了，我需要一段时间冷静冷静。你可以选择“重置会话”，或者过一会儿再来找我！\n预计恢复时间：Server error '503 Service Unavailable' for url 'http://127.0.0.1:7860/sdapi/v1/txt2img'\nFor more information check: https://httpstatuses.com/503\n

用本地 sd 绘图时，请求次数到一定次数就报 503 了

浏览器直接访问是 405，detail : method not allow

请问大大，是什么原因啊，访问本地有次数限制。

**Comment by lss233** [comment]
这肯定是你sd的问题。
