### ISSUE TITLE
[BUG] 未知错误：[Errno -2] Name or service not known

### ISSUE THREAD

**Issue by ZyL0NG** [lss233/chatgpt-mirai-qq-bot#663]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
机器人回复（重置会话也没用）：
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
原因：[Errno -2] Name or service not known

**运行环境:**  
- 操作系统：ubuntu
- Docker： √
- 项目版本：2.3.4

**截图**  
![image](https://user-images.githubusercontent.com/84181020/232676455-5cf7a9d9-f4eb-49ae-a070-3b3b5e99f00c.png)
![image](https://user-images.githubusercontent.com/84181020/232676498-fbdb4f6a-9488-4bf4-a721-50b4045622c0.png)
![image](https://user-images.githubusercontent.com/84181020/232676543-aedfae7b-1a15-46ab-ac23-0128445d7d69.png)
![image](https://user-images.githubusercontent.com/84181020/232676604-76c6c3d2-0209-4530-b088-25c30dcd5407.png)

**Comment by lss233** [comment]
那个 browserless_endpoint 又不能用了。改成别的吧

**Comment by 570351700squirrel** [comment]
我是windows本地运行 也突然报这个错 之前是正常运行的

**Comment by lss233** [comment]
最新的解决方法：升级最新版，然后删除配置文件中的 browserless_endpoint 设置。
