### ISSUE TITLE
[BUG] SD 默认设置错误，config.py中的  cfg_scale: float =0.75 应调整为cfg_scale: float = 7.5 

### ISSUE THREAD

**Issue by appleatiger** [lss233/chatgpt-mirai-qq-bot#669]
**提交 issue 前，请先确认：**
- [X] 我已看过 **FAQ**，此问题不在列表中
- [X] 我已看过其他 issue，他们不能解决我的问题 
- [X] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
config.py中的  cfg_scale: float = 0.75 是一个极低的值，相关性会非常的弱，导致图像扭曲。建议应调整为cfg_scale: float = 7.5 

**运行环境:**  
- 操作系统：win11
- Docker：no
- 项目版本：2.4.1

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 任意使用sd模块画图 画 cat

**预期行为**  
画 cat后应该出现 猫,实际图像扭曲变形

**其他内容**

**Comment by lss233** [comment]
感谢提醒，下个版本修复
