### ISSUE TITLE
无限循环

### ISSUE THREAD

**Issue by jamesocy** [lss233/chatgpt-mirai-qq-bot#67]
因为是国外服务器，在登陆qq时导致需要滑动验证，内置TxCaptchaHelper已经不再能够使用
https://github.com/mzdluo123/TxCaptchaHelper

**Comment by jamesocy** [comment]
已解决。
https://install.appcenter.ms/users/mzdluo123/apps/txcaptchahelper/distribution_groups/public TxCaptchaHelper程序，仅限安卓，可以使用模拟器。
如果验证码成功后显示版本太低，删除/mirai/bots下数据重新登陆即可

**Comment by jamesocy** [comment]
有遇到了新的问题
chatgpt_1  | 2023-01-07 20:28:24,623  expected permissions 700 but found 750
chatgpt_1  | 2023-01-07 20:28:24,624 created unix domain socket '/run/user/1000/xpra/aa4aaf3b9971-0'
chatgpt_1  | 2023-01-07 20:28:24,624 created unix domain socket '/tmp/0/socket'
chatgpt_1  | 2023-01-07 20:28:24,624 xvfb pid=11
chatgpt_1  | 2023-01-07 20:28:24,697 Warning: cannot watch for application menu changes without pyinotify:
chatgpt_1  | 2023-01-07 20:28:24,697  No module named 'pyinotify'
chatgpt_1  | 2023-01-07 20:28:24,703 Warning: cannot load menu data
chatgpt_1  | 2023-01-07 20:28:24,703  No module named 'xdg'
chatgpt_1  | 2023-01-07 20:28:24,776 Warning: webcam forwarding is disabled
chatgpt_1  | 2023-01-07 20:28:24,776  the virtual video directory '/sys/devices/virtual/video4linux' was not found
chatgpt_1  | 2023-01-07 20:28:24,776  make sure that the 'v4l2loopback' kernel module is installed and loaded
chatgpt_1  | 2023-01-07 20:28:24,776  or use the 'webcam=no' option
chatgpt_1  | 2023-01-07 20:28:24,778 found 0 virtual video devices for webcam forwarding
chatgpt_1  | 2023-01-07 20:28:24,781 started command `xterm -e python bot.py 2>&1 | tee /tmp/log.txt` with pid 37
chatgpt_1  | xterm: cannot load font "-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso10646-1"
chatgpt_1  | 2023-01-07 20:28:25,041 1.8GB of system memory
chatgpt_1  | 2023-01-07 20:28:25,075 Warning: OpenGL support check failed:
chatgpt_1  | 2023-01-07 20:28:25,075  unknown error
chatgpt_1  | 2023-01-07 20:28:25,236 xpra is ready.
chatgpt_1  | 2023-01-07 20:28:25,237 xpra X11 seamless version 4.4.3-r0 64-bit
chatgpt_1  | 2023-01-07 20:28:25,237  uid=0 (root), gid=0 (root)
chatgpt_1  | 2023-01-07 20:28:25,237  running with pid 7 on Linux Debian 11 bullseye
chatgpt_1  | 2023-01-07 20:28:25,238  connected to X11 display :0 with 24 bit colors
chatgpt_1  | 2023-01-07 20:28:26.060 | INFO     | chatbot:<module>:19 - 登录 OpenAI 中……
chatgpt_1  | 2023-01-07 20:28:26.060 | INFO     | chatbot:<module>:20 - 请在新打开的浏览器窗口中完成验证
chatgpt_1  | 2023-01-07 20:28:26.060 | INFO     | chatbot:<module>:22 - 如果您使用 xpra，请使用自己的浏览器访问 xpra 程序的端口，以访问到本程序启动的浏览器。
再次无限循环了。

**Comment by jamesocy** [comment]
captcha和session_token测试后都是无限循环

**Comment by lss233** [comment]
这和是不是 Docker Compose 部署没什么关系，需要提供后续的日志。

**Comment by lss233** [comment]
我这里试着复现了一下，具体的情况如下：  
OpenAI 现在有 Cloudflare 拦截请求，所以我们不能直接通过 Python 代码来使用 ChatGPT。  
绕过拦截的方式就是打开一次浏览器，获取 `cf_clearance` 这个 Cookie，
然后在接下来的 Python 请求中带上这个 Cookie 模拟自己是浏览器，以此绕过 Cloudflare。

目前来看，启动浏览器的时候确实是顺利拿到了 `cf_clearance`。
但是如果要向 ChatGPT 提问，还得请求 `/api/auth/session` 获取 `accessToken`。
问题就出在这里，这个请求的发送是通过 Python 代码实现的，而且这次请求被 Cloudflare 再次拦截了。  
所以它会尝试重新打开浏览器，获取新的 `cf_clearance` 。

这就是为什么出现无限循环的情况。
