### ISSUE TITLE
[BUG] manager.bot:login_openai:281 - 未知错误

### ISSUE THREAD

**Issue by lIlIlllllmeng** [lss233/chatgpt-mirai-qq-bot#671]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
manager.bot:login_openai:281 - 未知错误

**截图**  
![image](https://user-images.githubusercontent.com/94682166/233094345-fc1d3773-0690-4a7f-8685-e1e8f20a9333.png)
![image](https://user-images.githubusercontent.com/94682166/233094503-40029feb-9b77-49e0-aa30-92787f1aee04.png)

是因为网络原因造成的吗?

**Comment by lss233** [comment]
#663

**Comment by lss233** [comment]
#663
