### ISSUE TITLE
[BUG] 登录成功，但日志有问题

### ISSUE THREAD

**Issue by huangzhitian** [lss233/chatgpt-mirai-qq-bot#672]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：linux
- Docker： ？
- 项目版本：最新

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
![QQ截图20230419222656](https://user-images.githubusercontent.com/129321746/233106693-f2484f6c-d9b5-4e6e-8509-190c33fa75f8.png)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
先根据【常见问题解答】进行排查：https://chatgpt-qq.lss233.com/chang-jian-wen-ti-jie-da/chatgpt-qi-dong-guo-cheng-zhong-de-chang-jian-wen-ti

**Comment by huangzhitian** [comment]
> 先根据【常见问题解答】进行排查：https://chatgpt-qq.lss233.com/chang-jian-wen-ti-jie-da/chatgpt-qi-dong-guo-cheng-zhong-de-chang-jian-wen-ti
额 ， 现在在又有新问题了

**Comment by huangzhitian** [comment]
> 先根据【常见问题解答】进行排查：https://chatgpt-qq.lss233.com/chang-jian-wen-ti-jie-da/chatgpt-qi-dong-guo-cheng-zhong-de-chang-jian-wen-ti

![}``_(UN9~4Q`T99EJBR%6AU](https://user-images.githubusercontent.com/129321746/233251797-5799f289-8b41-473d-ae42-f36446a41b25.png)

**Comment by lss233** [comment]
经典问题了。删除 mirai/bots 文件夹，登录的时候使用 MACOS 协议。  实在不行用 go-cqhttp

**Comment by huangzhitian** [comment]
> 经典问题了。删除 mirai/bots 文件夹，登录的时候使用 MACOS 协议。 实在不行用 go-cqhttp

什么协议都试过了，这不是登录失败问题吧，之前登录失败是红字现在白的

**Comment by lss233** [comment]
是，和颜色没有关系。

**Comment by huangzhitian** [comment]
> 是，和颜色没有关系。

 go-cqhttp我一直登录不了
![QQ截图20230420114908](https://user-images.githubusercontent.com/129321746/233253845-54be9a23-e109-4a22-851e-43f24714a604.png)

**Comment by lss233** [comment]
如果你登录不上 gocqhttp，可以在本地下载并启动 gocqhttp，登录你的机器人账号
登录成功后，把 session.token 上传到服务器 ~/chatgpt-qq/gocqhttp 下，替换原有的文件（这个文件包含的是账号的登录信息）
然后你可以执行 docker-compose restart 重启程序。
执行 docker-compose logs -f -tail=200 gocqhttp 来查看 gocqhttp 的日志，看看机器人账号是否登录成功。
