### ISSUE TITLE
[BUG] Exception: 用户访问被限制

### ISSUE THREAD

**Issue by wzh195879702** [lss233/chatgpt-mirai-qq-bot#676]
**提交 issue 前，请先确认：**
 我已看过 FAQ，此问题不在列表中
我已看过其他 issue，他们不能解决我的问题
我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
使用文心一言时返回 Exception: 用户访问被限制

**运行环境:**  
- 操作系统：Ubuntu  22.04 64位
- Docker： ？
- 项目版本：2.4.1

**复现步骤**  
使用文心一言时返回 Exception: 用户访问被限制

root@iZ0jl6ghcrq4nalxyy1npmZ:~# screen -S robo
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f3eb4046de0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f3eb458bc40>
    └ <Handle <TaskStepMethWrapper object at 0x7f3eaf145660>()>
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f3eaf145660>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f3eaf145660>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f3eaf145660>()>

> File "/app/universal.py", line 206, in request
    async for rendered in task:
                          └ <async_generator object retry.<locals>.decorator.<locals>.wrapper at 0x7f3eb0eab5b0>

  File "/app/utils/retry.py", line 21, in wrapper
    async for result in func(*args, **kwargs):
                        │     │       └ {'prompt': '你好', 'chain': MessageChain([Plain(text='你好')]), 'name': '123'}
                        │     └ (<conversation.ConversationContext object at 0x7f3eaf0a4490>,)
                        └ <function ConversationContext.ask at 0x7f3eb0f0f240>

  File "/app/conversation.py", line 173, in ask
    async for item in self.adapter.ask(prompt):
                      │    │       │   └ '你好'
                      │    │       └ <function YiyanAdapter.ask at 0x7f3eb1dba980>
                      │    └ <adapter.baidu.yiyan.YiyanAdapter object at 0x7f3eb1152910>
                      └ <conversation.ConversationContext object at 0x7f3eaf0a4490>

  File "/app/adapter/baidu/yiyan.py", line 106, in ask
    self.__check_response(req.json())
    │                     │   └ <function Response.json at 0x7f3eb2a300e0>
    │                     └ <Response [200 OK]>
    └ <adapter.baidu.yiyan.YiyanAdapter object at 0x7f3eb1152910>

  File "/app/adapter/baidu/yiyan.py", line 162, in __check_response
    raise Exception(resp['msg'])
                    └ {'code': 40005, 'msg': '用户访问被限制', 'data': None, 'logId': '118000001028738511'}

Exception: 用户访问被限制

**Comment by superboyyy** [comment]
大概率被封号了

**Comment by wzh195879702** [comment]
但官网还能正常使用


> 大概率被封号了

**Comment by lss233** [comment]
已修复。

**Comment by xixixi2000** [comment]
> 已修复。

the problem still exist yet

**Comment by xixixi2000** [comment]
it still happens from yesterday

**Comment by beichen123-hub** [comment]
修复在哪里了 还是没办法使用也更新了最新版
