### ISSUE TITLE
获取到 session_token 之后再次打开了浏览器

### ISSUE THREAD

**Issue by jamesocy** [lss233/chatgpt-mirai-qq-bot#68]
配置好2Captcha API后启动程序，会导致无限打开openai官网，登陆，验证，关闭，再次打开。
日志显示已经获取session_token，2Captcha的api也显示成功使用并扣除了费用。

**Comment by jamesocy** [comment]
2023-01-08 04:18:45.776 | INFO     | chatbot:<module>:19 - 登录 OpenAI 中……
2023-01-08 04:18:45.776 | INFO     | chatbot:<module>:20 - 请在新打开的浏览器窗口中完成验证
Waiting for captcha to be solved...
Captcha solved successfully!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Found Session Token!
Login successful.
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.

**Comment by fstkonjac** [comment]
我也有这个问题。Windows系统，手动填写session token登录，使用代理（不用代理会显示Access denied）
```
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
Browser spawned.
Found Cloudflare Cookie!
Spawning browser...
```

**Comment by lss233** [comment]
我这里试着复现了一下，发现在 session token 过期的情况下会有这个情况。
有没有试过换一个 session_token，或者使用 微软账户登录？

**Comment by lss233** [comment]
@fstkonjac @jamesocy 
这似乎是一个上游的 bug。
可以试试 v1.5 的手动登录能否解决你们的问题

**Comment by lss233** [comment]
合并到 #67 进行讨论
