### ISSUE TITLE
[BUG] 看样子程序似乎没有正常退出。 'CHATGPT_FOR_BOT_FULL_CONFIG'

### ISSUE THREAD

**Issue by lanybass** [lss233/chatgpt-mirai-qq-bot#682]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

···
chatgpt-qq-chatgpt-1     |      If this server is no longer running, remove /tmp/.X0-lock
chatgpt-qq-chatgpt-1     |      and start again.
chatgpt-qq-chatgpt-1     | (EE)
chatgpt-qq-chatgpt-1     | 2023-04-21 08:04:56.951 | ERROR    | utils.exithooks:foo:33 - 看样子程序似
chatgpt-qq-chatgpt-1     | 2023-04-21 08:04:56.951 | ERROR    | utils.exithooks:foo:34 - 'CHATGPT_FO
chatgpt-qq-chatgpt-1     | NoneType: None
chatgpt-qq-chatgpt-1     | 2023-04-21 08:04:56.952 | ERROR    | utils.exithooks:foo:35 - 你可以在这里
chatgpt-qq-chatgpt-1     | 2023-04-21 08:04:56.952 | ERROR    | utils.exithooks:foo:36 - https://git
chatgpt-qq-chatgpt-1 exited with code 1

chatgpt-qq-chatgpt-1     | (EE)
chatgpt-qq-chatgpt-1     | Fatal server error:
chatgpt-qq-chatgpt-1     | (EE) Server is already active for display 0
chatgpt-qq-chatgpt-1     |      If this server is no longer running, remove /tmp/.X0-lock
chatgpt-qq-chatgpt-1     |      and start again.
chatgpt-qq-chatgpt-1     | (EE)
chatgpt-qq-chatgpt-1     | 2023-04-21 08:06:00.788 | ERROR    | utils.exithooks:foo:33 - 看样子程序似乎没有正常退出。
chatgpt-qq-chatgpt-1     | 2023-04-21 08:06:00.788 | ERROR    | utils.exithooks:foo:34 - 'CHATGPT_FOR_BOT_FULL_CONFIG'
chatgpt-qq-chatgpt-1     | NoneType: None
chatgpt-qq-chatgpt-1     | 2023-04-21 08:06:00.789 | ERROR    | utils.exithooks:foo:35 - 你可以在这里阅读常见问题的解决方案：
chatgpt-qq-chatgpt-1     | 2023-04-21 08:06:00.789 | ERROR    | utils.exithooks:foo:36 - https://github.com/lss233/chatgpt-mirai-qq-bot/issues/85
···

**Comment by lss233** [comment]
升级至最新代码即可解决。
```
docker-compose pull && docker-compose up -d
```

**Comment by Moebyte** [comment]
好像没有效果，poe用不了

**Comment by lss233** [comment]
> 好像没有效果，poe用不了

poe 不能用和这个 issue 没有关系吧？
