### ISSUE TITLE
[BUG] 无法连接至go-cqhttp

### ISSUE THREAD

**Issue by Wangmomo667** [lss233/chatgpt-mirai-qq-bot#684]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
发现mirai无法登录后改用go-cqhttp，跟着文档设置后报错”连接到反向WebSocket Universal服务器 ws://localhost:8566/ws 时出现错误: dial tcp 127.0.0.1:8566: connect: connection refused “，无法正常启动，是我配置文件有问题吗？实在搞不定求救大佬

**运行环境:**  
- 操作系统：Ubuntu20.04
- Docker：23.0.2
- 项目版本：2.4.2

**复现步骤**  
描述你是如何触发这个 BUG 的
每次启动都报错

**截图**  
![image](https://user-images.githubusercontent.com/94622958/233758934-88c0efca-7894-40e9-bea8-56b2a1ef4cca.png)
![5IQQARIVKD)5{` @SVD~WPC](https://user-images.githubusercontent.com/94622958/233758940-534352e9-6814-4f8a-907d-611a59e8386e.png)

**其他内容**  
chatgpt配置文件
`[onebot]
qq = 1279596549   
manager_qq = 29897996
reverse_ws_host = "0.0.0.0"
reverse_ws_port = 8566`

go-cqhttp配置文件
`- ws-reverse:
      # 反向WS Universal 地址
      # 注意 设置了此项地址后下面两项将会被忽略
      universal: ws://localhost:8566/ws
      # 反向WS API 地址
      api: ws://your_websocket_api.server
      # 反向WS Event 地址
      event: ws://your_websocket_event.server
      # 重连间隔 单位毫秒
      reconnect-interval: 3000
      middlewares:
        <<: *default # 引用默认中间件`

docker-compose.yaml
`version: '3.4'
services:
  gocqhttp:
    image: ghcr.io/mrs4s/go-cqhttp:master
    restart: always
    environment:
      LANG: 'C.UTF-8'
    volumes:
      - ./gocqhttp/:/data/
  chatgpt:
    image: lss233/chatgpt-mirai-qq-bot:browser-version
    restart: always
    environment:
      LANG: 'C.UTF-8'
    ports:
      #- 14501:14500
      - 8566:8566/tcp
    volumes:
      - ./config.cfg:/app/config.cfg
      - ./data:/app/data
      - ./presets:/app/presets
      # - ./fonts:/app/fonts # 如果你想自定义字体，就解除注释
  watchtower: # [可选] 自动更新
    image: containrrr/watchtower
    volumes: # 如果启动失败，请修改下面这条：
      - /var/run/docker.sock:/var/run/docker.sock`

**Comment by william20210206** [comment]
同样问题未解决

**Comment by lss233** [comment]
你的 gocqhttp 是运行在容器外的还是容器内的？

**Comment by Wangmomo667** [comment]
> 你的 gocqhttp 是运行在容器外的还是容器内的？

是在容器内运行的，我使用了项目中的`docker-compose-gocqhttp.yaml`部署项目

**Comment by lss233** [comment]
这样的话那不应该把 websocket 地址设置成 localhost 吧，你应该填`chatgpt`。
 这里建议用 一键脚本部署。

**Comment by Wangmomo667** [comment]
> 这样的话那不应该把 websocket 地址设置成 localhost 吧，你应该填`chatgpt`。
>  这里建议用 一键脚本部署。

解决了！谢谢大佬！

**Comment by GudaoO** [comment]
> > 这样的话那不应该把 websocket 地址设置成 localhost 吧，你应该填`chatgpt`。
> > 这里建议用 一键脚本部署。
> 
> 解决了！谢谢大佬！

同样的问题，大哥请问怎么解决的
我用了一键部署了

**Comment by GudaoO** [comment]
哥能给个Q私聊一下嘛，有差不多的问题

**Comment by GudaoO** [comment]
> > 这样的话那不应该把 websocket 地址设置成 localhost 吧，你应该填`chatgpt`。
> > 这里建议用 一键脚本部署。
> 
> 解决了！谢谢大佬！

哥能给个Q私聊一下嘛，有差不多的问题

**Comment by Wangmomo667** [comment]
> > > 这样的话那不应该把 websocket 地址设置成 localhost 吧，你应该填`chatgpt`。
> > > 这里建议用 一键脚本部署。
> > 
> > 解决了！谢谢大佬！
> 
> 哥能给个Q私聊一下嘛，有差不多的问题
> 
> 
> 

啥报错啊？估计我这浅薄的知识也帮不上你😂

**Comment by GudaoO** [comment]
> 

没事，有大佬帮我解决了(#^.^#)

**Comment by GudaoO** [comment]
> > > > 这样的话那不应该把 websocket 地址设置成 localhost 吧，你应该填`chatgpt`。
> > > > 这里建议用 一键脚本部署。
> > > 
> > > 
> > > 解决了！谢谢大佬！
> > 
> > 
> > 哥能给个Q私聊一下嘛，有差不多的问题
> 
> 啥报错啊？估计我这浅薄的知识也帮不上你😂
没事，有大佬帮我解决了(#^.^#)

**Comment by LYS-png** [comment]
哥们你可以把修改的地方告诉一下吗，我也是这个问题，QQ和openai都登录上了就是这个反向错误
