### ISSUE TITLE
 'NoneType' object has no attribute 'authorization' NoneType: None

### ISSUE THREAD

**Issue by dylanm199009** [lss233/chatgpt-mirai-qq-bot#686]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：？
- Docker： ？
- 项目版本：最新

**复现步骤**  
启动时报错  'NoneType' object has no attribute 'authorization' NoneType: None

**预期行为**  
启动时报错，会一直重新加载该错误

**截图**  
![~50GUWZCBFTIVG3XI $YJD5](https://user-images.githubusercontent.com/126437614/233775640-a27213c2-8ffe-4f9e-8fc4-93de1df0be05.png)

**其他内容**  
chatgpt-qq-chatgpt-1     | 2023-04-22 09:17:40.837 | SUCCESS  | manager.bot:login_openai:310 - 成功登录 1/1 个 OpenAI 账号！
chatgpt-qq-chatgpt-1     | 2023-04-22 09:17:40.837 | INFO     | manager.bot:login:141 - AI 类型：chatgpt-web - 可用账号： 0 个
chatgpt-qq-chatgpt-1     | 2023-04-22 09:17:40.838 | INFO     | manager.bot:login:141 - AI 类型：openai-api - 可用账号： 1 个
chatgpt-qq-chatgpt-1     | 2023-04-22 09:17:40.838 | INFO     | manager.bot:login:141 - AI 类型：poe-web - 可用账号： 0 个
chatgpt-qq-chatgpt-1     | 2023-04-22 09:17:40.846 | INFO     | manager.bot:login:141 - AI 类型：bing-cookie - 可用账号： 0 个
chatgpt-qq-chatgpt-1     | 2023-04-22 09:17:40.847 | INFO     | manager.bot:login:141 - AI 类型：bard-cookie - 可用账号： 0 个
chatgpt-qq-chatgpt-1     | 2023-04-22 09:17:40.847 | INFO     | manager.bot:login:141 - AI 类型：yiyan-cookie - 可用账号： 0 个
chatgpt-qq-chatgpt-1     | 2023-04-22 09:17:40.849 | INFO     | manager.bot:login:141 - AI 类型：chatglm-api - 可用账号： 0 个
chatgpt-qq-chatgpt-1     | 2023-04-22 09:17:40.850 | INFO     | __main__:<module>:22 - 检测到 Onebot 配置，将启动 Onebot 模式……
chatgpt-qq-chatgpt-1     | 2023-04-22 09:17:44.387 | ERROR    | utils.exithooks:foo:36 - 看样子程序似乎没有正常退出。
chatgpt-qq-chatgpt-1     | 2023-04-22 09:17:44.390 | ERROR    | utils.exithooks:foo:37 - 'NoneType' object has no attribute 'authorization'
chatgpt-qq-chatgpt-1     | NoneType: None
chatgpt-qq-chatgpt-1     | 2023-04-22 09:17:44.394 | ERROR    | utils.exithooks:foo:38 - 你可以在这里阅读常见问题的解决方案：
chatgpt-qq-chatgpt-1     | 2023-04-22 09:17:44.396 | ERROR    | utils.exithooks:foo:39 - https://github.com/lss233/chatgpt-mirai-qq-bot/issues/85
chatgpt-qq-chatgpt-1     | Exception ignored in atexit callback: <function foo at 0x7f4bf68d42c0>
chatgpt-qq-chatgpt-1     | Traceback (most recent call last):
chatgpt-qq-chatgpt-1     |   File "/app/utils/exithooks.py", line 40, in foo
chatgpt-qq-chatgpt-1     |     raise hooks.exception
chatgpt-qq-chatgpt-1     |   File "/app/bot.py", line 23, in <module>
chatgpt-qq-chatgpt-1     |     from platforms.onebot_bot import start_task
chatgpt-qq-chatgpt-1     |   File "/app/platforms/onebot_bot.py", line 16, in <module>
chatgpt-qq-chatgpt-1     |     from middlewares.ratelimit import manager as ratelimit_manager
chatgpt-qq-chatgpt-1     |   File "/app/middlewares/ratelimit.py", line 5, in <module>
chatgpt-qq-chatgpt-1     |     from conversation import ConversationContext
chatgpt-qq-chatgpt-1     |   File "/app/conversation.py", line 18, in <module>
chatgpt-qq-chatgpt-1     |     from adapter.ms.bing import BingAdapter
chatgpt-qq-chatgpt-1     |   File "/app/adapter/ms/bing.py", line 11, in <module>
chatgpt-qq-chatgpt-1     |     from drawing import DrawingAPI
chatgpt-qq-chatgpt-1     |   File "/app/drawing/__init__.py", line 2, in <module>
chatgpt-qq-chatgpt-1     |     from .sdwebui import SDWebUI
chatgpt-qq-chatgpt-1     |   File "/app/drawing/sdwebui.py", line 22, in <module>
chatgpt-qq-chatgpt-1     |     class SDWebUI(DrawingAPI):
chatgpt-qq-chatgpt-1     |   File "/app/drawing/sdwebui.py", line 26, in SDWebUI
chatgpt-qq-chatgpt-1     |     "Authorization": f"{init_authorization()}"
chatgpt-qq-chatgpt-1     |                         ^^^^^^^^^^^^^^^^^^^^
chatgpt-qq-chatgpt-1     |   File "/app/drawing/sdwebui.py", line 17, in init_authorization
chatgpt-qq-chatgpt-1     |     if config.sdwebui.authorization != '':
chatgpt-qq-chatgpt-1     |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chatgpt-qq-chatgpt-1     | AttributeError: 'NoneType' object has no attribute 'authorization'
chatgpt-qq-mirai-1       |   09:17:47 [INFO] Mirai Console Loader Announcement:
chatgpt-qq-mirai-1       | Mirai Console Loader 公告栏
chatgpt-qq-mirai-1       | 
chatgpt-qq-mirai-1       | 如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
chatgpt-qq-mirai-1       | `- 如 Unsupported image type for ExternalResource *
chatgpt-qq-mirai-1       | `  considering use gif/png/bmp/jpg format.
chatgpt-qq-mirai-1       | `- Tracker: https://github.com/mamoe/mirai/issues/new/choose
chatgpt-qq-mirai-1       | 
chatgpt-qq-mirai-1       | 常用资源整合
chatgpt-qq-mirai-1       | `- https://mirai.mamoe.net/topic/653
chatgpt-qq-mirai-1       |  
chatgpt-qq-mirai-1       | MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。
chatgpt-qq-mirai-1       | 
chatgpt-qq-mirai-1       |   09:17:47 [INFO] Verifying "net.mamoe:mirai-console" v2.15.0-M1
chatgpt-qq-mirai-1       |   09:17:56 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.15.0-M1
chatgpt-qq-chatgpt-1 exited with code 0
chatgpt-qq-mirai-1       |   09:17:58 [INFO] Verifying "net.mamoe:mirai-core-all" v2.15.0-M1
chatgpt-qq-chatgpt-1     | (EE) 
chatgpt-qq-chatgpt-1     | Fatal server error:
chatgpt-qq-chatgpt-1     | (EE) Server is already active for display 0
chatgpt-qq-chatgpt-1     |      If this server is no longer running, remove /tmp/.X0-lock
chatgpt-qq-chatgpt-1     |      and start again.
chatgpt-qq-chatgpt-1     | (EE) 
chatgpt-qq-mirai-1       |   09:18:01 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
chatgpt-qq-mirai-1       |   09:18:02 [INFO] Verifying "net.mamoe:mirai-api-http" v2.9.1
chatgpt-qq-mirai-1       |   09:18:02 [INFO] Verifying "xyz.cssxsh.mirai:mirai-device-generator" v1.1.3

**Comment by lss233** [comment]
参考 #682

**Comment by dylanm199009** [comment]
完美解决
