### ISSUE TITLE
[BUG] 所有登录方法均已失效

### ISSUE THREAD

**Issue by jzhlym** [lss233/chatgpt-mirai-qq-bot#687]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√ ] 我已看过其他 issue，他们不能解决我的问题 
- [ √] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况
![image](https://user-images.githubusercontent.com/127743101/233775835-c18f5ca6-041c-48e1-a373-1310dc277f3a.png)

**运行环境:**  
- 操作系统：Windows 11
**复现步骤**  
描述你是如何触发这个 BUG 的
打开就会出现
**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
按照提示信息检查即可。

**Comment by lss233** [comment]
另外，你的endpoint有问题。建议升级到最新版，然后删除 browserless_endpoint 配置项。

**Comment by jzhlym** [comment]
有个问题，我可以同时部署chatgpt和bing吗

**Comment by jzhlym** [comment]
@lss233

**Comment by lss233** [comment]
可以，教程说了。
