### ISSUE TITLE
[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:992)

### ISSUE THREAD

**Issue by 1002800982** [lss233/chatgpt-mirai-qq-bot#690]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
qq登录成功后无论发送什么消息都是这个错误

**运行环境:**  
- 操作系统：？
- Docker： ？
- 项目版本：？
- 

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
![image](https://user-images.githubusercontent.com/112914450/233832399-464dbd56-31d0-4888-933e-ffc0d50e3107.png)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
网络问题，建议部署在国外服务器。

**Comment by CarillonQA** [comment]
> 网络问题，建议部署在国外服务器。
私聊能跑通 群聊报上面这个错是网络问题吗

**Comment by lss233** [comment]
> > 私聊能跑通 群聊报上面这个错是网络问题吗

是，建议使用国外服务器。
