### ISSUE TITLE
[BUG] 使用 Poe 时，多人同时使用一个 AI 会串回答

### ISSUE THREAD

**Issue by seagullz4** [lss233/chatgpt-mirai-qq-bot#692]
意思就是这样，甲同学发了一个信息给机器人，乙同学刚好又发了一条信息给ai，结果ai把准备要回复给甲同学的信息发给了乙同学，导致把回答的对象搞错了，这种概率90%以上常有，希望加一个针对性的回答功能，防止搞错回答对象

**Comment by lss233** [comment]
我这里没有遇到过这种情况，
你用的是 Poe 吗？

**Comment by seagullz4** [comment]
对，poe模型，总是串回答

**Comment by lss233** [comment]
这个预期行为。因为目前的 Poe 只支持单个会话，所以如果有多个人发消息的时候就容易搞不清楚谁是谁了。    

目前还在想有没有什么更好方法解决这个问题。

**Comment by seagullz4** [comment]
谢谢[]()

**Comment by lss233** [comment]
v3中会通过创建自定义bot的方式支持上下文隔离。
