### ISSUE TITLE
[BUG] 给文心一言发消息报错：Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by linxp001** [lss233/chatgpt-mirai-qq-bot#693]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
今天发现和文心一言对话时报错，昨天还能用的。

**运行环境:**  
- 操作系统：CentOS Linux release 7.9.2009 (Core)
- Docker：Docker version 23.0.2, build 569dd73
- 项目版本：v2.4.2

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 切换AI到文心一言
2. 发送“你好”
3. 得到回复“出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。
Expecting value: line 1 column 1 (char 0)”

**预期行为**  
得到文心一言的正常答复

**截图**  
相关日志、聊天记录的截图，没有可跳过
![image](https://user-images.githubusercontent.com/75927451/233850559-c865cbc1-22d5-46d4-81cb-8be81837242c.png)
![image](https://user-images.githubusercontent.com/75927451/233850699-e1cf2cb6-bd67-4228-afbf-071ecb78455a.png)
![image](https://user-images.githubusercontent.com/75927451/233850728-7ad7e74c-9530-4dab-84a4-5e1529d6771d.png)
![image](https://user-images.githubusercontent.com/75927451/233850753-b3a69a17-0215-4c4c-953a-b095709ffa00.png)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by xixixi2000** [comment]
I got this error "用户访问被限制", code 40005, I can see my question on the webpage, but no answer, and the webpage runs ok

  File "/home/chatgpt-mirai-qq-bot/adapter/baidu/yiyan.py", line 126, in ask
    self.__check_response(req.json())
    │                     │   └ <function Response.json at 0x7f784fbaa3a0>
    │                     └ <Response [200 OK]>
    └ <adapter.baidu.yiyan.YiyanAdapter object at 0x7f784d715eb0>

  File "/home/chatgpt-mirai-qq-bot/adapter/baidu/yiyan.py", line 182, in __check_response
    raise Exception(resp['msg'])
                    └ {'code': 40005, 'msg': '用户访问被限制', 'data': None, 'logId': '001000000873287653'}

**Comment by linxp001** [comment]
pull了最新的内容，现在可以了。

**Comment by xixixi2000** [comment]
File "/root/chatgpt-mirai-qq-bot/utils/text_to_img.py", line 361, in to_image
    img = await text_to_image(text=str(text))
                │                      └ '出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。\nExpecting value: line 1 column 1 (char 0)'
                └ <function text_to_image at 0x7f7a24762a60>

**Comment by xixixi2000** [comment]
I got this error today after pulling the newest code

**Comment by feitang0** [comment]
> 

same problem

**Comment by pipinstalljoey** [comment]
the same

**Comment by devin-cat** [comment]
File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
          │                                  └ '<!DOCTYPE html>\n\n<!--[if IE 7]>    <html class="...
          └ <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ivotai** [comment]
the same
