### ISSUE TITLE
('Response is not in the correct format', 'Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com.')

### ISSUE THREAD

**Issue by Hikariion** [lss233/chatgpt-mirai-qq-bot#7]
部署后给机器人发消息一直显示下面的文字。

--------------------------------------------

寄了！
('Response is not in the correct format', 'Incorrect API key provided: Bearer. You can find your API key at https://beta.openai.com.')

**Comment by lss233** [comment]
登录失败，可能是遇到验证码了。与 [#/ChatGPT/72](https://github.com/acheong08/ChatGPT/issues/72) 有关

可以试试参考 [这里](https://github.com/acheong08/ChatGPT/wiki/Setup) 的教程配置 `api_key` 和 `session_token` 来登录。
![image](https://user-images.githubusercontent.com/8984680/206195760-6a27ea64-5c82-49cb-9f2c-f76b654789e8.png)

**Comment by Hikariion** [comment]
是这样的 解决了
