### ISSUE TITLE
回复时间久，添加输入中状态

### ISSUE THREAD

**Issue by fangyuan99** [lss233/chatgpt-mirai-qq-bot#70]
如题，有时候一个问题要回答很久，如果能显示输入中就表示机器人正常运行，不用去查日志

**Comment by lss233** [comment]
Mirai 似乎不支持设置 `输入中` 状态，目前应对这个问题的方式是：如果响应比较久的话，机器人会先回复一句”我还在思考中“，你可以在配置文件里看到有关设置。
