### ISSUE TITLE
[Feature] app.slack中的Claude应用支持

### ISSUE THREAD

**Issue by IloveTTLHz2023** [lss233/chatgpt-mirai-qq-bot#700]
原生claude无需翻墙，聊天体验接近gpt4，且免费，是言而有物的话唠，回复快回答长质量高，聊天体验明显强于懂不懂就报错的免费chatgpt乃至Plus版chatgpt
https://www.anthropic.com/claude-in-slack
申请网址
![image](https://user-images.githubusercontent.com/126993991/234181471-f4066da2-151c-4554-9d2a-f83bd6fdbaea.png)
![image](https://user-images.githubusercontent.com/126993991/234181547-90dfa457-71e7-47dd-95d2-0f419542efcb.png)

**Comment by lss233** [comment]
已经在进行中了，这两天内会支持。

**Comment by lss233** [comment]
v2.5.0 已支持。

**Comment by IloveTTLHz2023** [comment]
> v2.5.0 已支持。

感谢支持，项目很棒！
