### ISSUE TITLE
[BUG] 文心一言：Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by xixixi2000** [lss233/chatgpt-mirai-qq-bot#702]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：Centos 7
- Docker： None
- 项目版本：Newest

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

  File "/root/chatgpt-mirai-qq-bot/adapter/baidu/yiyan.py", line 93, in ask
    self.client.headers['Acs-Token'] = await self.get_sign()
    │    │      │                            │    └ <function YiyanAdapter.get_sign at 0x7efdb79753a0>
    │    │      │                            └ <adapter.baidu.yiyan.YiyanAdapter object at 0x7efdb637aeb0>
    │    │      └ <property object at 0x7efdb8654220>
    │    └ <httpx.AsyncClient object at 0x7efdb637afa0>
    └ <adapter.baidu.yiyan.YiyanAdapter object at 0x7efdb637aeb0>

  File "/root/chatgpt-mirai-qq-bot/adapter/baidu/yiyan.py", line 188, in get_sign
    return req.json()['acs']
           │   └ <function Response.json at 0x7efdb880f3a0>
           └ <Response [502 Bad Gateway]>

  File "/usr/local/python3/lib/python3.9/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
           │       │     │    │       └ {}
           │       │     │    └ <property object at 0x7efdb8809b80>
           │       │     └ <Response [502 Bad Gateway]>
           │       └ <function loads at 0x7efdba04cd30>
           └ <module 'json' from '/usr/local/python3/lib/python3.9/json/__init__.py'>
  File "/usr/local/python3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ '<!DOCTYPE html>\n\n\n\n\n<!--[if IE 7]>    <html class="...
          └ <class 'json.decoder.JSONDecodeError'>

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
which: no wkhtmltoimage in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/root/chatgpt-mirai-qq-bot)
2023-04-25 22:47:07.848 | ERROR    | utils.text_to_img:text_to_image:347 -

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
文心一言的token现在经常改变，我写了个自动更新的程序。之后遇到这个问题过会儿重试应该就可以了。

**Comment by xixixi2000** [comment]
> 文心一言的token现在经常改变，我写了个自动更新的程序。之后遇到这个问题过会儿重试应该就可以了。

ok, 可以主动触发更新么？比如502之后

**Comment by SkilledExtractor** [comment]
在2.5.3遇到同样问题，且这个BDUSS不会自动刷新，望解决

**Comment by caiweilv** [comment]
> 文心一言的token现在经常改变，我写了个自动更新的程序。之后遇到这个问题过会儿重试应该就可以了。

2.5.3还是同样的错
