### ISSUE TITLE
[BUG] 给bing发送某些消息时，提示 “Bing 已结束本次会话。继续发送消息将重新开启一个新会话”

### ISSUE THREAD

**Issue by CalvinRen** [lss233/chatgpt-mirai-qq-bot#706]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
1. 发送部分消息时会回复Bing 已结束本次会话。继续发送消息将重新开启一个新会话；
2. 发送如"你好"，"写诗"等消息时可以正常回复, "今天天气如何"等消息时会触发此bug；
3. 测试中英文都会出现此问题（"Hi"正常回复， "How is weather today"触发bug）

**运行环境:**  
- 操作系统：Ubuntu22.10
- Docker：23.0.2
- 项目版本：Latest

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 给new bing 发送消息
2. 返回“Bing 已结束本次会话。继续发送消息将重新开启一个新会话。”

**预期行为**  
正常回复

**截图**  
<img width="894" alt="image" src="https://user-images.githubusercontent.com/85126498/234341774-89125900-6ead-4eca-ba40-7eb1be9ab1f0.png">
<img width="899" alt="image" src="https://user-images.githubusercontent.com/85126498/234341854-baf80f46-b2f5-4306-bd8d-3ab236b38dde.png">
![IMG_5759](https://user-images.githubusercontent.com/85126498/234342180-f698c7fe-6696-42c2-9b9d-d41805a5dcf0.jpg)

**其他内容**  
1. 已`docker-compose pull && docker-compose up -d`更新最新版
2. 已更新cookie
3. 尝试过`docker-compose restart`

**Comment by huhao0208** [comment]
同样问题+1
