### ISSUE TITLE
希望作者接入一下狐猴浏览器的人工智能

### ISSUE THREAD

**Issue by seagullz4** [lss233/chatgpt-mirai-qq-bot#707]
主要是狐猴浏览器的人工智能免费，速度非常快，感觉和chatgpt3模型差不多![Screenshot_20230426_153650_com.lemurbrowser.exts.jpg](https://user-images.githubusercontent.com/96653729/234518974-69a423c0-6a15-4731-a1a2-244f5d96a0d2.jpg)

总体体验很棒，又不需要账号

**Comment by lss233** [comment]
这应该就是个 ChatGPT 套壳吧？

**Comment by seagullz4** [comment]
对的，但是很好用

**Comment by devinglaw** [comment]
一个套壳的东西没必要用啊，本项目应该是直接对接官方OPENAI
