### ISSUE TITLE
[BUG]  [Edge TTS] 读取失败！

### ISSUE THREAD

**Issue by huangzhitian** [lss233/chatgpt-mirai-qq-bot#712]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：linux
- Docker： ？
- 项目版本：最新

**复现步骤**  
描述你是如何触发这个 BUG 的
1. Go to '..更新之后.'

**预期行为**  

**截图**  
![QQ截图20230427124242](https://user-images.githubusercontent.com/129321746/234770814-91b6e06b-b375-4e54-bbc4-49ad63ba066b.png)
![QQ截图20230427124220](https://user-images.githubusercontent.com/129321746/234770833-86f0436c-ed93-4b8e-9e4a-3aab574d5265.png)

相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
这应该是你网络的问题导致的。  你执行 `ping speech.platform.bing.com` 看看？

**Comment by huangzhitian** [comment]
> 这应该是你网络的问题导致的。 你执行 看看？`ping speech.platform.bing.com`

可以ping的，刚刚再
部署还是一样的问题

**Comment by huangzhitian** [comment]
> 这应该是你网络的问题导致的。 你执行 看看？`ping speech.platform.bing.com`

![QQ截图20230427213932](https://user-images.githubusercontent.com/129321746/234879895-35b5da53-b727-4a6b-9765-38be40427403.png)

**Comment by huangzhitian** [comment]
> > 这应该是你网络的问题导致的。 你执行 看看？`ping speech.platform.bing.com`
> 
> ![QQ截图20230427213932](https://user-images.githubusercontent.com/129321746/234879895-35b5da53-b727-4a6b-9765-38be40427403.png)

试了密码登录，扫码登录都不行

**Comment by lss233** [comment]
看来是你服务器的网络有问题……
