### ISSUE TITLE
[BUG] 丢弃群聊消息，不符合聊天前缀（无论设置还是并设置均无法读取群消息，私聊正常）

### ISSUE THREAD

**Issue by Smartyaostudent** [lss233/chatgpt-mirai-qq-bot#715]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:Windows
- 操作系统：Windows 2022 serve
- Docker： ？
- 项目版本：2.4.2

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
应该可以正常读取群聊信息，并回复，但是并没有，总是先显示自动丢弃群聊信息，并没有后续操作，我在源文件中并没有设置有关聊天浅醉，采用的是one bot登录QQ，但发现无论怎么回复机器人，总是无法读取群聊信息。

**截图**  
![image](https://user-images.githubusercontent.com/85338367/235055839-b045cc57-0ab5-49c6-9c5a-9a4b5bf6570c.png)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
发下配置文件看看

**Comment by lss233** [comment]
发下配置文件看看

**Comment by Smartyaostudent** [comment]
> 发下配置文件看看

抱歉这个问题，我解决了，大概是因为我把这三个文件放在一个文件夹导致错误，我重新部署了一遍，将这个onebot文件单独翻出来，就正常了
原结果：![image](https://user-images.githubusercontent.com/85338367/235281713-cbb1b6ca-f104-4b93-80c5-f7f119ee266f.png)
解决问题后的文件位置：
![image](https://user-images.githubusercontent.com/85338367/235281730-7370fd7b-1eb8-4093-8458-3e42cd629f67.png)
