### ISSUE TITLE
接入 Claude 后对话回复 当前没有可用的chatgpt-web账号，不支持使用此 AI！

### ISSUE THREAD

**Issue by ivotai** [lss233/chatgpt-mirai-qq-bot#721]
接入 Claude 后对话回复 当前没有可用的chatgpt-web账号，不支持使用此 AI！

**Comment by lss233** [comment]
你可能设置了 chatgpt-web 为默认的 AI， 把配置文件里面的 default_ai 改成 slack-claude 就行

**Comment by ivotai** [comment]
好的 谢谢大大
