### ISSUE TITLE
[BUG] 企业微信报错 replace函数参数类型

### ISSUE THREAD

**Issue by Pretend-to** [lss233/chatgpt-mirai-qq-bot#728]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
使用企业微信自定义应用对接成功了，说话就报错，企业微信端可以收到这个报错消息

**截图**  
chatgpt_1  | 2023-04-29 14:49:50.785 | DEBUG    | platforms.wecom_bot:wechat:123 - TextMessage({'ToUserName': 'wwcbccdf4a8f1050ab', 'FromUserName': 'WangHanXi', 'CreateTime': '1682779790', 'MsgType': 'text', 'Content': '你好', 'MsgId': '7227484165719354917', 'AgentID': '1000002'})
chatgpt_1  | 2023-04-29 14:49:52.712 | INFO     | platforms.wecom_bot:construct_bot_request:196 - Get message from wecom-WangHanXi[WangHanXi]:
chatgpt_1  | 你好
chatgpt_1  | 2023-04-29 14:49:52.713 | DEBUG    | platforms.wecom_bot:process_request:223 - Start to process bot request 1682779792712.
chatgpt_1  | 2023-04-29 14:49:53.335 | DEBUG    | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！
chatgpt_1  | 2023-04-29 14:49:53.336 | DEBUG    | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！
chatgpt_1  | INFO:quart.serving:183.47.98.227:52260 POST /wechat 1.1 200 2 2651769
chatgpt_1  | [2023-04-29 14:49:53,339] 183.47.98.227:52260 POST /wechat 1.1 200 2 2651769
chatgpt_1  | 2023-04-29 14:49:53.341 | DEBUG    | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时……
chatgpt_1  | 2023-04-29 14:49:53.344 | ERROR    | universal:handle_message:295 - replace() argument 2 must be str, not dict
chatgpt_1  | Traceback (most recent call last):
chatgpt_1  | 
chatgpt_1  |   File "/app/bot.py", line 54, in <module>
chatgpt_1  |     loop.run_until_complete(asyncio.gather(*bots))
chatgpt_1  |     │    │                  │       │       └ [<Task pending name='Task-4' coro=<start_task() running at /app/platforms/wecom_bot.py:246> wait_for=<_GatheringFuture pendin...
chatgpt_1  |     │    │                  │       └ <function gather at 0x7f351f7545e0>
chatgpt_1  |     │    │                  └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>
chatgpt_1  |     │    └ <function BaseEventLoop.run_until_complete at 0x7f351f7653a0>
chatgpt_1  |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt_1  | 
chatgpt_1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
chatgpt_1  |     self.run_forever()
chatgpt_1  |     │    └ <function BaseEventLoop.run_forever at 0x7f351f765300>
chatgpt_1  |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt_1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
chatgpt_1  |     self._run_once()
chatgpt_1  |     │    └ <function BaseEventLoop._run_once at 0x7f351f767100>
chatgpt_1  |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt_1  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
chatgpt_1  |     handle._run()
chatgpt_1  |     │      └ <function Handle._run at 0x7f351fcc0040>
chatgpt_1  |     └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt_1  |   File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
chatgpt_1  |     self._context.run(self._callback, *self._args)
chatgpt_1  |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
chatgpt_1  |     │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt_1  |     │    │            │    └ <member '_callback' of 'Handle' objects>
chatgpt_1  |     │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt_1  |     │    └ <member '_context' of 'Handle' objects>
chatgpt_1  |     └ <Handle Task.task_wakeup(<Future finished result=None>)>
chatgpt_1  | 
chatgpt_1  |   File "/app/platforms/wecom_bot.py", line 228, in process_request
chatgpt_1  |     await handle_message(
chatgpt_1  |           └ <function handle_message at 0x7f3518d60fe0>
chatgpt_1  | 
chatgpt_1  | > File "/app/universal.py", line 269, in handle_message
chatgpt_1  |     await action(session_id, message.strip(), conversation_context, respond)
chatgpt_1  |           │      │           │       │        │                     └ <function handle_message.<locals>.respond at 0x7f34fb4faca0>
chatgpt_1  |           │      │           │       │        └ None
chatgpt_1  |           │      │           │       └ <method 'strip' of 'str' objects>
chatgpt_1  |           │      │           └ '你好'
chatgpt_1  |           │      └ 'wecom-WangHanXi'
chatgpt_1  |           └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7f34fb4fbe20>
chatgpt_1  | 
chatgpt_1  |   File "/app/universal.py", line 53, in call
chatgpt_1  |     await m.handle_request(session_id, message, respond, conversation_context, n)
chatgpt_1  |           │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7f34fb4fbd80>
chatgpt_1  |           │ │              │           │        │        └ None
chatgpt_1  |           │ │              │           │        └ <function handle_message.<locals>.respond at 0x7f34fb4faca0>
chatgpt_1  |           │ │              │           └ '你好'
chatgpt_1  |           │ │              └ 'wecom-WangHanXi'
chatgpt_1  |           │ └ <function MiddlewareConcurrentLock.handle_request at 0x7f3518cae200>
chatgpt_1  |           └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x7f351aa7c390>
chatgpt_1  | 
chatgpt_1  |   File "/app/middlewares/concurrentlock.py", line 43, in handle_request
chatgpt_1  |     await action(session_id, prompt, conversation_context, respond)
chatgpt_1  |           │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7f34fb4faca0>
chatgpt_1  |           │      │           │       └ None
chatgpt_1  |           │      │           └ '你好'
chatgpt_1  |           │      └ 'wecom-WangHanXi'
chatgpt_1  |           └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7f34fb4fbd80>
chatgpt_1  | 
chatgpt_1  |   File "/app/universal.py", line 53, in call
chatgpt_1  |     await m.handle_request(session_id, message, respond, conversation_context, n)
chatgpt_1  |           │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7f34fb4fbce0>
chatgpt_1  |           │ │              │           │        │        └ None
chatgpt_1  |           │ │              │           │        └ <function handle_message.<locals>.respond at 0x7f34fb4faca0>
chatgpt_1  |           │ │              │           └ '你好'
chatgpt_1  |           │ │              └ 'wecom-WangHanXi'
chatgpt_1  |           │ └ <function Middleware.handle_request at 0x7f3518cad6c0>
chatgpt_1  |           └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x7f351aa5bf90>
chatgpt_1  | 
chatgpt_1  |   File "/app/middlewares/middleware.py", line 9, in handle_request
chatgpt_1  |     await action(session_id, prompt, conversation_context, respond)
chatgpt_1  |           │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7f34fb4faca0>
chatgpt_1  |           │      │           │       └ None
chatgpt_1  |           │      │           └ '你好'
chatgpt_1  |           │      └ 'wecom-WangHanXi'
chatgpt_1  |           └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7f34fb4fbce0>
chatgpt_1  | 
chatgpt_1  |   File "/app/universal.py", line 53, in call
chatgpt_1  |     await m.handle_request(session_id, message, respond, conversation_context, n)
chatgpt_1  |           │ │              │           │        │        │                     └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7f34fb4fbc40>
chatgpt_1  |           │ │              │           │        │        └ None
chatgpt_1  |           │ │              │           │        └ <function handle_message.<locals>.respond at 0x7f34fb4faca0>
chatgpt_1  |           │ │              │           └ '你好'
chatgpt_1  |           │ │              └ 'wecom-WangHanXi'
chatgpt_1  |           │ └ <function MiddlewareRatelimit.handle_request at 0x7f3518cae3e0>
chatgpt_1  |           └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x7f351aa5bc50>
chatgpt_1  | 
chatgpt_1  |   File "/app/middlewares/ratelimit.py", line 23, in handle_request
chatgpt_1  |     await action(session_id, prompt, conversation_context, respond)
chatgpt_1  |           │      │           │       │                     └ <function handle_message.<locals>.respond at 0x7f34fb4faca0>
chatgpt_1  |           │      │           │       └ None
chatgpt_1  |           │      │           └ '你好'
chatgpt_1  |           │      └ 'wecom-WangHanXi'
chatgpt_1  |           └ <function handle_message.<locals>.wrap_request.<locals>.call at 0x7f34fb4fbc40>
chatgpt_1  | 
chatgpt_1  |   File "/app/universal.py", line 53, in call
chatgpt_1  |     await m.handle_request(session_id, message, respond, conversation_context, n)
chatgpt_1  |           │ │              │           │        │        │                     └ <function handle_message.<locals>.request at 0x7f34fb4fad40>
chatgpt_1  |           │ │              │           │        │        └ None
chatgpt_1  |           │ │              │           │        └ <function handle_message.<locals>.respond at 0x7f34fb4faca0>
chatgpt_1  |           │ │              │           └ '你好'
chatgpt_1  |           │ │              └ 'wecom-WangHanXi'
chatgpt_1  |           │ └ <function MiddlewareTimeout.handle_request at 0x7f3518cae5c0>
chatgpt_1  |           └ <middlewares.timeout.MiddlewareTimeout object at 0x7f351aa5bf10>
chatgpt_1  | 
chatgpt_1  |   File "/app/middlewares/timeout.py", line 27, in handle_request
chatgpt_1  |     await asyncio.wait_for(coro_task, config.response.max_timeout)
chatgpt_1  |           │       │        │          │      │        └ 600.0
chatgpt_1  |           │       │        │          │      └ Response(mode='mixed', buffer_delay=0.0, default_ai='chatgpt-api', error_format='出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回...
chatgpt_1  |           │       │        │          └ <unprintable Config object>
chatgpt_1  |           │       │        └ <Task finished name='Task-23' coro=<handle_message.<locals>.request() done, defined at /app/universal.py:107> exception=TypeE...
chatgpt_1  |           │       └ <function wait_for at 0x7f351f754040>
chatgpt_1  |           └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>
chatgpt_1  | 
chatgpt_1  |   File "/usr/local/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
chatgpt_1  |     return fut.result()
chatgpt_1  |            │   └ <method 'result' of '_asyncio.Task' objects>
chatgpt_1  |            └ <Task finished name='Task-23' coro=<handle_message.<locals>.request() done, defined at /app/universal.py:107> exception=TypeE...
chatgpt_1  | 
chatgpt_1  |   File "/app/universal.py", line 222, in request
chatgpt_1  |     async for rendered in task:
chatgpt_1  |                           └ <async_generator object retry.<locals>.decorator.<locals>.wrapper at 0x7f3518c63cd0>
chatgpt_1  | 
chatgpt_1  |   File "/app/utils/retry.py", line 21, in wrapper
chatgpt_1  |     async for result in func(*args, **kwargs):
chatgpt_1  |                         │     │       └ {'prompt': '你好', 'chain': MessageChain([Plain(text='Unsupported')]), 'name': {'errcode': 0, 'errmsg': 'ok', 'userid': 'WangHa...
chatgpt_1  |                         │     └ (<conversation.ConversationContext object at 0x7f34fb4fc350>,)
chatgpt_1  |                         └ <function ConversationContext.ask at 0x7f3518cacea0>
chatgpt_1  | 
chatgpt_1  |   File "/app/conversation.py", line 181, in ask
chatgpt_1  |     .replace("{nickname}", name)
chatgpt_1  |                            └ {'errcode': 0, 'errmsg': 'ok', 'userid': 'WangHanXi', 'name': 'Paul', 'department': [1], 'position': '', 'status': 1, 'islead...
chatgpt_1  | 
chatgpt_1  | TypeError: replace() argument 2 must be str, not dict
chatgpt_1  | 2023-04-29 14:49:53.371 | INFO     | platforms.wecom_bot:response:205 - Got response msg -> <class 'str'> -> 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。
chatgpt_1  | replace() argument 2 must be str, not dict
chatgpt_1  | 2023-04-29 14:49:53.381 | DEBUG    | platforms.wecom_bot:process_request:237 - Bot request 1682779792712 done.

**Comment by Pretend-to** [comment]
在conversation.py手动添加
async def ask(self, prompt: str, chain: MessageChain = None, name: Any = None):
    if name is not None and not isinstance(name, str):  #新加的
        name = str(name)  #新加的
解决。

**Comment by beichen123-hub** [comment]
> **提交 issue 前，请先确认：**
> 
> * [x]  我已看过 **FAQ**，此问题不在列表中
> * [ ]  我已看过其他 issue，他们不能解决我的问题
> * [ ]  我认为这不是 Mirai 或者 OpenAI 的 BUG
> 
> **表现** 使用企业微信自定义应用对接成功了，说话就报错，企业微信端可以收到这个报错消息
> 
> **截图** chatgpt_1 | 2023-04-29 14:49:50.785 | DEBUG | platforms.wecom_bot:wechat:123 - TextMessage({'ToUserName': 'wwcbccdf4a8f1050ab', 'FromUserName': 'WangHanXi', 'CreateTime': '1682779790', 'MsgType': 'text', 'Content': '你好', 'MsgId': '7227484165719354917', 'AgentID': '1000002'}) chatgpt_1 | 2023-04-29 14:49:52.712 | INFO | platforms.wecom_bot:construct_bot_request:196 - Get message from wecom-WangHanXi[WangHanXi]: chatgpt_1 | 你好 chatgpt_1 | 2023-04-29 14:49:52.713 | DEBUG | platforms.wecom_bot:process_request:223 - Start to process bot request 1682779792712. chatgpt_1 | 2023-04-29 14:49:53.335 | DEBUG | middlewares.concurrentlock:handle_request:40 - [Concurrent] 排队中，前面还有 0 个人！ chatgpt_1 | 2023-04-29 14:49:53.336 | DEBUG | middlewares.concurrentlock:handle_request:42 - [Concurrent] 排到了！ chatgpt_1 | INFO:quart.serving:183.47.98.227:52260 POST /wechat 1.1 200 2 2651769 chatgpt_1 | [2023-04-29 14:49:53,339] 183.47.98.227:52260 POST /wechat 1.1 200 2 2651769 chatgpt_1 | 2023-04-29 14:49:53.341 | DEBUG | middlewares.timeout:create_timeout_task:55 - [Timeout] 开始计时…… chatgpt_1 | 2023-04-29 14:49:53.344 | ERROR | universal:handle_message:295 - replace() argument 2 must be str, not dict chatgpt_1 | Traceback (most recent call last): chatgpt_1 | chatgpt_1 | File "/app/bot.py", line 54, in chatgpt_1 | loop.run_until_complete(asyncio.gather(*bots)) chatgpt_1 | │ │ │ │ └ [<Task pending name='Task-4' coro=<start_task() running at /app/platforms/wecom_bot.py:246> wait_for=<_GatheringFuture pendin... chatgpt_1 | │ │ │ └ <function gather at 0x7f351f7545e0> chatgpt_1 | │ │ └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/**init**.py'> chatgpt_1 | │ └ <function BaseEventLoop.run_until_complete at 0x7f351f7653a0> chatgpt_1 | └ <_UnixSelectorEventLoop running=True closed=False debug=False> chatgpt_1 | chatgpt_1 | File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete chatgpt_1 | self.run_forever() chatgpt_1 | │ └ <function BaseEventLoop.run_forever at 0x7f351f765300> chatgpt_1 | └ <_UnixSelectorEventLoop running=True closed=False debug=False> chatgpt_1 | File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever chatgpt_1 | self._run_once() chatgpt_1 | │ └ <function BaseEventLoop._run_once at 0x7f351f767100> chatgpt_1 | └ <_UnixSelectorEventLoop running=True closed=False debug=False> chatgpt_1 | File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once chatgpt_1 | handle._run() chatgpt_1 | │ └ <function Handle._run at 0x7f351fcc0040> chatgpt_1 | └ <Handle Task.task_wakeup()> chatgpt_1 | File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run chatgpt_1 | self._context.run(self._callback, *self._args) chatgpt_1 | │ │ │ │ │ └ <member '_args' of 'Handle' objects> chatgpt_1 | │ │ │ │ └ <Handle Task.task_wakeup()> chatgpt_1 | │ │ │ └ <member '_callback' of 'Handle' objects> chatgpt_1 | │ │ └ <Handle Task.task_wakeup()> chatgpt_1 | │ └ <member '_context' of 'Handle' objects> chatgpt_1 | └ <Handle Task.task_wakeup()> chatgpt_1 | chatgpt_1 | File "/app/platforms/wecom_bot.py", line 228, in process_request chatgpt_1 | await handle_message( chatgpt_1 | └ <function handle_message at 0x7f3518d60fe0> chatgpt_1 | chatgpt_1 | > File "/app/universal.py", line 269, in handle_message chatgpt_1 | await action(session_id, message.strip(), conversation_context, respond) chatgpt_1 | │ │ │ │ │ └ <function handle_message..respond at 0x7f34fb4faca0> chatgpt_1 | │ │ │ │ └ None chatgpt_1 | │ │ │ └ <method 'strip' of 'str' objects> chatgpt_1 | │ │ └ '你好' chatgpt_1 | │ └ 'wecom-WangHanXi' chatgpt_1 | └ <function handle_message..wrap_request..call at 0x7f34fb4fbe20> chatgpt_1 | chatgpt_1 | File "/app/universal.py", line 53, in call chatgpt_1 | await m.handle_request(session_id, message, respond, conversation_context, n) chatgpt_1 | │ │ │ │ │ │ └ <function handle_message..wrap_request..call at 0x7f34fb4fbd80> chatgpt_1 | │ │ │ │ │ └ None chatgpt_1 | │ │ │ │ └ <function handle_message..respond at 0x7f34fb4faca0> chatgpt_1 | │ │ │ └ '你好' chatgpt_1 | │ │ └ 'wecom-WangHanXi' chatgpt_1 | │ └ <function MiddlewareConcurrentLock.handle_request at 0x7f3518cae200> chatgpt_1 | └ <middlewares.concurrentlock.MiddlewareConcurrentLock object at 0x7f351aa7c390> chatgpt_1 | chatgpt_1 | File "/app/middlewares/concurrentlock.py", line 43, in handle_request chatgpt_1 | await action(session_id, prompt, conversation_context, respond) chatgpt_1 | │ │ │ │ └ <function handle_message..respond at 0x7f34fb4faca0> chatgpt_1 | │ │ │ └ None chatgpt_1 | │ │ └ '你好' chatgpt_1 | │ └ 'wecom-WangHanXi' chatgpt_1 | └ <function handle_message..wrap_request..call at 0x7f34fb4fbd80> chatgpt_1 | chatgpt_1 | File "/app/universal.py", line 53, in call chatgpt_1 | await m.handle_request(session_id, message, respond, conversation_context, n) chatgpt_1 | │ │ │ │ │ │ └ <function handle_message..wrap_request..call at 0x7f34fb4fbce0> chatgpt_1 | │ │ │ │ │ └ None chatgpt_1 | │ │ │ │ └ <function handle_message..respond at 0x7f34fb4faca0> chatgpt_1 | │ │ │ └ '你好' chatgpt_1 | │ │ └ 'wecom-WangHanXi' chatgpt_1 | │ └ <function Middleware.handle_request at 0x7f3518cad6c0> chatgpt_1 | └ <middlewares.baiducloud.MiddlewareBaiduCloud object at 0x7f351aa5bf90> chatgpt_1 | chatgpt_1 | File "/app/middlewares/middleware.py", line 9, in handle_request chatgpt_1 | await action(session_id, prompt, conversation_context, respond) chatgpt_1 | │ │ │ │ └ <function handle_message..respond at 0x7f34fb4faca0> chatgpt_1 | │ │ │ └ None chatgpt_1 | │ │ └ '你好' chatgpt_1 | │ └ 'wecom-WangHanXi' chatgpt_1 | └ <function handle_message..wrap_request..call at 0x7f34fb4fbce0> chatgpt_1 | chatgpt_1 | File "/app/universal.py", line 53, in call chatgpt_1 | await m.handle_request(session_id, message, respond, conversation_context, n) chatgpt_1 | │ │ │ │ │ │ └ <function handle_message..wrap_request..call at 0x7f34fb4fbc40> chatgpt_1 | │ │ │ │ │ └ None chatgpt_1 | │ │ │ │ └ <function handle_message..respond at 0x7f34fb4faca0> chatgpt_1 | │ │ │ └ '你好' chatgpt_1 | │ │ └ 'wecom-WangHanXi' chatgpt_1 | │ └ <function MiddlewareRatelimit.handle_request at 0x7f3518cae3e0> chatgpt_1 | └ <middlewares.ratelimit.MiddlewareRatelimit object at 0x7f351aa5bc50> chatgpt_1 | chatgpt_1 | File "/app/middlewares/ratelimit.py", line 23, in handle_request chatgpt_1 | await action(session_id, prompt, conversation_context, respond) chatgpt_1 | │ │ │ │ └ <function handle_message..respond at 0x7f34fb4faca0> chatgpt_1 | │ │ │ └ None chatgpt_1 | │ │ └ '你好' chatgpt_1 | │ └ 'wecom-WangHanXi' chatgpt_1 | └ <function handle_message..wrap_request..call at 0x7f34fb4fbc40> chatgpt_1 | chatgpt_1 | File "/app/universal.py", line 53, in call chatgpt_1 | await m.handle_request(session_id, message, respond, conversation_context, n) chatgpt_1 | │ │ │ │ │ │ └ <function handle_message..request at 0x7f34fb4fad40> chatgpt_1 | │ │ │ │ │ └ None chatgpt_1 | │ │ │ │ └ <function handle_message..respond at 0x7f34fb4faca0> chatgpt_1 | │ │ │ └ '你好' chatgpt_1 | │ │ └ 'wecom-WangHanXi' chatgpt_1 | │ └ <function MiddlewareTimeout.handle_request at 0x7f3518cae5c0> chatgpt_1 | └ <middlewares.timeout.MiddlewareTimeout object at 0x7f351aa5bf10> chatgpt_1 | chatgpt_1 | File "/app/middlewares/timeout.py", line 27, in handle_request chatgpt_1 | await asyncio.wait_for(coro_task, config.response.max_timeout) chatgpt_1 | │ │ │ │ │ └ 600.0 chatgpt_1 | │ │ │ │ └ Response(mode='mixed', buffer_delay=0.0, default_ai='chatgpt-api', error_format='出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回... chatgpt_1 | │ │ │ └ chatgpt_1 | │ │ └ <Task finished name='Task-23' coro=<handle_message..request() done, defined at /app/universal.py:107> exception=TypeE... chatgpt_1 | │ └ <function wait_for at 0x7f351f754040> chatgpt_1 | └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/**init**.py'> chatgpt_1 | chatgpt_1 | File "/usr/local/lib/python3.11/asyncio/tasks.py", line 479, in wait_for chatgpt_1 | return fut.result() chatgpt_1 | │ └ <method 'result' of '_asyncio.Task' objects> chatgpt_1 | └ <Task finished name='Task-23' coro=<handle_message..request() done, defined at /app/universal.py:107> exception=TypeE... chatgpt_1 | chatgpt_1 | File "/app/universal.py", line 222, in request chatgpt_1 | async for rendered in task: chatgpt_1 | └ <async_generator object retry..decorator..wrapper at 0x7f3518c63cd0> chatgpt_1 | chatgpt_1 | File "/app/utils/retry.py", line 21, in wrapper chatgpt_1 | async for result in func(*args, **kwargs): chatgpt_1 | │ │ └ {'prompt': '你好', 'chain': MessageChain([Plain(text='Unsupported')]), 'name': {'errcode': 0, 'errmsg': 'ok', 'userid': 'WangHa... chatgpt_1 | │ └ (<conversation.ConversationContext object at 0x7f34fb4fc350>,) chatgpt_1 | └ <function ConversationContext.ask at 0x7f3518cacea0> chatgpt_1 | chatgpt_1 | File "/app/conversation.py", line 181, in ask chatgpt_1 | .replace("{nickname}", name) chatgpt_1 | └ {'errcode': 0, 'errmsg': 'ok', 'userid': 'WangHanXi', 'name': 'Paul', 'department': [1], 'position': '', 'status': 1, 'islead... chatgpt_1 | chatgpt_1 | TypeError: replace() argument 2 must be str, not dict chatgpt_1 | 2023-04-29 14:49:53.371 | INFO | platforms.wecom_bot:response:205 - Got response msg -> <class 'str'> -> 出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。 chatgpt_1 | replace() argument 2 must be str, not dict chatgpt_1 | 2023-04-29 14:49:53.381 | DEBUG | platforms.wecom_bot:process_request:237 - Bot request 1682779792712 done.

大佬你的企业微信上怎么连接成功的 我在企业微信中链接一直显示openapi回调错误

**Comment by linxp001** [comment]
显示回调错误，应该是因为你的chatgpt-qq服务没有重启，先按照接入说明把config文件改好，然后重启服务再试。
