### ISSUE TITLE
[BUG] claude无法对话

### ISSUE THREAD

**Issue by bobandbrony** [lss233/chatgpt-mirai-qq-bot#731]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
在qq上与claude对话，消息发不过来，但在claude网页版是有消息的

**运行环境:**  
- 操作系统：Windows11 21h2
- Docker： 无
- 项目版本：2.5.0

**复现步骤**  
描述你是如何触发这个 BUG 的
未知

**预期行为**  
正常对话

**截图**  

**其他内容**  
在slack应用中，Claude-Interactor显示是离线

**Comment by linxp001** [comment]
我也遇到了同样的错误，跟claude说完话机器人就卡住了，不再回复消息了。

**Comment by ivotai** [comment]
仔细看说明文档，你需要将 Claude 和 Claude-Interactor 同时拉入频道，可能是这个问题。

**Comment by linxp001** [comment]
> 仔细看说明文档，你需要将 Claude 和 Claude-Interactor 同时拉入频道，可能是这个问题。

![image](https://user-images.githubusercontent.com/75927451/235352969-a5c35dec-d59a-4cf8-82bd-cf197ce1c84f.png)
这种算是同时拉入频道了吗？我感觉算吧

**Comment by linxp001** [comment]
> > 仔细看说明文档，你需要将 Claude 和 Claude-Interactor 同时拉入频道，可能是这个问题。
> 
> ![image](https://user-images.githubusercontent.com/75927451/235352969-a5c35dec-d59a-4cf8-82bd-cf197ce1c84f.png) 这种算是同时拉入频道了吗？我感觉算吧

![image](https://user-images.githubusercontent.com/75927451/235353059-1e6b7882-e6e1-445c-b27d-cc4639c6a27e.png)
问题好像在这里，通过QQ过来的消息是@claude（小写），在网页里对话@出来的效果是Claude，第一个字母大写，感觉QQ过来的消息没有@到Claude

**Comment by bobandbrony** [comment]
已找到解决办法
![image](https://user-images.githubusercontent.com/129247570/235367432-4ea7de58-0618-462e-8608-d4c48d246487.png)
将双引号全部改为单引号

**Comment by linxp001** [comment]
> 已找到解决办法 ![image](https://user-images.githubusercontent.com/129247570/235367432-4ea7de58-0618-462e-8608-d4c48d246487.png) 将双引号全部改为单引号

我改成单引号还是不行

**Comment by linxp001** [comment]
最后重新注册了一个slack账号好使了，以前的不知道为啥不行，可能是因为我没有用邮箱注册，直接用谷歌账号注册的？

**Comment by HalfSugarHakuryu** [comment]
我也这样，很烦，@没有变蓝

**Comment by lss233** [comment]
目前的一个暂时性的解决方法已经更新在项目教程文档中。需要进行的是获取 Claude 的成员识别码，然后加入到 channel_id中。

具体可以看：https://chatgpt-qq.lss233.com/pei-zhi-wen-jian-jiao-cheng/jie-ru-ai-ping-tai/jie-ru-claude#0x04-huo-qu-claude-de-shi-bie-ma

**Comment by DumoeDss** [comment]
> 目前的一个暂时性的解决方法已经更新在项目教程文档中。需要进行的是获取 Claude 的成员识别码，然后加入到 channel_id中。
> 
> 具体可以看：https://chatgpt-qq.lss233.com/pei-zhi-wen-jian-jiao-cheng/jie-ru-ai-ping-tai/jie-ru-claude#0x04-huo-qu-claude-de-shi-bie-ma

Claude-Interactor这个应用搜不到，请问应该怎么办？

**Comment by gallionmin** [comment]
config.cfg是什么呀
