### ISSUE TITLE
[BUG]Stable Diffusion 报错 405 Method Not Allowed

### ISSUE THREAD

**Issue by huangzhitian** [lss233/chatgpt-mirai-qq-bot#733]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**运行环境:**  
- 操作系统：linux
- 项目版本：最新

**描述**

SD日志 无内容
项目日志报错 405 Method Not Allowed
接口在浏览器下正常画图
接口后加上 sdapi/v1/txt2img，也能正常画图

**截图**  
![QQ截图20230430155626](https://user-images.githubusercontent.com/129321746/235342389-cf64c659-2a76-4d6a-9a55-8999bddcf83c.png)
![QQ截图20230430154917](https://user-images.githubusercontent.com/129321746/235342397-5ddf8b10-d2ac-44db-8158-45cedacd5c67.png)

![QQ截图20230430154947](https://user-images.githubusercontent.com/129321746/235342404-2caba6c6-f862-4a33-924c-c023d3cb661e.png)

**Comment by lss233** [comment]
看看你 sd webui 的日志，是不是没开 api？

**Comment by lss233** [comment]
看看你 sd webui 的日志，是不是没开 api？

**Comment by huangzhitian** [comment]
> 



> 看看你 SD webui 的日志，是不是没开 API？

API怎么开

**Comment by linxp001** [comment]
> > 
> 
> > 看看你 SD webui 的日志，是不是没开 API？
> 
> API怎么开

Launching Web UI with arguments: --autolaunch --medvram --xformers --api
