### ISSUE TITLE
[BUG] Sorry, you need to login first to access this service.

### ISSUE THREAD

**Issue by youtianmeng** [lss233/chatgpt-mirai-qq-bot#739]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG
增加了claude的登录后重启了一下，然后就变成这样了
chatgpt-qq-chatgpt-1     | 2023-05-01 04:09:42.654 | DEBUG    | platforms.onebot_bot:_:148 - 私聊消息：ping
chatgpt-qq-chatgpt-1     | 2023-05-01 04:09:42.737 | ERROR    | universal:handle_message:295 - Sorry, you need to login first to access this service.
chatgpt-qq-chatgpt-1     | Traceback (most recent call last):
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/bot.py", line 54, in <module>
chatgpt-qq-chatgpt-1     |     loop.run_until_complete(asyncio.gather(*bots))
chatgpt-qq-chatgpt-1     |     │    │                  │       │       └ [<Task pending name='Task-4' coro=<start_task() running at /app/platforms/onebot_bot.py:356> wait_for=<_GatheringFuture pendi...
chatgpt-qq-chatgpt-1     |     │    │                  │       └ <function gather at 0x7fd4bc3d0360>
chatgpt-qq-chatgpt-1     |     │    │                  └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop.run_until_complete at 0x7fd4bbe2d1c0>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
chatgpt-qq-chatgpt-1     |     self.run_forever()
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop.run_forever at 0x7fd4bbe2d120>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
chatgpt-qq-chatgpt-1     |     self._run_once()
chatgpt-qq-chatgpt-1     |     │    └ <function BaseEventLoop._run_once at 0x7fd4bbe2ef20>
chatgpt-qq-chatgpt-1     |     └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
chatgpt-qq-chatgpt-1     |     handle._run()
chatgpt-qq-chatgpt-1     |     │      └ <function Handle._run at 0x7fd4bc36bd80>
chatgpt-qq-chatgpt-1     |     └ <Handle <TaskStepMethWrapper object at 0x7fd4b5320d90>()>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
chatgpt-qq-chatgpt-1     |     self._context.run(self._callback, *self._args)
chatgpt-qq-chatgpt-1     |     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7fd4b5320d90>()>
chatgpt-qq-chatgpt-1     |     │    │            │    └ <member '_callback' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     │    │            └ <Handle <TaskStepMethWrapper object at 0x7fd4b5320d90>()>
chatgpt-qq-chatgpt-1     |     │    └ <member '_context' of 'Handle' objects>
chatgpt-qq-chatgpt-1     |     └ <Handle <TaskStepMethWrapper object at 0x7fd4b5320d90>()>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/platforms/onebot_bot.py", line 151, in _
chatgpt-qq-chatgpt-1     |     await handle_message(
chatgpt-qq-chatgpt-1     |           └ <function handle_message at 0x7fd4b5302e80>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | > File "/app/universal.py", line 261, in handle_message
chatgpt-qq-chatgpt-1     |     conversation_handler.current_conversation = await conversation_handler.create(
chatgpt-qq-chatgpt-1     |     │                    │                            │                    └ <function ConversationHandler.create at 0x7fd4b5302840>
chatgpt-qq-chatgpt-1     |     │                    │                            └ <conversation.ConversationHandler object at 0x7fd4b5f53b90>
chatgpt-qq-chatgpt-1     |     │                    └ None
chatgpt-qq-chatgpt-1     |     └ <conversation.ConversationHandler object at 0x7fd4b5f53b90>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/conversation.py", line 276, in create
chatgpt-qq-chatgpt-1     |     conversation = ConversationContext(_type, self.session_id)
chatgpt-qq-chatgpt-1     |                    │                   │      │    └ 'friend-1830242183'
chatgpt-qq-chatgpt-1     |                    │                   │      └ <conversation.ConversationHandler object at 0x7fd4b5f53b90>
chatgpt-qq-chatgpt-1     |                    │                   └ 'poe-chatgpt'
chatgpt-qq-chatgpt-1     |                    └ <class 'conversation.ConversationContext'>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/conversation.py", line 116, in __init__
chatgpt-qq-chatgpt-1     |     self.drawing_adapter = BingAdapter(self.session_id, ConversationStyle.creative)
chatgpt-qq-chatgpt-1     |     │    │                 │           │    │           │                 └ <ConversationStyle.creative: ['nlu_direct_response_filter', 'deepleo', 'disable_emoji_spoken_text', 'responsible_ai_policy_23...
chatgpt-qq-chatgpt-1     |     │    │                 │           │    │           └ <enum 'ConversationStyle'>
chatgpt-qq-chatgpt-1     |     │    │                 │           │    └ 'friend-1830242183'
chatgpt-qq-chatgpt-1     |     │    │                 │           └ <conversation.ConversationContext object at 0x7fd4b5ded750>
chatgpt-qq-chatgpt-1     |     │    │                 └ <class 'adapter.ms.bing.BingAdapter'>
chatgpt-qq-chatgpt-1     |     │    └ None
chatgpt-qq-chatgpt-1     |     └ <conversation.ConversationContext object at 0x7fd4b5ded750>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/app/adapter/ms/bing.py", line 47, in __init__
chatgpt-qq-chatgpt-1     |     self.bot = EdgeChatbot(cookies=self.cookieData, proxy=account.proxy)
chatgpt-qq-chatgpt-1     |     │          │                   │    │                 │       └ None
chatgpt-qq-chatgpt-1     |     │          │                   │    │                 └ BingCookiePath(cookie_content='MUID=06D05BE898B762AE0C0F490099BF63CB; SRCHD=AF=NOFORM; SRCHUID=V=2&GUID=45EFAE2157F74DD990D7A...
chatgpt-qq-chatgpt-1     |     │          │                   │    └ [{'name': 'MUID', 'value': '06D05BE898B762AE0C0F490099BF63CB'}, {'name': 'SRCHD', 'value': 'AF=NOFORM'}, {'name': 'SRCHUID', ...
chatgpt-qq-chatgpt-1     |     │          │                   └ <adapter.ms.bing.BingAdapter object at 0x7fd4b5342ad0>
chatgpt-qq-chatgpt-1     |     │          └ <class 'EdgeGPT.Chatbot'>
chatgpt-qq-chatgpt-1     |     └ <adapter.ms.bing.BingAdapter object at 0x7fd4b5342ad0>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/EdgeGPT.py", line 459, in __init__
chatgpt-qq-chatgpt-1     |     _Conversation(self.cookies, self.proxy),
chatgpt-qq-chatgpt-1     |     │             │    │        │    └ None
chatgpt-qq-chatgpt-1     |     │             │    │        └ <EdgeGPT.Chatbot object at 0x7fd4b5341a50>
chatgpt-qq-chatgpt-1     |     │             │    └ [{'name': 'MUID', 'value': '06D05BE898B762AE0C0F490099BF63CB'}, {'name': 'SRCHD', 'value': 'AF=NOFORM'}, {'name': 'SRCHUID', ...
chatgpt-qq-chatgpt-1     |     │             └ <EdgeGPT.Chatbot object at 0x7fd4b5341a50>
chatgpt-qq-chatgpt-1     |     └ <class 'EdgeGPT._Conversation'>
chatgpt-qq-chatgpt-1     |   File "/usr/local/lib/python3.11/site-packages/EdgeGPT.py", line 318, in __init__
chatgpt-qq-chatgpt-1     |     raise NotAllowedToAccess(self.struct["result"]["message"])
chatgpt-qq-chatgpt-1     |           │                  │    └ {'result': {'value': 'UnauthorizedRequest', 'message': 'Sorry, you need to login first to access this service.'}}
chatgpt-qq-chatgpt-1     |           │                  └ <EdgeGPT._Conversation object at 0x7fd4b5341110>
chatgpt-qq-chatgpt-1     |           └ <class 'EdgeGPT.NotAllowedToAccess'>
chatgpt-qq-chatgpt-1     | 
chatgpt-qq-chatgpt-1     | EdgeGPT.NotAllowedToAccess: Sorry, you need to login first to access this service.
chatgpt-qq-chatgpt-1     | 2023-05-01 04:09:42.750 | DEBUG    | platforms.onebot_bot:respond:112 - [OneBot] 尝试发送消息：出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
chatgpt-qq-chatgpt-1     | 原因：Sorry, you need to login first to access this service.
![image](https://user-images.githubusercontent.com/106040493/235405649-00d4fb71-aba7-419b-951c-5ae6af5646cd.png)

**Comment by lss233** [comment]
bing cookie 过期了吧
