### ISSUE TITLE
sdwebui的api应该加什么参数才能认证

### ISSUE THREAD

**Issue by iknow2333** [lss233/chatgpt-mirai-qq-bot#740]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
画图失败！原因： Client error '401 Unauthorized' for url 'https://xxxxxxx/sdapi/v1/txt2img'
For more information check: https://httpstatuses.com/401

**运行环境:**  
- 操作系统：？
- Docker： ？
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by GTian28** [comment]
如果自己的sd api设置了账号密码，就在config文件的[sdwebui]标签下添加（注意账号和密码中间的冒号是英文的冒号）：
Authorization = 账号:密码

**Comment by iknow2333** [comment]
> 如果自己的sd api设置了账号密码，就在config文件的[sdwebui]标签下添加（注意账号和密码中间的冒号是英文的冒号）：
> Authorization = 账号:密码

感谢🙏

**Comment by iknow2333** [comment]
> 如果自己的SD API设置了账号密码，就在config文件的[sdwebui]标签下添加（注意账号和密码中间的冒号是英文的冒号）： Authorization = 账号：密码

关太急了，还是报401，不加引号就是语法错误

**Comment by iknow2333** [comment]
😂应该是这个，我看你们的参数都是小写
authorization = "account:password"

**Comment by GTian28** [comment]
> 😂应该是这个，我看你们的参数都是小写 authorization = "account:password"

大意了，，忘记加引号了。。
