### ISSUE TITLE
[BUG] 机器人使用图片模式时总是会在图片前加一个换行

### ISSUE THREAD

**Issue by Ray-Lum** [lss233/chatgpt-mirai-qq-bot#742]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG
- [√] 我认为这可能是 go-cqhttp 与 chatGPT for QQ 通信之间的BUG

**表现**  
不论是私聊还是群聊，在图片模式回复模式下，总是在图片的前面有一个空格
![image](https://user-images.githubusercontent.com/51054841/235497556-886da8d4-7cae-4ab5-b142-2d4e58a17147.png)

**运行环境:**  
- 操作系统：Windows 11
- Docker： NO
- 项目版本：2.4.2
**复现步骤**  
描述你是如何触发这个 BUG 的
正常使用，没有任何报错，不知道什么时候，在图片回复的时候就会在图片前面多个换行，导致空了一行，不是很美观……

**预期行为**  
在图片的前面没有这个换行

**其他内容**  
这是 go-cqhttp 的相关配置部分：
![image](https://user-images.githubusercontent.com/51054841/235498587-77b79129-8d27-4813-b6df-83ec4fb599e0.png)

chatGPT for QQ 这边没有任何报错：
![image](https://user-images.githubusercontent.com/51054841/235499014-0394e2e5-62b2-4846-a6e1-4febff8ccb3a.png)

求助我该怎么消去这个换行呢？

**Comment by lss233** [comment]
似乎开了回复引用之后就会出现这个换行，应该是gocqhttp或者onebot的问题，没办法解决。
