### ISSUE TITLE
[BUG]slack-claude发送的emoji无法正确识别

### ISSUE THREAD

**Issue by iknow2333** [lss233/chatgpt-mirai-qq-bot#744]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
![屏幕截图 2023-05-02 091111](https://user-images.githubusercontent.com/103983460/235558428-efa1255d-2094-4d76-b4d6-f5ddff8a4edb.png)

**运行环境:**  
telegram，没有用过其他平台，不确定是否在其他平台发生

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by lss233** [comment]
已修复。
