### ISSUE TITLE
询问问题

### ISSUE THREAD

**Issue by GudaoO** [lss233/chatgpt-mirai-qq-bot#745]
![33](https://user-images.githubusercontent.com/113413850/235638874-d9b18c58-b2b3-4234-b1b9-36382d041fc0.png)
想直接用SLACK而不用 OPENAI ，这样写有问题嘛

**Comment by GudaoO** [comment]
用的是一键部署包

**Comment by GudaoO** [comment]
运行的时候没有反应，依旧是直接跑OPENAI

**Comment by Yoak3n** [comment]
不想用openai就都删掉，留在配置文件里程序会把```xxx```当成你的token去加载，就会报错
估计因为这个项目一开始是用来接入chagpt的，所以会优先加载openai的配置，而不是按照配置文件里的顺序

**Comment by lss233** [comment]
你的 endpoint 怎么还是这么旧的？    看着不像是最新版。旧版没有slack

**Comment by GudaoO** [comment]
> 你的 endpoint 怎么还是这么旧的？ 看着不像是最新版。旧版没有slack

谢谢老哥，更新后可以了

**Comment by GudaoO** [comment]
> 不想用openai就把openai的相关配置都删掉，留在配置文件里的话，程序会把`xxx`当成你的token去加载，就会报错 估计因为这个项目一开始是用来接入chagpt的，所以会优先加载openai的配置，而不是按照配置文件里的顺序

![不行](https://user-images.githubusercontent.com/113413850/235831155-03cd6036-c8f6-40d2-ba6b-c2ded29427ea.png)
好像不删也可以，我按楼下老哥说的更新了一下，可以了
![解决](https://user-images.githubusercontent.com/113413850/235831203-756c0b64-3fec-446e-a8b1-0e21505dc226.png)
这个是更新后的，没有删OEAN AI代码
阿里嘎多 指教 /doge

**Comment by lss233** [comment]
发下完整的错误日志

**Comment by GudaoO** [comment]
> 发下完整的错误日志

问题已经解决 阿里嘎多
