### ISSUE TITLE
运行一段时间后mirai就会报异常

### ISSUE THREAD

**Issue by ToukoYui** [lss233/chatgpt-mirai-qq-bot#747]
程序是能正常跑起来的，问题在于跑了一段时间后mirai就会报相关异常，异常信息如下：
![image](https://user-images.githubusercontent.com/118440716/235868005-4e5441e2-3493-4f3f-aad1-95f0228cd7b0.png)
异常一旦出现，仍能接收消息，但无法回复

**Comment by lss233** [comment]
这是 mirai api http 的错误信息，建议你到 mirai api http 项目下反馈。  我修不了
