### ISSUE TITLE
type object 'Config' has no attribute 'load_config'

### ISSUE THREAD

**Issue by keke1229488344** [lss233/chatgpt-mirai-qq-bot#75]
![image](https://user-images.githubusercontent.com/17313185/213870557-09db893d-391d-4ba8-9318-10e1ce043634.png)

**Comment by lss233** [comment]
你的项目是不是缺了一个叫 `config.py` 的文件

**Comment by keke1229488344** [comment]
是的，刚刚才发现，谢谢~除夕快乐(´▽`ʃ♡ƪ)
