### ISSUE TITLE
[BUG] 网页微信机器人太容易掉线了，测试

### ISSUE THREAD

**Issue by joe12801** [lss233/chatgpt-mirai-qq-bot#751]
网页微信机器人太容易掉线了，测试五天。每个掉线两三次。设置半个小时重启也没用
![image](https://user-images.githubusercontent.com/70465495/235970633-751c4edd-e213-4d30-8075-6f0206000782.png)

**Comment by lss233** [comment]
请到对应项目下反馈bug
