### ISSUE TITLE
vits 不存在该语音音色，请检查配置文件

### ISSUE THREAD

**Issue by yimrjotunn** [lss233/chatgpt-mirai-qq-bot#753]
使用MoeGoe-Simple-API 出现问题
使用本地api 用切换语音命令一直显示不存在音色
![image](https://user-images.githubusercontent.com/113271544/236159847-0de7b307-7784-4f87-973c-400496a3ce73.png)
使用http://lss.mchank.cn:23456/voice，没有问题
访问/voice/speakers后发现
![image](https://user-images.githubusercontent.com/113271544/236160440-ed3a54c3-c735-4a24-b09f-4f4399df8325.png)
![image](https://user-images.githubusercontent.com/113271544/236160547-ff4dad3e-40d1-4b96-9287-8d282804c808.png)
格式发生变化，不知道是不是这个原因导致的

使用名字切换，报错
![image](https://user-images.githubusercontent.com/113271544/236159457-0f7e66fc-c490-4144-8e53-3fd4cf3d5fc8.png)

**Comment by lss233** [comment]
最新版已修复此问题。
