### ISSUE TITLE
重复cf验证...无解?

### ISSUE THREAD

**Issue by keke1229488344** [lss233/chatgpt-mirai-qq-bot#76]
![image](https://user-images.githubusercontent.com/17313185/213899623-c0e97975-4f0c-4af8-8f54-971deefaa364.png)

![image](https://user-images.githubusercontent.com/17313185/213899465-0558e9ef-0ca4-4e7d-99fa-d849bc63381a.png)

更换ip依旧...

**Comment by lss233** [comment]
YES

**Comment by lss233** [comment]
#85 已对此情况的表现、原因和解决方案作了详细说明。
