### ISSUE TITLE
[Feature] 文心一言去水印

### ISSUE THREAD

**Issue by fangyuan99** [lss233/chatgpt-mirai-qq-bot#763]
希望可以结合这个脚本[文心一言去码工具 - 源码](https://greasyfork.org/zh-CN/scripts/462166-%E6%96%87%E5%BF%83%E4%B8%80%E8%A8%80%E5%8E%BB%E7%A0%81%E5%B7%A5%E5%85%B7/code)
去除文心一言生成图片的水印

**Comment by lss233** [comment]
我觉得留着挺好的，能证明人家确实是文心一言生成的。

**Comment by fangyuan99** [comment]
或许可以加个配置项？
