### ISSUE TITLE
企业微信支持群聊？

### ISSUE THREAD

**Issue by 6vision** [lss233/chatgpt-mirai-qq-bot#766]
看介绍，好像是创建的企业应用吧，不支持群聊吧

**Comment by lss233** [comment]
是的，不支持。

**Comment by yaoice** [comment]
> 是的，不支持。
那这里是不是要更新下
<img width="747" alt="image" src="https://github.com/lss233/chatgpt-mirai-qq-bot/assets/10432250/0bc3f4bb-d1ab-47ba-b784-bfa62b4ca1ae">
