### ISSUE TITLE
Railway部署

### ISSUE THREAD

**Issue by edu-lance** [lss233/chatgpt-mirai-qq-bot#768]
在Railway部署，CHATGPT_FOR_BOT_FULL_CONFIG中的reverse_ws_port 与 PORT 变量的值都设置为8554。go-cqhttp中的反向WS Universal 地址怎么填？ws://xxxx.up.railway.app:8554/ws 不行呀。

**Comment by lss233** [comment]
参考文档中的教程， reverse_ws_port、PORT都填80
然后 universal 地址填：wss://xxxx.up.railway.app/ws

**Comment by edu-lance** [comment]
> 参考文档中的教程， reverse_ws_port、PORT都填80 然后 universal 地址填：wss://xxxx.up.railway.app/ws

只能使用80端口不能指定其他端口吗？另外如果要接入个人微信开启http服务怎么办？需要两个端口

**Comment by edu-lance** [comment]
没事了，查询了下，Railway 只能使用 80 和 443 端口。
