### ISSUE TITLE
[BUG] 预设功能无法使用

### ISSUE THREAD

**Issue by 0908139992926517G** [lss233/chatgpt-mirai-qq-bot#773]
**提交 issue 前，请先确认：**
- [已看] 我已看过 **FAQ**，此问题不在列表中
- [ 已看] 我已看过其他 issue，他们不能解决我的问题 
- [ 已看] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
程序和go-cqhttp启动和运行没问题，但在qq上无法加载预设。

**运行环境:**  
- 操作系统：win11
- Docker： ？
- 项目版本：v2.5.1

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
机器人应该可以加载预设

**截图**  

<img width="1280" alt="屏幕截图 2023-05-07 041229" src="https://user-images.githubusercontent.com/130917898/236645949-5e5a67d6-f4d4-4e8e-ba66-0610a720d26d.png">
<img width="1280" alt="屏幕截图 2023-05-07 041242" src="https://user-images.githubusercontent.com/130917898/236645951-a96cdf78-1416-42cc-9ee9-d7d0d4495d99.png">
<img width="1280" alt="屏幕截图 2023-05-07 041619" src="https://user-images.githubusercontent.com/130917898/236645960-00d054eb-5f26-4205-8343-5f23757ce818.png">
<img width="167" alt="image" src="https://user-images.githubusercontent.com/130917898/236646023-e96fa552-516c-4aa9-9a6c-72229b2a5b6b.png">

**其他内容**  
本人纯小白，第一次，请多多包涵。
预设文件只进行了重命名，没动文件本体

**Comment by lss233** [comment]
bing不支持预设功能

**Comment by 0908139992926517G** [comment]
好吧，谢谢帮助。
