### ISSUE TITLE
是否可以添加Replit的支持?

### ISSUE THREAD

**Issue by Mhatetk** [lss233/chatgpt-mirai-qq-bot#774]
我想在Replit预览一下,可我只找到了Docker方式部署,Replit无法使用Docker

**Comment by lss233** [comment]
docker 只是用来封装运行环境用的，和这个没什么关系。  

你可以用他们的导入 GitHub 项目功能：  https://docs.replit.com/programming-ide/using-git-on-replit/running-github-repositories-replit

**Comment by Mhatetk** [comment]
> docker 只是用来封装运行环境用的，和这个没什么关系。
> 
> 你可以用他们的导入 GitHub 项目功能： https://docs.replit.com/programming-ide/using-git-on-replit/running-github-repositories-replit

抱歉,我还是不会,能否让你

**Comment by Mhatetk** [comment]
> docker 只是用来封装运行环境用的，和这个没什么关系。
> 
> 你可以用他们的导入 GitHub 项目功能： https://docs.replit.com/programming-ide/using-git-on-replit/running-github-repositories-replit

抱歉,我还是无法运行,能否请你写一个文档

**Comment by lss233** [comment]
你可以用这个 Template： https://replit.com/@lss233/chatgpt-mirai-qq-bot

然后在 Secrets 里面添加一项，键写  CHATGPT_FOR_BOT_FULL_CONFIG 值就写你的配置文件（不要把你的配置写进 config.cfg，会导致你被盗号）

然后再点 RUN 就行了。  


我建议不是专业人员**不要**用 Replit 跑这个项目，因为会缺少一些运行依赖（如 ffmpeg、wkhtmltopdf等），功能会缺失很多，免费版那点配置估计也跑不动这个程序。

**Comment by Mhatetk** [comment]
好的,感谢。我是教育人员,验证之后可以免费创建私有仓库,配置也会升级为2H2G，没有隐私风险，配置也都能跑那些占用不是特别高的那些
