### ISSUE TITLE
[BUG] Bing Cookie过期后，所有AI均无法使用

### ISSUE THREAD

**Issue by Winnie0408** [lss233/chatgpt-mirai-qq-bot#776]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
向机器人发送消息，无论当前使用哪个语言模型，都会提示“Bing Cookie过期”，且无法切换模型

**运行环境:**  
- 操作系统：Ubuntu 22.04 LTS
- Docker：无
- 项目版本：2.5.1

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 向机器人发送消息
2. See error

**预期行为**  
Bing Cookie过期导致Bing无法使用，但是其他语言模型均正常响应

**截图**  
![Screenshot_2023-05-07-12-58-15-534_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/42741874/236658758-0f11b9b5-beb7-437d-a8e9-2c250a05b8f5.jpg)

![Screenshot_2023-05-07-12-58-23-545_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/42741874/236658757-e0ed4cd7-e2fd-4594-a801-66bc290bdaef.jpg)

![Screenshot_2023-05-07-13-10-00-731_com.server.auditor.ssh.client.jpg](https://user-images.githubusercontent.com/42741874/236658914-4f1b64ec-a1f2-4059-9b8d-d1fb8251a9c4.jpg)

**其他内容**  
配置文件中，Bing的相关配置是排在第一个

**Comment by lss233** [comment]
这个可能和 Bing 账号初始化的策略有关系。  #755  会修复这个问题。  

目前版本的解决方法就是设置一个 bing 之外的 default_ai。

**Comment by Winnie0408** [comment]
> 这个可能和 Bing 账号初始化的策略有关系。  #755  会修复这个问题。  
> 
> 目前版本的解决方法就是设置一个 bing 之外的 default_ai。

目前我设置的default_ai是chatgpt-api，但是还是会有这个问题

**Comment by lss233** [comment]
是不是你开了bing的画图？

**Comment by Winnie0408** [comment]
> 是不是你开了bing的画图？
> 

是的
