### ISSUE TITLE
怎么切换模型？

### ISSUE THREAD

**Issue by Sunhomen** [lss233/chatgpt-mirai-qq-bot#779]
只有bing开头时才能调用它，怎么一直使用bing 而且不用加开头的“bing”字符？
![image](https://user-images.githubusercontent.com/109470730/236666706-93012f80-8033-4262-b6ed-4885b01b4243.png)
![image](https://user-images.githubusercontent.com/109470730/236666822-3e1f8f1c-5ff3-40e9-af62-564dd77f81c2.png)

**Comment by lss233** [comment]
https://github.com/lss233/chatgpt-mirai-qq-bot/wiki
