### ISSUE TITLE
假设QQ-Bot为A，能不能让A读取A发送的带有全局前缀的消息（即自己读自己的消息）？

### ISSUE THREAD

**Issue by araea** [lss233/chatgpt-mirai-qq-bot#786]
# 具体情景：
1. 使用MACOS协议部署QQ机器人A。
2. 在手机上登陆A。
3. 用A给A发消息。
# 默认情况：
- 现在默认是A无法读取A发的消息。
# 问题描述：
- 请问在哪里可以设置让A可以读取A的消息？

**Comment by lss233** [comment]
这种行为是被禁止的，否则机器人会永无止境地发送消息。

**Comment by araea** [comment]
> 这种行为是被禁止的，否则机器人会永无止境地发送消息。

我的意思是识别加前缀的消息，AI发消息不会加前缀，也就不会响应。所以其实是可行的，我想知道怎么做，您能告诉我吗？谢谢你！

**Comment by lss233** [comment]
我在代码里面写死了这个判定，如果你执意要开启的话，需要自己修改代码，删除这两行：
https://github.com/lss233/chatgpt-mirai-qq-bot/blob/72373f0a41811128b53cfd6c5747be1e99ee451a/platforms/ariadne_bot.py#LL143C2-L144C3

**Comment by araea** [comment]
> 我在代码里面写死了这个判定，如果你执意要开启的话，需要自己修改代码，删除这两行：
> 
> https://github.com/lss233/chatgpt-mirai-qq-bot/blob/72373f0a41811128b53cfd6c5747be1e99ee451a/platforms/ariadne_bot.py#LL143C2-L144C3

简直太感谢了！谢谢您！真的非常感谢有你们这些大佬们……感动的快哭了呜！

**Comment by lss233** [comment]
不客气

**Comment by araea** [comment]
> 不客气

大佬，不好意思，又要来打扰你一下，修改代码后私聊是可以自己读取自己发的消息，那如果在QQ群里面，也可以做到自己读自己吗？你说你已经锁死了代码，是不是没办法做到呢……如果很麻烦的话，就不耽误大佬时间了，如果可以做到的话，大佬可以提供一个操作思路吗？

**Comment by lss233** [comment]
> > 不客气
> 
> 大佬，不好意思，又要来打扰你一下，修改代码后私聊是可以自己读取自己发的消息，那如果在QQ群里面，也可以做到自己读自己吗？你说你已经锁死了代码，是不是没办法做到呢……如果很麻烦的话，就不耽误大佬时间了，如果可以做到的话，大佬可以提供一个操作思路吗？

mirai 读不到自己发送出去的消息，如果你要改的话可以在消息发送的代码处进行判断，符合前缀就重新调用 handle_message 让这条消息被认为是自己收到的消息。

**Comment by araea** [comment]
> > > 不客气
> > 
> > 
> > 大佬，不好意思，又要来打扰你一下，修改代码后私聊是可以自己读取自己发的消息，那如果在QQ群里面，也可以做到自己读自己吗？你说你已经锁死了代码，是不是没办法做到呢……如果很麻烦的话，就不耽误大佬时间了，如果可以做到的话，大佬可以提供一个操作思路吗？
> 
> mirai 读不到自己发送出去的消息，如果你要改的话可以在消息发送的代码处进行判断，符合前缀就重新调用 handle_message 让这条消息被认为是自己收到的消息。

大佬，我明白你的意思，但是我先道个歉，是我没表达清楚，我想要的效果是，电脑上MACOS的Bot登陆A账号，我手机上也登陆A账号，我在群聊里，用手机在群聊里也可以使用比如“ask 你好”这样的指令，我想让自己手机上QQ发送的消息能被传送到[Ariadne]里，这样就可以不用小号自己和机器人玩了，我有这个需求是因为就只有这一个QQ能成功登陆，不好意思啊，麻烦你这么久，如果大佬有解决或者说实现这个功能的方法，可以跟我讲一下吗？万分感激！

**Comment by lss233** [comment]
你可以监听 https://graia-ariadne.pages.dev/event/message/#graia.ariadne.event.message.GroupSyncMessage 这个事件。
当然，最简单的办法就是注册两个号，不用折磨自己。

**Comment by araea** [comment]
> 你可以监听 https://graia-ariadne.pages.dev/event/message/#graia.ariadne.event.message.GroupSyncMessage 这个事件。
> 当然，最简单的办法就是注册两个号，不用折磨自己。

好滴！等我回去就试试。是不是把上面的group复制一份，然后把这个事件名字换上去就好了。

**Comment by lss233** [comment]
是
