### ISSUE TITLE
cloudflare验证后提示“Failed to refresh session!”

### ISSUE THREAD

**Issue by VCE1** [lss233/chatgpt-mirai-qq-bot#79]
![image](https://user-images.githubusercontent.com/79588027/216762826-4ca9ff1d-b02d-41c6-98e3-1ec043c393e3.png)
![image](https://user-images.githubusercontent.com/79588027/216762841-1a439f66-e475-417e-8f49-e2b5843ec3bb.png)

**Comment by VCE1** [comment]
我是在国内的服务器上部署的，本机开了代理过了验证，难道和网络环境有关吗

**Comment by lss233** [comment]
试试 https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v1.6-RC1

**Comment by lss233** [comment]
IP 被封禁。属于 Case 2 情况之一。 #85 已对此情况的表现、原因和解决方案作了详细说明。
