### ISSUE TITLE
运行最新的Windows端程序的“启动chatgpt.cmd”报错

### ISSUE THREAD

**Issue by joyancy** [lss233/chatgpt-mirai-qq-bot#80]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\quickstart-windows-amd64(1)\chatgpt\bot.py", line 6, in <module>
    from typing_extensions import Annotated
ModuleNotFoundError: No module named 'typing_extensions'

这个错误要怎么解决？

**Comment by lss233** [comment]
重新执行初始化吧，应该是网络问题导致有库没装上

**Comment by joyancy** [comment]
> 重新执行初始化吧，应该是网络问题导致有库没装上

重新装了，应该不是网络问题

**Comment by lss233** [comment]
你看一下初始化的时候有没有提示什么错误

**Comment by lss233** [comment]
#101
