### ISSUE TITLE
[BUG] ChatGPT API报错：you must provide a model parameter

### ISSUE THREAD

**Issue by lsCoding666** [lss233/chatgpt-mirai-qq-bot#800]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况
调用chatgpt api时 返回
```
400 Bad Request {
    "error": {
        "message": "you must provide a model parameter",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}
```
但是没有找到那里可以设置这个参数
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/73888354/51aec032-7d1c-495a-8094-944c2e4154b1)
参考解决方案
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/73888354/faec9d96-83f5-4d9a-a22c-484831d6e3ac)
简单来说就是缺少了角色描述

**运行环境:**  
- 操作系统：windows 一键

**Comment by lsCoding666** [comment]
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/73888354/e8eb5d50-3a03-417d-92d2-cc22d5e09e43)

**Comment by lsCoding666** [comment]
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/73888354/e3957bdf-74f0-4b90-9e75-84ec4bc59eeb)

**Comment by lss233** [comment]
从截图来看你似乎设置了一个 api endpoint，所以要么是你写错了 api endpoint，或者是你的这个api endpoint 有问题。

**Comment by lsCoding666** [comment]
确实是 经过检查 url结尾多了个/
