### ISSUE TITLE
[BUG] 连接到反向WebSocket Universal服务器 ws://chatgpt:8554/ws 时出现错误

### ISSUE THREAD

**Issue by pasdy1** [lss233/chatgpt-mirai-qq-bot#805]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
连接到反向WebSocket Universal服务器 ws://chatgpt:8566/ws 时出现错误: websocket: bad handshake 

**运行环境:**  
- 操作系统：ubuntu
- Docker： 20
- 项目版本：Linux快速部署脚本

**截图**  
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/51935244/5b7c06b9-6728-4948-92f7-e695c5f4dc9e)

**配置文件信息**

reverse_ws_host = "chatgpt"
reverse_ws_port = 8566

servers:
  - ws-reverse:
      universal: ws://chatgpt:8566/ws

**Comment by lss233** [comment]
请提供一下本程序的日志
docker-compose logs -f chatgpt
