### ISSUE TITLE
[BUG] 百度云审核不合规消息自定义无效果原因

### ISSUE THREAD

**Issue by huangzhitian** [lss233/chatgpt-mirai-qq-bot#808]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**截图**  
之前设置一直没有效果，今天翻代码才发现群主变量名写错了= =
config.cfg配置文件中  illgalmessage 改为 prompt_message即可
![QQ截图20230514025914](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/129321746/2f810a5c-286f-4ee9-93c8-bf460b7f4087)
![QQ截图20230514030030](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/129321746/51070139-b40a-4b93-9d6b-18549de9009e)

**Comment by lss233** [comment]
感谢提醒，已更新文档。
