### ISSUE TITLE
[BUG] 正则表达式不能在句中匹配的问题

### ISSUE THREAD

**Issue by Cloxl** [lss233/chatgpt-mirai-qq-bot#809]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
正则表达式 只能匹配句首  
**运行环境:**  
- 操作系统：ubuntu 22.04
- Docker： 无docker 使用手动部署
- 项目版本：2.5.1

**复现步骤**  
我先声明一点 这只是我的个人需求 我需要判断一个文本中是否存在这个被正则表达式匹配的词语 如果这与你的预期不符 请忽略我的问题  

在您的universal.py的第241行代码中 匹配正则表达式为**match**匹配方法而**match**方法默认从句首开始匹配 如果匹配不到就放弃匹配 我的建议是换成**search**方法 或者在配置文件中加入一个全局匹配的值 同时保留**match**与**search**  

使用**match**对于本项目跟其它机器人插件混合在一起使用时是极其方便的 假设其它插件命令为**听歌**使用```ignore_regex = ["#听歌"]```可以完美解决这个情况  

但是我的想法是在全文中匹配一些词语 达到类似于审核的效果 我添加了ignore_regex = ["形式"] 在reg101可以在任何地方匹配 但在实际测试过程中 我使用 **形式你好** 能匹配 **你好形式**却不能匹配  
![6ae9f50e729e90ad.jpg](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/88774611/0e9d68a7-a9d3-4fde-b8d3-5f5eb5575148)  
开始我怀疑自己的正则表达式有问题
我换了
 ```.*(形式|日常)```
还有```^(服务器|server|举报|。。|add|xbjabjajja)```
均不能解决问题 后面我开始查找这方面的代码 发现了是匹配方式的问题 我替换成**search**后 能完美使用  
![-5668ab5029611b2.jpg](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/88774611/b930dce3-fb6b-406c-8530-5abe8338b389)  
这仅仅是我的个人建议 可能由于能力不佳 没有完全掌握正则表达式的相关知识导致我出现了这个问题   
感谢你看到这里！

**预期行为**  
在句子中匹配正则表达式

**Comment by lss233** [comment]
使用 `re.match` 就是为了避免在句中匹配导致机器人不回应的。
如果你想通过此功能实现关键词匹配功能，你可以把你的表达式改为：
```regex
.*(形式|日常).*
```
