### ISSUE TITLE
ARM 架构部署方法

### ISSUE THREAD

**Issue by Kaol-Fu** [lss233/chatgpt-mirai-qq-bot#81]
arm服务器执行`docker compose run --rm mirai`后报`exec /mirai/mcl: exec format error`的错误，怀疑是 docker image 没有 arm 版本导致，可否制作个 arm 的版本，谢谢！

**Comment by lss233** [comment]
我手头上没有 arm 服务器，建议你使用手动部署

**Comment by lss233** [comment]
我做了一个 mirai 的 docker镜像： lss233/mirai-http
但是 API 版的做不了，因为有一个依赖 tiktoken 没有 ARM 的 wheel，我在 CI 中也构建不出来。

**Comment by Erik11571** [comment]
在ARM架构的机器部署的方法（这个方法只适用于Docker和Docker Compose部署）

docker pull --platform amd64 lss233/chatgpt-mirai-qq-bot:browser-latest #--platform amd64 指定镜像的架构

执行下面三条命令实现多架构环境

开启 binfmt_misc 来运行非本地架构的 Docker 镜像
docker run --privileged --rm tonistiigi/binfmt --install all

将默认 Docker 构建器切换为多架构构建器
docker buildx create --use

查看新的多架构构建器是否生效，需执行 
docker buildx ls

之后就可以按正常步骤部署了。
