### ISSUE TITLE
官方 API 出错 临时解决方案 | That model does not exists | The server is overloaded or not ready yet. 

### ISSUE THREAD

**Issue by lss233** [lss233/chatgpt-mirai-qq-bot#82]
自 2023/2/8 起， 官方 API 的免费模型在调用时会出现 `That model does not exists` 或者 `The server is overloaded or not ready yet.` 的提示，以下为临时解决方案：

## 方案1：使用付费的 text-davinci-003 模型
想要使用此模型，需要设置环境变量 GPT_ENGINE=text-davinci-003
![8A$96P~2XUVN5@F)1I6N7H9](https://user-images.githubusercontent.com/8984680/217586865-62987e50-04d8-404e-905d-ccc34db3e873.png)

Windows 用户可以参考此教程：https://view.inews.qq.com/k/20211202A08CCW00

Linux 用户 可以使用 `export GPT_ENGINE=text-davinci-003` 设置终端环境变量，然后执行 `python3 bot.py` 启动程序。

docker 用户可以通过命令或 docker-compose.yml 传递配置。

## 方案2：使用 1.5.x 版的网页接口

此方案使用浏览器模拟，访问 ChatGPT 进行聊天。  
它需要你的服务器能够正常打开 ChatGPT 的网页（需要海外 IP)。  
此外，你需要一个使用量比较少的 IP，否则可能会遇到被 Cloudflare 拦截的情况。
下载地址： https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v1.5.3

**Comment by SuInk** [comment]
这个付费的是免费额度只有18美元的那个吗

**Comment by lss233** [comment]
> 这个付费的是免费额度只有18美元的那个吗

是

**Comment by SuInk** [comment]
> > 这个付费的是免费额度只有18美元的那个吗
> 
> 是

好的，谢谢作者

**Comment by ctexthuang** [comment]
docker 把环境变量写进去后 依然还是报错
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。
The server experienced an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. {
  "error": {
    "message": "The server experienced an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists.",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
 500 {'error': {'message': 'The server experienced an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists.', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Thu, 09 Feb 2023 07:02:50 GMT', 'Content-Type': 'application/json', 'Content-Length': '292', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Openai-Model': 'text-davinci-003', 'Openai-Organization': 'user-yg202d5ypynlo8rlaneyhh4j', 'Openai-Processing-Ms': '30167', 'Openai-Version': '2020-10-01', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Request-Id': '223146a6522ef7a022415978a803d8b8'}

The server had an error while processing your request. Sorry about that!

**Comment by ctexthuang** [comment]
启动命令 
docker run --name mirai-chatgpt-bot -e XPRA_PASSWORD=123456  -v /home/docker_composer/chatgpt/config.cfg:/app/config.cfg --env GPT_ENGINE=text-davinci-003 --network host lss233/chatgpt-mirai-qq-bot:latest

**Comment by lss233** [comment]
这个应该是别的问题导致的，你可以开一个新的 issue 跟进一下，从参数 `'Openai-Model': 'text-davinci-003'` 里看的话是设置成功了。

**Comment by ctexthuang** [comment]
> 这个应该是别的问题导向的，你可以开一个新的问题跟进一下，从参数`'Openai-Model': 'text-davinci-003'`里看的话是设置成功了。

是不是因为我忘记开翻墙了导致的。要不我直接把机子假设到国外去吧

**Comment by lss233** [comment]
和这个没关系，你已经连上服务器了，网页版才需要梯子。

**Comment by ctexthuang** [comment]
> 和这个没关系，你已经连上服务器了，网页版才需要梯子。

也对。这个回复是服务器 回复的。

**Comment by lss233** [comment]
#108 已解决。

**Comment by topsuder** [comment]
是这个么 api登录的话我这边聊天一致报错

**Comment by haoyuexinghai** [comment]
为什么我使用1.5.5网页版安装，启动Mirai.cmd会出现
系统找不到指定的路径
Process exited with 3
请按任意键继续. . .

**Comment by dhzq** [comment]
![image](https://user-images.githubusercontent.com/120349387/219772370-51c7ef2c-3517-466d-96a7-bbcf4ce40c03.png)
![image](https://user-images.githubusercontent.com/120349387/219772421-7809c682-9113-4419-9562-a3825aba55dc.png)
两种方法都试了，还是不行，依旧That model does not exist
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/120349387/219773953-25a2ec44-f11c-4441-a567-5090ebb2bd0a.png">

**Comment by lss233** [comment]
>  两种方法都试了，还是不行，依旧That model does not exist <img alt="image" width="1278" src="https://user-images.githubusercontent.com/120349387/219773953-25a2ec44-f11c-4441-a567-5090ebb2bd0a.png">

你改完以后要更新容器， `docker-compose up -d`

**Comment by GTian28** [comment]
请问免费额度的18美元是在哪儿看到的？大概可以用多少次呢？

**Comment by AzXuan** [comment]
> 请问免费额度的18美元是在哪儿看到的？大概可以用多少次呢？

https://platform.openai.com/account/usage
官网的这个网址可以看到，要看实际使用了，换算是按照模型使用token来算钱的
以text-davinci-003 举例 价格是：$0.0200  / 1K tokens 
一汉字约等于2token左右 大概可以使用十万字左右

**Comment by nanomm** [comment]
> > 请问免费额度的18美元是在哪儿看到的？大概可以用多少次呢？
> 
> https://platform.openai.com/account/usage 官网的这个网址可以看到，要看实际使用了，换算是按照模型使用token来算钱的 以text-davinci-003 举例 价格是：$0.0200 / 1K tokens 一汉字约等于2token左右 大概可以使用十万字左右

请问意思是免费版18刀的额度用完就不能用了吗？

**Comment by GTian28** [comment]
> > > 请问免费额度的18美元是在哪儿看到的？大概可以用多少次呢？
> > 
> > 
> > https://platform.openai.com/account/usage 官网的这个网址可以看到，要看实际使用了，换算是按照模型使用token来算钱的 以text-davinci-003 举例 价格是：$0.0200 / 1K tokens 一汉字约等于2token左右 大概可以使用十万字左右
> 
> 请问意思是免费版18刀的额度用完就不能用了吗？

充钱就行了。不过话说回来api版本那么笨，也没啥可用的

**Comment by AzXuan** [comment]
> 

对，不大聪明，不过貌似可以自己训练模型，也还行，反正是拿来玩的

**Comment by imlhx** [comment]
一样的api key 没付费这个插件能用 不会产生#82的issue https://github.com/obiscr/ChatGPT
要不看下那个作者怎么调用的 ChatGPT？

**Comment by lss233** [comment]
目前最新版支持 GPT3.5 的 api，其对话效果强、响应速度快，原api版已不推荐使用。

**Comment by YUANWEI888** [comment]
wechat部署的机器人聊一段时间后只回复“Something went wrong” 是GPT问题还是服务器问题

**Comment by devinglaw** [comment]
在Linux采用一键命令调用后，没有输入API-KEY的地方，导致机器人无法使用。
