### ISSUE TITLE
.查询API余额 命令为什么无效 gpt运行界面没有任何信息提示

### ISSUE THREAD

**Issue by chongya-369** [lss233/chatgpt-mirai-qq-bot#821]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：windows
- Docker： ？
- 项目版本：v2.5.1

**复现步骤**  
描述你是如何触发这个 BUG 的
管理员qq向机器人发送命令 .查询API余额 后没有任何反馈，其他功能依然正常使用

**预期行为**  
应该查询到api的余额吧

**Comment by lss233** [comment]
因为这个命令已经删除了。

**Comment by chongya-369** [comment]
个人微信的好友是不是不能限制每小时的使用额度

**Comment by lss233** [comment]
> 个人微信的好友是不是不能限制每小时的使用额度

目前确实没有提供相关的接口
