### ISSUE TITLE
ip和端口都对但是就是404

### ISSUE THREAD

**Issue by 961882** [lss233/chatgpt-mirai-qq-bot#837]
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/28557954/92b80580-e315-40d9-acee-af4266574ede)

**Comment by lss233** [comment]
没有这一步骤，不知道你在做什么，请按模板重新填写issu。
