### ISSUE TITLE
[BUG] 使用AI画图(img2img)时，调用api的请求载荷init_images字段为空

### ISSUE THREAD

**Issue by FelixFeli** [lss233/chatgpt-mirai-qq-bot#839]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
使用AI画图(img2img)时，调用api的请求载荷init_images字段为空，SD不能正常的执行图生图功能。报错提示AttributeError: 'NoneType' object has no attribute 'startswith'。

**运行环境:**  
- 操作系统：Windows 10 21H2
- Docker： 无
- 项目版本：v 2.4.2

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 配置好[sdwebui]，文生图功能正常
2. 输入AI 画图的触发指令+【一张图片】
3. 聊天返回提示“画图失败！原因： Server error '500 Internal Server Error' for url 'http://127.0.0.1:7860/sdapi/v1/img2img'”

**预期行为**  
应该返回一张img2img的图片

**截图**  
抓包发送数据：
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/57336904/c650a856-6423-4afc-b383-fb67ec0daf05)
抓包返回数据
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/57336904/9ef24d7b-3349-4a57-9dc8-5cc0e9402076)

**其他内容**  
查看源码发现sdwebui.py中line44，'init_images': [x.base64 for x in init_images]，其中x.base64为空。此Image只有id和url字段有效，base64字段未赋值。需要调用一次get_bytes()方法，才能将base64字段赋值。
亲测在sdwebui.py中line43处添加for x in init_images:    await x.get_bytes()，即可修复该问题！

**Comment by lss233** [comment]
感谢提醒，你可以直接发个 PR 过来！

**Comment by huangzhitian** [comment]
> **提交 issue 前，请先确认：**
> 
> * [√] 我已看过 **FAQ**，此问题不在列表中
> * [√] 我已看过其他 issue，他们不能解决我的问题
> * [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG
> 
> **表现** 使用AI画图(img2img)时，调用api的请求载荷init_images字段为空，SD不能正常的执行图生图功能。报错提示AttributeError: 'NoneType' object has no attribute 'startswith'。
> 
> **运行环境:**
> 
> * 操作系统：Windows 10 21H2
> * Docker： 无
> * 项目版本：v 2.4.2
> 
> **复现步骤** 描述你是如何触发这个 BUG 的
> 
> 1. 配置好[sdwebui]，文生图功能正常
> 2. 输入AI 画图的触发指令+【一张图片】
> 3. 聊天返回提示“画图失败！原因： Server error '500 Internal Server Error' for url '[http://127.0.0.1:7860/sdapi/v1/img2img'”](http://127.0.0.1:7860/sdapi/v1/img2img'%E2%80%9D)
> 
> **预期行为** 应该返回一张img2img的图片
> 
> **截图** 抓包发送数据： ![image](https://user-images.githubusercontent.com/57336904/239186245-c650a856-6423-4afc-b383-fb67ec0daf05.png) 抓包返回数据 ![image](https://user-images.githubusercontent.com/57336904/239186662-9ef24d7b-3349-4a57-9dc8-5cc0e9402076.png)
> 
> **其他内容** 查看源码发现sdwebui.py中line44，'init_images': [x.base64 for x in init_images]，其中x.base64为空。此Image只有id和url字段有效，base64字段未赋值。需要调用一次get_bytes()方法，才能将base64字段赋值。 亲测在sdwebui.py中line43处添加for x in init_images: await x.get_bytes()，即可修复该问题！

大佬，为什么我发送 画+一张图片，返回的是一张毫不相干的图，没用到图生图功能

**Comment by FelixFeli** [comment]
> 大佬，为什么我发送 画+一张图片，返回的是一张毫不相干的图，没用到图生图功能
图生图也需要提示词哦！
它参考的只是原图的结构，并不清楚你想生成的具体内容，而且与原图的相似程度还取决于Denoising strength等参数

**Comment by huangzhitian** [comment]
> > 大佬，为什么我发送 画+一张图片，返回的是一张毫不相干的图，没用到图生图功能
> 
> 图生图也需要提示词哦！ 它参考的只是原图的结构，并不清楚你想生成的具体内容，而且与原图的相似程度还取决于Denoising strength等参数

加了也还是不行，是这样用的吗
