### ISSUE TITLE
大佬是否考虑重新使用mirai 更新到mirai 2.15M1使用qr登录可以降低风控率

### ISSUE THREAD

**Issue by HoshinoHikariNeko** [lss233/chatgpt-mirai-qq-bot#852]
重振mirai荣光 吾辈义不容辞
[https://mirai.mamoe.net/topic/2134/%E4%BA%8C%E7%BB%B4%E7%A0%81%E6%89%AB%E7%A0%81%E7%99%BB%E5%BD%95?_=1684634682216](url)

**Comment by VoltaDusk** [comment]
可以手动部署mirai，目前在用qrlogin，挺稳的
