### ISSUE TITLE
[BUG] 无法使用access_token登录

### ISSUE THREAD

**Issue by pixia1234** [lss233/chatgpt-mirai-qq-bot#853]
无法使用正常的access_token登录
- 操作系统：windows最新版v2.5.1

使用了最新生成的access_token 并且使用类似的工具可以确认access_token正常，但是用本项目登录始终401

![这是使用本项目登陆的情况](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/61567631/903a4ab1-1474-4ff8-b8b1-e44f4373cd99)
![在使用相同的access_token时登陆的情况](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/61567631/4a5dbc77-120c-468b-9b3b-40b1386e1bc2)
同时可以确认代理工具正常

**Comment by singularity2000** [comment]
一样的情况

**Comment by lyl5678** [comment]
一样的情况，为什么呢？我重装了一遍又可以了
