### ISSUE TITLE
这种通过官方API调用的根本不是chatgpt，顶多是GPT-3

### ISSUE THREAD

**Issue by thechen130** [lss233/chatgpt-mirai-qq-bot#86]

**Comment by lss233** [comment]
取决于你使用的模型。
有些人觉得调用官方 API 时的输出和网页上的不一样，这和发送提示词的方式和内容有关，你可以通过修改预设和情感值来提高交流的质量。

目前本项目也支持调用 text-davinci-003 模型，也就是你
关于此问题的讨论请前往： https://github.com/acheong08/ChatGPT/issues/577
