### ISSUE TITLE
QQ画框验证地址无法打开

### ISSUE THREAD

**Issue by happymover** [lss233/chatgpt-mirai-qq-bot#866]
Linux版本
2.5.1

画框验证地址：https://captcha.go-cqhttp.org/captcha?id=l6MsC46q&style=simple&aid=16&uin=3180522649&sid=8867434771436491077&cap_cd=ReXLDTbW_s3af_TcDLyJvN02-2hV64HezuNHjTkIifug-wOfod4jHg**&clientype=1&apptype=2

在浏览器中输入该验证地址，提示：Web server is down

**Comment by lss233** [comment]
go-cqhttp 的问题请在 go-cqhttp 的仓库反馈。  
你也可以使用二维码登录。
