### ISSUE TITLE
付费模型调用失败

### ISSUE THREAD

**Issue by ctexthuang** [lss233/chatgpt-mirai-qq-bot#87]
docker 把环境变量写进去后 依然还是报错
环境变量:
docker run --name mirai-chatgpt-bot -e XPRA_PASSWORD=123456  -v /home/docker_composer/chatgpt/config.cfg:/app/config.cfg --env GPT_ENGINE=text-davinci-003 --network host lss233/chatgpt-mirai-qq-bot:latest

报错信息:
The server experienced an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists. {
"error": {
"message": "The server experienced an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists.",
"type": "server_error",
"param": null,
"code": null
}
}
500 {'error': {'message': 'The server experienced an error while processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if the error persists.', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Thu, 09 Feb 2023 07:02:50 GMT', 'Content-Type': 'application/json', 'Content-Length': '292', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Openai-Model': 'text-davinci-003', 'Openai-Organization': 'user-yg202d5ypynlo8rlaneyhh4j', 'Openai-Processing-Ms': '30167', 'Openai-Version': '2020-10-01', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Request-Id': '223146a6522ef7a022415978a803d8b8'}

The server had an error while processing your request. Sorry about that!

**Comment by ctexthuang** [comment]
我感觉可能跟网络真的有关系。因为同样的语句有时候可以有时候不行

**Comment by lss233** [comment]
https://community.openai.com/t/continuous-gpt3-api-500-error-the-server-had-an-error-while-processing-your-request-sorry-about-that/42239/37
这似乎是  OpenAI 的毛病。

**Comment by ctexthuang** [comment]
> https://community.openai.com/t/continuous-gpt3-api-500-error-the-server-had-an-error-while-processing-your-request-sorry-about-that/42239/37 这似乎是 OpenAI 的毛病。

那用session版本的才可以处理这个问题了。貌似官方网页没出现这种问题。

**Comment by lss233** [comment]
是的。你可以使用 v1.5.x 的版本， 我现在已经把此系列设置为主版本。
