### ISSUE TITLE
[Feature] 能否为OpenWrt开发插件(支持扫描登录),或OpenWrt一键脚本

### ISSUE THREAD

**Issue by tou-7** [lss233/chatgpt-mirai-qq-bot#871]
**疑问: 在境外vps上QQ靠谱?**
(QQ连国内服务器要经过GFW, vps 有可能被 GFW 标记 为代理服务器,有可能添加vps被墙风险)
(本人之前,开全局科学上网,vps被GFW 标记了,过一段时间vps端口就封了 )

在路由器(OpenWrt)运行, QQ直连国内服务器,chatgpt则通过代理连接
QQ比在境外vps,更稳定,在路由器运行,效果等同于在vps部署

**Comment by lss233** [comment]
那你应该问 go-cqhttp 或者 mirai 的开发团队吧， 这个项目不包含 QQ 登录部分。

**Comment by lsCoding666** [comment]
买个小主机，300块钱都不用，装个ubuntu跑就行了

**Comment by hgy327** [comment]
openwrt用这个https://github.com/lss233/chatgpt-mirai-qq-bot/releases可以部署
