### ISSUE TITLE
ERROR    | chatbot:<module>:66 - OpenAI 登录失败，可能是 session_token 过期或无法通过 CloudFlare 验证，建议歇息一下再重试。

### ISSUE THREAD

**Issue by lyhb414** [lss233/chatgpt-mirai-qq-bot#88]
运行Windows快速部署包的 启动ChatGPT.cmd 报了这个错：
ERROR    | chatbot:<module>:66 - OpenAI 登录失败，可能是 session_token 过期或无法通过 CloudFlare 验证，建议歇息一下再重试。

**Comment by lss233** [comment]
？

**Comment by Seventher** [comment]
我也遇到了这个问题

**Comment by paper-cut** [comment]
也遇到了这个问题

**Comment by lss233** [comment]
没有完整的日志不能判断具体是什么情况。
多数情况在 FAQ 中也已经解答了。

**Comment by zimozhou** [comment]
报错往上翻一点，可能是chrome和chromedrive版本不一致
`selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:55888
from session not created: This version of ChromeDriver only supports Chrome version 110
Current browser version is 109.0.5414.119`

**Comment by lss233** [comment]
是的。出现这个问题的情况还蛮多的，这是其中一种。

> 报错往上翻一点，可能是chrome和chromedrive版本不一致 `selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:55888 from session not created: This version of ChromeDriver only supports Chrome version 110 Current browser version is 109.0.5414.119`

**Comment by lss233** [comment]
现版本可以用 browserless 模式登录，此 issue 关闭。
