### ISSUE TITLE
[Feature] 多apikey怎么使用呢

### ISSUE THREAD

**Issue by joeyandyou** [lss233/chatgpt-mirai-qq-bot#89]

**Comment by lss233** [comment]
暂时不支持多 apikey，未来可以考虑加入

**Comment by lss233** [comment]
检查你使用的版本。api版对应master分支，latest镜像

**Comment by joeyandyou** [comment]
v1.6-RC3 - 官方 API 版  手动部署pip -r requirements.txt时默认安装revChatGPT=1.2.2会报错
建议修改一下.txt,revChatGPT==1.2.1这样才不会

**Comment by lss233** [comment]
> v1.6-RC3 - 官方 API 版 手动部署pip -r requirements.txt时默认安装revChatGPT=1.2.2会报错 建议修改一下.txt,revChatGPT==1.2.1这样才不会

感谢提醒，最新的  Docker 镜像将修复此问题

**Comment by lss233** [comment]
> > 暂时不支持多 apikey，未来可以考虑加入
> 
> 现在支持多apikey了吗

计划在 1.7 版本加入

**Comment by lss233** [comment]
v2.0 已支持
