### ISSUE TITLE
[BUG] 不支持poe.com付费模型

### ISSUE THREAD

**Issue by pixia1234** [lss233/chatgpt-mirai-qq-bot#895]
**提交 issue 前，请先确认：**
- [ ] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
无法调用poe.com付费模型
**运行环境:**  
- 操作系统：windows
- Docker： ？
- 项目版本：v2.5.1

**复现步骤**  切换模型时无法使用poe付费模型

**预期行为**  
支持付费模型

**截图**  
<img width="934" alt="image" src="https://github.com/lss233/chatgpt-mirai-qq-bot/assets/61567631/57146182-3a16-4c06-ae31-d803df0b4c29">

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by Cloxl** [comment]
已经修复请看这个[PR](https://github.com/lss233/chatgpt-mirai-qq-bot/pull/899)
