### ISSUE TITLE
[求助] 账号被风控 仅私聊可用

### ISSUE THREAD

**Issue by singularity2000** [lss233/chatgpt-mirai-qq-bot#896]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [√] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：Win10 和 Win11 （2个设备）
- Docker： ？
- 项目版本：2.5.1

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 运行机器人
2. 群友正常与其互动
3. 突然不回复消息
4. 查看控制台发现下图警报（bot正常响应但发不出）
5. 尝试重启chatgpt和QQ端无效；更换代理节点无效；更换设备运行无效
6. 私聊发消息能正常回复，该账号无任何被封迹象或人机验证

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/61232355/f39c5374-cf37-4b5e-ad9e-1990ea5990fc)
![Z7I{@1L%P4XISYNH4(7 D}2](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/61232355/6e089376-0a66-470c-b153-1660d5d69668)

**其他内容**  
故障出现后，**私聊发消息能正常回复，该账号登录QQ客户端后，能正常手动在群内发言**
从最初安装到现在，每次启动cqhttp都会有一行黄色英语警报：Protocol -> device lock is disable. http api may fail.

**Comment by wangji1231234** [comment]
去gocq反应

**Comment by imRhoAias** [comment]
教你，去把登录验证勾上，然后把QQ密码改下，再用最新的那个gocq默认设备6（Android pad)密码登录，然后手机验证🐎就行了，另，尽量别再用手机登录那个号，容易把服务器上的挤掉

**Comment by xinjingshun** [comment]
> 教你，去把登录验证勾上，然后把QQ密码改下，再用最新的那个gocq默认设备6（Android pad)密码登录，然后手机验证🐎就行了，另，尽量别再用手机登录那个号，容易把服务器上的挤掉

请问,如何配置gocq,修改默认设备?

**Comment by wangji1231234** [comment]
没用，我刚测试过了，在重置了密码且用pad协议登录成功以后，还是提示风控无法发送


&nbsp;


奇迹？？？？？
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月3日(星期六) 晚上7:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lss233/chatgpt-mirai-qq-bot] [求助] 账号被风控 仅私聊可用 (Issue #896)





  
教你，去把登录验证勾上，然后把QQ密码改下，再用最新的那个gocq默认设备6（Android pad)密码登录，然后手机验证🐎就行了，另，尽量别再用手机登录那个号，容易把服务器上的挤掉
  
请问,如何配置gocq,修改默认设备?

**Comment by wangji1231234** [comment]
奇迹？？？？？
***@***.***



&nbsp;


现在私聊都不行了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lss233/chatgpt-mirai-qq-bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月3日(星期六) 晚上7:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lss233/chatgpt-mirai-qq-bot] [求助] 账号被风控 仅私聊可用 (Issue #896)





  
教你，去把登录验证勾上，然后把QQ密码改下，再用最新的那个gocq默认设备6（Android pad)密码登录，然后手机验证🐎就行了，另，尽量别再用手机登录那个号，容易把服务器上的挤掉
  
请问,如何配置gocq,修改默认设备?

**Comment by imRhoAias** [comment]
> 没用，我刚测试过了，在重置了密码且用pad协议登录成功以后，还是提示风控无法发送 &nbsp; 奇迹？？？？？ ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年6月3日(星期六) 晚上7:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [lss233/chatgpt-mirai-qq-bot] [求助] 账号被风控 仅私聊可用 (Issue #896) 教你，去把登录验证勾上，然后把QQ密码改下，再用最新的那个gocq默认设备6（Android pad)密码登录，然后手机验证🐎就行了，另，尽量别再用手机登录那个号，容易把服务器上的挤掉 请问,如何配置gocq,修改默认设备? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
阿哲。我用这个方法挺好的，，，，

**Comment by chuxichan** [comment]
> 

我改成6之后，提示要配置密码，不能扫二维🐎怎么搞

**Comment by chuxichan** [comment]
> 教你，去把登录验证勾上，然后把QQ密码改下，再用最新的那个gocq默认设备6（Android pad）密码登录，然后手机验证🐎就进行了，另外，尽管量别再用手机登录那个号码，容易把服务器上的拔掉

我改成6之后，提示要配置密码，不能扫二维🐎怎么搞

**Comment by imRhoAias** [comment]
> > 教你，去把登录验证勾上，然后把QQ密码改下，再用最新的那个gocq默认设备6（Android pad）密码登录，然后手机验证🐎就进行了，另外，尽管量别再用手机登录那个号码，容易把服务器上的拔掉
> 
> 我改成6之后，提示要配置密码，不能扫二维🐎怎么搞
目前能扫码的就只有手表，6是androd pad 肯定扫不了，你把设备验证开了再把密码改一下，然后用最新版的gocq配置密码账号直接运行就行了，默认的设备就是6，我用这个方法还是挺好使的，你们可以试试

**Comment by singularity2000** [comment]
> 教你，去把登录验证勾上，然后把QQ密码改下，再用最新的那个gocq默认设备6（Android pad)密码登录，然后手机验证🐎就行了，另，尽量别再用手机登录那个号，容易把服务器上的挤掉

想问下大佬登录验证在哪里？是不是我截图里的那个“安全登录检查”开关？gocq的默认设备怎么修改呢，或者有无对应教程

**Comment by imRhoAias** [comment]
> > 教你，去把登录验证勾上，然后把QQ密码改下，再用最新的那个gocq默认设备6（Android pad)密码登录，然后手机验证🐎就行了，另，尽量别再用手机登录那个号，容易把服务器上的挤掉
> 
> 想问下大佬登录验证在哪里？是不是我截图里的那个“安全登录检查”开关？gocq的默认设备怎么修改呢，或者有无对应教程
私密马赛，就是那个检查，gocq一般默认就是设备6把，直接·默认不用改的

**Comment by lss233** [comment]
此问题为 go-cqhttp 或 mirai 问题，与本项目无关，请勿在此发 issue。
