### ISSUE TITLE
[Feature] 是否有计划支持EdgeGPT

### ISSUE THREAD

**Issue by TingoLee** [lss233/chatgpt-mirai-qq-bot#90]
https://github.com/acheong08/EdgeGPT 已经有相关API，未来能否支持EdgeGPT

**Comment by lss233** [comment]
有。

**Comment by lss233** [comment]
目前来看它寄了，这事先缓缓吧。

**Comment by lss233** [comment]
都一周多了，我还是没 EdgeGPT 的内测，而且 bing 也被砍了……

**Comment by TingoLee** [comment]
我昨天触发daily limit后，已经过了24小时，还是无法访问。bing目前基本不可用。

**Comment by lss233** [comment]
v2.0 已支持
