### ISSUE TITLE
[BUG] 机器人微信发送语音为MP3文件而不是语音对话，群聊不回复语音

### ISSUE THREAD

**Issue by cernard** [lss233/chatgpt-mirai-qq-bot#900]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
机器人微信发送语音为MP3文件而不是语音对话，群聊不发送语音消息作为回复

**运行环境:**  
- 操作系统：ubuntu 22.04
- Docker： 20.10.21
- 项目版本：最新

**复现步骤**  
微信私聊机器人，正常响应发回文字和语音，不过语音是mp3文件而不是语音消息
群聊@机器人，正常响应发回文字回复，但是不发送mp3或语音消息。

**预期行为**  
1. 最好发回的是微信标准的语音消息
2. 微信和群聊都应该发送mp3或语音消息

**Comment by lss233** [comment]
不支持语音。

**Comment by zhiyixu** [comment]
discord 可以支持发送 语音消息吗？ 不是mp3 文件

**Comment by lss233** [comment]
discord 不能发语音

**Comment by zhiyixu** [comment]
了解， 谢谢
