### ISSUE TITLE
[BUG] Poe不可用，字典为空，找不到bot名称

### ISSUE THREAD

**Issue by jiaigo** [lss233/chatgpt-mirai-qq-bot#901]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
找不到对应的poe bot，昨天还是可以显示的，有a2，chinchilla这些key，但是今早出bug，字典为空？请问有可能是什么原因导致？
（cookies没变，poe账号是可用的）

**运行环境:**  
- 操作系统：ubuntu 20.04
- Docker：20.10.22
- 项目版本：docker-compose pull && docker-compose up ，早上已删掉容器和镜像，重试后问题依旧

![20230531121800](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/42903140/fa15dd02-3b60-44d9-817a-8bbd2d75f0c8)

**Comment by Cloxl** [comment]
poe库的问题

**Comment by jiaigo** [comment]
是的，更新到pip install poe-api==0.4.3，问题解决，未见异常，暂不确定其他依赖是否受影响

**Comment by Cloxl** [comment]
> @Cloxl 是的，更新到pip install poe-api==0.4.3，问题解决，未见异常，暂不确定其他依赖是否受影响

恭喜 现在你可以关掉issue了

**Comment by lanybass** [comment]
docker什么时候更新？怎么给docker里面安装0.4.3?

**Comment by Cloxl** [comment]
> docker什么时候更新？怎么给docker里面安装0.4.3?

下个版本支持 目前请你询问gpt怎么更新 或者等群主更新docker版本

**Comment by Cloxl** [comment]
群主已经在最新的代码中 加入了poe最新版 再下个版本更新前 如果不能使用 请手动更新poe-api库大于等于0.4.3版本
