### ISSUE TITLE
希望加入讯飞星火，星火在某些方面还是比chatgpt强的，我看比别的项目已经支持了

### ISSUE THREAD

**Issue by huangzhitian** [lss233/chatgpt-mirai-qq-bot#906]
看到你在群里说星火加密了什么，没加入，群主可以看看别人的项目
别人的项目地址https://github.com/canxin121/Spark-GPT
对你来说应该不难，望加入
![QQ截图20230601231406](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/129321746/ba7a347d-e43e-4874-980e-be7708fa7e27)

**Comment by lss233** [comment]
已发布。
