### ISSUE TITLE
今天一觉起来mirai就登陆不上了 code=45

### ISSUE THREAD

**Issue by Nothingness-Void** [lss233/chatgpt-mirai-qq-bot#908]
如题 吃着火锅唱着歌，忽然就掉线了然后提示版本过低
`2023-06-02 12:07:42 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2924181640), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)`

**Comment by AlexMason2077** [comment]
是这样的，我几个星期前就遇到这个问题登不进去了

**Comment by DUXING130** [comment]
> 如题 吃着火锅唱着歌，忽然就掉线了然后提示版本过低 `2023-06-02 12:07:42 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2924181640), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)`

风控，自己去解除，跟此处项目无关

**Comment by Nothingness-Void** [comment]
> > 如题 吃着火锅唱着歌，忽然就掉线了然后提示版本过低 `2023-06-02 12:07:42 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2924181640), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)`
> 
> 风控，自己去解除，跟此处项目无关

想问问大佬怎么解，我换cq-http登录能够登录上，但是发不出消息，发消息就提示`发送失败，账号可能被风控`

**Comment by DUXING130** [comment]
> > > 如题 吃着火锅唱着歌，忽然就掉线了然后提示版本过低 `2023-06-02 12:07:42 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2924181640), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)`
> > 
> > 
> > 风控，自己去解除，跟此处项目无关
> 
> 想问问大佬怎么解，我换cq-http登录能够登录上，但是发不出消息，发消息就提示`发送失败，账号可能被风控`

用真实设备登陆机器人账号几天，正常聊天应该很快就会解除，然后使用Mirai的话，论坛会有讨论提示具体方法。
https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88

**Comment by Nothingness-Void** [comment]
> > > > 如题 吃着火锅唱着歌，忽然就掉线了然后提示版本过低 `2023-06-02 12:07:42 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2924181640), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)`
> > > 
> > > 
> > > 风控，自己去解除，跟此处项目无关
> > 
> > 
> > 想问问大佬怎么解，我换cq-http登录能够登录上，但是发不出消息，发消息就提示`发送失败，账号可能被风控`
> 
> 用真实设备登陆机器人账号几天，正常聊天应该很快就会解除，然后使用Mirai的话，论坛会有讨论提示具体方法。 https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88

我这号一直在我备用机（安卓）上登录 我感觉应该就是昨天日子比较那啥 腾讯最近查的严了 过去了就好了
