### ISSUE TITLE
[Feature] gpt-4-browsing and gpt-4-plugins

### ISSUE THREAD

**Issue by bbpp222006** [lss233/chatgpt-mirai-qq-bot#909]
gpt plus 会员已经可以使用上网等插件，在 https://github.com/acheong08/ChatGPT 中已经提供支持，请求增加这部分功能。

**Comment by Nothingness-Void** [comment]
> gpt plus 会员已经可以使用上网等插件，在 https://github.com/acheong08/ChatGPT 中已经提供支持，请求增加这部分功能。

配置文件中有这么一栏
`# 如果你是 Plus 用户，加入这一条，否则无法切换至 plus 模型 
paid=true
# 这里填写的内容由你的代理服务器提供
model="gpt-4-mobile"`
尝试把model 里面的值改成 gpt-4-plugins 和 gpt-4-browsing试试
