### ISSUE TITLE
刚开始还用的好好的，突然就报错了

### ISSUE THREAD

**Issue by mlpxt** [lss233/chatgpt-mirai-qq-bot#913]
**提交 issue 前，请先确认：**
- [ ] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
描述 BUG 的表现情况

**运行环境:**  
- 操作系统：win 10
- 项目版本：Windows-quickstart-go-cqhttp-refs.tags.v2.5.1

**复现步骤**  
描述你是如何触发这个 BUG 的
QQ聊天群里面正常使用的时候突然出现了报错，然后就一直无法发出会话。
使用私人的QQ进行聊天的时候一切正常，但是群聊无法正常使用。

**预期行为**  
正常应该会进行回复，现在cmd工具里面存在一大堆的报错。

**截图**  
![图片](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/108312263/e7e3aced-f184-482e-bdc8-f9c7f186fb49)

**其他内容**  
[触发的问题的报错.txt](https://github.com/lss233/chatgpt-mirai-qq-bot/files/11641733/default.txt)

我将报错信息进行复制到一个txt文本里面，希望可以有用。

**Comment by mlpxt** [comment]
chatGPT的对话可以进行正常回复，但是在QQ群里面无法看到任何看到任何回复，是否是在传输的过程中出现了问题。
![图片](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/108312263/fef8fd71-cb28-47e6-8223-bba77aa42dc3)

**Comment by Cloxl** [comment]
虽然你没有提供gocqhttp的日志 但是我能猜到 你gocqhttp的日志报错内容为:   
```
消息发送失败 账号可能被风控  
```

这个其实就是近期腾讯加强了风控 群聊发信息有问题 私聊没有 具体请前往gocqhttp的仓库 查阅相关issue

**Comment by mlpxt** [comment]
可以提供一下gocqhttp的链接吗

**Comment by Cloxl** [comment]
看[这个](https://github.com/Mrs4s/go-cqhttp/issues/2183)

**Comment by Cloxl** [comment]
可以close issue了
