### ISSUE TITLE
linux登录错误“你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证”

### ISSUE THREAD

**Issue by 854524301** [lss233/chatgpt-mirai-qq-bot#920]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/52943070/1191e007-2dd7-4b0d-94e1-2fb395a7fd55)

**运行环境:**  
- 操作系统：？
- Docker： ？
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 一键配置
2. sudo运行程序
3. 手动滑动滑块

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
相关日志、聊天记录的截图，没有可跳过

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by 854524301** [comment]
手机端无任何信息弹出，更改配置文件为扫码，提示扫码不支持。

**Comment by imRhoAias** [comment]
你可以试试勾选安全登录然后改密码然后本地用gocq填写账号密码默认设备六手机验证码登录，然后搬文件到服务器，我是这样处理风控的，稳定三四天了，没再遇到过其他账号问题了，你可以试试

**Comment by 854524301** [comment]
我现在是直接微信那边申请接触非常用看看，我晚上回去试试大佬推荐的方法，感谢大佬的回复





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lss233/chatgpt-mirai-qq-bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月6日(星期二) 中午1:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lss233/chatgpt-mirai-qq-bot] linux登录错误“你的账号涉嫌违规被限制在非常用设备登录, 请在手机QQ登录并根据提示完成认证” (Issue #920)





 
你可以试试勾选安全登录然后改密码然后本地用gocq填写账号密码默认设备六手机验证码登录，然后搬文件到服务器，我是这样处理风控的，稳定三四天了，没再遇到过其他账号问题了，你可以试试
