### ISSUE TITLE
[Feature] 兼容OICQ框架

### ISSUE THREAD

**Issue by d4renk** [lss233/chatgpt-mirai-qq-bot#924]
在 QQ 群聊被风控情况下，使用 [Icalingua-plus-plus](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus) 仍可通过 [FIX](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/tree/develop/icalingua-bridge-oicq) 协议发送群聊消息。Icalingua-plus-plus 使用 [OICQ](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/tree/develop/icalingua-bridge-oicq) 作为其底层通信协议。 
[OICQ 仓库](https://github.com/takayama-lily/oicq)

**Comment by lss233** [comment]
本项目只是一个面向即时聊天工具的机器人平台。  
你所使用的接入 QQ 平台的能力是通过 OneBot、mirai api http 或者项目中的其他形式提供的接口连接到某种第三方 QQ 客户端实现的。  
项目本身与 QQ 协议本身并无任何关系，并且项目也没有计划参与 QQ 协议的逆向破解。  
你在使用过程中遇到群聊风控也与我没有关系，你应该联系的是第三方 QQ 客户端的作者，而不是我。

 如果你觉得 OICQ 好用，你可以找一个使用 OICQ 并且支持本项目所对外协议（如 OneBot 协议）的第三方 QQ 客户端。
