### ISSUE TITLE
sudo docker-compose up报错

### ISSUE THREAD

**Issue by coolbiubiu** [lss233/chatgpt-mirai-qq-bot#93]
![image](https://user-images.githubusercontent.com/42194590/218245717-a56e14fa-eac1-4f3a-a467-9372592dda53.png)
请执行：sudo apt install dbus-x11  解决

![image](https://user-images.githubusercontent.com/42194590/218245677-afc141ee-28da-4f4a-b6d1-6efeb0131a4e.png)
请执行：sudo apt install gnupg2 pass  解决

**Comment by lss233** [comment]
这应该是你服务器缺了什么环境吧
