### ISSUE TITLE
[BUG] 无法登录open ai账号

### ISSUE THREAD

**Issue by beizhaibei** [lss233/chatgpt-mirai-qq-bot#930]
无法登录open ai账号，登录方式access_token

**运行环境:**  
- 操作系统：windows
- Docker： ？
- 项目版本：v2.51

**截图**  
![QQ截图20230607233935](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/89172126/a5bc6401-59d4-47fa-b71e-263bf787d79c)

**Comment by Nothingness-Void** [comment]
> 无法登录open ai账号，登录方式access_token
> 
> **运行环境:**
> 
> * 操作系统：windows
> * Docker： ？
> * 项目版本：v2.51
> 
> **截图** ![QQ截图20230607233935](https://user-images.githubusercontent.com/89172126/244122291-a5bc6401-59d4-47fa-b71e-263bf787d79c.png)

我解决了 请参考 https://github.com/lss233/chatgpt-mirai-qq-bot/issues/929#issuecomment-1581002399

**Comment by imRhoAias** [comment]
我也是这个问题

**Comment by lss233** [comment]
已恢复
