### ISSUE TITLE
[BUG] poe解析失败

### ISSUE THREAD

**Issue by imRhoAias** [lss233/chatgpt-mirai-qq-bot#931]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
无法登录poe

**运行环境:**  
- 操作系统：win2012r2
- Docker： ？
- 项目版本：？

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/133833496/042a86d0-731b-44b4-a182-237bcffec341)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by linxp001** [comment]
我也遇到同样的问题，不过其它没重启过的还能用poe，现在都不敢重启了。

**Comment by xiaosatai** [comment]
相同问题+1
服务器位于美国
系统为Debian GNU/Linux 10 x86_64(Py3.7.9)
配置方式为 docker部署
出现的问题也是解析失败
<img width="1001" alt="微信截图_20230608112814" src="https://github.com/lss233/chatgpt-mirai-qq-bot/assets/44671057/d0d0d343-d4da-4d07-88b6-be17e8cd8c98">

**Comment by QiYorkkk** [comment]
+1，gpt4读的日志
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/93068569/9d9eb31f-f38c-4182-b31d-b8da800ba4fc)

**Comment by jiaigo** [comment]
应该是poe问题，web端退出后也登不进：
Something went wrong. Please wait a moment and try again.

**Comment by L-Lynxu** [comment]
同样的问题

**Comment by Elijah-0616** [comment]
# https://github.com/ading2210/poe-api/issues/105
# https://github.com/ading2210/poe-api/issues/108

**Comment by Elijah-0616** [comment]
已提交PR修复，等待合并 :)
