### ISSUE TITLE
[BUG] docker部署无法连接至本地代理服务器

### ISSUE THREAD

**Issue by Konjac-wjh** [lss233/chatgpt-mirai-qq-bot#933]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
docker部署项目无法通过代理测试

**运行环境:**  
- 操作系统：Ubuntu 22.04
- Docker： Docker Compose version v2.18.1
- 项目版本：v2.5.1

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 配置config.cfg(截图在下面), 已将proxy替换为宿主机地址
2. 配置docker-compose.yaml
3. docker-compose restart

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
阿里云的实例使用clashshell代理, 代理可以正常使用
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/70873609/110793cf-7404-495e-9ce1-87502e96f710)

config.cfg:
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/70873609/2dfebfc5-c119-4757-84af-ff3731b2126a)

docker-compose.yaml
`
version: '3.4'
services:
#  gocqhttp:
#    image: silicer/go-cqhttp:latest
#    restart: always
#    environment:
#      LANG: 'C.UTF-8'
#    volumes:
#      - ./gocqhttp/:/data/
  chatgpt:
    image: lss233/chatgpt-mirai-qq-bot:browser-version
    restart: always
    environment:
      LANG: 'C.UTF-8'
    ports:
      - 8554:8554/tcp
    volumes:
      - ./config.cfg:/app/config.cfg
      - ./data:/app/data
      - ./presets:/app/presets
      # - ./fonts:/app/fonts # 如果你想自定义字体，就解除注释
  watchtower: # [可选] 自动更新
    image: containrrr/watchtower
    volumes: # 如果启动失败，请修改下面这条：
      
`

报错信息
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/70873609/49ec8a79-87ce-4204-8a94-7a020d2e3546)

**Comment by Konjac-wjh** [comment]
docker-compose.yaml:

**Comment by Konjac-wjh** [comment]
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/70873609/67ee76ea-674c-4bad-b70d-c96cf6576960)

**Comment by you-not-fish** [comment]
把proxy改为127.0.0.1:7890试试？检查一下出站入站规则有没有配置正确

**Comment by Konjac-wjh** [comment]
> 把proxy改为127.0.0.1:7890试试？检查一下出站入站规则有没有配置正确

有试过将proxy改为127.0.0.1:7890, 报错依旧:
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/70873609/f000103b-0290-48e9-a27e-2004bbc1ce67)
出入站规则也有放行本项目的8554和clash的7890
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/70873609/238b22d5-a15b-4acb-b235-d0ee7b89668f)

**Comment by L-Lynxu** [comment]
理论上来说不应该使用127.0.0.1，楼主的设置是正确的，是不是clash没有开启lan？

**Comment by L-Lynxu** [comment]
运行
```
docker network inspect chatgpt-mirai-qq-bot_default
```
看看容器所在的虚拟网，然后把地址改成这个虚拟网地址试一下？端口还是clash的7890

**Comment by Konjac-wjh** [comment]
问题解决了, 如果有同样是docker部署的朋友遇到问题可以参考

**Comment by wnagDouble** [comment]
我也遇到了这个问题。和楼主一样。解决了太好了。
