### ISSUE TITLE
[BUG] Server error '523 ' for url 'https://chatgpt-proxy.lss233.com/claude-in-slack/backend-api/conversation'

### ISSUE THREAD

**Issue by tozmart** [lss233/chatgpt-mirai-qq-bot#934]
claude貌似失效了
Server error '523 ' for url 'https://chatgpt-proxy.lss233.com/claude-in-slack/backend-api/conversation'

**Comment by L-Lynxu** [comment]
同样的错误，刚刚出现的

**Comment by linxp001** [comment]
同样的错误

**Comment by tozmart** [comment]
参照这个https://github.com/LlmKira/claude-in-slack-server，自己部署了一个。

**Comment by tozmart** [comment]
参照下面链接，自己部署了一个
https://github.com/LlmKira/claude-in-slack-server

**Comment by linxp001** [comment]
貌似现在已经恢复了
