### ISSUE TITLE
[BUG] poe 描述不统一

### ISSUE THREAD

**Issue by a2292509814** [lss233/chatgpt-mirai-qq-bot#937]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [ ] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
在文档中，poe Chatgpt显示为poe-chinchilla，在运行提示中，显示为poe-chatgpt，同时无法在配置两者时正常运行

**运行环境:**  
- 操作系统：Windows
- Docker： None
- 项目版本：2.51

**复现步骤**  
描述你是如何触发这个 BUG 的
设置default_ai为poe的chatgpt

**Comment by lufenghuai** [comment]
poe是指添加了Claude嘛，我好像遇到了同样的问题

**Comment by a2292509814** [comment]
> 
是的

**Comment by lss233** [comment]
那就统一用 poe-chatgpt 吧， 我改下文档
