### ISSUE TITLE
[BUG] string indices must be integers, not 'str' 错误码254

### ISSUE THREAD

**Issue by Mika-LiFeng** [lss233/chatgpt-mirai-qq-bot#938]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
OPEN AI 账号登录失败，py脚本执行报错

**运行环境:**  
- 操作系统：linux ubuntu
- Docker： 23.0.2
- 项目版本：2.5最新版

**复现步骤**  
描述你是如何触发这个 BUG 的

**预期行为**  
之前可以正常允许，更新到最新版本后，使用的是扫码登录，qq已登录成功。OPEN AI账号token已更新，但是无法登录成功

**截图**  
![图片](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/33191871/58abce9e-35a7-4ceb-a0d4-96c5ab08c2e4)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by G37H9** [comment]
#929

**Comment by Mika-LiFeng** [comment]
no ,我试过替换token，已经是最新的了，不是这个问题

**Comment by Mika-LiFeng** [comment]
> #929
no ,我试过替换token，已经是最新的了，不是这个问题

**Comment by G37H9** [comment]
那你再看看这个把   应该是接入点的问题吧
#932

**Comment by Mika-LiFeng** [comment]
> 那你再看看这个把 应该是接入点的问题吧 #932
 OK，使用新的接入点后，已成功登录，3Q
[openai]
browserless_endpoint="http://us.nothingnessvoid.tech:8080/chatgpt/"
