### ISSUE TITLE
[BUG] Chinese (Simplified)-China is an invalid culture identifier.

### ISSUE THREAD

**Issue by pzzmyc** [lss233/chatgpt-mirai-qq-bot#942]
- [x] 我已看过 **FAQ**，此问题不在列表中
**运行环境:**  
- 操作系统：windows
- 项目版本：.v2.5.2

**复现步骤**  
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/43562427/bc9802c1-108a-4f48-8d7c-4a92124fc410)

![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/43562427/03fbc5fa-2d2b-4033-ba6d-266f7616f666)

**Comment by Qmymy** [comment]
我也是bing报错，不支持中国地区的文化检索，回复你好这些是正常的，我使用2.5.1版本的话bing是正常的。但是2.5.1版本的bing就像是被阉割了一样，很多网页或者APP上面能回答的问题，到了2.5.1版本对接后的bing却不能回答了，bing会说没有找到这个问题。![mmexport1686462619747.png](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/129690756/8968f76e-fbda-4512-8800-5952aeb4c18b)

**Comment by pzzmyc** [comment]
> 我也是bing报错，不支持中国地区的文化检索，回复你好这些是正常的，我使用2.5.1版本的话bing是正常的。但是2.5.1版本的bing就像是被阉割了一样，很多网页或者APP上面能回答的问题，到了2.5.1版本对接后的bing却不能回答了，bing会说没有找到这个问题。![mmexport1686462619747.png](https://user-images.githubusercontent.com/129690756/244916057-8968f76e-fbda-4512-8800-5952aeb4c18b.png)

那好像是bing的问题，我来晚了吗😢,头次使用就碰到这鸟问题，我还以为是梯子不好

**Comment by Qmymy** [comment]
> 鸟

2.5.1版本能够正常使用bing，但是bing会有些智障，如果你只使用bing的话，你可以退回版本使用

**Comment by pzzmyc** [comment]
> > 鸟
> 
> 2.5.1版本能够正常使用bing，但是bing会有些智障，如果你只使用bing的话，你可以退回版本使用

那我俩问题可能不太一样，我压根用不了

**Comment by lss233** [comment]
可以先试下按下面的方法进行修改：
https://github.com/lss233/chatgpt-mirai-qq-bot/commit/5b4b6ab0ab6b5044313e04d2de363e5ae296cf89

**Comment by pzzmyc** [comment]
> 可以先试下按下面的方法进行修改： [5b4b6ab](https://github.com/lss233/chatgpt-mirai-qq-bot/commit/5b4b6ab0ab6b5044313e04d2de363e5ae296cf89)

泰酷辣，问题解决

**Comment by FFFKLD** [comment]
> 

更改后可以减少报错概率，但问题内容稍微涉及中国，又会开始报错，比如安徽的车牌号有哪些

**Comment by FFFKLD** [comment]
> 可以先试下按下面的方法进行修改： [5b4b6ab](https://github.com/lss233/chatgpt-mirai-qq-bot/commit/5b4b6ab0ab6b5044313e04d2de363e5ae296cf89)

更改后可以减少报错概率，但问题内容稍微涉及中国，又会开始报错，比如安徽的车牌号有哪些

**Comment by Nothingness-Void** [comment]
改完说你好能回复，问题长点就报错
