### ISSUE TITLE
linux客户端在发信息是发生错误

### ISSUE THREAD

**Issue by 2048556128** [lss233/chatgpt-mirai-qq-bot#95]
**在我搭建好了之后，我给机器人QQ发送信息然后就报错输出这些，并在QQ上回复我这个“出现故障！如果这
个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。\nWrong response code: 400! Refreshing session...”
一下是发送信息之后服务器报错信息：**

```
onse code: 400! Refreshing session...
mirai_1    | 2023-02-11 09:27:22 V/Bot.2111633287: 咳咳(2048556128) -> 重置会话
chatgpt_1  | 2023-02-11 09:27:22.773 | INFO     | graia.ariadne.model:log:83 - 2111633287: [RECV][咳咳(2048556128)] -> 重置会话
chatgpt_1  | 2023-02-11 09:27:22.775 | DEBUG    | chatbot:initial_process:144 - 初始化处理中...
mirai_1    | 2023-02-11 09:27:23 V/Bot.2111633287: Friend(2048556128) <- [mirai:quote:[mirai:source:ids=[34585], internalIds=[1056274531], from friend 2048556128 to 2111633287 at 1676107642], content=重置会话]会话已重置。
chatgpt_1  | 2023-02-11 09:27:23.294 | INFO     | graia.ariadne.model:log:83 - 2111633287: [SEND][咳咳(2048556128)] <- 会话已重置。
mirai_1    | 2023-02-11 09:27:28 V/Bot.2111633287: 咳咳(2048556128) -> 哈喽
chatgpt_1  | 2023-02-11 09:27:28.133 | INFO     | graia.ariadne.model:log:83 - 2111633287: [RECV][咳咳(2048556128)] -> 哈喽
chatgpt_1  | 2023-02-11 09:27:29.194 | ERROR    | __main__:handle_message:75 - Wrong response code: 400! Refreshing session...
chatgpt_1  | Traceback (most recent call last):
chatgpt_1  | 
chatgpt_1  |   File "/app/bot.py", line 83, in friend_message_listener
chatgpt_1  |     response = await handle_message(friend, f"friend-{friend.id}", chain.display, source)
chatgpt_1  |                      │              │                              │     │        └ Source(id=34586, time=datetime.datetime(2023, 2, 11, 9, 27, 27, tzinfo=datetime.timezone.utc), type='Source')
chatgpt_1  |                      │              │                              │     └ <property object at 0x7efec6a542c0>
chatgpt_1  |                      │              │                              └ MessageChain([Plain(text='哈喽')])
chatgpt_1  |                      │              └ Friend(id=2048556128, nickname='咳咳', remark='咳咳')
chatgpt_1  |                      └ <function handle_message at 0x7efe8a467ee0>
chatgpt_1  | 
chatgpt_1  | > File "/app/bot.py", line 67, in handle_message
chatgpt_1  |     resp = await session.get_chat_response(message)
chatgpt_1  |                  │       │                 └ '哈喽'
chatgpt_1  |                  │       └ <function ChatSession.get_chat_response at 0x7efe987c5f70>
chatgpt_1  |                  └ <chatbot.ChatSession object at 0x7efe8a41bb20>
chatgpt_1  | 
chatgpt_1  |   File "/app/chatbot.py", line 110, in get_chat_response
chatgpt_1  |     final_resp = await loop.run_in_executor(None, bot.ask, message)
chatgpt_1  |                        │    │                     │   │    └ '哈喽'
chatgpt_1  |                        │    │                     │   └ <function Chatbot.ask at 0x7efec40f8f70>
chatgpt_1  |                        │    │                     └ <chatbot.mChatbot object at 0x7efec40fa400>
chatgpt_1  |                        │    └ <function BaseEventLoop.run_in_executor at 0x7efec7d40280>
chatgpt_1  |                        └ <_UnixSelectorEventLoop running=True closed=False debug=False>
chatgpt_1  | 
chatgpt_1  |   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
chatgpt_1  |     result = self.fn(*self.args, **self.kwargs)
chatgpt_1  |              │        │            └ None
chatgpt_1  |              │        └ None
chatgpt_1  |              └ None
chatgpt_1  |   File "/usr/local/lib/python3.9/site-packages/revChatGPT/Unofficial.py", line 160, in ask
chatgpt_1  |     raise HTTPError(
chatgpt_1  |           └ <class 'requests.exceptions.HTTPError'>
chatgpt_1  | 

```

**对了这是用一键脚本搭建的：[https://github.com/paradox8599/mirai-chatgpt-setup](url)**

**Comment by lss233** [comment]
session_token 登录的？

**Comment by 2048556128** [comment]
> 

是的，今天上午还可以，下午就不行了

**Comment by lss233** [comment]
那你刷新 session_token 了吗？

**Comment by 2048556128** [comment]
> 那你刷新session_token了吗？

刷新了，然后我重新填token，重启容器都没用，最后我把所有文件删了，重新从github上拉下来，也这样。

**Comment by lss233** [comment]
这就是你的 session_token 问题。你获取 session_token 的 IP 和客户端的 IP 一样吗？
有没有用过邮箱登录？

**Comment by 2048556128** [comment]
> 

我之前可以用，然后换了别人升级plus的session-token就那样了，改回自己的也不行了，我一直用自动登录的那个token，是输入邮箱密码登录的，没有用快捷登录，登录上去我就没开vpn了

**Comment by 2048556128** [comment]
> 这就是你的 session_token 问题。你获取 session_token 的 IP 和客户端的 IP 一样吗？ 有没有用过邮箱登录？

我用改cookie工具把session_token值更改了可以登录进去

**Comment by 2048556128** [comment]
> 这就是你的 session_token 问题。你获取 session_token 的 IP 和客户端的 IP 一样吗？ 有没有用过邮箱登录？

我在qq里发信息，他回复让回滚对话和重置会话，我重置对话qq里显示成功但是网页上没有显示新的会话，回滚对话也显示那个报错

**Comment by 2048556128** [comment]
> 这就是你的 session_token 问题。你获取 session_token 的 IP 和客户端的 IP 一样吗？ 有没有用过邮箱登录？

我用那台服务器ip不能用用户名密码登录，那对用session_token登录也是会被限制的吗?

**Comment by deadnessking** [comment]
同样的问题，同PLUS账户，不过我用的是账号密码登录
![image](https://user-images.githubusercontent.com/40329411/218320619-304f5587-f944-4ce9-a9a7-168bdd7c6759.png)

**Comment by deadnessking** [comment]
刚看到后面多了个报错
2023-02-12 15:31:51,829 HTML5 client 1 disconnected.
OverflowError: can't convert negative value to unsigned long
Exception ignored in: 'xpra.x11.bindings.core_bindings.X11CoreBindingsInstance.xatom'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/x11/gtk_x11/send_wm.py", line 33, in send_wm_take_focus
    X11Window.sendClientMessage(xid, xid, False, 0,
OverflowError: can't convert negative value to unsigned long

**Comment by lss233** [comment]
有没有可能，是plus账号的问题？

**Comment by 2048556128** [comment]
> 有没有可能，是plus账号的问题？

我用普通账号新的token，直接不回复我了，可以正常接收信息
![Screenshot_2023-02-12-22-44-46-235_com sonelli juicessh](https://user-images.githubusercontent.com/68473229/218349117-de4484d5-33d8-432b-8cf4-fdc50f3025d4.jpg)
是不是没有对接上，反复试了好几遍，有什么解决方法

**Comment by Cold-Stars** [comment]
我的问题很类似，“出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。\nThat model does not exist”。
用的aip版。
![image](https://user-images.githubusercontent.com/113192545/218997852-39ea107a-d173-4fa7-a02b-cf828c894394.png)
![image](https://user-images.githubusercontent.com/113192545/218998366-4038813b-97af-4aad-bea4-89a2fac58fca.png)

**Comment by lss233** [comment]
> 我的问题很类似，“出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚对话” 来回溯到上一条对话，你上一条说的我就当作没看见。\nThat model does not exist”。 用的aip版。 ![image](https://user-images.githubusercontent.com/113192545/218997852-39ea107a-d173-4fa7-a02b-cf828c894394.png) ![image](https://user-images.githubusercontent.com/113192545/218998366-4038813b-97af-4aad-bea4-89a2fac58fca.png)

**看置顶 ISSUE**

**Comment by deadnessking** [comment]
我的PLUS账号已经没问题了，网页版能用。api版本来也能用，只是不想用gpt3.

**Comment by evanzing** [comment]
请问这个一键布置在ubuntu后,退出ssh窗口,下一次该怎么重新启动机器人呢

**Comment by maxage** [comment]
![image](https://user-images.githubusercontent.com/42706238/219759354-e6084e6f-7091-466a-b4c4-d889bd5870c4.png)
一路错误。

**Comment by lss233** [comment]
> ![image](https://user-images.githubusercontent.com/42706238/219759354-e6084e6f-7091-466a-b4c4-d889bd5870c4.png) 一路错误。

请不要在别人的 issue 里面发与主题无关的错误。  

你的这个错误单纯是因为你的配置文件少了内容。
