### ISSUE TITLE
qq-bot 使用stable diffusion产生不明原因错误，sd的webui卡在96%,绘图无法生成                    

### ISSUE THREAD

**Issue by qwqhahaya123** [lss233/chatgpt-mirai-qq-bot#951]
![E3F ~2228 GO`LG11P3@7G7](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/126888250/2c357477-cb85-47ae-a04d-86ffdae5c71a)

**Comment by qwqhahaya123** [comment]
![Q_%{@N_R6 F`JA$SVZBBVJ3](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/126888250/c754b7d5-5bb1-4830-9fcc-4cc120e89354)

**Comment by qwqhahaya123** [comment]
![T{C0E~PB()DGLE{8EE 39Q3](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/126888250/7a8de67b-f25e-4483-b030-16e5af652a62)

**Comment by lss233** [comment]
这里错误应该是因为超时了吧。问题可能出在sd那边。你发的日志看不出什么问题。

**Comment by lss233** [comment]
另外请按模板填写issue
