### ISSUE TITLE
[BUG] access_token登录失败

### ISSUE THREAD

**Issue by slamd14** [lss233/chatgpt-mirai-qq-bot#955]
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/105451780/7619acbc-6d53-4e3e-bf32-867a80855e85)

两张截图

![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/105451780/7d5dec43-ca3f-42ec-941a-6bf3a642d699)

**Comment by INSide-734** [comment]
[#929 (comment)](https://github.com/lss233/chatgpt-mirai-qq-bot/issues/929#issuecomment-1581002399)

**Comment by slamd14** [comment]
知道原因了，是没有获取到正确的access token
