### ISSUE TITLE
[BUG] access_token方式登录失败，所有登录方式已失效

### ISSUE THREAD

**Issue by xixilai1** [lss233/chatgpt-mirai-qq-bot#956]
**提交 issue 前，请先确认：**
- [√] 我已看过 **FAQ**，此问题不在列表中
- [√] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
chatgpt网页版，accesstoken方式登录无效

**运行环境:**  
- 操作系统：windows10
- Docker： ？
- 项目版本：v2.5.2

**复现步骤**  

**预期行为**  
描述你认为正常情况下应该看见的情况

**截图**  
![H1B{5 ({` $(EI67J0 {G8T](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/116078568/63ae4e4a-0285-4764-ab59-d898a063b70c)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by pp0915** [comment]
同问

**Comment by SuperHack0328** [comment]
+1同样的问题

**Comment by INSide-734** [comment]
试试自己搭接入点？

**Comment by INSide-734** [comment]
[#929 (comment)](https://github.com/lss233/chatgpt-mirai-qq-bot/issues/929#issuecomment-1581002399)

**Comment by 147graze** [comment]
同问

**Comment by Fuky112** [comment]
同问

**Comment by snowsno** [comment]
同问

**Comment by Matrix1127** [comment]
同问

**Comment by Nothingness-Void** [comment]
改接入点，推荐自建

**Comment by lss233** [comment]
已修复。
