### ISSUE TITLE
请问怎么获取session_token

### ISSUE THREAD

**Issue by DreamyWen** [lss233/chatgpt-mirai-qq-bot#96]
readme中的界面已经不存在了，多谢

**Comment by Mo-Qiong** [comment]
打开https://chat.openai.com/chat
F12->点网络，然后刷新，在cookie值里找到session-token="xxx"，这个xxx就是
![image](https://user-images.githubusercontent.com/87867429/218268431-f01d7f9e-911b-4cd1-8707-6ee79e59e612.png)

**Comment by Mo-Qiong** [comment]
应该是这个吧...我还没弄，明天早上再试。

**Comment by lss233** [comment]
是的

**Comment by lss233** [comment]
是的

**Comment by DreamyWen** [comment]
> 打开https://chat.openai.com/chat F12->点网络，然后刷新，在cookie值里找到session-token="xxx"，这个xxx就是 ![image](https://user-images.githubusercontent.com/87867429/218268431-f01d7f9e-911b-4cd1-8707-6ee79e59e612.png)

明白了，多谢大佬

**Comment by brianzhang** [comment]
可以去看控制台网络请求
> https://chat.openai.com/api/auth/session
的接口请求
![image](https://user-images.githubusercontent.com/766999/218617216-0ba3f658-e962-4e06-8953-40ac6bc5783d.png)
