### ISSUE TITLE
[Feature] 请求支持OpenAI的文本审核

### ISSUE THREAD

**Issue by DevHaoZi** [lss233/chatgpt-mirai-qq-bot#960]
OpenAI有一个文本审核，文档地址：[https://platform.openai.com/docs/guides/moderation/overview](https://platform.openai.com/docs/guides/moderation/overview) 

和百度相比主要优势是免费，请求添加支持。

**Comment by DevHaoZi** [comment]
> ![image](https://user-images.githubusercontent.com/120039624/246118387-ea757434-6ed0-4909-b302-c11729a98812.png) 需要OpenAI的API key?

嗯

**Comment by G37H9** [comment]
百度那边不也是免费的么和免费没区别啊

**Comment by lss233** [comment]
这个文本审核是否适用于国内场景？

**Comment by lss233** [comment]
这个文本审核不包含对政治敏感的过滤，接入后机器人还是有可能会发送会违反平台规则的消息。没什么用，不考虑支持。
