### ISSUE TITLE
[BUG] 需要升级 revchatgpt 依赖才能支持 OpenAI 0613 系列模型

### ISSUE THREAD

**Issue by 0x7c13** [lss233/chatgpt-mirai-qq-bot#965]
昨天的PR增加了0613系列模型的切换，但是切换之后对话会报错：
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/1166162/ce2f2a5a-c3a4-42e5-8e7e-0ac83b956a39)

原因是revchatgpt写死了所有支持的模型，作者昨天也添加了新的模型，所以需要更新一下依赖：
https://github.com/acheong08/ChatGPT/blob/2c15b1af512c24e81421df64090c624cc20b67f8/src/revChatGPT/V3.py#L29

他好像少加了两个模型，给他丢了一个PR，等release之后更新到6.3.2+版本就行
https://github.com/acheong08/ChatGPT/pull/1425

**Comment by 0x7c13** [comment]
PR: https://github.com/lss233/chatgpt-mirai-qq-bot/pull/967

**Comment by imRhoAias** [comment]
一键包目前只能等作者更新么
