### ISSUE TITLE
[BUG] openai账号登录失败

### ISSUE THREAD

**Issue by beizhaibei** [lss233/chatgpt-mirai-qq-bot#968]
**表现**  
access_token登录失败

**运行环境:**  
- 操作系统：windows11
- Docker： ？
- 项目版本：v2.52

**截图**  
![QQ截图20230616233216](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/89172126/93964c4a-07cb-451d-83ef-e50198260fec)

**其他内容**  
此处填写其他内容，没有可跳过

**Comment by TaoismDeepLake** [comment]
+1，使用最新token仍然如此，持续了一阵子了，我是v251

**Comment by Wkt-MJ** [comment]
me too

**Comment by HuangJune** [comment]
一样

**Comment by surpassSelf** [comment]
一样，用最新版本v2.5.2

**Comment by elin66alpha** [comment]
browserless账号密码 和 access token 都用不了了

**Comment by Wkt-MJ** [comment]
不知道啥情况api可以，用claude了，sese挺猛的感觉

**Comment by INSide-734** [comment]
请尝试自己搭建接入点
[接入点搭建教程](https://github.com/lss233/chatgpt-mirai-qq-bot/issues/978)

**Comment by Dansha-zzj** [comment]
同问题请问有人解决了吗

**Comment by lss233** [comment]
已修复
