### ISSUE TITLE
在会话初始化时，可以获取好友的生日，所在地等信息，以便让ChatGPT更好地了解好友。

### ISSUE THREAD

**Issue by iamyx123** [lss233/chatgpt-mirai-qq-bot#97]
在会话初始化时，可以获取好友的生日，所在地等信息，以便让ChatGPT更好地了解好友。

**Comment by lss233** [comment]
不考虑实现此功能，原因有二：
- Mirai 未提供此信息接口
- 收集此类信息侵犯用户隐私，OpenAI 可以看到用户发给机器人的信息。
