### ISSUE TITLE
[BUG] 错误代码502

### ISSUE THREAD

**Issue by xiaoz012007** [lss233/chatgpt-mirai-qq-bot#975]
**提交 issue 前，请先确认：**
- [ ] 我已看过 **FAQ**，此问题不在列表中
- [x ] 我已看过其他 issue，他们不能解决我的问题 
- [x ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
在qq中跟机器人对话后显示502 Bad Gateway

**运行环境:**  
- 操作系统：windwows10
- Docker：/
- 项目版本：2.5.2

**复现步骤**  
描述你是如何触发这个 BUG 的
1、运行本地服务器api.py
2、解压下载的windows一键安装包，并且按照要求配置qq号，chatglm相关设置
3、通过二维码登入qq后，用管理员号与测试qq聊天

**预期行为**  
正常情况下应该成功与模型进行交互，获得相应的回复

**截图**  
下图为config.cfg的配置
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/121837486/50449bb0-01e6-421f-bec1-246be8bc066f)
下图为服务器运行情况
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/121837486/c8e98a94-b3e5-49bc-a2c5-a4f19cd9818f)
下图为运行日志
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/121837486/2bb70ff8-5ea5-44fd-adc2-4579d1e8c550)
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/121837486/d8201a3c-57cb-442b-9a12-39eeb7c34173)

打扰大佬了，麻烦帮忙看一下是什么情况，谢谢大佬

**Comment by 123sghn** [comment]
你好，我也遇到这个问题了，请问该如何解决呢？我查看了以往的回答，应该是browserless_endpoint = "https://chatgpt-proxy.lss233.com/api/"这块的api网址需要变更，如何修改呢？

**Comment by lss233** [comment]
看下请求之后ChatGLM的日志吧

**Comment by xiaoz012007** [comment]
搞定了，谢谢大佬
