### ISSUE TITLE
关于在阿里云国内云服务器上一键部署项目（GO-CQHTTP 版）接入讯飞星火失败的问题

### ISSUE THREAD

**Issue by Twenru-zzh** [lss233/chatgpt-mirai-qq-bot#977]
提交 issue 前，我已确认相关issue无解决思路
能力水平：程序小白
我有认真阅读使用文档并在window本地成功部署接入讯飞星火的QQ机器人
由于一些后续集成想法和条件限制选择此种方法

操作系统：centos 7.9 64 位

以下是我在linux上部署失败的流程：
1. 在初始化的linux环境上用root身份在/目录安装软件curl，`curl --version`后显示版本号好相关信息【成功】
2. 切换到~目录后执行GO-CQHTTP 版的命令【成功】，后自动安装好docker以及docker-compose，录入QQ账号密码管理人等信息【成功】
3. 在跳出的1或2方式选择步骤，命令行ctrl+c取消，进入/目录，将docker hub镜像源更换为阿里云镜像源[https://30miwjob.mirror.aliyuncs.com](https://30miwjob.mirror.aliyuncs.com)，执行`systemctl daemon-reload`、`systemctl restart docker`命令后，用`docker pull hello-world`命令检查是否成功，返回结果:【不知是否成功】
```
Using default tag: latest
latest: Pulling from library/hello-world
Digest: sha256:2498fce14358aa50ead0cc6c19990fc6ff866ce72aeb5546e1d59caac3d0d60f
Status: Image is up to date for hello-world:latest
docker.io/library/hello-world:latest
```
4. 将chatgpt-qq/目录下config.cfg文件替换会Win10本地正常运行的对应文件内容后保存退出，以下是省略文本信息：
```python
[onebot]
qq=363····276
manager_qq=37····780
# 此处保持默认设置，无需修改
reverse_ws_port = 8554

[xinghuo]
[[xinghuo.accounts]]
# 必填
ssoSessionId = "ae0d0c41-4648-4287-9555-ea244dea497b"
# 保持固定即可，也可以自己抓包获取
【gttoken太长省略】
# 可以不填，如果经常出现验证码可以填下试试
# fd = "848897"

[presets]
# 切换预设的命令： 加载预设 猫娘
command = "加载预设 (\\w+)"

loaded_successful = "预设加载成功！"

[presets.keywords]
# 预设关键词 <-> 实际文件
"正常" = "presets/default.txt"
"猫娘" = "presets/catgirl.txt"
```
5. 由于没有自动跳出的选项，后执行`docker-compose pull` 或者`docker-compose up -d`命令查看现象：其中watchtower全部pull，gocqhttp部分pull，chatgpt不能pull【不知如何】，返回结果如下
`error pulling image configuration: download failed after attempts=6: dial tcp 104.18.123.25:443: i/o timeout`
6. 上述结果询问ai，告知是错误信息提示 Docker 拉取镜像时连接到容器镜像仓库的服务器超时了，可以尝试以下方法解决：
	1. 检查网络连接【检查正常】
	2. 更换镜像【前述更换】
	3. 添加代理【使用的本地网络且，Win10本地部署过程中并未实用代理】

以上是个人部署流程，不知道如何解决现有问题并继续后续流程，请求帮助

**Comment by INSide-734** [comment]
这个貌似只能更改仓库镜像或者在可以成功pull的机器下导出镜像然后传到服务器上

**Comment by lss233** [comment]
这是你网络的问题，和GO-CQHTTP、讯飞没什么关系。

你把错误提示放百度搜一下就可以找到解决方法了。    
https://www.baidu.com/s?ie=utf-8&wd=104.18.123.25
