### ISSUE TITLE
revChatGPT已经增加无需浏览器且客户端自动刷新session功能，希望可以跟进

### ISSUE THREAD

**Issue by ferretgeek** [lss233/chatgpt-mirai-qq-bot#98]
https://github.com/acheong08/ChatGPT最新的V1.1Proxy API已经增加配置代理就可以无需浏览器获取session功能，可以解决浏览器无限重启的问题

**Comment by lss233** [comment]
对于新出来的功能，我仍保持与 #90 一样的观点。
还有一个原因是我还没来得及搞

**Comment by lss233** [comment]
v1.5.4 支持

**Comment by lss233** [comment]
目前为止 Proxy 版本仍然是不可以状态。
![image](https://user-images.githubusercontent.com/8984680/218291205-59d40496-1891-42f3-bcd3-90dcd146b4fa.png)

**Comment by lss233** [comment]
v1.5.4 已发布。
