### ISSUE TITLE
[BUG] 请填写标题

### ISSUE THREAD

**Issue by shadowbox-cash** [lss233/chatgpt-mirai-qq-bot#980]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [x] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
运行test.py报错，显示OpenAI: Internal Server Error (code: 500)，但是access token已经读取成功
<img width="1490" alt="image" src="https://github.com/lss233/chatgpt-mirai-qq-bot/assets/71253948/f35eaf66-7f37-4b93-b3fc-dd5723a3bcd3">

**运行环境:**  
- 操作系统：MacOS
- Docker： 默认
- 项目版本：安装的最新版本的Windows-quickstart-go-cqhttp-refs.tags.v2.5.2.zip

**预期行为**  
关于Mac的搭建安装非常不详细，说让用户用windows包来安装，但是mac不能执行exe，所以只能斗胆python test.py，也不知道对不对，就报错了。。。

**截图**  
前面已经发了

**Comment by wxxsfxyzm** [comment]
mac为啥不用linux的安装脚本

**Comment by lss233** [comment]
已修复
