### ISSUE TITLE
[Feature] 可否让机器人预加载一个默认预设

### ISSUE THREAD

**Issue by liu2-3zhi** [lss233/chatgpt-mirai-qq-bot#989]
当用户没有设置预设时，系统会自动加载默认的预设。只有在用户设置了预设之后，系统才会加载其他预设。否则，默认都会加载默认预设。这样可以确保用户在没有进行任何操作的情况下，仍然能够使用系统的默认预设。例如，当用户输入一些无意义的内容，例如“1”时，chatgpt的回复内容是中文，而不是英文。这样可以确保用户在使用系统时能够获得最佳体验。

**Comment by lss233** [comment]
把你想要设置为默认预设的预设文件改名为 default.txt 即可

**Comment by liu2-3zhi** [comment]
建议在文档中写明，不然找都找不到。

**Comment by zhou123tie** [comment]
怎么实现的啊

**Comment by liu2-3zhi** [comment]
> 怎么实现的啊



> 把你想要设置为默认预设的预设文件改名为 default.txt 即可
