### ISSUE TITLE
启动时 Chatbot 报错

### ISSUE THREAD

**Issue by gebederry** [lss233/chatgpt-mirai-qq-bot#99]
请问大佬
[v1.6-RC3](https://github.com/lss233/chatgpt-mirai-qq-bot/releases/tag/v1.6-RC3)
**revChatGPT** 是 V2.0.3

![Xshell_AmO5UuVNpH](https://user-images.githubusercontent.com/3938353/218289278-135ad280-7828-43bc-a917-485e968733fa.png)

**Comment by lss233** [comment]
把报错的最后一句话拿去Google 一下吧。这个是你Python环境的问题，与项目无关

**Comment by gebederry** [comment]
> 把报错的最后一句话拿去Google 一下吧。这个是你Python环境的问题，与项目无关

感谢回复
好像是的，之前 pip3 就有 ssl 问题，安装时临时加了信任 host。改了好几次源都不成功。我再找找原因
