### ISSUE TITLE
修改有关WeChatBox文档

### ISSUE THREAD

**Issue by liu2-3zhi** [lss233/chatgpt-mirai-qq-bot#992]
使用docker部署的WeChatBox更新太麻烦。
可否修改安装文档，提供
docker-compose.yml

    version: '3.4'
    services:
      wechatbot:
        image: lcjqyml/wechatbot:latest
        restart: always
        working_dir: /app
        volumes:
          - ./config.yaml:/app/config.yaml
        - ./my-wechat-bot.memory-card.json:/app/my-wechat-bot.memory-card.json  #用于保存登录记录，防止封号
		  

和config.yaml

    chatbotProxy: "http://chatgpt-qq-chatgpt-1:8080"
    #自动通过好友请求
    autoAcceptFriendShip: "true"
    #自动通过群聊邀请
    autoAcceptRoomInvite: "false"
    #机器人私聊触发器，空则都触发
    privateChatTrigger: ""
    #机器人群聊触发器，空则@触发，否则：trigger 或 @bot trigger 触发
    groupChatTrigger: ""
    #群聊中回复时是否引用触发的消息
    responseQuote: "true"

**Comment by lss233** [comment]
你发错地方了吧

**Comment by liu2-3zhi** [comment]
没有啊，我指的是
![image](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/43312573/211efd39-2b4f-4517-b551-8fbb622d105e)

**Comment by liu2-3zhi** [comment]
没人理我,关闭了.
