### ISSUE TITLE
在aws上搭建服务器，复制一键部署指令时显示failed: Connection timed out.

### ISSUE THREAD

**Issue by ldmilu** [lss233/chatgpt-mirai-qq-bot#993]
[](url)
![截图20230626214825](https://github.com/lss233/chatgpt-mirai-qq-bot/assets/137718374/640ecd6f-7630-4519-b564-460f331c73cf)

**Comment by ldmilu** [comment]
怎么解决啊，我白痴的捣鼓了一晚上

**Comment by xuaowen** [comment]
我遇到了相同的问题
